SELECT
    SDI.FISCAL_YR
    , SDI.SLS_DOC_ID
    , SDI.SLS_DOC_ITM_ID
    
    , SD.SD_DOC_CTGY_CD
    , SD.TRANS_GRP_CD
    , SD.SLS_DOC_TYP_CD
    , SD.DELIV_BLK_CD
    , SD.BILL_BLK_CD
    , SD.CO_CD
    , SD.SALES_ORG_CD
    , SD.DISTR_CHAN_CD
    , SD.DIV_CD
    , SD.SHIP_COND_CD
    , SD.SAP_TRANS_CD
    
    , SD.CUST_PRCH_ORD_ID
    , SD.CUST_PRCH_ORD_TYP_CD
    , SD.CUST_PRCH_ORD_DT
    
    , SD.REQ_DELIV_DT
    , SD.COMPL_DELIV_IND
    
    , SD.SOLD_TO_CUST_ID
    
    , SDI.REJ_REAS_ID
    , SDI.DELIV_GRP_ID
    , SDI.BILL_BLK_CD
    
    , SDI.MATL_ID
    , SDI.MATL_GRP_ID
    , SDI.MATL_HIER_ID
    , SDI.BATCH_NBR
    
    , SDI.SLS_UOM_CD
    , SDI.SLS_UNIT_CUM_ORD_QTY
    , SDI.SLS_UNIT_CUM_REQ_DELIV_QTY
    , SDI.SLS_UNIT_CUM_CNFRM_QTY
    
    , SDI.FACILITY_ID
    , SDI.SHIP_RCVE_PT_CD
    , SDI.ROUTE_CD
    , SDI.RET_IND
    , SDI.SAP_TRANS_CD
    
    , SD.SRC_CRT_DT
    , SD.SRC_CRT_TM
    , SD.SRC_CRT_USR_ID
    
    , SDI.SRC_CRT_TS
    , SDI.SRC_CRT_USR_ID
    , SDI.SRC_UPD_DT
    
    , SDI.SLS_DOC_ITM_CTGY_CD
    , SDI.ITM_TYP_CD
    , SDI.ITM_RLVNT_DELIV_IND
    , SDI.ITM_RLVNT_BILL_ICD
    
    , SDI.ORIG_REQ_DELIV_DT
    , SDI.FRST_MATL_AVAIL_DT
    , SDI.FRST_PLN_GOODS_ISS_DT
    , SDI.FRST_REQ_DELIV_dT
    , SDI.FNL_ACCEPT_DT

FROM GDYR_BI_VWS.NAT_SLS_DOC_ITM_CURR SDI

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = SDI.MATL_ID
        AND M.PBU_NBR IN ('01')
    
    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = SDI.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_SLS_DOC_CURR SD
        ON SD.FISCAL_YR = SDI.FISCAL_YR
        AND SD.SLS_DOC_ID = SDI.SLS_DOC_ID
        AND SD.CO_CD IN ('N101', 'N102', 'N266')
        AND SD.SD_DOC_CTGY_CD = 'C'
        AND SD.CUST_PRCH_ORD_TYP_CD <> 'RO'
        
WHERE
    SDI.SRC_UPD_DT BETWEEN DATE '2009-01-01' AND DATE '2009-01-10'
