SELECT
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR

    , OOL.CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , BD.CMBN_ORD_IND

    , OOL.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME

    , OOL.FACILITY_ID
    , F.FACILITY_NAME

    , OOL.RPT_QTY_UNIT_MEAS_ID
    , SUM(OOL.RPT_OPEN_CNFRM_QTY) AS OPEN_CNFRM_QTY
    , SUM(OOL.RPT_UNCNFRM_QTY) AS UNCNFRM_QTY
    , SUM(OOL.RPT_BACK_ORDER_QTY) AS BACK_ORDER_QTY
    , SUM(OOL.RPT_DEFER_QTY) AS DEFER_QTY
    , SUM(OOL.RPT_WAIT_LIST_QTY) AS WAIT_LIST_QTY
    , SUM(OOL.RPT_OTHR_ORDER_QTY) AS OTHR_ORDER_QTY

FROM NA_VWS.OPEN_ORDER_SCHDLN OOL

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OOL.CUST_ID
        AND C.OWN_CUST_ID = '00A0006582'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OOL.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_cURR F
        ON F.FACILITY_ID = OOL.FACILITY_ID

    INNER JOIN NA_BI_VWS.SD_DOC_BUS_DATA_CURR BD
        ON BD.SD_DOC_ID = OOL.ORDER_ID
        AND BD.SD_DOC_ITM_ID = 0

WHERE
    OOL.EXP_DT = CAST('5555-12-31' AS DATE)
    AND (
        OOL.OPEN_CNFRM_QTY > 0
        OR OOL.UNCNFRM_QTY > 0
        OR OOL.BACK_ORDER_QTY > 0
        OR OOL.DEFER_QTY > 0
        OR OOL.WAIT_LIST_QTY > 0
    )
    AND BD.CMBN_ORD_IND = 'Y'

GROUP BY
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR

    , OOL.CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , BD.CMBN_ORD_IND

    , OOL.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME

    , OOL.FACILITY_ID
    , F.FACILITY_NAME

    , OOL.RPT_QTY_UNIT_MEAS_ID

ORDER BY
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
