SELECT
    ODC.SHIP_TO_CUST_ID
    , CUST.SHIP_TO_CUST_ID || ' - ' || CUST.CUST_NAME AS SHIP_TO_CUST
    , CUST.CITY_NAME
    , CUST.TERR_NAME
    , ODC.CUST_PO_NBR
    , ODC.ORDER_ID
    , ODC.ORDER_LINE_NBR
    , CAST(CASE
        WHEN OOL.OPEN_CNFRM_QTY > 0
            THEN 'Confirmed'
        WHEN OOL.UNCNFRM_QTY > 0
            THEN 'Unconfirmed'
        WHEN OOL.BACK_ORDER_QTY > 0
            THEN 'Back Ordered'
        END AS VARCHAR(25)) AS STATUS_CD
    , ZEROIFNULL(OOL.OPEN_CNFRM_QTY) + ZEROIFNULL(OOL.BACK_ORDER_QTY) + ZEROIFNULL(OOL.UNCNFRM_QTY) AS QUANTITY
    , QUANTITY * MATL.UNIT_WT AS GROSS_WT
    , MATL.PROD9_CD
    , MATL.MATL_ID_TRIM
    , MATL.MKT_CTGY_PROD_LINE_NBR || ' - ' || MATL.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE
    , MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , ODC.ORDER_DT
    , ODC.FRST_RDD
    , CASE
        WHEN OOL.OPEN_CNFRM_QTY > 0 
            THEN ODC.PLN_MATL_AVL_DT
        END AS PLN_MATL_AVAIL_DT
    , CASE
        WHEN OOL.OPEN_CNFRM_QTY > 0 
            THEN ODC.PLN_GOODS_ISS_DT
        END AS PLN_GOODS_ISS_DT

FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL ODC
        ON ODC.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND ODC.ORDER_ID = OOL.ORDER_ID
        AND ODC.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND ODC.SCHED_LINE_NBR = OOL.SCHED_LINE_NBR
        AND ODC.EXP_DT = DATE '5555-12-31'
        AND ODC.ORDER_CAT_ID = 'C'
        AND ODC.PO_TYPE_ID <> 'RO'
        AND ODC.ORDER_FISCAL_YR >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-2 AS CHAR(4))
        AND ODC.REJ_REAS_ID = ''
        AND ODC.ORDER_DT <= CURRENT_DATE-90

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID
        AND CUST.OWN_CUST_ID = '00A0006582'

WHERE
    OOL.OPEN_CNFRM_QTY > 0
    OR OOL.UNCNFRM_QTY > 0
    OR OOL.BACK_ORDER_QTY > 0

ORDER BY
    ODC.ORDER_ID
    , ODC.ORDER_LINE_NBR
    , STATUS_CD
