SELECT
    D.DELIV_FISCAL_YR
    , D.DELIV_ID

    , D.SHIP_TO_CUST_ID
    , D.CUST_NAME
    , D.CUST_LOC_NBR
    , D.OWN_CUST_ID
    , D.OWN_CUST_NAME

    , D.SAP_PLN_GOODS_MVT_DT
    , D.SAP_DELIV_DT

    , D.QTY_UOM
    , D.IN_PROC_QTY

FROM (

    SELECT
        DIP.DELIV_FISCAL_YR
        , DIP.DELIV_ID

        , DD.SHIP_TO_CUST_ID
        , C.CUST_NAME
        , REGEXP_SUBSTR(C.CUST_NAME, '[0-9]+', 1, 1, 'I') AS CUST_LOC_NBR
        , C.OWN_CUST_ID
        , C.OWN_CUST_NAME

        , DD.PLN_GOODS_MVT_DT AS SAP_PLN_GOODS_MVT_DT
        , DD.DELIV_DT AS SAP_DELIV_DT

        , DIP.RPT_QTY_UNIT_MEAS_ID AS QTY_UOM
        , SUM(DIP.RPT_QTY_TO_SHIP) AS IN_PROC_QTY

    FROM GDYR_VWS.DELIV_IN_PROC DIP

        INNER JOIN GDYR_VWS.DELIV_DOC DD
            ON DD.FISCAL_YR = DIP.DELIV_FISCAL_YR
            AND DD.DELIV_DOC_ID = DIP.DELIV_ID
            AND DD.ORIG_SYS_ID = DIP.ORIG_SYS_ID
            AND DD.EXP_DT = DIP.EXP_DT

        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
            ON C.SHIP_TO_CUST_ID = DD.SHIP_TO_CUST_ID
            AND C.OWN_CUST_ID = '00A0006582'

    WHERE
        DIP.ORIG_SYS_ID = 2
        AND DIP.EXP_DT = CAST('5555-12-31' AS DATE)
        AND DIP.INTRA_CMPNY_FLG = 'N'

    GROUP BY
        DIP.DELIV_FISCAL_YR
        , DIP.DELIV_ID
        , DD.SHIP_TO_CUST_ID
        , C.CUST_NAME
        , CUST_LOC_NBR
        , C.OWN_CUST_ID
        , C.OWN_CUST_NAME
        , DD.PLN_GOODS_MVT_DT
        , DD.DELIV_DT
        , DIP.RPT_QTY_UNIT_MEAS_ID

    ) D
