/*

SOLD TO PARTY / NAME
CITY
STATE
PO NBR
ORDER ID
ORDER LINE
STATUS -- SHIPPED / IN PROCESS
QTY - DELIVERY
TOTAL GROSS WT
CUST PART NBR
PRODUCT 9
MATL ID
PRODUCT LINE NAME
CATEGORY NAME
MATERIAL DESCRIPTION
ORDER CREATE DATE
FRDD
MAD DATE
PGI DATE - ACTUAL GOODS ISSUE / PLANNED GOODS MOVEMENT

*/

SELECT
    DDC.SHIP_TO_CUST_ID
    , CUST.SHIP_TO_CUST_ID || ' - ' || CUST.CUST_NAME AS SHIP_TO_CUST
    , CUST.CITY_NAME
    , CUST.TERR_NAME
    , ODC.CUST_PO_NBR
    , DDC.ORDER_ID
    , DDC.ORDER_LINE_NBR
    , CAST('Shipped' AS VARCHAR(25)) AS STATUS_CD
    , SUM(DDC.DELIV_QTY) AS QUANTITY
    , SUM(DDC.GROSS_WT) AS GROSS_WT
    , MATL.PROD9_CD
    , MATL.MATL_ID_TRIM
    , MATL.MKT_CTGY_PROD_LINE_NBR || ' - ' || MATL.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE
    , MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , ODC.ORDER_DT
    , ODC.FRST_RDD
    , DDC.DELIV_NOTE_CREA_DT AS MATL_AVAIL_DT
    , CASE
        WHEN DDC.GOODS_ISS_IND = 'Y'
            THEN DDC.ACTL_GOODS_ISS_DT
        ELSE DDC.PLN_GOODS_MVT_DT
        END AS CALC_GOODS_ISS_DT

FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = DDC.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID
        AND CUST.OWN_CUST_ID = '00A0006582'

    INNER JOIN NA_BI_VWS.ORDER_DETAIL_CURR ODC
        ON ODC.ORDER_FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND ODC.ORDER_ID = DDC.ORDER_ID
        AND ODC.ORDER_LINE_NBR = DDC.ORDER_LINE_NBR
        AND ODC.SCHED_LINE_NBR = 1
        AND ODC.PLN_DELIV_DT >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1) || '-01-01' AS DATE)
        AND ODC.ORDER_CAT_ID = 'C'
        AND ODC.PO_TYPE_ID <> 'R0'

WHERE
    DDC.GOODS_ISS_IND = 'Y'
    AND DDC.ACTL_GOODS_ISS_DT IS NOT NULL
    AND DDC.ACTL_GOODS_ISS_DT BETWEEN CURRENT_DATE-10 AND CURRENT_DATE
    AND DDC.DELIV_QTY > 0

GROUP BY
    DDC.SHIP_TO_CUST_ID
    , SHIP_TO_CUST
    , CUST.CITY_NAME
    , CUST.TERR_NAME
    , ODC.CUST_PO_NBR
    , DDC.ORDER_ID
    , DDC.ORDER_LINE_NBR
    , STATUS_CD
    , MATL.PROD9_CD
    , MATL.MATL_ID_TRIM
    , SALES_PROD_LINE
    , CATEGORY
    , MATL_DESCR
    , ODC.ORDER_DT
    , ODC.FRST_RDD
    , MATL_AVAIL_DT
    , CALC_GOODS_ISS_DT

UNION ALL

SELECT
    DDC.SHIP_TO_CUST_ID
    , CUST.SHIP_TO_CUST_ID || ' - ' || CUST.CUST_NAME AS SHIP_TO_CUST
    , CUST.CITY_NAME
    , CUST.TERR_NAME
    , ODC.CUST_PO_NBR
    , DDC.ORDER_ID
    , DDC.ORDER_LINE_NBR
    , CAST('In Process' AS VARCHAR(25)) AS STATUS_CD
    , SUM(DDC.DELIV_QTY) AS QUANTITY
    , SUM(DDC.GROSS_WT) AS GROSS_WT
    , MATL.PROD9_CD
    , MATL.MATL_ID_TRIM
    , MATL.MKT_CTGY_PROD_LINE_NBR || ' - ' || MATL.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE
    , MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , ODC.ORDER_DT
    , ODC.FRST_RDD
    , DDC.DELIV_NOTE_CREA_DT AS MATL_AVAIL_DT
    , CASE
        WHEN DDC.GOODS_ISS_IND = 'Y'
            THEN DDC.ACTL_GOODS_ISS_DT
        ELSE DDC.PLN_GOODS_MVT_DT
        END AS CALC_GOODS_ISS_DT

FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_VWS.DELIV_IN_PROC_CURR DIP
        ON DIP.DELIV_ID = DDC.DELIV_ID
        AND DIP.DELIV_LINE_NBR = DDC.DELIV_LINE_NBR
        AND DIP.ORDER_ID = DDC.ORDER_ID
        AND DIP.ORDER_LINE_NBR = DDC.ORDER_LINE_NBR
        AND DIP.INTRA_CMPNY_FLG = 'N'
        AND DIP.QTY_TO_SHIP > 0

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = DDC.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID
        AND CUST.OWN_CUST_ID = '00A0006582'

    INNER JOIN NA_BI_VWS.ORDER_DETAIL_CURR ODC
        ON ODC.ORDER_FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND ODC.ORDER_ID = DDC.ORDER_ID
        AND ODC.ORDER_LINE_NBR = DDC.ORDER_LINE_NBR
        AND ODC.SCHED_LINE_NBR = 1
        AND ODC.PLN_DELIV_DT >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1) || '-01-01' AS DATE)
        AND ODC.ORDER_CAT_ID = 'C'
        AND ODC.PO_TYPE_ID <> 'R0'

WHERE
    DDC.GOODS_ISS_IND = 'N'

GROUP BY
    DDC.SHIP_TO_CUST_ID
    , SHIP_TO_CUST
    , CUST.CITY_NAME
    , CUST.TERR_NAME
    , ODC.CUST_PO_NBR
    , DDC.ORDER_ID
    , DDC.ORDER_LINE_NBR
    , STATUS_CD
    , MATL.PROD9_CD
    , MATL.MATL_ID_TRIM
    , SALES_PROD_LINE
    , CATEGORY
    , MATL_DESCR
    , ODC.ORDER_DT
    , ODC.FRST_RDD
    , MATL_AVAIL_DT
    , CALC_GOODS_ISS_DT

UNION ALL

SELECT
    ODC.SHIP_TO_CUST_ID
    , CUST.SHIP_TO_CUST_ID || ' - ' || CUST.CUST_NAME AS SHIP_TO_CUST
    , CUST.CITY_NAME
    , CUST.TERR_NAME
    , ODC.CUST_PO_NBR
    , ODC.ORDER_ID
    , ODC.ORDER_LINE_NBR
    , CAST(CASE
        WHEN OOL.OPEN_CNFRM_QTY > 0
            THEN 'Confirmed'
        WHEN OOL.UNCNFRM_QTY > 0
            THEN 'Unconfirmed'
        WHEN OOL.BACK_ORDER_QTY > 0
            THEN 'Back Ordered'
        END AS VARCHAR(25)) AS STATUS_CD
    , ZEROIFNULL(OOL.OPEN_CNFRM_QTY) + ZEROIFNULL(OOL.BACK_ORDER_QTY) + ZEROIFNULL(OOL.UNCNFRM_QTY) AS QUANTITY
    , QUANTITY * MATL.UNIT_WT AS GROSS_WT
    , MATL.PROD9_CD
    , MATL.MATL_ID_TRIM
    , MATL.MKT_CTGY_PROD_LINE_NBR || ' - ' || MATL.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE
    , MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , ODC.ORDER_DT
    , ODC.FRST_RDD
    , CASE
        WHEN OOL.OPEN_CNFRM_QTY > 0 
            THEN ODC.PLN_MATL_AVL_DT
        END AS PLN_MATL_AVAIL_DT
    , CASE
        WHEN OOL.OPEN_CNFRM_QTY > 0 
            THEN ODC.PLN_GOODS_ISS_DT
        END AS PLN_GOODS_ISS_DT

FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL ODC
        ON ODC.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND ODC.ORDER_ID = OOL.ORDER_ID
        AND ODC.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND ODC.SCHED_LINE_NBR = OOL.SCHED_LINE_NBR
        AND ODC.EXP_DT = DATE '5555-12-31'
        AND ODC.ORDER_CAT_ID = 'C'
        AND ODC.PO_TYPE_ID <> 'RO'
        AND ODC.ORDER_FISCAL_YR >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-2 AS CHAR(4))
        AND ODC.REJ_REAS_ID = ''

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID
        AND CUST.OWN_CUST_ID = '00A0006582'
