SELECT
    C.SALES_ORG_CD
    , C.DISTR_CHAN_CD
    , (CASE
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0000505' THEN 'AA'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0005642' THEN 'AA'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0000510' THEN 'SW'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0000518' THEN 'AT'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0000600' THEN 'WC'			
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0000608' THEN 'HI'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0000869' THEN 'DA'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0000356' THEN 'DA'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0001863' THEN 'HB'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0005702' THEN 'HB'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0001866' THEN 'BO'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0001867' THEN 'CA'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0001870' THEN 'GA'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0001876' THEN 'AP'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0001877' THEN 'AG'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0001890' THEN 'DT'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0005621' THEN 'SA'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00B0430577' THEN 'TR'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00B0431356' THEN 'GM'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00B0431754' THEN 'MI'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00B0431757' THEN 'LA'
    	ELSE C.CUST_GRP_ID
    	END ) AS CUST_GRP_CD
    , C.DISTR_CHAN_SECT_CD
    , C.TIRE_CUST_TYP_CD
    , M.MATL_ID
    , M.PBU_NBR
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.MKT_CTGY_MKT_GRP_NBR
    , M.MKT_CTGY_MKT_GRP_NAME
    , M.MKT_CTGY_PROD_GRP_NBR
    , M.MKT_CTGY_PROD_GRP_NAME
    , M.MKT_CTGY_PROD_LINE_NBR
    , M.MKT_CTGY_PROD_LINE_NAME
    , M.SUPER_BRAND_ID
    , M.SUPER_BRAND_NAME
    , M.ASSOC_BRAND_ID
    , M.ASSOC_BRAND_NAME
    , M.BRAND_ID
    , M.BRAND_NAME
    , M.PROD9_CD
    , M.TIRE_SZ_TEXT
    , M.RIM_DIAM_INCHES
    , M.HMC_TXT
    , SPP.HMC_AGG_LVL_CD
    , SA.BILL_REF_MTH_DT
    , SUM(ZEROIFNULL(SA.SLS_QTY)) AS SLS_QTY

FROM NA_VWS.SLS_AGG SA

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = SA.MATL_NO
        AND M.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
        AND M.MATL_TYPE_ID IN ('ACCT', 'PCTL')

    INNER JOIN NA_BI_VWS.SLS_PLN_PRODUCTS SPP
        ON SPP.MATL_ID = SA.MATL_NO

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = SA.LEGACY_SHIP_TO_CUST_NO

WHERE
    SA.BILL_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-5 || '-01-01' AS DATE)
        AND CURRENT_DATE-1
    AND SA.SLS_QTY <> 0

GROUP BY
    C.SALES_ORG_CD
    , C.DISTR_CHAN_CD
    , CUST_GRP_CD
    , C.DISTR_CHAN_SECT_CD
    , C.TIRE_CUST_TYP_CD
    , M.MATL_ID
    , M.PBU_NBR
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.MKT_CTGY_MKT_GRP_NBR
    , M.MKT_CTGY_MKT_GRP_NAME
    , M.MKT_CTGY_PROD_GRP_NBR
    , M.MKT_CTGY_PROD_GRP_NAME
    , M.MKT_CTGY_PROD_LINE_NBR
    , M.MKT_CTGY_PROD_LINE_NAME
    , M.SUPER_BRAND_ID
    , M.SUPER_BRAND_NAME
    , M.ASSOC_BRAND_ID
    , M.ASSOC_BRAND_NAME
    , M.BRAND_ID
    , M.BRAND_NAME
    , M.PROD9_CD
    , M.TIRE_SZ_TEXT
    , M.RIM_DIAM_INCHES
    , M.HMC_TXT
    , SPP.HMC_AGG_LVL_CD
    , SA.BILL_REF_MTH_DT

UNION ALL

SELECT
    C.SALES_ORG_CD
    , C.DISTR_CHAN_CD
    , (CASE
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0000505' THEN 'AA'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0005642' THEN 'AA'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0000510' THEN 'SW'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0000518' THEN 'AT'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0000600' THEN 'WC'			
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0000608' THEN 'HI'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0000869' THEN 'DA'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0000356' THEN 'DA'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0001863' THEN 'HB'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0005702' THEN 'HB'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0001866' THEN 'BO'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0001867' THEN 'CA'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0001870' THEN 'GA'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0001876' THEN 'AP'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0001877' THEN 'AG'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0001890' THEN 'DT'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00A0005621' THEN 'SA'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00B0430577' THEN 'TR'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00B0431356' THEN 'GM'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00B0431754' THEN 'MI'
    	WHEN M.PBU_NBR = '04' AND C.OWN_CUST_ID = '00B0431757' THEN 'LA'
    	ELSE C.CUST_GRP_ID
    	END ) AS CUST_GRP_CD
    , C.DISTR_CHAN_SECT_CD
    , C.TIRE_CUST_TYP_CD
    , M.MATL_ID
    , M.PBU_NBR
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.MKT_CTGY_MKT_GRP_NBR
    , M.MKT_CTGY_MKT_GRP_NAME
    , M.MKT_CTGY_PROD_GRP_NBR
    , M.MKT_CTGY_PROD_GRP_NAME
    , M.MKT_CTGY_PROD_LINE_NBR
    , M.MKT_CTGY_PROD_LINE_NAME
    , M.SUPER_BRAND_ID
    , M.SUPER_BRAND_NAME
    , M.ASSOC_BRAND_ID
    , M.ASSOC_BRAND_NAME
    , M.BRAND_ID
    , M.BRAND_NAME
    , M.PROD9_CD
    , M.TIRE_SZ_TEXT
    , M.RIM_DIAM_INCHES
    , M.HMC_TXT
    , SPP.HMC_AGG_LVL_CD
    , DDC.ACTL_GOODS_ISS_DT - (EXTRACT(DAY FROM DDC.ACTL_GOODS_ISS_DT)-1) AS AGID_MTH
    , SUM(ZEROIFNULL(DDC.DELIV_QTY)) AS DELIV_QTY

FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = DDC.MATL_ID
        AND M.PBU_NBR ='04'
        -- IN ('01', '03', '04', '05', '07', '08', '09')
        AND M.MATL_TYPE_ID IN ('ACCT', 'PCTL')

    INNER JOIN NA_BI_VWS.SLS_PLN_PRODUCTS SPP
        ON SPP.MATL_ID = DDC.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID
        AND C.SALES_ORG_CD = 'N304'
        AND C.DISTR_CHAN_CD = '41'
        AND C.CUST_GRP_ID IN ('79', 'AA', 'AT', 'DA', 'SW')

WHERE
    DDC.GOODS_ISS_IND = 'Y'
    AND DDC.ACTL_GOODS_ISS_DT IS NOT NULL
    AND DDC.DELIV_QTY <> 0
    AND DDC.ACTL_GOODS_ISS_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-5 || '-01-01' AS DATE)
        AND CURRENT_DATE-1

GROUP BY
    C.SALES_ORG_CD
    , C.DISTR_CHAN_CD
    , CUST_GRP_CD
    , C.DISTR_CHAN_SECT_CD
    , C.TIRE_CUST_TYP_CD
    , M.MATL_ID
    , M.PBU_NBR
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.MKT_CTGY_MKT_GRP_NBR
    , M.MKT_CTGY_MKT_GRP_NAME
    , M.MKT_CTGY_PROD_GRP_NBR
    , M.MKT_CTGY_PROD_GRP_NAME
    , M.MKT_CTGY_PROD_LINE_NBR
    , M.MKT_CTGY_PROD_LINE_NAME
    , M.SUPER_BRAND_ID
    , M.SUPER_BRAND_NAME
    , M.ASSOC_BRAND_ID
    , M.ASSOC_BRAND_NAME
    , M.BRAND_ID
    , M.BRAND_NAME
    , M.PROD9_CD
    , M.TIRE_SZ_TEXT
    , M.RIM_DIAM_INCHES
    , M.HMC_TXT
    , SPP.HMC_AGG_LVL_CD
    , AGID_MTH