SELECT
    ORD.MATL_ID
    , ORD.FACILITY_ID
    , ORD.PROD_ALLCT_DETERM_PROC_ID
    , ORD.MATL_STA_ID
    , ORD.SAL_IND
    , ORD.PAL_IND
    
    , ORD.BACK_ORDER_QTY
    , ORD.OPEN_CNFRM_QTY
    , ZEROIFNULL(DD.DELIV_QTY) AS SHIP_QTY

FROM (

SELECT
    OD.MATL_ID
    , OD.FACILITY_ID
    
    , OD.PROD_ALLCT_DETERM_PROC_ID
    
    , M.MATL_STA_ID
    , M.SAL_IND
    , COALESCE(PAL.PAL_IND, 'N') AS PAL_IND
    
    , SUM(ZEROIFNULL(OOL.OPEN_CNFRM_QTY)) AS OPEN_CNFRM_QTY
    , SUM(ZEROIFNULL(OOL.BACK_ORDER_QTY)) AS BACK_ORDER_QTY
    
FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND OD.ORDER_ID = OOL.ORDER_ID
        AND OD.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = 1
        AND OD.EXP_DT = DATE '5555-12-31'
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.RO_PO_TYPE_IND = 'N'
        AND OD.FRST_RDD < ADD_MONTHS(CURRENT_DATE-1, -6)

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = OD.MATL_ID
        AND M.PBU_NBR = '01'
        AND M.EXT_MATL_GRP_ID = 'TIRE'

    LEFT OUTER JOIN GDYR_BI_VWS.NAT_MATL_PAL_CURR PAL
        ON PAL.MATL_ID = m.MATL_ID

WHERE
    OOL.BACK_ORDER_QTY > 0 OR ool.open_cnfrm_qty > 0

GROUP BY
    OD.MATL_ID
    , OD.FACILITY_ID
    , OD.PROD_ALLCT_DETERM_PROC_ID
    , M.MATL_STA_ID
    , M.SAL_IND
    , COALESCE(PAL.PAL_IND, 'N')
    
    ) ORD
    
    LEFT OUTER JOIN (
        SELECT
            D.MATL_ID
            , D.DELIV_LINE_FACILITY_ID
            , SUM(D.DELIV_QTY) AS DELIV_QTY
        
        FROM NA_BI_vWS.DELIVERY_DETAIL_CURR D

            INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
                ON OD.ORDER_FISCAL_YR = D.ORDER_FISCAL_YR
                AND OD.ORDER_ID = D.ORDER_ID
                AND OD.ORDER_LINE_NBR = D.ORDER_LINE_NBR
                AND OD.SCHED_LINE_NBR = 1
                AND OD.EXP_DT = DATE '5555-12-31'
                AND OD.ORDER_CAT_ID = 'C'
                AND OD.RO_PO_TYPE_IND = 'N'
                AND OD.ORDER_DT >= (CURRENT_DATE-1) - (EXTRACT(DAY FROM CURRENT_DATE-1) - 1)

            INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
                ON M.MATL_ID = D.MATL_ID
                AND M.PBU_NBR = '01'
                AND M.EXT_MATL_GRP_ID = 'TIRE'
        
        WHERE
            D.DELIV_NOTE_CREA_DT >= (CURRENT_DATE-1) - (EXTRACT(DAY FROM CURRENT_DATE-1) - 1)
            AND D.DELIV_QTY > 0
            AND D.DELIV_CAT_ID = 'J'
            AND D.SALES_ORG_CD NOT IN ('N306', 'N316', 'N326')
            AND D.DISTR_CHAN_CD <> '81'
            
        GROUP BY
            D.MATL_ID
            , D.DELIV_LINE_FACILITY_ID
    ) DD
        ON DD.MATL_ID = ORD.MATL_ID
        AND DD.DELIV_LINE_FACILITY_ID = ORD.FACILITY_ID