SELECT
    Q.PBU_NBR
    , CASE
        WHEN Q.DAY_DATE > CURRENT_DATE
            THEN CURRENT_DATE
        ELSE Q.DAY_DATE
        END AS REF_DT
    , Q.BEGIN_MONTH
    , CAST(BEGIN_MONTH AS FORMAT 'MMM') (CHAR(3)) AS MONTH_NAME
    , Q.CAL_YR AS BEGIN_YEAR
    , SUM(CASE
        WHEN Q.FRDD_IN_MONTH_IND = 'Y'
            THEN Q.BACK_ORDER_QTY
        ELSE 0
        END) AS BO_IN_MONTH_QTY
    , SUM(CASE
        WHEN Q.FRDD_IN_MONTH_IND = 'Y'
            THEN Q.UNCNFRM_QTY
        ELSE 0
        END) AS UC_IN_MONTH_QTY
    , SUM(CASE
        WHEN Q.FRDD_IN_MONTH_IND = 'Y' AND Q.DYS_BTWN_PAST_FRDD > 0
            THEN Q.OPEN_CNFRM_QTY
        ELSE 0
        END) AS PAST_DUE_IN_MONTH_QTY
    , SUM(Q.BACK_ORDER_QTY) AS TOT_BO_QTY
    , SUM(Q.UNCNFRM_QTY) AS TOT_UC_QTY
    , SUM(Q.OPEN_CNFRM_QTY) AS TOT_OPEN_CNFRM_QTY
    , SUM(CASE
        WHEN Q.DYS_BTWN_PAST_FRDD > 0
            THEN Q.OPEN_CNFRM_QTY
        ELSE 0
        END) AS PAST_DUE_QTY
    , Q.TIRE_CUST_TYP_CD

FROM (

SELECT
    CAL.DAY_DATE
    , CAL.MONTH_DT AS BEGIN_MONTH
    , CAL.CAL_YR
    , ADD_MONTHS(CAL.MONTH_DT, 1) -1 AS END_MONTH
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR
    , OD.SCHED_LINE_NBR
    , OD.FRST_RDD
    , CASE
        WHEN OD.FRST_RDD BETWEEN BEGIN_MONTH AND END_MONTH
            THEN 'Y'
        ELSE 'N'
        END AS FRDD_IN_MONTH_IND
    , CUST.TIRE_CUST_TYP_CD
    , MATL.PBU_NBR
    , CASE 
        WHEN CAL.DAY_DATE = ADD_MONTHS(((CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1)) + 1, 1) - 1
            THEN CASE 
                WHEN OD.FRST_RDD < CURRENT_DATE
                    THEN OD.PLN_DELIV_DT - OD.FRST_RDD
                ELSE 0
                END
        ELSE CASE 
            WHEN OD.FRST_RDD < CAL.DAY_DATE
                THEN OD.PLN_DELIV_DT - OD.FRST_RDD
            ELSE 0
            END
        END AS DYS_BTWN_PAST_FRDD
    , OOL.OPEN_CNFRM_QTY
    , OOL.UNCNFRM_QTY
    , OOL.BACK_ORDER_QTY

FROM GDYR_BI_VWS.GDYR_CAL CAL

    INNER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN_SNP OOL
        ON OOL.REF_DT = CAL.MONTH_DT

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_ID = OOL.ORDER_ID
        AND OD.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = OOL.SCHED_LINE_NBR
        AND CAL.DAY_DATE BETWEEN OD.EFF_DT AND OD.EXP_DT
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.RO_PO_TYPE_IND = 'N'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID
        AND (
            CUST.SALES_ORG_CD IN ('N301', 'N311', 'N302', 'N312', 'N322', 'N336') 
            OR (
                CUST.SALES_ORG_CD IN ('N303', 'N313', 'N323') 
                AND CUST.DISTR_CHAN_CD IN ('30', '31', '32')
                )
            )
        
    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = OD.MATL_ID
        AND MATL.PBU_NBR IN ('01', '03')
        AND MATL.SUPER_BRAND_ID IN ('01', '02', '03', '05')
        AND MATL.EXT_MATL_GRP_ID = 'TIRE'

WHERE
    CAL.DAY_DATE BETWEEN DATE '2013-10-01' AND ADD_MONTHS(CURRENT_DATE-1, 1)
    AND CAL.CAL_LAST_DAY_MO_IND = 'Y'

    ) Q

GROUP BY
    Q.PBU_NBR
    , REF_DT
    , Q.BEGIN_MONTH
    , MONTH_NAME
    , Q.CAL_YR
    , Q.TIRE_CUST_TYP_CD

ORDER BY
    REF_DT
    , Q.PBU_NBR
    , Q.TIRE_CUST_TYP_CD


