SELECT 
    CAST('Delivery' AS VARCHAR(10)) AS QUERY_TYP
    , DELIV.ACTL_GOODS_ISS_DT AS BUS_DT
	, DELIV.SALES_ORG_CD
	, MA.MKT_GRP_NBR || ' - ' || MA.MKT_GRP_NAME AS MKT_GRP
    , CASE
        WHEN CH.OWN_CUST_ID = '00A0006677'
            THEN 'Wingfoot'
        ELSE 'Other'
        END AS WINGFOOT_IND
	, SUM(RPT_DELIV_QTY) AS RPT_QTY
    
FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DELIV
INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MA 
    ON DELIV.MATL_ID = MA.MATL_ID
INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CH
    ON CH.SHIP_TO_CUST_ID = DELIV.SHIP_TO_CUST_ID
WHERE 
    DELIV.SALES_ORG_CD = 'N301'
	AND MA.PBU_NBR IN ('03')
	AND MA.MKT_AREA_NBR IN ('04')
	AND MA.MKT_GRP_NBR IN ('0018', '0112', '0113', '0019')
	AND MA.EXT_MATL_GRP_ID IN ('TIRE', 'TREADRBR', '2PIECE')
	AND DELIV.ACTL_GOODS_ISS_DT > CAST((
			SELECT PERD_END_DT
			FROM GDYR_BI_VWS.TIME_PERD_DESC_SYSPR
			WHERE PERD_DESC = 'Prior Month'
			) AS DATE)

GROUP BY
    QUERY_TYP
    , DELIV.ACTL_GOODS_ISS_DT
    , DELIV.SALES_ORG_CD
    , MKT_GRP
    , WINGFOOT_IND

UNION ALL

SELECT
    CAST('Order' AS VARCHAR(10)) AS QUERY_TYP
    , ODC.ORDER_DT
    , ODC.SALES_ORG_CD
    , MATL.MKT_GRP_NBR || ' - ' || MATL.MKT_GRP_NAME AS MKT_GRP
    , CASE
        WHEN CUST.OWN_CUST_ID = '00A0006677'
            THEN 'Wingfoot'
        ELSE 'Other'
        END AS WINGFOOT_IND
	, SUM(ODC.RPT_ORDER_QTY) AS RPT_ORDER_QTY

FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID
        AND MATL.PBU_NBR = '03'
        AND MATL.MKT_AREA_NBR = '04'
        AND MATL.MKT_GRP_NBR IN ('0018', '0112', '0113', '0019')
        AND MATL.EXT_MATL_GRP_ID IN ('TIRE', 'TREADRBR', '2PIECE')
    
    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID

WHERE
    ODC.SALES_ORG_CD = 'N301'
    AND ODC.ORDER_DT > CAST((
			SELECT PERD_END_DT
			FROM GDYR_BI_VWS.TIME_PERD_DESC_SYSPR
			WHERE PERD_DESC = 'Prior Month'
			) AS DATE)

GROUP BY
    QUERY_TYP
    , ODC.ORDER_DT
    , ODC.SALES_ORG_CD
    , MKT_GRP
    , WINGFOOT_IND


            