SELECT
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    , OOL.SCHED_LINE_NBR
    
    , ODC.SHIP_TO_CUST_ID
    , CUST.CUST_NAME AS SHIP_TO_CUST_NAME
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    , CUST.TIRE_CUST_TYP_CD
    
    , CUST.PRIM_SHIP_FACILITY_ID
    , ODC.FACILITY_ID
    , ODC.SHIP_PT_ID
    
    , ODC.MATL_ID
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , MATL.PBU_NBR
    , MATL.PBU_NAME
    , MATL.MKT_CTGY_MKT_AREA_NBR AS CATEGORY_CD
    , MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY_NM
    , MATL.MKT_CTGY_MKT_GRP_NBR AS SEGMENT_CD
    , MATL.MKT_CTGY_MKT_GRP_NAME AS SEGMENT_NM
    , MATL.MKT_CTGY_PROD_GRP_NBR AS PROD_GRP_CD
    , MATL.MKT_CTGY_PROD_GRP_NAME AS PROD_GRP_NM
    , MATL.MKT_CTGY_PROD_LINE_NBR AS SALES_PROD_LINE_CD
    , MATL.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE_NAME
    , CASE
        WHEN MATL.PBU_NBR = '01'
            THEN MATL.MKT_CTGY_PROD_GRP_NAME
        ELSE MATL.TIERS
        END AS TIER
    , MATL.MATL_PRTY
    , MATL.EXT_MATL_GRP_ID
    
    , ODC.ORDER_DT
    , ODC.ORDER_LN_CRT_DT
    , ODC.ORDER_LN_CRT_TM
    
    , FD.PLN_MATL_AVL_DT AS MAD_FIRST_DATE
    , FD.PLN_GOODS_ISS_DT AS PGI_FIRST_DATE
    , FD.PLN_DELIV_DT AS FIRST_DATE
    
    , ODC.PLN_MATL_AVL_DT
    , ODC.PLN_GOODS_ISS_DT
    , ODC.PLN_DELIV_DT
    
    , ODC.CUST_RDD AS ORDD
    , ODC.FRST_MATL_AVL_DT AS FRDD_FMAD
    , ODC.FRST_PLN_GOODS_ISS_DT AS FRDD_FPGI
    , ODC.FRST_RDD AS FRDD
    
    , ODC.FC_MATL_AVL_DT AS FCDD_FMAD
    , ODC.FC_PLN_GOODS_ISS_DT AS FCDD_fPGI
    , ODC.FRST_PROM_DELIV_DT AS FCDD
    
    , OOL.CREDIT_HOLD_FLG
    , ODC.ORDER_DELIV_BLK_CD
    , ODC.DELIV_BLK_CD
    , ODC.ORDER_CREATOR
    , ODC.SHIP_COND_ID
    , ODC.DELIV_PRTY_ID
    , ODC.DELIV_GRP_CD
    , ODC.ROUTE_ID
    , ODC.SPCL_PROC_ID
    , ODC.CUST_GRP2_CD

    , CASE
        WHEN OOL.OPEN_CNFRM_QTY > 0
            THEN 'Open Confirmed'
        WHEN OOL.UNCNFRM_QTY > 0
            THEN 'Unconfirmed'
        WHEN OOL.BACK_ORDER_QTY > 0
            THEN 'Back Ordered'
        WHEN OOL.DEFER_QTY > 0
            THEN 'Deferred'
        WHEN OOL.WAIT_LIST_QTY > 0
            THEN 'Wait List'
        END AS STATUS_CD
    , ZEROIFNULL(OOL.OPEN_CNFRM_QTY) + ZEROIFNULL(OOL.UNCNFRM_QTY) + ZEROIFNULL(OOL.BACK_ORDER_QTY) + ZEROIFNULL(OOL.WAIT_LIST_QTY) + ZEROIFNULL(OOL.DEFER_QTY) AS OPEN_QTY

FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL ODC
        ON ODC.ORDER_ID = OOL.ORDER_ID
        AND ODC.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND ODC.SCHED_LINE_NBR = OOL.SCHED_LINE_NBR
        AND ODC.EXP_DT = DATE '5555-12-31'
        AND ODC.ORDER_CAT_ID = 'C'
        AND ODC.RO_PO_TYPE_IND = 'N'
        AND ODC.CUST_GRP_ID = '3R'
        AND ODC.PLN_DELIV_DT > CURRENT_DATE+14
        AND ODC.REJ_REAS_ID = ''

    INNER JOIN NA_BI_VWS.ORDER_DETAIL FD
        ON FD.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND FD.ORDER_ID = OOL.ORDER_ID
        AND FD.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND FD.SCHED_LINE_NBR = 1
        AND FD.EXP_DT = DATE '5555-12-31'
        AND FD.ORDER_CAT_ID = 'C'
        AND FD.RO_PO_TYPE_IND = 'N'
        AND FD.REJ_REAS_ID = ''
        AND FD.CUST_GRP_ID = '3R'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID
        AND CUST.CUST_GRP_ID = '3R'

WHERE
    OPEN_QTY > 0
