SELECT
    INV.BUS_DT,
    INV.MATL_ID,
    INV.FACILITY_ID,
    INV.TOT_QTY,
    INV.BLOCKED_STK_QTY,
    INV.QUAL_INSP_QTY,
    ZEROIFNULL( OTD.ORIGINAL_ORDER_QTY ) AS ORIGINAL_ORDER_QTY,
    ZEROIFNULL( OTD.CURRENT_ORDER_QTY ) AS CURRENT_ORDER_QTY,
    ZEROIFNULL( OTD.FRDD_RELEASE_LATE_QTY ) AS FRDD_RELEASE_LATE_QTY,
    ZEROIFNULL( OTD.FRDD_RELEASE_ONTIME_QTY ) AS FRDD_RELEASE_ONTIME_QTY,
    ZEROIFNULL( OTD.CANCEL_QTY ) AS CANCEL_QTY,
    ZEROIFNULL( OTD.FRDD_DELIVER_LATE_QTY ) AS FRDD_DELIVER_LATE_QTY,
    ZEROIFNULL( OTD.FRDD_DELIVER_ONTIME_QTY ) AS FRDD_DELIVER_ONTIME_QTY,

    ZEROIFNULL( OTD.FRDD_RETURN_HIT_QTY ) AS FRDD_RETURN_HIT_QTY,
    ZEROIFNULL( OTD.FRDD_CLAIM_HIT_QTY ) AS FRDD_CLAIM_HIT_QTY,
    ZEROIFNULL( OTD.FRDD_FREIGHT_PLCY_HIT_QTY ) AS FRDD_FREIGHT_POLICY_HIT_QTY,
    ZEROIFNULL( OTD.FRDD_PHYS_LOG_HIT_QTY ) AS FRDD_PHYS_LOG_HIT_QTY,
    ZEROIFNULL( OTD.FRDD_MAN_BLK_HIT_QTY ) AS FRDD_MAN_BLK_HIT_QTY,
    ZEROIFNULL( OTD.FRDD_CREDIT_HIT_QTY ) AS FRDD_CREDIT_HOLD_HIT_QTY,
    ZEROIFNULL( OTD.FRDD_NO_STOCK_HIT_QTY ) AS FRDD_NO_STOCK_HIT_QTY,
    ZEROIFNULL( OTD.FRDD_CANCEL_HIT_QTY ) AS FRDD_CANCEL_HIT_QTY,
    ZEROIFNULL( OTD.FRDD_CUST_GEN_HIT_QTY ) AS FRDD_CUST_GEN_HIT_QTY,
    ZEROIFNULL( OTD.FRDD_MAN_REL_CUST_GEN_HIT_QTY ) AS FRDD_MAN_REL_CUST_GEN_HIT_QTY,
    ZEROIFNULL( OTD.FRDD_MAN_REL_HIT_QTY ) FRDD_MAN_REL_HIT_QTY,
    ZEROIFNULL( OTD.FRDD_OTHER_HIT_QTY ) AS FRDD_OTHER_HIT_QTY,

    ZEROIFNULL( OTD.FRDD_ONTIME_QTY ) AS FRDD_ONTIME_QTY,
    ZEROIFNULL( OTD.FRDD_LATE_QTY ) AS FRDD_LATE_QTY

FROM (

        SELECT
            BI.FACILITY_ID,
            BI.MATL_ID,
            BI.DAY_DT AS BUS_DT,
            SUM( BI.BLOCKED_STK_QTY ) AS BLOCKED_STK_QTY,
            SUM( BI.QUAL_INSP_QTY ) AS QUAL_INSP_QTY,
            SUM( BI.TOT_QTY ) AS TOT_QTY

        FROM GDYR_BI_VWS.BATCH_INV BI

        WHERE
            BI.SRC_SYS_ID = 2
            AND BI.DAY_DT BETWEEN CAST( SUBSTR( CAST( ADD_MONTHS( CURRENT_DATE, -24 ) AS CHAR(10) ), 1, 7 ) || '-01' AS DATE )  AND ( CURRENT_DATE - 1 )
            AND bi.matl_id LIKE '%00193043'

        GROUP BY
            BI.FACILITY_ID,
            BI.MATL_ID,
            BI.DAY_DT

    ) INV

    LEFT OUTER JOIN (

            SELECT
                POL.MATL_ID,
                POL.SHIP_FACILITY_ID AS FACILITY_ID,
                -- POL.ORDER_DT,
                POL.REQ_DELIV_DT AS FRDD,
                -- POL.CMPL_DT AS FRDD_CMPL_DT,

                SUM( ZEROIFNULL( POL.ORIG_ORD_QTY ) ) AS ORIGINAL_ORDER_QTY,
                SUM( ZEROIFNULL( POL.CURR_ORD_QTY ) ) AS CURRENT_ORDER_QTY,
                SUM( ZEROIFNULL( POL.REL_LATE_QTY ) ) AS FRDD_RELEASE_LATE_QTY,
                SUM( ZEROIFNULL( POL.REL_ONTIME_QTY ) ) AS FRDD_RELEASE_ONTIME_QTY,
                SUM( ZEROIFNULL( POL.CANCEL_QTY ) ) AS CANCEL_QTY,
                SUM( ZEROIFNULL( POL.DELIV_LATE_QTY ) ) AS FRDD_DELIVER_LATE_QTY,
                SUM( ZEROIFNULL( POL.DELIV_ONTIME_QTY ) ) AS FRDD_DELIVER_ONTIME_QTY,

                SUM( ZEROIFNULL( POL.NE_HIT_RT_QTY ) ) AS FRDD_RETURN_HIT_QTY,
                SUM( ZEROIFNULL( POL.NE_HIT_CL_QTY ) ) AS FRDD_CLAIM_HIT_QTY,
                SUM( ZEROIFNULL( POL.OT_HIT_FP_QTY ) ) AS FRDD_FREIGHT_PLCY_HIT_QTY,
                SUM( ZEROIFNULL( POL.OT_HIT_CARR_PICKUP_QTY ) ) + SUM( ZEROIFNULL( POL.OT_HIT_WI_QTY ) ) AS FRDD_PHYS_LOG_HIT_QTY,
                SUM( ZEROIFNULL( POL.OT_HIT_MB_QTY ) ) AS FRDD_MAN_BLK_HIT_QTY,
                SUM( ZEROIFNULL( POL.OT_HIT_CH_QTY ) ) AS FRDD_CREDIT_HIT_QTY,
                SUM( ZEROIFNULL( POL.IF_HIT_NS_QTY ) ) AS FRDD_NO_STOCK_HIT_QTY,
                SUM( ZEROIFNULL( POL.IF_HIT_CO_QTY ) ) AS FRDD_CANCEL_HIT_QTY,
                SUM( ZEROIFNULL( POL.OT_HIT_CG_QTY ) ) AS FRDD_CUST_GEN_HIT_QTY,
                SUM( ZEROIFNULL( POL.OT_HIT_CG_99_QTY ) ) AS FRDD_MAN_REL_CUST_GEN_HIT_QTY,
                SUM( ZEROIFNULL( POL.OT_HIT_99_QTY ) ) AS FRDD_MAN_REL_HIT_QTY,
                SUM( ZEROIFNULL( POL.OT_HIT_LO_QTY ) ) AS FRDD_OTHER_HIT_QTY,

                SUM( ZEROIFNULL( POL.CURR_ORD_QTY ) ) - SUM( ZEROIFNULL( POL.PRFCT_ORD_HIT_QTY ) ) AS FRDD_ONTIME_QTY,
                SUM( ZEROIFNULL( POL.PRFCT_ORD_HIT_QTY ) ) AS FRDD_LATE_QTY

            FROM NA_BI_VWS.PRFCT_ORD_LINE POL

            WHERE
                POL.CMPL_IND = 1
                AND POL.CMPL_DT BETWEEN CAST( SUBSTR( CAST( ADD_MONTHS( CURRENT_DATE, -24 ) AS CHAR(10) ), 1, 7 ) || '-01' AS DATE )  AND ( CURRENT_DATE - 1 )
                AND POL.REQ_DELIV_DT < CURRENT_DATE
                AND POL.PRFCT_ORD_HIT_DESC <> 'FRDD Hit - Error'

            GROUP BY
                POL.MATL_ID,
                POL.SHIP_FACILITY_ID,
                -- POL.ORDER_DT,
                -- POL.CMPL_DT,
                POL.REQ_DELIV_DT

            ) OTD
        ON OTD.FACILITY_ID = INV.FACILITY_ID
        AND OTD.MATL_ID = INV.MATL_ID
        AND OTD.FRDD = INV.BUS_DT