SELECT
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    CAST( CASE
        WHEN ORDD IS NULL
            THEN 'ORDD Missing'
    END AS VARCHAR(40) ) AS ORDD_TEST,
    CAST( CASE
        WHEN FRDD < ORDD
            THEN 'FRDD < ORDD'
    END AS VARCHAR(40) ) AS FRDD_ORDD_TEST,
    
    CAST( CASE
        WHEN FRDD < FRDD_FMAD
            THEN 'FRDD < FMAD for FRDD'
    END AS VARCHAR(40) ) AS FRDD_FMAD_FRDD_TEST,
    CAST( CASE
        WHEN FRDD < FRDD_FPGI
            THEN 'FRDD < FPGI for FRDD'
    END AS VARCHAR(40) ) AS FRDD_FPGI_FRDD_TEST,
    
    CAST( CASE
        WHEN FRDD < FRDD_FMAD
            THEN 'FRDD < FMAD for FRDD'
    END AS VARCHAR(40) ) AS FRDD_FMAD_FRDD_TEST,
    CAST( CASE
        WHEN FRDD < FRDD_FPGI
            THEN 'FRDD < FPGI for FRDD'
    END AS VARCHAR(40) ) AS FRDD_FPGI_FRDD_TEST,
    CAST( CASE
        WHEN FCDD < FRDD
            THEN 'FCDD < FRDD'
    END AS VARCHAR(40) ) AS FCDD_FRDD_TEST,
    
    ODC.SHIP_TO_CUST_ID,
    
    ODC.SALES_ORG_CD,
    ODC.DISTR_CHAN_CD,
    ODC.CUST_GRP_ID,

    ODC.CO_CD,
    ODC.DIV_CD,
    
    ODC.ORDER_DT,
    
    ODC.CUST_RDD AS ORDD,
    
    ODC.FRST_RDD AS FRDD, 
    ODC.FRST_MATL_AVL_DT AS FRDD_FMAD,
    ODC.FRST_PLN_GOODS_ISS_DT AS FRDD_FPGI,
    ODC.FC_MATL_AVL_DT AS FCDD_FMAD,
    ODC.FC_PLN_GOODS_ISS_DT AS FCDD_FPGI,
    ODC.FRST_PROM_DELIV_DT AS FCDD,
    
    ODC.PLN_TRANSP_PLN_DT,
    ODC.PLN_MATL_AVL_DT,
    ODC.PLN_GOODS_ISS_DT,
    ODC.PLN_DELIV_DT,
    
    ODC.CANCEL_DT,
    
    ODC.ORDER_CAT_ID,
    ODC.ORDER_TYPE_ID,
    
    ODC.PO_TYPE_ID,
    
    ODC.DELIV_BLK_CD,
    
    ODC.FACILITY_ID,
    ODC.SHIP_PT_ID,
    
    ODC.ITEM_CAT_ID,
    ODC.MATL_ID,
    
    ODC.SHIP_COND_ID,
    
    ODC.REJ_REAS_ID,
    ODC.REJ_REAS_DESC,

    ODC.DELIV_PRTY_ID,
    ODC.ROUTE_ID,
    ODC.DELIV_GRP_CD,
    ODC.SPCL_PROC_ID,
    ODC.CUST_GRP2_CD
    
FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC

    INNER JOIN NA_BI_VWS.OPEN_ORDER_ORDLN_CURR OOL
        ON OOL.ORDER_ID = ODC.ORDER_ID
        AND OOL.ORDER_LINE_NBR = ODC.ORDER_LINE_NBR
        AND ( OOL.OPEN_CNFRM_QTY > 0 OR OOL.UNCNFRM_QTY > 0 OR OOL.BACK_ORDER_QTY > 0 )

WHERE
    ODC.ORDER_CAT_ID = 'C'
    AND ODC.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' ) 
    AND ODC.PO_TYPE_ID <> 'RO'
    AND ODC.ORDER_DT >= ( CURRENT_DATE - 7 ) 
    AND (
        ORDD_TEST IS NOT NULL
        OR FRDD_ORDD_TEST IS NOT NULL
        OR FRDD_FMAD_FRDD_TEST IS NOT NULL
        OR FRDD_FPGI_FRDD_TEST IS NOT NULL
        OR FCDD_FRDD_TEST IS NOT NULL
        OR FRDD_FMAD_FRDD_TEST IS NOT NULL
        OR FRDD_FPGI_FRDD_TEST IS NOT NULL
    )

GROUP BY
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    ORDD_TEST,
    FRDD_ORDD_TEST,
    FRDD_FMAD_FRDD_TEST,
    FRDD_FPGI_FRDD_TEST,
    FRDD_FMAD_FRDD_TEST,
    FRDD_FPGI_FRDD_TEST,
    FCDD_FRDD_TEST,
    ODC.SHIP_TO_CUST_ID,
    ODC.SALES_ORG_CD,
    ODC.DISTR_CHAN_CD,
    ODC.CUST_GRP_ID,
    ODC.CO_CD,
    ODC.DIV_CD,
    ODC.ORDER_DT,
    ODC.CUST_RDD,
    ODC.FRST_RDD ,
    ODC.FRST_MATL_AVL_DT,
    ODC.FRST_PLN_GOODS_ISS_DT,
    ODC.FC_MATL_AVL_DT,
    ODC.FC_PLN_GOODS_ISS_DT,
    ODC.FRST_PROM_DELIV_DT,
    ODC.PLN_TRANSP_PLN_DT,
    ODC.PLN_MATL_AVL_DT,
    ODC.PLN_GOODS_ISS_DT,
    ODC.PLN_DELIV_DT,
    ODC.CANCEL_DT,
    ODC.ORDER_CAT_ID,
    ODC.ORDER_TYPE_ID,
    ODC.PO_TYPE_ID,
    ODC.DELIV_BLK_CD,
    ODC.FACILITY_ID,
    ODC.SHIP_PT_ID,
    ODC.ITEM_CAT_ID,
    ODC.MATL_ID,
    ODC.SHIP_COND_ID,
    ODC.REJ_REAS_ID,
    ODC.REJ_REAS_DESC,
    ODC.DELIV_PRTY_ID,
    ODC.ROUTE_ID,
    ODC.DELIV_GRP_CD,
    ODC.SPCL_PROC_ID,
    ODC.CUST_GRP2_CD

ORDER BY
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR
