SELECT
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    ODC.SCHED_LINE_NBR,
    
    ODC.ORDER_CAT_ID,
    ODC.ORDER_TYPE_ID,
    
    ODC.SHIP_TO_CUST_ID,
    CUST.CUST_NAME AS SHIP_TO_CUST_NAME,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,
    ODC.SALES_ORG_CD,
    ODC.DISTR_CHAN_CD,
    ODC.CUST_GRP_ID,
    ODC.CUST_GRP2_CD,
    ODC.PO_TYPE_ID,
    ODC.DELIV_PRTY_ID,
    ODC.SHIP_COND_ID,
    ODC.ROUTE_ID,
    ODC.DELIV_GRP_CD,
    NULLIF( ODC.SPCL_PROC_ID, '' )  AS SPCL_PROC_ID,
    
    ODC.MATL_ID,
    MATL.DESCR,
    MATL.PBU_NBR,
    MATL.PBU_NAME,
    
    ODC.FACILITY_ID,
    FAC.XTND_NAME AS FACILITY_NAME,
    
    ODC.CANCEL_DT,
    ODC.REJ_REAS_ID,
    ODC.REJ_REAS_DESC,
    
    ODC.QTY_UNIT_MEAS_ID AS QTY_UOM,
    ODC.ORDER_QTY,
    ODC.CNFRM_QTY,
    
    ODC.WT_UNITS_MEAS_ID AS WT_UOM,
    ODC.NET_WT,
    ODC.GROSS_WT,
    
    ODC.VOL_UNIT_MEAS_ID AS VOL_UOM,
    ODC.VOL,

    ODC.ORDER_DT,
    ODC.CUST_RDD AS ORDD,
    ODC.FRST_MATL_AVL_DT AS FRDD_FMAD,
    ODC.FRST_PLN_GOODS_ISS_DT AS FRDD_FPGI,
    ODC.FRST_RDD AS FRDD,
    
    ODC.FC_MATL_AVL_DT AS FCDD_FMAD,
    ODC.FC_PLN_GOODS_ISS_DT AS FCDD_FPGI,
    ODC.FRST_PROM_DELIV_DT AS FCDD
    
FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC

    INNER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOSL
        ON OOSL.ORDER_ID = ODC.ORDER_ID
        AND OOSL.ORDER_LINE_NBR = ODC.ORDER_LINE_NBR
        AND OOSL.SCHED_LINE_NBR = ODC.SCHED_LINE_NBR

    LEFT OUTER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID  = ODC.SHIP_TO_CUST_ID

    LEFT OUTER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID

    LEFT OUTER JOIN GDYR_BI_VWS.NAT_FACILITY_HIER_EN_CURR FAC
        ON FAC.FACILITY_ID = ODC.FACILITY_ID

WHERE
    ODC.ORDER_CAT_ID = 'C'
    AND ODC.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
    AND ODC.PO_TYPE_ID <> 'RO'
    -- AND ORDD > FRDD

ORDER BY
    ODC.ORDER_DT DESC,
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    ODC.SCHED_LINE_NBR