SELECT
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    
    ODC.MATL_ID,
    
    ODC.SHIP_TO_CUST_ID,
    ODC.SALES_ORG_CD,
    ODC.DISTR_CHAN_CD,
    ODC.CO_CD,
    ODC.DIV_CD,
    ODC.CUST_GRP_ID,
    ODC.CUST_GRP2_CD,
    
    ODC.FACILITY_ID,
    ODC.SHIP_PT_ID,
    
    ODC.ORDER_CAT_ID,
    ODC.ORDER_TYPE_ID,
    MAX( ODC.CANCEL_IND ) AS CANCEL_IND,
    MAX( ODC.CANCEL_DT ) AS CANCEL_DT,
    MAX( ODC.RETURN_IND ) AS RETURN_IND,
    CASE
        WHEN OOL.ORDER_ID IS NOT NULL
            THEN 'Open Order'
        ELSE 'Closed'
    END AS OPEN_ORDER_IND,
    ODC.PO_TYPE_ID,
    ODC.DELIV_BLK_CD,
    ODC.ORDER_CREATOR,
    ODC.SHIP_COND_ID,
    ODC.DELIV_PRTY_ID,
    ODC.ROUTE_ID,
    ODC.DELIV_GRP_CD,
    ODC.SPCL_PROC_ID,
    
    ODC.ORDER_DT,
    ODC.FRST_RDD AS FRDD,
    CASE
        WHEN CAST( COALESCE( ODC.CUST_RDD, ODC.FRST_RDD ) - ODC.ORDER_DT AS INTEGER ) < 14
            THEN CAST( ODC.ORDER_DT + 14 AS DATE )
        ELSE COALESCE( ODC.CUST_RDD, ODC.FRST_RDD )
    END AS FOUNTAIN_RDD,
    
    ODC.ORDER_DT - ( EXTRACT( DAY FROM ODC.ORDER_DT ) - 1 ) AS ORDER_MONTH,
    ODC.FRST_RDD - ( EXTRACT( DAY FROM ODC.FRST_RDD ) - 1 ) AS FRDD_MONTH,
    FOUNTAIN_RDD - ( EXTRACT( DAY FROM FOUNTAIN_RDD ) - 1 ) AS FOUNTAIN_RDD_MONTH,

    MAX( ODC.ORDER_QTY ) AS ORDER_QTY,
    SUM( ODC.CNFRM_QTY ) AS CNFRM_QTY,
    OOL.OPEN_CNFRM_QTY,
    OOL.BACK_ORDER_QTY,
    OOL.UNCNFRM_QTY,
    OOL.DEFER_QTY,
    OOL.IN_PROC_QTY,
    ODC.QTY_UNIT_MEAS_ID
    
FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC
        
    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID
        AND CUST.OWN_CUST_ID = '00A0009337'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID
        AND MATL.EXT_MATL_GRP_ID = 'TIRE'
        
    LEFT OUTER JOIN NA_BI_VWS.OPEN_ORDER_ORDLN_CURR OOL
        ON OOL.ORDER_ID = ODC.ORDER_ID
        AND OOL.ORDER_LINE_NBR = ODC.ORDER_LINE_NBR
        
WHERE
    ODC.ORDER_DT BETWEEN CAST( SUBSTR( CAST( ADD_MONTHS(CURRENT_DATE, -6) AS CHAR(10) ),1, 7 ) ||'-01' AS DATE ) AND ( CURRENT_DATE - 1 )
    AND ODC.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
    AND ODC.ORDER_CAT_ID = 'C'
    AND ODC.PO_TYPE_ID NOT IN ( 'RO' )
    
GROUP BY
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    
    ODC.MATL_ID,
    
    ODC.SHIP_TO_CUST_ID,
    ODC.SALES_ORG_CD,
    ODC.DISTR_CHAN_CD,
    ODC.CO_CD,
    ODC.DIV_CD,
    ODC.CUST_GRP_ID,
    ODC.CUST_GRP2_CD,
    
    ODC.FACILITY_ID,
    ODC.SHIP_PT_ID,
    
    ODC.ORDER_CAT_ID,
    ODC.ORDER_TYPE_ID,
    OPEN_ORDER_IND,
    ODC.PO_TYPE_ID,
    ODC.DELIV_BLK_CD,
    ODC.ORDER_CREATOR,
    ODC.SHIP_COND_ID,
    ODC.DELIV_PRTY_ID,
    ODC.ROUTE_ID,
    ODC.DELIV_GRP_CD,
    ODC.SPCL_PROC_ID,
    
    ODC.ORDER_DT,
    ODC.FRST_RDD,
    FOUNTAIN_RDD,
    
    ORDER_MONTH,
    FRDD_MONTH,
    FOUNTAIN_RDD_MONTH,

    OOL.OPEN_CNFRM_QTY,
    OOL.BACK_ORDER_QTY,
    OOL.UNCNFRM_QTY,
    OOL.DEFER_QTY,
    OOL.IN_PROC_QTY,
    ODC.QTY_UNIT_MEAS_ID

ORDER BY
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR
;

SELECT
    DDC.FISCAL_YR,
    DDC.DELIV_ID,
    DDC.DELIV_LINE_NBR,
    
    DDC.ORDER_ID,
    DDC.ORDER_LINE_NBR,
    
    DDC.SHIP_TO_CUST_ID,
    
    DDC.MATL_ID,
    
    DDC.FACILITY_ID,
    DDC.DELIV_LINE_FACILITY_ID,
    DDC.SHIP_PT_ID,
    DDC.SHIP_FACILITY_ID,
    
    DDC.DELIV_NOTE_CREA_DT,
    DDC.DELIV_LINE_CREA_DT,
    DDC.LOAD_DT,
    DDC.PICK_DT,
    DDC.ACTL_GOODS_ISS_DT,
    DDC.DELIV_DT,
    
    DDC.DELIV_TYPE_ID,
    DDC.DELIV_CAT_ID,
    DDC.DELIV_PRTY_ID,
    DDC.BILL_LADING_ID,
    DDC.SHIP_COND_ID,
    DDC.RTG_ID,
    DDC.TERMS_ID,
    DDC.UNLD_PT_CD,
    DDC.SPCL_PROC_ID,
    DDC.RPT_FRT_PLCY_CD AS CUST_GRP2_CD,
    DDC.SRC_CRT_USR_ID,
    
    DDC.MATL_ID,
    
    DDC.DELIV_QTY,
    DDC.QTY_UNIT_MEAS_ID AS QTY_UOM,
    DDC.VOL,
    DDC.VOL_UNIT_MEAS_ID,
    DDC.GROSS_WT,
    DDC.NET_WT,
    DDC.WT_UNIT_MEAS_ID
    
FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID
        AND CUST.OWN_CUST_ID = '00A0009337'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = DDC.MATL_ID
        AND MATL.EXT_MATL_GRP_ID = 'TIRE'

WHERE
    DDC.DELIV_DT BETWEEN CAST( SUBSTR( CAST( ADD_MONTHS(CURRENT_DATE, -6) AS CHAR(10) ),1, 7 ) ||'-01' AS DATE ) AND ( CURRENT_DATE - 1 )
    AND DDC.DELIV_QTY > 0
    
ORDER BY
    DDC.FISCAL_YR,
    DDC.DELIV_ID,
    DDC.DELIV_LINE_NBR
    
;

SELECT
    *
FROM GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR
WHERE
    OWN_CUST_ID = '00A0009337'
ORDER BY
    SHIP_TO_CUST_ID
;

SELECT
    *
FROM GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR
WHERE
    MATL_ID IN ( 
        SELECT
            ODC.MATL_ID
        FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC
        
            INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
                ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID
                AND CUST.OWN_CUST_ID = '00A0009337'
                
        WHERE
            ODC.ORDER_DT BETWEEN CAST( SUBSTR( CAST( ADD_MONTHS(CURRENT_DATE, -6) AS CHAR(10) ),1, 7 ) ||'-01' AS DATE ) AND ( CURRENT_DATE - 1 )
        GROUP BY
            ODC.MATL_ID
            
        UNION
        
        SELECT
            DDC.MATL_ID
        FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC
        
            INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
                ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID
                AND CUST.OWN_CUST_ID = '00A0009337'
                
        WHERE
            DDC.DELIV_DT BETWEEN CAST( SUBSTR( CAST( ADD_MONTHS(CURRENT_DATE, -6) AS CHAR(10) ),1, 7 ) ||'-01' AS DATE ) AND ( CURRENT_DATE - 1 )
        GROUP BY
            DDC.MATL_ID
            )
ORDER BY
    MATL_ID
;
