SELECT
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    ODC.SCHED_LINE_NBR,

    ODC.SHIP_TO_CUST_ID,
    CUST.CUST_NAME AS SHIP_TO_CUST_NAME,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,
    ODC.CUST_GRP_ID,
    ODC.CUST_GRP2_CD,
    ODC.CO_CD,
    ODC.DIV_CD,
    ODC.SALES_ORG_CD,
    ODC.DISTR_CHAN_CD,

    ODC.MATL_ID,
    MATL.DESCR,
    MATL.PBU_NBR,
    MATL.PBU_NAME,
    MATL.EXT_MATL_GRP_ID,

    ODC.FACILITY_ID,
    FAC.FACILITY_TYPE_ID,
    FAC.FACILITY_TYPE_DESC,
    FAC.XTND_NAME AS FACILITY_NAME,
    ODC.SHIP_PT_ID,

    ODC.PO_TYPE_ID,
    ODC.ORDER_CAT_ID,
    ODC.ORDER_TYPE_ID,
    ODC.DELIV_BLK_CD,
    ODC.DELIV_PRTY_ID,
    ODC.SPCL_PROC_ID,
    ODC.DELIV_GRP_CD,
    ODC.ROUTE_ID,
    ODC.REJ_REAS_ID,
    ODC.REJ_REAS_DESC,

    ODC.CANCEL_DT,
    ODC.CANCEL_IND,
    ODC.RETURN_IND,

    ODC.ORDER_DT,
    ODC.PLN_TRANSP_PLN_DT,
    ODC.PLN_MATL_AVL_DT,
    ODC.PLN_LOAD_DT,
    ODC.PLN_GOODS_ISS_DT,
    CAST( ( ODC.PLN_GOODS_ISS_DT - ( EXTRACT( DAY FROM ODC.PLN_GOODS_ISS_DT ) - 1 ) ) AS DATE ) AS PLN_GOODS_ISS_MTH,
    ODC.PLN_DELIV_DT,

    ODC.CUST_RDD AS ORDD,
    ODC.FRST_MATL_AVL_DT AS FRDD_FMAD,
    ODC.FRST_PLN_GOODS_ISS_DT AS FRDD_FPGI,
    ODC.FRST_RDD AS FRDD,

    ODC.FC_MATL_AVL_DT AS FCDD_FMAD,
    ODC.FC_PLN_GOODS_ISS_DT AS FCDD_FPGI,
    ODC.FRST_PROM_DELIV_DT AS FCDD,

    OOSL.OPEN_CNFRM_QTY,

    ODC.QTY_UNIT_MEAS_ID AS QTY_UOM,
    ODC.NET_WT,
    ODC.GROSS_WT,
    ODC.WT_UNITS_MEAS_ID AS WT_UOM,
    ODC.VOL,
    ODC.VOL_UNIT_MEAS_ID AS VOL_UOM

FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID
        AND MATL.PBU_NBR IN ( '01', '03' )

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID
        AND CUST.CUST_GRP_ID <> '3R'

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_HIER_EN_CURR FAC
        ON FAC.FACILITY_ID = ODC.FACILITY_ID

    LEFT OUTER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOSL
        ON OOSL.ORDER_ID = ODC.ORDER_ID
        AND OOSL.ORDER_LINE_NBR = ODC.ORDER_LINE_NBR
        AND OOSL.SCHED_LINE_NBR = ODC.SCHED_LINE_NBR
        AND OOSL.OPEN_CNFRM_QTY > 0

WHERE
    ODC.ORDER_CAT_ID = 'C'
    AND ODC.CUST_GRP_ID NOT IN ( '3R' )
    AND ODC.PO_TYPE_ID NOT IN ( 'RO' )
    AND ODC.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
    AND ODC.DELIV_BLK_CD NOT IN ( '' )

ORDER BY
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    ODC.SCHED_LINE_NBR