SELECT
    OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , OD.MATL_ID
    , MATL.DESCR
    , MATL.PBU_NBR
    , MATL.PBU_NAME

    , OD.DELIV_PRTY_ID AS ORDER_DELIV_PRTY
    , CUST.DELIV_PRTY_CD AS CUST_DELIV_PRTY
    , OD.SHIP_TO_CUST_ID
    , CUST.CUST_NAME
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME

    , OD.ORDER_DT
    , OD.ORDER_LN_CRT_DT

FROM NA_BI_VWS.ORDER_DETAIL OD

    INNER JOIN NA_BI_VWS.OPEN_ORDER_ORDLN_CURR OOL
        ON OOL.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = OD.ORDER_ID
        AND OOL.ORDER_LINE_NBR = OD.ORDER_LINE_NBR

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = OD.MATL_ID
        AND MATL.PBU_NBR = '01'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

WHERE
    OD.EXP_DT = CAST('5555-12-31' AS DATE)
    AND OD.ORDER_CAT_ID = 'C'
    AND OD.RO_PO_TYPE_IND = 'N'
    AND OD.SCHED_LINE_NBR = 1

    AND OD.DELIV_PRTY_ID <> CUST.DELIV_PRTY_CD
    AND NOT (OD.DELIV_PRTY_ID IN ('12', '45') AND OD.CUST_GRP2_CD = 'TLB')

ORDER BY
    OD.ORDER_DT DESC
    , OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR
