SELECT
    CAL.MONTH_DT AS ITM_CRT_MTH_DT
    , CAL.WEEK_OF_MONTH AS ITM_CRT_WK_OF_MTH
    --, CAST(OD.FRST_RDD - OD.ORDER_LN_CRT_DT AS INTEGER) AS ITM_CRT_TO_FRDD_DAYS
    , CAST(CASE
        WHEN CAST(OD.FRST_RDD - OD.ORDER_LN_CRT_DT AS INTEGER) / 7 < 0
            THEN '0'
        WHEN CAST(OD.FRST_RDD - OD.ORDER_LN_CRT_DT AS INTEGER) / 7 BETWEEN 0 AND 4
            THEN CAST(CAST(OD.FRST_RDD - OD.ORDER_LN_CRT_DT AS INTEGER) / 7 AS CHAR(1))
        ELSE '5+'
        END || ' Weeks between FRDD and Item Crt Dt' AS VARCHAR(255)) AS ITM_CRT_TO_FRDD_WKS
    , CASE
        WHEN RDD_CAL.MONTH_DT <= CAL.MONTH_DT
            THEN 'RDD and Itm Crt Same Month'
        ELSE 'RDD and Itm Crt Different Months'
        END AS TEST_ITM_MTH_VS_RDD_MTH
/*    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    , CUST.SALES_ORG_CD
    , CUST.SALES_ORG_NAME*/
    , MATL.PBU_NBR
    , MATL.PBU_NAME
    , MATL.MKT_CTGY_MKT_AREA_NBR
    , MATL.MKT_CTGY_MKT_AREA_NAME
    , MATL.MKT_CTGY_PROD_LINE_NBR
    , MATL.MKT_CTGY_PROD_LINE_NAME
    , MATL.MATL_NO_8
    , MATL.DESCR
/*    , FAC.FACILITY_ID
    , FAC.FACILITY_NAME*/

    , OD.QTY_UNIT_MEAS_ID
    , SUM(OD.ORDER_QTY) AS ORDER_QTY
    , SUM(ZEROIFNULL(DDC.DELIV_QTY)) AS DELIV_QTY
    , SUM(CASE
        WHEN OD.REJ_REAS_ID = ''
            THEN OD.ORDER_QTY
        ELSE ZEROIFNULL(DDC.DELIV_QTY)
        END) AS NET_ORDER_QTY

FROM NA_BI_VWS.ORDER_DETAIL OD

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE = OD.ORDER_LN_CRT_DT

    INNER JOIN GDYR_BI_vWS.GDYR_CAL RDD_CAL
        ON RDD_CAL.DAY_DATE = OD.FRST_RDD

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FAC
        ON FAC.FACILITY_ID = OD.FACILITY_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID
        AND CUST.SALES_ORG_CD IN ('N301', 'N311', 'N321')

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = OD.MATL_ID
        AND MATL.PBU_NBR = '01'

    LEFT OUTER JOIN (
            SELECT
                DD.ORDER_FISCAL_YR
                , DD.ORDER_ID
                , DD.ORDER_LINE_NBR
                , SUM(DD.DELIV_QTY) AS DELIV_QTY
            FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DD
            WHERE
                DD.SD_DOC_CTGY_CD = 'C'
                AND DD.DELIV_CAT_ID = 'J'
                AND DD.DELIV_NOTE_CREA_DT >= CAST('2014-01-01' AS DATE)
            GROUP BY
                DD.ORDER_FISCAL_YR
                , DD.ORDER_ID
                , DD.ORDER_LINE_NBR
            ) DDC
        ON DDC.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
        AND DDC.ORDER_ID = OD.ORDER_ID
        AND DDC.ORDER_LINE_NBR = OD.ORDER_LINE_NBR

WHERE
    OD.EXP_DT = CAST('5555-12-31' AS DATE)
    AND OD.ORDER_LN_CRT_DT >= CAST('2014-01-01' AS DATE)
    AND OD.ORDER_CAT_ID = 'C'
    AND OD.RO_PO_TYPE_IND = 'N'
    AND OD.SCHED_LINE_NBR = 1

GROUP BY
    ITM_CRT_MTH_DT
    , ITM_CRT_WK_OF_MTH
    --, ITM_CRT_TO_FRDD_DAYS
    , ITM_CRT_TO_FRDD_WKS
    , TEST_ITM_MTH_VS_RDD_MTH
/*    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    , CUST.SALES_ORG_CD
    , CUST.SALES_ORG_NAME*/
    , MATL.PBU_NBR
    , MATL.PBU_NAME
    , MATL.MKT_CTGY_MKT_AREA_NBR
    , MATL.MKT_CTGY_MKT_AREA_NAME
    , MATL.MKT_CTGY_PROD_LINE_NBR
    , MATL.MKT_CTGY_PROD_LINE_NAME
    , MATL.MATL_NO_8
    , MATL.DESCR
/*    , FAC.FACILITY_ID
    , FAC.FACILITY_NAME*/

    , OD.QTY_UNIT_MEAS_ID
