SELECT
    DDC.FISCAL_YR
    , DDC.DELIV_ID
    , DDC.DELIV_LINE_NBR

    , DDC.BILL_LADING_ID

    , DDC.ORDER_FISCAL_YR
    , DDC.ORDER_ID
    , DDC.ORDER_LINE_NBR

    , ROW_NUMBER() OVER (PARTITION BY DDC.ORDER_FISCAL_YR, DDC.ORDER_ID, DDC.ORDER_LINE_NBR ORDER BY DDC.ACTL_GOODS_ISS_DT, DDC.DELIV_ID) AS ORD_DLV_SEQ_ID

    , OD.CUST_PO_NBR

    , OD.CO_CD
    , CO.NAME AS CO_NAME
    , DDC.SALES_ORG_CD
    , CUST.SALES_ORG_NAME
    , DDC.DISTR_CHAN_CD
    , CUST.DISTR_CHAN_NAME
    , DDC.DIV_CD
    , DDC.CUST_GRP_ID
    , CUST.CUST_GRP_NAME

    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    , DDC.SHIP_TO_CUST_ID
    , CUST.CUST_NAME AS SHIP_TO_CUST_NAME
    , CUST.POSTAL_CD
    , CUST.DISTRICT_NAME
    , CUST.TERR_NAME
    , CUST.CITY_NAME
    , CUST.CNTRY_NAME_CD

    , CASE
        WHEN DDC.DELIV_LINE_FACILITY_ID = CUST.PRIM_SHIP_FACILITY_ID
            THEN 'P'
        WHEN DDC.DELIV_LINE_FACILITY_ID LIKE 'N5%'
            THEN 'F'
        ELSE 'O'
        END AS TEST_PRIM_SHIP_FACILITY
    , CUST.PRIM_SHIP_FACILITY_ID
    , DDC.DELIV_LINE_FACILITY_ID AS FACILITY_ID
    , FAC.NAME AS FACILITY_NANE
    , DDC.SHIP_PT_ID

    , DDC.MATL_ID
    , MATL.PROD9_CD
    , DDC.CUST_PART_NBR
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , MATL.TIC_CD

    , MATL.HVA_TXT
    , MATL.HMC_TXT
    , MATL.MATL_PRTY
    , MATL.EXT_MATL_GRP_ID
    , MATL.STK_CLASS_ID
    , MATL.TIRE_SZ_TEXT

    , CASE
        WHEN MATL.PBU_NBR = '01'
            THEN MATL.MKT_CTGY_PROD_GRP_NAME
        ELSE MATL.TIERS
        END AS TIER

    , MATL.PBU_NBR
    , MATL.PBU_NAME
    , MATL.MKT_CTGY_MKT_AREA_NBR AS CATEGORY_CD
    , MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY_NM
    , MATL.MKT_CTGY_MKT_GRP_NBR AS SEGMENT_CD
    , MATL.MKT_CTGY_MKT_GRP_NAME AS SEGMENT_NM
    , MATL.MKT_CTGY_PROD_GRP_NBR AS SALES_PROD_GRP_CD
    , MATL.MKT_CTGY_PROD_GRP_NAME AS SALES_PROD_GRP_NM
    , MATL.MKT_CTGY_PROD_LINE_NBR AS SALES_PROD_LINE_CD
    , MATL.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE_NM

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID
    , OD.PO_TYPE_ID
    , DDC.DELIV_CAT_ID
    , DDC.DELIV_TYPE_ID

    , DDC.QTY_UNIT_MEAS_ID
    , OD.ORDER_QTY
    , OD.CNFRM_QTY
    , DDC.DELIV_QTY

    , OD.ORDER_DT
    , OD.ORDER_LN_CRT_DT

    , OD.PLN_MATL_AVL_DT AS MAD_FIRST_DATE
    , OD.PLN_GOODS_ISS_DT AS PGI_FIRST_DATE
    , OD.PLN_DELIV_DT AS FIRST_DATE
    , FIRST_DATE - OD.ORDER_DT AS FIRST_DATE_INTERVAL_DAYS

    , OD.FNL_ACCEPT_DT

    , OD.CUST_RDD AS ORDD
    , ORDD - OD.ORDER_DT AS ORDD_INTERVAL_DAYS

    , OD.FRST_MATL_AVL_DT AS FRDD_FMAD
    , OD.FRST_PLN_GOODS_ISS_DT AS FRDD_FPGI
    , OD.FRST_RDD AS FRDD
    , FRDD - OD.ORDER_DT AS FRDD_INTERVAL_DAYS

    , OD.FC_MATL_AVL_DT AS FCDD_FMAD
    , OD.FC_PLN_GOODS_ISS_DT AS FCDD_FPGI
    , OD.FRST_PROM_DELIV_DT AS FCDD
    , FCDD - OD.ORDER_DT AS FCDD_INTERVAL_DAYS

    , DDC.DELIV_NOTE_CREA_DT
    , DDC.DELIV_NOTE_CREA_DT - OD.ORDER_DT AS DN_CREATE_INTERVAL_DAYS

    , DDC.PLN_GOODS_MVT_DT
    , DDC.ACTL_GOODS_ISS_DT
    , DDC.ACTL_GOODS_ISS_DT - OD.ORDER_DT AS AGID_INTERVAL_DAYS

    , DDC.DELIV_DT
    , DDC.DELIV_DT - OD.ORDER_DT AS SAP_DLV_INTERVAL_DAYS

    , DDC.CUST_GRP2_CD
    , DDC.DELIV_PRTY_ID
    , DDC.SHIP_COND_ID
    , DDC.RTG_ID AS ROUTE_ID
    , DDC.TERMS_ID
    , DDC.UNLD_PT_CD
    , OD.SPCL_PROC_ID
    , DDC.PRM_SHIP_CARR_CD
    , DDC.TRANSP_VEH_NO
    , DDC.SRC_CRT_USR_ID AS DELIV_CREATOR
    , OD.ORDER_CREATOR
    , DDC.GOODS_ISS_IND
    , OD.CANCEL_DT
    , OD.REJ_REAS_ID
    , OD.DELIV_GRP_CD

FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND OD.ORDER_ID = DDC.ORDER_ID
        AND OD.ORDER_LINE_NBR = DDC.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = 1
        AND OD.EXP_DT = DATE '5555-12-31'
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.RO_PO_TYPE_IND = 'N'
        AND OD.ORDER_DT >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE)

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE = DDC.ACTL_GOODS_ISS_DT
        -- ROLLING 12 MONTHS
        AND CAL.DAY_DATE BETWEEN ADD_MONTHS(CURRENT_DATE-1, -13) - (EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE-1, -13))-1) AND CURRENT_DATE-1

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID
        AND CUST.OWN_CUST_ID = '00A0003047'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = DDC.MATL_ID

    INNER JOIN GDYR_VWS.FACILITY FAC
        ON FAC.FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID
        AND FAC.EXP_DT = DATE '5555-12-31'
        AND FAC.ORIG_SYS_ID = 2
        AND FAC.LANG_ID = 'EN'
        AND FAC.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND FAC.PURCH_ORG_ID IN ('N701', 'N702', 'N703')
        AND FAC.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_CO_EN_CURR CO
        ON CO.CO_CD = OD.CO_CD
        AND CO.CO_CD IN ('N101', 'N102', 'N266')

WHERE
    DDC.GOODS_ISS_IND = 'Y'
    AND DDC.DELIV_CAT_ID = 'J'
    AND DDC.DELIV_QTY > 0

ORDER BY
    DDC.FISCAL_YR
    , DDC.DELIV_ID
    , DDC.DELIV_LINE_NBR
