SELECT
    ODC.ORDER_FISCAL_YR
    , ODC.ORDER_ID
    , ODC.ORDER_LINE_NBR
    , ODC.CUST_PO_NBR

    , ODC.ORDER_CAT_ID
    , ODC.ORDER_TYPE_ID
    , ODC.PO_TYPE_ID

    , CUST.SALES_ORG_CD
    , CUST.SALES_ORG_NAME
    , CUST.DISTR_CHAN_CD
    , CUST.DISTR_CHAN_NAME
    , CUST.CUST_GRP_ID
    , CUST.CUST_GRP_NAME
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    , CUST.SHIP_TO_CUST_ID
    , CUST.CUST_NAME AS SHIP_TO_CUST_NAME

    , CASE
        WHEN ODC.FACILITY_ID IN ('N5US', 'N5CA')
            THEN 'N'
        WHEN CUST.PRIM_SHIP_FACILITY_ID = ODC.FACILITY_ID
            THEN 'P'
        WHEN ODC.FACILITY_ID LIKE 'N5%'
            THEN 'F'
        ELSE 'O'
        END AS TEST_PRIM_SHIP_FACILITY
    , CUST.PRIM_SHIP_FACILITY_ID
    , FAC.FACILITY_ID
    , FAC.FACILITY_NAME
    , ODC.SHIP_PT_ID

    , ODC.MATL_ID
    , ODC.CUST_PART_NBR
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , MATL.TIC_CD
    , MATL.HVA_TXT
    , MATL.HMC_TXT
    , MATL.SAL_IND
    , MATL.MATL_PRTY
    , MATL.EXT_MATL_GRP_ID
    , MATL.STK_CLASS_ID
    , MATL.TIRE_SZ_TEXT
    , MATL.PBU_NBR
    , MATL.PBU_NAME
    , MATL.MKT_CTGY_MKT_AREA_NBR AS CATEGORY_CD
    , MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY_NAME
    , MATL.MKT_CTGY_MKT_GRP_NBR AS SEGMENT_CD
    , MATL.MKT_CTGY_MKT_GRP_NAME AS SEGMENT_NAME
    , MATL.MKT_CTGY_PROD_GRP_NBR AS TIER_CD
    , MATL.MKT_CTGY_PROD_GRP_NAME AS TIER_NAME
    , MATL.MKT_CTGY_PROD_LINE_NBR AS SALES_PROD_LINE_CD
    , MATL.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE_NAME

    , ODC.CANCEL_DT
    , ODC.REJ_REAS_ID
    , ODC.REJ_REAS_DESC

    , ODC.ORDER_DELIV_BLK_CD
    , ODC.DELIV_BLK_CD
    , ODC.ORDER_CREATOR
    , ODC.SHIP_COND_ID

    , ODC.DELIV_PRTY_ID
    , ODC.ROUTE_ID
    , ODC.DELIV_GRP_CD
    , ODC.SPCL_PROC_ID
    , ODC.CUST_GRP2_CD

    , ODC.ORDER_DT
    , ODC.ORDER_LN_CRT_DT
    , ODC.PLN_DELIV_DT AS FIRST_DATE
    , ODC.CUST_RDD AS ORDD
    , ODC.FRST_RDD AS FRDD
    , ODC.FRST_PROM_DELIV_DT AS FCDD

    , ODC.PLN_DELIV_DT - ODC.ORDER_DT AS ORDER_TO_FIRST_DATE
    , ODC.CUST_RDD - ODC.ORDER_DT AS ORDER_TO_ORDD
    , ODC.FRST_RDD - ODC.ORDER_DT AS ORDER_TO_FRDD
    , ODC.FRST_PROM_DELIV_DT - ODC.ORDER_DT AS ORDER_TO_FCDD

    , ODC.QTY_UNIT_MEAS_ID
    , ODC.ORDER_QTY

FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID
        AND CUST.OWN_CUST_ID = '00A0003047'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID
        AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
        AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')
        AND MATL.SUPER_BRAND_ID IN ('01', '02', '03', '05')

    INNER JOIN GDYR_BI_vWS.NAT_FACILITY_EN_CURR FAC
        ON FAC.FACILITY_ID = ODC.FACILITY_ID
        AND FAC.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND FAC.DISTR_CHAN_CD = '81'

WHERE
    ODC.ORDER_CAT_ID = 'C'
    AND ODC.ORDER_DT >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE)
    AND ODC.PO_TYPE_ID <> 'RO'


