SELECT
    DDC.FISCAL_YR
    , DDC.DELIV_ID
    , DDC.DELIV_LINE_NBR
    , DDC.BILL_LADING_ID
    
    , DDC.ORDER_FISCAL_YR
    , DDC.ORDER_ID
    , DDC.ORDER_LINE_NBR
    , ODC.CUST_PO_NBR
    
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    , DDC.SHIP_TO_CUST_ID
    , CUST.CUST_NAME AS SHIP_TO_cUST_NAME
    , CUST.CITY_NAME
    , CUST.TERR_NAME
    , CUST.POSTAL_CD
    , CUST.CNTRY_NAME_CD
    
    , CASE
        WHEN CUST.PRIM_SHIP_FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID
            THEN 'P'
        WHEN DDC.DELIV_LINE_FACILITY_ID LIKE 'N5%'
            THEN 'F'
        ELSE 'O'
        END AS TEST_PRIM_SHIP_FACILITY
    , CUST.PRIM_SHIP_FACILITY_ID
    , DDC.DELIV_LINE_FACILITY_ID
    , FAC.FACILITY_NAME
    , DDC.SHIP_PT_ID
    
    , DDC.MATL_ID
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , DDC.CUST_PART_NBR
    , MATL.MATL_STA_ID
    , MATL.MATL_PRTY
    
    , MATL.PROD9_CD
    , MATL.TIC_CD

    , MATL.HVA_TXT
    , MATL.HMC_TXT

    , CASE
        WHEN MATL.PBU_NBR = '01'
            THEN MATL.MKT_CTGY_PROD_GRP_NAME
        ELSE MATL.TIERS
        END AS TIER
        
    , MATL.PBU_NBR
    , MATL.PBU_NAME
    , MATL.MKT_CTGY_MKT_AREA_NBR AS CATEGORY_CD
    , MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY_NM
    , MATL.MKT_CTGY_MKT_GRP_NBR AS SEGMENT_CD
    , MATL.MKT_CTGY_MKT_GRP_NAME AS SEGMENT_NM
    , MATL.MKT_CTGY_PROD_GRP_NBR AS SALES_PROD_GRP_CD
    , MATL.MKT_CTGY_PROD_GRP_NAME AS SALES_PROD_GRP_NM
    , MATL.MKT_CTGY_PROD_LINE_NBR AS SALES_PROD_LINE_CD
    , MATL.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE_NM
    
    , DDC.QTY_UNIT_MEAS_ID
    , DDC.DELIV_QTY
    
    , ODC.ORDER_DT
    , ODC.ORDER_LN_CRT_DT
    
    , ODC.PLN_MATL_AVL_DT AS MAD_FIRST_DATE
    , ODC.PLN_GOODS_ISS_DT AS PGI_FIRST_DATE
    , ODC.PLN_DELIV_DT AS FIRST_DATE
    
    , ODC.CUST_RDD AS ORDD
    
    , ODC.FRST_MATL_AVL_DT AS FRDD_FMAD
    , ODC.FRST_PLN_GOODS_ISS_DT AS FRDD_FPGI
    , ODC.FRST_RDD AS FRDD
    
    , ODC.FC_MATL_AVL_DT AS FCDD_FMAD
    , ODC.FC_PLN_GOODS_ISS_DT AS FCDD_FPGI
    , ODC.FRST_PROM_DELIV_DT AS FCDD
    
    , DDC.DELIV_NOTE_CREA_DT
    , DDC.PLN_GOODS_MVT_DT
    , DDC.ACTL_GOODS_ISS_DT
    , DDC.DELIV_DT
    
    , DWS.APPT_DT
    , DWS.RTE_PLN_DT
    , DWS.LD_PICK_DT
    , DWS.LD_READY_DT
    , DWS.LD_REL_DT
    
    , CDM.TM_CARR_ID
    , CDM.MSTR_BOL
    , CDM.SHIP_BOL
    
    , CDM.CARR_ACCEPT_TS
    , CDM.READYBYPLN_DT
    , CDM.ARRV_AT_PKUP_TS
    , CDM.DEPART_FROM_PKUP_TS
    , CDM.REQ_DELIV_DT
    , CDM.PLN_ARRV_TS
    , CDM.LPC_APPT_TS
    , CDM.ARRV_AT_DELIV_TS
    
    , DDC.CUST_GRP2_CD
    , DDC.DELIV_PRTY_ID
    , DDC.SHIP_COND_ID
    , ODC.DELIV_GRP_CD
    
    , ODC.SPCL_PROC_ID
    , DDC.TERMS_ID AS INCOTERMS_ID
    , DDC.RTG_ID AS ROUTE_ID
    
    , ODC.ORDER_CREATOR
    , DDC.SRC_CRT_USR_ID AS DELIVERY_CREATOR
    , DDC.GOODS_ISS_IND
    
    , ODC.CANCEL_DT
    , ODC.REJ_REAS_ID
    , ODC.REJ_REAS_DESC
    
    , ODC.ORDER_CAT_ID
    , ODC.ORDER_TYPE_ID
    , DDC.DELIV_CAT_ID
    , DDC.DELIV_TYPE_ID
    , ODC.PO_TYPE_ID
    
FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID
        AND CUST.OWN_CUST_ID = '00A0003047'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = DDC.MATL_ID
        AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
        --AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FAC
        ON FAC.FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID
        --AND FAC.DISTR_CHAN_CD = '81'

    INNER JOIN NA_BI_VWS.ORDER_DETAIL_CURR ODC
        ON ODC.ORDER_FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND ODC.ORDER_ID = DDC.ORDER_ID
        AND ODC.ORDER_LINE_NBR = DDC.ORDER_LINE_NBR
        AND ODC.SCHED_LINE_NBR = 1
        AND ODC.ORDER_CAT_ID = 'C'
        AND ODC.RO_PO_TYPE_IND = 'N'

    LEFT OUTER JOIN NA_BI_VWS.DELIV_WHSE_SCHD DWS
        ON DWS.DELIV_FISCAL_YR = DDC.FISCAL_YR
        AND DWS.DELIV_ID = DDC.DELIV_ID

    LEFT OUTER JOIN NA_BI_VWS.TM_CARR_DELIV_MSG_CURR CDM
        ON CDM.SAP_DELIV_FISCAL_YR = DDC.FISCAL_YR
        AND CDM.SAP_DELIV_ID = DDC.DELIV_ID
        AND CDM.TM_DEST_TYP_CD = 'CUST'

WHERE
    DDC.GOODS_ISS_IND = 'Y'
    AND DDC.DELIV_CAT_ID = 'J'
    AND DDC.DELIV_QTY > 0
    AND DDC.ACTL_GOODS_ISS_DT IS NOT NULL
    AND DDC.ACTL_GOODS_ISS_DT BETWEEN ADD_MONTHS(CURRENT_DATE-1, -6) - (EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE-1, -6)) - 1) 
        AND CURRENT_DATE-1

ORDER BY
    DDC.FISCAL_YR
    , DDC.DELIV_ID
    , DDC.DELIV_LINE_NBR
