SELECT
    CAL.DAY_DATE
    , OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR
    
    , CASE
        WHEN CAL.DAY_DATE = DLV.DELIV_NOTE_CREA_DT
            THEN (CASE
                WHEN CAL.DAY_DATE = DLV.ACTL_GOODS_ISS_DT
                    THEN 'Order to AGID - Same Day'
                ELSE 'Order to DN Create - Same Day'
                END)
        WHEN CAL.DAY_DATE = OD.CANCEL_DT
            THEN 'Ordered and Rejected - Same Day'
        WHEN OD.ORDER_CRT_TM BETWEEN TIME '22:30:00' AND TIME '23:59:59'
            THEN 'Order Created between 10:30 PM and Midnight'
        END AS EVAL

    , OD.ORDER_TYPE_ID
    , OD.PO_TYPE_ID
    , OD.ITEM_CAT_ID

    , CAST(OD.ORDER_DT AS TIMESTAMP(0)) + (OD.ORDER_CRT_TM - TIME '00:00:00' HOUR TO SECOND) AS ORDER_CRT_TS
    --, OD.ORDER_DT
    --, OD.ORDER_CRT_TM

    , CAST(OD.ORDER_LN_CRT_DT AS TIMESTAMP(0)) + (OD.ORDER_LN_CRT_TM - TIME '00:00:00' HOUR TO SECOND) AS ITEM_CRT_TS
    --, OD.ORDER_LN_CRT_DT
    --, OD.ORDER_LN_CRT_TM

    , OD.SHIP_TO_CUST_ID
    , CUST.CUST_NAME
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME

    , OD.MATL_ID
    , MATL.DESCR
    , MATL.PBU_NBR
    , MATL.PBU_NAME

    , OD.FACILITY_ID
    , FAC.FACILITY_NAME

    , OD.QTY_UNIT_MEAS_ID
    , OD.ORDER_QTY


    , OD.ORDER_CREATOR

    , OD.REJ_REAS_ID
    , OD.CANCEL_DT
    , DLV.DELIV_NOTE_CREA_DT
    , DLV.DELIV_QTY
    , DLV.ACTL_GOODS_ISS_DT
    /*    , CASE
        WHEN OD.CANCEL_DT = CAL.DAY_DATE
            THEN 'Y'
        ELSE 'N'
        END AS CANCELED_ON_ORDER_DT_IND*/

FROM NA_BI_VWS.ORDER_DETAIL OD

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE BETWEEN OD.EFF_DT AND OD.EXP_DT
        AND CAL.DAY_DATE BETWEEN CURRENT_DATE-14 AND CURRENT_DATE-1
        AND OD.ORDER_DT = CAL.DAY_DATE

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = OD.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FAC
        ON FAC.FACILITY_ID = OD.FACILITY_ID

    LEFT OUTER JOIN (
            SELECT
                ORDER_FISCAL_YR
                , ORDER_ID
                , ORDER_LINE_NBR
                , DELIV_NOTE_CREA_DT
                , SUM(DELIV_QTY) AS DELIV_QTY
                , ACTL_GOODS_ISS_DT
            FROM NA_BI_VWS.DELIVERY_DETAIL_CURR
            WHERE
                DELIV_NOTE_CREA_DT BETWEEN CURRENT_DATE-14 AND CURRENT_DATE-1
            GROUP BY
                ORDER_FISCAL_YR
                , ORDER_ID
                , ORDER_LINE_NBR
                , DELIV_NOTE_CREA_DT
                , ACTL_GOODS_ISS_DT
            ) DLV
        ON DLV.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
        AND DLV.ORDER_ID = OD.ORDER_ID
        AND DLV.ORDER_LINE_NBR = OD.ORDER_LINE_NBR
        AND DLV.DELIV_NOTE_CREA_DT = CAL.DAY_DATE

WHERE
    OD.ORDER_CAT_ID = 'C'
    AND OD.RO_PO_TYPE_IND = 'N'
    AND OD.SCHED_LINE_NBR = 1
    --AND OD.REJ_REAS_ID = ''

EXCEPT

SELECT
    CAL.DAY_DATE
    , OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , CASE
        WHEN CAL.DAY_DATE = DLV.DELIV_NOTE_CREA_DT
            THEN (CASE
                WHEN CAL.DAY_DATE = DLV.ACTL_GOODS_ISS_DT
                    THEN 'Order to AGID - Same Day'
                ELSE 'Order to DN Create - Same Day'
                END)
        WHEN CAL.DAY_DATE = OD.CANCEL_DT
            THEN 'Ordered and Rejected - Same Day'
        WHEN OD.ORDER_CRT_TM BETWEEN TIME '22:30:00' AND TIME '23:59:59'
            THEN 'Order Created between 10:30 PM and Midnight'
        END AS EVAL

    , OD.ORDER_TYPE_ID
    , OD.PO_TYPE_ID
    , OD.ITEM_CAT_ID

    , CAST(OD.ORDER_DT AS TIMESTAMP(0)) + (OD.ORDER_CRT_TM - TIME '00:00:00' HOUR TO SECOND) AS ORDER_CRT_TS
    --, OD.ORDER_DT
    --, OD.ORDER_CRT_TM

    , CAST(OD.ORDER_LN_CRT_DT AS TIMESTAMP(0)) + (OD.ORDER_LN_CRT_TM - TIME '00:00:00' HOUR TO SECOND) AS ITEM_CRT_TS
    --, OD.ORDER_LN_CRT_DT
    --, OD.ORDER_LN_CRT_TM

    , OD.SHIP_TO_CUST_ID
    , CUST.CUST_NAME
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME

    , OD.MATL_ID
    , MATL.DESCR
    , MATL.PBU_NBR
    , MATL.PBU_NAME

    , OD.FACILITY_ID
    , FAC.FACILITY_NAME

    , OD.QTY_UNIT_MEAS_ID
    , OD.ORDER_QTY


    , OD.ORDER_CREATOR

    , OD.REJ_REAS_ID
    , OD.CANCEL_DT
    , DLV.DELIV_NOTE_CREA_DT
    , DLV.DELIV_QTY
    , DLV.ACTL_GOODS_ISS_DT
    /*    , CASE
        WHEN OD.CANCEL_DT = CAL.DAY_DATE
            THEN 'Y'
        ELSE 'N'
        END AS CANCELED_ON_ORDER_DT_IND*/

FROM NA_BI_VWS.ORDER_DETAIL OD

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE BETWEEN OD.EFF_DT AND OD.EXP_DT
        AND CAL.DAY_DATE BETWEEN CURRENT_DATE-14 AND CURRENT_DATE-1
        AND OD.ORDER_DT = CAL.DAY_DATE

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = OD.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FAC
        ON FAC.FACILITY_ID = OD.FACILITY_ID

    INNER JOIN NA_VWS.OPEN_ORDER_SCHDLN OOL
        ON OOL.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = OD.ORDER_ID
        AND OOL.ORDER_LINE_NBR = OD.ORDER_LINE_NBR
        AND OOL.SCHED_LINE_NBR = OD.SCHED_LINE_NBR
        AND CAL.DAY_DATE BETWEEN OOL.EFF_DT AND OOL.EXP_DT

    LEFT OUTER JOIN (
            SELECT
                ORDER_FISCAL_YR
                , ORDER_ID
                , ORDER_LINE_NBR
                , DELIV_NOTE_CREA_DT
                , SUM(DELIV_QTY) AS DELIV_QTY
                , ACTL_GOODS_ISS_DT
            FROM NA_BI_VWS.DELIVERY_DETAIL_CURR
            WHERE
                DELIV_NOTE_CREA_DT BETWEEN CURRENT_DATE-14 AND CURRENT_DATE-1
            GROUP BY
                ORDER_FISCAL_YR
                , ORDER_ID
                , ORDER_LINE_NBR
                , DELIV_NOTE_CREA_DT
                , ACTL_GOODS_ISS_DT
            ) DLV
        ON DLV.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
        AND DLV.ORDER_ID = OD.ORDER_ID
        AND DLV.ORDER_LINE_NBR = OD.ORDER_LINE_NBR
        AND DLV.DELIV_NOTE_CREA_DT = CAL.DAY_DATE

WHERE
    OD.ORDER_CAT_ID = 'C'
    AND OD.RO_PO_TYPE_IND = 'N'
    AND OD.SCHED_LINE_NBR = 1
    --AND OD.REJ_REAS_ID = ''

ORDER BY 1,2,3,4
