SELECT
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    , OOL.SCHED_LINE_NBR
    
    , ODC.ORDER_TYPE_ID
    , ODC.PO_TYPE_ID
    , ODC.ORDER_DT
    , ODC.ORDER_LN_CRT_DT
    
    , ODC.SHIP_TO_CUST_ID
    , CUST.SHIP_TO_CUST_ID || ' - ' || CUST.CUST_NAME AS SHIP_TO_CUST
    , CUST.OWN_CUST_ID || ' - ' || CUST.OWN_CUST_NAME AS OWN_CUST
    , ODC.CUST_GRP2_CD
    , ODC.SHIP_COND_ID
    
    , OOL.CREDIT_HOLD_FLG
    , ODC.ORDER_DELIV_BLK_CD
    , ODC.DELIV_BLK_CD
    
    , ODC.MATL_ID
    , MATL.PBU_NBR
    , MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY
    , MATL.MKT_CTGY_PROD_GRP_NAME AS TIER
    , ODC.FACILITY_ID
    , ODC.SHIP_PT_ID
    
    , INV.AVAIL_TO_PROM_QTY
    
    , ODC.PLN_MATL_AVL_DT
    , ODC.PLN_GOODS_ISS_DT
    , ODC.PLN_DELIV_DT
    
    , ODC.QTY_UNIT_MEAS_ID
    , OOL.OPEN_CNFRM_QTY
    , OOL.UNCNFRM_QTY
    , OOL.BACK_ORDER_QTY

FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL ODC
        ON ODC.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND ODC.ORDER_ID = OOL.ORDER_ID
        AND ODC.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND ODC.SCHED_LINE_NBR = OOL.SCHED_LINE_NBR
        AND ODC.EXP_DT = DATE '5555-12-31'
        AND ODC.ORDER_FISCAL_YR >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-2 AS CHAR(4))
        AND ODC.ORDER_CAT_ID = 'C'
        AND ODC.PO_TYPE_ID <> 'RO'
        AND ODC.REJ_REAS_ID = ''

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID
        AND CUST.OWN_CUST_ID IN ('00A0006054', '00A0006090')

    LEFT OUTER JOIN NA_BI_VWS.FACILITY_MATL_INVENTORY INV
        ON INV.FACILITY_ID = ODC.FACILITY_ID
        AND INV.MATL_ID = ODC.MATL_ID
        AND INV.DAY_DT = (CURRENT_DATE-1)

WHERE
    OOL.OPEN_CNFRM_QTY > 0
    OR OOL.UNCNFRM_QTY > 0
    OR OOL.BACK_ORDER_QTY > 0

ORDER BY
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    , OOL.SCHED_LINE_NBR
