SELECT
    ODC.SALES_ORG_CD
    , ODC.DISTR_CHAN_CD
    , ODC.CUST_GRP_ID
    , SH.OWN_CUST_ID
    , ODC.SOLD_TO_CUST_ID
    , SP.CUST_NAME AS SOLD_TO_CUST_NAME
    , ODC.SHIP_TO_CUST_ID
    , SH.CUST_NAME AS SHIP_TO_CUST_NAME
    , SH.ADDR_LINE_1
    , SH.CITY_NAME
    , SH.TERR_NAME
    , SH.POSTAL_CD
    , SH.FAX_NO
    , ODC.CUST_PO_NBR
    , ODC.PO_TYPE_ID
    , ODC.ORDER_FISCAL_YR
    , ODC.ORDER_ID
    , ODC.ORDER_LINE_NBR
    , ODC.SCHED_LINE_NBR
    , CASE
        WHEN OOL.OPEN_CNFRM_QTY > 0
            THEN 'C'
        WHEN OOL.UNCNFRM_QTY > 0
            THEN 'U'
        WHEN OOL.BACK_ORDER_QTY > 0
            THEN 'B'
        END AS STATUS_CD
    , ODC.ORDER_TYPE_ID
    , ODC.ORDER_DELIV_BLK_CD
    , ODC.DELIV_BLK_CD
    , ODC.DELIV_PRTY_ID
    , CAST(NULL AS VARCHAR(55)) AS INCOTERMS_CD
    , ODC.GROSS_WT
    , ODC.PRICE
    , ODC.CUST_PART_NBR
    , MATL.PROD9_CD
    , ODC.BATCH_NBR
    , ODC.MATL_ID
    , MATL.DESCR
    , CAST(MATL.PBU_NBR || MATL.MKT_AREA_NBR || MATL.MKT_GRP_NBR || MATL.PROD_GRP_NBR || MATL.PROD_LINE_NBR AS CHAR(18)) AS PROD_HIER
    , MATL.UNIT_WT
    , MATL.BRAND_ID
    , ZEROIFNULL(OOL.OPEN_CNFRM_QTY) + ZEROIFNULL(OOL.UNCNFRM_QTY) + ZEROIFNULL(OOL.BACK_ORDER_QTY) AS QTY
    , ODC.FACILITY_ID
    , CAST(NULL AS VARCHAR(55)) AS UNLD_PT_CD
    , ODC.DELIV_GRP_CD
    , ODC.ORDER_CREATOR
    , ODC.ORDER_LN_CRT_DT
    , ODC.HANDSHAKE_TYP_CD
    , ODC.FRST_RDD
    , ODC.CUST_RDD
    , ODC.SPCL_PROC_ID
    , ODC.PLN_DELIV_DT
    , ODC.PLN_GOODS_ISS_DT
    , ODC.PLN_MATL_AVL_DT
    , ODC.FNL_ACCEPT_DT
    , ODC.ORDER_DT
    , ODC.PRC_DT
    , ODC.VOL
    , ODC.PROD_ALLCT_DETERM_PROC_ID
    , CASE COALESCE(ITM.DELIV_STA_CD, '')
        WHEN ''
            THEN 'Not Relevant'
        WHEN 'A'
            THEN 'Not yet processed'
        WHEN 'B'
            THEN 'Partially Processed'
        WHEN 'C'
            THEN 'Completely Processed'
        END AS DELIV_STA

FROM NA_BI_VWS.ORDER_DETAIL ODC

    INNER JOIN NA_BI_VWS.SD_DOC_ITM_STA ITM
        ON ITM.FISCAL_YR = ODC.ORDER_FISCAL_YR
        AND ITM.SD_DOC_ID = ODC.ORDER_ID
        AND ITM.SD_DOC_ITM_ID = ODC.ORDER_LINE_NBR
        AND ITM.EXP_DT = DATE '5555-12-31'

    INNER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL
        ON OOL.ORDER_FISCAL_YR = ODC.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = ODC.ORDER_ID
        AND OOL.ORDER_LINE_NBR = ODC.ORDER_LINE_NBR
        AND OOL.SCHED_LINE_NBR = ODC.SCHED_LINE_NBR

    INNER JOIN GDYR_BI_VWS.NAT_CUST_CURR SP
        ON SP.CUST_ID = ODC.SOLD_TO_CUST_ID
    
    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR SH
        ON SH.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID
        AND SH.TIRE_CUST_TYP_CD = 'OE'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID
        AND MATL.PBU_NBR IN ('01', '07')

WHERE
    ODC.EXP_DT = DATE '5555-12-31'
    AND ODC.ORDER_CAT_ID = 'C'
    AND ODC.RO_PO_TYPE_IND = 'N'
    
