-- OUTPUT SUMMARIZES OPEN ORDERS FOR TRUCKLOAD WEIGHT CUSTOMERS
-- USED TO DETERMINE WHICH ORDERS CAN BE DROPPED TO DELIVERY NOTE TODAY WITHOUT MODIFYING THE DELIVERY DATE

-- FIRST STEP SUMMARIZES ALL OPEN ORDERS TO IDENTIFY THE TRUE OPEN CONFIRMED QTY (DERIVED TABLE IN FROM CLAUSE)
-- SECOND STEP IDENTIFIES IF A ORDER IS SHIPPING AT THE PRIMARY LC OR OUT OF AREA
--      EVALUATES ATP VS. OPEN CONFIRMED QTY FOR LINE
--      PRIORITIZES NON-SIGS WITH THE GREATEST OPEN CONFIRMED WEIGHT
--      IF LINE HAS DELIVERY BLOCK PRESENT ON HEADER OR SCHEDULE LINE, DOES NOT CONSIDER OPEN CNFRM QTY AS ELIGIBLE FOR IMPROVEMENT

SELECT
    OPN.ORDER_FISCAL_YR
    , OPN.ORDER_ID
    , OPN.ORDER_LINE_NBR
    , OPN.SCHED_LINE_NBR

    , OPN.CUST_GRP2_CD
    , OPN.SHIP_TO_CUST_ID
    , CUST.SHIP_TO_CUST_ID || ' - ' || CUST.CUST_NAME AS SHIP_TO_CUST
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_ID || ' - ' || CUST.OWN_CUST_NAME AS OWN_CUST
    , CUST.SALES_ORG_CD
    , CUST.SALES_ORG_CD || ' - ' || CUST.SALES_ORG_NAME AS SALES_ORG

    , OPN.MATL_ID_TRIM
    , OPN.MATL_DESCR
    , OPN.PBU_NBR
    , OPN.PBU
    , OPN.CATEGORY
    , OPN.SALES_PROD_LINE

    , OPN.FACILITY_ID
    , OPN.SHIP_PT_ID

    , OPN.QTY_UOM
    , OPN.OPEN_CNFRM_QTY
    , OPN.FACL_MATL_OPEN_QTY
    , OPN.FACL_INV_ATP_QTY
    , CASE
        WHEN OPN.FACL_ATP_INV_TEST = 'Y'
            THEN 'Improvable'
        ELSE 'Product/Facility Constrained'
        END AS FACILITY_ATP_INV_TEST

    , OPN.WT_UOM
    , OPN.OPEN_CNFRM_WT
    , OPN.IMPR_OPEN_CNFRM_WT
    , SUM(OPN.IMPR_OPEN_CNFRM_WT) OVER (PARTITION BY OPN.SHIP_TO_CUST_ID, OPN.FACILITY_ID, OPN.PLN_GOODS_ISS_DT, OPN.DELIV_PRTY_ID) AS FACL_CUST_OPEN_WT

    , CAST(CASE
        WHEN FACL_CUST_OPEN_WT > 30000
            THEN '>30K'
        WHEN FACL_CUST_OPEN_WT > 25000
            THEN '25-30K'
        WHEN FACL_CUST_OPEN_WT > 20000
            THEN '20-25K'
        WHEN FACL_CUST_OPEN_WT > 15000
            THEN '15-20K'
        ELSE '<15K'
        END AS VARCHAR(6)) AS FACL_CUST_OPEN_WT_TEST

    , OPN.VOL_UOM
    , OPN.OPEN_CNFRM_VOL
    , OPN.IMPR_OPEN_CNFRM_VOL
    , SUM(OPN.IMPR_OPEN_CNFRM_VOL) OVER (PARTITION BY OPN.SHIP_TO_CUST_ID, OPN.FACILITY_ID, OPN.PLN_GOODS_ISS_DT, OPN.DELIV_PRTY_ID) AS FACL_CUST_OPEN_VOL

    , CAST(CASE
        WHEN FACL_CUST_OPEN_WT > 3500
            THEN '>3,500 FT3'
        WHEN FACL_CUST_OPEN_WT > 3000
            THEN '3,000-3,500 FT3'
        WHEN FACL_CUST_OPEN_WT > 2500
            THEN '2,500-3,000 FT3'
        WHEN FACL_CUST_OPEN_WT > 2000
            THEN '2,000-2,500 FT3'
        ELSE '<2,000 FT3'
        END AS VARCHAR(6)) AS FACL_CUST_OPEN_VOL_TEST

    , OPN.SHIP_COND_ID
    , OPN.DELIV_PRTY_ID
    , OPN.ROUTE_ID
    , OPN.DELIV_GRP_CD
    , OPN.SPCL_PROC_ID

    , OPN.PLN_MATL_AVL_DT
    , OPN.PLN_GOODS_ISS_DT
    , OPN.PLN_DELIV_DT

    , OPN.ORDER_DT
    , OPN.ORDD
    , OPN.FRDD_FMAD
    , OPN.FRDD_FPGI
    , OPN.FRDD

FROM (

    SELECT
        OOL.ORDER_FISCAL_YR
        , OOL.ORDER_ID
        , OOL.ORDER_LINE_NBR
        , OOL.SCHED_LINE_NBR

        , ODC.CUST_GRP2_CD

        , ODC.SALES_ORG_CD
        , ODC.SHIP_TO_CUST_ID

        , MATL.MATL_ID_TRIM
        , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
        , MATL.PBU_NBR
        , MATL.PBU_NBR || ' - ' || MATL.PBU_NAME AS PBU
        , MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY
        , MATL.MKT_CTGY_PROD_LINE_NBR || ' - ' || MATL.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE
        , CAST(CASE MATL.PBU_NBR || MATL.MKT_AREA_NBR
            WHEN '0101' THEN 0.75
            WHEN '0108' THEN 0.80
            WHEN '0305' THEN 1.20
            WHEN '0314' THEN 1.20
            WHEN '0406' THEN 1.20
            WHEN '0507' THEN 0.75
            WHEN '0711' THEN 0.75
            WHEN '0712' THEN 0.75
            WHEN '0803' THEN 1.20
            WHEN '0923' THEN 0.75
            ELSE 1
            END AS DECIMAL(15,3)) AS COMPRESSION_RATIO
        , ODC.FACILITY_ID
        , ODC.SHIP_PT_ID

        , ODC.QTY_UNIT_MEAS_ID AS QTY_UOM
        , OOL.OPEN_CNFRM_QTY
        , SUM(OOL.OPEN_CNFRM_QTY) OVER (PARTITION BY ODC.MATL_ID, ODC.FACILITY_ID) AS FACL_MATL_OPEN_QTY
        , ZEROIFNULL(INV.AVAIL_TO_PROM_QTY) AS FACL_INV_ATP_QTY
        
        -- IDENTIFY MATERIAL / FACILITY PAIRS WHICH HAVE ATP > FACTOR * THE MATERIAL-FACILITY OPEN CNFRM QTY
        , CAST(CASE
            WHEN (FACL_MATL_OPEN_QTY * 1.1) < FACL_INV_ATP_QTY 
                    AND ODC.DELIV_BLK_CD = '' 
                    AND ODC.ORDER_DELIV_BLK_CD = '' 
                    AND OOL.CREDIT_HOLD_FLG = 'N'
                THEN 'Y'
            ELSE 'N'
            END AS CHAR(1)) AS FACL_ATP_INV_TEST

        , ODC.WT_UNITS_MEAS_ID AS WT_UOM
        , CAST(OOL.OPEN_CNFRM_QTY * MATL.UNIT_WT AS DECIMAL(15,3)) AS OPEN_CNFRM_WT
        , CASE
            WHEN FACL_ATP_INV_TEST = 'Y'
                THEN OPEN_CNFRM_WT
            ELSE 0
            END AS IMPR_OPEN_CNFRM_WT

        , ODC.VOL_UNIT_MEAS_ID AS VOL_UOM
        
        , CAST(OOL.OPEN_CNFRM_QTY * MATL.UNIT_VOL * COMPRESSION_RATIO AS DECIMAL(15,3)) AS OPEN_CNFRM_VOL
        , CASE
            WHEN FACL_ATP_INV_TEST = 'Y'
                THEN OPEN_CNFRM_VOL
            ELSE 0
            END AS IMPR_OPEN_CNFRM_VOL

        , ODC.SHIP_COND_ID
        , ODC.DELIV_PRTY_ID
        , ODC.ROUTE_ID
        , ODC.DELIV_GRP_CD
        , ODC.SPCL_PROC_ID
        , ODC.ORDER_DELIV_BLK_CD
        , ODC.DELIV_BLK_CD

        , ODC.PLN_MATL_AVL_DT
        , ODC.PLN_GOODS_ISS_DT
        , ODC.PLN_DELIV_DT

        , ODC.ORDER_DT
        , ODC.CUST_RDD AS ORDD
        , ODC.FRST_MATL_AVL_DT AS FRDD_FMAD
        , ODC.FRST_PLN_GOODS_ISS_DT AS FRDD_FPGI
        , ODC.FRST_RDD AS FRDD

    FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL

        INNER JOIN (
                SELECT
                    O.ORDER_FISCAL_YR
                    , O.ORDER_ID
                    , O.ORDER_LINE_NBR
                    , O.SCHED_LINE_NBR
                    , O.CUST_GRP2_CD
                    , O.SALES_ORG_CD
                    , O.SHIP_TO_CUST_ID
                    , O.MATL_ID
                    , O.FACILITY_ID
                    , O.SHIP_PT_ID
                    , O.QTY_UNIT_MEAS_ID
                    , O.WT_UNITS_MEAS_ID
                    , O.VOL_UNIT_MEAS_ID
                    , O.ORDER_DELIV_BLK_CD
                    , O.DELIV_BLK_CD
                    , O.SHIP_COND_ID
                    , O.DELIV_PRTY_ID
                    , O.ROUTE_ID
                    , O.DELIV_GRP_CD
                    , O.SPCL_PROC_ID
                    , O.PLN_MATL_AVL_DT
                    , O.PLN_GOODS_ISS_DT
                    , O.PLN_DELIV_DT
                    , O.ORDER_DT
                    , O.CUST_RDD
                    , O.FRST_MATL_AVL_DT
                    , O.FRST_PLN_GOODS_ISS_DT
                    , O.FRST_RDD
                FROM NA_BI_VWS.ORDER_DETAIL O
                WHERE
                    O.EXP_DT = DATE '5555-12-31'
                    AND O.ORDER_CAT_ID = 'C'
                    AND O.RO_PO_TYPE_IND = 'N'
                    AND O.REJ_REAS_ID = ''
                    AND O.FACILITY_ID IN ('N602', 'N607', 'N623', 'N636', 'N637', 'N639', 'N699', 'N6D3')
                    AND O.PLN_MATL_AVL_DT IS NOT NULL
                    AND O.PLN_MATL_AVL_DT BETWEEN (CURRENT_DATE+1) AND (CURRENT_DATE+15)
                    AND O.SCHED_LINE_NBR = 1
                ) ODC
            ON ODC.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
            AND ODC.ORDER_ID = OOL.ORDER_ID
            AND ODC.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR

        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
            ON MATL.MATL_ID = ODC.MATL_ID
            AND MATL.PBU_NBR IN ('01', '03')
            AND MATL.MKT_CTGY_MKT_AREA_NBR IN ('01', '08', '32', '36', '15', '33', '31', '35', '05')
            AND MATL.SUPER_BRAND_ID IN ('01', '02', '03', '05')

        LEFT OUTER JOIN GDYR_BI_VWS.NAT_INV_CURR INV
            ON INV.FACILITY_ID = ODC.FACILITY_ID
            AND INV.MATL_ID = ODC.MATL_ID

    WHERE
        OOL.OPEN_CNFRM_QTY > 0

    ) OPN

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = OPN.SHIP_TO_CUST_ID
        AND CUST.PRIM_SHIP_FACILITY_ID = OPN.FACILITY_ID

WHERE
    OPN.SCHED_LINE_NBR = 1
    AND (OPN.CUST_GRP2_CD IN ('MAN', 'NWC', '20M', 'YDN') OR (OPN.CUST_GRP2_CD = 'TLB' AND OPN.DELIV_PRTY_ID = '12'))
    AND OPN.SALES_ORG_CD IN ('N301', 'N311')

ORDER BY
    OPN.ORDER_FISCAL_YR
    , OPN.ORDER_ID
    , OPN.ORDER_LINE_NBR
    , OPN.SCHED_LINE_NBR
