SELECT
    'SLS_DOC' AS TBL_ID
    , 'CUST_ID' AS FIELD_ID
    , SHIP_TO_CUST_ID AS VAL_ID
    , 'EQ' AS OPERATOR_CD
    , 'E' AS INCLUDE_EXCLUDE_IND

FROM GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR
WHERE
    OWN_CUST_ID IN ('00A0000632', '00A0003088')
ORDER BY
    SHIP_TO_CUST_ID