SELECT
    TRIM(OD.ORDER_TYPE_ID) || '-' || TRIM(OD.SOLD_TO_CUST_ID) || '-' || TRIM(OD.CUST_PO_NBR) AS JOIN_KEY_CD
    , OD.ORDER_TYPE_ID AS SLS_DOC_TYPE_CD
    , OD.SOLD_TO_CUST_ID AS CUST_ID
    , OD.CUST_PO_NBR AS CUST_PO_NBR

FROM NA_BI_VWS.ORDER_DETAIL OD

WHERE
    OD.EXP_DT = CAST('5555-12-31' AS DATE)
    AND OD.ORDER_CAT_ID = 'C'
    --AND OD.ORDER_TYPE_ID IN ('ZOR', 'ZML', 'ZTA')
    --AND OD.ITEM_CAT_ID IN ('TAN', 'ZZML', 'TAMA')
    --AND OD.SCHD_LN_CTGY_CD IN ('CP', 'ZM')
    --AND OD.FACILITY_ID NOT IN ('N5US', 'N5CA')

    --AND OD.RO_PO_TYPE_IND = 'N'
    AND OD.SCHED_LINE_NBR = 1
    AND OD.ORDER_DT = CAST('2014-08-12' AS DATE)
    AND OD.ORDER_CRT_TM BETWEEN TIME '16:00:00' AND TIME '23:59:59'

GROUP BY
    1,2,3,4

ORDER BY
    2,3,4
;

SELECT
    TRIM(OD.ORDER_TYPE_ID) || '-' || TRIM(OD.SOLD_TO_CUST_ID) || '-' || TRIM(OD.CUST_PO_NBR) AS JOIN_KEY_CD
    , OD.MATL_ID
    , SUM(OD.ORDER_QTY) AS ORDER_QTY

FROM NA_BI_VWS.ORDER_DETAIL OD

WHERE
    OD.EXP_DT = CAST('5555-12-31' AS DATE)
    AND OD.ORDER_CAT_ID = 'C'
    --AND OD.ORDER_TYPE_ID IN ('ZOR', 'ZML', 'ZTA')
    --AND OD.ITEM_CAT_ID IN ('TAN', 'ZZML', 'TAMA')
    --AND OD.SCHD_LN_CTGY_CD IN ('CP', 'ZM')
    --AND OD.FACILITY_ID NOT IN ('N5US', 'N5CA')

    --AND OD.RO_PO_TYPE_IND = 'N'
    AND OD.SCHED_LINE_NBR = 1
    AND OD.ORDER_DT = CAST('2014-08-12' AS DATE)
    AND OD.ORDER_CRT_TM BETWEEN TIME '16:00:00' AND TIME '23:59:59'

GROUP BY
    1,2
    
ORDER BY
    1,2
