SELECT
    OD.ORDER_DT
    , EXTRACT(HOUR FROM OD.ORDER_CRT_TM) AS HDR_CRT_HOUR
    --, EXTRACT(MINUTE FROM OD.ORDER_CRT_TM) AS HDR_CRT_MIN

    , COUNT(*) AS ORDER_LN_CNT

FROM NA_BI_VWS.ORDER_DETAIL OD

WHERE
    OD.EXP_DT = CAST('5555-12-31' AS DATE)
    AND OD.ORDER_CAT_ID = 'C'
    AND OD.ORDER_DT >= CAST('2014-01-01' AS DATE)
    AND OD.SCHED_LINE_NBR = 1

GROUP BY 1,2--,3
ORDER BY 1,2--,3
