SELECT
    SD.FISCAL_YR,
    SD.SLS_DOC_ID,
    SDI.SLS_DOC_ITM_ID,
    
    SD.SRC_CRT_DT,
    SD.SRC_CRT_USR_ID,
    SD.SRC_UPD_DT,
    
    SD.OUTLN_AGRMNT_VLD_FRM_DT,
    SD.OUTLN_AGRMNT_VLD_TO_DT,
    
    SDI.MATL_ID,
    MATL.DESCR,
    MATL.PBU_NBR,
    MATL.PBU_NAME,
    
    NULLIF( SDI.REJ_REAS_ID, '' ) AS REJ_REAS_ID,
    SD.DELIV_BLK_CD,
    SD.SHIP_COND_CD,
    SD.CUST_PRCH_ORD_TYP_CD,
    SD.SLS_DOC_TYP_CD,
    SD.SD_DOC_CTGY_CD,
    
    SD.SHIP_TO_CUST_ID,
    CUST.CUST_NAME AS SHIP_TO_CUST_NAME,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,
    SD.SALES_ORG_CD,
    SD.CUST_GRP_ID_1,
    SD.CUST_GRP_ID_2,
    
    OOL.OPEN_CNFRM_QTY,
    OOL.UNCNFRM_QTY,
    OOL.BACK_ORDER_QTY,
    OOL.DEFER_QTY,
    OOL.IN_PROC_QTY,
    
    SUM( SDSL.SLS_UNIT_ORD_QTY ) AS ORDER_QTY,
    SUM( SDSL.SLS_UNIT_CNFRM_QTY ) AS CNFRM_QTY

FROM NA_BI_VWS.NAT_SLS_DOC SD

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM SDI
        ON SDI.SLS_DOC_ID = SD.SLS_DOC_ID
        AND SDI.ORIG_SYS_ID = SD.ORIG_SYS_ID
        AND SDI.EXP_DT = DATE '5555-12-31'

    INNER JOIN NA_BI_VWS.OPEN_ORDER_ORDLN_CURR OOL
        ON OOL.ORDER_ID = SD.SLS_DOC_ID
        AND OOL.ORDER_LINE_NBR = SDI.SLS_DOC_ITM_ID

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_SCHD_LN SDSL
        ON SDSL.SLS_DOC_ID = SD.SLS_DOC_ID
        AND SDSL.SLS_DOC_ITM_ID = SDI.SLS_DOC_ITM_ID
        AND SDSL.ORIG_SYS_ID = SD.ORIG_SYS_ID
        AND SDSL.EXP_DT = DATE '5555-12-31'        

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = SD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = SDI.MATL_ID

WHERE
    SD.OUTLN_AGRMNT_VLD_TO_DT < CURRENT_DATE
    AND SD.SLS_DOC_TYP_CD IN ( 'ZLS', 'ZLZ' )
    AND SD.EXP_DT = DATE '5555-12-31'
    AND NULLIF( SDI.REJ_REAS_ID, '' ) IS NULL -- SCHEDULING AGREEMENTS THAT ARE NOT REJECTED BY THEIR 'VALID TO' DATE
    AND SD.ORIG_SYS_ID = 2

GROUP BY
    SD.FISCAL_YR,
    SD.SLS_DOC_ID,
    SDI.SLS_DOC_ITM_ID,
    
    SD.SRC_CRT_DT,
    SD.SRC_CRT_USR_ID,
    SD.SRC_UPD_DT,
    
    SD.OUTLN_AGRMNT_VLD_FRM_DT,
    SD.OUTLN_AGRMNT_VLD_TO_DT,
    
    SDI.MATL_ID,
    MATL.DESCR,
    MATL.PBU_NBR,
    MATL.PBU_NAME,
    
    SDI.REJ_REAS_ID, 
    SD.DELIV_BLK_CD,
    SD.SHIP_COND_CD,
    SD.CUST_PRCH_ORD_TYP_CD,
    SD.SLS_DOC_TYP_CD,
    SD.SD_DOC_CTGY_CD,
    
    SD.SHIP_TO_CUST_ID,
    CUST.CUST_NAME,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,
    SD.SALES_ORG_CD,
    SD.CUST_GRP_ID_1,
    SD.CUST_GRP_ID_2,
    
    OOL.OPEN_CNFRM_QTY,
    OOL.UNCNFRM_QTY,
    OOL.BACK_ORDER_QTY,
    OOL.DEFER_QTY,
    OOL.IN_PROC_QTY
    
HAVING
    CNFRM_QTY < ORDER_QTY