WITH TLB_BOL_SMRY
    (
    
    FISCAL_YR
    , BILL_LADING_ID
    , SHIP_FACILITY_ID
    , SHIP_TO_CUST_ID
    , DELIV_GRP_CD
    , DELIV_DT
    , MATL_CNT
    , WT_UNIT_MEAS_ID
    , GROSS_WT
    , VOL_UNIT_MEAS_ID
    , VOL
    , CMPR_VOL
    
    ) AS (
SELECT
    DL.FISCAL_YR
    , DL.BILL_LADING_ID
    
    , DL.DELIV_LINE_FACILITY_ID AS SHIP_FACILITY_ID
    , DL.SHIP_TO_CUST_ID
    , DL.DELIV_GRP_CD
    
    , DL.DELIV_DT
    
    , COUNT(DISTINCT DL.MATL_ID) AS MATL_CNT

    , DL.WT_UNIT_MEAS_ID
    , SUM(DL.GROSS_WT) AS GROSS_WT

    , DL.VOL_UNIT_MEAS_ID
    , SUM(DL.VOL) AS VOL
    , CAST(SUM(DL.VOL * MC.CMPRS_FCTR_QTY) AS DECIMAL(15,3)) AS CMPR_VOL

FROM NA_BI_VWS.DELIV_LN_SMRY DL

    INNER JOIN NA_BI_VWS.TL_CMPRS_MATL_LVL MC
        ON MC.MATL_ID = DL.MATL_ID

WHERE
    DL.DELIV_CAT_ID = 'J'
    AND DL.GOODS_ISS_IND = 'Y'
    AND DL.CUST_GRP2_CD = 'TLB'
    AND DL.DELIV_GRP_CD > '000'
    AND DL.DELIV_QTY > 0
    AND DL.ACTL_GOODS_ISS_DT IS NOT NULL
    AND DL.ACTL_GOODS_ISS_DT BETWEEN CURRENT_DATE-14 AND CURRENT_DATE-1

GROUP BY
    DL.FISCAL_YR
    , DL.BILL_LADING_ID
    , DL.DELIV_LINE_FACILITY_ID
    , DL.SHIP_TO_CUST_ID
    , DL.DELIV_GRP_CD
    , DL.DELIV_DT
    , DL.WT_UNIT_MEAS_ID
    , DL.VOL_UNIT_MEAS_ID
    
    ) -- END NAMED QUERY TLB_BOL_SMRY
    
SELECT
    BOL.FISCAL_YR
    , BOL.BILL_LADING_ID
    , BOL.SHIP_FACILITY_ID
    , BOL.SHIP_TO_CUST_ID
    , BOL.DELIV_GRP_CD
    , BOL.DELIV_DT
    , BOL.MATL_CNT
    , BOL.WT_UNIT_MEAS_ID
    , BOL.GROSS_WT
    , BOL.VOL_UNIT_MEAS_ID
    , BOL.VOL
    , BOL.CMPR_VOL

FROM TLB_BOL_SMRY BOL

ORDER BY
    BOL.SHIP_TO_CUST_ID
    , BOL.DELIV_GRP_CD
    , BOL.DELIV_DT

