SELECT
    DDI.FISCAL_YR
    , DDI.DELIV_DOC_ID
    , DDI.DELIV_DOC_ITM_ID
    
    , STA.GOODS_MVT_STA_CD
    , ROW_NUMBER() OVER (PARTITION BY MATL.PBU_NBR, MATL.EXT_MATL_GRP_ID ORDER BY CALC_DEFICIT_QTY, DD.DELIV_DT, DDI.ACTL_DELIV_QTY DESC) AS ITEM_RANKING
    
    , TRIM(DD.BILL_LADING_ID) AS BILL_LADING_ID
    , TRIM(REGEXP_SUBSTR(DD.BILL_LADING_ID, '([0-9a-zA-Z]+)', 1, 1, 'I')) AS BOL_SUBSTR_1
    , TRIM(REGEXP_SUBSTR(DD.BILL_LADING_ID, '([0-9a-zA-Z]+)', 1, 2, 'I')) AS BOL_SUBSTR_2
    
    , DD.MOT_SHIP_ID

    , DDI.FACILITY_ID
    , FAC.FACILITY_NAME
    , DD.SHIP_RCVE_PT_CD
    
    , ZEROIFNULL(INV.TOT_QTY) AS ON_HAND_INV_QTY
    , ZEROIFNULL(OO.OPEN_CONFIRMED_QTY) AS OPEN_CNFRM_QTY
    , ZEROIFNULL(OO.UNCONFIRMED_QTY) AS UNCNFRM_QTY
    , ZEROIFNULL(OO.BACKORDER_QTY) AS BACK_ORDER_QTY
    
    , ON_HAND_INV_QTY - ZEROIFNULL(OO.TOTAL_OPEN_QTY) AS CALC_DEFICIT_QTY
    
    , DD.SRC_CRT_TS
    , DD.DELIV_DT
    
    , DD.VEND_ID
    , VEND.VEND_NM AS VEND_NAME
    , VEND.CNTRY_NAME_CD
    
    , DDI.MATL_ID
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , MATL.EXT_MATL_GRP_ID
    , DDI.BATCH_NBR
    , DDI.MATL_HIER_ID
    , MATL.PBU_NBR
    , MATL.PBU_NBR || ' - ' || MATL.PBU_NAME AS PBU
    , MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY
    , MATL.MKT_CTGY_PROD_LINE_NBR || ' - ' || MATL.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE
    
    , DDI.BASE_UOM_CD
    , DDI.ACTL_DELIV_QTY
    
    , DDI.WT_UOM_CD
    , DDI.TOT_GROSS_WT_QTY
    , DD.TOT_WT_QTY
    
    , DDI.SD_DOC_CTGY_CD AS ORDER_CAT_ID
    , DDI.SLS_DOC_ID
    , DDI.SLS_DOC_ITM_ID
    
    , DD.SD_DOC_CTGY_CD AS DELIV_CAT_ID
    , DD.DELIV_TYP_CD AS DELIV_TYPE_ID
    , DD.INCOTERM_CD_1
    , DD.INCOTERM_CD_2

FROM NA_BI_VWS.SD_DOC_STA STA

    INNER JOIN GDYR_BI_VWS.DELIV_DOC_CURR DD
        ON DD.FISCAL_YR = STA.FISCAL_YR
        AND DD.DELIV_DOC_ID = STA.SD_DOC_ID
        AND DD.ORIG_SYS_ID = STA.ORIG_SYS_ID
        AND DD.SD_DOC_CTGY_CD = '7'

    INNER JOIN NA_BI_VWS.NAT_DELIV_DOC_ITM_CURR DDI
        ON DDI.FISCAL_YR = DD.FISCAL_YR
        AND DDI.DELIV_DOC_ID = DD.DELIV_DOC_ID
        AND DDI.ACTL_DELIV_QTY > 0

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FAC
        ON FAC.FACILITY_ID = DDI.FACILITY_ID
        AND FAC.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND FAC.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.VENDOR_EN_CURR VEND
        ON VEND.VEND_ID = DD.VEND_ID
        AND VEND.ORIG_SYS_ID = 2

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = DDI.MATL_ID
        AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
        AND MATL.SUPER_BRAND_ID IN ('01', '02', '03', '05')
        AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')

    LEFT OUTER JOIN NA_BI_VWS.FACILITY_MATL_INVENTORY INV
        ON INV.FACILITY_ID = DDI.FACILITY_ID
        AND INV.MATL_ID = DDI.MATL_ID
        AND INV.DAY_DT = CURRENT_DATE-1

    LEFT OUTER JOIN (
            SELECT
                ODC.MATL_ID
                , ODC.FACILITY_ID
                , SUM(ZEROIFNULL(OOL.OPEN_CNFRM_QTY)) AS OPEN_CONFIRMED_QTY
                , SUM(ZEROIFNULL(OOL.UNCNFRM_QTY)) AS UNCONFIRMED_QTY
                , SUM(ZEROIFNULL(OOL.BACK_ORDER_QTY)) AS BACKORDER_QTY
                , OPEN_CONFIRMED_QTY + UNCONFIRMED_QTY + BACKORDER_QTY AS TOTAL_OPEN_QTY

            FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL

                INNER JOIN NA_BI_VWS.ORDER_DETAIL ODC
                    ON ODC.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
                    AND ODC.ORDER_ID = OOL.ORDER_ID
                    AND ODC.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
                    AND ODC.SCHED_LINE_NBR = 1
                    AND ODC.EXP_DT = DATE '5555-12-31'
                    AND ODC.ORDER_CAT_ID = 'C'
                    AND ODC.RO_PO_TYPE_IND = 'N'
                    AND ODC.ORDER_FISCAL_YR >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-2 AS CHAR(4))

            WHERE
                (OOL.OPEN_CNFRM_QTY > 0
                OR OOL.UNCNFRM_QTY > 0
                OR OOL.BACK_ORDER_QTY > 0)

            GROUP BY
                ODC.MATL_ID
                , ODC.FACILITY_ID
            ) OO
        ON OO.MATL_ID = DDI.MATL_ID
        AND OO.FACILITY_ID = DDI.FACILITY_ID

WHERE
    STA.DOC_CTGY_ID = '7'
    AND STA.EXP_DT = DATE '5555-12-31'
    AND STA.GOODS_MVT_STA_CD IN ('A', 'B')

ORDER BY
     MATL.PBU_NBR
     , MATL.EXT_MATL_GRP_ID
     , ITEM_RANKING
