SELECT
    Q.DOC_TYPE
    , CASE Q.DOC_TYPE
        WHEN 'TI' THEN 'Total Inventory'
        WHEN 'DN' THEN 'Delivery Note'
        WHEN 'SA' THEN 'Scheduling Agreement'
        WHEN 'RO' THEN 'Reserve Order'
        WHEN 'SO' THEN 'Sales Order'
        WHEN 'TR' THEN 'Stock Transfer'
        ELSE 'Unknown'
        END AS DOC_DESCR
    , CASE Q.DOC_TYPE
        WHEN 'TI' THEN 0
        WHEN 'DN' THEN 20
        WHEN 'SA' THEN 40
        WHEN 'RO' THEN 60
        WHEN 'SO' THEN 80
        WHEN 'TR' THEN 100
        ELSE 200
        END  AS DOC_SORT_KEY
    , Q.AVAIL_DT
    , Q.FUTURE_REQ_IND
    , Q.FACILITY_ID
    , F.FACILITY_NAME
    , Q.MATL_ID
    , M.MATL_NO_8 || ' - ' || M.DESCR AS MATL_DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME
    , Q.TOT_QTY
    , Q.REQTS_QTY
    , SUM(Q.TOT_QTY + Q.REQTS_QTY) OVER (PARTITION BY Q.MATL_ID, Q.FACILITY_ID ORDER BY Q.AVAIL_DT ASC, Q.TOT_QTY DESC, Q.REQTS_QTY ASC ROWS UNBOUNDED PRECEDING) AS AVAIL_QTY
    , CASE WHEN AVAIL_QTY > 0 THEN Q.FUTURE_REQ_IND ELSE '' END AS IMPROVABLE_IND

FROM (

SELECT
    CAST('TI' AS CHAR(2)) AS DOC_TYPE
    , CURRENT_DATE-1 AS AVAIL_DT
    , CAST('' AS CHAR(1)) AS FUTURE_REQ_IND
    , I.FACILITY_ID
    , I.MATL_ID
    , I.TOT_QTY
    , CAST(0 AS DECIMAL(15,3)) AS REQTS_QTY
    --, -1 * ZEROIFNULL(D.DN_QTY) AS REQTS_QTY

FROM NA_BI_VWS.FACL_MATL_INV I

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = I.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = I.MATL_ID
        AND M.PBU_NBR = '01'

WHERE
    I.DAY_DT = CURRENT_DATE-1
    --AND I.MATL_ID = '000000000000019032'

UNION ALL

SELECT
    CAST('DN' AS CHAR(2)) AS DOC_TYPE
    , CURRENT_DATE-1 AS AVAIL_DT
    , CAST('' AS CHAR(1)) AS FUTURE_REQ_IND
    , DD.DELIV_LINE_FACILITY_ID
    , DD.MATL_ID
    , 0 AS TOT_QTY
    , -1 * SUM(DD.DELIV_QTY) AS REQTS_QTY

FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DD

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = DD.DELIV_LINE_FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = DD.MATL_ID
        AND M.PBU_NBR = '01'

WHERE
    DD.ACTL_GOODS_ISS_DT IS NULL
    --AND DD.MATL_ID = '000000000000019032'

GROUP BY
    DD.MATL_ID
    , DD.DELIV_LINE_FACILITY_ID

UNION ALL

SELECT
    CAST('TR' AS CHAR(2)) AS DOC_TYPE
    , D.DELIV_DT AS AVAIL_DT
    , CAST('' AS CHAR(1)) AS FUTURE_REQ_IND
    , PDI.FACILITY_ID
    , D.MATL_ID
    , 0 AS TOT_QTY
    , SUM(D.DELIV_QTY) AS REQTS_QTY

FROM NA_VWS.DELIV_DTL D

    INNER JOIN GDYR_BI_VWS.PRCH_DOC_CURR PD
        ON PD.PRCH_DOC_ID = D.ORDER_ID
        AND PD.ORIG_SYS_ID = 2
        AND PD.CO_CD IN ('N101', 'N102', 'N266')
        AND PD.PRCH_TYPE_CD IN ('ZB', 'ZS', 'IB', 'CS', 'CB', 'UB')

    INNER JOIN GDYR_BI_VWS.PRCH_DOC_ITM_CURR PDI
        ON PDI.PRCH_DOC_ID = D.ORDER_ID
        AND PDI.PRCH_DOC_ITM_ID = D.ORDER_LINE_NBR
        AND PDI.ORIG_SYS_ID = 2

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = PDI.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = D.MATL_ID
        AND M.PBU_NBR = '01'

WHERE
    D.EXP_DT = CAST('5555-12-31' AS DATE)
    AND D.OUTBOUND_DELIV_IND = 'N'
    AND D.ACTL_GOODS_ISS_DT IS NULL
    AND D.DELIV_DT > CURRENT_DATE
    --AND D.MATL_ID = '000000000000019032'

GROUP BY
    D.DELIV_DT
    , PDI.FACILITY_ID
    , D.MATL_ID

UNION ALL

SELECT
    CAST(CASE WHEN OD.PO_TYPE_ID <> 'RO' THEN 'SO' ELSE 'RO' END AS CHAR(2)) AS DOC_TYPE
    , CASE
        WHEN OO.OPEN_CNFRM_QTY > 0 AND OD.PLN_MATL_AVL_DT >= CURRENT_DATE
            THEN OD.PLN_MATL_AVL_DT
        WHEN OO.OPEN_CNFRM_QTY > 0 AND OD.PLN_MATL_AVL_DT < CURRENT_DATE
            THEN CURRENT_DATE
        ELSE CAST('5555-12-31' AS DATE)
        END AS AVAIL_DT
    , CAST(CASE 
        WHEN OD.FRST_PLN_GOODS_ISS_DT >= ADD_MONTHS(CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 1, 1)
            THEN 'Y'
        ELSE 'N'
        END AS CHAR(1)) AS FUTURE_REQ_IND
    , OD.FACILITY_ID
    , OD.MATL_ID
    , 0 AS TOT_QTY
    , -1 * SUM(OO.OPEN_CNFRM_QTY + OO.UNCNFRM_QTY + OO.BACK_ORDER_QTY + OO.DEFER_QTY + OO.WAIT_LIST_QTY + OO.OTHR_ORDER_QTY) AS REQTS_QTY

FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OO

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = OO.ORDER_FISCAL_YR
        AND OD.ORDER_ID = OO.ORDER_ID
        AND OD.ORDER_LINE_NBR = OO.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = OO.SCHED_LINE_NBR
        AND OD.EXP_DT = CAST('5555-12-31' AS DATE)
        AND OD.ORDER_CAT_ID = 'C'

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = OD.MATL_ID
        AND M.PBU_NBR = '01'

WHERE
    (
        OO.OPEN_CNFRM_QTY > 0
        OR OO.UNCNFRM_QTY > 0
        OR OO.BACK_ORDER_QTY > 0
        OR OO.DEFER_QTY > 0
        OR OO.WAIT_LIST_QTY > 0
        OR OO.OTHR_ORDER_QTY > 0
    )
    --AND OD.MATL_ID = '000000000000019032'

GROUP BY
    DOC_TYPE
    , AVAIL_DT
    , FUTURE_REQ_IND
    , OD.FACILITY_ID
    , OD.MATL_ID

    ) Q
    
    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = Q.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = Q.MATL_ID
        AND M.PBU_NBR = '01'