SELECT
    S.QRY_TYPE
    , S.SNAPSHOT_DT

    --, S.SHIP_TO_CUST_ID
    --, S.CUST_NAME
    --, S.OWN_CUST_ID
    --, S.OWN_CUST_NAME
    --, S.SALES_ORG_CD
    --, S.SALES_ORG_NAME
    --, S.DISTR_CHAN_CD
    --, S.DISTR_CHAN_NAME
    --, S.CUST_GRP_ID
    --, S.CUST_GRP_NAME

    --, S.MATL_ID
    --, S.MATL_NO_8
    --, S.DESCR
    --, S.PBU_NBR
    --, S.PBU_NAME
    --, S.MKT_AREA_NBR
    --, S.MKT_AREA_NAME
    --, S.MKT_CTGY_MKT_AREA_NBR
    --, S.MKT_CTGY_MKT_AREA_NAME
    --, S.PROD_LINE_NBR
    --, S.PROD_LINE_NAME
    --, S.EXT_MATL_GRP_ID
    --, S.MATL_TYPE_ID
    --, S.MATL_STA_ID
    --, S.MATL_STA_DT
    --, S.STK_CLASS_ID
    --, S.STK_CLASS_DT

    --, S.FACILITY_ID
    --, S.FACILITY_NAME

    --, S.REPL_OE_IND
    --, S.FRDD_IN_MNTH_FLG
    --, S.FRDD_FPGI_IN_MNTH_FLG

    --, S.ORDER_CAT_ID
    --, S.ORDER_TYPE_ID
    --, S.REJ_REAS_ID
    --, S.PO_TYPE_ID

    --, S.ORDER_DT
    --, S.ORDER_CRT_TM
    --, S.ORDER_LN_CRT_DT
    --, S.ORDER_LN_CRT_TM

    , S.QTY_UNIT_MEAS_ID
    , SUM(S.ORDER_QTY) AS ORDER_QTY
    , SUM(S.ADJ_ORDER_QTY) AS ADJ_ORDER_QTY
    , SUM(S.OPEN_CNFRM_QTY) AS TOT_OPEN_CNFRM_QTY
    , SUM(S.OPEN_CNFRM_IN_MNTH_QTY) AS OPEN_CNFRM_IN_MNTH_QTY
    , SUM(S.OPEN_CNFRM_AFTER_MNTH_QTY) AS OPEN_CNFRM_AFTER_MNTH_QTY
    , SUM(S.UNCNFRM_QTY) AS UNCNFRM_QTY
    , SUM(S.WAIT_LIST_QTY) AS WAIT_LIST_QTY
    , SUM(S.OTHER_ORDER_QTY) AS OTHER_ORDER_QTY
    , SUM(S.IN_PROC_PGMV_IN_MNTH_QTY) AS IN_PROC_PGMV_IN_MNTH_QTY
    , SUM(S.IN_PROC_PGMV_AFTER_MNTH_QTY) AS IN_PROC_PGMV_AFTER_MNTH_QTY
    , SUM(S.AGID_IN_MNTH_QTY) AS AGID_IN_MNTH_QTY
    , SUM(S.AGID_AFTER_MNTH_QTY) AS AGID_AFTER_MNTH_QTY

    , SUM(S.OPEN_QTY) AS TOT_OPEN_QTY
    , SUM(S.DELIV_QTY) AS TOT_DELIV_QTY
    , SUM(S.CANCEL_QTY) AS NET_CANCEL_QTY

FROM (

SELECT
    O.QRY_TYPE
    , O.SNAPSHOT_DT
    , O.SNAPSHOT_MONTH_DT
    , O.NEXT_MONTH_DT
    , O.ORDER_FISCAL_YR
    , O.ORDER_ID
    , O.ORDER_LINE_NBR

    , O.SHIP_TO_CUST_ID
    , O.CUST_NAME
    , O.OWN_CUST_ID
    , O.OWN_CUST_NAME
    , O.SALES_ORG_CD
    , O.SALES_ORG_NAME
    , O.DISTR_CHAN_CD
    , O.DISTR_CHAN_NAME
    , O.CUST_GRP_ID
    , O.CUST_GRP_NAME

    , O.MATL_ID
    , O.MATL_NO_8
    , O.DESCR
    , O.PBU_NBR
    , O.PBU_NAME
    , O.MKT_AREA_NBR
    , O.MKT_AREA_NAME
    , O.MKT_CTGY_MKT_AREA_NBR
    , O.MKT_CTGY_MKT_AREA_NAME
    , O.PROD_LINE_NBR
    , O.PROD_LINE_NAME
    , O.EXT_MATL_GRP_ID
    , O.MATL_TYPE_ID
    , O.MATL_STA_ID
    , O.MATL_STA_DT
    , O.STK_CLASS_ID
    , O.STK_CLASS_DT

    , O.FACILITY_ID
    , O.FACILITY_NAME

    , O.REPL_OE_IND
    , O.FRDD_IN_MNTH_FLG
    , O.FRDD_FPGI_IN_MNTH_FLG

    , O.ORDER_CAT_ID
    , O.ORDER_TYPE_ID
    , O.REJ_REAS_ID
    , O.PO_TYPE_ID

    , O.ORDER_DT
    , O.ORDER_CRT_TM
    , O.ORDER_LN_CRT_DT
    , O.ORDER_LN_CRT_TM

    , O.QTY_UNIT_MEAS_ID
    , O.ORDER_QTY
    , CASE
        WHEN ZEROIFNULL(SUM(DD.DELIV_QTY)) > O.ORDER_QTY
            THEN ZEROIFNULL(SUM(DD.DELIV_QTY))
        ELSE O.ORDER_QTY
        END AS ADJ_ORDER_QTY
    , O.OPEN_CNFRM_QTY
    , O.OPEN_CNFRM_IN_MNTH_QTY
    , O.OPEN_CNFRM_AFTER_MNTH_QTY
    , O.UNCNFRM_QTY
    , O.WAIT_LIST_QTY
    , O.OTHER_ORDER_QTY
    , ZEROIFNULL(SUM(CASE WHEN DD.ACTL_GOODS_ISS_DT IS NULL AND DD.PLN_GOODS_MVT_DT < O.NEXT_MONTH_DT THEN DIP.QTY_TO_SHIP ELSE 0 END)) AS IN_PROC_PGMV_IN_MNTH_QTY
    , ZEROIFNULL(SUM(CASE WHEN DD.ACTL_GOODS_ISS_DT IS NULL AND DD.PLN_GOODS_MVT_DT >= O.NEXT_MONTH_DT THEN DIP.QTY_TO_SHIP ELSE 0 END)) AS IN_PROC_PGMV_AFTER_MNTH_QTY
    , ZEROIFNULL(SUM(CASE WHEN DD.ACTL_GOODS_ISS_DT IS NOT NULL AND DD.ACTL_GOODS_ISS_DT < O.NEXT_MONTH_DT THEN DD.DELIV_QTY ELSE 0 END)) AS AGID_IN_MNTH_QTY
    , ZEROIFNULL(SUM(CASE WHEN DD.ACTL_GOODS_ISS_DT IS NOT NULL AND DD.ACTL_GOODS_ISS_DT >= O.NEXT_MONTH_DT THEN DD.DELIV_QTY ELSE 0 END)) AS AGID_AFTER_MNTH_QTY

    , O.OPEN_CNFRM_QTY + O.UNCNFRM_QTY + O.WAIT_LIST_QTY + O.OTHER_ORDER_QTY AS OPEN_QTY
    , ZEROIFNULL(SUM(DD.DELIV_QTY)) AS DELIV_QTY
    
    , CASE
        WHEN O.REJ_REAS_ID > '' AND O.ORDER_QTY > ZEROIFNULL(SUM(DD.DELIV_QTY))
            THEN O.ORDER_QTY - ZEROIFNULL(SUM(DD.DELIV_QTY))
        ELSE 0
        END AS CANCEL_QTY

FROM (

SELECT
    CAST('Order Create Date' AS VARCHAR(55)) AS QRY_TYPE
    , CAL.DAY_DATE AS SNAPSHOT_DT
    , CAL.MONTH_DT AS SNAPSHOT_MONTH_DT
    , ADD_MONTHS(CAL.MONTH_DT, 1) AS NEXT_MONTH_DT
    , OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , OD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME

    , OD.MATL_ID
    , M.MATL_NO_8
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME
    , M.EXT_MATL_GRP_ID
    , M.MATL_TYPE_ID
    , M.MATL_STA_ID
    , M.MATL_STA_DT
    , M.STK_CLASS_ID
    , M.STK_CLASS_DT

    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , CASE
        WHEN C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N307', 'N317', 'N336') OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN ('30', '31'))
            THEN 'R'
        ELSE 'O'
        END REPL_OE_IND
    , CASE WHEN OD.FRST_RDD < NEXT_MONTH_DT THEN 'Y' ELSE 'N' END AS FRDD_IN_MNTH_FLG
    , CASE WHEN OD.FRST_PLN_GOODS_ISS_DT < NEXT_MONTH_DT THEN 'Y' ELSE 'N' END AS FRDD_FPGI_IN_MNTH_FLG

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID
    , OD.REJ_REAS_ID
    , OD.PO_TYPE_ID

    , OD.ORDER_DT
    , OD.ORDER_CRT_TM
    , OD.ORDER_LN_CRT_DT
    , OD.ORDER_LN_CRT_TM

    , OD.QTY_UNIT_MEAS_ID
    , MAX(OD.ORDER_QTY) AS ORDER_QTY
    , ZEROIFNULL(SUM(OOL.OPEN_CNFRM_QTY)) AS OPEN_CNFRM_QTY
    , ZEROIFNULL(SUM(CASE WHEN OD.PLN_GOODS_ISS_DT < NEXT_MONTH_DT THEN OOL.OPEN_CNFRM_QTY ELSE 0 END)) AS OPEN_CNFRM_IN_MNTH_QTY
    , ZEROIFNULL(SUM(CASE WHEN OD.PLN_GOODS_ISS_DT >= NEXT_MONTH_DT THEN OOL.OPEN_CNFRM_QTY ELSE 0 END)) AS OPEN_CNFRM_AFTER_MNTH_QTY
    , ZEROIFNULL(SUM(OOL.UNCNFRM_QTY)) + ZEROIFNULL(SUM(OOL.BACK_ORDER_QTY)) AS UNCNFRM_QTY
    , ZEROIFNULL(SUM(OOL.WAIT_LIST_QTY)) AS WAIT_LIST_QTY
    , ZEROIFNULL(SUM(OOL.DEFER_QTY)) + ZEROIFNULL(SUM(OOL.OTHR_ORDER_QTY)) AS OTHER_ORDER_QTY

FROM NA_BI_VWS.ORDER_DETAIL OD

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE = OD.ORDER_DT

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID
        AND M.PBU_NBR IN ('01', '03')
        AND M.MKT_AREA_NBR <> '04'
        AND M.EXT_MATL_GRP_ID = 'TIRE'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    LEFT OUTER JOIN NA_VWS.OPEN_ORDER_SCHDLN OOL
        ON OOL.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = OD.ORDER_ID
        AND OOL.ORDER_LINE_NBR = OD.ORDER_LINE_NBR
        AND OOL.SCHED_LINE_NBR = OD.SCHED_LINE_NBR
        AND OD.ORDER_DT BETWEEN OOL.EFF_DT AND OOL.EXP_DT

WHERE
    OD.ORDER_DT BETWEEN OD.EFF_DT AND OD.EXP_DT
    AND OD.ORDER_DT BETWEEN DATE  '2015-01-01' AND CURRENT_DATE-1
    AND OD.RO_PO_TYPE_IND = 'N'
    AND REPL_OE_IND = 'R'

GROUP BY
    SNAPSHOT_DT
    , SNAPSHOT_MONTH_DT
    , NEXT_MONTH_DT
    , OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , OD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME

    , OD.MATL_ID
    , M.MATL_NO_8
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME
    , M.EXT_MATL_GRP_ID
    , M.MATL_TYPE_ID
    , M.MATL_STA_ID
    , M.MATL_STA_DT
    , M.STK_CLASS_ID
    , M.STK_CLASS_DT

    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , REPL_OE_IND
    , FRDD_IN_MNTH_FLG
    , FRDD_FPGI_IN_MNTH_FLG

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID
    , OD.REJ_REAS_ID
    , OD.PO_TYPE_ID

    , OD.ORDER_DT
    , OD.ORDER_CRT_TM
    , OD.ORDER_LN_CRT_DT
    , OD.ORDER_LN_CRT_TM

    , OD.QTY_UNIT_MEAS_ID

    ) O

    LEFT OUTER JOIN (
        NA_VWS.DELIV_DTL DD

        LEFT OUTER JOIN GDYR_VWS.DELIV_IN_PROC DIP
            ON DIP.DELIV_FISCAL_YR = DD.FISCAL_YR
            AND DIP.DELIV_ID = DD.DELIV_ID
            AND DIP.DELIV_LINE_NBR = DD.DELIV_LINE_NBR
            AND DIP.ORIG_SYS_ID = 2
        )
        ON DD.ORDER_FISCAL_YR = O.ORDER_FISCAL_YR
        AND DD.ORDER_ID = O.ORDER_ID
        AND DD.ORDER_LINE_NBR = O.ORDER_LINE_NBR
        AND O.SNAPSHOT_DT BETWEEN DD.EFF_DT AND DD.EXP_DT
        AND O.SNAPSHOT_DT BETWEEN DIP.EFF_DT AND DIP.EXP_DT

GROUP BY
    O.QRY_TYPE
    , O.SNAPSHOT_DT
    , O.SNAPSHOT_MONTH_DT
    , O.NEXT_MONTH_DT
    , O.ORDER_FISCAL_YR
    , O.ORDER_ID
    , O.ORDER_LINE_NBR

    , O.SHIP_TO_CUST_ID
    , O.CUST_NAME
    , O.OWN_CUST_ID
    , O.OWN_CUST_NAME
    , O.SALES_ORG_CD
    , O.SALES_ORG_NAME
    , O.DISTR_CHAN_CD
    , O.DISTR_CHAN_NAME
    , O.CUST_GRP_ID
    , O.CUST_GRP_NAME

    , O.MATL_ID
    , O.MATL_NO_8
    , O.DESCR
    , O.PBU_NBR
    , O.PBU_NAME
    , O.MKT_AREA_NBR
    , O.MKT_AREA_NAME
    , O.MKT_CTGY_MKT_AREA_NBR
    , O.MKT_CTGY_MKT_AREA_NAME
    , O.PROD_LINE_NBR
    , O.PROD_LINE_NAME
    , O.EXT_MATL_GRP_ID
    , O.MATL_TYPE_ID
    , O.MATL_STA_ID
    , O.MATL_STA_DT
    , O.STK_CLASS_ID
    , O.STK_CLASS_DT

    , O.FACILITY_ID
    , O.FACILITY_NAME

    , O.REPL_OE_IND
    , O.FRDD_IN_MNTH_FLG
    , O.FRDD_FPGI_IN_MNTH_FLG

    , O.ORDER_CAT_ID
    , O.ORDER_TYPE_ID
    , O.REJ_REAS_ID
    , O.PO_TYPE_ID

    , O.ORDER_DT
    , O.ORDER_CRT_TM
    , O.ORDER_LN_CRT_DT
    , O.ORDER_LN_CRT_TM

    , O.QTY_UNIT_MEAS_ID
    , O.ORDER_QTY
    , O.OPEN_CNFRM_QTY
    , O.OPEN_CNFRM_IN_MNTH_QTY
    , O.OPEN_CNFRM_AFTER_MNTH_QTY
    , O.UNCNFRM_QTY
    , O.WAIT_LIST_QTY
    , O.OTHER_ORDER_QTY

    ) S

GROUP BY
    S.QRY_TYPE
    , S.SNAPSHOT_DT

    , S.SHIP_TO_CUST_ID
    , S.CUST_NAME
    , S.OWN_CUST_ID
    , S.OWN_CUST_NAME
    , S.SALES_ORG_CD
    , S.SALES_ORG_NAME
    , S.DISTR_CHAN_CD
    , S.DISTR_CHAN_NAME
    , S.CUST_GRP_ID
    , S.CUST_GRP_NAME

    , S.MATL_ID
    , S.MATL_NO_8
    , S.DESCR
    , S.PBU_NBR
    , S.PBU_NAME
    , S.MKT_AREA_NBR
    , S.MKT_AREA_NAME
    , S.MKT_CTGY_MKT_AREA_NBR
    , S.MKT_CTGY_MKT_AREA_NAME
    , S.PROD_LINE_NBR
    , S.PROD_LINE_NAME
    , S.EXT_MATL_GRP_ID
    , S.MATL_TYPE_ID
    , S.MATL_STA_ID
    , S.MATL_STA_DT
    , S.STK_CLASS_ID
    , S.STK_CLASS_DT

    , S.FACILITY_ID
    , S.FACILITY_NAME

    , S.REPL_OE_IND
    , S.FRDD_IN_MNTH_FLG
    , S.FRDD_FPGI_IN_MNTH_FLG

    , S.ORDER_CAT_ID
    , S.ORDER_TYPE_ID
    , S.REJ_REAS_ID
    , S.PO_TYPE_ID

    , S.ORDER_DT
    --, S.ORDER_CRT_TM
    , S.ORDER_LN_CRT_DT
    --, S.ORDER_LN_CRT_TM

    , S.QTY_UNIT_MEAS_ID

UNION ALL

SELECT
    S.QRY_TYPE
    , S.SNAPSHOT_DT

    , S.SHIP_TO_CUST_ID
    , S.CUST_NAME
    , S.OWN_CUST_ID
    , S.OWN_CUST_NAME
    , S.SALES_ORG_CD
    , S.SALES_ORG_NAME
    , S.DISTR_CHAN_CD
    , S.DISTR_CHAN_NAME
    , S.CUST_GRP_ID
    , S.CUST_GRP_NAME

    , S.MATL_ID
    , S.MATL_NO_8
    , S.DESCR
    , S.PBU_NBR
    , S.PBU_NAME
    , S.MKT_AREA_NBR
    , S.MKT_AREA_NAME
    , S.MKT_CTGY_MKT_AREA_NBR
    , S.MKT_CTGY_MKT_AREA_NAME
    , S.PROD_LINE_NBR
    , S.PROD_LINE_NAME
    , S.EXT_MATL_GRP_ID
    , S.MATL_TYPE_ID
    , S.MATL_STA_ID
    , S.MATL_STA_DT
    , S.STK_CLASS_ID
    , S.STK_CLASS_DT

    , S.FACILITY_ID
    , S.FACILITY_NAME

    , S.REPL_OE_IND
    , S.FRDD_IN_MNTH_FLG
    , S.FRDD_FPGI_IN_MNTH_FLG

    , S.ORDER_CAT_ID
    , S.ORDER_TYPE_ID
    , S.REJ_REAS_ID
    , S.PO_TYPE_ID

    , S.ORDER_DT
    --, S.ORDER_CRT_TM
    , S.ORDER_LN_CRT_DT
    --, S.ORDER_LN_CRT_TM

    , S.QTY_UNIT_MEAS_ID
    , SUM(S.ORDER_QTY) AS ORDER_QTY
    , SUM(S.ADJ_ORDER_QTY) AS ADJ_ORDER_QTY
    , SUM(S.OPEN_CNFRM_QTY) AS TOT_OPEN_CNFRM_QTY
    , SUM(S.OPEN_CNFRM_IN_MNTH_QTY) AS OPEN_CNFRM_IN_MNTH_QTY
    , SUM(S.OPEN_CNFRM_AFTER_MNTH_QTY) AS OPEN_CNFRM_AFTER_MNTH_QTY
    , SUM(S.UNCNFRM_QTY) AS UNCNFRM_QTY
    , SUM(S.WAIT_LIST_QTY) AS WAIT_LIST_QTY
    , SUM(S.OTHER_ORDER_QTY) AS OTHER_ORDER_QTY
    , SUM(S.IN_PROC_PGMV_IN_MNTH_QTY) AS IN_PROC_PGMV_IN_MNTH_QTY
    , SUM(S.IN_PROC_PGMV_AFTER_MNTH_QTY) AS IN_PROC_PGMV_AFTER_MNTH_QTY
    , SUM(S.AGID_IN_MNTH_QTY) AS AGID_IN_MNTH_QTY
    , SUM(S.AGID_AFTER_MNTH_QTY) AS AGID_AFTER_MNTH_QTY

    , SUM(S.OPEN_QTY) AS TOT_OPEN_QTY
    , SUM(S.DELIV_QTY) AS TOT_DELIV_QTY
    , SUM(S.CANCEL_QTY) AS NET_CANCEL_QTY

FROM (

SELECT
    O.QRY_TYPE
    , O.SNAPSHOT_DT
    , O.SNAPSHOT_MONTH_DT
    , O.NEXT_MONTH_DT
    , O.ORDER_FISCAL_YR
    , O.ORDER_ID
    , O.ORDER_LINE_NBR

    , O.SHIP_TO_CUST_ID
    , O.CUST_NAME
    , O.OWN_CUST_ID
    , O.OWN_CUST_NAME
    , O.SALES_ORG_CD
    , O.SALES_ORG_NAME
    , O.DISTR_CHAN_CD
    , O.DISTR_CHAN_NAME
    , O.CUST_GRP_ID
    , O.CUST_GRP_NAME

    , O.MATL_ID
    , O.MATL_NO_8
    , O.DESCR
    , O.PBU_NBR
    , O.PBU_NAME
    , O.MKT_AREA_NBR
    , O.MKT_AREA_NAME
    , O.MKT_CTGY_MKT_AREA_NBR
    , O.MKT_CTGY_MKT_AREA_NAME
    , O.PROD_LINE_NBR
    , O.PROD_LINE_NAME
    , O.EXT_MATL_GRP_ID
    , O.MATL_TYPE_ID
    , O.MATL_STA_ID
    , O.MATL_STA_DT
    , O.STK_CLASS_ID
    , O.STK_CLASS_DT

    , O.FACILITY_ID
    , O.FACILITY_NAME

    , O.REPL_OE_IND
    , O.FRDD_IN_MNTH_FLG
    , O.FRDD_FPGI_IN_MNTH_FLG

    , O.ORDER_CAT_ID
    , O.ORDER_TYPE_ID
    , O.REJ_REAS_ID
    , O.PO_TYPE_ID

    , O.ORDER_DT
    , O.ORDER_CRT_TM
    , O.ORDER_LN_CRT_DT
    , O.ORDER_LN_CRT_TM

    , O.QTY_UNIT_MEAS_ID
    , O.ORDER_QTY
    , CASE
        WHEN ZEROIFNULL(SUM(DD.DELIV_QTY)) > O.ORDER_QTY
            THEN ZEROIFNULL(SUM(DD.DELIV_QTY))
        ELSE O.ORDER_QTY
        END AS ADJ_ORDER_QTY
    , O.OPEN_CNFRM_QTY
    , O.OPEN_CNFRM_IN_MNTH_QTY
    , O.OPEN_CNFRM_AFTER_MNTH_QTY
    , O.UNCNFRM_QTY
    , O.WAIT_LIST_QTY
    , O.OTHER_ORDER_QTY
    , ZEROIFNULL(SUM(CASE WHEN DD.ACTL_GOODS_ISS_DT IS NULL AND DD.PLN_GOODS_MVT_DT < O.NEXT_MONTH_DT THEN DIP.QTY_TO_SHIP ELSE 0 END)) AS IN_PROC_PGMV_IN_MNTH_QTY
    , ZEROIFNULL(SUM(CASE WHEN DD.ACTL_GOODS_ISS_DT IS NULL AND DD.PLN_GOODS_MVT_DT >= O.NEXT_MONTH_DT THEN DIP.QTY_TO_SHIP ELSE 0 END)) AS IN_PROC_PGMV_AFTER_MNTH_QTY
    , ZEROIFNULL(SUM(CASE WHEN DD.ACTL_GOODS_ISS_DT IS NOT NULL AND DD.ACTL_GOODS_ISS_DT < O.NEXT_MONTH_DT THEN DD.DELIV_QTY ELSE 0 END)) AS AGID_IN_MNTH_QTY
    , ZEROIFNULL(SUM(CASE WHEN DD.ACTL_GOODS_ISS_DT IS NOT NULL AND DD.ACTL_GOODS_ISS_DT >= O.NEXT_MONTH_DT THEN DD.DELIV_QTY ELSE 0 END)) AS AGID_AFTER_MNTH_QTY

    , O.OPEN_CNFRM_QTY + O.UNCNFRM_QTY + O.WAIT_LIST_QTY + O.OTHER_ORDER_QTY AS OPEN_QTY
    , ZEROIFNULL(SUM(DD.DELIV_QTY)) AS DELIV_QTY
    
    , CASE
        WHEN O.REJ_REAS_ID > '' AND O.ORDER_QTY > ZEROIFNULL(SUM(DD.DELIV_QTY))
            THEN O.ORDER_QTY - ZEROIFNULL(SUM(DD.DELIV_QTY))
        ELSE 0
        END AS CANCEL_QTY

FROM (

SELECT
    CAST('Current Date' AS VARCHAR(55)) AS QRY_TYPE
    , CAL.DAY_DATE AS SNAPSHOT_DT
    , CAL.MONTH_DT AS SNAPSHOT_MONTH_DT
    , ADD_MONTHS(CAL.MONTH_DT, 1) AS NEXT_MONTH_DT
    , OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , OD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME

    , OD.MATL_ID
    , M.MATL_NO_8
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME
    , M.EXT_MATL_GRP_ID
    , M.MATL_TYPE_ID
    , M.MATL_STA_ID
    , M.MATL_STA_DT
    , M.STK_CLASS_ID
    , M.STK_CLASS_DT

    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , CASE
        WHEN C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N307', 'N317', 'N336') OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN ('30', '31'))
            THEN 'R'
        ELSE 'O'
        END REPL_OE_IND
    , CASE WHEN OD.FRST_RDD < NEXT_MONTH_DT THEN 'Y' ELSE 'N' END AS FRDD_IN_MNTH_FLG
    , CASE WHEN OD.FRST_PLN_GOODS_ISS_DT < NEXT_MONTH_DT THEN 'Y' ELSE 'N' END AS FRDD_FPGI_IN_MNTH_FLG

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID
    , OD.REJ_REAS_ID
    , OD.PO_TYPE_ID

    , OD.ORDER_DT
    , OD.ORDER_CRT_TM
    , OD.ORDER_LN_CRT_DT
    , OD.ORDER_LN_CRT_TM

    , OD.QTY_UNIT_MEAS_ID
    , MAX(OD.ORDER_QTY) AS ORDER_QTY
    , ZEROIFNULL(SUM(OOL.OPEN_CNFRM_QTY)) AS OPEN_CNFRM_QTY
    , ZEROIFNULL(SUM(CASE WHEN OD.PLN_GOODS_ISS_DT < NEXT_MONTH_DT THEN OOL.OPEN_CNFRM_QTY ELSE 0 END)) AS OPEN_CNFRM_IN_MNTH_QTY
    , ZEROIFNULL(SUM(CASE WHEN OD.PLN_GOODS_ISS_DT >= NEXT_MONTH_DT THEN OOL.OPEN_CNFRM_QTY ELSE 0 END)) AS OPEN_CNFRM_AFTER_MNTH_QTY
    , ZEROIFNULL(SUM(OOL.UNCNFRM_QTY)) + ZEROIFNULL(SUM(OOL.BACK_ORDER_QTY)) AS UNCNFRM_QTY
    , ZEROIFNULL(SUM(OOL.WAIT_LIST_QTY)) AS WAIT_LIST_QTY
    , ZEROIFNULL(SUM(OOL.DEFER_QTY)) + ZEROIFNULL(SUM(OOL.OTHR_ORDER_QTY)) AS OTHER_ORDER_QTY

FROM NA_BI_VWS.ORDER_DETAIL OD

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE = OD.ORDER_DT

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID
        AND M.PBU_NBR IN ('01', '03')
        AND M.MKT_AREA_NBR <> '04'
        AND M.EXT_MATL_GRP_ID = 'TIRE'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    LEFT OUTER JOIN NA_VWS.OPEN_ORDER_SCHDLN OOL
        ON OOL.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = OD.ORDER_ID
        AND OOL.ORDER_LINE_NBR = OD.ORDER_LINE_NBR
        AND OOL.SCHED_LINE_NBR = OD.SCHED_LINE_NBR
        AND OOL.EXP_DT = CAST('5555-12-31' AS DATE)

WHERE
    OD.EXP_DT = CAST('5555-12-31' AS DATE)
    AND OD.ORDER_DT BETWEEN DATE  '2015-01-01' AND CURRENT_DATE-1
    AND OD.RO_PO_TYPE_IND = 'N'
    AND REPL_OE_IND = 'R'

GROUP BY
    SNAPSHOT_DT
    , SNAPSHOT_MONTH_DT
    , NEXT_MONTH_DT
    , OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , OD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME

    , OD.MATL_ID
    , M.MATL_NO_8
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME
    , M.EXT_MATL_GRP_ID
    , M.MATL_TYPE_ID
    , M.MATL_STA_ID
    , M.MATL_STA_DT
    , M.STK_CLASS_ID
    , M.STK_CLASS_DT

    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , REPL_OE_IND
    , FRDD_IN_MNTH_FLG
    , FRDD_FPGI_IN_MNTH_FLG

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID
    , OD.REJ_REAS_ID
    , OD.PO_TYPE_ID

    , OD.ORDER_DT
    , OD.ORDER_CRT_TM
    , OD.ORDER_LN_CRT_DT
    , OD.ORDER_LN_CRT_TM

    , OD.QTY_UNIT_MEAS_ID

    ) O

    LEFT OUTER JOIN (
        NA_VWS.DELIV_DTL DD

        LEFT OUTER JOIN GDYR_VWS.DELIV_IN_PROC DIP
            ON DIP.DELIV_FISCAL_YR = DD.FISCAL_YR
            AND DIP.DELIV_ID = DD.DELIV_ID
            AND DIP.DELIV_LINE_NBR = DD.DELIV_LINE_NBR
            AND DIP.ORIG_SYS_ID = 2
            AND DIP.EXP_DT = CAST('5555-12-31' AS DATE)
        )
        ON DD.ORDER_FISCAL_YR = O.ORDER_FISCAL_YR
        AND DD.ORDER_ID = O.ORDER_ID
        AND DD.ORDER_LINE_NBR = O.ORDER_LINE_NBR
        AND DD.EXP_DT = CAST('5555-12-31' AS DATE)

GROUP BY
    O.QRY_TYPE
    , O.SNAPSHOT_DT
    , O.SNAPSHOT_MONTH_DT
    , O.NEXT_MONTH_DT
    , O.ORDER_FISCAL_YR
    , O.ORDER_ID
    , O.ORDER_LINE_NBR

    , O.SHIP_TO_CUST_ID
    , O.CUST_NAME
    , O.OWN_CUST_ID
    , O.OWN_CUST_NAME
    , O.SALES_ORG_CD
    , O.SALES_ORG_NAME
    , O.DISTR_CHAN_CD
    , O.DISTR_CHAN_NAME
    , O.CUST_GRP_ID
    , O.CUST_GRP_NAME

    , O.MATL_ID
    , O.MATL_NO_8
    , O.DESCR
    , O.PBU_NBR
    , O.PBU_NAME
    , O.MKT_AREA_NBR
    , O.MKT_AREA_NAME
    , O.MKT_CTGY_MKT_AREA_NBR
    , O.MKT_CTGY_MKT_AREA_NAME
    , O.PROD_LINE_NBR
    , O.PROD_LINE_NAME
    , O.EXT_MATL_GRP_ID
    , O.MATL_TYPE_ID
    , O.MATL_STA_ID
    , O.MATL_STA_DT
    , O.STK_CLASS_ID
    , O.STK_CLASS_DT

    , O.FACILITY_ID
    , O.FACILITY_NAME

    , O.REPL_OE_IND
    , O.FRDD_IN_MNTH_FLG
    , O.FRDD_FPGI_IN_MNTH_FLG

    , O.ORDER_CAT_ID
    , O.ORDER_TYPE_ID
    , O.REJ_REAS_ID
    , O.PO_TYPE_ID

    , O.ORDER_DT
    , O.ORDER_CRT_TM
    , O.ORDER_LN_CRT_DT
    , O.ORDER_LN_CRT_TM

    , O.QTY_UNIT_MEAS_ID
    , O.ORDER_QTY
    , O.OPEN_CNFRM_QTY
    , O.OPEN_CNFRM_IN_MNTH_QTY
    , O.OPEN_CNFRM_AFTER_MNTH_QTY
    , O.UNCNFRM_QTY
    , O.WAIT_LIST_QTY
    , O.OTHER_ORDER_QTY

    ) S

GROUP BY
    S.QRY_TYPE
    , S.SNAPSHOT_DT

    , S.SHIP_TO_CUST_ID
    , S.CUST_NAME
    , S.OWN_CUST_ID
    , S.OWN_CUST_NAME
    , S.SALES_ORG_CD
    , S.SALES_ORG_NAME
    , S.DISTR_CHAN_CD
    , S.DISTR_CHAN_NAME
    , S.CUST_GRP_ID
    , S.CUST_GRP_NAME

    , S.MATL_ID
    , S.MATL_NO_8
    , S.DESCR
    , S.PBU_NBR
    , S.PBU_NAME
    , S.MKT_AREA_NBR
    , S.MKT_AREA_NAME
    , S.MKT_CTGY_MKT_AREA_NBR
    , S.MKT_CTGY_MKT_AREA_NAME
    , S.PROD_LINE_NBR
    , S.PROD_LINE_NAME
    , S.EXT_MATL_GRP_ID
    , S.MATL_TYPE_ID
    , S.MATL_STA_ID
    , S.MATL_STA_DT
    , S.STK_CLASS_ID
    , S.STK_CLASS_DT

    , S.FACILITY_ID
    , S.FACILITY_NAME

    , S.REPL_OE_IND
    , S.FRDD_IN_MNTH_FLG
    , S.FRDD_FPGI_IN_MNTH_FLG

    , S.ORDER_CAT_ID
    , S.ORDER_TYPE_ID
    , S.REJ_REAS_ID
    , S.PO_TYPE_ID

    , S.ORDER_DT
    --, S.ORDER_CRT_TM
    , S.ORDER_LN_CRT_DT
    --, S.ORDER_LN_CRT_TM

    , S.QTY_UNIT_MEAS_ID

ORDER BY
    1 DESC
    , 2
    , 3
    , 5
    , 7
   , 9
;
