SELECT
    CAST('Order Date' AS VARCHAR(55)) AS SNAPSHOT_TYP
    , SP.OE_REPL_IND
    , SP.ORDER_CAT_ID

    , SP.ORDER_DT
    , SP.MONTH_DT
    , SP.END_OF_MONTH_DT

    , SP.REQ_IN_MNTH_IND

    , SP.QTY_UNIT_MEAS_ID
    , SUM(SP.ORDER_QTY) AS ORDER_QTY
    , SUM(SP.SL_CNFRM_QTY) AS SL_CNFRM_QTY

    , SUM(SP.CM_OPEN_CNFRM_QTY) AS CM_OPEN_CNFRM_QTY
    , SUM(SP.FM_OPEN_CNFRM_QTY) AS FM_OPEN_CNFRM_QTY
    , SUM(SP.UNCNFRM_QTY) AS UNCNFRM_QTY
    , SUM(SP.WAIT_LIST_QTY) AS WAIT_LIST_QTY
    , SUM(SP.OTHR_ORDER_QTY) AS OTHR_ORDER_QTY
    , SUM(SP.NEW_IN_PROC_QTY) AS NEW_IN_PROC_QTY

    , SUM(ZEROIFNULL(DD.PGMV_CURR_QTY)) AS PGMV_CURR_QTY
    , SUM(ZEROIFNULL(DD.PGMV_FTR_QTY)) AS PGMV_FTR_QTY
    , SUM(ZEROIFNULL(DD.AGID_CURR_QTY)) AS AGID_CURR_QTY
    , SUM(ZEROIFNULL(DD.AGID_FTR_QTY)) AS AGID_FTR_QTY

FROM (

SELECT
    OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , OD.MATL_ID
    , CASE 
        WHEN (C.SALES_ORG_CD IN('N301', 'N311', 'N321', 'N307', 'N317', 'N336') OR (C.SALES_ORG_CD IN('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN('30', '31')))
           THEN 'REPL'
        ELSE 'OE'
        END AS OE_REPL_IND
    , OD.ORDER_CAT_ID

    , OD.ORDER_DT
    , CAL.MONTH_DT
    , ADD_MONTHS(CAL.MONTH_DT, 1) - 1 AS END_OF_MONTH_DT

    , CASE WHEN OD.FRST_RDD <= END_OF_MONTH_DT THEN 'Y' ELSE 'N' END AS REQ_IN_MNTH_IND

    , OD.QTY_UNIT_MEAS_ID
    , MAX(OD.ORDER_QTY) AS ORDER_QTY
    , SUM(OD.CNFRM_QTY) AS SL_CNFRM_QTY

    , SUM(ZEROIFNULL(CASE WHEN OD.PLN_GOODS_ISS_DT <= END_OF_MONTH_DT THEN OOL.OPEN_CNFRM_QTY ELSE 0 END)) AS CM_OPEN_CNFRM_QTY
    , SUM(ZEROIFNULL(CASE WHEN OD.PLN_GOODS_ISS_DT > END_OF_MONTH_DT THEN OOL.OPEN_CNFRM_QTY ELSE 0 END)) AS FM_OPEN_CNFRM_QTY
    , SUM(ZEROIFNULL(OOL.UNCNFRM_QTY) + ZEROIFNULL(OOL.BACK_ORDER_QTY)) AS UNCNFRM_QTY
    , SUM(ZEROIFNULL(OOL.WAIT_LIST_QTY)) AS WAIT_LIST_QTY
    , SUM(ZEROIFNULL(OOL.DEFER_QTY) + ZEROIFNULL(OOL.OTHR_ORDER_QTY)) AS OTHR_ORDER_QTY
    , SUM(ZEROIFNULL(OOL.IN_PROC_QTY)) AS NEW_IN_PROC_QTY

FROM NA_BI_VWS.ORDER_DETAIL OD

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE = OD.ORDER_DT

    LEFT OUTER JOIN NA_VWS.OPEN_ORDER_SCHDLN OOL
        ON OOL.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = OD.ORDER_ID
        AND OOL.ORDER_LINE_NBR = OD.ORDER_LINE_NBR
        AND OOL.SCHED_LINE_NBR = OD.SCHED_LINE_NBR
        AND OD.ORDER_DT BETWEEN OOL.EFF_DT AND OOL.EXP_DT

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID
        AND M.PBU_NBR = '01'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

WHERE
    OD.ORDER_DT BETWEEN OD.EFF_DT AND OD.EXP_DT
    AND OD.RO_PO_TYPE_IND = 'N'
    AND OD.ORDER_DT BETWEEN DATE '2015-01-01' AND CURRENT_DATE-1
    AND OE_REPL_IND = 'REPL'

GROUP BY
    OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , OD.MATL_ID
    , OE_REPL_IND
    , OD.ORDER_CAT_ID

    , OD.ORDER_DT
    , CAL.MONTH_DT
    , END_OF_MONTH_DT

    , REQ_IN_MNTH_IND

    , OD.QTY_UNIT_MEAS_ID

    ) SP

    LEFT OUTER JOIN (
            SELECT
                D.ORDER_FISCAL_YR
                , D.ORDER_ID
                , D.ORDER_LINE_NBR
                , SUM(CASE
                    WHEN D.ACTL_GOODS_ISS_DT IS NULL AND D.PLN_GOODS_MVT_DT < ADD_MONTHS(CAL.MONTH_DT, 1)
                        THEN DIP.QTY_TO_SHIP
                    ELSE 0
                    END) AS PGMV_CURR_QTY
                , SUM(CASE
                    WHEN D.ACTL_GOODS_ISS_DT IS NULL AND D.PLN_GOODS_MVT_DT >= ADD_MONTHS(CAL.MONTH_DT, 1)
                        THEN DIP.QTY_TO_SHIP
                    ELSE 0
                    END) AS PGMV_FTR_QTY
                , SUM(CASE WHEN D.ACTL_GOODS_ISS_DT IS NOT NULL AND D.ACTL_GOODS_ISS_DT < ADD_MONTHS(CAL.MONTH_DT, 1) THEN D.DELIV_QTY ELSE 0 END) AS AGID_CURR_QTY
                , SUM(CASE WHEN D.ACTL_GOODS_ISS_DT IS NOT NULL AND D.ACTL_GOODS_ISS_DT >= ADD_MONTHS(CAL.MONTH_DT, 1) THEN D.DELIV_QTY ELSE 0 END) AS AGID_FTR_QTY

            FROM GDYR_BI_VWS.GDYR_CAL CAL

                INNER JOIN NA_BI_VWS.ORD_DTL_SMRY OD
                    ON OD.ORDER_DT = CAL.DAY_DATE
    
                INNER JOIN NA_VWS.DELIV_DTL D
                    ON CAL.DAY_DATE BETWEEN D.EFF_DT AND D.EXP_DT
                    AND D.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
                    AND D.ORDER_ID = OD.ORDER_ID
                    AND D.ORDER_LINE_NBR = OD.ORDER_LINE_NBR
                
                LEFT OUTER JOIN GDYR_VWS.DELIV_IN_PROC DIP
                    ON DIP.DELIV_FISCAL_YR = D.FISCAL_YR
                    AND DIP.DELIV_ID = D.DELIV_ID
                    AND DIP.DELIV_LINE_NBR = D.DELIV_LINE_NBR
                    AND CAL.DAY_DATE BETWEEN D.EFF_DT AND D.EXP_DT
                    AND DIP.ORIG_SYS_ID = 2
                
            WHERE
                CAL.DAY_DATE BETWEEN DATE '2015-01-01' AND CURRENT_DATE-1
            
            GROUP BY
                D.ORDER_FISCAL_YR
                , D.ORDER_ID
                , D.ORDER_LINE_NBR
            ) DD
        ON DD.ORDER_FISCAL_YR = SP.ORDER_FISCAL_YR
        AND DD.ORDER_ID = SP.ORDER_ID
        AND DD.ORDER_LINE_NBR = SP.ORDER_LINE_NBR

GROUP BY
    SP.OE_REPL_IND
    , SP.ORDER_CAT_ID

    , SP.ORDER_DT
    , SP.MONTH_DT
    , SP.END_OF_MONTH_DT

    , SP.REQ_IN_MNTH_IND

    , SP.QTY_UNIT_MEAS_ID

UNION ALL

SELECT
    CAST('Current Date' AS VARCHAR(55)) AS SNAPSHOT_TYP
    , SP.OE_REPL_IND
    , SP.ORDER_CAT_ID

    , SP.ORDER_DT
    , SP.MONTH_DT
    , SP.END_OF_MONTH_DT

    , SP.REQ_IN_MNTH_IND

    , SP.QTY_UNIT_MEAS_ID
    , SUM(SP.ORDER_QTY) AS ORDER_QTY
    , SUM(SP.SL_CNFRM_QTY) AS SL_CNFRM_QTY

    , SUM(SP.CM_OPEN_CNFRM_QTY) AS CM_OPEN_CNFRM_QTY
    , SUM(SP.FM_OPEN_CNFRM_QTY) AS FM_OPEN_CNFRM_QTY
    , SUM(SP.UNCNFRM_QTY) AS UNCNFRM_QTY
    , SUM(SP.WAIT_LIST_QTY) AS WAIT_LIST_QTY
    , SUM(SP.OTHR_ORDER_QTY) AS OTHR_ORDER_QTY
    , SUM(SP.NEW_IN_PROC_QTY) AS NEW_IN_PROC_QTY

    , SUM(ZEROIFNULL(DD.PGMV_CURR_QTY)) AS PGMV_CURR_QTY
    , SUM(ZEROIFNULL(DD.PGMV_FTR_QTY)) AS PGMV_FTR_QTY
    , SUM(ZEROIFNULL(DD.AGID_CURR_QTY)) AS AGID_CURR_QTY
    , SUM(ZEROIFNULL(DD.AGID_FTR_QTY)) AS AGID_FTR_QTY

FROM (

SELECT
    OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , OD.MATL_ID
    , CASE 
        WHEN (C.SALES_ORG_CD IN('N301', 'N311', 'N321', 'N307', 'N317', 'N336') OR (C.SALES_ORG_CD IN('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN('30', '31')))
           THEN 'REPL'
        ELSE 'OE'
        END AS OE_REPL_IND
    , OD.ORDER_CAT_ID

    , OD.ORDER_DT
    , CAL.MONTH_DT
    , ADD_MONTHS(CAL.MONTH_DT, 1) - 1 AS END_OF_MONTH_DT

    , CASE WHEN OD.FRST_RDD <= END_OF_MONTH_DT THEN 'Y' ELSE 'N' END AS REQ_IN_MNTH_IND

    , OD.QTY_UNIT_MEAS_ID
    , MAX(OD.ORDER_QTY) AS ORDER_QTY
    , SUM(OD.CNFRM_QTY) AS SL_CNFRM_QTY

    , SUM(ZEROIFNULL(CASE WHEN OD.PLN_GOODS_ISS_DT <= END_OF_MONTH_DT THEN OOL.OPEN_CNFRM_QTY ELSE 0 END)) AS CM_OPEN_CNFRM_QTY
    , SUM(ZEROIFNULL(CASE WHEN OD.PLN_GOODS_ISS_DT > END_OF_MONTH_DT THEN OOL.OPEN_CNFRM_QTY ELSE 0 END)) AS FM_OPEN_CNFRM_QTY
    , SUM(ZEROIFNULL(OOL.UNCNFRM_QTY) + ZEROIFNULL(OOL.BACK_ORDER_QTY)) AS UNCNFRM_QTY
    , SUM(ZEROIFNULL(OOL.WAIT_LIST_QTY)) AS WAIT_LIST_QTY
    , SUM(ZEROIFNULL(OOL.DEFER_QTY) + ZEROIFNULL(OOL.OTHR_ORDER_QTY)) AS OTHR_ORDER_QTY
    , SUM(ZEROIFNULL(OOL.IN_PROC_QTY)) AS NEW_IN_PROC_QTY

FROM NA_BI_VWS.ORDER_DETAIL OD

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE = OD.ORDER_DT

    LEFT OUTER JOIN NA_VWS.OPEN_ORDER_SCHDLN OOL
        ON OOL.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = OD.ORDER_ID
        AND OOL.ORDER_LINE_NBR = OD.ORDER_LINE_NBR
        AND OOL.SCHED_LINE_NBR = OD.SCHED_LINE_NBR
        AND OOL.EXP_DT = CAST('5555-12-31' AS DATE)

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID
        AND M.PBU_NBR = '01'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

WHERE
    OD.EXP_DT = CAST('5555-12-31' AS DATE)
    AND OD.RO_PO_TYPE_IND = 'N'
    AND OD.ORDER_DT BETWEEN DATE '2015-01-01' AND CURRENT_DATE-1
    AND OE_REPL_IND = 'REPL'

GROUP BY
    OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , OD.MATL_ID
    , OE_REPL_IND
    , OD.ORDER_CAT_ID

    , OD.ORDER_DT
    , CAL.MONTH_DT
    , END_OF_MONTH_DT

    , REQ_IN_MNTH_IND

    , OD.QTY_UNIT_MEAS_ID

    ) SP

    LEFT OUTER JOIN (
            SELECT
                D.ORDER_FISCAL_YR
                , D.ORDER_ID
                , D.ORDER_LINE_NBR
                , SUM(CASE
                    WHEN D.ACTL_GOODS_ISS_DT IS NULL AND D.PLN_GOODS_MVT_DT < ADD_MONTHS(CAL.MONTH_DT, 1)
                        THEN DIP.QTY_TO_SHIP
                    ELSE 0
                    END) AS PGMV_CURR_QTY
                , SUM(CASE
                    WHEN D.ACTL_GOODS_ISS_DT IS NULL AND D.PLN_GOODS_MVT_DT >= ADD_MONTHS(CAL.MONTH_DT, 1)
                        THEN DIP.QTY_TO_SHIP
                    ELSE 0
                    END) AS PGMV_FTR_QTY
                , SUM(CASE WHEN D.ACTL_GOODS_ISS_DT IS NOT NULL AND D.ACTL_GOODS_ISS_DT < ADD_MONTHS(CAL.MONTH_DT, 1) THEN D.DELIV_QTY ELSE 0 END) AS AGID_CURR_QTY
                , SUM(CASE WHEN D.ACTL_GOODS_ISS_DT IS NOT NULL AND D.ACTL_GOODS_ISS_DT >= ADD_MONTHS(CAL.MONTH_DT, 1) THEN D.DELIV_QTY ELSE 0 END) AS AGID_FTR_QTY

            FROM GDYR_BI_VWS.GDYR_CAL CAL

                INNER JOIN NA_BI_VWS.ORD_DTL_SMRY OD
                    ON OD.ORDER_DT = CAL.DAY_DATE

                INNER JOIN NA_VWS.DELIV_DTL D
                    ON D.EXP_DT = CAST('5555-12-31' AS DATE)
                    AND D.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
                    AND D.ORDER_ID = OD.ORDER_ID
                    AND D.ORDER_LINE_NBR = OD.ORDER_LINE_NBR

                LEFT OUTER JOIN GDYR_VWS.DELIV_IN_PROC DIP
                    ON DIP.DELIV_FISCAL_YR = D.FISCAL_YR
                    AND DIP.DELIV_ID = D.DELIV_ID
                    AND DIP.DELIV_LINE_NBR = D.DELIV_LINE_NBR
                    AND DIP.EXP_DT = CAST('5555-12-31' AS DATE)
                    AND DIP.ORIG_SYS_ID = 2

            WHERE
                CAL.DAY_DATE BETWEEN DATE '2015-01-01' AND CURRENT_DATE-1

            GROUP BY
                D.ORDER_FISCAL_YR
                , D.ORDER_ID
                , D.ORDER_LINE_NBR
            ) DD
        ON DD.ORDER_FISCAL_YR = SP.ORDER_FISCAL_YR
        AND DD.ORDER_ID = SP.ORDER_ID
        AND DD.ORDER_LINE_NBR = SP.ORDER_LINE_NBR

GROUP BY
    SP.OE_REPL_IND
    , SP.ORDER_CAT_ID

    , SP.ORDER_DT
    , SP.MONTH_DT
    , SP.END_OF_MONTH_DT

    , SP.REQ_IN_MNTH_IND

    , SP.QTY_UNIT_MEAS_ID





