SELECT
    CR.ORDER_DT
    , CR.SNAP_REQ_IN_MNTH_IND
    , CR.CURR_REQ_IN_MNTH_IND

    , CR.QTY_UNIT_MEAS_ID
    , SUM(CR.SNAP_ORDER_QTY) AS SNAP_ORDER_QTY
    , SUM(CR.SNAP_SL_CNFRM_QTY) AS SNAP_SL_CNFRM_QTY

    , SUM(CR.SNAP_CM_OPEN_CNFRM_QTY) AS SNAP_CM_OPEN_CNFRM_QTY
    , SUM(CR.SNAP_FM_OPEN_CNFRM_QTY) AS SNAP_FM_OPEN_CNFRM_QTY
    , SUM(CR.SNAP_UNCNFRM_QTY) AS SNAP_UNCNFRM_QTY
    , SUM(CR.SNAP_WAIT_LIST_QTY) AS SNAP_WAIT_LIST_QTY
    , SUM(CR.SNAP_OTHR_ORDER_QTY) AS SNAP_OTHR_ORDER_QTY
    , SUM(CR.SNAP_NEW_IN_PROC_QTY) AS SNAP_NEW_IN_PROC_QTY

    , SUM(CR.SNAP_CM_IN_PROC_QTY) AS SNAP_CM_IN_PROC_QTY
    , SUM(CR.SNAP_FM_IN_PROC_QTY) AS SNAP_FM_IN_PROC_QTY
    , SUM(CR.SNAP_AGID_QTY) AS SNAP_AGID_QTY

    , SUM(CR.CURR_ORDER_QTY) AS CURR_ORDER_QTY
    , SUM(CR.CURR_CNFRM_QTY) AS CURR_CNFRM_QTY

    , SUM(CR.CURR_CM_OPEN_CNFRM_QTY) AS CURR_CM_OPEN_CNFRM_QTY
    , SUM(CR.CURR_FM_OPEN_CNFRM_QTY) AS CURR_FM_OPEN_CNFRM_QTY
    , SUM(CR.CURR_UNCNFRM_QTY) AS CURR_UNCNFRM_QTY
    , SUM(CR.CURR_WAIT_LIST_QTY) AS CURR_WAIT_LIST_QTY
    , SUM(CR.CURR_OTHR_ORDER_QTY) AS CURR_OTHR_ORDER_QTY
    , SUM(CR.CURR_NEW_IN_PROC_QTY) AS CURR_NEW_IN_PROC_QTY

    , SUM(CR.CURR_CM_IN_PROC_QTY) AS CURR_CM_IN_PROC_QTY
    , SUM(CR.CURR_FM_IN_PROC_QTY) AS CURR_FM_IN_PROC_QTY
    , SUM(CR.CURR_CM_AGID_QTY) AS CURR_CM_AGID_QTY
    , SUM(CR.CURR_FM_AGID_QTY) AS CURR_FM_AGID_QTY

FROM (

SELECT
    SC.ORDER_FISCAL_YR
    , SC.ORDER_ID
    , SC.ORDER_LINE_NBR

    , SC.ORDER_DT
    , SC.MONTH_DT
    , SC.END_OF_MONTH_DT

    , SC.SNAP_REQ_IN_MNTH_IND
    , SC.CURR_REQ_IN_MNTH_IND

    , SC.QTY_UNIT_MEAS_ID
    , SC.SNAP_ORDER_QTY
    , SC.SNAP_SL_CNFRM_QTY

    , SC.SNAP_CM_OPEN_CNFRM_QTY
    , SC.SNAP_FM_OPEN_CNFRM_QTY
    , SC.SNAP_UNCNFRM_QTY
    , SC.SNAP_WAIT_LIST_QTY
    , SC.SNAP_OTHR_ORDER_QTY
    , SC.SNAP_NEW_IN_PROC_QTY

    , SC.SNAP_CM_IN_PROC_QTY
    , SC.SNAP_FM_IN_PROC_QTY
    , SC.SNAP_AGID_QTY

    , SC.CURR_ORDER_QTY
    , SC.CURR_CNFRM_QTY

    , SC.CURR_CM_OPEN_CNFRM_QTY
    , SC.CURR_FM_OPEN_CNFRM_QTY
    , SC.CURR_UNCNFRM_QTY
    , SC.CURR_WAIT_LIST_QTY
    , SC.CURR_OTHR_ORDER_QTY
    , SC.CURR_NEW_IN_PROC_QTY

    , ZEROIFNULL(SUM(CASE WHEN DD.ACTL_GOODS_ISS_DT IS NULL AND DD.PLN_GOODS_MVT_DT <= SC.END_OF_MONTH_DT THEN DIP.QTY_TO_SHIP ELSE 0 END)) AS CURR_CM_IN_PROC_QTY
    , ZEROIFNULL(SUM(CASE WHEN DD.ACTL_GOODS_ISS_DT IS NULL AND DD.PLN_GOODS_MVT_DT > SC.END_OF_MONTH_DT THEN DIP.QTY_TO_SHIP ELSE 0 END)) AS CURR_FM_IN_PROC_QTY
    , ZEROIFNULL(SUM(CASE WHEN DD.ACTL_GOODS_ISS_DT IS NOT NULL AND DD.ACTL_GOODS_ISS_DT <= SC.END_OF_MONTH_DT THEN DD.DELIV_QTY ELSE 0 END)) AS CURR_CM_AGID_QTY
    , ZEROIFNULL(SUM(CASE WHEN DD.ACTL_GOODS_ISS_DT IS NOT NULL AND DD.ACTL_GOODS_ISS_DT > SC.END_OF_MONTH_DT THEN DD.DELIV_QTY ELSE 0 END)) AS CURR_FM_AGID_QTY

FROM (

SELECT
    S.ORDER_FISCAL_YR
    , S.ORDER_ID
    , S.ORDER_LINE_NBR

    , S.ORDER_DT
    , S.MONTH_DT
    , S.END_OF_MONTH_DT

    , S.REQ_IN_MNTH_IND AS SNAP_REQ_IN_MNTH_IND
    , CASE WHEN OD.FRST_RDD <= S.END_OF_MONTH_DT THEN 'Y' ELSE 'N' END AS CURR_REQ_IN_MNTH_IND

    , S.QTY_UNIT_MEAS_ID
    , S.SNAP_ORDER_QTY
    , S.SNAP_SL_CNFRM_QTY

    , S.SNAP_CM_OPEN_CNFRM_QTY
    , S.SNAP_FM_OPEN_CNFRM_QTY
    , S.SNAP_UNCNFRM_QTY
    , S.SNAP_WAIT_LIST_QTY
    , S.SNAP_OTHR_ORDER_QTY
    , S.SNAP_NEW_IN_PROC_QTY

    , S.SNAP_CM_IN_PROC_QTY
    , S.SNAP_FM_IN_PROC_QTY
    , S.SNAP_AGID_QTY

    , MAX(OD.ORDER_QTY) AS CURR_ORDER_QTY
    , SUM(OD.CNFRM_QTY) AS CURR_CNFRM_QTY

    , SUM(ZEROIFNULL(CASE WHEN OD.PLN_GOODS_ISS_DT <= S.END_OF_MONTH_DT THEN OOL.OPEN_CNFRM_QTY ELSE 0 END)) AS CURR_CM_OPEN_CNFRM_QTY
    , SUM(ZEROIFNULL(CASE WHEN OD.PLN_GOODS_ISS_DT > S.END_OF_MONTH_DT THEN OOL.OPEN_CNFRM_QTY ELSE 0 END)) AS CURR_FM_OPEN_CNFRM_QTY
    , SUM(ZEROIFNULL(OOL.UNCNFRM_QTY) + ZEROIFNULL(OOL.BACK_ORDER_QTY)) AS CURR_UNCNFRM_QTY
    , SUM(ZEROIFNULL(OOL.WAIT_LIST_QTY)) AS CURR_WAIT_LIST_QTY
    , SUM(ZEROIFNULL(OOL.DEFER_QTY) + ZEROIFNULL(OOL.OTHR_ORDER_QTY)) AS CURR_OTHR_ORDER_QTY
    , SUM(ZEROIFNULL(OOL.IN_PROC_QTY)) AS CURR_NEW_IN_PROC_QTY

FROM (

SELECT
    OO.ORDER_FISCAL_YR
    , OO.ORDER_ID
    , OO.ORDER_LINE_NBR

    , OO.ORDER_DT
    , OO.MONTH_DT
    , OO.END_OF_MONTH_DT

    , OO.REQ_IN_MNTH_IND

    , OO.QTY_UNIT_MEAS_ID
    , OO.SNAP_ORDER_QTY
    , OO.SNAP_SL_CNFRM_QTY

    , OO.SNAP_CM_OPEN_CNFRM_QTY
    , OO.SNAP_FM_OPEN_CNFRM_QTY
    , OO.SNAP_UNCNFRM_QTY
    , OO.SNAP_WAIT_LIST_QTY
    , OO.SNAP_OTHR_ORDER_QTY
    , OO.SNAP_NEW_IN_PROC_QTY

    , ZEROIFNULL(SUM(CASE WHEN DD.ACTL_GOODS_ISS_DT IS NULL AND DD.PLN_GOODS_MVT_DT <= OO.END_OF_MONTH_DT THEN DIP.QTY_TO_SHIP ELSE 0 END)) AS SNAP_CM_IN_PROC_QTY
    , ZEROIFNULL(SUM(CASE WHEN DD.ACTL_GOODS_ISS_DT IS NULL AND DD.PLN_GOODS_MVT_DT > OO.END_OF_MONTH_DT THEN DIP.QTY_TO_SHIP ELSE 0 END)) AS SNAP_FM_IN_PROC_QTY
    , ZEROIFNULL(SUM(CASE WHEN DD.ACTL_GOODS_ISS_DT IS NOT NULL THEN DD.DELIV_QTY ELSE 0 END)) AS SNAP_AGID_QTY

FROM (



    ) OO

    LEFT OUTER JOIN NA_VWS.DELIV_DTL DD
        ON DD.ORDER_FISCAL_YR = OO.ORDER_FISCAL_YR
        AND DD.ORDER_ID = OO.ORDER_ID
        AND DD.ORDER_LINE_NBR = OO.ORDER_LINE_NBR
        AND OO.ORDER_DT BETWEEN DD.EFF_DT AND DD.EXP_DT

    LEFT OUTER JOIN GDYR_VWS.DELIV_IN_PROC DIP
        ON DIP.DELIV_FISCAL_YR = DD.FISCAL_YR
        AND DIP.DELIV_ID = DD.DELIV_ID
        AND DIP.DELIV_LINE_NBR = DD.DELIV_LINE_NBR
        AND DIP.ORIG_SYS_ID = 2
        AND OO.ORDER_DT BETWEEN DIP.EFF_DT AND DIP.EXP_DT

GROUP BY
    OO.ORDER_FISCAL_YR
    , OO.ORDER_ID
    , OO.ORDER_LINE_NBR

    , OO.ORDER_DT
    , OO.MONTH_DT
    , OO.END_OF_MONTH_DT

    , OO.REQ_IN_MNTH_IND

    , OO.QTY_UNIT_MEAS_ID
    , OO.SNAP_ORDER_QTY
    , OO.SNAP_SL_CNFRM_QTY

    , OO.SNAP_CM_OPEN_CNFRM_QTY
    , OO.SNAP_FM_OPEN_CNFRM_QTY
    , OO.SNAP_UNCNFRM_QTY
    , OO.SNAP_WAIT_LIST_QTY
    , OO.SNAP_OTHR_ORDER_QTY
    , OO.SNAP_NEW_IN_PROC_QTY
    
    ) S

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = S.ORDER_FISCAL_YR
        AND OD.ORDER_ID = S.ORDER_ID
        AND OD.ORDER_LINE_NBR = S.ORDER_LINE_NBR
        AND OD.EXP_DT = CAST('5555-12-31' AS DATE)

    LEFT OUTER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL
        ON OOL.ORDER_FISCAL_YR = S.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = S.ORDER_ID
        AND OOL.ORDER_LINE_NBR = S.ORDER_LINE_NBR
        AND OOL.SCHED_LINE_NBR = OD.SCHED_LINE_NBR

GROUP BY
    S.ORDER_FISCAL_YR
    , S.ORDER_ID
    , S.ORDER_LINE_NBR

    , S.ORDER_DT
    , S.MONTH_DT
    , S.END_OF_MONTH_DT

    , SNAP_REQ_IN_MNTH_IND
    , CURR_REQ_IN_MNTH_IND

    , S.QTY_UNIT_MEAS_ID
    , S.SNAP_ORDER_QTY
    , S.SNAP_SL_CNFRM_QTY

    , S.SNAP_CM_OPEN_CNFRM_QTY
    , S.SNAP_FM_OPEN_CNFRM_QTY
    , S.SNAP_UNCNFRM_QTY
    , S.SNAP_WAIT_LIST_QTY
    , S.SNAP_OTHR_ORDER_QTY
    , S.SNAP_NEW_IN_PROC_QTY

    , S.SNAP_CM_IN_PROC_QTY
    , S.SNAP_FM_IN_PROC_QTY
    , S.SNAP_AGID_QTY

    ) SC

    LEFT OUTER JOIN NA_VWS.DELIV_DTL DD
        ON DD.ORDER_FISCAL_YR = SC.ORDER_FISCAL_YR
        AND DD.ORDER_ID = SC.ORDER_ID
        AND DD.ORDER_LINE_NBR = SC.ORDER_LINE_NBR
        AND DD.EXP_DT = CAST('5555-12-31' AS DATE)

    LEFT OUTER JOIN GDYR_VWS.DELIV_IN_PROC DIP
        ON DIP.DELIV_FISCAL_YR = DD.FISCAL_YR
        AND DIP.DELIV_ID = DD.DELIV_ID
        AND DIP.DELIV_LINE_NBR = DD.DELIV_LINE_NBR
        AND DIP.ORIG_SYS_ID = 2
        AND DIP.EXP_DT = CAST('5555-12-31' AS DATE)

GROUP BY
    SC.ORDER_FISCAL_YR
    , SC.ORDER_ID
    , SC.ORDER_LINE_NBR

    , SC.ORDER_DT
    , SC.MONTH_DT
    , SC.END_OF_MONTH_DT

    , SC.SNAP_REQ_IN_MNTH_IND
    , SC.CURR_REQ_IN_MNTH_IND

    , SC.QTY_UNIT_MEAS_ID
    , SC.SNAP_ORDER_QTY
    , SC.SNAP_SL_CNFRM_QTY

    , SC.SNAP_CM_OPEN_CNFRM_QTY
    , SC.SNAP_FM_OPEN_CNFRM_QTY
    , SC.SNAP_UNCNFRM_QTY
    , SC.SNAP_WAIT_LIST_QTY
    , SC.SNAP_OTHR_ORDER_QTY
    , SC.SNAP_NEW_IN_PROC_QTY

    , SC.SNAP_CM_IN_PROC_QTY
    , SC.SNAP_FM_IN_PROC_QTY
    , SC.SNAP_AGID_QTY

    , SC.CURR_ORDER_QTY
    , SC.CURR_CNFRM_QTY

    , SC.CURR_CM_OPEN_CNFRM_QTY
    , SC.CURR_FM_OPEN_CNFRM_QTY
    , SC.CURR_UNCNFRM_QTY
    , SC.CURR_WAIT_LIST_QTY
    , SC.CURR_OTHR_ORDER_QTY
    , SC.CURR_NEW_IN_PROC_QTY

    ) CR

GROUP BY
    CR.ORDER_DT
    , CR.SNAP_REQ_IN_MNTH_IND
    , CR.CURR_REQ_IN_MNTH_IND

    , CR.QTY_UNIT_MEAS_ID

ORDER BY
    CR.ORDER_DT
    , CR.SNAP_REQ_IN_MNTH_IND
    , CR.CURR_REQ_IN_MNTH_IND

