-- CREATE DATE ANALYSIS

SELECT
    CAL.DAY_DATE
    , OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , OD.ORDER_DT
    , OD.ORDER_LN_CRT_DT
    , CASE
        WHEN OD.CUST_GRP2_CD = 'TLB'
            THEN OD.ORDER_DT
        ELSE OD.ORDER_LN_CRT_DT
        END AS MEAS_DT

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID
    , OD.PO_TYPE_ID

    , OD.REJ_REAS_ID
    , OD.CANCEL_DT
    , OD.CUST_GRP2_CD

    , OD.DELIV_PRTY_ID
    , OD.ORDER_DELIV_BLK_CD
    , MAX(OD.DELIV_BLK_CD) AS SL_DELIV_BLK_CD
    , OD.WAIT_LIST_CD
    , OD.SPCL_PROC_ID
    , OD.PROD_ALLCT_DETERM_PROC_ID
    , OD.AVAIL_CHK_GRP_CD

    , OD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME

    , OD.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME

    , CASE
        WHEN OD.FACILITY_ID IN ('N5US', 'N5CA')
            THEN 'N5'
        WHEN OD.FACILITY_ID = C.PRIM_SHIP_FACILITY_ID
            THEN 'PF'
        WHEN OD.FACILITY_ID LIKE 'N5%'
            THEN 'FD'
        ELSE 'OA'
        END AS TEST_PRIM_SHIP_FACILITY
    , C.PRIM_SHIP_FACILITY_ID
    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , OD.QTY_UNIT_MEAS_ID
    , MAX(OD.ORDER_QTY) AS ORDER_QTY

FROM NA_BI_VWS.ORDER_DETAIL OD

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE BETWEEN OD.EFF_DT AND OD.EXP_DT
        AND CAL.DAY_DATE = MEAS_DT

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID

WHERE
    CAL.DAY_DATE BETWEEN DATE '2015-02-01' AND CURRENT_DATE-1
    AND OD.ORDER_CAT_ID = 'C'
    AND OD.PO_TYPE_ID <> 'RO'

    AND (
        C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N307', 'N317', 'N336', 'N302', 'N312', 'N322')
        OR (
            C.SALES_ORG_CD IN ('N303', 'N313', 'N323')
            AND C.DISTR_CHAN_CD IN ('30', '31', '32')
            )
        )
    AND M.PBU_NBR = '01' --IN ('01', '03')
    AND M.MKT_AREA_NBR <> '04'
    AND M.SUPER_BRAND_ID IN ('01', '02', '03', '05')

GROUP BY
    CAL.DAY_DATE
    , OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , OD.ORDER_DT
    , OD.ORDER_LN_CRT_DT

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID
    , OD.PO_TYPE_ID

    , OD.REJ_REAS_ID
    , OD.CANCEL_DT
    , OD.CUST_GRP2_CD

    , OD.DELIV_PRTY_ID
    , OD.ORDER_DELIV_BLK_CD
    --, MAX(OD.DELIV_BLK_CD) AS SL_DELIV_BLK_CD
    , OD.WAIT_LIST_CD
    , OD.SPCL_PROC_ID
    , OD.PROD_ALLCT_DETERM_PROC_ID
    , OD.AVAIL_CHK_GRP_CD

    , OD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME

    , OD.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME

    , TEST_PRIM_SHIP_FACILITY
    , C.PRIM_SHIP_FACILITY_ID
    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , OD.QTY_UNIT_MEAS_ID
    --, MAX(OD.ORDER_QTY) AS ORDER_QTY
