SELECT
    Q.QRY_TYP
    , Q.DAY_DATE
    , Q.PBU_NBR
    , Q.PBU_NAME
    , Q.OE_REPL_IND
    , Q.QTY_UNIT_MEAS_ID
    , SUM(Q.IN_PROC_PRI_CUR_MTH_QTY) AS IN_PROC_PRI_CUR_MTH_QTY
    , SUM(Q.IN_PROC_NXT_FUT_MTH_QTY) AS IN_PROC_NXT_FUT_MTH_QTY
    , SUM(Q.IN_PROC_TOT_QTY) AS IN_PROC_TOT_QTY

FROM (

SELECT
    CAST('EDW' AS VARCHAR(15)) AS QRY_TYP
    , IPGC.DAY_DATE
    , DLS.ORDER_FISCAL_YR
    , DLS.ORDER_ID
    , DLS.ORDER_LINE_NBR

    , DLS.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , CASE 
        WHEN (C.SALES_ORG_CD IN('N301', 'N311', 'N321', 'N307', 'N317', 'N336') OR (C.SALES_ORG_CD IN('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN('30', '31')))
           THEN('REPL')
        ELSE('OE')
        END AS OE_REPL_IND

    , DLS.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME

    , DLS.DELIV_LINE_FACILITY_ID AS FACILITY_ID
    , F.FACILITY_NAME

    , DLS.QTY_UNIT_MEAS_ID

    , SUM(CASE
            WHEN DLS.PLN_GOODS_MVT_DT < ADD_MONTHS((CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1) + 1, 1) AND ORD.CALC_FRDD_CPM_FLG = 'Y'
                THEN DIP.RPT_QTY_TO_SHIP
            ELSE 0
            END) IN_PROC_PRI_CUR_MTH_QTY
    , SUM(CASE
            WHEN DLS.PLN_GOODS_MVT_DT >= ADD_MONTHS((CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1) + 1, 1) AND ORD.CALC_FRDD_CPM_FLG = 'Y'
                THEN DIP.RPT_QTY_TO_SHIP
            ELSE 0
            END) IN_PROC_NXT_FUT_MTH_QTY
    , SUM(DIP.RPT_QTY_TO_SHIP) IN_PROC_TOT_QTY

FROM GDYR_VWS.DELIV_IN_PROC DIP

    INNER JOIN GDYR_BI_VWS.GDYR_CAL IPGC
        ON IPGC.DAY_DATE BETWEEN DIP.EFF_DT AND DIP.EXP_DT

    INNER JOIN NA_VWS.DELIV_DTL DLS
        ON DIP.ORDER_FISCAL_YR = DLS.ORDER_FISCAL_YR
        AND DIP.DELIV_ID = DLS.DELIV_ID
        AND DIP.DELIV_LINE_NBR = DLS.DELIV_LINE_NBR
        AND IPGC.DAY_DATE BETWEEN DIP.EFF_DT AND DIP.EXP_DT

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = DLS.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = DLS.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = DLS.DELIV_LINE_FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN (
            SELECT 
                ODGC.DAY_DATE
                , ODC.ORDER_FISCAL_YR
                , ODC.ORDER_ID
                , ODC.ORDER_LINE_NBR
                , MAX(ODC.FRST_RDD) AS FRST_RDD_DT
                , CASE
                    WHEN FRST_RDD_DT < ADD_MONTHS((CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1) + 1, 1)
                        THEN 'Y'
                    ELSE 'N'
                    END CALC_FRDD_CPM_FLG
            FROM NA_BI_VWS.ORDER_DETAIL ODC
            INNER JOIN GDYR_BI_VWS.GDYR_CAL ODGC
                ON ODGC.DAY_DATE BETWEEN ODC.EFF_DT AND ODC.EXP_DT
            WHERE ODC.RO_PO_TYPE_IND = 'N'
                AND ODC.ORDER_DT = ODGC.DAY_DATE
                AND ODGC.DAY_DATE BETWEEN (CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1) + 1 AND CURRENT_DATE - 1
            GROUP BY 1, 2, 3, 4
            ) ORD
        ON ORD.ORDER_FISCAL_YR = DIP.ORDER_FISCAL_YR
        AND ORD.ORDER_ID = DIP.ORDER_ID
        AND ORD.ORDER_LINE_NBR = DIP.ORDER_LINE_NBR
        AND ORD.DAY_DATE = IPGC.DAY_DATE

WHERE 
    DIP.INTRA_CMPNY_FLG = 'N'
    AND DLS.ACTL_GOODS_ISS_DT IS NULL
    AND IPGC.DAY_DATE BETWEEN DATE '2015-03-01' AND DATE-1 -- BETWEEN (CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1) + 1 AND CURRENT_DATE - 1
    AND (
        C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N307', 'N317', 'N336', 'N302', 'N312', 'N322')
        OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN ('30', '31', '32'))
        )
    AND M.PBU_NBR = '01' -- IN ('01', '03')
    AND M.MKT_AREA_NBR <> '04'
    AND M.SUPER_BRAND_ID IN ('01', '02', '03', '05')

GROUP BY 
    IPGC.DAY_DATE
    , DLS.ORDER_FISCAL_YR
    , DLS.ORDER_ID
    , DLS.ORDER_LINE_NBR

    , DLS.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , OE_REPL_IND

    , DLS.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME

    , DLS.DELIV_LINE_FACILITY_ID
    , F.FACILITY_NAME

    , DLS.QTY_UNIT_MEAS_ID

UNION ALL

SELECT
    CAST('OOSL' AS VARCHAR(15)) AS QRY_TYP
    , CAL.DAY_DATE
    , O.ORDER_FISCAL_YR
    , O.ORDER_ID
    , O.ORDER_LINE_NBR

    , O.CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , CASE 
        WHEN (C.SALES_ORG_CD IN('N301', 'N311', 'N321', 'N307', 'N317', 'N336') OR (C.SALES_ORG_CD IN('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN('30', '31')))
           THEN('REPL')
        ELSE('OE')
        END AS OE_REPL_IND

    , O.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME

    , O.FACILITY_ID
    , F.FACILITY_NAME

    , O.RPT_QTY_UNIT_MEAS_ID

    , SUM(CASE
        WHEN CAL.MONTH_DT = PGI_CAL.MONTH_DT
            THEN O.RPT_IN_PROC_QTY
        ELSE 0
        END) AS IN_PROC_QTY_CURR
    , SUM(CASE
        WHEN CAL.MONTH_DT < PGI_CAL.MONTH_DT
            THEN O.RPT_IN_PROC_QTY
        ELSE 0
        END) AS IN_PROC_QTY_FTR
    , SUM(O.RPT_IN_PROC_QTY) AS IN_PROC_QTY

FROM GDYR_BI_VWS.GDYR_CAL CAL

    INNER JOIN NA_VWS.OPEN_ORDER_SCHDLN O
        ON CAL.DAY_DATE BETWEEN O.EFF_DT AND O.EXP_DT

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = O.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = O.CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = O.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.GDYR_CAL PGI_CAL
        ON PGI_CAL.DAY_DATE = O.PLN_GOODS_ISS_DT

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = O.ORDER_FISCAL_YR
        AND OD.ORDER_ID = O.ORDER_ID
        AND OD.ORDER_LINE_NBR = O.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = 1
        AND CAL.DAY_DATE BETWEEN OD.EFF_DT AND OD.EXP_DT
        AND OD.ORDER_LN_CRT_DT = CAL.DAY_DATE
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.PO_TYPE_ID <> 'RO'

WHERE
    CAL.DAY_DATE BETWEEN DATE '2015-03-01' AND DATE-1 -- BETWEEN CAST('2015-02-01' AS DATE) AND CURRENT_DATE-1
    AND (
        C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N307', 'N317', 'N336', 'N302', 'N312', 'N322')
        OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN ('30', '31', '32'))
        )
    AND M.PBU_NBR = '01' -- IN ('01', '03')
    AND M.MKT_AREA_NBR <> '04'
    AND M.SUPER_BRAND_ID IN ('01', '02', '03', '05')

    AND O.IN_PROC_QTY > 0

GROUP BY
    CAL.DAY_DATE
    , O.ORDER_FISCAL_YR
    , O.ORDER_ID
    , O.ORDER_LINE_NBR

    , O.CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , OE_REPL_IND

    , O.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME

    , O.FACILITY_ID
    , F.FACILITY_NAME

    , O.RPT_QTY_UNIT_MEAS_ID

UNION ALL

SELECT
    CAST('DD' AS VARCHAR(15)) AS QRY_TYP
    , CAL.DAY_DATE
    , D.ORDER_FISCAL_YR
    , D.ORDER_ID
    , D.ORDER_LINE_NBR

    , D.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , CASE 
        WHEN (C.SALES_ORG_CD IN('N301', 'N311', 'N321', 'N307', 'N317', 'N336') OR (C.SALES_ORG_CD IN('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN('30', '31')))
           THEN('REPL')
        ELSE('OE')
        END AS OE_REPL_IND

    , D.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME

    , D.DELIV_LINE_FACILITY_ID AS FACILITY_ID
    , F.FACILITY_NAME

    , D.QTY_UNIT_MEAS_ID

    , SUM(CASE
        WHEN CAL.MONTH_DT = PGI_CAL.MONTH_DT
            THEN D.RPT_DELIV_QTY
        ELSE 0
        END) AS IN_PROC_QTY_CURR
    , SUM(CASE
        WHEN CAL.MONTH_DT < PGI_CAL.MONTH_DT
            THEN D.RPT_DELIV_QTY
        ELSE 0
        END) AS IN_PROC_QTY_FTR
    , SUM(D.RPT_DELIV_QTY) AS IN_PROC_QTY

FROM GDYR_BI_VWS.GDYR_CAL CAL

    INNER JOIN NA_VWS.DELIV_DTL D
        ON CAL.DAY_DATE BETWEEN D.EFF_DT AND D.EXP_DT
        AND D.DELIV_CAT_ID = 'J'
        AND D.SD_DOC_CTGY_CD = 'C'
        AND D.DELIV_NOTE_CREA_DT = CAL.DAY_DATE
        AND D.ACTL_GOODS_ISS_DT IS NULL

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = D.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = D.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = D.DELIV_LINE_FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.GDYR_CAL PGI_CAL
        ON PGI_CAL.DAY_DATE = D.PLN_GOODS_MVT_DT

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = D.ORDER_FISCAL_YR
        AND OD.ORDER_ID = D.ORDER_ID
        AND OD.ORDER_LINE_NBR = D.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = 1
        AND CAL.DAY_DATE BETWEEN OD.EFF_DT AND OD.EXP_DT
        AND OD.ORDER_LN_CRT_DT = CAL.DAY_DATE
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.PO_TYPE_ID <> 'RO'

WHERE 
    CAL.DAY_DATE BETWEEN DATE '2015-03-01' AND DATE-1 --  BETWEEN (CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1) + 1 AND CURRENT_DATE - 1
    AND (
        C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N307', 'N317', 'N336', 'N302', 'N312', 'N322')
        OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN ('30', '31', '32'))
        )
    AND M.PBU_NBR = '01' -- IN ('01', '03')
    AND M.MKT_AREA_NBR <> '04'
    AND M.SUPER_BRAND_ID IN ('01', '02', '03', '05')

GROUP BY
    CAL.DAY_DATE
    , D.ORDER_FISCAL_YR
    , D.ORDER_ID
    , D.ORDER_LINE_NBR

    , D.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , OE_REPL_IND

    , D.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME

    , D.DELIV_LINE_FACILITY_ID
    , F.FACILITY_NAME

    , D.QTY_UNIT_MEAS_ID

UNION ALL

SELECT
    CAST('AGID' AS VARCHAR(15)) AS QRY_TYP
    , CAL.DAY_DATE
    , D.ORDER_FISCAL_YR
    , D.ORDER_ID
    , D.ORDER_LINE_NBR

    , D.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , CASE 
        WHEN (C.SALES_ORG_CD IN('N301', 'N311', 'N321', 'N307', 'N317', 'N336') OR (C.SALES_ORG_CD IN('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN('30', '31')))
           THEN('REPL')
        ELSE('OE')
        END AS OE_REPL_IND

    , D.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME

    , D.DELIV_LINE_FACILITY_ID AS FACILITY_ID
    , F.FACILITY_NAME

    , D.QTY_UNIT_MEAS_ID

    , SUM(CASE
        WHEN CAL.MONTH_DT = PGI_CAL.MONTH_DT
            THEN D.RPT_DELIV_QTY
        ELSE 0
        END) AS IN_PROC_QTY_CURR
    , SUM(CASE
        WHEN CAL.MONTH_DT < PGI_CAL.MONTH_DT
            THEN D.RPT_DELIV_QTY
        ELSE 0
        END) AS IN_PROC_QTY_FTR
    , SUM(D.RPT_DELIV_QTY) AS IN_PROC_QTY

FROM GDYR_BI_VWS.GDYR_CAL CAL

    INNER JOIN NA_VWS.DELIV_DTL D
        ON CAL.DAY_DATE = D.ACTL_GOODS_ISS_DT
        AND D.EXP_DT = DATE '5555-12-31'
        AND D.DELIV_CAT_ID = 'J'
        AND D.SD_DOC_CTGY_CD = 'C'
        AND D.DELIV_NOTE_CREA_DT = CAL.DAY_DATE
        AND D.ACTL_GOODS_ISS_DT IS NOT NULL

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = D.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = D.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = D.DELIV_LINE_FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.GDYR_CAL PGI_CAL
        ON PGI_CAL.DAY_DATE = D.PLN_GOODS_MVT_DT

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = D.ORDER_FISCAL_YR
        AND OD.ORDER_ID = D.ORDER_ID
        AND OD.ORDER_LINE_NBR = D.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = 1
        AND OD.EXP_DT = DATE '5555-12-31'
        --AND CAL.DAY_DATE BETWEEN OD.EFF_DT AND OD.EXP_DT
        AND OD.ORDER_LN_CRT_DT = CAL.DAY_DATE
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.PO_TYPE_ID <> 'RO'

WHERE 
    CAL.DAY_DATE BETWEEN DATE '2015-03-01' AND DATE-1 --  BETWEEN (CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1) + 1 AND CURRENT_DATE - 1
    AND (
        C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N307', 'N317', 'N336', 'N302', 'N312', 'N322')
        OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN ('30', '31', '32'))
        )
    AND M.PBU_NBR = '01' -- IN ('01', '03')
    AND M.MKT_AREA_NBR <> '04'
    AND M.SUPER_BRAND_ID IN ('01', '02', '03', '05')

GROUP BY
    CAL.DAY_DATE
    , D.ORDER_FISCAL_YR
    , D.ORDER_ID
    , D.ORDER_LINE_NBR

    , D.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , OE_REPL_IND

    , D.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME

    , D.DELIV_LINE_FACILITY_ID
    , F.FACILITY_NAME

    , D.QTY_UNIT_MEAS_ID

    ) Q

GROUP BY
    Q.QRY_TYP
    , Q.DAY_DATE
    , Q.PBU_NBR
    , Q.PBU_NAME
    , Q.OE_REPL_IND
    , Q.QTY_UNIT_MEAS_ID

ORDER BY
    Q.PBU_NBR
    , Q.OE_REPL_IND
    , Q.DAY_DATE
    , Q.QRY_TYP
    , Q.QTY_UNIT_MEAS_ID
