SELECT
    CAST('DIP' AS VARCHAR(25)) AS QRY_TYP
    , CASE 
        WHEN ODMS_PMW.ORDER_ID IS NOT NULL
            THEN ADD_MONTHS((CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1) + 1, - 1)
        WHEN ODS.ORDER_DT <= (CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1) OR ODS.ORDER_DT IS NULL
            THEN ADD_MONTHS((CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1) + 2, - 1)
        ELSE ODS.ORDER_DT
        END DAY_DT
    , M.PBU_NBR
    , M.PBU_NAME
    , CASE 
        WHEN C.SALES_ORG_CD IN('N301', 'N311', 'N321', 'N307', 'N317', 'N336') OR (C.SALES_ORG_CD IN('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN('30', '31'))
           THEN 'REPL'
        ELSE 'OE'
        END AS OE_REPL_IND
    , DIP.SLS_QTY_UNIT_MEAS_ID
    , CASE
        WHEN PGMV_CAL.MONTH_DT < CURRENT_DATE
            THEN 'PGMV Current'
        ELSE 'PGMV Future'
        END AS PGMV_MONTH_DESC
    , SUM(DIP.QTY_TO_SHIP) AS QTY_TO_SHIP
    , DIP.RPT_QTY_UNIT_MEAS_ID
    , SUM(DIP.RPT_QTY_TO_SHIP) AS RPT_QTY_TO_SHIP

FROM GDYR_VWS.DELIV_IN_PROC DIP

    INNER JOIN NA_BI_VWS.DELIVERY_DETAIL_CURR DDC
        ON DDC.FISCAL_YR = DIP.DELIV_FISCAL_YR
        AND DDC.DELIV_ID = DIP.DELIV_ID
        AND DDC.DELIV_LINE_NBR = DIP.DELIV_LINE_NBR
        AND DDC.ACTL_GOODS_ISS_DT IS NULL

    INNER JOIN GDYR_BI_VWS.GDYR_CAL PGMV_CAL
        ON PGMV_CAL.DAY_DATE = DDC.PLN_GOODS_MVT_DT

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = DDC.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID

    INNER JOIN NA_BI_VWS.ORD_DTL_SMRY ODS
        ON ODS.ORDER_FISCAL_YR = DIP.ORDER_FISCAL_YR
        AND ODS.ORDER_ID = DIP.ORDER_ID
        AND ODS.ORDER_LINE_NBR = DIP.ORDER_LINE_NBR
        AND ODS.RO_PO_TYPE_IND = 'N'

    LEFT JOIN NA_BI_VWS.ORD_DLV_MTH_SMRY ODMS_PMW
        ON DIP.ORDER_FISCAL_YR = ODMS_PMW.ORDER_FISCAL_YR
        AND DIP.ORDER_ID = ODMS_PMW.ORDER_ID
        AND DIP.ORDER_LINE_NBR = ODMS_PMW.ORDER_LINE_NBR
        AND ODMS_PMW.REF_DT = (CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1)
        AND ODMS_PMW.OPEN_CNFRM_PGI_PAST_MTH_QTY + ODMS_PMW.OPEN_CNFRM_PGI_PRIOR_MTH_QTY + ODMS_PMW.OPEN_CNFRM_PGI_CURR_MTH_QTY + ODMS_PMW.OPEN_CNFRM_PGI_NXT_MTH_QTY + ODMS_PMW.IN_PROC_PGMV_PAST_MTH_QTY + ODMS_PMW.IN_PROC_PGMV_PRIOR_MTH_QTY + ODMS_PMW.IN_PROC_PGMV_CURR_MTH_QTY + ODMS_PMW.IN_PROC_PGMV_NXT_MTH_QTY <> 0

WHERE
    DIP.ORIG_SYS_ID = 2
    AND DIP.EXP_DT = CAST('5555-12-31' AS DATE)
    AND DIP.INTRA_CMPNY_FLG = 'N'

    AND M.PBU_NBR = '01'
    AND M.SUPER_BRAND_ID IN ('01', '02', '03', '05')
    AND (
        C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N302', 'N312', 'N322', 'N307', 'N317', 'N336')
        OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN ('30', '31', '32'))
        )

GROUP BY
    DAY_DT
    , M.PBU_NBR
    , M.PBU_NAME
    , OE_REPL_IND
    , PGMV_MONTH_DESC
    , DIP.SLS_QTY_UNIT_MEAS_ID
    --, SUM(DIP.QTY_TO_SHIP) AS QTY_TO_SHIP
    , DIP.RPT_QTY_UNIT_MEAS_ID
    --, SUM(DIP.RPT_QTY_TO_SHIP) AS RPT_QTY_TO_SHIP

UNION ALL

SELECT
    CAST('OOSL' AS VARCHAR(25)) AS QRY_TYP
    , CASE 
        WHEN ODMS_PMW.ORDER_ID IS NOT NULL
            THEN ADD_MONTHS((CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1) + 1, - 1)
        WHEN ODS.ORDER_DT <= (CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1) OR ODS.ORDER_DT IS NULL
            THEN ADD_MONTHS((CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1) + 2, - 1)
        ELSE ODS.ORDER_DT
        END DAY_DT
    , M.PBU_NBR
    , M.PBU_NAME
    , CASE 
        WHEN C.SALES_ORG_CD IN('N301', 'N311', 'N321', 'N307', 'N317', 'N336') OR (C.SALES_ORG_CD IN('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN('30', '31'))
           THEN 'REPL'
        ELSE 'OE'
        END AS OE_REPL_IND
    , OOL.SLS_QTY_UNIT_MEAS_ID
    , CASE
        WHEN PGMV_CAL.MONTH_DT < CURRENT_DATE
            THEN 'PGMV Current'
        ELSE 'PGMV Future'
        END AS PGMV_MONTH_DESC
    , SUM(OOL.IN_PROC_QTY) AS QTY_TO_SHIP
    , OOL.RPT_QTY_UNIT_MEAS_ID
    , SUM(OOL.RPT_IN_PROC_QTY) AS RPT_QTY_TO_SHIP

FROM NA_VWS.OPEN_ORDER_SCHDLN OOL

    INNER JOIN GDYR_BI_VWS.GDYR_CAL PGMV_CAL
        ON PGMV_CAL.DAY_DATE = OOL.PLN_GOODS_ISS_DT

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OOL.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OOL.CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OOL.FACILITY_ID

    INNER JOIN NA_BI_VWS.ORDER_DETAIL ODS
        ON ODS.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND ODS.ORDER_ID = OOL.ORDER_ID
        AND ODS.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND ODS.SCHED_LINE_NBR = 1
        AND ODS.EXP_DT = CAST('5555-12-31' AS DATE)
        AND ODS.RO_PO_TYPE_IND = 'N'

    LEFT JOIN NA_BI_VWS.ORD_DLV_MTH_SMRY ODMS_PMW
        ON OOL.ORDER_FISCAL_YR = ODMS_PMW.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = ODMS_PMW.ORDER_ID
        AND OOL.ORDER_LINE_NBR = ODMS_PMW.ORDER_LINE_NBR
        AND ODMS_PMW.REF_DT = (CURRENT_DATE - 1) - EXTRACT(DAY FROM CURRENT_DATE - 1)
        AND ODMS_PMW.OPEN_CNFRM_PGI_PAST_MTH_QTY + ODMS_PMW.OPEN_CNFRM_PGI_PRIOR_MTH_QTY + ODMS_PMW.OPEN_CNFRM_PGI_CURR_MTH_QTY + ODMS_PMW.OPEN_CNFRM_PGI_NXT_MTH_QTY + ODMS_PMW.IN_PROC_PGMV_PAST_MTH_QTY + ODMS_PMW.IN_PROC_PGMV_PRIOR_MTH_QTY + ODMS_PMW.IN_PROC_PGMV_CURR_MTH_QTY + ODMS_PMW.IN_PROC_PGMV_NXT_MTH_QTY <> 0

WHERE
    OOL.ORIG_SYS_ID = 2
    AND OOL.EXP_DT = CAST('5555-12-31' AS DATE)
    --AND DIP.INTRA_CMPNY_FLG = 'N'

    AND M.PBU_NBR = '01'
    AND M.SUPER_BRAND_ID IN ('01', '02', '03', '05')
    AND (
        C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N302', 'N312', 'N322', 'N307', 'N317', 'N336')
        OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN ('30', '31', '32'))
        )

GROUP BY
    DAY_DT
    , M.PBU_NBR
    , M.PBU_NAME
    , OE_REPL_IND
    , PGMV_MONTH_DESC
    , OOL.SLS_QTY_UNIT_MEAS_ID
    --, SUM(DIP.QTY_TO_SHIP) AS QTY_TO_SHIP
    , OOL.RPT_QTY_UNIT_MEAS_ID
    --, SUM(DIP.RPT_QTY_TO_SHIP) AS RPT_QTY_TO_SHIP

ORDER BY 1,2,3,5,8

