SELECT
    M.PBU_NBR || ' - ' || M.PBU_NAME AS PBU

    , OOL.REF_DT AS "Snapshot Date"

    , OD.ORDER_DELIV_BLK_CD AS "Header Delivery Block Code"
    , OD.DELIV_BLK_CD AS "SL Delivery Block Code"

    , COUNT(DISTINCT OOL.ORDER_ID || OOL.ORDER_LINE_NBR) AS "Open Order Line Count"
    --, SUM(OOL.OPEN_CNFRM_QTY) AS OPEN_CNFRM_QTY
    --, SUM(OOL.UNCNFRM_QTY) AS UNCNFRM_QTY
    --, SUM(OOL.BACK_ORDER_QTY) AS BACK_ORDER_QTY
    --, SUM(OOL.DEFER_QTY) AS DEFER_QTY
    --, SUM(OOL.WAIT_LIST_QTY) AS WAIT_LIST_QTY
    --, SUM(OOL.OTHR_ORDER_QTY) AS OTHR_ORDER_QTY

FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_SNP OOL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_ID = OOL.ORDER_ID
        AND OD.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = OOL.SCHED_LINE_NBR
        AND ADD_MONTHS(OOL.REF_DT, 1) - CAST(1 AS INTERVAL DAY(4)) BETWEEN OD.EFF_DT AND OD.EXP_DT
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.RO_PO_TYPE_IND = 'N'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID

    --INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_cURR C
        --ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

WHERE
    OOL.REF_DT BETWEEN ADD_MONTHS(CURRENT_DATE-1, -13) AND CURRENT_DATE-1
    AND (
        OOL.OPEN_CNFRM_QTY > 0 
        OR OOL.UNCNFRM_QTY > 0
        OR OOL.BACK_ORDER_QTY > 0
        OR OOL.DEFER_QTY > 0
        OR OOL.WAIT_LIST_QTY > 0
        OR OOL.OTHR_ORDER_QTY > 0
        )
        
GROUP BY
    PBU
    , OOL.REF_DT

    , OD.ORDER_DELIV_BLK_CD
    , OD.DELIV_BLK_CD

ORDER BY
    PBU
    , OOL.REF_DT
    , OD.ORDER_DELIV_BLK_CD
    , OD.DELIV_BLK_CD
;