SELECT
    CASE
        WHEN OD.FACILITY_ID IN ('N5US', 'N5CA')
            THEN 'N5US / N5CA'
        ELSE 'PGI 2015-03-31'
        END AS QUERY_TYPE
    , OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR

    , OD.CUST_PO_NBR
    , OD.PO_TYPE_ID

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID

    , OD.ORDER_DELIV_BLK_CD
    , MAX(OD.DELIV_BLK_CD) AS SCHD_LN_DELIV_BLK_CD

    , OD.SHIP_COND_ID
    , OD.SPCL_PROC_ID
    , OD.PROD_ALLCT_DETERM_PROC_ID
    , OD.CUST_GRP2_CD
    , OD.SHIP_TO_CUST_ID

    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME
    , CASE 
        WHEN C.SALES_ORG_CD IN ('N302', 'N312', 'N322') OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD = '32')
            THEN 'OE'
        ELSE 'Replacement'
        END OE_REPL_IND

    , OD.MATL_ID
    , M.MATL_NO_8 || ' - ' || M.DESCR AS MATL_DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME

    , CASE
        WHEN OD.FACILITY_ID IN ('N5US', 'N5CA')
            THEN 'N5US / N5CA'
        WHEN OD.FACILITY_ID = C.PRIM_SHIP_FACILITY_ID
            THEN 'Primary LC'
        WHEN OD.FACILITY_ID LIKE 'N5%'
            THEN 'Factory Direct'
        ELSE 'Out of Area'
        END AS TEST_PRIM_SHIP_FACILITY_ID
    , C.PRIM_SHIP_FACILITY_ID
    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , OD.ORDER_DT
    , OD.ORDER_LN_CRT_DT
    , OD.FRST_MATL_AVL_DT
    , OD.FRST_PLN_GOODS_ISS_DT
    , OD.FRST_RDD
    , OD.FC_MATL_AVL_DT
    , OD.FC_PLN_GOODS_ISS_DT
    , OD.FRST_PROM_DELIV_DT

    , OD.PLN_MATL_AVL_DT
    , OD.PLN_GOODS_ISS_DT
    , OD.PLN_DELIV_DT

    , OOL.SLS_QTY_UNIT_MEAS_ID
    , SUM(OOL.OPEN_CNFRM_QTY) AS OPEN_CNFRM_QTY
    , SUM(OOL.UNCNFRM_QTY) AS UNCNFRM_QTY
    , SUM(OOL.BACK_ORDER_QTY) AS BACK_ORDER_QTY
    , SUM(OOL.WAIT_LIST_QTY) AS WAIT_LIST_QTY
    , SUM(OOL.OTHR_ORDER_QTY) AS OTHR_ORDER_QTY

FROM NA_VWS.OPEN_ORDER_SCHDLN OOL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND OD.ORDER_ID = OOL.ORDER_ID
        AND OD.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = OOL.SCHED_LINE_NBR
        AND OD.EXP_DT = OOL.EXP_DT
        --AND OD.ORDER_CAT_ID = 'C'
        AND OD.RO_PO_TYPE_IND = 'N'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        --AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        --AND F.DISTR_CHAN_CD = '81'

WHERE
    OOL.EXP_DT = CAST('5555-12-31' AS DATE)
    AND M.PBU_NBR = '01'
    --AND OOL.OPEN_CNFRM_QTY <> 0
    
    AND (
        OD.FACILITY_ID IN ('N5US', 'N5CA')    
        OR OD.PLN_GOODS_ISS_DT = DATE '2015-03-31'
        )

GROUP BY
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR

    , OD.CUST_PO_NBR
    , OD.PO_TYPE_ID

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID

    , OD.ORDER_DELIV_BLK_CD

    , OD.SHIP_COND_ID
    , OD.SPCL_PROC_ID
    , OD.PROD_ALLCT_DETERM_PROC_ID
    , OD.CUST_GRP2_CD
    , OD.SHIP_TO_CUST_ID

    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME
    , OE_REPL_IND

    , OD.MATL_ID
    , MATL_DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME

    , TEST_PRIM_SHIP_FACILITY_ID
    , C.PRIM_SHIP_FACILITY_ID
    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , OD.ORDER_DT
    , OD.ORDER_LN_CRT_DT
    , OD.FRST_MATL_AVL_DT
    , OD.FRST_PLN_GOODS_ISS_DT
    , OD.FRST_RDD
    , OD.FC_MATL_AVL_DT
    , OD.FC_PLN_GOODS_ISS_DT
    , OD.FRST_PROM_DELIV_DT

    , OD.PLN_MATL_AVL_DT
    , OD.PLN_GOODS_ISS_DT
    , OD.PLN_DELIV_DT

    , OOL.SLS_QTY_UNIT_MEAS_ID

ORDER BY
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
