SELECT
    OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR
    , COALESCE(OD.SCHED_LINE_NBR, OOL.SCHED_LINE_NBR) AS SCHED_LINE_NBR
    
    , CASE
        WHEN OD.SCHED_LINE_NBR IS NOT NULL
            THEN 'In Order Detail'
        END AS TEST_ORDER_DETAIL
    , CASE
        WHEN OOL.SCHED_LINE_NBR IS NOT NULL
            THEN 'In Open Order Sched Line'
        END AS TEST_OPEN_ORDER_SCHDLN
    
    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID
    , OD.PO_TYPE_ID
    
    , OD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , OD.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME

    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , OD.QTY_UNIT_MEAS_ID
    , (OD.ORDER_QTY) AS ORDER_QTY
    , (OD.CNFRM_QTY) AS CNFRM_QTY
    , (OOL.OPEN_CNFRM_QTY) AS OPEN_CNFRM_QTY
    , (OOL.UNCNFRM_QTY) AS UNCNFRM_QTY
    , (OOL.BACK_ORDER_QTY) AS BACK_ORDER_QTY
    , (OOL.DEFER_QTY) AS DEFER_QTY
    , (OOL.WAIT_LIST_QTY) AS WAIT_LIST_QTY
    , (OOL.OTHR_ORDER_QTY) AS OTHR_ORDER_QTY
    , (OOL.IN_PROC_QTY) AS IN_PROC_QTY

FROM NA_BI_VWS.ORDER_DETAIL OD

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M    
        ON M.MATL_ID = OD.MATL_ID
        AND M.EXT_MATL_GRP_ID = 'TIRE'
        AND M.PBU_NBR = '01'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    FULL OUTER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL
        ON OOL.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = OD.ORDER_ID
        AND OOL.ORDER_LINE_NBR = OD.ORDER_LINE_NBR
        AND OOL.SCHED_LINE_NBR = OD.SCHED_LINE_NBR
        AND (
                OOL.OPEN_CNFRM_QTY > 0
                OR OOL.UNCNFRM_QTY > 0
                OR OOL.BACK_ORDER_QTY > 0
                OR OOL.DEFER_QTY > 0
                OR OOL.WAIT_LIST_QTY > 0
            )

WHERE
    OD.EXP_DT = CAST('5555-12-31' AS DATE)
    AND OD.ORDER_CAT_ID = 'C'
    AND OD.PO_TYPE_ID <> 'RO'

    AND (OD.ORDER_FISCAL_YR, OD.ORDER_ID, OD.ORDER_LINE_NBR) IN (
        SELECT
            ORDER_FISCAL_YR
            , ORDER_ID
            , ORDER_LINE_NBR
        FROM NA_BI_VWS.OPEN_ORDER_ORDLN_CURR
        WHERE
            OPEN_CNFRM_QTY > 0
            OR UNCNFRM_QTY > 0
            OR BACK_ORDER_QTY > 0
            OR DEFER_QTY > 0
            OR WAIT_LIST_QTY > 0
    )

QUALIFY
    MIN(