SELECT
    O.SNAPSHOT_DATE
    , O.FIRST_OF_MONTH_IND
    , O.QTY_UOM
    , SUM(O.OPEN_CNFRM_PGI_CURR_QTY) AS OPEN_CNFRM_PGI_CURR_QTY
    , SUM(O.OPEN_CNFRM_PGI_FTR_QTY) AS OPEN_CNFRM_PGI_FTR_QTY
    , SUM(O.OPEN_CNFRM_PAST_DUE_QTY) AS OPEN_CNFRM_PAST_DUE_QTY
    , SUM(O.UNCNFRM_QTY) AS UNCNFRM_QTY
    , SUM(O.BACK_ORDER_QTY) AS BACK_ORDER_QTY
    , SUM(O.DEFER_QTY) AS DEFER_QTY
    , SUM(O.OTHR_ORDER_QTY) AS OTHR_ORDER_QTY
    , SUM(O.IN_PROC_PGMV_CURR_QTY) AS IN_PROC_PGMV_CURR_QTY
    , SUM(O.IN_PROC_PGMV_FTR_QTY) AS IN_PROC_PGMV_FTR_QTY
    , SUM(O.SHIP_CURR_QTY) AS SHIP_CURR_QTY

FROM (

SELECT
    CAL.DAY_DATE AS SNAPSHOT_DATE
    , CASE WHEN CAL.DAY_OF_MONTH = 1 THEN 'Y' ELSE 'N' END AS FIRST_OF_MONTH_IND
    , CAL.MONTH_DT
    , ADD_MONTHS(CAL.MONTH_DT, 1) AS NEXT_MONTH_DT

    , OOL.SLS_QTY_UNIT_MEAS_ID AS QTY_UOM
    , SUM(CASE WHEN OD.PLN_GOODS_ISS_DT < NEXT_MONTH_DT THEN OOL.OPEN_CNFRM_QTY ELSE 0 END) AS OPEN_CNFRM_PGI_CURR_QTY
    , SUM(CASE WHEN OD.PLN_GOODS_ISS_DT >= NEXT_MONTH_DT THEN OOL.OPEN_CNFRM_QTY ELSE 0 END) AS OPEN_CNFRM_PGI_FTR_QTY

    , SUM(CASE WHEN OD.FRST_RDD < SNAPSHOT_DATE THEN OOL.OPEN_CNFRM_QTY ELSE 0 END) AS OPEN_CNFRM_PAST_DUE_QTY

    , SUM(OOL.UNCNFRM_QTY) AS UNCNFRM_QTY
    , SUM(OOL.BACK_ORDER_QTY) AS BACK_ORDER_QTY
    , SUM(OOL.DEFER_QTY) AS DEFER_QTY
    , SUM(OOL.OTHR_ORDER_QTY) AS OTHR_ORDER_QTY
    , CAST(0 AS DECIMAL(15,3)) AS IN_PROC_PGMV_CURR_QTY
    , CAST(0 AS DECIMAL(15,3)) AS IN_PROC_PGMV_FTR_QTY
    , CAST(0 AS DECIMAL(15,3)) AS SHIP_CURR_QTY

FROM GDYR_BI_VWS.GDYR_CAL CAL

    INNER JOIN NA_VWS.OPEN_ORDER_SCHDLN OOL
        ON SNAPSHOT_DATE BETWEEN OOL.EFF_DT AND OOL.EXP_DT

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND OD.ORDER_ID = OOL.ORDER_ID
        AND OD.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = OOL.SCHED_LINE_NBR
        AND SNAPSHOT_DATE BETWEEN OD.EFF_DT AND OD.EXP_DT
        AND OD.RO_PO_TYPE_IND = 'N'
        -- REPLACEMENT ONLY
        AND (OD.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N307', 'N317', 'N336') OR (OD.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND OD.DISTR_CHAN_CD IN ('30', '31')))

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = OD.MATL_ID
        AND M.PBU_NBR = '01'

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

WHERE
    CAL.DAY_DATE = :0

GROUP BY
    SNAPSHOT_DATE
    , FIRST_OF_MONTH_IND
    , CAL.MONTH_DT
    , NEXT_MONTH_DT

    --, OOL.ORDER_FISCAL_YR
    --, OOL.ORDER_ID
    --, OOL.ORDER_LINE_NBR

    , QTY_UOM

UNION ALL

SELECT
    CAL.DAY_DATE AS SNAPSHOT_DATE
    , CASE WHEN CAL.DAY_OF_MONTH = 1 THEN 'Y' ELSE 'N' END AS FIRST_OF_MONTH_IND
    , CAL.MONTH_DT
    , ADD_MONTHS(CAL.MONTH_DT, 1) AS NEXT_MONTH_DT

    --, D.ORDER_FISCAL_YR
    --, D.ORDER_ID
    --, D.ORDER_LINE_NBR

    , DIP.SLS_QTY_UNIT_MEAS_ID AS QTY_UOM
    , 0 AS OPEN_CNFRM_PGI_CURR_QTY
    , 0 AS OPEN_CNFRM_PGI_FTR_QTY

    , 0 AS OPEN_CNFRM_PAST_DUE_QTY

    , 0 AS UNCNFRM_QTY
    , 0 AS BACK_ORDER_QTY
    , 0 AS DEFER_QTY
    , 0 AS OTHR_ORDER_QTY
    , SUM(CASE WHEN D.PLN_GOODS_MVT_DT < NEXT_MONTH_DT THEN DIP.QTY_TO_SHIP ELSE 0 END) AS IN_PROC_PGMV_CURR_QTY
    , SUM(CASE WHEN D.PLN_GOODS_MVT_DT >= NEXT_MONTH_DT THEN DIP.QTY_TO_SHIP ELSE 0 END) AS IN_PROC_PGMV_FTR_QTY
    , 0 AS SHIP_CURR_QTY

FROM GDYR_BI_VWS.GDYR_CAL CAL

    INNER JOIN GDYR_VWS.DELIV_IN_PROC DIP
        ON SNAPSHOT_DATE BETWEEN DIP.EFF_DT AND DIP.EXP_DT
        AND DIP.INTRA_CMPNY_FLG = 'N'

    INNER JOIN NA_VWS.DELIV_DTL D
        ON D.FISCAL_YR = DIP.DELIV_FISCAL_YR
        AND D.DELIV_ID = DIP.DELIV_ID
        AND D.DELIV_LINE_NBR = DIP.DELIV_LINE_NBR
        AND SNAPSHOT_DATE BETWEEN D.EFF_DT AND D.EXP_DT
        AND D.DELIV_CAT_ID = 'J'
        AND D.SD_DOC_CTGY_CD = 'C'
        AND D.ACTL_GOODS_ISS_DT IS NULL
        -- REPLACEMENT ONLY
        AND (D.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N307', 'N317', 'N336') OR (D.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND D.DISTR_CHAN_CD IN ('30', '31')))

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = D.ORDER_FISCAL_YR
        AND OD.ORDER_ID = D.ORDER_ID
        AND OD.ORDER_LINE_NBR = D.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = 1
        AND OD.EXP_DT = CAST('5555-12-31' AS DATE)

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = D.MATL_ID
        AND M.PBU_NBR = '01'

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = D.DELIV_LINE_FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

WHERE
    CAL.DAY_DATE = :0

GROUP BY
    SNAPSHOT_DATE
    , FIRST_OF_MONTH_IND
    , CAL.MONTH_DT
    , NEXT_MONTH_DT

    --, OOL.ORDER_FISCAL_YR
    --, OOL.ORDER_ID
    --, OOL.ORDER_LINE_NBR

    , QTY_UOM

UNION ALL

SELECT
    CAL.DAY_DATE AS SNAPSHOT_DATE
    , CASE WHEN CAL.DAY_OF_MONTH = 1 THEN 'Y' ELSE 'N' END AS FIRST_OF_MONTH_IND
    , CAL.MONTH_DT
    , ADD_MONTHS(CAL.MONTH_DT, 1) AS NEXT_MONTH_DT

    --, D.ORDER_FISCAL_YR
    --, D.ORDER_ID
    --, D.ORDER_LINE_NBR

    , D.QTY_UNIT_MEAS_ID AS QTY_UOM
    , 0 AS OPEN_CNFRM_PGI_CURR_QTY
    , 0 AS OPEN_CNFRM_PGI_FTR_QTY

    , 0 AS OPEN_CNFRM_PAST_DUE_QTY

    , 0 AS UNCNFRM_QTY
    , 0 AS BACK_ORDER_QTY
    , 0 AS DEFER_QTY
    , 0 AS OTHR_ORDER_QTY
    , 0 AS IN_PROC_PGMV_CURR_QTY
    , 0 AS IN_PROC_PGMV_FTR_QTY
    , SUM(D.DELIV_QTY) AS SHIP_CURR_QTY

FROM GDYR_BI_VWS.GDYR_CAL CAL

    INNER JOIN NA_VWS.DELIV_DTL D
        ON D.EXP_DT = CAST('5555-12-31' AS DATE)
        AND D.ACTL_GOODS_ISS_DT = SNAPSHOT_DATE
        AND D.DELIV_CAT_ID = 'J'
        AND D.SD_DOC_CTGY_CD = 'C'
        -- REPLACEMENT ONLY
        AND (D.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N307', 'N317', 'N336') OR (D.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND D.DISTR_CHAN_CD IN ('30', '31')))

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = D.ORDER_FISCAL_YR
        AND OD.ORDER_ID = D.ORDER_ID
        AND OD.ORDER_LINE_NBR = D.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = 1
        AND OD.EXP_DT = CAST('5555-12-31' AS DATE)

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = D.MATL_ID
        AND M.PBU_NBR = '01'

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = D.DELIV_LINE_FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

WHERE
    CAL.DAY_DATE = :0

GROUP BY
    SNAPSHOT_DATE
    , FIRST_OF_MONTH_IND
    , CAL.MONTH_DT
    , NEXT_MONTH_DT

    --, OOL.ORDER_FISCAL_YR
    --, OOL.ORDER_ID
    --, OOL.ORDER_LINE_NBR

    , QTY_UOM

    ) O

GROUP BY
    O.SNAPSHOT_DATE
    , O.FIRST_OF_MONTH_IND
    , O.QTY_UOM
