SELECT
    CAST('PGI' AS VARCHAR(25)) AS DOC_TYPE
    , OL_CAL.MONTH_DT AS ITM_CRT_MONTH_DT
    , RDD_CAL.MONTH_DT AS FRDD_MONTH_DT
    , CASE
        WHEN RDD_CAL.MONTH_DT > OL_CAL.MONTH_DT
            THEN 'Requested Future Month'
        ELSE 'Requested Same Month'
        END AS REQ_DELIV_DT_TYP_DESC

    , OD.MATL_ID
    , MATL.DESCR
    , MATL.MATL_PRTY
    , MATL.PBU_NBR
    , MATL.PBU_NAME
    , MATL.MKT_CTGY_MKT_AREA_NBR AS CATEGORY_CD
    , MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY_NAME
    , MATL.MKT_CTGY_PROD_LINE_NBR AS SALES_PROD_LINE_CD
    , MATL.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE_NM
    , CASE
        WHEN MATL.PBU_NBR = '01'
            THEN MATL.MKT_CTGY_PROD_GRP_NAME
        ELSE MATL.TIERS
        END AS TIER

    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , OD.QTY_UNIT_MEAS_ID
    , SUM(CASE WHEN IST.DELIV_STA_CD = 'A' THEN OD.ORDER_QTY ELSE 0 END) AS ORDER_QTY
    , SUM(OOL.OPEN_CNFRM_QTY) AS OPEN_CNFRM_QTY
    , SUM(CASE WHEN OD.PLN_GOODS_ISS_DT / 100 = OD.FRST_RDD / 100 THEN OOL.OPEN_CNFRM_QTY ELSE 0 END) AS CNFRM_IN_RDD_MTH_QTY
    , SUM(CASE WHEN OD.PLN_GOODS_ISS_DT / 100 = OD.FRST_RDD / 100 THEN OOL.OPEN_CNFRM_QTY ELSE 0 END) AS CNFRM_AFTER_RDD_MTH_QTY
    , CAST(0 AS DECIMAL(15,3)) AS CANCEL_QTY

FROM NA_BI_VWS.ORDER_DETAIL OD

    INNER JOIN NA_BI_VWS.SD_DOC_ITM_STA IST
        ON IST.FISCAL_YR = OD.ORDER_FISCAL_YR
        AND IST.SD_DOC_ID = OD.ORDER_ID
        AND IST.SD_DOC_ITM_ID = OD.ORDER_LINE_NBR
        AND IST.EXP_DT = CAST('5555-12-31' AS DATE)
        AND IST.ORIG_SYS_ID = 2
        AND IST.DELIV_STA_CD IS NOT NULL

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = OD.MATL_ID
        AND MATL.MATL_TYPE_ID = 'PCTL'
        AND MATL.EXT_MATL_GRP_ID = 'TIRE'
        AND MATL.PBU_NBR = '01'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID
        AND CUST.SALES_ORG_CD IN ('N301', 'N311', 'N321')

    INNER JOIN GDYR_BI_VWS.GDYR_CAL OL_CAL
        ON OL_CAL.DAY_DATE = OD.ORDER_LN_CRT_DT

    INNER JOIN GDYR_BI_VWS.GDYR_CAL RDD_CAL
        ON RDD_CAL.DAY_DATE = OD.FRST_RDD

    INNER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL
        ON OOL.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = OD.ORDER_ID
        AND OOL.ORDER_LINE_NBR = OD.ORDER_LINE_NBR
        AND OOL.SCHED_LINE_NBR = OD.SCHED_LINE_NBR
    
WHERE
    OD.EXP_DT = CAST('5555-12-31' AS DATE)
    AND OD.ORDER_CAT_ID = 'C'
    AND OD.RO_PO_TYPE_IND = 'N'
    AND OD.ORDER_LN_CRT_DT >= CAST('2014-01-01' AS DATE)

GROUP BY
    DOC_TYPE
    , OL_CAL.MONTH_DT
    , RDD_CAL.MONTH_DT 
    , CASE
        WHEN RDD_CAL.MONTH_DT > OL_CAL.MONTH_DT
            THEN 'Requested Future Month'
        ELSE 'Requested Same Month'
        END

    , OD.MATL_ID
    , MATL.DESCR
    , MATL.MATL_PRTY
    , MATL.PBU_NBR
    , MATL.PBU_NAME
    , MATL.MKT_CTGY_MKT_AREA_NBR AS CATEGORY_CD
    , MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY_NAME
    , MATL.MKT_CTGY_PROD_LINE_NBR AS SALES_PROD_LINE_CD
    , MATL.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE_NM
    , CASE
        WHEN MATL.PBU_NBR = '01'
            THEN MATL.MKT_CTGY_PROD_GRP_NAME
        ELSE MATL.TIERS
        END AS TIER

    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , OD.QTY_UNIT_MEAS_ID