

SELECT
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    , OOL.SCHED_LINE_NBR

    , OD.ORIG_ORDER_LINE_NBR
    , CASE
        WHEN OD.ORIG_ORDER_LINE_NBR = 0 OR OD.ORIG_ORDER_LINE_NBR = OD.ORDER_LINE_NBR
            THEN 'N'
        ELSE 'Y'
        END AS SPLIT_LINE_IND

    , OD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME
    , CASE
        WHEN C.SALES_ORG_CD IN ('N302', 'N312', 'N322') OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD = '32')
            THEN 'O'
        ELSE 'R'
        END OE_REPL_CD
    , CASE OE_REPL_CD
        WHEN 'O' THEN 'OE'
        WHEN 'R' THEN 'Replacement'
        ELSE 'Undefined'
        END AS OE_REPL_DESC

    , OD.MATL_ID
    , M.TIC_CD
    , M.MATL_NO_8 || ' - ' || M.DESCR AS MATL_DESCR
    , M.SUPER_BRAND_ID
    , M.SUPER_BRAND_NAME
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME
    , M.EXT_MATL_GRP_ID
    , M.MATL_TYPE_ID
    , M.SAL_IND
    , M.MATL_STA_ID
    , M.MATL_STA_DT
    , M.STK_CLASS_ID
    , M.STK_CLASS_DT
    , M.MATL_PRTY
    , M.HVA_TXT
    , M.HMC_TXT

    , CAST(CASE
        WHEN OD.FACILITY_ID IN ('N5US', 'N5CA')
            THEN 'N'
        WHEN C.PRIM_SHIP_FACILITY_ID = OD.FACILITY_ID
            THEN 'P'
        WHEN OD.FACILITY_ID LIKE 'N5%'
            THEN 'F'
        ELSE 'O'
        END AS CHAR(1)) AS TEST_PRIM_SHIP_FACILITY_CD
    , CAST(CASE TEST_PRIM_SHIP_FACILITY_CD
        WHEN 'N' THEN 'N5US / N5CA'
        WHEN 'P' THEN 'Primary LC'
        WHEN 'F' THEN 'Factory Direct'
        WHEN 'O' THEN 'Out of Area'
        END AS VARCHAR(35)) AS TEST_PRIM_SHIP_FACILITY_DESC
    , CASE TEST_PRIM_SHIP_FACILITY_CD
        WHEN 'P' THEN 0
        WHEN 'O' THEN 10
        WHEN 'N' THEN 25
        WHEN 'F' THEN 50
        ELSE 99
        END AS TEST_PRIM_SHIP_FACILITY_SORT_KEY
    , C.PRIM_SHIP_FACILITY_ID
    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID
    , OD.PO_TYPE_ID

    , OD.ORDER_DELIV_BLK_CD
    , OD.DELIV_BLK_CD
    , OOL.CREDIT_HOLD_FLG

    , OD.DELIV_PRTY_ID
    , OD.PRTL_DLVY_CD
    , OD.SHIP_COND_ID
    , OD.PROD_ALLCT_DETERM_PROC_ID
    , OD.CUST_GRP2_CD
    , OD.AVAIL_CHK_GRP_CD
    , OD.SPCL_PROC_ID
    , OD.ROUTE_ID
    , OD.WAIT_LIST_CD

    , OD.ORDER_DT
    , OD.ORDER_CRT_TM
    , OD.ORDER_LN_CRT_DT
    , OD.ORDER_LN_CRT_TM
    , OD.CUST_RDD
    , OD.FRST_MATL_AVL_DT
    , OD.FRST_PLN_GOODS_ISS_DT
    , OD.FRST_RDD
    , OD.FC_MATL_AVL_DT
    , OD.FC_PLN_GOODS_ISS_DT
    , OD.FRST_PROM_DELIV_DT
    , OD.PLN_MATL_AVL_DT
    , OD.PLN_GOODS_ISS_DT
    , OD.PLN_DELIV_DT

    , OD.QTY_UNIT_MEAS_ID AS QTY_UOM
    , OD.ORDER_QTY
    , OD.CNFRM_QTY

    , OOL.SLS_QTY_UNIT_MEAS_ID AS SLS_QTY_UOM
    , OOL.OPEN_CNFRM_QTY
    , OOL.UNCNFRM_QTY + OOL.BACK_ORDER_QTY AS UNCONFIRMED_QTY
    , OOL.WAIT_LIST_QTY + OOL.DEFER_QTY AS WAIT_LIST_QTY
    , OOL.OTHR_ORDER_QTY
    , OOL.IN_PROC_QTY

    , ZEROIFNULL(FMI.TOT_QTY) AS TOT_QTY
    , ZEROIFNULL(FMI.AVAIL_TO_PROM_QTY) AS AVAIL_TO_PROM_QTY
    , ZEROIFNULL(FMI.STO_INBOUND_QTY) AS STO_INBOUND_QTY
    , ZEROIFNULL(FMI.IN_TRANS_QTY) AS IN_TRANS_QTY
    , ZEROIFNULL(FMI.STO_OUTBOUND_QTY) AS STO_OUTBOUND_QTY
    , ZEROIFNULL(FMI.IN_PROS_TO_CUST_QTY) AS IN_PROS_TO_CUST_QTY
    , ZEROIFNULL(FMI.RSVR_QTY) AS RSVR_QTY
    , ZEROIFNULL(FMI.QUAL_INSP_QTY) AS QUAL_INSP_QTY
    , ZEROIFNULL(FMI.BLOCKED_STK_QTY) AS BLOCKED_STK_QTY
    , ZEROIFNULL(FMI.RSTR_QTY) AS RSTR_QTY
    , ZEROIFNULL(FMI.STK_RET_QTY) AS STK_RET_QTY
    , ZEROIFNULL(FMI.SAFE_STK_QTY) AS SAFE_STK_QTY
    , ZEROIFNULL(FMI.COMMIT_ON_HAND_QTY) AS COMMIT_ON_HAND_QTY
    , ZEROIFNULL(FMI.COMMIT_IN_TRANS_QTY) AS COMMIT_IN_TRANS_QTY
    , ZEROIFNULL(FMI.EST_DAYS_SUPPLY) AS EST_DAYS_SUPPLY

    , ZEROIFNULL(NI.NTWK_ATP_QTY) AS NTWK_ATP_QTY
    , ZEROIFNULL(NI.NTWK_TOT_QTY) AS NTWK_TOT_QTY
    , ZEROIFNULL(NI.NTWK_IN_TRANS_QTY) AS NTWK_IN_TRANS_QTY
    , ZEROIFNULL(NI.N602_ATP_QTY) AS N602_ATP_QTY
    , ZEROIFNULL(NI.N607_ATP_QTY) AS N607_ATP_QTY
    , ZEROIFNULL(NI.N623_ATP_QTY) AS N623_ATP_QTY
    , ZEROIFNULL(NI.N636_ATP_QTY) AS N636_ATP_QTY
    , ZEROIFNULL(NI.N637_ATP_QTY) AS N637_ATP_QTY
    , ZEROIFNULL(NI.N639_ATP_QTY) AS N639_ATP_QTY
    , ZEROIFNULL(NI.N699_ATP_QTY) AS N699_ATP_QTY
    , ZEROIFNULL(NI.N6D3_ATP_QTY) AS N6D3_ATP_QTY
    , ZEROIFNULL(NI.N602_DSI) AS N602_DSI
    , ZEROIFNULL(NI.N607_DSI) AS N607_DSI
    , ZEROIFNULL(NI.N623_DSI) AS N623_DSI
    , ZEROIFNULL(NI.N636_DSI) AS N636_DSI
    , ZEROIFNULL(NI.N637_DSI) AS N637_DSI
    , ZEROIFNULL(NI.N639_DSI) AS N639_DSI
    , ZEROIFNULL(NI.N699_DSI) AS N699_DSI
    , ZEROIFNULL(NI.N6D3_DSI) AS N6D3_DSI

FROM NA_VWS.OPEN_ORDER_SCHDLN OOL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND OD.ORDER_ID = OOL.ORDER_ID
        AND OD.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = OOL.SCHED_LINE_NBR
        AND OD.EXP_DT = OOL.EXP_DT
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.RO_PO_TYPE_IND = 'N'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    LEFT OUTER JOIN NA_BI_VWS.FACILITY_MATL_INVENTORY FMI
        ON FMI.FACILITY_ID = OD.FACILITY_ID
        AND FMI.MATL_ID = OD.MATL_ID
        AND FMI.DAY_DT = CURRENT_DATE-1

    LEFT OUTER JOIN (
        SELECT
            MATL_ID
            , SUM(AVAIL_TO_PROM_QTY) AS NTWK_ATP_QTY
            , SUM(TOT_QTY) AS NTWK_TOT_QTY
            , SUM(IN_TRANS_QTY) AS NTWK_IN_TRANS_QTY
            , SUM(CASE WHEN FACILITY_ID = 'N602' THEN AVAIL_TO_PROM_QTY ELSE 0 END) AS N602_ATP_QTY
            , SUM(CASE WHEN FACILITY_ID = 'N607' THEN AVAIL_TO_PROM_QTY ELSE 0 END) AS N607_ATP_QTY
            , SUM(CASE WHEN FACILITY_ID = 'N623' THEN AVAIL_TO_PROM_QTY ELSE 0 END) AS N623_ATP_QTY
            , SUM(CASE WHEN FACILITY_ID = 'N636' THEN AVAIL_TO_PROM_QTY ELSE 0 END) AS N636_ATP_QTY
            , SUM(CASE WHEN FACILITY_ID = 'N637' THEN AVAIL_TO_PROM_QTY ELSE 0 END) AS N637_ATP_QTY
            , SUM(CASE WHEN FACILITY_ID = 'N639' THEN AVAIL_TO_PROM_QTY ELSE 0 END) AS N639_ATP_QTY
            , SUM(CASE WHEN FACILITY_ID = 'N699' THEN AVAIL_TO_PROM_QTY ELSE 0 END) AS N699_ATP_QTY
            , SUM(CASE WHEN FACILITY_ID = 'N6D3' THEN AVAIL_TO_PROM_QTY ELSE 0 END) AS N6D3_ATP_QTY

            , MAX(CASE WHEN FACILITY_ID = 'N602' THEN EST_DAYS_SUPPLY ELSE 0 END) AS N602_DSI
            , MAX(CASE WHEN FACILITY_ID = 'N607' THEN EST_DAYS_SUPPLY ELSE 0 END) AS N607_DSI
            , MAX(CASE WHEN FACILITY_ID = 'N623' THEN EST_DAYS_SUPPLY ELSE 0 END) AS N623_DSI
            , MAX(CASE WHEN FACILITY_ID = 'N636' THEN EST_DAYS_SUPPLY ELSE 0 END) AS N636_DSI
            , MAX(CASE WHEN FACILITY_ID = 'N637' THEN EST_DAYS_SUPPLY ELSE 0 END) AS N637_DSI
            , MAX(CASE WHEN FACILITY_ID = 'N639' THEN EST_DAYS_SUPPLY ELSE 0 END) AS N639_DSI
            , MAX(CASE WHEN FACILITY_ID = 'N699' THEN EST_DAYS_SUPPLY ELSE 0 END) AS N699_DSI
            , MAX(CASE WHEN FACILITY_ID = 'N6D3' THEN EST_DAYS_SUPPLY ELSE 0 END) AS N6D3_DSI
        FROM NA_BI_vWS.FACILITY_MATL_INVENTORY

        WHERE
            DAY_DT = CURRENT_DATE-1
            AND FACILITY_ID IN ('N602', 'N607', 'N623', 'N636', 'N637', 'N639', 'N699', 'N6D3')

        GROUP BY MATL_ID
        ) NI
        ON NI.MATL_ID = OD.MATL_ID

WHERE
    OOL.EXP_DT = CAST('5555-12-31' AS DATE)
    AND M.PBU_NBR = '01'
