SELECT
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR

    , OD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , OD.FACILITY_ID

    , OD.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME

    , OD.ORDER_DELIV_BLK_CD
    , OD.DELIV_BLK_CD
    , OOL.CREDIT_HOLD_FLG

    , OD.ORDER_DT
    , CAST(OD.ORDER_DT - CURRENT_DATE AS INTEGER) AS ORDER_DT_TO_CURR
    , OD.ORDER_LN_CRT_DT
    , CAST(OD.ORDER_DT - CURRENT_DATE AS INTEGER) AS ITEM_DT_TO_CURR

    , SUM(OOL.OPEN_CNFRM_QTY) AS OPEN_CNFRM_QTY
    , SUM(OOL.UNCNFRM_QTY) AS UNCNFRM_QTY
    , SUM(OOL.BACK_ORDER_QTY) AS BACK_ORDER_QTY
    , SUM(OOL.WAIT_LIST_QTY) AS WAIT_LIST_QTY
    , SUM(OOL.OTHR_ORDER_QTY) AS OTHR_ORDER_QTY

FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND OD.ORDER_ID = OOL.ORDER_ID
        AND OD.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = 1
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.RO_PO_TYPE_IND = 'N'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_cURR M
        ON M.MATL_ID = OD.MATL_ID
        AND M.PBU_NBR = '01'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_cURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

WHERE
    OOL.IN_PROC_QTY = 0

GROUP BY
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR

    , OD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , OD.FACILITY_ID

    , OD.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME

    , OD.ORDER_DELIV_BLK_CD
    , OD.DELIV_BLK_CD
    , OOL.CREDIT_HOLD_FLG

    , OD.ORDER_DT
    , ORDER_DT_TO_CURR
    , OD.ORDER_LN_CRT_DT
    , ITEM_DT_TO_CURR
