SELECT
    SA.MATL_ID
    , SA.DESCR
    , SA.PBU_NBR
    , SA.PBU_NAME
    , SA.MKT_AREA_NBR
    , SA.MKT_AREA_NAME
    , SA.FACILITY_ID
    , SA.FACILITY_NAME
    , SA.OUTLN_AGRMNT_VLD_FRM_DT
    , SA.OUTLN_AGRMNT_VLD_TO_DT

    , SA.QTY_UOM
    , SA.SA_TARGET_QTY
    , SA.SA_SL_TARGET_QTY
    , SA.SA_SL_CNFRM_QTY
    , SA.SA_SL_CNFRM_IN_PD_QTY
    , SA.SLS_ORDER_QTY
    , SA.SA_UTILIZATION_QTY
    , ZEROIFNULL(SUM(ORD.DELIV_LATE_QTY)) AS DELIV_LATE_QTY

FROM (

SELECT
    SA_UTL.MATL_ID
    , SA_UTL.DESCR
    , SA_UTL.PBU_NBR
    , SA_UTL.PBU_NAME
    , SA_UTL.MKT_AREA_NBR
    , SA_UTL.MKT_AREA_NAME
    , SA_UTL.FACILITY_ID
    , SA_UTL.FACILITY_NAME
    , SA_UTL.OUTLN_AGRMNT_VLD_FRM_DT
    , SA_UTL.OUTLN_AGRMNT_VLD_TO_DT
    --, SA_UTL.OWN_CUST_ID
    --, SA_UTL.OWN_CUST_NAME

    , SA_UTL.QTY_UOM
    , SUM(SA_UTL.SA_TARGET_QTY) AS SA_TARGET_QTY
    , SUM(SA_UTL.SA_SL_TARGET_QTY) AS SA_SL_TARGET_QTY
    , SUM(SA_UTL.SA_SL_CNFRM_QTY) AS SA_SL_CNFRM_QTY
    , SUM(SA_UTL.SA_SL_CNFRM_IN_PD_QTY) AS SA_SL_CNFRM_IN_PD_QTY
    , SUM(SA_UTL.SLS_ORDER_QTY) AS SLS_ORDER_QTY
    , SUM(SA_UTL.SA_UTILIZATION_QTY) AS SA_UTILIZATION_QTY

FROM (

SELECT
    SDI_BOM.FISCAL_YR
    , SDI_BOM.SLS_DOC_ID
    , SDI_BOM.SLS_DOC_ITM_ID

    , SD.SRC_CRT_DT
    , SD.SRC_CRT_TM
    , SD.DOC_DT
    , SD.SRC_UPD_DT
    , SDI_BOM.SRC_CRT_TS AS ITM_CRT_TS
    , SDI_BOM.SRC_CRT_USR_ID AS ITM_CRT_USR_ID
    , SDI_BOM.SRC_UPD_DT AS ITM_UPD_DT
    , SD.SAP_TRANS_CD
    , SD.INQ_QTE_VLD_FRM_DT
    , SD.INQ_QTE_VLD_TO_DT
    , SD.OUTLN_AGRMNT_VLD_FRM_DT
    , SD.OUTLN_AGRMNT_VLD_TO_DT
    , SD.REQ_DELIV_DT AS HDR_REQ_DELIV_DT

    , SD.CUST_PRCH_ORD_ID
    , SD.CUST_PRCH_ORD_TYP_CD
    , SD.CUST_PRCH_ORD_DT

    , SD.SD_DOC_CTGY_CD
    , SD.SLS_DOC_TYP_CD
    , SDI_BOM.SLS_DOC_ITM_CTGY_CD
    , SDI_BOM.ITM_TYP_CD

    , SD.CO_CD
    , SD.SALES_ORG_CD
    , SD.DISTR_CHAN_CD
    , SD.DIV_CD
    , SD.SOLD_TO_CUST_ID
    , SD.SHIP_TO_CUST_ID
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , SDI_BOM.MATL_ID
    , M.DESCR
    , SDI_BOM.MATL_HIER_ID
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME

    , SDI_BOM.FACILITY_ID
    , F.FACILITY_NAME
    , SDI_BOM.SHIP_RCVE_PT_CD

    , SDI_BOM.REJ_REAS_ID AS BOM_REJ_REAS_ID
    --, SDI_EOM.REJ_REAS_ID AS EOM_REJ_REAS_ID

    , SDI_BOM.ITM_RLVNT_DELIV_IND
    , SDI_BOM.ITM_RLVNT_BILL_ICD

    , SDI_BOM.SLS_UOM_CD AS QTY_UOM
    , SDI_BOM.SLS_UNIT_CUM_ORD_QTY AS SA_TARGET_QTY
    , SUM(SL.SLS_UNIT_ORD_QTY) AS SA_SL_TARGET_QTY
    , SUM(SL.SLS_UNIT_CNFRM_QTY) AS SA_SL_CNFRM_QTY
    , SUM(CASE WHEN SL.MATL_AVAIL_DT BETWEEN SD.OUTLN_AGRMNT_VLD_FRM_DT AND SD.OUTLN_AGRMNT_VLD_TO_DT THEN SL.SLS_UNIT_CNFRM_QTY ELSE 0 END) AS SA_SL_CNFRM_IN_PD_QTY

    , ZEROIFNULL(UTL.ORDER_QTY) AS SLS_ORDER_QTY
    , ZEROIFNULL(UTL.DELIV_QTY) AS SA_UTILIZATION_QTY

FROM NA_BI_VWS.NAT_SLS_DOC SD

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = SD.SHIP_TO_CUST_ID

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM SDI_BOM
        ON SD.FISCAL_YR = SDI_BOM.FISCAL_YR
        AND SD.SLS_DOC_ID = SDI_BOM.SLS_DOC_ID
        AND SDI_BOM.SLS_DOC_ITM_CTGY_CD = 'LZMA'
        AND SD.OUTLN_AGRMNT_VLD_FRM_DT BETWEEN SDI_BOM.EFF_DT AND SDI_BOM.EXP_DT
        AND SDI_BOM.REJ_REAS_ID IS NULL
        AND SDI_BOM.SRC_CRT_TS BETWEEN ADD_MONTHS(CURRENT_TIMESTAMP, -6) AND ADD_MONTHS(CURRENT_TIMESTAMP, 3)

    --INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM SDI_EOM
        --ON SDI_EOM.FISCAL_YR = SDI_BOM.FISCAL_YR
        --AND SDI_EOM.SLS_DOC_ID = SDI_BOM.SLS_DOC_ID
        --AND SDI_EOM.SLS_DOC_ITM_ID = SDI_BOM.SLS_DOC_ITM_ID
        --AND SDI_EOM.SLS_DOC_ITM_CTGY_CD = 'LZMA'
        --AND SD.OUTLN_AGRMNT_VLD_TO_DT BETWEEN SDI_EOM.EFF_DT AND SDI_EOM.EXP_DT
        --AND SDI_EOM.SRC_CRT_TS BETWEEN ADD_MONTHS(CURRENT_TIMESTAMP, -6) AND ADD_MONTHS(CURRENT_TIMESTAMP, 3)

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = SDI_BOM.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = SDI_BOM.MATL_ID
        AND M.PBU_NBR = '01'

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_SCHD_LN SL
        ON SL.FISCAL_YR = SDI_BOM.FISCAL_YR
        AND SL.SLS_DOC_ID = SDI_BOM.SLS_DOC_ID
        AND SL.SLS_DOC_ITM_ID = SDI_BOM.SLS_DOC_ITM_ID
        AND SD.OUTLN_AGRMNT_VLD_TO_DT - CAST(1 AS INTERVAL DAY(4)) BETWEEN SL.EFF_DT AND SL.EXP_DT
        AND SL.MATL_AVAIL_DT BETWEEN ADD_MONTHS(CURRENT_DATE, -6) AND ADD_MONTHS(CURRENT_DATE, 3)

    LEFT OUTER JOIN (
        SELECT
            Q.SA_FISCAL_YR
            , Q.SA_DOC_ID
            , Q.SA_DOC_ITM_ID
            , Q.SA_DOC_CTGY_CD
            , Q.QTY_UNIT_MEAS_ID
            , SUM(Q.ORDER_QTY) AS ORDER_QTY
            , SUM(DD.DELIV_QTY) AS DELIV_QTY
        FROM (
            SELECT
                DF.PREV_FISCAL_YR AS SA_FISCAL_YR
                , DF.PREV_SD_DOC_ID AS SA_DOC_ID
                , DF.PREV_SD_DOC_ITM_ID AS SA_DOC_ITM_ID
                , DF.PREV_SD_DOC_CTGY_CD AS SA_DOC_CTGY_CD
                , DF.NEXT_FISCAL_YR AS ORDER_FISCAL_YR
                , DF.NEXT_SD_DOC_ID AS ORDER_ID
                , DF.NEXT_SD_DOC_ITM_ID AS ORDER_LINE_NBR
                , DF.NEXT_SD_DOC_CTGY_CD AS ORDER_CAT_ID
                , OD.QTY_UNIT_MEAS_ID
                , MAX(OD.ORDER_QTY) AS ORDER_QTY
            FROM GDYR_VWS.SD_DOC_FLOW DF
                INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
                    ON OD.ORDER_FISCAL_YR = DF.NEXT_FISCAL_YR
                    AND OD.ORDER_ID = DF.NEXT_SD_DOC_ID
                    AND OD.ORDER_LINE_NBR = DF.NEXT_SD_DOC_ITM_ID
                    AND OD.ORDER_CAT_ID = DF.NEXT_SD_DOC_CTGY_cD
                    AND OD.EXP_DT = DF.EXP_DT
            WHERE
                DF.EXP_DT = CAST('5555-12-31' AS DATE)
                AND DF.ORIG_SYS_ID = 2
                AND DF.PREV_SD_DOC_CTGY_CD = 'E'
                AND DF.NEXT_SD_DOC_CTGY_CD = 'C'
                AND DF.CRT_DT BETWEEN DATE '2015-02-01' AND DATE '2015-02-28'
            GROUP BY
                DF.PREV_FISCAL_YR
                , DF.PREV_SD_DOC_ID
                , DF.PREV_SD_DOC_ITM_ID
                , DF.PREV_SD_DOC_CTGY_CD
                , DF.NEXT_FISCAL_YR
                , DF.NEXT_SD_DOC_ID
                , DF.NEXT_SD_DOC_ITM_ID
                , DF.NEXT_SD_DOC_CTGY_CD
                , OD.QTY_UNIT_MEAS_ID
            ) Q
            INNER JOIN NA_VWS.DELIV_DTL DD
                ON DD.ORDER_FISCAL_YR = Q.ORDER_FISCAL_YR
                AND DD.ORDER_ID = Q.ORDER_ID
                AND DD.ORDER_LINE_NBR = Q.ORDER_LINE_NBR
                AND DD.EXP_DT = CAST('5555-12-31' AS DATE)
                AND DD.DELIV_CAT_ID = 'J'
                AND DD.DELIV_NOTE_CREA_DT BETWEEN DATE '2015-02-01' AND DATE '2015-02-28'
        GROUP BY
            Q.SA_FISCAL_YR
            , Q.SA_DOC_ID
            , Q.SA_DOC_ITM_ID
            , Q.SA_DOC_CTGY_CD
            , Q.QTY_UNIT_MEAS_ID
            ) UTL
        ON UTL.SA_FISCAL_YR = SDI_BOM.FISCAL_YR
        AND UTL.SA_DOC_ID = SDI_BOM.SLS_DOC_ID
        AND UTL.SA_DOC_ITM_ID = SDI_BOM.SLS_DOC_ITM_ID
        AND UTL.SA_DOC_CTGY_CD = SD.SD_DOC_CTGY_CD

WHERE
    SD.EXP_DT = CAST('5555-12-31' AS DATE)
    AND DATE '2015-02-01' BETWEEN SD.OUTLN_AGRMNT_VLD_FRM_DT AND SD.OUTLN_AGRMNT_VLD_TO_DT
    AND SD.SD_DOC_CTGY_CD = 'E'
    AND SD.SLS_DOC_TYP_CD = 'ZLZ'
    AND SD.CO_CD IN ('N101', 'N102', 'N266')    

GROUP BY
    SDI_BOM.FISCAL_YR
    , SDI_BOM.SLS_DOC_ID
    , SDI_BOM.SLS_DOC_ITM_ID

    , SD.SRC_CRT_DT
    , SD.SRC_CRT_TM
    , SD.DOC_DT
    , SD.SRC_UPD_DT
    , SDI_BOM.SRC_CRT_TS
    , SDI_BOM.SRC_CRT_USR_ID
    , SDI_BOM.SRC_UPD_DT
    , SD.SAP_TRANS_CD
    , SD.INQ_QTE_VLD_FRM_DT
    , SD.INQ_QTE_VLD_TO_DT
    , SD.OUTLN_AGRMNT_VLD_FRM_DT
    , SD.OUTLN_AGRMNT_VLD_TO_DT
    , SD.REQ_DELIV_DT

    , SD.CUST_PRCH_ORD_ID
    , SD.CUST_PRCH_ORD_TYP_CD
    , SD.CUST_PRCH_ORD_DT

    , SD.SD_DOC_CTGY_CD
    , SD.SLS_DOC_TYP_CD
    , SDI_BOM.SLS_DOC_ITM_CTGY_CD
    , SDI_BOM.ITM_TYP_CD
    --, SL.SCHD_LN_CTGY_CD

    , SD.CO_CD
    , SD.SALES_ORG_CD
    , SD.DISTR_CHAN_CD
    , SD.DIV_CD
    , SD.SOLD_TO_CUST_ID
    , SD.SHIP_TO_CUST_ID
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , SDI_BOM.MATL_ID
    , M.DESCR
    , SDI_BOM.MATL_HIER_ID
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME

    , SDI_BOM.FACILITY_ID
    , F.FACILITY_NAME
    , SDI_BOM.SHIP_RCVE_PT_CD

    , SDI_BOM.REJ_REAS_ID
    --, SDI_EOM.REJ_REAS_ID

    , SDI_BOM.ITM_RLVNT_DELIV_IND
    , SDI_BOM.ITM_RLVNT_BILL_ICD

    , SDI_BOM.SLS_UOM_CD
    , SDI_BOM.SLS_UNIT_CUM_ORD_QTY
    , SDI_BOM.SLS_UNIT_CUM_REQ_DELIV_QTY
    , SDI_BOM.SLS_UNIT_CUM_CNFRM_QTY
    
    , ZEROIFNULL(UTL.ORDER_QTY)
    , ZEROIFNULL(UTL.DELIV_QTY)

    ) SA_UTL

GROUP BY
    SA_UTL.MATL_ID
    , SA_UTL.DESCR
    , SA_UTL.PBU_NBR
    , SA_UTL.PBU_NAME
    , SA_UTL.MKT_AREA_NBR
    , SA_UTL.MKT_AREA_NAME
    , SA_UTL.FACILITY_ID
    , SA_UTL.FACILITY_NAME
    , SA_UTL.OUTLN_AGRMNT_VLD_FRM_DT
    , SA_UTL.OUTLN_AGRMNT_VLD_TO_DT
    --, SA_UTL.OWN_CUST_ID
    --, SA_UTL.OWN_CUST_NAME

    , SA_UTL.QTY_UOM

    ) SA

    LEFT OUTER JOIN (
            SELECT
                O.MATL_ID
                , O.FACILITY_ID
                , O.FRST_PLN_GOODS_ISS_DT
                , SUM(DD.DELIV_QTY) AS DELIV_LATE_QTY

            FROM NA_BI_VWS.ORDER_DETAIL O

                INNER JOIN GDYR_BI_VWS.GDYR_CAL RDD_CAL
                    ON RDD_CAL.DAY_DATE = O.FRST_PLN_GOODS_ISS_DT

                INNER JOIN NA_VWS.DELIV_DTL DD
                    ON DD.ORDER_FISCAL_YR = O.ORDER_FISCAL_YR
                    AND DD.ORDER_ID = O.ORDER_ID
                    AND DD.ORDER_LINE_NBR = O.ORDER_LINE_NBR
                    AND DD.EXP_DT = O.EXP_DT
                    AND DD.SD_DOC_CTGY_CD = O.ORDER_CAT_ID
                    AND DD.DELIV_CAT_ID = 'J'

                INNER JOIN GDYR_BI_VWS.GDYR_CAL PGMV_CAL
                    ON PGMV_CAL.DAY_DATE = DD.PLN_GOODS_MVT_DT

                LEFT OUTER JOIN GDYR_BI_VWS.GDYR_CAL AGID_CAL
                    ON AGID_CAL.DAY_DATE = DD.ACTL_GOODS_ISS_DT

            WHERE
                O.EXP_DT = CAST('5555-12-31' AS DATE)
                AND O.ORDER_CAT_ID = 'C'
                AND O.ORDER_TYPE_ID <> 'ZTA'
                AND O.PO_TYPE_ID <> 'RO'
                AND O.ORDER_DT BETWEEN CAST('2015-02-01' AS DATE) AND CAST('2015-02-28' AS DATE)
                AND (
                    (DD.ACTL_GOODS_ISS_DT IS NOT NULL AND AGID_CAL.MONTH_DT > RDD_CAL.MONTH_DT)
                    OR (DD.ACTL_GOODS_ISS_DT IS NULL AND PGMV_CAL.MONTH_DT > RDD_CAL.MONTH_DT)
                    )

            GROUP BY
                O.MATL_ID
                , O.FACILITY_ID
                , O.FRST_PLN_GOODS_ISS_DT
            ) ORD
        ON ORD.MATL_ID = SA.MATL_ID
        AND ORD.FACILITY_ID = SA.FACILITY_ID
        AND ORD.FRST_PLN_GOODS_ISS_DT BETWEEN SA.OUTLN_AGRMNT_VLD_FRM_DT AND SA.OUTLN_AGRMNT_VLD_TO_DT

GROUP BY
    SA.MATL_ID
    , SA.DESCR
    , SA.PBU_NBR
    , SA.PBU_NAME
    , SA.MKT_AREA_NBR
    , SA.MKT_AREA_NAME
    , SA.FACILITY_ID
    , SA.FACILITY_NAME
    , SA.OUTLN_AGRMNT_VLD_FRM_DT
    , SA.OUTLN_AGRMNT_VLD_TO_DT

    , SA.QTY_UOM
    , SA.SA_TARGET_QTY
    , SA.SA_SL_TARGET_QTY
    , SA.SA_SL_CNFRM_QTY
    , SA.SA_SL_CNFRM_IN_PD_QTY
    , SA.SLS_ORDER_QTY
    , SA.SA_UTILIZATION_QTY
