SELECT
    Q.SA_FISCAL_YR
    , Q.SA_DOC_ID
    , Q.SA_DOC_ITM_ID
    , Q.SA_DOC_CTGY_CD
    , Q.ORDER_CAT_ID
    , Q.ORDER_TYPE_ID
    , DD.DELIV_CAT_ID
    , DD.DELIV_TYPE_ID

    , Q.QTY_UNIT_MEAS_ID
    , SUM(Q.ORDER_QTY) AS ORDER_QTY
    , SUM(DD.DELIV_QTY) AS DELIV_QTY

FROM (

    SELECT
        DF.PREV_FISCAL_YR AS SA_FISCAL_YR
        , DF.PREV_SD_DOC_ID AS SA_DOC_ID
        , DF.PREV_SD_DOC_ITM_ID AS SA_DOC_ITM_ID
        , DF.PREV_SD_DOC_CTGY_CD AS SA_DOC_CTGY_CD

        , DF.NEXT_FISCAL_YR AS ORDER_FISCAL_YR
        , DF.NEXT_SD_DOC_ID AS ORDER_ID
        , DF.NEXT_SD_DOC_ITM_ID AS ORDER_LINE_NBR
        , DF.NEXT_SD_DOC_CTGY_CD AS ORDER_CAT_ID
        , OD.ORDER_TYPE_ID

        , OD.QTY_UNIT_MEAS_ID
        , MAX(OD.ORDER_QTY) AS ORDER_QTY

    FROM GDYR_VWS.SD_DOC_FLOW DF

        INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
            ON OD.ORDER_FISCAL_YR = DF.NEXT_FISCAL_YR
            AND OD.ORDER_ID = DF.NEXT_SD_DOC_ID
            AND OD.ORDER_LINE_NBR = DF.NEXT_SD_DOC_ITM_ID
            AND OD.ORDER_CAT_ID = DF.NEXT_SD_DOC_CTGY_cD
            AND OD.EXP_DT = DF.EXP_DT

    WHERE
        DF.EXP_DT = CAST('5555-12-31' AS DATE)
        AND DF.ORIG_SYS_ID = 2
        AND DF.PREV_SD_DOC_CTGY_CD = 'E'
        AND DF.NEXT_SD_DOC_CTGY_CD = 'C'
        AND DF.CRT_DT BETWEEN DATE '2015-01-01' AND DATE '2015-01-31'

    GROUP BY
        DF.PREV_FISCAL_YR
        , DF.PREV_SD_DOC_ID
        , DF.PREV_SD_DOC_ITM_ID
        , DF.PREV_SD_DOC_CTGY_CD

        , DF.NEXT_FISCAL_YR
        , DF.NEXT_SD_DOC_ID
        , DF.NEXT_SD_DOC_ITM_ID
        , DF.NEXT_SD_DOC_CTGY_CD
        , OD.ORDER_TYPE_ID

        , OD.QTY_UNIT_MEAS_ID

    ) Q

    INNER JOIN NA_VWS.DELIV_DTL DD
        ON DD.ORDER_FISCAL_YR = Q.ORDER_FISCAL_YR
        AND DD.ORDER_ID = Q.ORDER_ID
        AND DD.ORDER_LINE_NBR = Q.ORDER_LINE_NBR
        AND DD.EXP_DT = CAST('5555-12-31' AS DATE)

GROUP BY
    Q.SA_FISCAL_YR
    , Q.SA_DOC_ID
    , Q.SA_DOC_ITM_ID
    , Q.SA_DOC_CTGY_CD
    , Q.ORDER_CAT_ID
    , Q.ORDER_TYPE_ID
    , DD.DELIV_CAT_ID
    , DD.DELIV_TYPE_ID

    , Q.QTY_UNIT_MEAS_ID

