SELECT
    SAQ.OUTLN_AGRMNT_VLD_FRM_DT
    , SAQ.OUTLN_AGRMNT_VLD_TO_DT
    , SAQ.MATL_ID
    , SAQ.DESCR
    , SAQ.MATL_HIER_ID
    , SAQ.PBU_NBR
    , SAQ.PBU_NAME
    , SAQ.MKT_AREA_NBR
    , SAQ.MKT_AREA_NAME
    , SAQ.FACILITY_ID
    , SAQ.FACILITY_NAME

    , SAQ.QTY_UOM
    , SAQ.SA_BOM_TARGET_QTY
    , SAQ.SA_EOM_TARGET_QTY
    , CASE
        WHEN SAQ.SA_EOM_TARGET_QTY < SAQ.SA_BOM_TARGET_QTY
            THEN 'Decrease'
        WHEN SAQ.SA_EOM_TARGET_QTY > SAQ.SA_BOM_TARGET_QTY
            THEN 'Increase'
        ELSE 'No Change'
        END AS ITM_TARGET_QTY_CHG_DESC

    , SAQ.SA_BOM_SL_TARGET_QTY
    , SAQ.SA_EOM_SL_TARGET_QTY
    , CASE
        WHEN SAQ.SA_EOM_SL_TARGET_QTY < SAQ.SA_BOM_SL_TARGET_QTY
            THEN 'Decrease'
        WHEN SAQ.SA_EOM_SL_TARGET_QTY > SAQ.SA_BOM_SL_TARGET_QTY
            THEN 'Increase'
        ELSE 'No Change'
        END AS SL_TARGET_QTY_CHG_DESC

    , SAQ.SA_BOM_SL_CNFRM_QTY
    , CASE
        WHEN SAQ.SA_BOM_SL_CNFRM_QTY < SAQ.SA_BOM_SL_TARGET_QTY
            THEN 'Underconfirmed'
        WHEN SAQ.SA_BOM_SL_CNFRM_QTY > SAQ.SA_BOM_SL_TARGET_QTY
            THEN 'Overconfirmed'
        ELSE 'Fully Confirmed'
        END AS SL_BOM_TARGET_QTY_CHG_DESC
    , SAQ.SA_EOM_SL_CNFRM_QTY
    , CASE
        WHEN SAQ.SA_EOM_SL_CNFRM_QTY < SAQ.SA_EOM_SL_TARGET_QTY
            THEN 'Underconfirmed'
        WHEN SAQ.SA_EOM_SL_CNFRM_QTY > SAQ.SA_EOM_SL_TARGET_QTY
            THEN 'Overconfirmed'
        ELSE 'Fully Confirmed'
        END AS SL_EOM_TARGET_QTY_CHG_DESC

    , SAQ.SA_BOM_SL_CNFRM_IN_PD_QTY
    , SAQ.SA_EOM_SL_CNFRM_IN_PD_QTY

    , SAQ.SA_SLS_ORDER_QTY
    , SAQ.SA_SLS_ORDER_DELIV_QTY

    , CASE
        WHEN SAQ.SA_EOM_SL_CNFRM_IN_PD_QTY - SAQ.SA_SLS_ORDER_DELIV_QTY > 0
            THEN SAQ.SA_EOM_SL_CNFRM_IN_PD_QTY - SAQ.SA_SLS_ORDER_DELIV_QTY
        ELSE 0
        END AS SA_EOM_UNUTILIZED_CNFRM_QTY
    , CASE
        WHEN SA_EOM_UNUTILIZED_CNFRM_QTY = 0
            THEN 'Fully Utilized Confirmed Units'
        ELSE 'Some Unutilized Units'
        END AS UTILIZATION_DESC

    , ZEROIFNULL(SUM(DLV_LT.DELIV_LATE_QTY)) AS NON_SA_DELIV_LATE_QTY
    , CASE
        WHEN NON_SA_DELIV_LATE_QTY > 0 AND SA_EOM_UNUTILIZED_CNFRM_QTY - NON_SA_DELIV_LATE_QTY >= 0
            THEN NON_SA_DELIV_LATE_QTY
        WHEN SA_EOM_UNUTILIZED_CNFRM_QTY - NON_SA_DELIV_LATE_QTY < 0
            THEN SA_EOM_UNUTILIZED_CNFRM_QTY
        ELSE 0
        END AS SA_POTENTIAL_DELAY_QTY

FROM (

SELECT
    SA.OUTLN_AGRMNT_VLD_FRM_DT
    , SA.OUTLN_AGRMNT_VLD_TO_DT
    , SA.MATL_ID
    , SA.DESCR
    , SA.MATL_HIER_ID
    , SA.PBU_NBR
    , SA.PBU_NAME
    , SA.MKT_AREA_NBR
    , SA.MKT_AREA_NAME
    , SA.FACILITY_ID
    , SA.FACILITY_NAME

    , SA.QTY_UOM
    , SUM(SA.SA_BOM_TARGET_QTY) AS SA_BOM_TARGET_QTY
    , SUM(SA.SA_EOM_TARGET_QTY) AS SA_EOM_TARGET_QTY

    , SUM(SA.SA_BOM_SL_TARGET_QTY) AS SA_BOM_SL_TARGET_QTY
    , SUM(SA.SA_EOM_SL_TARGET_QTY) AS SA_EOM_SL_TARGET_QTY

    , SUM(SA.SA_BOM_SL_CNFRM_QTY) AS SA_BOM_SL_CNFRM_QTY
    , SUM(SA.SA_BOM_SL_CNFRM_QTY) AS SA_EOM_SL_CNFRM_QTY

    , SUM(SA.SA_BOM_SL_CNFRM_IN_PD_QTY) AS SA_BOM_SL_CNFRM_IN_PD_QTY
    , SUM(SA.SA_EOM_SL_CNFRM_IN_PD_QTY) AS SA_EOM_SL_CNFRM_IN_PD_QTY

    , SUM(SA.SLS_ORDER_QTY) AS SA_SLS_ORDER_QTY
    , SUM(SA.SLS_ORDER_DELIV_QTY) AS SA_SLS_ORDER_DELIV_QTY

FROM (

SELECT
    BOM.FISCAL_YR
    , BOM.SLS_DOC_ID
    , BOM.SLS_DOC_ITM_ID

    , BOM.DOC_DT
    , BOM.OUTLN_AGRMNT_VLD_FRM_DT
    , BOM.OUTLN_AGRMNT_VLD_TO_DT

    , BOM.CUST_PRCH_ORD_ID
    , BOM.CUST_PRCH_ORD_TYP_CD

    , BOM.SD_DOC_CTGY_CD
    , BOM.SLS_DOC_TYP_CD
    , BOM.SLS_DOC_ITM_CTGY_CD

    , BOM.SOLD_TO_CUST_ID
    , BOM.SHIP_TO_CUST_ID
    , BOM.OWN_CUST_ID
    , BOM.OWN_CUST_NAME

    , BOM.MATL_ID
    , BOM.DESCR
    , BOM.MATL_HIER_ID
    , BOM.PBU_NBR
    , BOM.PBU_NAME
    , BOM.MKT_AREA_NBR
    , BOM.MKT_AREA_NAME

    , BOM.FACILITY_ID
    , BOM.FACILITY_NAME

    , BOM.BOM_REJ_REAS_ID
    , SDI_EOM.REJ_REAS_ID AS EOM_REJ_REAS_ID

    , BOM.QTY_UOM
    , BOM.SA_BOM_TARGET_QTY
    , SDI_EOM.SLS_UNIT_CUM_ORD_QTY AS SA_EOM_TARGET_QTY

    , BOM.SA_BOM_SL_TARGET_QTY
    , SUM(SL.SLS_UNIT_ORD_QTY) AS SA_EOM_SL_TARGET_QTY

    , CASE WHEN BOM.BOM_REJ_REAS_ID IS NULL THEN BOM.SA_BOM_SL_CNFRM_QTY ELSE 0 END AS SA_BOM_SL_CNFRM_QTY
    , SUM(CASE WHEN SDI_EOM.REJ_REAS_ID IS NULL THEN SL.SLS_UNIT_CNFRM_QTY ELSE 0 END) AS SA_EOM_SL_CNFRM_QTY

    , CASE WHEN BOM.BOM_REJ_REAS_ID IS NULL THEN BOM.SA_BOM_SL_CNFRM_IN_PD_QTY ELSE 0 END AS SA_BOM_SL_CNFRM_IN_PD_QTY
    , SUM(CASE WHEN SDI_EOM.REJ_REAS_ID IS NULL SL.MATL_AVAIL_DT BETWEEN BOM.OUTLN_AGRMNT_VLD_FRM_DT AND BOM.OUTLN_AGRMNT_VLD_TO_DT THEN SL.SLS_UNIT_CNFRM_QTY ELSE 0 END) AS SA_EOM_SL_CNFRM_IN_PD_QTY

    , ZEROIFNULL(UTL.ORDER_QTY) AS SLS_ORDER_QTY
    , ZEROIFNULL(UTL.DELIV_QTY) AS SLS_ORDER_DELIV_QTY

FROM (

SELECT
    SDI_BOM.FISCAL_YR
    , SDI_BOM.SLS_DOC_ID
    , SDI_BOM.SLS_DOC_ITM_ID
    , SD.DOC_DT

    , CAL.MONTH_DT AS OUTLN_AGRMNT_VLD_FRM_DT
    , ADD_MONTHS(CAL.MONTH_DT, 1) - CAST(1 AS INTERVAL DAY(4)) AS OUTLN_AGRMNT_VLD_TO_DT

    , SD.CUST_PRCH_ORD_ID
    , SD.CUST_PRCH_ORD_TYP_CD

    , SD.SD_DOC_CTGY_CD
    , SD.SLS_DOC_TYP_CD
    , SDI_BOM.SLS_DOC_ITM_CTGY_CD

    , SD.SOLD_TO_CUST_ID
    , SD.SHIP_TO_CUST_ID
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , SDI_BOM.MATL_ID
    , M.DESCR
    , SDI_BOM.MATL_HIER_ID
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME

    , SDI_BOM.FACILITY_ID
    , F.FACILITY_NAME

    , SDI_BOM.REJ_REAS_ID AS BOM_REJ_REAS_ID

    , SDI_BOM.SLS_UOM_CD AS QTY_UOM
    , SDI_BOM.SLS_UNIT_CUM_ORD_QTY AS SA_BOM_TARGET_QTY
    , SUM(SL.SLS_UNIT_ORD_QTY) AS SA_BOM_SL_TARGET_QTY
    , SUM(SL.SLS_UNIT_CNFRM_QTY) AS SA_BOM_SL_CNFRM_QTY
    , SUM(CASE WHEN SL.MATL_AVAIL_DT BETWEEN CAL.MONTH_DT AND ADD_MONTHS(CAL.MONTH_DT, 1) - CAST(1 AS INTERVAL DAY(4)) THEN SL.SLS_UNIT_CNFRM_QTY ELSE 0 END) AS SA_BOM_SL_CNFRM_IN_PD_QTY

FROM NA_BI_VWS.NAT_SLS_DOC SD

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE BETWEEN SD.OUTLN_AGRMNT_VLD_FRM_DT AND SD.OUTLN_AGRMNT_VLD_TO_DT

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = SD.SHIP_TO_CUST_ID

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM SDI_BOM
        ON SD.FISCAL_YR = SDI_BOM.FISCAL_YR
        AND SD.SLS_DOC_ID = SDI_BOM.SLS_DOC_ID
        AND SDI_BOM.SLS_DOC_ITM_CTGY_CD = 'LZMA'
        AND SD.OUTLN_AGRMNT_VLD_FRM_DT - CAST(1 AS INTERVAL DAY(4)) BETWEEN SDI_BOM.EFF_DT AND SDI_BOM.EXP_DT
        AND SDI_BOM.REJ_REAS_ID IS NULL
        AND SDI_BOM.SRC_CRT_TS BETWEEN ADD_MONTHS(CURRENT_TIMESTAMP, -6) AND ADD_MONTHS(CURRENT_TIMESTAMP, 3)

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = SDI_BOM.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = SDI_BOM.MATL_ID
        AND M.PBU_NBR = '01'

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_SCHD_LN SL
        ON SL.FISCAL_YR = SDI_BOM.FISCAL_YR
        AND SL.SLS_DOC_ID = SDI_BOM.SLS_DOC_ID
        AND SL.SLS_DOC_ITM_ID = SDI_BOM.SLS_DOC_ITM_ID
        AND SD.OUTLN_AGRMNT_VLD_FRM_DT - CAST(1 AS INTERVAL DAY(4)) BETWEEN SL.EFF_DT AND SL.EXP_DT
        --AND SL.SCHD_LN_CTGY_CD = 'L3'
        AND SL.MATL_AVAIL_DT BETWEEN ADD_MONTHS(CURRENT_DATE, -6) AND ADD_MONTHS(CURRENT_DATE, 3)

WHERE
    SD.EXP_DT = CAST('5555-12-31' AS DATE)
    AND CAL.DAY_DATE = CAL.MONTH_DT
    AND CAL.MONTH_DT = CAST('2015-02-01' AS DATE)

    AND SD.SD_DOC_CTGY_CD = 'E'
    AND SD.SLS_DOC_TYP_CD = 'ZLZ'
    AND SD.CO_CD IN ('N101', 'N102', 'N266')

GROUP BY
    SDI_BOM.FISCAL_YR
    , SDI_BOM.SLS_DOC_ID
    , SDI_BOM.SLS_DOC_ITM_ID
    , SD.DOC_DT
    , CAL.MONTH_DT
    , (ADD_MONTHS(CAL.MONTH_DT, 1) - CAST(1 AS INTERVAL DAY(4)))
    , SD.CUST_PRCH_ORD_ID
    , SD.CUST_PRCH_ORD_TYP_CD
    , SD.SD_DOC_CTGY_CD
    , SD.SLS_DOC_TYP_CD
    , SDI_BOM.SLS_DOC_ITM_CTGY_CD
    , SD.SOLD_TO_CUST_ID
    , SD.SHIP_TO_CUST_ID
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , SDI_BOM.MATL_ID
    , M.DESCR
    , SDI_BOM.MATL_HIER_ID
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , SDI_BOM.FACILITY_ID
    , F.FACILITY_NAME
    , SDI_BOM.REJ_REAS_ID
    , SDI_BOM.SLS_UOM_CD
    , SDI_BOM.SLS_UNIT_CUM_ORD_QTY

    ) BOM

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM SDI_EOM
        ON SDI_EOM.FISCAL_YR = BOM.FISCAL_YR
        AND SDI_EOM.SLS_DOC_ID = BOM.SLS_DOC_ID
        AND SDI_EOM.SLS_DOC_ITM_ID = BOM.SLS_DOC_ITM_ID
        AND BOM.OUTLN_AGRMNT_VLD_TO_DT - CAST(1 AS INTERVAL DAY(4)) BETWEEN SDI_EOM.EFF_DT AND SDI_EOM.EXP_DT
        AND SDI_EOM.SLS_DOC_ITM_CTGY_CD = 'LZMA'
        AND SDI_EOM.SRC_CRT_TS BETWEEN ADD_MONTHS(CURRENT_TIMESTAMP, -6) AND ADD_MONTHS(CURRENT_TIMESTAMP, 3)

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_SCHD_LN SL
        ON SL.FISCAL_YR = BOM.FISCAL_YR
        AND SL.SLS_DOC_ID = BOM.SLS_DOC_ID
        AND SL.SLS_DOC_ITM_ID = BOM.SLS_DOC_ITM_ID
        AND BOM.OUTLN_AGRMNT_VLD_TO_DT - CAST(1 AS INTERVAL DAY(4)) BETWEEN SL.EFF_DT AND SL.EXP_DT
        --AND SL.SCHD_LN_CTGY_CD = 'L3'
        AND SL.MATL_AVAIL_DT BETWEEN ADD_MONTHS(CURRENT_DATE, -6) AND ADD_MONTHS(CURRENT_DATE, 3)

    LEFT OUTER JOIN (
            SELECT
                SA.SA_FISCAL_YR
                , SA.SA_DOC_ID
                , SA.SA_DOC_ITM_ID
                , SA.SA_DOC_CTGY_CD
                , SA.QTY_UNIT_MEAS_ID
                , SUM(SA.ORDER_QTY) AS ORDER_QTY
                , SUM(SA.DELIV_QTY) AS DELIV_QTY
            FROM (
                SELECT
                    SO.SA_FISCAL_YR
                    , SO.SA_DOC_ID
                    , SO.SA_DOC_ITM_ID
                    , SO.SA_DOC_CTGY_CD
                    , SO.ORDER_FISCAL_YR
                    , SO.ORDER_ID
                    , SO.ORDER_LINE_NBR
                    , SO.QTY_UNIT_MEAS_ID
                    , SO.ORDER_QTY
                    , ZEROIFNULL(SUM(DD.DELIV_QTY)) AS DELIV_QTY
                FROM (
                    SELECT
                        DF.PREV_FISCAL_YR AS SA_FISCAL_YR
                        , DF.PREV_SD_DOC_ID AS SA_DOC_ID
                        , DF.PREV_SD_DOC_ITM_ID AS SA_DOC_ITM_ID
                        , DF.PREV_SD_DOC_CTGY_CD AS SA_DOC_CTGY_CD
                        , DF.NEXT_FISCAL_YR AS ORDER_FISCAL_YR
                        , DF.NEXT_SD_DOC_ID AS ORDER_ID
                        , DF.NEXT_SD_DOC_ITM_ID AS ORDER_LINE_NBR
                        , DF.NEXT_SD_DOC_CTGY_CD AS ORDER_CAT_ID
                        , OD.QTY_UNIT_MEAS_ID
                        , MAX(OD.ORDER_QTY) AS ORDER_QTY
                    FROM GDYR_VWS.SD_DOC_FLOW DF
                        INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
                            ON OD.ORDER_FISCAL_YR = DF.NEXT_FISCAL_YR
                            AND OD.ORDER_ID = DF.NEXT_SD_DOC_ID
                            AND OD.ORDER_LINE_NBR = DF.NEXT_SD_DOC_ITM_ID
                            AND OD.ORDER_CAT_ID = DF.NEXT_SD_DOC_CTGY_cD
                            AND OD.EXP_DT = DF.EXP_DT
                    WHERE
                        DF.EXP_DT = CAST('5555-12-31' AS DATE)
                        AND DF.ORIG_SYS_ID = 2
                        AND DF.PREV_SD_DOC_CTGY_CD = 'E'
                        AND DF.NEXT_SD_DOC_CTGY_CD = 'C'
                        AND DF.CRT_DT BETWEEN DATE '2015-02-01' AND DATE '2015-02-28'
                    GROUP BY
                        DF.PREV_FISCAL_YR
                        , DF.PREV_SD_DOC_ID
                        , DF.PREV_SD_DOC_ITM_ID
                        , DF.PREV_SD_DOC_CTGY_CD
                        , DF.NEXT_FISCAL_YR
                        , DF.NEXT_SD_DOC_ID
                        , DF.NEXT_SD_DOC_ITM_ID
                        , DF.NEXT_SD_DOC_CTGY_CD
                        , OD.QTY_UNIT_MEAS_ID
                    ) SO
                    LEFT OUTER JOIN NA_VWS.DELIV_DTL DD
                        ON DD.ORDER_FISCAL_YR = SO.ORDER_FISCAL_YR
                        AND DD.ORDER_ID = SO.ORDER_ID
                        AND DD.ORDER_LINE_NBR = SO.ORDER_LINE_NBR
                        AND DD.EXP_DT = CAST('5555-12-31' AS DATE)
                        AND DD.DELIV_CAT_ID = 'J'
                        AND DD.DELIV_NOTE_CREA_DT BETWEEN DATE '2015-02-01' AND DATE '2015-02-28'
                GROUP BY
                    SO.SA_FISCAL_YR
                    , SO.SA_DOC_ID
                    , SO.SA_DOC_ITM_ID
                    , SO.SA_DOC_CTGY_CD
                    , SO.ORDER_FISCAL_YR
                    , SO.ORDER_ID
                    , SO.ORDER_LINE_NBR
                    , SO.QTY_UNIT_MEAS_ID
                    , SO.ORDER_QTY
                    , SO.QTY_UNIT_MEAS_ID
                ) SA
            GROUP BY
                SA.SA_FISCAL_YR
                , SA.SA_DOC_ID
                , SA.SA_DOC_ITM_ID
                , SA.SA_DOC_CTGY_CD
                , SA.QTY_UNIT_MEAS_ID
            ) UTL
        ON UTL.SA_FISCAL_YR = BOM.FISCAL_YR
        AND UTL.SA_DOC_ID = BOM.SLS_DOC_ID
        AND UTL.SA_DOC_ITM_ID = BOM.SLS_DOC_ITM_ID
        AND UTL.SA_DOC_CTGY_CD = BOM.SD_DOC_CTGY_CD

GROUP BY
    BOM.FISCAL_YR
    , BOM.SLS_DOC_ID
    , BOM.SLS_DOC_ITM_ID
    , BOM.DOC_DT
    , BOM.OUTLN_AGRMNT_VLD_FRM_DT
    , BOM.OUTLN_AGRMNT_VLD_TO_DT
    , BOM.CUST_PRCH_ORD_ID
    , BOM.CUST_PRCH_ORD_TYP_CD
    , BOM.SD_DOC_CTGY_CD
    , BOM.SLS_DOC_TYP_CD
    , BOM.SLS_DOC_ITM_CTGY_CD
    , BOM.SOLD_TO_CUST_ID
    , BOM.SHIP_TO_CUST_ID
    , BOM.OWN_CUST_ID
    , BOM.OWN_CUST_NAME
    , BOM.MATL_ID
    , BOM.DESCR
    , BOM.MATL_HIER_ID
    , BOM.PBU_NBR
    , BOM.PBU_NAME
    , BOM.MKT_AREA_NBR
    , BOM.MKT_AREA_NAME
    , BOM.FACILITY_ID
    , BOM.FACILITY_NAME
    , BOM.BOM_REJ_REAS_ID
    , SDI_EOM.REJ_REAS_ID
    , BOM.QTY_UOM
    , BOM.SA_BOM_TARGET_QTY
    , BOM.SA_BOM_SL_TARGET_QTY
    , BOM.SA_BOM_SL_CNFRM_QTY
    , BOM.SA_BOM_SL_CNFRM_IN_PD_QTY
    , SDI_EOM.SLS_UNIT_CUM_ORD_QTY
    , ZEROIFNULL(UTL.ORDER_QTY)
    , ZEROIFNULL(UTL.DELIV_QTY)

    ) SA

GROUP BY
    SA.OUTLN_AGRMNT_VLD_FRM_DT
    , SA.OUTLN_AGRMNT_VLD_TO_DT
    , SA.MATL_ID
    , SA.DESCR
    , SA.MATL_HIER_ID
    , SA.PBU_NBR
    , SA.PBU_NAME
    , SA.MKT_AREA_NBR
    , SA.MKT_AREA_NAME
    , SA.FACILITY_ID
    , SA.FACILITY_NAME
    , SA.BOM_REJ_REAS_ID
    , SA.EOM_REJ_REAS_ID
    , SA.QTY_UOM

    ) SAQ

    LEFT OUTER JOIN (
            SELECT
                O.MATL_ID
                , O.FACILITY_ID
                , O.FRST_PLN_GOODS_ISS_DT
                , SUM(DD.DELIV_QTY) AS DELIV_LATE_QTY
            FROM NA_BI_VWS.ORDER_DETAIL O
                INNER JOIN GDYR_BI_VWS.GDYR_CAL RDD_CAL
                    ON RDD_CAL.DAY_DATE = O.FRST_PLN_GOODS_ISS_DT
                INNER JOIN NA_VWS.DELIV_DTL DD
                    ON DD.ORDER_FISCAL_YR = O.ORDER_FISCAL_YR
                    AND DD.ORDER_ID = O.ORDER_ID
                    AND DD.ORDER_LINE_NBR = O.ORDER_LINE_NBR
                    AND DD.EXP_DT = O.EXP_DT
                    AND DD.SD_DOC_CTGY_CD = O.ORDER_CAT_ID
                    AND DD.DELIV_CAT_ID = 'J'
                INNER JOIN GDYR_BI_VWS.GDYR_CAL PGMV_CAL
                    ON PGMV_CAL.DAY_DATE = DD.PLN_GOODS_MVT_DT
                LEFT OUTER JOIN GDYR_BI_VWS.GDYR_CAL AGID_CAL
                    ON AGID_CAL.DAY_DATE = DD.ACTL_GOODS_ISS_DT
            WHERE
                O.EXP_DT = CAST('5555-12-31' AS DATE)
                AND O.ORDER_CAT_ID = 'C'
                AND O.ORDER_TYPE_ID NOT IN ('ZTA')
                AND O.PO_TYPE_ID <> 'RO'
                AND O.ORDER_DT BETWEEN CAST('2015-02-01' AS DATE) AND CAST('2015-02-28' AS DATE)
                AND (
                    (DD.ACTL_GOODS_ISS_DT IS NOT NULL AND AGID_CAL.MONTH_DT > RDD_CAL.MONTH_DT)
                    OR (DD.ACTL_GOODS_ISS_DT IS NULL AND PGMV_CAL.MONTH_DT > RDD_CAL.MONTH_DT)
                    )
            GROUP BY
                O.MATL_ID
                , O.FACILITY_ID
                , O.FRST_PLN_GOODS_ISS_DT
            ) DLV_LT
        ON DLV_LT.MATL_ID = SAQ.MATL_ID
        AND DLV_LT.FACILITY_ID = SAQ.FACILITY_ID
        AND DLV_LT.FRST_PLN_GOODS_ISS_DT BETWEEN SAQ.OUTLN_AGRMNT_VLD_FRM_DT AND SAQ.OUTLN_AGRMNT_VLD_TO_DT

GROUP BY
    SAQ.OUTLN_AGRMNT_VLD_FRM_DT
    , SAQ.OUTLN_AGRMNT_VLD_TO_DT
    , SAQ.MATL_ID
    , SAQ.DESCR
    , SAQ.MATL_HIER_ID
    , SAQ.PBU_NBR
    , SAQ.PBU_NAME
    , SAQ.MKT_AREA_NBR
    , SAQ.MKT_AREA_NAME
    , SAQ.FACILITY_ID
    , SAQ.FACILITY_NAME
    , SAQ.QTY_UOM
    , SAQ.SA_BOM_TARGET_QTY
    , SAQ.SA_EOM_TARGET_QTY
    , SAQ.SA_BOM_SL_TARGET_QTY
    , SAQ.SA_EOM_SL_TARGET_QTY
    , SAQ.SA_BOM_SL_CNFRM_QTY
    , SAQ.SA_EOM_SL_CNFRM_QTY
    , SAQ.SA_BOM_SL_CNFRM_IN_PD_QTY
    , SAQ.SA_EOM_SL_CNFRM_IN_PD_QTY
    , SAQ.SA_SLS_ORDER_QTY
    , SAQ.SA_SLS_ORDER_DELIV_QTY

ORDER BY
    SAQ.OUTLN_AGRMNT_VLD_FRM_DT
    , SAQ.OUTLN_AGRMNT_VLD_TO_DT
    , SAQ.MATL_ID
    , SAQ.FACILITY_ID
