DYNAMIC EXPLAIN 
SELECT
    BOM.FISCAL_YR
    , BOM.SLS_DOC_ID
    , BOM.SLS_DOC_ITM_ID

    , BOM.END_OF_PRIOR_MONTH_DT
    , BOM.LAST_ORDER_DAY_OF_MONTH
    , BOM.CUST_PRCH_ORD_ID
    , BOM.CUST_PRCH_ORD_TYP_CD
    , BOM.CUST_PRCH_ORD_DT

    , BOM.SOLD_TO_CUST_ID
    , BOM.CUST_NAME
    , BOM.OWN_CUST_ID
    , BOM.OWN_CUST_NAME
    , BOM.HDR_CRT_DT
    , BOM.HDR_CRT_TM
    , BOM.HDR_CRT_USR_ID
    , BOM.HDR_SAP_TRANS_CD
    , BOM.HDR_UPD_DT
    , BOM.ITM_CRT_TS
    , BOM.ITM_UPD_DT

    , BOM.OUTLN_AGRMNT_VLD_FRM_DT
    , BOM.OUTLN_AGRMNT_VLD_TO_DT
    , BOM.SD_DOC_CTGY_CD
    , BOM.TRANS_GRP_CD
    , BOM.SLS_DOC_TYP_CD

    , BOM.CO_CD
    , BOM.SALES_ORG_CD
    , BOM.DISTR_CHAN_CD
    , BOM.DIV_CD

    , BOM.SLS_DOC_ITM_CTGY_CD
    , BOM.ITM_RLVNT_DELIV_IND
    , BOM.ITM_RLVNT_BILL_ICD
    , BOM.REJ_REAS_ID
    , BOM.DELIV_GRP_ID
    , BOM.BILL_BLK_CD
    , BOM.DELIV_PRTY_CD
    , BOM.AVAIL_CHK_GRP_CD

    , BOM.FACILITY_ID
    , BOM.FACILITY_NAME
    , BOM.STOR_LOC_CD
    , BOM.SHIP_RCVE_PT_CD

    , BOM.MATL_ID
    , BOM.MATL_HIER_ID
    , BOM.DESCR
    , BOM.PBU_NBR
    , BOM.PBU_NAME

    , BOM.QTY_UOM_CD
    , BOM.ITM_ORD_QTY AS BOM_ITM_ORD_QTY
    , SDI.SLS_UNIT_CUM_ORD_QTY AS EOM_ITM_ORD_QTY

    , BOM.ITM_REQ_DELIV_QTY AS BOM_ITM_REQ_DELIV_QTY
    , SDI.SLS_UNIT_CUM_REQ_DELIV_QTY AS EOM_ITM_REQL_DELIV_QTY
    
    , BOM.ITM_REQ_DELIV_PCT AS BOM_ITM_REQ_DELIV_PCT
    , 1 - (SDI.SLS_UNIT_CUM_REQ_DELIV_QTY / SDI.SLS_UNIT_CUM_ORD_QTY) AS EOM_ITM_REQ_DELIV_PCT

    , BOM.ITM_CNFRM_QTY AS BOM_ITM_CNFRM_QTY
    , SDI.SLS_UNIT_CUM_CNFRM_QTY AS EOM_ITM_CNFRM_QTY

    , BOM.ITM_CNFRM_PCT AS BOM_ITM_CNFRM_PCT
    , SDI.SLS_UNIT_CUM_CNFRM_QTY / SDI.SLS_UNIT_CUM_ORD_QTY AS EOM_ITM_CNFRM_PCT

    , BOM.SL_CNFRM_QTY AS BOM_SL_CNFRM_QTY
    , SUM(SL.SLS_UNIT_CNFRM_QTY) AS EOM_SL_CNFRM_QTY
    
    , BOM.SL_TOT_CNFRM_PCT AS BOM_SL_TOT_CNFRM_PCT
    , SL_CNFRM_QTY / SDI.SLS_UNIT_CUM_ORD_QTY AS EOM_SL_TOT_CNFRM_PCT
    
    , BOM.SL_CNFRM_QTY_IN_VLDTY_PD AS BOM_SL_CNFRM_QTY_IN_VLDTY_PD
    , SUM(CASE WHEN SL.MATL_AVAIL_DT <= BOM.OUTLN_AGRMNT_VLD_TO_DT THEN SL.SLS_UNIT_CNFRM_QTY ELSE 0 END) AS EOM_SL_CNFRM_QTY_IN_VLDTY_PD
    
    , BOM.SL_CNFRM_IN_VLDTY_PD_PCT AS BOM_SL_CNFRM_IN_VLDTY_PD_PCT
    , SL_CNFRM_QTY_IN_VLDTY_PD / SDI.SLS_UNIT_CUM_ORD_QTY AS EOM_SL_CNFRM_IN_VLDTY_PD_PCT

FROM (

    SELECT
        SL.FISCAL_YR
        , SL.SLS_DOC_ID
        , SL.SLS_DOC_ITM_ID
        --, SL.SCHD_LN_ID

        , CAL.MONTH_DT - CAST(1 AS INTERVAL DAY(4)) AS END_OF_PRIOR_MONTH_DT
        , CAL.MONTH_DT AS MEAS_BEGIN_MONTH_DT
        , ADD_MONTHS(CAL.MONTH_DT, 1) - CAST(1 AS INTERVAL DAY(4)) AS MEAS_END_MONTH_DT
        , ADD_MONTHS(CAL.MONTH_DT, 1) - CAST(2 AS INTERVAL DAY(4)) AS LAST_ORDER_DAY_OF_MONTH

        , SD.CUST_PRCH_ORD_ID
        , SD.CUST_PRCH_ORD_TYP_CD
        , SD.CUST_PRCH_ORD_DT

        , SD.SOLD_TO_CUST_ID
        , C.CUST_NAME
        , C.OWN_CUST_ID
        , C.OWN_CUST_NAME

        , SD.SRC_CRT_DT AS HDR_CRT_DT
        , SD.SRC_CRT_TM AS HDR_CRT_TM
        , SD.SRC_CRT_USR_ID AS HDR_CRT_USR_ID
        , SD.SAP_TRANS_CD AS HDR_SAP_TRANS_CD
        , SD.SRC_UPD_DT AS HDR_UPD_DT
        , SDI.SRC_CRT_TS AS ITM_CRT_TS
        , SDI.SRC_UPD_DT AS ITM_UPD_DT

        , SD.OUTLN_AGRMNT_VLD_FRM_DT
        , SD.OUTLN_AGRMNT_VLD_TO_DT

        , SD.SD_DOC_CTGY_CD
        , SD.TRANS_GRP_CD
        , SD.SLS_DOC_TYP_CD

        , SD.CO_CD
        , SD.SALES_ORG_CD
        , SD.DISTR_CHAN_CD
        , SD.DIV_CD

        , SDI.SLS_DOC_ITM_CTGY_CD
        , SDI.ITM_RLVNT_DELIV_IND
        , SDI.ITM_RLVNT_BILL_ICD
        , SDI.REJ_REAS_ID
        , SDI.DELIV_GRP_ID
        , SDI.BILL_BLK_CD
        , SDI.DELIV_PRTY_CD
        , SDI.AVAIL_CHK_GRP_CD

        , SDI.FACILITY_ID
        , F.FACILITY_NAME
        , SDI.STOR_LOC_CD
        , SDI.SHIP_RCVE_PT_CD

        , SDI.MATL_ID
        , SDI.MATL_HIER_ID
        , M.DESCR
        , M.PBU_NBR
        , M.PBU_NAME

        , SDI.SLS_UOM_CD AS QTY_UOM_CD
        , SDI.SLS_UNIT_CUM_ORD_QTY AS ITM_ORD_QTY
        , SDI.SLS_UNIT_CUM_CNFRM_QTY AS ITM_CNFRM_QTY
        , SDI.SLS_UNIT_CUM_CNFRM_QTY / SDI.SLS_UNIT_CUM_ORD_QTY AS ITM_CNFRM_PCT
        , SDI.SLS_UNIT_CUM_REQ_DELIV_QTY AS ITM_REQ_DELIV_QTY
        , 1 - (SDI.SLS_UNIT_CUM_REQ_DELIV_QTY / SDI.SLS_UNIT_CUM_ORD_QTY) AS ITM_REQ_DELIV_PCT

        , SUM(SL.SLS_UNIT_CNFRM_QTY) AS SL_CNFRM_QTY
        , SL_CNFRM_QTY / SDI.SLS_UNIT_CUM_ORD_QTY AS SL_TOT_CNFRM_PCT
        , SUM(CASE WHEN SL.MATL_AVAIL_DT <= SD.OUTLN_AGRMNT_VLD_TO_DT THEN SL.SLS_UNIT_CNFRM_QTY ELSE 0 END) AS SL_CNFRM_QTY_IN_VLDTY_PD
        , SL_CNFRM_QTY_IN_VLDTY_PD / SDI.SLS_UNIT_CUM_ORD_QTY AS SL_CNFRM_IN_VLDTY_PD_PCT

    FROM GDYR_BI_VWS.GDYR_CAL CAL

        INNER JOIN NA_BI_VWS.NAT_SLS_DOC SD
            ON END_OF_PRIOR_MONTH_DT BETWEEN SD.EFF_DT AND SD.EXP_DT
            AND SD.SD_DOC_CTGY_CD = 'E'
            AND SD.SLS_DOC_TYP_CD = 'ZLZ'

        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
            ON C.SHIP_TO_CUST_ID = SD.SOLD_TO_CUST_ID

        INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM SDI
            ON SDI.FISCAL_YR = SD.FISCAL_YR
            AND SDI.SLS_DOC_ID = SD.SLS_DOC_ID
            AND END_OF_PRIOR_MONTH_DT BETWEEN SDI.EFF_DT AND SDI.EXP_DT
            --AND SDI.SLS_DOC_ITM_CTGY_CD = 'ZLMA'
            AND SDI.SRC_CRT_TS BETWEEN ADD_MONTHS(CURRENT_TIMESTAMP, -6) AND CURRENT_TIMESTAMP

        INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
            ON F.FACILITY_ID = SDI.FACILITY_ID
            AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
            AND F.DISTR_CHAN_CD = '81'

        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
            ON M.MATL_ID = SDI.MATL_ID
            AND M.PBU_NBR = '01'

        INNER JOIN NA_BI_vWS.NAT_SLS_DOC_SCHD_LN SL
            ON SL.FISCAL_YR = SDI.FISCAL_YR
            AND SL.SLS_DOC_ID = SDI.SLS_DOC_ID
            AND SL.SLS_DOC_ITM_ID = SDI.SLS_DOC_ITM_ID
            AND END_OF_PRIOR_MONTH_DT BETWEEN SL.EFF_DT AND SL.EXP_DT
            --AND SL.SCHD_LN_CTGY_CD = 'L3'
            AND SL.SCHD_LN_DELIV_DT BETWEEN ADD_MONTHS(CURRENT_DATE, -6) AND ADD_MONTHS(CURRENT_DATE, 4)

    WHERE
        CAL.MONTH_DT = DATE '2015-01-01'
        AND CAL.DAY_DATE = CAL.MONTH_DT
        AND (
            (SD.OUTLN_AGRMNT_VLD_FRM_DT BETWEEN MEAS_BEGIN_MONTH_DT AND MEAS_END_MONTH_DT AND SD.OUTLN_AGRMNT_VLD_TO_DT BETWEEN MEAS_BEGIN_MONTH_DT AND MEAS_END_MONTH_DT)
            OR (SL.MATL_AVAIL_DT BETWEEN MEAS_BEGIN_MONTH_DT AND MEAS_END_MONTH_DT AND SDI.REJ_REAS_ID IS NULL)
            )

    GROUP BY
        SL.FISCAL_YR
        , SL.SLS_DOC_ID
        , SL.SLS_DOC_ITM_ID
        --, SL.SCHD_LN_ID

        , END_OF_PRIOR_MONTH_DT
        , MEAS_BEGIN_MONTH_DT
        , MEAS_END_MONTH_DT
        , LAST_ORDER_DAY_OF_MONTH

        , SD.CUST_PRCH_ORD_ID
        , SD.CUST_PRCH_ORD_TYP_CD
        , SD.CUST_PRCH_ORD_DT

        , SD.SOLD_TO_CUST_ID
        , C.CUST_NAME
        , C.OWN_CUST_ID
        , C.OWN_CUST_NAME

        , HDR_CRT_DT
        , HDR_CRT_TM
        , HDR_CRT_USR_ID
        , HDR_SAP_TRANS_CD
        , HDR_UPD_DT
        , ITM_CRT_TS
        , ITM_UPD_DT

        , SD.OUTLN_AGRMNT_VLD_FRM_DT
        , SD.OUTLN_AGRMNT_VLD_TO_DT

        , SD.SD_DOC_CTGY_CD
        , SD.TRANS_GRP_CD
        , SD.SLS_DOC_TYP_CD

        , SD.CO_CD
        , SD.SALES_ORG_CD
        , SD.DISTR_CHAN_CD
        , SD.DIV_CD

        , SDI.SLS_DOC_ITM_CTGY_CD
        , SDI.ITM_RLVNT_DELIV_IND
        , SDI.ITM_RLVNT_BILL_ICD
        , SDI.REJ_REAS_ID
        , SDI.DELIV_GRP_ID
        , SDI.BILL_BLK_CD
        , SDI.DELIV_PRTY_CD
        , SDI.AVAIL_CHK_GRP_CD

        , SDI.FACILITY_ID
        , F.FACILITY_NAME
        , SDI.STOR_LOC_CD
        , SDI.SHIP_RCVE_PT_CD

        , SDI.MATL_ID
        , SDI.MATL_HIER_ID
        , M.DESCR
        , M.PBU_NBR
        , M.PBU_NAME

        , QTY_UOM_CD
        , ITM_ORD_QTY
        , ITM_REQ_DELIV_QTY
        , ITM_CNFRM_QTY
        , ITM_CNFRM_PCT

    ) BOM

        INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM SDI
            ON SDI.FISCAL_YR = BOM.FISCAL_YR
            AND SDI.SLS_DOC_ID = BOM.SLS_DOC_ID
            AND SDI.SLS_DOC_ITM_ID = BOM.SLS_DOC_ITM_ID
            AND BOM.LAST_ORDER_DAY_OF_MONTH BETWEEN SDI.EFF_DT AND SDI.EXP_DT
            --AND SDI.SLS_DOC_ITM_CTGY_CD = 'ZLMA'
            AND SDI.SRC_CRT_TS BETWEEN ADD_MONTHS(CURRENT_TIMESTAMP, -6) AND CURRENT_TIMESTAMP

        INNER JOIN NA_BI_vWS.NAT_SLS_DOC_SCHD_LN SL
            ON SL.FISCAL_YR = BOM.FISCAL_YR
            AND SL.SLS_DOC_ID = BOM.SLS_DOC_ID
            AND SL.SLS_DOC_ITM_ID = BOM.SLS_DOC_ITM_ID
            AND BOM.LAST_ORDER_DAY_OF_MONTH BETWEEN SL.EFF_DT AND SL.EXP_DT
            --AND SL.SCHD_LN_CTGY_CD = 'L3'
            AND SL.SCHD_LN_DELIV_DT BETWEEN ADD_MONTHS(CURRENT_DATE, -6) AND ADD_MONTHS(CURRENT_DATE, 4)

GROUP BY
    BOM.FISCAL_YR
    , BOM.SLS_DOC_ID
    , BOM.SLS_DOC_ITM_ID

    , BOM.END_OF_PRIOR_MONTH_DT
    , BOM.LAST_ORDER_DAY_OF_MONTH
    , BOM.CUST_PRCH_ORD_ID
    , BOM.CUST_PRCH_ORD_TYP_CD
    , BOM.CUST_PRCH_ORD_DT

    , BOM.SOLD_TO_CUST_ID
    , BOM.CUST_NAME
    , BOM.OWN_CUST_ID
    , BOM.OWN_CUST_NAME
    , BOM.HDR_CRT_DT
    , BOM.HDR_CRT_TM
    , BOM.HDR_CRT_USR_ID
    , BOM.HDR_SAP_TRANS_CD
    , BOM.HDR_UPD_DT
    , BOM.ITM_CRT_TS
    , BOM.ITM_UPD_DT

    , BOM.OUTLN_AGRMNT_VLD_FRM_DT
    , BOM.OUTLN_AGRMNT_VLD_TO_DT
    , BOM.SD_DOC_CTGY_CD
    , BOM.TRANS_GRP_CD
    , BOM.SLS_DOC_TYP_CD

    , BOM.CO_CD
    , BOM.SALES_ORG_CD
    , BOM.DISTR_CHAN_CD
    , BOM.DIV_CD

    , BOM.SLS_DOC_ITM_CTGY_CD
    , BOM.ITM_RLVNT_DELIV_IND
    , BOM.ITM_RLVNT_BILL_ICD
    , BOM.REJ_REAS_ID
    , BOM.DELIV_GRP_ID
    , BOM.BILL_BLK_CD
    , BOM.DELIV_PRTY_CD
    , BOM.AVAIL_CHK_GRP_CD

    , BOM.FACILITY_ID
    , BOM.FACILITY_NAME
    , BOM.STOR_LOC_CD
    , BOM.SHIP_RCVE_PT_CD

    , BOM.MATL_ID
    , BOM.MATL_HIER_ID
    , BOM.DESCR
    , BOM.PBU_NBR
    , BOM.PBU_NAME

    , BOM.QTY_UOM_CD
    , BOM_ITM_ORD_QTY
    , EOM_ITM_ORD_QTY

    , BOM_ITM_REQ_DELIV_QTY
    , EOM_ITM_REQL_DELIV_QTY
    
    , BOM_ITM_REQ_DELIV_PCT
    , EOM_ITM_REQ_DELIV_PCT

    , BOM_ITM_CNFRM_QTY
    , EOM_ITM_CNFRM_QTY

    , BOM_ITM_CNFRM_PCT
    , EOM_ITM_CNFRM_PCT

    , BOM_SL_CNFRM_QTY
    --, SUM(SL.SLS_UNIT_CNFRM_QTY) AS EOM_SL_CNFRM_QTY
    
    , BOM_SL_TOT_CNFRM_PCT
    --, SL_CNFRM_QTY / SDI.SLS_UNIT_CUM_ORD_QTY AS EOM_SL_TOT_CNFRM_PCT
    
    , BOM_SL_CNFRM_QTY_IN_VLDTY_PD
    --, SUM(CASE WHEN SL.MATL_AVAIL_DT <= SD.OUTLN_AGRMNT_VLD_TO_DT THEN SL.SLS_UNIT_CNFRM_QTY ELSE 0 END) AS EOM_SL_CNFRM_QTY_IN_VLDTY_PD
    
    , BOM_SL_CNFRM_IN_VLDTY_PD_PCT
    --, SL_CNFRM_QTY_IN_VLDTY_PD / SDI.SLS_UNIT_CUM_ORD_QTY AS EOM_SL_CNFRM_IN_VLDTY_PD_PCT

ORDER BY
    BOM.FISCAL_YR
    , BOM.SLS_DOC_ID
    , BOM.SLS_DOC_ITM_ID

