SELECT
    S.DAY_DATE
    , S.DAY_BEFORE_PD_BEGIN
    , S.DAY_BEFORE_PD_END

    , S.MATL_ID
    , S.DESCR
    , S.MATL_HIER_ID
    , S.PBU_NBR
    , S.PBU_NAME

    , S.FACILITY_ID
    , S.FACILITY_NAME

    , S.SLS_UOM_CD
    , S.SLS_UNIT_CUM_ORD_QTY
    , S.SLS_UNIT_CUM_CNFRM_QTY

    , S.SCHD_LN_CNFRM_QTY
    , S.SCHD_LN_CNFRM_IN_PD_QTY

    , S.SLS_ORDER_QTY
    , S.SLS_ORDER_CNFRM_QTY
    , S.SLS_ORDER_DELIV_QTY

    , S.UNUTILIZED_SA_CNFRM_QTY
    , ZEROIFNULL(DL.GOODS_ISS_LATE_QTY) AS NON_SA_GOODS_ISS_LATE_QTY
    , CASE
        WHEN S.UNUTILIZED_SA_CNFRM_QTY < NON_SA_GOODS_ISS_LATE_QTY
            THEN S.UNUTILIZED_SA_CNFRM_QTY
        ELSE NON_SA_GOODS_ISS_LATE_QTY
        END AS OPPORTUNITY_QTY

FROM (

SELECT
    SAS.DAY_DATE
    , SAS.DAY_BEFORE_PD_BEGIN
    , SAS.DAY_BEFORE_PD_END

    , SAS.MATL_ID
    , SAS.DESCR
    , SAS.MATL_HIER_ID
    , SAS.PBU_NBR
    , SAS.PBU_NAME

    , SAS.FACILITY_ID
    , SAS.FACILITY_NAME

    , SAS.SLS_UOM_CD
    , SUM(SAS.SLS_UNIT_CUM_ORD_QTY) AS SLS_UNIT_CUM_ORD_QTY
    , SUM(SAS.SLS_UNIT_CUM_CNFRM_QTY) AS SLS_UNIT_CUM_CNFRM_QTY

    , SUM(SAS.SCHD_LN_CNFRM_QTY) AS SCHD_LN_CNFRM_QTY
    , SUM(SAS.SCHD_LN_CNFRM_IN_PD_QTY) AS SCHD_LN_CNFRM_IN_PD_QTY

    , SUM(SAS.SLS_ORDER_QTY) AS SLS_ORDER_QTY
    , SUM(SAS.SLS_ORDER_CNFRM_QTY) AS SLS_ORDER_CNFRM_QTY
    , SUM(SAS.SLS_ORDER_DELIV_QTY) AS SLS_ORDER_DELIV_QTY

    , SUM(SAS.UNUTILIZED_SA_CNFRM_QTY) AS UNUTILIZED_SA_CNFRM_QTY

FROM (

SELECT
    SAO.DAY_DATE
    , SAO.FISCAL_YR
    , SAO.SLS_DOC_ID
    , SAO.SLS_DOC_ITM_ID

    , SAO.OUTLN_AGRMNT_VLD_FRM_DT
    , SAO.OUTLN_AGRMNT_VLD_TO_DT

    , SAO.DAY_BEFORE_PD_BEGIN
    , SAO.DAY_BEFORE_PD_END

    , SAO.SD_DOC_CTGY_CD
    , SAO.SLS_DOC_TYP_CD
    , SAO.SLS_DOC_ITM_CTGY_CD

    , SAO.AVAIL_CHK_GRP_CD

    , SAO.SHIP_TO_CUST_ID
    , SAO.SHIP_TO_CUST_NAME
    , SAO.OWN_CUST_ID
    , SAO.OWN_CUST_NAME

    , SAO.MATL_ID
    , SAO.DESCR
    , SAO.MATL_HIER_ID
    , SAO.PBU_NBR
    , SAO.PBU_NAME

    , SAO.FACILITY_ID
    , SAO.FACILITY_NAME

    , SAO.SLS_UOM_CD
    , SAO.SLS_UNIT_CUM_ORD_QTY
    , SAO.SLS_UNIT_CUM_CNFRM_QTY

    , SAO.SCHD_LN_CNFRM_QTY
    , SAO.SCHD_LN_CNFRM_IN_PD_QTY

    , SAO.SLS_ORDER_QTY
    , SAO.SLS_ORDER_CNFRM_QTY
    , ZEROIFNULL(SUM(DD.DELIV_QTY)) AS SLS_ORDER_DELIV_QTY

    , CASE
        WHEN SAO.SCHD_LN_CNFRM_IN_PD_QTY - SLS_ORDER_DELIV_QTY > 0
            THEN SAO.SCHD_LN_CNFRM_IN_PD_QTY - SLS_ORDER_DELIV_QTY
        ELSE 0
        END AS UNUTILIZED_SA_CNFRM_QTY

FROM (

SELECT
    SA.DAY_DATE
    , SA.FISCAL_YR
    , SA.SLS_DOC_ID
    , SA.SLS_DOC_ITM_ID

    , SA.OUTLN_AGRMNT_VLD_FRM_DT
    , SA.OUTLN_AGRMNT_VLD_TO_DT

    , SA.DAY_BEFORE_PD_BEGIN
    , SA.DAY_BEFORE_PD_END

    , SA.SD_DOC_CTGY_CD
    , SA.SLS_DOC_TYP_CD
    , SA.SLS_DOC_ITM_CTGY_CD

    , SA.AVAIL_CHK_GRP_CD

    , SA.SHIP_TO_CUST_ID
    , SA.SHIP_TO_CUST_NAME
    , SA.OWN_CUST_ID
    , SA.OWN_CUST_NAME

    , SA.MATL_ID
    , SA.DESCR
    , SA.MATL_HIER_ID
    , SA.PBU_NBR
    , SA.PBU_NAME

    , SA.FACILITY_ID
    , SA.FACILITY_NAME

    , SA.SLS_UOM_CD
    , SA.SLS_UNIT_CUM_ORD_QTY
    , SA.SLS_UNIT_CUM_CNFRM_QTY

    , SA.SCHD_LN_CNFRM_QTY
    , SA.SCHD_LN_CNFRM_IN_PD_QTY

    , ZEROIFNULL(SUM(OD.ORDER_QTY)) AS SLS_ORDER_QTY
    , ZEROIFNULL(SUM(OD.CNFRM_QTY)) AS SLS_ORDER_CNFRM_QTY

FROM (

SELECT
    H.DAY_DATE
    , H.FISCAL_YR
    , H.SLS_DOC_ID
    , H.SLS_DOC_ITM_ID

    , H.OUTLN_AGRMNT_VLD_FRM_DT
    , H.OUTLN_AGRMNT_VLD_TO_DT

    , H.DAY_BEFORE_PD_BEGIN
    , H.DAY_BEFORE_PD_END

    , H.SD_DOC_CTGY_CD
    , H.SLS_DOC_TYP_CD
    , SDI.SLS_DOC_ITM_CTGY_CD

    , SDI.AVAIL_CHK_GRP_CD

    , H.SHIP_TO_CUST_ID
    , H.SHIP_TO_CUST_NAME
    , H.OWN_CUST_ID
    , H.OWN_CUST_NAME

    , SDI.MATL_ID
    , M.DESCR
    , SDI.MATL_HIER_ID
    , M.PBU_NBR
    , M.PBU_NAME

    , SDI.FACILITY_ID
    , F.FACILITY_NAME

    , SDI.SLS_UOM_CD
    , SDI.SLS_UNIT_CUM_ORD_QTY
    , SDI.SLS_UNIT_CUM_CNFRM_QTY

    , SUM(SL.SLS_UNIT_CNFRM_QTY) AS RAW_SCHD_LN_CNFRM_QTY
    , CASE
        WHEN RAW_SCHD_LN_CNFRM_QTY > SDI.SLS_UNIT_CUM_CNFRM_QTY
            THEN SDI.SLS_UNIT_CUM_CNFRM_QTY
        ELSE RAW_SCHD_LN_CNFRM_QTY
        END AS SCHD_LN_CNFRM_QTY
    , SUM(CASE WHEN SL.MATL_AVAIL_DT BETWEEN H.OUTLN_AGRMNT_VLD_FRM_DT AND H.OUTLN_AGRMNT_VLD_TO_DT THEN SL.SLS_UNIT_CNFRM_QTY ELSE 0 END) AS RAW_SCHD_LN_CNFRM_IN_PD_QTY
    , CASE
        WHEN RAW_SCHD_LN_CNFRM_IN_PD_QTY > SDI.SLS_UNIT_CUM_CNFRM_QTY
            THEN SDI.SLS_UNIT_CUM_CNFRM_QTY
        ELSE RAW_SCHD_LN_CNFRM_IN_PD_QTY
        END AS SCHD_LN_CNFRM_IN_PD_QTY

FROM (

SELECT
    CAL.DAY_DATE
    , SD.FISCAL_YR
    , SD.SLS_DOC_ID
    , SDI_BOM.SLS_DOC_ITM_ID
    , SD.OUTLN_AGRMNT_VLD_FRM_DT
    , SD.OUTLN_AGRMNT_VLD_TO_DT
    , CAL.DAY_DATE - CAST(1 AS INTERVAL DAY) AS DAY_BEFORE_PD_BEGIN
    , ADD_MONTHS(CAL.DAY_DATE,1) - CAST(2 AS INTERVAL DAY) AS DAY_BEFORE_PD_END
    , SD.SD_DOC_CTGY_CD
    , SD.SLS_DOC_TYP_CD
    , SD.SHIP_TO_CUST_ID
    , C.CUST_NAME AS SHIP_TO_CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

FROM GDYR_BI_VWS.GDYR_CAL CAL

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC SD
        ON CAL.DAY_DATE BETWEEN SD.OUTLN_AGRMNT_VLD_FRM_DT AND SD.OUTLN_AGRMNT_VLD_TO_DT
        AND SD.EXP_DT = CAST('5555-12-31' AS DATE)
        AND SD.SD_DOC_CTGY_CD = 'E'
        AND SD.CO_CD IN ('N101', 'N102', 'N266')

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = SD.SHIP_TO_CUST_ID

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM SDI_BOM
        ON SDI_BOM.FISCAL_YR = SD.FISCAL_YR
        AND SDI_BOM.SLS_DOC_ID = SD.SLS_DOC_ID
        AND DAY_BEFORE_PD_BEGIN BETWEEN SDI_BOM.EFF_DT AND SDI_BOM.EXP_DT
        AND SDI_BOM.ITM_RLVNT_DELIV_IND = 'N'
        AND SDI_BOM.REJ_REAS_ID IS NULL

WHERE
    CAL.DAY_DATE = CAL.MONTH_DT
    AND CAL.DAY_DATE BETWEEN DATE '2014-01-01' AND DATE '2015-02-28'

    ) H

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM SDI
        ON SDI.FISCAL_YR = H.FISCAL_YR
        AND SDI.SLS_DOC_ID = H.SLS_DOC_ID
        AND SDI.SLS_DOC_ITM_ID = H.SLS_DOC_ITM_ID
        AND H.DAY_BEFORE_PD_END BETWEEN SDI.EFF_DT AND SDI.EXP_DT
        AND SDI.ITM_RLVNT_DELIV_IND = 'N'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = SDI.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = SDI.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_SCHD_LN SL
        ON SL.FISCAL_YR = H.FISCAL_YR
        AND SL.SLS_DOC_ID = H.SLS_DOC_ID
        AND SL.SLS_DOC_ITM_ID = H.SLS_DOC_ITM_ID
        AND H.DAY_BEFORE_PD_END BETWEEN SL.EFF_DT AND SL.EXP_DT
        AND SL.ITM_RLVNT_DELIV_IND = 'N'

WHERE
    M.PBU_NBR = '01'

GROUP BY
    H.DAY_DATE
    , H.FISCAL_YR
    , H.SLS_DOC_ID
    , H.SLS_DOC_ITM_ID

    , H.OUTLN_AGRMNT_VLD_FRM_DT
    , H.OUTLN_AGRMNT_VLD_TO_DT

    , H.DAY_BEFORE_PD_BEGIN
    , H.DAY_BEFORE_PD_END

    , H.SD_DOC_CTGY_CD
    , H.SLS_DOC_TYP_CD
    , SDI.SLS_DOC_ITM_CTGY_CD

    , SDI.AVAIL_CHK_GRP_CD

    , H.SHIP_TO_CUST_ID
    , H.SHIP_TO_CUST_NAME
    , H.OWN_CUST_ID
    , H.OWN_CUST_NAME

    , SDI.MATL_ID
    , M.DESCR
    , SDI.MATL_HIER_ID
    , M.PBU_NBR
    , M.PBU_NAME

    , SDI.FACILITY_ID
    , F.FACILITY_NAME

    , SDI.SLS_UOM_CD
    , SDI.SLS_UNIT_CUM_ORD_QTY
    , SDI.SLS_UNIT_CUM_CNFRM_QTY

    ) SA

    LEFT OUTER JOIN (
        GDYR_VWS.SD_DOC_FLOW DF

        INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
            ON OD.ORDER_FISCAL_YR = DF.NEXT_FISCAL_YR
            AND OD.ORDER_ID = DF.NEXT_SD_DOC_ID
            AND OD.ORDER_LINE_NBR = DF.NEXT_SD_DOC_ITM_ID
            AND OD.EXP_DT = CAST('5555-12-31' AS DATE)
            AND OD.ORDER_CAT_ID = 'C'
        )
        ON DF.PREV_FISCAL_YR = SA.FISCAL_YR
        AND DF.PREV_SD_DOC_ID = SA.SLS_DOC_ID
        AND DF.PREV_SD_DOC_ITM_ID = SA.SLS_DOC_ITM_ID
        AND DF.ORIG_SYS_ID = 2
        AND DF.EXP_DT = CAST('5555-12-31' AS DATE)
        AND DF.PREV_SD_DOC_CTGY_CD = 'E'
        AND DF.NEXT_SD_DOC_CTGY_CD = 'C'


GROUP BY
    SA.DAY_DATE
    , SA.FISCAL_YR
    , SA.SLS_DOC_ID
    , SA.SLS_DOC_ITM_ID

    , SA.OUTLN_AGRMNT_VLD_FRM_DT
    , SA.OUTLN_AGRMNT_VLD_TO_DT

    , SA.DAY_BEFORE_PD_BEGIN
    , SA.DAY_BEFORE_PD_END

    , SA.SD_DOC_CTGY_CD
    , SA.SLS_DOC_TYP_CD
    , SA.SLS_DOC_ITM_CTGY_CD

    , SA.AVAIL_CHK_GRP_CD

    , SA.SHIP_TO_CUST_ID
    , SA.SHIP_TO_CUST_NAME
    , SA.OWN_CUST_ID
    , SA.OWN_CUST_NAME

    , SA.MATL_ID
    , SA.DESCR
    , SA.MATL_HIER_ID
    , SA.PBU_NBR
    , SA.PBU_NAME

    , SA.FACILITY_ID
    , SA.FACILITY_NAME

    , SA.SLS_UOM_CD
    , SA.SLS_UNIT_CUM_ORD_QTY
    , SA.SLS_UNIT_CUM_CNFRM_QTY

    , SA.SCHD_LN_CNFRM_QTY
    , SA.SCHD_LN_CNFRM_IN_PD_QTY
    
    ) SAO

    LEFT OUTER JOIN (
        GDYR_VWS.SD_DOC_FLOW DF

        INNER JOIN NA_BI_VWS.DELIVERY_DETAIL_CURR DD
            ON DD.FISCAL_YR = DF.NEXT_FISCAL_YR
            AND DD.DELIV_ID = DF.NEXT_SD_DOC_ID
            AND DD.DELIV_LINE_NBR = DF.NEXT_SD_DOC_ITM_ID
            AND DD.DELIV_CAT_ID = 'J'
            AND DD.SD_DOC_CTGY_CD = 'C'
        )
        ON DF.PREV_FISCAL_YR = SAO.FISCAL_YR
        AND DF.PREV_SD_DOC_ID = SAO.SLS_DOC_ID
        AND DF.PREV_SD_DOC_ITM_ID = SAO.SLS_DOC_ITM_ID
        AND DF.ORIG_SYS_ID = 2
        AND DF.EXP_DT = CAST('5555-12-31' AS DATE)
        AND DF.PREV_SD_DOC_CTGY_CD = 'E'
        AND DF.NEXT_SD_DOC_CTGY_CD = 'J'

GROUP BY
    SAO.DAY_DATE
    , SAO.FISCAL_YR
    , SAO.SLS_DOC_ID
    , SAO.SLS_DOC_ITM_ID

    , SAO.OUTLN_AGRMNT_VLD_FRM_DT
    , SAO.OUTLN_AGRMNT_VLD_TO_DT

    , SAO.DAY_BEFORE_PD_BEGIN
    , SAO.DAY_BEFORE_PD_END

    , SAO.SD_DOC_CTGY_CD
    , SAO.SLS_DOC_TYP_CD
    , SAO.SLS_DOC_ITM_CTGY_CD

    , SAO.AVAIL_CHK_GRP_CD

    , SAO.SHIP_TO_CUST_ID
    , SAO.SHIP_TO_CUST_NAME
    , SAO.OWN_CUST_ID
    , SAO.OWN_CUST_NAME

    , SAO.MATL_ID
    , SAO.DESCR
    , SAO.MATL_HIER_ID
    , SAO.PBU_NBR
    , SAO.PBU_NAME

    , SAO.FACILITY_ID
    , SAO.FACILITY_NAME

    , SAO.SLS_UOM_CD
    , SAO.SLS_UNIT_CUM_ORD_QTY
    , SAO.SLS_UNIT_CUM_CNFRM_QTY

    , SAO.SCHD_LN_CNFRM_QTY
    , SAO.SCHD_LN_CNFRM_IN_PD_QTY

    , SAO.SLS_ORDER_QTY
    , SAO.SLS_ORDER_CNFRM_QTY

    ) SAS

GROUP BY
    SAS.DAY_DATE
    , SAS.DAY_BEFORE_PD_BEGIN
    , SAS.DAY_BEFORE_PD_END

    , SAS.MATL_ID
    , SAS.DESCR
    , SAS.MATL_HIER_ID
    , SAS.PBU_NBR
    , SAS.PBU_NAME

    , SAS.FACILITY_ID
    , SAS.FACILITY_NAME

    , SAS.SLS_UOM_CD

    ) S

    LEFT OUTER JOIN (
        SELECT
            D.MATL_ID
            , D.DELIV_LINE_FACILITY_ID
            , RDD_CAL.MONTH_DT AS FRDD_FPGI_MTH_DT
            , D.QTY_UNIT_MEAS_ID
            , SUM(D.DELIV_QTY) AS GOODS_ISS_LATE_QTY

        FROM NA_BI_VWS.DELIVERY_DETAIL_CURR D

            INNER JOIN GDYR_BI_VWS.GDYR_CAL AGID_CAL
                ON AGID_CAL.DAY_DATE = D.ACTL_GOODS_ISS_DT

            INNER JOIN NA_BI_VWS.ORDER_DETAIL O
                ON O.ORDER_FISCAL_YR = D.ORDER_FISCAL_YR
                AND O.ORDER_ID = D.ORDER_ID
                AND O.ORDER_LINE_NBR = D.ORDER_LINE_NBR
                AND O.SCHED_LINE_NBR = 1
                AND O.EXP_DT = CAST('5555-12-31' AS DATE)
                AND O.ORDER_CAT_ID = 'C'
                AND O.ORDER_TYPE_ID <> 'ZTA'

            INNER JOIN GDYR_BI_VWS.GDYR_CAL RDD_CAL
                ON RDD_CAL.DAY_DATE = O.FRST_PLN_GOODS_ISS_DT

        WHERE
            D.DELIV_NOTE_CREA_DT >= DATE '2013-12-31'
            AND O.FRST_PLN_GOODS_ISS_DT BETWEEN DATE '2014-01-01' AND DATE '2015-02-28'
            AND D.DELIV_CAT_ID = 'J'
            AND RDD_CAL.MONTH_DT < AGID_CAL.MONTH_DT

        GROUP BY
            D.MATL_ID
            , D.DELIV_LINE_FACILITY_ID
            , FRDD_FPGI_MTH_DT
            , D.QTY_UNIT_MEAS_ID
        ) DL
        ON DL.MATL_ID = S.MATL_ID
        AND DL.DELIV_LINE_FACILITY_ID = S.FACILITY_ID
        AND DL.FRDD_FPGI_MTH_DT = S.DAY_DATE
