SELECT
    SL.FISCAL_YR
    , SL.SLS_DOC_ID
    , SL.SLS_DOC_ITM_ID
    --, SL.SCHD_LN_ID

    , SD.SRC_CRT_DT
    , SD.SRC_CRT_TM
    , SD.DOC_DT
    , SD.SRC_UPD_DT
    , SDI.SRC_CRT_TS AS ITM_CRT_TS
    , SDI.SRC_CRT_USR_ID AS ITM_CRT_USR_ID
    , SDI.SRC_UPD_DT AS ITM_UPD_DT
    , SD.SAP_TRANS_CD
    , SD.INQ_QTE_VLD_FRM_DT
    , SD.INQ_QTE_VLD_TO_DT
    , SD.OUTLN_AGRMNT_VLD_FRM_DT
    , SD.OUTLN_AGRMNT_VLD_TO_DT
    , SD.REQ_DELIV_DT AS HDR_REQ_DELIV_DT

    , SD.CUST_PRCH_ORD_ID
    , SD.CUST_PRCH_ORD_TYP_CD
    , SD.CUST_PRCH_ORD_DT

    , SD.SD_DOC_CTGY_CD
    , SD.SLS_DOC_TYP_CD
    , SDI.SLS_DOC_ITM_CTGY_CD
    , SDI.ITM_TYP_CD
    , SL.SCHD_LN_CTGY_CD

    , SD.CO_CD
    , SD.SALES_ORG_CD
    , SD.DISTR_CHAN_CD
    , SD.DIV_CD
    , SD.SOLD_TO_CUST_ID
    , SD.SHIP_TO_CUST_ID

    , SDI.MATL_ID
    , SDI.MATL_HIER_ID

    , SDI.FACILITY_ID
    , SDI.STOR_LOC_CD
    , SDI.SHIP_RCVE_PT_CD

    , SDI.REJ_REAS_ID

    , SDI.ITM_RLVNT_DELIV_IND
    , SDI.ITM_RLVNT_BILL_ICD
    , SL.ITM_RLVNT_DELIV_IND AS SL_RLVNT_DELIV_IND
    , SL.SCHD_LN_CNFRM_STA_CD
    , SL.SCHD_LN_DELIV_BLK_CD
    , SL.AVAIL_CNFRM_AUTO_IND
    , SDI.AVAIL_CHK_GRP_CD

    , SL.MATL_AVAIL_DT
    , SL.GOODS_ISS_DT
    , SL.SCHD_LN_DELIV_DT

    , SDI.ORIG_REQ_DELIV_DT
    , SDI.FRST_MATL_AVAIL_DT
    , SDI.FRST_PLN_GOODS_ISS_DT
    , SDI.FRST_REQ_DELIV_DT

    , SL.SLS_UOM_CD
    , SDI.SLS_UNIT_CUM_ORD_QTY
    , SDI.SLS_UNIT_CUM_REQ_DELIV_QTY
    , SDI.SLS_UNIT_CUM_CNFRM_QTY
    , SL.SLS_UNIT_ORD_QTY AS SL_SLS_UNIT_ORD_QTY
    , SL.SLS_UNIT_CNFRM_QTY AS SL_SLS_UNIT_CNFRM_QTY

FROM GDYR_BI_VWS.NAT_SLS_DOC_SCHD_LN_CURR SL

    INNER JOIN GDYR_BI_VWS.NAT_SLS_DOC_CURR SD
        ON SD.FISCAL_YR = SL.FISCAL_YR
        AND SD.SLS_DOC_ID = SL.SLS_DOC_ID
        AND SD.SD_DOC_CTGY_CD = 'E'
        AND SD.SLS_DOC_TYP_CD = 'ZLZ'
        AND SD.CO_CD IN ('N101', 'N102', 'N266')

    INNER JOIN GDYR_BI_VWS.NAT_SLS_DOC_ITM_CURR SDI
        ON SDI.FISCAL_YR = SL.FISCAL_YR
        AND SDI.SLS_DOC_ID = SL.SLS_DOC_ID
        AND SDI.SLS_DOC_ITM_ID = SL.SLS_DOC_ITM_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = SDI.MATL_ID
        AND M.PBU_NBR = '01'

WHERE
    SL.SCHD_LN_DELIV_DT BETWEEN DATE '2015-01-01' AND CURRENT_DATE-1

ORDER BY 1,2,3,4