SELECT
    SHIP_TO_CUST_ID
    , SHIP_TO_CUST_NO
    , CUST_ID_TRIM
    , CUST_NAME

    , OWN_CUST_ID
    , OWN_CUST_NAME

    , CO_CD
    , CO_DESC

    , SALES_ORG_CD
    , SALES_ORG_NAME

    , DISTR_CHAN_CD
    , DISTR_CHAN_NAME

    , DIV_CD

    , CUST_GRP_ID
    , CUST_GRP_NAME

    , PRIM_SHIP_FACILITY_ID
    , DELIV_PRTY_CD
    , SHIP_COND_ID
    , SALES_ORG_GRP_DESC
    , ACTIV_IND
    , TRANSP_ZONE_CD

    , CUST_GRP2_CD

    , DISTRICT_NAME
    , TERR_NAME
    , CITY_NAME
    , POSTAL_CD
    , CNTRY_NAME_CD
    , ADDR_LINE_1

FROM GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR
