SELECT
    FACILITY_ID
    , NAME
    , XTND_NAME
    , VAL_AREA_ID
    , INT_CUST_ID
    , VENDOR_CUST_ID
    , PURCH_ORG_ID
    , SALES_ORG_CD
    , DISTR_CHAN_CD
    , DIV_CD
    , CNTRY_ID
    , TERR_ID
    , DISTRICT_ID
    , CITY_ID
    , ADDR_ID
    , FACILITY_CAT_ID
    , FACILITY_ACTIV_IND

FROM GDYR_VWS.FACILITY

WHERE
    ORIG_SYS_ID = 2
    AND EXP_DT = CAST('5555-12-31' AS DATE)
    AND LANG_ID = 'EN'
