SELECT
    M.MATL_ID
    , MH.MATL_NO_8
    , M.MATL_ID_TRIM
    , MH.DESCR

    , M.TIC_CD
    , M.MATL_STA_ID
    , M.MATL_STA_DT

    , MH.HVA_TXT
    , MH.HMC_TXT
    , M.SAL_IND

    , MH.MATL_PRTY
    , M.EXT_MATL_GRP_ID
    , MH.STK_CLASS_ID
    , MH.TIRE_SZ_TEXT
    , M.MATL_TYPE_ID

    , M.BRAND_ID
    , MH.BRAND_NAME

    , MH.ASSOC_BRAND_ID
    , MH.ASSOC_BRAND_NAME

    , MH.SUPER_BRAND_ID
    , MH.SUPER_BRAND_NAME

    , M.PBU_NBR
    , MH.PBU_NAME

    , M.MKT_AREA_NBR
    , MH.MKT_AREA_NAME

    , M.MKT_GRP_NBR
    , MH.MKT_GRP_NAME

    , M.PROD_GRP_NBR
    , MH.PROD_GRP_NAME

    , M.PROD_LINE_NBR
    , MH.PROD_LINE_NAME

    , M.MKT_CTGY_MKT_AREA_NBR AS CATEGORY_CD
    , MH.MKT_CTGY_MKT_AREA_NAME AS CATEGORY_NM

    , M.MKT_CTGY_MKT_GRP_NBR AS SEGMENT_CD
    , MH.MKT_CTGY_MKT_GRP_NAME AS SEGMENT_NM

    , M.MKT_CTGY_PROD_GRP_NBR AS SALES_PROD_GRP_CD
    , MH.MKT_CTGY_PROD_GRP_NAME AS SALES_PROD_GRP_NM

    , M.MKT_CTGY_PROD_LINE_NBR AS SALES_PROD_LINE_CD
    , MH.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE_NM

    , CASE
        WHEN M.PBU_NBR = '01'
            THEN MH.MKT_CTGY_PROD_GRP_NAME
        ELSE M.TIERS
        END AS TIER

    , M.BASE_UOM

FROM GDYR_BI_VWS.NAT_MATL_CURR M

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MH
        ON M.MATL_ID = MH.MATL_ID
