SELECT
    CDI.OBJ_CLS_CD
    , CDI.OBJ_VAL_ID
    , CDI.CHG_DOC_ID
    , CDI.SAP_TBL_NM
    , CDI.SAP_COL_NM
    , CDI.CHG_TBL_REC_ID
    , CDI.CHG_TYP_CD
    , CDI.DOC_ID
    , CDI.DOC_ITM_ID
    , CDI.TXT_CHG_IND
    , CDI.OLD_UNIT_QTY
    , CDI.NEW_UNIT_QTY
    , CDI.OLD_CRNCY_ID
    , CDI.NEW_CRNCY_ID
    , CDI.OLD_VAL_TXT
    , CDI.NEW_VAL_TXT
    , CDI.SRC_CRT_DT
    , CDI.SRC_CRT_TM
    , CDI.SRC_CRT_TS

FROM GDYR_BI_vWS.CHG_DOC_ITM CDI

WHERE
    CDI.ORIG_SYS_ID = 2
