SELECT
    DDI.FISCAL_YR
    , DDI.DELIV_DOC_ID
    , DDI.DELIV_DOC_ITM_ID

    , DD.BILL_LADING_ID

    , DD.SD_DOC_CTGY_CD AS DELIV_CTGY_CD
    , DD.DELIV_TYP_CD
    , DD.SRC_CRT_USR_ID AS HDR_CRT_USR_ID
    , DD.SRC_CRT_TS AS HDR_CRT_TS
    , DD.SRC_UPD_DT AS HDR_UPD_DT
    , DD.ORIG_DOC_DT
    , CAL.MONTH_DT AS ORIG_DOC_MONTH_DT

    , CHG.SRC_CRT_DT AS DEL_DT
    , DEL_CAL.MONTH_DT AS DEL_MONTH_DT

    , DDI.ITM_CTGY_CD
    , DDI.SRC_CRT_USR_ID AS ITM_CRT_USR_ID
    , DDI.SRC_CRT_TS AS ITM_CRT_TS
    , DDI.SRC_UPD_DT AS ITM_UPD_DT

    , DDI.SD_DOC_CTGY_CD
    , DDI.SLS_DOC_FISCAL_YR
    , DDI.SLS_DOC_ID
    , DDI.SLS_DOC_ITM_ID

    , DD.SOLD_TO_CUST_ID
    , DD.SHIP_TO_CUST_ID
    , DD.VEND_ID

    , DD.SALES_ORG_CD
    , DDI.DISTR_CHAN_CD
    , DDI.DIV_CD
    , DD.CUST_GRP_CD

    , DDI.MATL_ID
    , DDI.BATCH_NBR
    , DDI.MATL_HIER_ID

    , DD.FACILITY_ID AS HDR_FACILITY_ID
    , DDI.FACILITY_ID AS ITM_FACILITY_ID
    , DDI.STOR_LOC_CD

    , DD.PLN_GOODS_MVT_DT
    , DD.ACTL_GOODS_MVT_DT
    , DD.DELIV_DT

    , DDI.BASE_UOM_CD
    , DDI.ACTL_DELIV_QTY

    , DD.UNLD_PT_TXT
    , DD.INCOTERM_CD_1
    , DD.INCOTERM_CD_2
    , DD.DELIV_PRTY_CD
    , DD.SHIP_COND_CD
    , DD.SAP_TRANS_CD
    , DD.SPCL_PROC_CD
    , DD.MOT_SHIP_ID

    , DDI.MVT_TYP_CD
    , DDI.AVAIL_CHK_GRP_CD
    , DDI.SPCL_STK_TYP_CD

FROM GDYR_VWS.DELIV_DOC_ITM DDI

    INNER JOIN (
        GDYR_VWS.PRCH_DOC_ITM PDI

            INNER JOIN GDYR_VWS.PRCH_DOC PD
                ON PD.PRCH_DOC_ID = PDI.PRCH_DOC_ID
                AND PD.ORIG_SYS_ID = 2
                AND PD.EXP_DT = CAST('5555-12-31' AS DATE)
                AND PD.CO_CD IN ('N101', 'N102', 'N266')
                AND PD.PRCH_CTGY_CD = 'F'
                -- IDENTIFIES STANDARD PO'S TO EXCLUDE INTERNAL STOCK TRANSFERS
                -- INTERNAL STOCK TRANSFERS WILL BE CAPTURED BY MATERIAL MOVEMENTS
                AND PD.PRCH_TYPE_CD = 'NB'
            )
        ON PDI.PRCH_DOC_ID = DDI.SLS_DOC_ID
        AND PDI.PRCH_DOC_ITM_ID = DDI.SLS_DOC_ITM_ID
        AND PDI.ORIG_SYS_ID = 2
        AND PDI.EXP_DT = CAST('5555-12-31' AS DATE)
        AND PDI.CO_CD IN ('N101', 'N102', 'N266')
        AND PDI.CNFRM_CNTRL_ID IN ('Z004', 'Z005')

    INNER JOIN GDYR_BI_VWS.CHG_DOC_ITM CHG
        ON CHG.DOC_ID = DDI.DELIV_DOC_ID
        AND CHG.DOC_ITM_ID = DDI.DELIV_DOC_ITM_ID
        AND CHG.ORIG_SYS_ID = 2
        AND CHG.OBJ_CLS_CD = 'LIEFERUNG'
        AND CHG.SAP_TBL_NM = 'LIPS'
        AND CHG.SAP_COL_NM  = 'KEY'
        AND CHG.CHG_TYP_CD = 'D'

    INNER JOIN GDYR_VWS.DELIV_DOC DD
        ON DD.FISCAL_YR = DDI.FISCAL_YR
        AND DD.DELIV_DOC_ID = DDI.DELIV_DOC_ID
        AND DD.ORIG_SYS_ID = 2

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE = DD.ORIG_DOC_DT

    INNER JOIN GDYR_BI_VWS.GDYR_CAL DEL_CAL
        ON DEL_CAL.DAY_DATE = CHG.SRC_CRT_DT

WHERE
    DDI.ORIG_SYS_ID = 2
    AND CHG.SRC_CRT_DT - CAST(1 AS INTERVAL DAY(4)) BETWEEN DDI.EFF_DT AND DDI.EXP_DT
    AND CHG.SRC_CRT_DT - CAST(1 AS INTERVAL DAY(4)) BETWEEN DD.EFF_DT AND DD.EXP_DT
