CASE
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) = 'BI'
        THEN 'Beginning Inventory'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) = 'EI'
        THEN 'Ending Inventory'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) = 'CI'
        THEN 'Calculated Inventory'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) = 'AD'
        THEN 'Adjustments'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'PC%'
        THEN 'Production Credits'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'GI%'
        THEN 'Goods Issue'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'IP%' OR CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'SN%'
        THEN 'Inbound Import'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'IC%' OR CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'SC%'
        THEN 'Inbound Import Cancel / Reversal'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'TR%'
        THEN 'Stock Receipt'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'RT%'
        THEN 'Stock Receipt Reversal'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'TO%'
        THEN 'STO Outbound'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'TI%'
        THEN 'STO Inbound'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'TC%'
        THEN 'STO Reversal'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'CO%'
        THEN 'Intercompany STO Outbound'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'CR%'
        THEN 'Intercompany STO Inbound'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'CC%'
        THEN 'Intercompany STO Reversal'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'IL%'
        THEN 'Inventory Loss'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'IG%'
        THEN 'Inventory Gain'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'GC%'
        THEN 'Goods Issue for Consumption'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'TF%'
        THEN 'Stock Status Transfer'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'RR%'
        THEN 'Return Receipted'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE 'NC%'
        THEN 'Unclassified Movement'
    ELSE 'No Description Available'
END
||
CASE
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE '%CCPO'
        THEN ' - Counted Current, Posted Other'
    WHEN CAST([Q MM R32 Comparison Union Network Base].[Data Type] AS VARCHAR(25)) LIKE '%PCCO'
        THEN ' - Posted Current, Counted Other'
    ELSE ''
END
