SELECT
    DDC.FISCAL_YR
    , DDC.DELIV_ID
    , DDC.DELIV_LINE_NBR

    , DDC.BILL_LADING_ID
    , DDC.DELIV_CAT_ID
    , DDC.DELIV_TYPE_ID
    , DDC.ITEM_CAT_ID

    , DDC.ORDER_FISCAL_YR
    , DDC.ORDER_ID
    , DDC.ORDER_LINE_NBR

    , DDC.SD_DOC_CTGY_CD

    , DDC.MATL_ID
    , DDC.BATCH_NBR
    , M.MATL_TYPE_ID
    , M.EXT_MATL_GRP_ID
    , M.PBU_NBR
    , M.PBU_NAME
    , M.SUPER_BRAND_ID
    , M.SUPER_BRAND_NAME
    , M.ASSOC_BRAND_ID
    , M.ASSOC_BRAND_NAME

    , DDC.FACILITY_ID AS HDR_FACILITY_ID
    , DDC.DELIV_LINE_FACILITY_ID AS ITM_FACILITY_ID
    , F.FACILITY_NAME AS ITM_FACILITY_NAME

    , DDC.SHIP_TO_CUST_ID

    , DDC.QTY_UNIT_MEAS_ID
    , (-1 * DDC.DELIV_QTY) AS DELIV_QTY

    , DDC.DELIV_PRTY_ID
    , DDC.DELIV_GRP_CD
    , DDC.SHIP_COND_ID
    , DDC.RTG_ID
    , DDC.TERMS_ID
    , DDC.UNLD_PT_CD
    , DDC.GOODS_ISS_IND

    , DDC.DELIV_NOTE_CREA_DT
    , DDC.DELIV_LINE_CREA_DT
    , DDC.PLN_GOODS_MVT_DT
    , DDC.ACTL_GOODS_ISS_DT
    , CAL.MONTH_DT AS ACTL_GOODS_ISS_MONTH_DT
    , DDC.DELIV_DT

FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE = DDC.ACTL_GOODS_ISS_DT

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = DDC.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID

WHERE
    DDC.DELIV_CAT_ID = 'J'
    AND DDC.SD_DOC_CTGY_CD = 'C'
    AND DDC.GOODS_ISS_IND = 'Y'
    AND DDC.ACTL_GOODS_ISS_DT IS NOT NULL
    
    AND M.MATL_TYPE_ID = 'PCTL'
    AND M.EXT_MATL_GRP_ID = 'TIRE'
    
    AND (
        M.PBU_NBR = '01' AND (
            (C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N331') AND M.SUPER_BRAND_ID = '01') -- GDYR_REPL
            OR (C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N331') AND M.ASSOC_BRAND_ID = '10') -- KELLY_BRAND
            OR (C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N331') AND M.ASSOC_BRAND_ID = '11') -- KELLY_ASSOC
            OR (C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N331') AND M.ASSOC_BRAND_ID = '13') -- KELLY_CUSTOM
            OR (C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N331') AND M.SUPER_BRAND_ID = '03') -- DUN_REPL
            OR (M.SUPER_BRAND_ID = '05') -- BLUE_STREAK
            OR (C.SALES_ORG_CD IN ('N303', 'N313') AND C.DISTR_CHAN_CD IN ('30', '31') AND M.SUPER_BRAND_ID = '01') -- GDYR_EXP
            OR (C.SALES_ORG_CD IN ('N303', 'N313') AND C.DISTR_CHAN_CD IN ('30', '31') AND M.SUPER_BRAND_ID = '02') -- KELLY_EXP
            OR (C.SALES_ORG_CD IN ('N303', 'N313') AND C.DISTR_CHAN_CD IN ('30', '31') AND M.SUPER_BRAND_ID = '03') -- DUN_EXP
            OR (C.SALES_ORG_CD IN ('N302', 'N312', 'N322', 'N332') AND M.SUPER_BRAND_ID = '01') -- GDYR_OE
            OR (C.SALES_ORG_CD IN ('N303', 'N313') AND C.DISTR_CHAN_CD IN ('32') AND M.SUPER_BRAND_ID = '01') -- GDYR_EXP_OE
            OR (C.SALES_ORG_CD IN ('N302', 'N312') AND M.SUPER_BRAND_ID = '03') -- DUN_OE
            OR (C.SALES_ORG_CD IN ('N322') AND M.SUPER_BRAND_ID = '03') -- DUN_JV_OE
            OR (C.SALES_ORG_CD IN ('N323') AND C.DISTR_CHAN_CD = '32' AND M.SUPER_BRAND_ID = '03') -- DUN_JV_EXP_OE
        )
        OR M.PBU_NBR <> '01'
        )

    AND M.PBU_NBR = CAST(#prompt('P_PBU', 'text', '''01''')# AS CHAR(2))
    AND CAL.CAL_YR = CAST(#prompt('P_CalYear', 'integer', '2014')# AS INTEGER)
    AND CAL.CAL_MTH BETWEEN CAST(#prompt('P_BeginCalMonth', 'integer', '1')# AS INTEGER)
        AND CAST(#prompt('P_EndCalMonth', 'integer', '12')# AS INTEGER)
