SELECT
    IMP.IMP_DT
    , CAL.MONTH_DT AS IMP_MTH_DT

    , IMP.PRCH_DOC_ID
    , IMP.PRCH_DOC_ITM_ID

    , IMP.MATL_ID
    , IMP.BATCH_NBR
    , M.MATL_TYPE_ID
    , M.EXT_MATL_GRP_ID
    , M.PBU_NBR
    , M.PBU_NAME
    , M.SUPER_BRAND_ID
    , M.SUPER_BRAND_NAME
    , M.ASSOC_BRAND_ID
    , M.ASSOC_BRAND_NAME

    , IMP.FACILITY_ID
    , F.FACILITY_NAME

    , IMP.VEND_ID
    , V.VEND_NM

    , IMP.PRCH_GRP_CD
    , IMP.CNTRY_NAME_CD
    , IMP.CNTRY_NAME
    , IMP.GDYR_RGN_NM

    , MATL.BASE_UOM
    , IMP.IMP_POST_QTY

FROM NA_BI_VWS.NAT_IMPORT_POST_QTY IMP

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE = IMP.IMP_DT

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = IMP.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = IMP.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR MATL
        ON MATL.MATL_ID = IMP.MATL_ID

    INNER JOIN GDYR_BI_VWS.VENDOR_CURR V
        ON V.VEND_ID = IMP.VEND_ID
        AND V.ORIG_SYS_ID = 2
        AND V.LANG_ID = 'E'

WHERE
    M.MATL_TYPE_ID = 'PCTL'
    AND M.EXT_MATL_GRP_ID = 'TIRE'

    AND M.PBU_NBR = CAST(#prompt('P_PBU', 'text', '''01''')# AS CHAR(2))
    AND CAL.CAL_YR = CAST(#prompt('P_CalYear', 'integer', '2014')# AS INTEGER)
    AND CAL.CAL_MTH BETWEEN CAST(#prompt('P_BeginCalMonth', 'integer', '1')# AS INTEGER)
        AND CAST(#prompt('P_EndCalMonth', 'integer', '12')# AS INTEGER)
