SELECT
    CAST('C' AS CHAR(1)) AS QUERY_TYPE
    , C.DAY_DATE
    , C.MONTH_DT
    , PC.MATL_ID
    , PC.FACILITY_ID
    , SUM(PC.PROD_QTY) AS QUANTITY

FROM NA_BI_VWS.PROD_CREDIT_DY PC

    INNER JOIN GDYR_BI_VWS.GDYR_CAL C
        ON C.DAY_DATE = PC.PROD_DT

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = PC.MATL_ID
        AND M.PBU_NBR IN ('01', '03', '04', '05', '07', '08','09')

    INNER JOIN GDYR_VWS.FACILITY F
        ON F.FACILITY_ID = pc.FACILITY_ID
        AND F.EXP_DT = DATE '5555-12-31'
        AND F.ORIG_SYS_ID = 2
        AND F.LANG_ID = 'EN'
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.PURCH_ORG_ID IN ('N701', 'N702', 'N703')
        AND F.DISTR_CHAN_CD = '81'

WHERE
    PC.PROD_DT >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE)
    AND PC.PROD_QTY <> 0

GROUP BY
    QUERY_TYPE
    , C.DAY_DATE
    , C.MONTH_DT
    , PC.MATL_ID
    , PC.FACILITY_ID
