SELECT
    CAL.DAY_DATE
    , CAL.MONTH_DT
    , M.MATL_ID
    , M.PBU_NBR
    
FROM GDYR_BI_VWS.GDYR_CAL CAL

    INNER JOIN GDYR_VWS.MATL M
        ON CAL.DAY_DATE BETWEEN M.EFF_DT AND M.EXP_DT
        AND M.EXP_DT >= ADD_MONTHS(CURRENT_DATE-1, -4) - (EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE-1, -4))-1) 
        AND M.ORIG_SYS_ID = 2
        AND M.MATL_STA_ID <> 'DN'
        AND M.MATL_TYPE_ID IN ('ACCT', 'PCTL')
        AND M.PBU_NBR IN ('01', '03')
        AND M.EXT_MATL_GRP_ID = 'TIRE'



WHERE
    CAL.DAY_DATE BETWEEN ADD_MONTHS(CURRENT_DATE-1, -3) - (EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE-1, -3))-1) 
        AND ADD_MONTHS(CURRENT_DATE-1, -4) - EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE-1, -4))
        
        --AND ADD_MONTHS(CURRENT_DATE-1, 2) - EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE-1, 2))
