SELECT
    CAST('FRDD' AS CHAR(4)) AS METRIC_TYPE
    , C.SALES_ORG_CD
    , C.DISTR_CHAN_CD
    , C.CUST_GRP_ID
    , C.OWN_CUST_ID
    , C.SHIP_TO_CUST_ID
    
    , M.PBU_NBR
    , M.MKT_CTGY_MKT_AREA_NBR AS CATEGORY_CD
    , POL.MATL_ID
    
    , POL.SHIP_FACILITY_ID AS FACILITY_ID
    , POL.CMPL_DT AS BUS_DT

    , SUM(ZEROIFNULL(POL.ORIG_ORD_QTY)) AS ORIG_ORDER_QTY
    , SUM(ZEROIFNULL(POL.CANCEL_QTY)) AS CANCEL_QTY
    , SUM(ZEROIFNULL(POL.CURR_ORD_QTY)) AS ORDER_QTY
    , SUM(ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY)) AS HIT_QTY
    , SUM(ZEROIFNULL(POL.CURR_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY)) AS ONTIME_QTY
    , SUM(ZEROIFNULL(POL.REL_LATE_QTY)) AS REL_LATE_QTY
    , SUM(ZEROIFNULL(POL.REL_ONTIME_QTY)) AS REL_ONTIME_QTY
    , SUM(ZEROIFNULL(POL.COMMIT_ONTIME_QTY)) AS COMMIT_ONTIME_QTY
    , SUM(ZEROIFNULL(POL.DELIV_LATE_QTY)) AS DELIV_LATE_QTY
    , SUM(ZEROIFNULL(POL.DELIV_ONTIME_QTY)) AS DELIV_ONTIME_QTY
    , SUM(ZEROIFNULL(POL.NE_HIT_RT_QTY)) AS RETURN_HIT_QTY
    , SUM(ZEROIFNULL(POL.NE_HIT_CL_QTY)) AS CLAIM_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_HIT_FP_QTY)) AS FREIGHT_POLICY_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_HIT_CARR_PICKUP_QTY) + ZEROIFNULL(POL.OT_HIT_WI_QTY)) AS PHYS_LOG_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_HIT_MB_QTY)) AS MAN_BLK_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_HIT_CH_QTY)) AS CREDIT_HOLD_HIT_QTY
    , SUM(ZEROIFNULL(POL.IF_HIT_NS_QTY)) AS NO_STOCK_HIT_QTY
    , SUM(ZEROIFNULL(POL.IF_HIT_CO_QTY)) AS CANCEL_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_HIT_CG_QTY)) AS CUST_GEN_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_HIT_CG_99_QTY)) AS MAN_REL_CUST_GEN_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_HIT_99_QTY)) AS MAN_REL_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_HIT_LO_QTY)) AS OTHER_HIT_QTY

FROM NA_BI_VWS.PRFCT_ORD_LINE POL

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = POL.MATL_ID
        AND M.PBU_NBR = '01'
        AND M.EXT_MATL_GRP_ID = 'TIRE'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_CURR C
        ON C.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID
        AND C.SALES_ORG_CD NOT IN ('N306', 'N316', 'N326')
        AND C.DISTR_CHAN_CD <> '81'
        
WHERE
    POL.CMPL_IND = 1
    AND POL.CMPL_DT BETWEEN ADD_MONTHS(CURRENT_DATE-1, -3) - (EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE-1, -3)) -1) 
        AND CURRENT_DATE-1
    AND POL.PRFCT_ORD_HIT_SORT_KEY <> 99

GROUP BY
    METRIC_TYPE
    , C.SALES_ORG_CD
    , C.DISTR_CHAN_CD
    , C.CUST_GRP_ID
    , C.OWN_CUST_ID
    , C.SHIP_TO_CUST_ID
    
    , M.PBU_NBR
    , M.MKT_CTGY_MKT_AREA_NBR
    , POL.MATL_ID
    
    , POL.SHIP_FACILITY_ID
    , POL.CMPL_DT

UNION ALL

SELECT
    CAST('FCDD' AS CHAR(4)) AS METRIC_TYPE
    , C.SALES_ORG_CD
    , C.DISTR_CHAN_CD
    , C.CUST_GRP_ID
    , C.OWN_CUST_ID
    , C.SHIP_TO_CUST_ID
    
    , M.PBU_NBR
    , M.MKT_CTGY_MKT_AREA_NBR AS CATEGORY_CD
    , POL.MATL_ID
    
    , POL.SHIP_FACILITY_ID AS FACILITY_ID
    , POL.CMPL_DT AS BUS_DT

    , SUM(ZEROIFNULL(POL.ORIG_ORD_QTY)) AS ORIG_ORDER_QTY
    , SUM(ZEROIFNULL(POL.CANCEL_QTY)) AS CANCEL_QTY
    , SUM(ZEROIFNULL(POL.FPDD_ORD_QTY)) AS ORDER_QTY
    , SUM(ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY)) AS HIT_QTY
    , SUM(ZEROIFNULL(POL.FPDD_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY)) AS ONTIME_QTY
    , SUM(ZEROIFNULL(POL.DELIV_FPDD_LATE_QTY)) AS DELIV_LATE_QTY
    , SUM(ZEROIFNULL(POL.DELIV_FPDD_ONTIME_QTY)) AS DELIV_ONTIME_QTY
    , SUM(ZEROIFNULL(POL.FPDD_COMMIT_ONTIME_QTY)) AS COMMIT_ONTIME_QTY
    , SUM(ZEROIFNULL(POL.REL_FPDD_LATE_QTY)) AS REL_LATE_QTY
    , SUM(ZEROIFNULL(POL.REL_FPDD_ONTIME_QTY)) AS REL_ONTIME_QTY
    , SUM(ZEROIFNULL(POL.NE_FPDD_HIT_RT_QTY)) AS RETURN_HIT_QTY
    , SUM(ZEROIFNULL(POL.NE_FPDD_HIT_CL_QTY)) AS CLAIM_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_FP_QTY)) AS FREIGHT_POLICY_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CARR_QTY) + ZEROIFNULL(POL.OT_FPDD_HIT_WI_QTY)) AS PHYS_LOG_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_MB_QTY)) AS MAN_BLK_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CH_QTY)) AS CREDIT_HOLD_HIT_QTY
    , SUM(ZEROIFNULL(POL.IF_FPDD_HIT_NS_QTY)) AS NO_STOCK_HIT_QTY
    , SUM(ZEROIFNULL(POL.IF_FPDD_HIT_CO_QTY)) AS CANCEL_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CG_QTY)) AS CUST_GEN_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CG_99_QTY)) AS MAN_REL_CUST_GEN_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_99_QTY)) AS MAN_REL_HIT_QTY
    , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_LO_QTY)) AS OTHER_HIT_QTY

FROM NA_BI_VWS.PRFCT_ORD_LINE POL

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = POL.MATL_ID
        AND M.PBU_NBR = '01'
        AND M.EXT_MATL_GRP_ID = 'TIRE'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_CURR C
        ON C.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID
        AND C.SALES_ORG_CD NOT IN ('N306', 'N316', 'N326')
        AND C.DISTR_CHAN_CD <> '81'
        
WHERE
    POL.FPDD_CMPL_IND = 1
    AND POL.FRST_PROM_DELIV_DT IS NOT NULL
    AND POL.FPDD_CMPL_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND CURRENT_DATE-1
    AND POL.PRFCT_ORD_FPDD_HIT_SORT_KEY <> 99

GROUP BY
    METRIC_TYPE
    , C.SALES_ORG_CD
    , C.DISTR_CHAN_CD
    , C.CUST_GRP_ID
    , C.OWN_CUST_ID
    , C.SHIP_TO_CUST_ID
    
    , M.PBU_NBR
    , M.MKT_CTGY_MKT_AREA_NBR
    , POL.MATL_ID
    
    , POL.SHIP_FACILITY_ID
    , POL.CMPL_DT
