SELECT
    Q.MONTH_DT
    , Q.DAY_DATE
    , Q.SALES_ORG_CD
    , Q.SALES_ORG_NAME
    , Q.DISTR_CHAN_CD
    , Q.DISTR_CHAN_NAME
    , Q.CUST_GRP_ID
    , Q.CUST_GRP_NAME
    , Q.OWN_CUST_ID
    , Q.OWN_CUST_NAME
    --, Q.SHIP_TO_CUST_ID
    --, Q.SHIP_TO_CUST_NAME
    --, Q.MATL_ID
    --, Q.DESCR
    , Q.PBU_NBR
    , Q.PBU_NAME
    , Q.QTY_UOM
    , SUM(CASE
        WHEN TYP = 'ORD'
            THEN Q.QUANTITY
        ELSE 0
        END) AS ORDER_QTY
    , SUM(CASE
        WHEN TYP = 'DLV'
            THEN Q.QUANTITY
        ELSE 0
        END) AS DELIV_QTY
    , SUM(CASE
        WHEN TYP = 'SLS'
            THEN Q.QUANTITY
        ELSE 0
        END) AS BILL_QTY
    , SUM(CASE
        WHEN TYP = 'PGI'
            THEN Q.QUANTITY
        ELSE 0
        END) AS PGI_QTY

FROM (

    SELECT
        CAST('SLS' AS CHAR(3)) AS TYP
        , CAL.MONTH_DT
        , CAL.DAY_DATE
        , CUST.SALES_ORG_CD
        , CUST.SALES_ORG_NAME
        , CUST.DISTR_CHAN_CD
        , CUST.DISTR_CHAN_NAME
        , CUST.CUST_GRP_ID
        , CUST.CUST_GRP_NAME
        , CUST.TIRE_CUST_TYP_CD
        , CUST.OWN_CUST_ID
        , CUST.OWN_CUST_NAME
        --, CUST.SHIP_TO_CUST_ID
        --, CUST.CUST_NAME AS SHIP_TO_CUST_NAME
        --, MATL.MATL_ID
        --, MATL.DESCR
        , MATL.PBU_NBR
        , MATL.PBU_NAME
        , SA.SLS_UOM AS QTY_UOM
        , SUM(ZEROIFNULL(SA.SLS_QTY)) AS QUANTITY

    FROM NA_VWS.SLS_AGG SA

        INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
            ON CAL.DAY_DATE = SA.BILL_DT

        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = SA.LEGACY_SHIP_TO_CUST_NO
            AND CUST.SALES_ORG_CD NOT IN ('N306', 'N316', 'N326')
            AND CUST.DISTR_CHAN_CD <> '81'

        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
            ON MATL.MATL_ID = SA.MATL_NO
            AND MATL.PBU_NBR IN ('01', '03')
            AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')
            AND MATL.MATL_STA_ID <> 'DN'
            AND MATL.EXT_MATL_GRP_ID = 'TIRE'

    WHERE
        SA.BILL_DT BETWEEN ADD_MONTHS(CURRENT_DATE-1, -4) - (EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE-1, -4))-1) AND CURRENT_DATE-1
        AND SA.SLS_QTY <> 0

    GROUP BY
        TYP
        , CAL.MONTH_DT
        , CAL.DAY_DATE
        , CUST.SALES_ORG_CD
        , CUST.SALES_ORG_NAME
        , CUST.DISTR_CHAN_CD
        , CUST.DISTR_CHAN_NAME
        , CUST.CUST_GRP_ID
        , CUST.CUST_GRP_NAME
        , CUST.TIRE_CUST_TYP_CD
        , CUST.OWN_CUST_ID
        , CUST.OWN_CUST_NAME
        --, CUST.SHIP_TO_CUST_ID
        --, SHIP_TO_CUST_NAME
        --, MATL.MATL_ID
        --, MATL.DESCR
        , MATL.PBU_NBR
        , MATL.PBU_NAME
        , QTY_UOM

    UNION ALL

    SELECT
        CAST('DLV' AS CHAR(3)) AS TYP
        , CAL.MONTH_DT
        , CAL.DAY_DATE
        , CUST.SALES_ORG_CD
        , CUST.SALES_ORG_NAME
        , CUST.DISTR_CHAN_CD
        , CUST.DISTR_CHAN_NAME
        , CUST.CUST_GRP_ID
        , CUST.CUST_GRP_NAME
        , CUST.TIRE_CUST_TYP_CD
        , CUST.OWN_CUST_ID
        , CUST.OWN_CUST_NAME
        --, CUST.SHIP_TO_CUST_ID
        --, CUST.CUST_NAME AS SHIP_TO_CUST_NAME
        --, MATL.MATL_ID
        --, MATL.DESCR
        , MATL.PBU_NBR
        , MATL.PBU_NAME
        , DDC.QTY_UNIT_MEAS_ID AS QTY_UOM
        , SUM(ZEROIFNULL(DDC.DELIV_QTY)) AS QUANTITY

    FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

        INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
            ON CAL.DAY_DATE = DDC.ACTL_GOODS_ISS_DT
        
        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID

        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
            ON MATL.MATL_ID = DDC.MATL_ID
            AND MATL.PBU_NBR IN ('01', '03')
            AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')
            AND MATL.MATL_STA_ID <> 'DN'
            AND MATL.EXT_MATL_GRP_ID = 'TIRE'

    WHERE
        DDC.DELIV_CAT_ID = 'J'
        AND DDC.DELIV_QTY > 0
        AND DDC.GOODS_ISS_IND = 'Y'
        AND DDC.ACTL_GOODS_ISS_DT IS NOT NULL
        AND DDC.ACTL_GOODS_ISS_DT BETWEEN ADD_MONTHS(CURRENT_DATE-1, -6) - (EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE-1, -6))-1) AND CURRENT_DATE-1
        AND DDC.SALES_ORG_CD NOT IN ('N306', 'N316', 'N326')
        AND DDC.DISTR_CHAN_CD <> '81'

    GROUP BY
        TYP
        , CAL.MONTH_DT
        , CAL.DAY_DATE
        , CUST.SALES_ORG_CD
        , CUST.SALES_ORG_NAME
        , CUST.DISTR_CHAN_CD
        , CUST.DISTR_CHAN_NAME
        , CUST.CUST_GRP_ID
        , CUST.CUST_GRP_NAME
        , CUST.TIRE_CUST_TYP_CD
        , CUST.OWN_CUST_ID
        , CUST.OWN_CUST_NAME
        --, CUST.SHIP_TO_CUST_ID
        --, SHIP_TO_CUST_NAME
        --, MATL.MATL_ID
        --, MATL.DESCR
        , MATL.PBU_NBR
        , MATL.PBU_NAME
        , QTY_UOM

    UNION ALL

    SELECT
        CAST('ORD' AS CHAR(3)) AS TYP
        , CAL.MONTH_DT
        , CAL.DAY_DATE
        , CUST.SALES_ORG_CD
        , CUST.SALES_ORG_NAME
        , CUST.DISTR_CHAN_CD
        , CUST.DISTR_CHAN_NAME
        , CUST.CUST_GRP_ID
        , CUST.CUST_GRP_NAME
        , CUST.TIRE_CUST_TYP_CD
        , CUST.OWN_CUST_ID
        , CUST.OWN_CUST_NAME
        --, CUST.SHIP_TO_CUST_ID
        --, CUST.CUST_NAME AS SHIP_TO_CUST_NAME
        --, MATL.MATL_ID
        --, MATL.DESCR
        , MATL.PBU_NBR
        , MATL.PBU_NAME
        , ODC.QTY_UNIT_MEAS_ID AS QTY_UOM
        , SUM(ZEROIFNULL(ODC.ORDER_QTY)) AS QUANTITY

    FROM NA_BI_VWS.ORDER_DETAIL ODC

        INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
            ON CAL.DAY_DATE = ODC.ORDER_DT
        
        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID

        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
            ON MATL.MATL_ID = ODC.MATL_ID
            AND MATL.PBU_NBR IN ('01', '03')
            AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')
            AND MATL.MATL_STA_ID <> 'DN'
            AND MATL.EXT_MATL_GRP_ID = 'TIRE'

    WHERE
        ODC.EXP_DT = DATE '5555-12-31'
        AND ODC.ORDER_CAT_ID = 'C'
        AND ODC.ORDER_DT BETWEEN ADD_MONTHS(CURRENT_DATE-1, -6) - (EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE-1, -6))-1) AND CURRENT_DATE-1
        AND ODC.RO_PO_TYPE_IND = 'N'

    GROUP BY
        TYP
        , CAL.MONTH_DT
        , CAL.DAY_DATE
        , CUST.SALES_ORG_CD
        , CUST.SALES_ORG_NAME
        , CUST.DISTR_CHAN_CD
        , CUST.DISTR_CHAN_NAME
        , CUST.CUST_GRP_ID
        , CUST.CUST_GRP_NAME
        , CUST.TIRE_CUST_TYP_CD
        , CUST.OWN_CUST_ID
        , CUST.OWN_CUST_NAME
        --, CUST.SHIP_TO_CUST_ID
        --, SHIP_TO_CUST_NAME
        --, MATL.MATL_ID
        --, MATL.DESCR
        , MATL.PBU_NBR
        , MATL.PBU_NAME
        , QTY_UOM
        
    UNION ALL
        
    SELECT
        CAST('PGI' AS CHAR(3)) AS TYP
        , CAL.MONTH_DT
        , CAL.DAY_DATE
        , CUST.SALES_ORG_CD
        , CUST.SALES_ORG_NAME
        , CUST.DISTR_CHAN_CD
        , CUST.DISTR_CHAN_NAME
        , CUST.CUST_GRP_ID
        , CUST.CUST_GRP_NAME
        , CUST.TIRE_CUST_TYP_CD
        , CUST.OWN_CUST_ID
        , CUST.OWN_CUST_NAME
        --, CUST.SHIP_TO_CUST_ID
        --, CUST.CUST_NAME AS SHIP_TO_CUST_NAME
        --, MATL.MATL_ID
        --, MATL.DESCR
        , MATL.PBU_NBR
        , MATL.PBU_NAME
        , ODC.QTY_UNIT_MEAS_ID AS QTY_UOM
        , SUM(ZEROIFNULL(OOL.OPEN_CNFRM_QTY)) AS QUANTITY

    FROM NA_BI_VWS.ORDER_DETAIL ODC

        INNER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL
            ON OOL.ORDER_FISCAL_YR = ODC.ORDER_FISCAL_YR
            AND OOL.ORDER_ID = ODC.ORDER_ID
            AND OOL.ORDER_LINE_NBR = ODC.ORDER_LINE_NBR
            AND OOL.SCHED_LINE_NBR = ODC.SCHED_LINE_NBR
            AND OOL.OPEN_CNFRM_QTY > 0

        INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
            ON CAL.DAY_DATE = ODC.PLN_GOODS_ISS_DT
        
        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID

        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
            ON MATL.MATL_ID = ODC.MATL_ID
            AND MATL.PBU_NBR IN ('01', '03')
            AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')
            AND MATL.MATL_STA_ID <> 'DN'
            AND MATL.EXT_MATL_GRP_ID = 'TIRE'

    WHERE
        ODC.EXP_DT = DATE '5555-12-31'
        AND ODC.ORDER_CAT_ID = 'C'
        -- ROLLING +6 MONTHS
        AND ODC.PLN_GOODS_ISS_DT CURRENT_DATE-1 AND ADD_MONTHS(CURRENT_DATE-1, 7) - EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE-1, 7)
        AND ODC.RO_PO_TYPE_IND = 'N'

    GROUP BY
        TYP
        , CAL.MONTH_DT
        , CAL.DAY_DATE
        , CUST.SALES_ORG_CD
        , CUST.SALES_ORG_NAME
        , CUST.DISTR_CHAN_CD
        , CUST.DISTR_CHAN_NAME
        , CUST.CUST_GRP_ID
        , CUST.CUST_GRP_NAME
        , CUST.TIRE_CUST_TYP_CD
        , CUST.OWN_CUST_ID
        , CUST.OWN_CUST_NAME
        --, CUST.SHIP_TO_CUST_ID
        --, SHIP_TO_CUST_NAME
        --, MATL.MATL_ID
        --, MATL.DESCR
        , MATL.PBU_NBR
        , MATL.PBU_NAME
        , QTY_UOM

    ) Q

GROUP BY
    Q.MONTH_DT
    , Q.DAY_DATE
    , Q.SALES_ORG_CD
    , Q.SALES_ORG_NAME
    , Q.DISTR_CHAN_CD
    , Q.DISTR_CHAN_NAME
    , Q.CUST_GRP_ID
    , Q.CUST_GRP_NAME
    , Q.OWN_CUST_ID
    , Q.OWN_CUST_NAME
    --, Q.SHIP_TO_CUST_ID
    --, Q.SHIP_TO_CUST_NAME
    --, Q.MATL_ID
    --, Q.DESCR
    , Q.PBU_NBR
    , Q.PBU_NAME
    , Q.QTY_UOM

ORDER BY
    Q.DAY_DATE
    , Q.SALES_ORG_CD
    , Q.DISTR_CHAN_CD
    , Q.CUST_GRP_ID
    , Q.OWN_CUST_ID
    , Q.PBU_NBR

