SELECT
    CYC.MATL_ID,
    CAL.DAY_DATE,
    CYC.FACILITY_ID,
    MIN( CYC.LVL_GRP_ID ) AS MIN_LEVEL_DESIGN,
    MAX( CYC.LVL_GRP_ID ) AS MAX_LEVEL_DESIGN

FROM GDYR_VWS.GDYR_CAL CAL

    INNER JOIN NA_VWS.FACL_MATL_CYCASGN CYC
        ON CAL.DAY_DATE BETWEEN CYC.EFF_DT AND CYC.EXP_DT
        AND CYC.LVL_DESIGN_STA_CD = 'A'
        AND CYC.ORIG_SYS_ID = 2
        AND CYC.SBU_ID = 2
        AND CYC.SRC_SYS_ID = 2

    INNER JOIN (
        SELECT
            MATL_ID,
            FACILITY_ID,
            DAY_DATE,
            MAX(LVL_DESIGN_EFF_DT) AS MAX_LVL_DESIGN_EFF_DT

        FROM GDYR_BI_VWS.GDYR_CAL C

            INNER JOIN NA_VWS.FACL_MATL_CYCASGN B
                ON C.DAY_DATE BETWEEN B.EFF_DT AND B.EXP_DT
                AND B.LVL_DESIGN_STA_CD = 'A'
                AND B.ORIG_SYS_ID = 2
                AND B.SBU_ID = 2
                AND B.SRC_SYS_ID = 2

        WHERE
            C.DAY_DATE BETWEEN ( CAST( ( EXTRACT( YEAR FROM CURRENT_DATE ) - 1 ) || '-01-01' AS DATE ) ) AND ( CURRENT_DATE - 1 )
            
        GROUP BY
            MATL_ID,
            FACILITY_ID,
            DAY_DATE

        ) LIM
        ON LIM.MATL_ID = CYC.MATL_ID
        AND LIM.FACILITY_ID = CYC.FACILITY_ID
        AND LIM.DAY_DATE = CAL.DAY_DATE
        AND LIM.MAX_LVL_DESIGN_EFF_DT = CYC.LVL_DESIGN_EFF_DT

WHERE
    CAL.DAY_DATE BETWEEN ( CAST( ( EXTRACT( YEAR FROM CURRENT_DATE ) - 1 ) || '-01-01' AS DATE ) ) AND ( CURRENT_DATE - 1 )

GROUP BY
    CYC.MATL_ID,
    CAL.DAY_DATE,
    CYC.FACILITY_ID

HAVING
    MAX_LEVEL_DESIGN IS NOT NULL
    AND COUNT(*) > 1

ORDER BY
    CAL.DAY_DATE,
    CYC.FACILITY_ID,
    CYC.MATL_ID