SELECT
    P.PLN_MATL_ID,
    P.FACILITY_ID,
    P.PROD_WK_DT,
    P.PROD_WK_DT + 6 AS PROD_WK_END,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = '0' AND C.BEGIN_DT - ( 2 + 7 * 0 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END / 7.000 AS FLOAT ) ) AS LAG_00_DYS_PLN_0_QTY,
    MAX( CAST(  CASE
        WHEN P.PROD_PLN_CD = '0' AND C.BEGIN_DT - ( 2 + 7 * 1 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END / 7.000 AS FLOAT) ) AS LAG_07_DYS_PLN_0_QTY,
    MAX( CAST(  CASE
        WHEN P.PROD_PLN_CD = '0' AND C.BEGIN_DT -  ( 2 + 7 * 2 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_14_DYS_PLN_0_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = '0' AND C.BEGIN_DT - ( 2 + 7 * 3 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END / 7.000 AS FLOAT ) ) AS LAG_21_DYS_PLN_0_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = '0' AND  ADD_MONTHS( ( C.BEGIN_DT - 2 ), -1 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_1_MTH_PLN_0_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = '0' AND  ADD_MONTHS( ( C.BEGIN_DT - 2 ), -2 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_2_MTH_PLN_0_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = '0' AND  ADD_MONTHS( ( C.BEGIN_DT - 2 ), -3 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END / 7.000 AS FLOAT ) ) AS LAG_3_MTH_PLN_0_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = '0' AND  ADD_MONTHS( ( C.BEGIN_DT - 2 ), -4 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_4_MTH_PLN_0_QTY,
    
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = '4' AND C.BEGIN_DT - ( 2 + 7 * 0 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_00_DYS_PLN_4_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = '4' AND C.BEGIN_DT - ( 2 + 7 * 1 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_07_DYS_PLN_4_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = '4' AND C.BEGIN_DT -  ( 2 + 7 * 2 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_14_DYS_PLN_4_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = '4' AND C.BEGIN_DT - ( 2 + 7 * 3 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_21_DYS_PLN_4_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = '4' AND  ADD_MONTHS( ( C.BEGIN_DT - 2 ), -1 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_1_MTH_PLN_4_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = '4' AND  ADD_MONTHS( ( C.BEGIN_DT - 2 ), -2 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_2_MTH_PLN_4_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = '4' AND  ADD_MONTHS( ( C.BEGIN_DT - 2 ), -3 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_3_MTH_PLN_4_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = '4' AND  ADD_MONTHS( ( C.BEGIN_DT - 2 ), -4 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_4_MTH_PLN_4_QTY,
    
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = 'A' AND C.BEGIN_DT - ( 2 + 7 * 0 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_00_DYS_PLN_A_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = 'A' AND C.BEGIN_DT - ( 2 + 7 * 1 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_07_DYS_PLN_A_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = 'A' AND C.BEGIN_DT -  ( 2 + 7 * 2 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_14_DYS_PLN_A_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = 'A' AND C.BEGIN_DT - ( 2 + 7 * 3 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_21_DYS_PLN_A_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = 'A' AND  ADD_MONTHS( ( C.BEGIN_DT - 2 ), -1 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_1_MTH_PLN_A_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = 'A' AND  ADD_MONTHS( ( C.BEGIN_DT - 2 ), -2 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_2_MTH_PLN_A_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = 'A' AND  ADD_MONTHS( ( C.BEGIN_DT - 2 ), -3 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_3_MTH_PLN_A_QTY,
    MAX( CAST( CASE
        WHEN P.PROD_PLN_CD = 'A' AND  ADD_MONTHS( ( C.BEGIN_DT - 2 ), -4 ) BETWEEN P.EFF_DT AND P.EXP_DT
            THEN P.PLN_QTY
        ELSE 0
    END/ 7.000 AS FLOAT ) ) AS LAG_4_MTH_PLN_A_QTY

FROM GDYR_VWS.PROD_PLN P

    INNER JOIN GDYR_VWS.GDYR_CAL C
        ON C.DAY_DATE = P.PROD_WK_DT

WHERE
    P.PROD_PLN_CD IN ( '0', '4', 'A' )
    AND P.SBU_ID = 2
    AND EXTRACT( YEAR FROM P.PROD_WK_DT ) >= EXTRACT( YEAR FROM CURRENT_DATE ) - 2

GROUP BY
    P.PLN_MATL_ID,
    P.FACILITY_ID,
    P.PROD_WK_DT