SELECT
    ICG.MATL_ID
    , ICG.MONTH_DT
    , AVERAGE(ICG.SUM_DEMAND_VAR + ICG.SUM_TRANS_VAR + ICG.SUM_SUPPLY_VAR + ICG.SUM_GEO + (ICG.SUM_SHIP_LOT_SIZE / 2) +
              (ICG.SUM_SHIP_INTERVAL / 2)) + AVERAGE(ZEROIFNULL(ICA.MIN_INV_ADJ_QTY)) AS MIN_INV
    , AVERAGE(ICG.SUM_DEMAND_VAR + ICG.SUM_TRANS_VAR + ICG.SUM_SUPPLY_VAR + ICG.SUM_GEO + (ICG.SUM_SHIP_LOT_SIZE / 2) +
             (ICG.SUM_SHIP_INTERVAL / 2) + ICG.SUM_MFG_LOT_SIZE + ICG.SUM_INFO_CYCLE) + AVERAGE(ZEROIFNULL(ICA.MIN_INV_ADJ_QTY)) +
             AVERAGE(ZEROIFNULL(ICA.SHIP_STD_DEVN_MATL_ADJ_QTY)) + AVERAGE(ZEROIFNULL(ICA.MIN_PROD_RUN_INV_ADJ_QTY)) AS MAX_INV
    , (MIN_INV + MAX_INV) / 2 AS TARGET_INV

FROM (

    SELECT
        ICC.MATL_ID
        , CAL.DAY_DATE
        , CAL.MONTH_DT
        , SUM(ZEROIFNULL(ICC.DMAN_VAR_CMPNT_INV_QTY)) AS SUM_DEMAND_VAR
        , SUM(ZEROIFNULL(ICC.TRANSP_VAR_CMPNT_INV_QTY)) AS SUM_TRANS_VAR
        , SUM(ZEROIFNULL(ICC.SPLY_VAR_CMPNT_INV_QTY)) AS SUM_SUPPLY_VAR
        , SUM(ZEROIFNULL(ICC.GEO_CMPNT_INV_QTY)) AS SUM_GEO
        , SUM(ZEROIFNULL(ICC.SHIP_LOT_SZ_CMPNT_INV_QTY)) AS SUM_SHIP_LOT_SIZE
        , SUM(ZEROIFNULL(ICC.SHIP_INTVL_CMPNT_INV_QTY)) AS SUM_SHIP_INTERVAL
        , SUM(ZEROIFNULL(ICC.MFG_LOT_SZ_CMPNT_INV_QTY)) AS SUM_MFG_LOT_SIZE
        , SUM(ZEROIFNULL(ICC.INFO_CYCL_CMPNT_INV_QTY)) AS SUM_INFO_CYCLE

    FROM NA_BI_VWS.INV_COMPONENT_CURR ICC

        INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
            ON CAL.DAY_DATE = ICC.SRC_CRT_DT
            AND CAL.DAY_DATE BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND CURRENT_DATE-1

        INNER JOIN GDYR_VWS.FACILITY F
            ON F.FACILITY_ID = ICC.FACILITY_ID
            AND F.EXP_DT = DATE '5555-12-31'
            AND F.ORIG_SYS_ID = 2
            AND F.LANG_ID = 'EN'
            AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
            AND F.PURCH_ORG_ID IN ('N701', 'N702', 'N703')
            AND F.DISTR_CHAN_CD = '81'

        INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR MH
            ON MH.MATL_ID = ICC.MATL_ID
            AND MH.PBU_NBR IN ('01','03')
            AND MH.EXT_MATL_GRP_ID = 'TIRE'
            AND mh.matl_id = '000000000000204489'

    WHERE
        ICC.SRC_CRT_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND CURRENT_DATE-1

    GROUP BY
        ICC.MATL_ID
        , CAL.DAY_DATE
        , CAL.MONTH_DT

    UNION ALL

    SELECT
        Q.MATL_ID
        , CAL.DAY_DATE
        , CAL.MONTH_DT
        , Q.SUM_DEMAND_VAR
        , Q.SUM_TRANS_VAR
        , Q.SUM_SUPPLY_VAR
        , Q.SUM_GEO
        , Q.SUM_SHIP_LOT_SIZE
        , Q.SUM_SHIP_INTERVAL
        , Q.SUM_MFG_LOT_SIZE
        , Q.SUM_INFO_CYCLE

    FROM GDYR_BI_VWS.GDYR_CAL CAL

        FULL OUTER JOIN (
                SELECT
                    ICC.MATL_ID
                    , SUM(ZEROIFNULL(ICC.DMAN_VAR_CMPNT_INV_QTY)) AS SUM_DEMAND_VAR
                    , SUM(ZEROIFNULL(ICC.TRANSP_VAR_CMPNT_INV_QTY)) AS SUM_TRANS_VAR
                    , SUM(ZEROIFNULL(ICC.SPLY_VAR_CMPNT_INV_QTY)) AS SUM_SUPPLY_VAR
                    , SUM(ZEROIFNULL(ICC.GEO_CMPNT_INV_QTY)) AS SUM_GEO
                    , SUM(ZEROIFNULL(ICC.SHIP_LOT_SZ_CMPNT_INV_QTY)) AS SUM_SHIP_LOT_SIZE
                    , SUM(ZEROIFNULL(ICC.SHIP_INTVL_CMPNT_INV_QTY)) AS SUM_SHIP_INTERVAL
                    , SUM(ZEROIFNULL(ICC.MFG_LOT_SZ_CMPNT_INV_QTY)) AS SUM_MFG_LOT_SIZE
                    , SUM(ZEROIFNULL(ICC.INFO_CYCL_CMPNT_INV_QTY)) AS SUM_INFO_CYCLE

                FROM NA_BI_VWS.INV_COMPONENT_CURR ICC

                    INNER JOIN GDYR_VWS.FACILITY F
                        ON F.FACILITY_ID = ICC.FACILITY_ID
                        AND F.EXP_DT = DATE '5555-12-31'
                        AND F.ORIG_SYS_ID = 2
                        AND F.LANG_ID = 'EN'
                        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
                        AND F.PURCH_ORG_ID IN ('N701', 'N702', 'N703')
                        AND F.DISTR_CHAN_CD = '81'

                    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR MH
                        ON MH.MATL_ID = ICC.MATL_ID
                        AND MH.PBU_NBR IN ('01','03')
                        AND MH.EXT_MATL_GRP_ID = 'TIRE'
                        AND mh.matl_id = '000000000000204489'

                WHERE
                    ICC.SRC_CRT_DT = CURRENT_DATE-1

                GROUP BY
                    ICC.MATL_ID
                ) Q
            ON 1=1

    WHERE
        CAL.DAY_DATE BETWEEN CURRENT_DATE AND ADD_MONTHS(CURRENT_DATE, 7) - EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE, 7))

    ) ICG

    LEFT OUTER JOIN NA_BI_VWS.INV_COMPONENT_ADJ_CURR ICA
        ON ICA.MATL_ID = ICG.MATL_ID
        AND ICA.SRC_CRT_DT = ICG.DAY_DATE

GROUP BY
    ICG.MATL_ID
    , ICG.MONTH_DT