SELECT
    INV.MATL_ID
    , INV.FACILITY_ID
    , CAL.MONTH_DT
    , INV.INV_QTY_UOM
    , ZEROIFNULL(INV.DEF_QTY) AS DEF_QTY
    , ZEROIFNULL(INV.BACK_ORDER_QTY) AS BACK_ORDER_QTY
    , ZEROIFNULL(INV.NET_BACK_ORDER_QTY) AS NET_BACK_ORDER_QTY
    , ZEROIFNULL(INV.COMMIT_QTY) AS COMMIT_QTY
    , ZEROIFNULL(INV.UN_COMMIT_QTY) AS UN_COMMIT_QTY
    , ZEROIFNULL(INV.TOT_QTY) AS TOT_QTY
    , ZEROIFNULL(INV.AVAIL_TO_PROM_QTY) AS ATP_QTY
    , ZEROIFNULL(INV.STO_INBOUND_QTY) AS STO_INBOUND_QTY
    , ZEROIFNULL(INV.IN_TRANS_QTY) AS IN_TRANS_QTY
    , ZEROIFNULL(INV.STO_OUTBOUND_QTY) AS STO_OUTBOUND_QTY
    , ZEROIFNULL(INV.IN_PROS_TO_CUST_QTY) AS IN_PROS_TO_CUST_QTY
    , ZEROIFNULL(INV.OPEN_FACT_UNIT_QTY) AS OPEN_FACT_UNIT_QTY
    , ZEROIFNULL(INV.FACT_SHR) AS FACT_SHR
    , ZEROIFNULL(INV.RSVR_QTY) AS RSVR_QTY
    , ZEROIFNULL(INV.QUAL_INSP_QTY) AS QUAL_INSP_QTY
    , ZEROIFNULL(INV.BLOCKED_STK_QTY) AS BLOCKED_STK_QTY
    , ZEROIFNULL(INV.RSTR_QTY) AS RSTR_QTY
    , ZEROIFNULL(INV.STK_RET_QTY) AS STK_RET_QTY
    , ZEROIFNULL(INV.SAFE_STK_QTY) AS SAFE_STK_QTY
    , ZEROIFNULL(INV.COMMIT_ON_HAND_QTY) AS COMMIT_ON_HAND_QTY
    , ZEROIFNULL(INV.COMMIT_IN_TRANS_QTY) AS COMMIT_IN_TRANS_QTY
    , ZEROIFNULL(INV.PAST_DUE_QTY) AS PAST_DUE_QTY
    , ZEROIFNULL(INV.DELAYED_QTY) AS DELAYED_QTY
    , ZEROIFNULL(INV.TOT_QTY) - ZEROIFNULL(INV.BLOCKED_STK_QTY) - ZEROIFNULL(INV.QUAL_INSP_QTY) - ZEROIFNULL(INV.RSTR_QTY) + ZEROIFNULL(INV.STK_RET_QTY) AS UNRSTR_QTY
    , SUM(CASE WHEN INV.DAY_DT / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_1
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 1) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_2
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 2) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_3
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 3) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_4
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 4) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_5
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 5) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_6
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 6) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_7
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 7) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_8
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 8) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_9
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 9) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_10
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 10) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_11
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 11) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_12
    , CASE
        WHEN ATP_QTY > 0 AND (FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 + FORC_SKU_QTY_8 + FORC_SKU_QTY_9 + FORC_SKU_QTY_10 + FORC_SKU_QTY_11 + FORC_SKU_QTY_12) <= 0
            THEN -1
        WHEN ATP_QTY <= 0 AND (FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 + FORC_SKU_QTY_8 + FORC_SKU_QTY_9 + FORC_SKU_QTY_10 + FORC_SKU_QTY_11 + FORC_SKU_QTY_12) <= 0
            THEN -2
        WHEN ATP_QTY <= 0
            THEN 0
        WHEN (FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 + FORC_SKU_QTY_8 + FORC_SKU_QTY_9 + FORC_SKU_QTY_10 + FORC_SKU_QTY_11 + FORC_SKU_QTY_12) <= ATP_QTY
            THEN 360
        WHEN (FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 + FORC_SKU_QTY_8 + FORC_SKU_QTY_9 + FORC_SKU_QTY_10 + FORC_SKU_QTY_11) <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4 - FORC_SKU_QTY_5 - FORC_SKU_QTY_6 - FORC_SKU_QTY_7 - FORC_SKU_QTY_8 - FORC_SKU_QTY_9 - FORC_SKU_QTY_10 - FORC_SKU_QTY_11) / NULLIFZERO(FORC_SKU_QTY_12) * 30) + 330
        WHEN (FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 + FORC_SKU_QTY_8 + FORC_SKU_QTY_9 + FORC_SKU_QTY_10) <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4 - FORC_SKU_QTY_5 - FORC_SKU_QTY_6 - FORC_SKU_QTY_7 - FORC_SKU_QTY_8 - FORC_SKU_QTY_9 - FORC_SKU_QTY_10) / NULLIFZERO(FORC_SKU_QTY_11) * 30) + 300
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 + FORC_SKU_QTY_8 + FORC_SKU_QTY_9 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4 - FORC_SKU_QTY_5 - FORC_SKU_QTY_6 - FORC_SKU_QTY_7 - FORC_SKU_QTY_8 - FORC_SKU_QTY_9) / NULLIFZERO(FORC_SKU_QTY_10) * 30) + 270
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 + FORC_SKU_QTY_8 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4 - FORC_SKU_QTY_5 - FORC_SKU_QTY_6 - FORC_SKU_QTY_7 - FORC_SKU_QTY_8) / NULLIFZERO(FORC_SKU_QTY_9) * 30) + 240
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4 - FORC_SKU_QTY_5 - FORC_SKU_QTY_6 - FORC_SKU_QTY_7) / NULLIFZERO(FORC_SKU_QTY_8) * 30) + 210
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4 - FORC_SKU_QTY_5 - FORC_SKU_QTY_6) / NULLIFZERO(FORC_SKU_QTY_7) * 30) + 180
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4 - FORC_SKU_QTY_5) / NULLIFZERO(FORC_SKU_QTY_6) * 30) + 150
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4) / NULLIFZERO(FORC_SKU_QTY_5) * 30) + 120
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3) / NULLIFZERO(FORC_SKU_QTY_4) * 30) + 90
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2) / NULLIFZERO(FORC_SKU_QTY_3) * 30) + 60
        WHEN FORC_SKU_QTY_1 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1) / NULLIFZERO(FORC_SKU_QTY_2) * 30) + 30
        ELSE ATP_QTY / NULLIFZERO(FORC_SKU_QTY_1) * 30
    END AS EST_DAYS_SUPPLY

FROM (
    SELECT
        I.FACILITY_ID
        , I.MATL_ID
        , I.DAY_DT
        , I.DEF_QTY
        , I.BACK_ORDER_QTY
        , I.NET_BACK_ORDER_QTY
        , I.COMMIT_QTY
        , I.UN_COMMIT_QTY
        , I.TOT_QTY
        , I.AVAIL_TO_PROM_QTY
        , I.STO_INBOUND_QTY
        , I.IN_TRANS_QTY
        , I.STO_OUTBOUND_QTY
        , I.IN_PROS_TO_CUST_QTY
        , I.OPEN_FACT_UNIT_QTY
        , I.FACT_SHR
        , I.RSVR_QTY
        , I.QUAL_INSP_QTY
        , I.BLOCKED_STK_QTY
        , I.RSTR_QTY
        , I.STK_RET_QTY
        , I.SAFE_STK_QTY
        , I.COMMIT_ON_HAND_QTY
        , I.COMMIT_IN_TRANS_QTY
        , I.PAST_DUE_QTY
        , I.DELAYED_QTY
        , I.INV_QTY_UOM
    FROM GDYR_VWS.NAT_INV_MTH_END I
        
        INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
            ON M.MATL_ID = I.MATL_ID
            AND M.PBU_NBR IN ('01', '03')
            AND M.EXT_MATL_GRP_ID = 'TIRE'
        
        INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
            ON F.FACILITY_ID = I.FACILITY_ID
            AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
            AND F.DISTR_CHAN_CD = '81'
    
    WHERE
        I.DAY_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND ADD_MONTHS(CURRENT_DATE-1, -1)
        
    UNION
    
    SELECT
        I.FACILITY_ID
        , I.MATL_ID
        , I.DAY_DT
        , I.DEF_QTY
        , I.BACK_ORDER_QTY
        , I.NET_BACK_ORDER_QTY
        , I.COMMIT_QTY
        , I.UN_COMMIT_QTY
        , I.TOT_QTY
        , I.AVAIL_TO_PROM_QTY
        , I.STO_INBOUND_QTY
        , I.IN_TRANS_QTY
        , I.STO_OUTBOUND_QTY
        , I.IN_PROS_TO_CUST_QTY
        , I.OPEN_FACT_UNIT_QTY
        , I.FACT_SHR
        , I.RSVR_QTY
        , I.QUAL_INSP_QTY
        , I.BLOCKED_STK_QTY
        , I.RSTR_QTY
        , I.STK_RET_QTY
        , I.SAFE_STK_QTY
        , I.COMMIT_ON_HAND_QTY
        , I.COMMIT_IN_TRANS_QTY
        , I.PAST_DUE_QTY
        , I.DELAYED_QTY
        , I.INV_QTY_UOM
    FROM GDYR_VWS.NAT_INV_CURR I
    
        INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
            ON M.MATL_ID = I.MATL_ID
            AND M.PBU_NBR IN ('01', '03')
            AND M.EXT_MATL_GRP_ID = 'TIRE'
        
        INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
            ON F.FACILITY_ID = I.FACILITY_ID
            AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
            AND F.DISTR_CHAN_CD = '81'
    ) INV

    INNER JOIN (
            SELECT
                MONTH_DT
                , MONTH_DT + 14 AS IDES_OF_MTH
                , ADD_MONTHS(MONTH_DT, 1)-1 AS MONTH_END_DT
            FROM GDYR_BI_VWS.GDYR_CAL
            WHERE
                DAY_DATE BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND ADD_MONTHS(CURRENT_DATE-1, -1)
            GROUP BY
                MONTH_DT
                , IDES_OF_MTH
                , MONTH_END_DT
            UNION
            SELECT
                MONTH_DT AS MONTH_DT
                , MONTH_DT + 14 AS IDES_OF_MTH
                , DAY_DATE AS MONTH_END_DT
            FROM GDYR_BI_VWS.GDYR_CAL
            WHERE
                DAY_DATE = CURRENT_DATE-1
            ) CAL
        ON CAL.MONTH_END_DT = INV.DAY_DT

    LEFT OUTER JOIN GDYR_VWS.SKU_FORC SF
        ON CAL.IDES_OF_MTH BETWEEN SF.EFF_DT AND SF.EXP_DT
        AND SF.FACILITY_ID = INV.FACILITY_ID
        AND SF.MATL_ID = INV.MATL_ID
        AND SF.SBU_ID = 2

WHERE
    INV.MATL_ID LIKE '%000172824'
    
GROUP BY
    INV.MATL_ID
    , INV.FACILITY_ID
    , CAL.MONTH_DT
    , INV.INV_QTY_UOM
    , DEF_QTY
    , BACK_ORDER_QTY
    , NET_BACK_ORDER_QTY
    , COMMIT_QTY
    , UN_COMMIT_QTY
    , TOT_QTY
    , ATP_QTY
    , STO_INBOUND_QTY
    , IN_TRANS_QTY
    , STO_OUTBOUND_QTY
    , IN_PROS_TO_CUST_QTY
    , OPEN_FACT_UNIT_QTY
    , FACT_SHR
    , RSVR_QTY
    , QUAL_INSP_QTY
    , BLOCKED_STK_QTY
    , RSTR_QTY
    , STK_RET_QTY
    , SAFE_STK_QTY
    , COMMIT_ON_HAND_QTY
    , COMMIT_IN_TRANS_QTY
    , PAST_DUE_QTY
    , DELAYED_QTY
    , UNRSTR_QTY