SELECT
    Q.MATL_ID
    , Q.MONTH_DT
    , Q.INV_QTY_UOM
    , SUM(ZEROIFNULL(Q.TOT_QTY) + ZEROIFNULL(Q.IN_TRANS_QTY)) AS GROSS_INV
    , SUM(CASE WHEN Q.FACILITY_ID LIKE 'N5%' THEN Q.TOT_QTY ELSE 0 END) AS FACT_END_INV
    , SUM(CASE WHEN Q.FACILITY_ID IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.TOT_QTY + Q.IN_TRANS_QTY ELSE 0 END) AS LC_END_INV
    , SUM(CASE WHEN Q.FACILITY_ID NOT LIKE 'N5%' AND Q.FACILITY_ID NOT IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.TOT_QTY + Q.IN_TRANS_QTY ELSE 0 END) AS OTHER_END_INV

    , SUM(Q.TOT_QTY + Q.IN_TRANS_QTY) AS TOT_END_INV

    , SUM(CASE WHEN Q.FACILITY_ID = 'N602' THEN Q.TOT_QTY + Q.IN_TRANS_QTY ELSE 0 END) AS N602_END_INV
    , SUM(CASE WHEN Q.FACILITY_ID = 'N623' THEN Q.TOT_QTY + Q.IN_TRANS_QTY ELSE 0 END) AS N623_END_INV
    , SUM(CASE WHEN Q.FACILITY_ID = 'N636' THEN Q.TOT_QTY + Q.IN_TRANS_QTY ELSE 0 END) AS N636_END_INV
    , SUM(CASE WHEN Q.FACILITY_ID = 'N637' THEN Q.TOT_QTY + Q.IN_TRANS_QTY ELSE 0 END) AS N637_END_INV
    , SUM(CASE WHEN Q.FACILITY_ID = 'N639' THEN Q.TOT_QTY + Q.IN_TRANS_QTY ELSE 0 END) AS N639_END_INV
    , SUM(CASE WHEN Q.FACILITY_ID = 'N699' THEN Q.TOT_QTY + Q.IN_TRANS_QTY ELSE 0 END) AS N699_END_INV
    , SUM(CASE WHEN Q.FACILITY_ID = 'N6D3' THEN Q.TOT_QTY + Q.IN_TRANS_QTY ELSE 0 END) AS N6D3_END_INV

    , MAX(CASE WHEN Q.FACILITY_ID = 'N602' THEN Q.EST_DAYS_SUPPLY ELSE 0 END) AS N602_EST_DSI
    , MAX(CASE WHEN Q.FACILITY_ID = 'N623' THEN Q.EST_DAYS_SUPPLY ELSE 0 END) AS N623_EST_DSI
    , MAX(CASE WHEN Q.FACILITY_ID = 'N636' THEN Q.EST_DAYS_SUPPLY ELSE 0 END) AS N636_EST_DSI
    , MAX(CASE WHEN Q.FACILITY_ID = 'N637' THEN Q.EST_DAYS_SUPPLY ELSE 0 END) AS N637_EST_DSI
    , MAX(CASE WHEN Q.FACILITY_ID = 'N639' THEN Q.EST_DAYS_SUPPLY ELSE 0 END) AS N639_EST_DSI
    , MAX(CASE WHEN Q.FACILITY_ID = 'N699' THEN Q.EST_DAYS_SUPPLY ELSE 0 END) AS N699_EST_DSI
    , MAX(CASE WHEN Q.FACILITY_ID = 'N6D3' THEN Q.EST_DAYS_SUPPLY ELSE 0 END) AS N6D3_EST_DSI


    , SUM(CASE WHEN Q.FACILITY_ID IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.ATP_QTY ELSE 0 END) AS LC_ATP_INV_QTY
    , SUM(CASE WHEN Q.FACILITY_ID IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_1 ELSE 0 END) AS LC_FORC_QTY_1
    , SUM(CASE WHEN Q.FACILITY_ID IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_2 ELSE 0 END) AS LC_FORC_QTY_2
    , SUM(CASE WHEN Q.FACILITY_ID IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_3 ELSE 0 END) AS LC_FORC_QTY_3
    , SUM(CASE WHEN Q.FACILITY_ID IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_4 ELSE 0 END) AS LC_FORC_QTY_4
    , SUM(CASE WHEN Q.FACILITY_ID IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_5 ELSE 0 END) AS LC_FORC_QTY_5
    , SUM(CASE WHEN Q.FACILITY_ID IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_6 ELSE 0 END) AS LC_FORC_QTY_6
    , SUM(CASE WHEN Q.FACILITY_ID IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_7 ELSE 0 END) AS LC_FORC_QTY_7
    , SUM(CASE WHEN Q.FACILITY_ID IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_8 ELSE 0 END) AS LC_FORC_QTY_8
    , SUM(CASE WHEN Q.FACILITY_ID IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_9 ELSE 0 END) AS LC_FORC_QTY_9
    , SUM(CASE WHEN Q.FACILITY_ID IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_10 ELSE 0 END) AS LC_FORC_QTY_10
    , SUM(CASE WHEN Q.FACILITY_ID IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_11 ELSE 0 END) AS LC_FORC_QTY_11
    , SUM(CASE WHEN Q.FACILITY_ID IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_12 ELSE 0 END) AS LC_FORC_QTY_12
    , CASE
        WHEN LC_ATP_INV_QTY > 0 AND (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5 + LC_FORC_QTY_6 + LC_FORC_QTY_7 + LC_FORC_QTY_8 + LC_FORC_QTY_9 + LC_FORC_QTY_10 + LC_FORC_QTY_11 + LC_FORC_QTY_12) <= 0
            THEN -1
        WHEN LC_ATP_INV_QTY <= 0 AND (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5 + LC_FORC_QTY_6 + LC_FORC_QTY_7 + LC_FORC_QTY_8 + LC_FORC_QTY_9 + LC_FORC_QTY_10 + LC_FORC_QTY_11 + LC_FORC_QTY_12) <= 0
            THEN -2
        WHEN LC_ATP_INV_QTY <= 0
            THEN 0
        WHEN (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5 + LC_FORC_QTY_6 + LC_FORC_QTY_7 + LC_FORC_QTY_8 + LC_FORC_QTY_9 + LC_FORC_QTY_10 + LC_FORC_QTY_11 + LC_FORC_QTY_12) <= LC_ATP_INV_QTY
            THEN 360
        WHEN (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5 + LC_FORC_QTY_6 + LC_FORC_QTY_7 + LC_FORC_QTY_8 + LC_FORC_QTY_9 + LC_FORC_QTY_10 + LC_FORC_QTY_11) <= LC_ATP_INV_QTY
            THEN 330 + (30 * (LC_ATP_INV_QTY - (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5 + LC_FORC_QTY_6 + LC_FORC_QTY_7 + LC_FORC_QTY_8 + LC_FORC_QTY_9 + LC_FORC_QTY_10 + LC_FORC_QTY_11)) / NULLIFZERO(LC_FORC_QTY_12))
        WHEN (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5 + LC_FORC_QTY_6 + LC_FORC_QTY_7 + LC_FORC_QTY_8 + LC_FORC_QTY_9 + LC_FORC_QTY_10) <= LC_ATP_INV_QTY
            THEN 300 + (30 * (LC_ATP_INV_QTY - (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5 + LC_FORC_QTY_6 + LC_FORC_QTY_7 + LC_FORC_QTY_8 + LC_FORC_QTY_9 + LC_FORC_QTY_10)) / NULLIFZERO(LC_FORC_QTY_11))
        WHEN (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5 + LC_FORC_QTY_6 + LC_FORC_QTY_7 + LC_FORC_QTY_8 + LC_FORC_QTY_9) <= LC_ATP_INV_QTY
            THEN 270 + (30 * (LC_ATP_INV_QTY - (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5 + LC_FORC_QTY_6 + LC_FORC_QTY_7 + LC_FORC_QTY_8 + LC_FORC_QTY_9)) / NULLIFZERO(LC_FORC_QTY_10))
        WHEN (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5 + LC_FORC_QTY_6 + LC_FORC_QTY_7 + LC_FORC_QTY_8) <= LC_ATP_INV_QTY
            THEN 240 + (30 * (LC_ATP_INV_QTY - (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5 + LC_FORC_QTY_6 + LC_FORC_QTY_7 + LC_FORC_QTY_8)) / NULLIFZERO(LC_FORC_QTY_9))
        WHEN (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5 + LC_FORC_QTY_6 + LC_FORC_QTY_7) <= LC_ATP_INV_QTY
            THEN 210 + (30 * (LC_ATP_INV_QTY - (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5 + LC_FORC_QTY_6 + LC_FORC_QTY_7)) / NULLIFZERO(LC_FORC_QTY_8))
        WHEN (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5 + LC_FORC_QTY_6) <= LC_ATP_INV_QTY
            THEN 180 + (30 * (LC_ATP_INV_QTY - (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5 + LC_FORC_QTY_6)) / NULLIFZERO(LC_FORC_QTY_7))
        WHEN (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5) <= LC_ATP_INV_QTY
            THEN 150 + (30 * (LC_ATP_INV_QTY - (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4 + LC_FORC_QTY_5)) / NULLIFZERO(LC_FORC_QTY_6))
        WHEN (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4) <= LC_ATP_INV_QTY
            THEN 120 + (30 * (LC_ATP_INV_QTY - (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3 + LC_FORC_QTY_4)) / NULLIFZERO(LC_FORC_QTY_5))
        WHEN (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3) <= LC_ATP_INV_QTY
            THEN 90 + (30 * (LC_ATP_INV_QTY - (LC_FORC_QTY_1 + LC_FORC_QTY_2 + LC_FORC_QTY_3)) / NULLIFZERO(LC_FORC_QTY_4))
        WHEN (LC_FORC_QTY_1 + LC_FORC_QTY_2) <= LC_ATP_INV_QTY
            THEN 60 + (30 * (LC_ATP_INV_QTY - (LC_FORC_QTY_1 + LC_FORC_QTY_2)) / NULLIFZERO(LC_FORC_QTY_3))
        WHEN (LC_FORC_QTY_1) <= LC_ATP_INV_QTY
            THEN 30 + (30 * (LC_ATP_INV_QTY - LC_FORC_QTY_1) / NULLIFZERO(LC_FORC_QTY_2))
        ELSE 30 * (LC_ATP_INV_QTY / NULLIFZERO(LC_FORC_QTY_1))
        END AS LC_NETWORK_EST_DSI

    , SUM(CASE WHEN Q.FACILITY_ID LIKE 'N5%' THEN Q.ATP_QTY ELSE 0 END) AS FACT_ATP_INV_QTY
    , SUM(CASE WHEN Q.FACILITY_ID LIKE 'N5%' THEN Q.FORC_SKU_QTY_1 ELSE 0 END) AS FACT_FORC_QTY_1
    , SUM(CASE WHEN Q.FACILITY_ID LIKE 'N5%' THEN Q.FORC_SKU_QTY_2 ELSE 0 END) AS FACT_FORC_QTY_2
    , SUM(CASE WHEN Q.FACILITY_ID LIKE 'N5%' THEN Q.FORC_SKU_QTY_3 ELSE 0 END) AS FACT_FORC_QTY_3
    , SUM(CASE WHEN Q.FACILITY_ID LIKE 'N5%' THEN Q.FORC_SKU_QTY_4 ELSE 0 END) AS FACT_FORC_QTY_4
    , SUM(CASE WHEN Q.FACILITY_ID LIKE 'N5%' THEN Q.FORC_SKU_QTY_5 ELSE 0 END) AS FACT_FORC_QTY_5
    , SUM(CASE WHEN Q.FACILITY_ID LIKE 'N5%' THEN Q.FORC_SKU_QTY_6 ELSE 0 END) AS FACT_FORC_QTY_6
    , SUM(CASE WHEN Q.FACILITY_ID LIKE 'N5%' THEN Q.FORC_SKU_QTY_7 ELSE 0 END) AS FACT_FORC_QTY_7
    , SUM(CASE WHEN Q.FACILITY_ID LIKE 'N5%' THEN Q.FORC_SKU_QTY_8 ELSE 0 END) AS FACT_FORC_QTY_8
    , SUM(CASE WHEN Q.FACILITY_ID LIKE 'N5%' THEN Q.FORC_SKU_QTY_9 ELSE 0 END) AS FACT_FORC_QTY_9
    , SUM(CASE WHEN Q.FACILITY_ID LIKE 'N5%' THEN Q.FORC_SKU_QTY_10 ELSE 0 END) AS FACT_FORC_QTY_10
    , SUM(CASE WHEN Q.FACILITY_ID LIKE 'N5%' THEN Q.FORC_SKU_QTY_11 ELSE 0 END) AS FACT_FORC_QTY_11
    , SUM(CASE WHEN Q.FACILITY_ID LIKE 'N5%' THEN Q.FORC_SKU_QTY_12 ELSE 0 END) AS FACT_FORC_QTY_12
    , CASE
        WHEN FACT_ATP_INV_QTY > 0 AND (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5 + FACT_FORC_QTY_6 + FACT_FORC_QTY_7 + FACT_FORC_QTY_8 + FACT_FORC_QTY_9 + FACT_FORC_QTY_10 + FACT_FORC_QTY_11 + FACT_FORC_QTY_12) <= 0
            THEN -1
        WHEN FACT_ATP_INV_QTY <= 0 AND (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5 + FACT_FORC_QTY_6 + FACT_FORC_QTY_7 + FACT_FORC_QTY_8 + FACT_FORC_QTY_9 + FACT_FORC_QTY_10 + FACT_FORC_QTY_11 + FACT_FORC_QTY_12) <= 0
            THEN -2
        WHEN FACT_ATP_INV_QTY <= 0
            THEN 0
        WHEN (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5 + FACT_FORC_QTY_6 + FACT_FORC_QTY_7 + FACT_FORC_QTY_8 + FACT_FORC_QTY_9 + FACT_FORC_QTY_10 + FACT_FORC_QTY_11 + FACT_FORC_QTY_12) <= FACT_ATP_INV_QTY
            THEN 360
        WHEN (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5 + FACT_FORC_QTY_6 + FACT_FORC_QTY_7 + FACT_FORC_QTY_8 + FACT_FORC_QTY_9 + FACT_FORC_QTY_10 + FACT_FORC_QTY_11) <= FACT_ATP_INV_QTY
            THEN 330 + (30 * (FACT_ATP_INV_QTY - (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5 + FACT_FORC_QTY_6 + FACT_FORC_QTY_7 + FACT_FORC_QTY_8 + FACT_FORC_QTY_9 + FACT_FORC_QTY_10 + FACT_FORC_QTY_11)) / NULLIFZERO(FACT_FORC_QTY_12))
        WHEN (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5 + FACT_FORC_QTY_6 + FACT_FORC_QTY_7 + FACT_FORC_QTY_8 + FACT_FORC_QTY_9 + FACT_FORC_QTY_10) <= FACT_ATP_INV_QTY
            THEN 300 + (30 * (FACT_ATP_INV_QTY - (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5 + FACT_FORC_QTY_6 + FACT_FORC_QTY_7 + FACT_FORC_QTY_8 + FACT_FORC_QTY_9 + FACT_FORC_QTY_10)) / NULLIFZERO(FACT_FORC_QTY_11))
        WHEN (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5 + FACT_FORC_QTY_6 + FACT_FORC_QTY_7 + FACT_FORC_QTY_8 + FACT_FORC_QTY_9) <= FACT_ATP_INV_QTY
            THEN 270 + (30 * (FACT_ATP_INV_QTY - (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5 + FACT_FORC_QTY_6 + FACT_FORC_QTY_7 + FACT_FORC_QTY_8 + FACT_FORC_QTY_9)) / NULLIFZERO(FACT_FORC_QTY_10))
        WHEN (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5 + FACT_FORC_QTY_6 + FACT_FORC_QTY_7 + FACT_FORC_QTY_8) <= FACT_ATP_INV_QTY
            THEN 240 + (30 * (FACT_ATP_INV_QTY - (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5 + FACT_FORC_QTY_6 + FACT_FORC_QTY_7 + FACT_FORC_QTY_8)) / NULLIFZERO(FACT_FORC_QTY_9))
        WHEN (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5 + FACT_FORC_QTY_6 + FACT_FORC_QTY_7) <= FACT_ATP_INV_QTY
            THEN 210 + (30 * (FACT_ATP_INV_QTY - (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5 + FACT_FORC_QTY_6 + FACT_FORC_QTY_7)) / NULLIFZERO(FACT_FORC_QTY_8))
        WHEN (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5 + FACT_FORC_QTY_6) <= FACT_ATP_INV_QTY
            THEN 180 + (30 * (FACT_ATP_INV_QTY - (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5 + FACT_FORC_QTY_6)) / NULLIFZERO(FACT_FORC_QTY_7))
        WHEN (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5) <= FACT_ATP_INV_QTY
            THEN 150 + (30 * (FACT_ATP_INV_QTY - (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4 + FACT_FORC_QTY_5)) / NULLIFZERO(FACT_FORC_QTY_6))
        WHEN (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4) <= FACT_ATP_INV_QTY
            THEN 120 + (30 * (FACT_ATP_INV_QTY - (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3 + FACT_FORC_QTY_4)) / NULLIFZERO(FACT_FORC_QTY_5))
        WHEN (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3) <= FACT_ATP_INV_QTY
            THEN 90 + (30 * (FACT_ATP_INV_QTY - (FACT_FORC_QTY_1 + FACT_FORC_QTY_2 + FACT_FORC_QTY_3)) / NULLIFZERO(FACT_FORC_QTY_4))
        WHEN (FACT_FORC_QTY_1 + FACT_FORC_QTY_2) <= FACT_ATP_INV_QTY
            THEN 60 + (30 * (FACT_ATP_INV_QTY - (FACT_FORC_QTY_1 + FACT_FORC_QTY_2)) / NULLIFZERO(FACT_FORC_QTY_3))
        WHEN (FACT_FORC_QTY_1) <= FACT_ATP_INV_QTY
            THEN 30 + (30 * (FACT_ATP_INV_QTY - FACT_FORC_QTY_1) / NULLIFZERO(FACT_FORC_QTY_2))
        ELSE 30 * (FACT_ATP_INV_QTY / NULLIFZERO(FACT_FORC_QTY_1))
        END AS FACT_NETWORK_EST_DSI

    , SUM(CASE WHEN Q.FACILITY_ID NOT LIKE 'N5%' AND Q.FACILITY_ID NOT IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.ATP_QTY ELSE 0 END) AS OTHER_ATP_INV_QTY
    , SUM(CASE WHEN Q.FACILITY_ID NOT LIKE 'N5%' AND Q.FACILITY_ID NOT IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_1 ELSE 0 END) AS OTHER_FORC_QTY_1
    , SUM(CASE WHEN Q.FACILITY_ID NOT LIKE 'N5%' AND Q.FACILITY_ID NOT IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_2 ELSE 0 END) AS OTHER_FORC_QTY_2
    , SUM(CASE WHEN Q.FACILITY_ID NOT LIKE 'N5%' AND Q.FACILITY_ID NOT IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_3 ELSE 0 END) AS OTHER_FORC_QTY_3
    , SUM(CASE WHEN Q.FACILITY_ID NOT LIKE 'N5%' AND Q.FACILITY_ID NOT IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_4 ELSE 0 END) AS OTHER_FORC_QTY_4
    , SUM(CASE WHEN Q.FACILITY_ID NOT LIKE 'N5%' AND Q.FACILITY_ID NOT IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_5 ELSE 0 END) AS OTHER_FORC_QTY_5
    , SUM(CASE WHEN Q.FACILITY_ID NOT LIKE 'N5%' AND Q.FACILITY_ID NOT IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_6 ELSE 0 END) AS OTHER_FORC_QTY_6
    , SUM(CASE WHEN Q.FACILITY_ID NOT LIKE 'N5%' AND Q.FACILITY_ID NOT IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_7 ELSE 0 END) AS OTHER_FORC_QTY_7
    , SUM(CASE WHEN Q.FACILITY_ID NOT LIKE 'N5%' AND Q.FACILITY_ID NOT IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_8 ELSE 0 END) AS OTHER_FORC_QTY_8
    , SUM(CASE WHEN Q.FACILITY_ID NOT LIKE 'N5%' AND Q.FACILITY_ID NOT IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_9 ELSE 0 END) AS OTHER_FORC_QTY_9
    , SUM(CASE WHEN Q.FACILITY_ID NOT LIKE 'N5%' AND Q.FACILITY_ID NOT IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_10 ELSE 0 END) AS OTHER_FORC_QTY_10
    , SUM(CASE WHEN Q.FACILITY_ID NOT LIKE 'N5%' AND Q.FACILITY_ID NOT IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_11 ELSE 0 END) AS OTHER_FORC_QTY_11
    , SUM(CASE WHEN Q.FACILITY_ID NOT LIKE 'N5%' AND Q.FACILITY_ID NOT IN ('N602','N623','N636','N637','N639','N699','N6D3') THEN Q.FORC_SKU_QTY_12 ELSE 0 END) AS OTHER_FORC_QTY_12
    , CASE
        WHEN OTHER_ATP_INV_QTY > 0 AND (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5 + OTHER_FORC_QTY_6 + OTHER_FORC_QTY_7 + OTHER_FORC_QTY_8 + OTHER_FORC_QTY_9 + OTHER_FORC_QTY_10 + OTHER_FORC_QTY_11 + OTHER_FORC_QTY_12) <= 0
            THEN -1
        WHEN OTHER_ATP_INV_QTY <= 0 AND (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5 + OTHER_FORC_QTY_6 + OTHER_FORC_QTY_7 + OTHER_FORC_QTY_8 + OTHER_FORC_QTY_9 + OTHER_FORC_QTY_10 + OTHER_FORC_QTY_11 + OTHER_FORC_QTY_12) <= 0
            THEN -2
        WHEN OTHER_ATP_INV_QTY <= 0
            THEN 0
        WHEN (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5 + OTHER_FORC_QTY_6 + OTHER_FORC_QTY_7 + OTHER_FORC_QTY_8 + OTHER_FORC_QTY_9 + OTHER_FORC_QTY_10 + OTHER_FORC_QTY_11 + OTHER_FORC_QTY_12) <= OTHER_ATP_INV_QTY
            THEN 360
        WHEN (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5 + OTHER_FORC_QTY_6 + OTHER_FORC_QTY_7 + OTHER_FORC_QTY_8 + OTHER_FORC_QTY_9 + OTHER_FORC_QTY_10 + OTHER_FORC_QTY_11) <= OTHER_ATP_INV_QTY
            THEN 330 + (30 * (OTHER_ATP_INV_QTY - (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5 + OTHER_FORC_QTY_6 + OTHER_FORC_QTY_7 + OTHER_FORC_QTY_8 + OTHER_FORC_QTY_9 + OTHER_FORC_QTY_10 + OTHER_FORC_QTY_11)) / NULLIFZERO(OTHER_FORC_QTY_12))
        WHEN (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5 + OTHER_FORC_QTY_6 + OTHER_FORC_QTY_7 + OTHER_FORC_QTY_8 + OTHER_FORC_QTY_9 + OTHER_FORC_QTY_10) <= OTHER_ATP_INV_QTY
            THEN 300 + (30 * (OTHER_ATP_INV_QTY - (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5 + OTHER_FORC_QTY_6 + OTHER_FORC_QTY_7 + OTHER_FORC_QTY_8 + OTHER_FORC_QTY_9 + OTHER_FORC_QTY_10)) / NULLIFZERO(OTHER_FORC_QTY_11))
        WHEN (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5 + OTHER_FORC_QTY_6 + OTHER_FORC_QTY_7 + OTHER_FORC_QTY_8 + OTHER_FORC_QTY_9) <= OTHER_ATP_INV_QTY
            THEN 270 + (30 * (OTHER_ATP_INV_QTY - (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5 + OTHER_FORC_QTY_6 + OTHER_FORC_QTY_7 + OTHER_FORC_QTY_8 + OTHER_FORC_QTY_9)) / NULLIFZERO(OTHER_FORC_QTY_10))
        WHEN (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5 + OTHER_FORC_QTY_6 + OTHER_FORC_QTY_7 + OTHER_FORC_QTY_8) <= OTHER_ATP_INV_QTY
            THEN 240 + (30 * (OTHER_ATP_INV_QTY - (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5 + OTHER_FORC_QTY_6 + OTHER_FORC_QTY_7 + OTHER_FORC_QTY_8)) / NULLIFZERO(OTHER_FORC_QTY_9))
        WHEN (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5 + OTHER_FORC_QTY_6 + OTHER_FORC_QTY_7) <= OTHER_ATP_INV_QTY
            THEN 210 + (30 * (OTHER_ATP_INV_QTY - (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5 + OTHER_FORC_QTY_6 + OTHER_FORC_QTY_7)) / NULLIFZERO(OTHER_FORC_QTY_8))
        WHEN (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5 + OTHER_FORC_QTY_6) <= OTHER_ATP_INV_QTY
            THEN 180 + (30 * (OTHER_ATP_INV_QTY - (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5 + OTHER_FORC_QTY_6)) / NULLIFZERO(OTHER_FORC_QTY_7))
        WHEN (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5) <= OTHER_ATP_INV_QTY
            THEN 150 + (30 * (OTHER_ATP_INV_QTY - (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4 + OTHER_FORC_QTY_5)) / NULLIFZERO(OTHER_FORC_QTY_6))
        WHEN (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4) <= OTHER_ATP_INV_QTY
            THEN 120 + (30 * (OTHER_ATP_INV_QTY - (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3 + OTHER_FORC_QTY_4)) / NULLIFZERO(OTHER_FORC_QTY_5))
        WHEN (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3) <= OTHER_ATP_INV_QTY
            THEN 90 + (30 * (OTHER_ATP_INV_QTY - (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2 + OTHER_FORC_QTY_3)) / NULLIFZERO(OTHER_FORC_QTY_4))
        WHEN (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2) <= OTHER_ATP_INV_QTY
            THEN 60 + (30 * (OTHER_ATP_INV_QTY - (OTHER_FORC_QTY_1 + OTHER_FORC_QTY_2)) / NULLIFZERO(OTHER_FORC_QTY_3))
        WHEN (OTHER_FORC_QTY_1) <= OTHER_ATP_INV_QTY
            THEN 30 + (30 * (OTHER_ATP_INV_QTY - OTHER_FORC_QTY_1) / NULLIFZERO(OTHER_FORC_QTY_2))
        ELSE 30 * (OTHER_ATP_INV_QTY / NULLIFZERO(OTHER_FORC_QTY_1))
        END AS OTHER_NETWORK_EST_DSI

FROM (

SELECT
    INV.MATL_ID
    , INV.FACILITY_ID
    , INV.DAY_DT AS MONTH_DT
    , INV.INV_QTY_UOM
    , ZEROIFNULL(INV.DEF_QTY) AS DEF_QTY
    , ZEROIFNULL(INV.BACK_ORDER_QTY) AS BACK_ORDER_QTY
    , ZEROIFNULL(INV.NET_BACK_ORDER_QTY) AS NET_BACK_ORDER_QTY
    , ZEROIFNULL(INV.COMMIT_QTY) AS COMMIT_QTY
    , ZEROIFNULL(INV.UN_COMMIT_QTY) AS UN_COMMIT_QTY
    , ZEROIFNULL(INV.TOT_QTY) AS TOT_QTY
    , ZEROIFNULL(INV.AVAIL_TO_PROM_QTY) AS ATP_QTY
    , ZEROIFNULL(INV.STO_INBOUND_QTY) AS STO_INBOUND_QTY
    , ZEROIFNULL(INV.IN_TRANS_QTY) AS IN_TRANS_QTY
    , ZEROIFNULL(INV.STO_OUTBOUND_QTY) AS STO_OUTBOUND_QTY
    , ZEROIFNULL(INV.IN_PROS_TO_CUST_QTY) AS IN_PROS_TO_CUST_QTY
    , ZEROIFNULL(INV.OPEN_FACT_UNIT_QTY) AS OPEN_FACT_UNIT_QTY
    , ZEROIFNULL(INV.FACT_SHR) AS FACT_SHR
    , ZEROIFNULL(INV.RSVR_QTY) AS RSVR_QTY
    , ZEROIFNULL(INV.QUAL_INSP_QTY) AS QUAL_INSP_QTY
    , ZEROIFNULL(INV.BLOCKED_STK_QTY) AS BLOCKED_STK_QTY
    , ZEROIFNULL(INV.RSTR_QTY) AS RSTR_QTY
    , ZEROIFNULL(INV.STK_RET_QTY) AS STK_RET_QTY
    , ZEROIFNULL(INV.SAFE_STK_QTY) AS SAFE_STK_QTY
    , ZEROIFNULL(INV.COMMIT_ON_HAND_QTY) AS COMMIT_ON_HAND_QTY
    , ZEROIFNULL(INV.COMMIT_IN_TRANS_QTY) AS COMMIT_IN_TRANS_QTY
    , ZEROIFNULL(INV.PAST_DUE_QTY) AS PAST_DUE_QTY
    , ZEROIFNULL(INV.DELAYED_QTY) AS DELAYED_QTY
    , ZEROIFNULL(INV.TOT_QTY) - ZEROIFNULL(INV.BLOCKED_STK_QTY) - ZEROIFNULL(INV.QUAL_INSP_QTY) - ZEROIFNULL(INV.RSTR_QTY) + ZEROIFNULL(INV.STK_RET_QTY) AS UNRSTR_QTY
    , SUM(CASE WHEN INV.DAY_DT / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_1
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 1) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_2
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 2) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_3
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 3) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_4
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 4) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_5
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 5) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_6
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 6) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_7
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 7) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_8
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 8) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_9
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 9) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_10
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 10) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_11
    , SUM(CASE WHEN ADD_MONTHS(INV.DAY_DT, 11) / 100 = SF.FORC_MTH_DT / 100 THEN ZEROIFNULL(SF.FORC_SKU_QTY) ELSE 0 END) AS FORC_SKU_QTY_12
    , CASE
        WHEN ATP_QTY > 0 AND (FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 + FORC_SKU_QTY_8 + FORC_SKU_QTY_9 + FORC_SKU_QTY_10 + FORC_SKU_QTY_11 + FORC_SKU_QTY_12) <= 0
            THEN -1
        WHEN ATP_QTY <= 0 AND (FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 + FORC_SKU_QTY_8 + FORC_SKU_QTY_9 + FORC_SKU_QTY_10 + FORC_SKU_QTY_11 + FORC_SKU_QTY_12) <= 0
            THEN -2
        WHEN ATP_QTY <= 0
            THEN 0
        WHEN (FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 + FORC_SKU_QTY_8 + FORC_SKU_QTY_9 + FORC_SKU_QTY_10 + FORC_SKU_QTY_11 + FORC_SKU_QTY_12) <= ATP_QTY
            THEN 360
        WHEN (FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 + FORC_SKU_QTY_8 + FORC_SKU_QTY_9 + FORC_SKU_QTY_10 + FORC_SKU_QTY_11) <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4 - FORC_SKU_QTY_5 - FORC_SKU_QTY_6 - FORC_SKU_QTY_7 - FORC_SKU_QTY_8 - FORC_SKU_QTY_9 - FORC_SKU_QTY_10 - FORC_SKU_QTY_11) / NULLIFZERO(FORC_SKU_QTY_12) * 30) + 330
        WHEN (FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 + FORC_SKU_QTY_8 + FORC_SKU_QTY_9 + FORC_SKU_QTY_10) <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4 - FORC_SKU_QTY_5 - FORC_SKU_QTY_6 - FORC_SKU_QTY_7 - FORC_SKU_QTY_8 - FORC_SKU_QTY_9 - FORC_SKU_QTY_10) / NULLIFZERO(FORC_SKU_QTY_11) * 30) + 300
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 + FORC_SKU_QTY_8 + FORC_SKU_QTY_9 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4 - FORC_SKU_QTY_5 - FORC_SKU_QTY_6 - FORC_SKU_QTY_7 - FORC_SKU_QTY_8 - FORC_SKU_QTY_9) / NULLIFZERO(FORC_SKU_QTY_10) * 30) + 270
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 + FORC_SKU_QTY_8 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4 - FORC_SKU_QTY_5 - FORC_SKU_QTY_6 - FORC_SKU_QTY_7 - FORC_SKU_QTY_8) / NULLIFZERO(FORC_SKU_QTY_9) * 30) + 240
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 + FORC_SKU_QTY_7 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4 - FORC_SKU_QTY_5 - FORC_SKU_QTY_6 - FORC_SKU_QTY_7) / NULLIFZERO(FORC_SKU_QTY_8) * 30) + 210
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 + FORC_SKU_QTY_6 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4 - FORC_SKU_QTY_5 - FORC_SKU_QTY_6) / NULLIFZERO(FORC_SKU_QTY_7) * 30) + 180
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 + FORC_SKU_QTY_5 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4 - FORC_SKU_QTY_5) / NULLIFZERO(FORC_SKU_QTY_6) * 30) + 150
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 + FORC_SKU_QTY_4 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3 - FORC_SKU_QTY_4) / NULLIFZERO(FORC_SKU_QTY_5) * 30) + 120
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 + FORC_SKU_QTY_3 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2 - FORC_SKU_QTY_3) / NULLIFZERO(FORC_SKU_QTY_4) * 30) + 90
        WHEN FORC_SKU_QTY_1 + FORC_SKU_QTY_2 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1 - FORC_SKU_QTY_2) / NULLIFZERO(FORC_SKU_QTY_3) * 30) + 60
        WHEN FORC_SKU_QTY_1 <= ATP_QTY
            THEN((ATP_QTY - FORC_SKU_QTY_1) / NULLIFZERO(FORC_SKU_QTY_2) * 30) + 30
        ELSE ATP_QTY / NULLIFZERO(FORC_SKU_QTY_1) * 30
    END AS EST_DAYS_SUPPLY

FROM (
    SELECT
        I.FACILITY_ID
        , I.MATL_ID
        , CAL.MONTH_DT AS DAY_DT
        , CAL.MONTH_DT+15 AS IDES_OF_MTH
        , ADD_MONTHS(CAL.MONTH_DT,1)-1 AS END_OF_MTH
        , I.DEF_QTY
        , I.BACK_ORDER_QTY
        , I.NET_BACK_ORDER_QTY
        , I.COMMIT_QTY
        , I.UN_COMMIT_QTY
        , I.TOT_QTY
        , I.AVAIL_TO_PROM_QTY
        , I.STO_INBOUND_QTY
        , I.IN_TRANS_QTY
        , I.STO_OUTBOUND_QTY
        , I.IN_PROS_TO_CUST_QTY
        , I.OPEN_FACT_UNIT_QTY
        , I.FACT_SHR
        , I.RSVR_QTY
        , I.QUAL_INSP_QTY
        , I.BLOCKED_STK_QTY
        , I.RSTR_QTY
        , I.STK_RET_QTY
        , I.SAFE_STK_QTY
        , I.COMMIT_ON_HAND_QTY
        , I.COMMIT_IN_TRANS_QTY
        , I.PAST_DUE_QTY
        , I.DELAYED_QTY
        , I.INV_QTY_UOM

    FROM GDYR_VWS.NAT_INV_MTH_END I

        INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
            ON CAL.DAY_DATE = I.DAY_DT

        INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
            ON M.MATL_ID = I.MATL_ID
            AND M.PBU_NBR IN ('01', '03')
            AND M.EXT_MATL_GRP_ID = 'TIRE'

        INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
            ON F.FACILITY_ID = I.FACILITY_ID
            AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
            AND F.DISTR_CHAN_CD = '81'

    WHERE
        I.DAY_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND CURRENT_DATE-1

    UNION

    SELECT
        I.FACILITY_ID
        , I.MATL_ID
        , CAL.MONTH_DT AS DAY_DT
        , I.DAY_DT AS IDES_OF_MTH
        , ADD_MONTHS(CAL.MONTH_DT,1)-1 AS END_OF_MTH
        , I.DEF_QTY
        , I.BACK_ORDER_QTY
        , I.NET_BACK_ORDER_QTY
        , I.COMMIT_QTY
        , I.UN_COMMIT_QTY
        , I.TOT_QTY
        , I.AVAIL_TO_PROM_QTY
        , I.STO_INBOUND_QTY
        , I.IN_TRANS_QTY
        , I.STO_OUTBOUND_QTY
        , I.IN_PROS_TO_CUST_QTY
        , I.OPEN_FACT_UNIT_QTY
        , I.FACT_SHR
        , I.RSVR_QTY
        , I.QUAL_INSP_QTY
        , I.BLOCKED_STK_QTY
        , I.RSTR_QTY
        , I.STK_RET_QTY
        , I.SAFE_STK_QTY
        , I.COMMIT_ON_HAND_QTY
        , I.COMMIT_IN_TRANS_QTY
        , I.PAST_DUE_QTY
        , I.DELAYED_QTY
        , I.INV_QTY_UOM
    FROM GDYR_VWS.NAT_INV_CURR I

        INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
            ON CAL.DAY_DATE = I.DAY_DT

        INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
            ON M.MATL_ID = I.MATL_ID
            AND M.PBU_NBR IN ('01', '03')
            AND M.EXT_MATL_GRP_ID = 'TIRE'

        INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
            ON F.FACILITY_ID = I.FACILITY_ID
            AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
            AND F.DISTR_CHAN_CD = '81'
    ) INV

    LEFT OUTER JOIN GDYR_VWS.SKU_FORC SF
        ON INV.IDES_OF_MTH BETWEEN SF.EFF_DT AND SF.EXP_DT
        AND SF.FACILITY_ID = INV.FACILITY_ID
        AND SF.MATL_ID = INV.MATL_ID
        AND SF.SBU_ID = 2

GROUP BY
    INV.MATL_ID
    , INV.FACILITY_ID
    , INV.DAY_DT
    , INV.INV_QTY_UOM
    , DEF_QTY
    , BACK_ORDER_QTY
    , NET_BACK_ORDER_QTY
    , COMMIT_QTY
    , UN_COMMIT_QTY
    , TOT_QTY
    , ATP_QTY
    , STO_INBOUND_QTY
    , IN_TRANS_QTY
    , STO_OUTBOUND_QTY
    , IN_PROS_TO_CUST_QTY
    , OPEN_FACT_UNIT_QTY
    , FACT_SHR
    , RSVR_QTY
    , QUAL_INSP_QTY
    , BLOCKED_STK_QTY
    , RSTR_QTY
    , STK_RET_QTY
    , SAFE_STK_QTY
    , COMMIT_ON_HAND_QTY
    , COMMIT_IN_TRANS_QTY
    , PAST_DUE_QTY
    , DELAYED_QTY
    , UNRSTR_QTY
    
    ) Q

/*WHERE
    Q.MATL_ID LIKE '%000196149'*/
    
GROUP BY
    Q.MATL_ID
    , Q.MONTH_DT
    , Q.INV_QTY_UOM

ORDER BY
    Q.MATL_ID
    , Q.MONTH_DT
    , Q.INV_QTY_UOM
