SELECT
    A.PERD_BEGIN_MTH_DT AS EFF_DT
    , CAST(ADD_MONTHS(A.PERD_BEGIN_MTH_DT, 1) - 1 AS DATE) AS EXP_DT
    , A.MATL_ID
    , ZEROIFNULL(SUM(CASE WHEN SP.LAG_DESC = 0 THEN SP.OFFCL_SOP_SLS_PLN_QTY END)) / NULLIFZERO(CAST(CAL.TTL_DAYS_IN_MNTH AS DECIMAL(18,3))) AS DP_LAG0
    , ZEROIFNULL(SUM(CASE WHEN SP.LAG_DESC = 2 THEN SP.OFFCL_SOP_SLS_PLN_QTY END)) / NULLIFZERO(CAST(CAL.TTL_DAYS_IN_MNTH AS DECIMAL(18,3))) AS DP_LAG2

FROM NA_BI_VWS.CUST_SLS_PLN_SNAP A

WHERE
    A.LAG_DESC IN (0,2)
    AND A.PERD_BEGIN_MTH_DT BETWEEN CAST(EXTRACT(YEAR FROM (CURRENT_DATE-1)) || '-01-01' AS DATE)
            AND (CAST(EXTRACT(YEAR FROM (CURRENT_DATE-1))+1 || '-01-01' AS DATE) - 1)
    AND A.OFFCL_SOP_SLS_PLN_QTY > 0

GROUP BY
    EFF_DT
    , EXP_DT
    , A.MATL_ID
