SELECT
    F.POSTED_DT
    , PP.PROD_WK_DT
    , PP.MATL_ID
    , PP.FACILITY_ID
    , CAST(PP.PLN_QTY / 7.0 AS DECIMAL(15,3)) AS PLAN_QTY

FROM (

SELECT
    P.PLN_MATL_ID AS MATL_ID
    , P.FACILITY_ID
    , P.PROD_WK_DT
    , P.PLN_QTY

FROM GDYR_VWS.PROD_PLN P

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = P.PLN_MATL_ID

WHERE
    P.PROD_WK_DT - CAST(3 AS INTERVAL DAY(4)) BETWEEN P.EFF_DT AND P.EXP_DT
    AND P.PROD_WK_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND CURRENT_DATE-1
    AND P.SBU_ID = 2
    AND P.PROD_PLN_CD = '0'
    AND M.PBU_NBR IN ('01', '03')

UNION ALL

SELECT
    P.PLN_MATL_ID
    , P.FACILITY_ID
    , P.PROD_WK_DT
    , P.PLN_QTY

FROM GDYR_VWS.PROD_PLN P

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = P.PLN_MATL_ID

WHERE
    P.EXP_DT = CAST('5555-12-31' AS DATE)
    AND P.PROD_WK_DT BETWEEN CURRENT_DATE AND CURRENT_DATE+56
    AND P.SBU_ID = 2
    AND P.PROD_PLN_CD = '0'
    AND M.PBU_NBR IN ('01', '03')

UNION ALL

SELECT
    P.PLN_MATL_ID
    , P.FACILITY_ID
    , P.PROD_WK_DT
    , P.PLN_QTY

FROM GDYR_VWS.PROD_PLN P

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = P.PLN_MATL_ID

WHERE
    P.EXP_DT = CAST('5555-12-31' AS DATE)
    AND P.PROD_WK_DT BETWEEN CURRENT_DATE+57 AND ADD_MONTHS(CURRENT_DATE-1, 7) - EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE-1, 7))
    AND P.SBU_ID = 2
    AND P.PROD_PLN_CD = 'A'
    AND M.PBU_NBR IN ('01', '03')

    ) PP

    INNER JOIN GDYR_VWS.DMAN_GRP_PRD_FCTR F
        ON F.MEAS_DT = PP.PROD_WK_DT
        AND F.FNL_PERDY_ID = 'D'
        AND F.PERDY_ID = 'W'
        AND F.EXP_DT = CAST('5555-12-31' AS DATE)
