/*
PSI MONTHLY - 8 REASONS FOR INVENTORY MIN/MAX & TARGET

CREATED: 2014-05-01

QUERY FINDS THE 8 REASONS FOR INVENTORY MIN, MAX & TARGET INVENTORY FOR THE PREVIOUS 24 MONTHS AND
COPIES THE VALUES FROM THE CURRENT MONTH FOR THE NEXT 12 MONTHS.
*/

SELECT
    ICG.MATL_ID,
    ICG.INV_YEAR,
    ICG.INV_MONTH,
    AVERAGE(ICG.SUM_DEMAND_VAR + ICG.SUM_TRANS_VAR + ICG.SUM_SUPPLY_VAR + ICG.SUM_GEO) AS MIN_INV,
    AVERAGE(ICG.SUM_DEMAND_VAR + ICG.SUM_TRANS_VAR + ICG.SUM_SUPPLY_VAR + ICG.SUM_GEO + ICG.SUM_SHIP_LOT_SIZE +
             ICG.SUM_SHIP_INTERVAL + ICG.SUM_MFG_LOT_SIZE + ICG.SUM_INFO_CYCLE) AS TARGET_INV,
    AVERAGE(ICG.SUM_DEMAND_VAR + ICG.SUM_TRANS_VAR + ICG.SUM_SUPPLY_VAR + ICG.SUM_GEO + ICG.SUM_SHIP_LOT_SIZE +
             ICG.SUM_SHIP_INTERVAL + ICG.SUM_MFG_LOT_SIZE + ICG.SUM_INFO_CYCLE) + ZEROIFNULL(AVERAGE(ICA.MIN_INV_ADJ_QTY)) +
             ZEROIFNULL(AVERAGE(ICA.SHIP_STD_DEVN_MATL_ADJ_QTY)) + ZEROIFNULL(AVERAGE(ICA.MIN_PROD_RUN_INV_ADJ_QTY)) AS MAX_INV

FROM (
    SELECT
        IC.MATL_ID,
        IC.SRC_CRT_DT,
        EXTRACT (YEAR FROM IC.SRC_CRT_DT) AS INV_YEAR,
        EXTRACT (MONTH FROM IC.SRC_CRT_DT) AS INV_MONTH,
        SUM(IC.DMAN_VAR_CMPNT_INV_QTY) AS SUM_DEMAND_VAR,
        SUM(IC.TRANSP_VAR_CMPNT_INV_QTY) AS SUM_TRANS_VAR ,
        SUM(IC.SPLY_VAR_CMPNT_INV_QTY) AS SUM_SUPPLY_VAR,
        SUM(IC.GEO_CMPNT_INV_QTY) AS SUM_GEO,
        SUM(IC.SHIP_LOT_SZ_CMPNT_INV_QTY) AS SUM_SHIP_LOT_SIZE,
        SUM(IC.SHIP_INTVL_CMPNT_INV_QTY) AS SUM_SHIP_INTERVAL,
        SUM(IC.MFG_LOT_SZ_CMPNT_INV_QTY) AS SUM_MFG_LOT_SIZE,
        SUM(IC.INFO_CYCL_CMPNT_INV_QTY) AS SUM_INFO_CYCLE

    FROM NA_BI_VWS.INV_COMPONENT_CURR IC

        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MH
            ON MH.MATL_ID = IC.MATL_ID
            AND MH.PBU_NBR IN ('01','03')
    WHERE
        IC.SRC_CRT_DT BETWEEN CAST(SUBSTR(CAST(ADD_MONTHS((CURRENT_DATE-1), -24) AS CHAR(10)),1,7) || '-01' AS DATE)
            AND CAST( (CAST(SUBSTR(CAST((CURRENT_DATE-1) AS CHAR(10)),1,7) || '-01' AS DATE) - 1 ) AS DATE)
        -- AND IC.MATL_ID LIKE '%00019032'

    GROUP BY
        IC.MATL_ID,
        IC.SRC_CRT_DT,
        INV_YEAR,
        INV_MONTH
    )ICG

    LEFT OUTER JOIN NA_BI_VWS.INV_COMPONENT_ADJ_CURR ICA
        ON ICA.MATL_ID = ICG.MATL_ID
        AND ICA.SRC_CRT_DT = ICG.SRC_CRT_DT

GROUP BY
    ICG.MATL_ID,
    ICG.INV_YEAR,
    ICG.INV_MONTH

UNION ALL

SELECT
    Q.MATL_ID,
    CAL.CAL_YR,
    CAL.CAL_MTH,
    Q.MIN_INV,
    Q.TARGET_INV,
    Q.MAX_INV

FROM ( SELECT CAL_YR, CAL_MTH FROM GDYR_BI_VWS.GDYR_CAL WHERE DAY_DATE BETWEEN (CURRENT_DATE-1) AND ADD_MONTHS(CURRENT_DATE-1, 18) GROUP BY CAL_YR, CAL_MTH ) CAL

FULL OUTER JOIN (

SELECT
    ICG.MATL_ID,
    AVERAGE(ICG.SUM_DEMAND_VAR + ICG.SUM_TRANS_VAR + ICG.SUM_SUPPLY_VAR + ICG.SUM_GEO) AS MIN_INV,
    AVERAGE(ICG.SUM_DEMAND_VAR + ICG.SUM_TRANS_VAR + ICG.SUM_SUPPLY_VAR + ICG.SUM_GEO + ICG.SUM_SHIP_LOT_SIZE +
             ICG.SUM_SHIP_INTERVAL + ICG.SUM_MFG_LOT_SIZE + ICG.SUM_INFO_CYCLE) AS TARGET_INV,
    AVERAGE(ICG.SUM_DEMAND_VAR + ICG.SUM_TRANS_VAR + ICG.SUM_SUPPLY_VAR + ICG.SUM_GEO + ICG.SUM_SHIP_LOT_SIZE +
             ICG.SUM_SHIP_INTERVAL + ICG.SUM_MFG_LOT_SIZE + ICG.SUM_INFO_CYCLE) + ZEROIFNULL(AVERAGE(ICA.MIN_INV_ADJ_QTY)) +
             ZEROIFNULL(AVERAGE(ICA.SHIP_STD_DEVN_MATL_ADJ_QTY)) + ZEROIFNULL(AVERAGE(ICA.MIN_PROD_RUN_INV_ADJ_QTY)) AS MAX_INV

FROM (
        SELECT
            IC.MATL_ID,
            IC.SRC_CRT_DT,
            SUM(IC.DMAN_VAR_CMPNT_INV_QTY) AS SUM_DEMAND_VAR,
            SUM(IC.TRANSP_VAR_CMPNT_INV_QTY) AS SUM_TRANS_VAR ,
            SUM(IC.SPLY_VAR_CMPNT_INV_QTY) AS SUM_SUPPLY_VAR,
            SUM(IC.GEO_CMPNT_INV_QTY) AS SUM_GEO,
            SUM(IC.SHIP_LOT_SZ_CMPNT_INV_QTY) AS SUM_SHIP_LOT_SIZE,
            SUM(IC.SHIP_INTVL_CMPNT_INV_QTY) AS SUM_SHIP_INTERVAL,
            SUM(IC.MFG_LOT_SZ_CMPNT_INV_QTY) AS SUM_MFG_LOT_SIZE,
            SUM(IC.INFO_CYCL_CMPNT_INV_QTY) AS SUM_INFO_CYCLE

        FROM NA_BI_VWS.INV_COMPONENT_CURR IC

            INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MH
                ON MH.MATL_ID = IC.MATL_ID
                AND MH.PBU_NBR IN ('01','03')
        WHERE
            IC.SRC_CRT_DT >= CAST(SUBSTR(CAST((CURRENT_DATE-1) AS CHAR(10)),1,7) || '-01' AS DATE)

        GROUP BY
            IC.MATL_ID,
            IC.SRC_CRT_DT
    )ICG

    LEFT OUTER JOIN NA_BI_VWS.INV_COMPONENT_ADJ_CURR ICA
        ON ICA.MATL_ID = ICG.MATL_ID
        AND ICA.SRC_CRT_DT = ICG.SRC_CRT_DT

GROUP BY
    ICG.MATL_ID
    ) Q
    ON 1=1
