SELECT
    FM.FACILITY_ID
    , F.FACILITY_NAME
    , FM.MATL_ID
    , CAST(CASE FM.SPCL_PRCU_TYP_CD
        WHEN 'AA' THEN 'N501'
        WHEN 'AB' THEN 'N502'
        WHEN 'AC' THEN 'N503'
        WHEN 'AD' THEN 'N504'
        WHEN 'AE' THEN 'N505'
        WHEN 'AF' THEN 'N506'
        WHEN 'AH' THEN 'N508'
        WHEN 'AI' THEN 'N509'
        WHEN 'AJ' THEN 'N510'
        WHEN 'AM' THEN 'N513'
        WHEN 'AS' THEN 'N603'
        WHEN 'CA' THEN 'N5CA'
        WHEN 'CC' THEN 'N518'
        WHEN 'NR' THEN 'N638'
        WHEN 'S1' THEN 'N6BD'
        WHEN 'S2' THEN 'N6BE'
        WHEN 'S3' THEN 'N6BF'
        WHEN 'S4' THEN 'N6BS'
        WHEN 'S6' THEN 'N6J2'
        WHEN 'S7' THEN 'N6J3'
        WHEN 'S8' THEN 'N6J4'
        WHEN 'S9' THEN 'N6J7'
        WHEN 'SA' THEN 'N526'
        WHEN 'SC' THEN 'N6A1'
        WHEN 'SD' THEN 'N6A2'
        WHEN 'SE' THEN 'N6A3'
        WHEN 'SF' THEN 'N6A4'
        WHEN 'SG' THEN 'N6A6'
        WHEN 'SH' THEN 'N6A8'
        WHEN 'SJ' THEN 'N6AA'
        WHEN 'SM' THEN 'N6AE'
        WHEN 'SN' THEN 'N6AG'
        WHEN 'SO' THEN 'N6AH'
        WHEN 'SP' THEN 'N6AJ'
        WHEN 'SQ' THEN 'N6AK'
        WHEN 'SR' THEN 'N6AL'
        WHEN 'SS' THEN 'N6J8'
        WHEN 'ST' THEN 'N6AO'
        WHEN 'SU' THEN 'N6AQ'
        WHEN 'SV' THEN 'N6AR'
        WHEN 'SW' THEN 'N6AS'
        WHEN 'SX' THEN 'N6AT'
        WHEN 'SY' THEN 'N6AX'
        WHEN 'SZ' THEN 'N6BB'
        WHEN 'US' THEN 'N5US'
        WHEN 'WA' THEN 'N637'
        WHEN 'WD' THEN 'N6D3'
        WHEN 'WH' THEN 'N699'
        WHEN 'WL' THEN 'N607'
        ELSE COALESCE(FMX.FACILITY_ID, FM.SPCL_PRCU_TYP_CD, '')
        END AS CHAR(4)) AS SRC_FACILITY_ID
    , COALESCE(FN.FACILITY_NAME, '') AS SRC_FACILITY_NAME

FROM GDYR_VWS.FACILITY_MATL FM

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = FM.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = FM.MATL_ID
        AND M.PBU_NBR = '01'

    LEFT OUTER JOIN GDYR_VWS.FACILITY_MATL FMX
        ON FMX.MATL_ID = FM.MATL_ID
        AND FMX.ORIG_SYS_ID = FM.ORIG_SYS_ID
        AND FMX.EXP_DT = FM.EXP_DT
        AND FMX.MRP_TYPE_ID = 'X0'

    LEFT OUTER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FN
        ON FN.FACILITY_ID = SRC_FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

WHERE
    FM.ORIG_SYS_ID = 2
    AND FM.EXP_DT = CAST('5555-12-31' AS DATE)
    AND FM.MRP_TYPE_ID = 'XB'

GROUP BY
    FM.FACILITY_ID
    , F.FACILITY_NAME
    , FM.MATL_ID
    , SRC_FACILITY_ID
    , FN.FACILITY_NAME

