SELECT
    CAST('S&OP Official Forecast' AS VARCHAR(55)) AS VAL_TYPE
    , CAST(SP.DP_LAG_DESC AS VARCHAR(55)) AS DESCR
    , SP.PERD_BEGIN_MTH_DT AS MONTH_DT
    , SP.MATL_ID
    , SUM(ZEROIFNULL(SP.OFFCL_SOP_SLS_PLN_QTY)) AS QUANTITY

FROM NA_BI_VWS.CUST_SLS_PLN_SNAP SP
    
    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = SP.MATL_ID
        AND M.EXT_MATL_GRP_ID = 'TIRE'
        AND M.PBU_NBR IN ('01', '03')

WHERE
    SP.DP_LAG_DESC IN ('LAG 0', 'LAG 2')
    AND SP.PERD_BEGIN_MTH_DT BETWEEN (CURRENT_DATE-1) AND (CURRENT_DATE-1) + 180
    AND SP.SALES_ORG_CD IN ('N301', 'N302', 'N303', 'N311', 'N312', 'N313', 'N321', 'N322', 'N323')

GROUP BY
    VAL_TYPE
    , DESCR
    , SP.PERD_BEGIN_MTH_DT
    , SP.MATL_ID

UNION ALL

SELECT
    CAST('DP Forecast' AS VARCHAR(55)) AS VAL_TYPE
    , CAST(SP.LAG_DESC AS VARCHAR(55)) AS DESCR
    , SP.PERD_BEGIN_MTH_DT AS MONTH_DT
    , SP.MATL_ID
    , SUM(ZEROIFNULL(SP.OFFCL_SOP_SLS_PLN_QTY)) AS QUANTITY

FROM NA_BI_VWS.CUST_SLS_PLN_SNAP SP

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = SP.MATL_ID
        AND M.EXT_MATL_GRP_ID = 'TIRE'
        AND M.PBU_NBR IN ('01', '03')

WHERE
    SP.LAG_DESC IN ('0', '2')
    AND SP.PERD_BEGIN_MTH_DT BETWEEN (CURRENT_DATE-1) AND (CURRENT_DATE-1) + 180
    AND SP.SALES_ORG_CD IN ('N301', 'N302', 'N303', 'N311', 'N312', 'N313', 'N321', 'N322', 'N323')

GROUP BY
    VAL_TYPE
    , DESCR
    , SP.PERD_BEGIN_MTH_DT
    , SP.MATL_ID

UNION ALL

SELECT
    CAST('Billed Units' AS VARCHAR(55)) AS VAL_TYPE
    , CAST('Collectibles' AS VARCHAR(55)) AS DESCR
    , SA.BILL_REF_MTH_DT AS MONTH_DT
    , SA.MATL_NO
    , SUM(ZEROIFNULL(SA.COLLCT_SLS_GRP_AMT)) AS QUANTITY

FROM NA_VWS.SLS_AGG SA

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = SA.MATL_NO
        AND M.EXT_MATL_GRP_ID = 'TIRE'
        AND M.PBU_NBR IN ('01', '03')

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_CURR C
        ON C.SHIP_TO_CUST_ID = SA.LEGACY_SHIP_TO_CUST_NO
        AND C.SALES_ORG_CD IN ('N301', 'N302', 'N303', 'N311', 'N312', 'N313', 'N321', 'N322', 'N323')

WHERE
    SA.BILL_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND (CURRENT_DATE-1)

GROUP BY
    VAL_TYPE
    , DESCR
    , SA.BILL_REF_MTH_DT
    , SA.MATL_NO

UNION ALL

SELECT
    CAST('Billed Units' AS VARCHAR(55)) AS VAL_TYPE
    , CAST('Collectibles Std. Margin' AS VARCHAR(55)) AS DESCR
    , SA.BILL_REF_MTH_DT AS MONTH_DT
    , SA.MATL_NO
    , SUM(ZEROIFNULL(SA.COLLCT_STD_MRGN_GRP_AMT)) AS QUANTITY

FROM NA_VWS.SLS_AGG SA

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = SA.MATL_NO
        AND M.EXT_MATL_GRP_ID = 'TIRE'
        AND M.PBU_NBR IN ('01', '03')

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_CURR C
        ON C.SHIP_TO_CUST_ID = SA.LEGACY_SHIP_TO_CUST_NO
        AND C.SALES_ORG_CD IN ('N301', 'N302', 'N303', 'N311', 'N312', 'N313', 'N321', 'N322', 'N323')

WHERE
    SA.BILL_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND (CURRENT_DATE-1)

GROUP BY
    VAL_TYPE
    , DESCR
    , SA.BILL_REF_MTH_DT
    , SA.MATL_NO

UNION ALL

SELECT
    CAST('Billed Units' AS VARCHAR(55)) AS VAL_TYPE
    , CAST('Billed Units' AS VARCHAR(55)) AS DESCR
    , SA.BILL_REF_MTH_DT AS MONTH_DT
    , SA.MATL_NO
    , SUM(ZEROIFNULL(SA.SLS_QTY)) AS QUANTITY

FROM NA_VWS.SLS_AGG SA

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = SA.MATL_NO
        AND M.EXT_MATL_GRP_ID = 'TIRE'
        AND M.PBU_NBR IN ('01', '03')
        AND M.MATL_TYPE_ID IN ('PCTL', 'ACCT')

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_CURR C
        ON C.SHIP_TO_CUST_ID = SA.LEGACY_SHIP_TO_CUST_NO
        AND C.SALES_ORG_CD IN ('N301', 'N302', 'N303', 'N311', 'N312', 'N313', 'N321', 'N322', 'N323')

WHERE
    SA.BILL_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND (CURRENT_DATE-1)

GROUP BY
    VAL_TYPE
    , DESCR
    , SA.BILL_REF_MTH_DT
    , SA.MATL_NO

UNION ALL

SELECT
    CAST('Ordered Units' AS VARCHAR(55)) AS VAL_TYPE
    , CAST('Order Qty' AS VARCHAR(55)) AS DESCR
    , ODC.FRST_RDD - (EXTRACT(DAY FROM ODC.FRST_RDD) - 1) AS MONTH_DT
    , ODC.MATL_ID
    , SUM(ODC.ORDER_QTY) AS QUANTITY

FROM NA_BI_VWS.ORDER_DETAIL ODC

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = ODC.MATL_ID
        AND M.EXT_MATL_GRP_ID = 'TIRE'
        AND M.PBU_NBR IN ('01', '03')

WHERE
    ODC.ORDER_CAT_ID = 'C'
    AND ODC.RO_PO_TYPE_IND = 'N'
    AND ODC.FRST_RDD BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND (CURRENT_DATE+180)
    AND ODC.EXP_DT = DATE '5555-12-31'
    AND ODC.SALES_ORG_CD IN ('N301', 'N302', 'N303', 'N311', 'N312', 'N313', 'N321', 'N322', 'N323')

GROUP BY
    VAL_TYPE
    , DESCR
    , MONTH_DT
    , ODC.MATL_ID

UNION ALL

SELECT
    CAST('Ordered Units' AS VARCHAR(55)) AS VAL_TYPE
    , CAST('Reserve Order Qty' AS VARCHAR(55)) AS DESCR
    , ODC.FRST_RDD - (EXTRACT(DAY FROM ODC.FRST_RDD) - 1) AS MONTH_DT
    , ODC.MATL_ID
    , SUM(ODC.ORDER_QTY) AS QUANTITY

FROM NA_BI_VWS.ORDER_DETAIL ODC

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = ODC.MATL_ID
        AND M.EXT_MATL_GRP_ID = 'TIRE'
        AND M.PBU_NBR IN ('01', '03')

WHERE
    ODC.ORDER_CAT_ID = 'C'
    AND ODC.RO_PO_TYPE_IND = 'Y'
    AND ODC.FRST_RDD BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND (CURRENT_DATE+180)
    AND ODC.EXP_DT = DATE '5555-12-31'
    AND ODC.SALES_ORG_CD IN ('N301', 'N302', 'N303', 'N311', 'N312', 'N313', 'N321', 'N322', 'N323')

GROUP BY
    VAL_TYPE
    , DESCR
    , MONTH_DT
    , ODC.MATL_ID

UNION ALL

SELECT
    CAST('Ordered Units' AS VARCHAR(55)) AS VAL_TYPE
    , CAST('Confirmed Qty' AS VARCHAR(55)) AS DESCR
    , ODC.FRST_RDD - (EXTRACT(DAY FROM ODC.FRST_RDD) - 1) AS MONTH_DT
    , ODC.MATL_ID
    , SUM(ODC.CNFRM_QTY) AS QUANTITY

FROM NA_BI_VWS.ORDER_DETAIL ODC

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = ODC.MATL_ID
        AND M.EXT_MATL_GRP_ID = 'TIRE'
        AND M.PBU_NBR IN ('01', '03')

WHERE
    ODC.ORDER_CAT_ID = 'C'
    AND ODC.RO_PO_TYPE_IND = 'N'
    AND ODC.FRST_RDD BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND (CURRENT_DATE+180)
    AND ODC.EXP_DT = DATE '5555-12-31'
    AND ODC.SALES_ORG_CD IN ('N301', 'N302', 'N303', 'N311', 'N312', 'N313', 'N321', 'N322', 'N323')

GROUP BY
    VAL_TYPE
    , DESCR
    , MONTH_DT
    , ODC.MATL_ID

UNION ALL

SELECT
    CAST('Ordered Units' AS VARCHAR(55)) AS VAL_TYPE
    , CAST('Open Confirmed Qty' AS VARCHAR(55)) AS DESCR
    , ODC.PLN_DELIV_DT - (EXTRACT(DAY FROM ODC.PLN_DELIV_DT) - 1) AS MONTH_DT
    , ODC.MATL_ID
    , SUM(ZEROIFNULL(OOL.OPEN_CNFRM_QTY)) AS QUANTITY

FROM NA_BI_VWS.ORDER_DETAIL ODC

    INNER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL
        ON OOL.ORDER_FISCAL_YR = ODC.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = ODC.ORDER_ID
        AND OOL.ORDER_LINE_NBR = ODC.ORDER_LINE_NBR
        AND OOL.SCHED_LINE_NBR = ODC.SCHED_LINE_NBR
        AND OOL.OPEN_CNFRM_QTY > 0

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = ODC.MATL_ID
        AND M.EXT_MATL_GRP_ID = 'TIRE'
        AND M.PBU_NBR IN ('01', '03')

WHERE
    ODC.ORDER_CAT_ID = 'C'
    AND ODC.RO_PO_TYPE_IND = 'N'
    AND ODC.FRST_RDD BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND (CURRENT_DATE-1)+180
    AND ODC.EXP_DT = DATE '5555-12-31'
    AND ODC.SALES_ORG_CD IN ('N301', 'N302', 'N303', 'N311', 'N312', 'N313', 'N321', 'N322', 'N323')

GROUP BY
    VAL_TYPE
    , DESCR
    , MONTH_DT
    , ODC.MATL_ID
    
UNION ALL

SELECT
    CAST('Ordered Units' AS VARCHAR(55)) AS VAL_TYPE
    , CAST('Scheduling Agreement Qty' AS VARCHAR(55)) AS DESCR
    , SL.SCHD_LN_DELIV_DT - (EXTRACT(DAY FROM SL.SCHD_LN_DELIV_DT) - 1) AS MONTH_DT
    , SDI.MATL_ID
    , SUM(ZEROIFNULL(SDI.SLS_UNIT_CUM_ORD_QTY)) AS QUANTITY

FROM GDYR_BI_VWS.NAT_SLS_DOC_ITM_CURR SDI

    INNER JOIN GDYR_BI_VWS.NAT_SLS_DOC_CURR SD
        ON SD.FISCAL_YR = SDI.FISCAL_YR
        AND SD.SLS_DOC_ID = SDI.SLS_DOC_ID
        AND SD.SD_DOC_CTGY_CD = 'E'
        AND SD.SALES_ORG_CD IN ('N301', 'N302', 'N303', 'N311', 'N312', 'N313', 'N321', 'N322', 'N323')

    INNER JOIN GDYR_BI_VWS.NAT_SLS_DOC_SCHD_LN_CURR SL
        ON SL.FISCAL_YR = SDI.FISCAL_YR
        AND SL.SLS_DOC_ID = SDI.SLS_DOC_ID
        AND SL.SLS_DOC_ITM_ID = SDI.SLS_DOC_ITM_ID
        AND SL.SCHD_LN_ID = 1
        

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = SDI.MATL_ID
        AND M.EXT_MATL_GRP_ID = 'TIRE'
        AND M.PBU_NBR IN ('01', '03')

WHERE
    SDI.REJ_REAS_ID IS NULL

GROUP BY
    VAL_TYPE
    , DESCR
    , MONTH_DT
    , SDI.MATL_ID

UNION ALL

SELECT
    CAST('Delivered Units' AS VARCHAR(55)) AS VAL_TYPE
    , CAST('Actual Shipped Units' AS VARCHAR(55)) AS DESCR
    , DDC.ACTL_GOODS_ISS_DT - (EXTRACT(DAY FROM DDC.ACTL_GOODS_ISS_DT) - 1) AS MONTH_DT
    , DDC.MATL_ID
    , SUM(ZEROIFNULL(DDC.DELIV_QTY)) AS QUANTITY
    
FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

WHERE
    DDC.GOODS_ISS_IND = 'Y'
    AND DDC.ACTL_GOODS_ISS_DT IS NOT NULL
    AND DDC.ACTL_GOODS_ISS_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND (CURRENT_DATE-1)
    AND DDC.DELIV_CAT_ID = 'J'
    AND DDC.RETURN_IND = 'N'
    AND DDC.DELIV_QTY > 0
    AND DDC.SALES_ORG_CD IN ('N301', 'N302', 'N303', 'N311', 'N312', 'N313', 'N321', 'N322', 'N323')

GROUP BY
    VAL_TYPE
    , DESCR
    , MONTH_DT
    , DDC.MATL_ID


