SELECT
    FAC.FACILITY_ID,
    MATL.MATL_ID,
    CAL.DAY_DATE,
    FAC.MRP_TYPE_ID,
    FAC.SPCL_PRCU_TYP_CD

FROM GDYR_VWS.FACILITY_MATL FAC

    INNER JOIN GDYR_VWS.MATL MATL
        ON MTL.MATL_ID = FAC.MATL_ID

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE BETWEEN ( CURRENT_DATE - 480 ) AND CURRENT_DATE
        AND CAL.DAY_DATE BETWEEN FAC.EFF_DT AND FAC.EXP_DT
        AND CAL.DAY_DATE BETWEEN MATL.EFF_DT AND MATL.EXP_DT

WHERE
    FAC.MRP_TYPE_ID IN ( 'XB', 'X0' )
    AND MATL.PBU_NBR = '03'
    AND MATL.MKT_AREA_NBR IN ( '05', '14' )
    AND FAC.FACILITY_ID LIKE 'N5%'

ORDER BY
    MATL.MATL_ID,
    FAC.FACILITY_ID,
    CAL.DAY_DATE
;
    

/*SELECT M.FACILITY_ID,
    M.MATL_ID,
    C.DAY_DATE,
    M.MRP_TYPE_ID,
    M.SPCL_PRCU_TYP_CD -- (MAY NEED TO CONVERT TO 4 CHAR PLANT CODE?)
FROM GDYR_VWS.FACILITY_MATL M
INNER JOIN GDYR_VWS.MATL M1 ON M.MATL_ID = M1.MATL_ID,
    GDYR_BI_VWS.GDYR_CAL C
WHERE C.DAY_DATE BETWEEN DATE - 480
        AND DATE
    AND EXTRACT(DAY FROM C.DAY_DATE) = 1
    AND C.DAY_DATE BETWEEN M.EFF_DT
        AND M.EXP_DT
    AND C.DAY_DATE BETWEEN M1.EFF_DT
        AND M1.EXP_DT
    AND (
        M.MRP_TYPE_ID = 'XB'
        OR M.MRP_TYPE_ID = 'X0'
        )
    AND M1.PBU_NBR = '03'
    AND M1.MKT_AREA_NBR IN (
        '05',
        '14'
        )
    AND (
        M.FACILITY_ID LIKE 'N6%'
        OR M.FACILITY_ID LIKE 'N5%'
        )
ORDER BY 2,
    1,
    3*/