SELECT
    CDI.OBJ_CLS_CD
    , CDI.OBJ_VAL_ID
    , CDI.CHG_DOC_ID
    , CDI.SAP_TBL_NM
    , CDI.SAP_COL_NM
    , CDI.CHG_TBL_REC_ID
    , CDI.CHG_TYP_CD
    , CDI.DOC_ID
    , CDI.DOC_ITM_ID
    , CDI.TXT_CHG_IND
    , CDI.OLD_UNIT_QTY
    , CDI.NEW_UNIT_QTY
    , CDI.OLD_CRNCY_ID
    , CDI.NEW_CRNCY_ID
    , CDI.OLD_VAL_TXT
    , CDI.NEW_VAL_TXT

    --, CAST(CDI.OLD_VAL_TXT AS DATE FORMAT 'YYYYMMDD') AS OLD_ORDD_DT
    --, CAST(CDI.NEW_VAL_TXT AS DATE FORMAT 'YYYYMMDD') AS NEW_ORDD_DT

    , CDI.SRC_CRT_DT
    , CDI.SRC_CRT_TM
    , CDI.SRC_CRT_TS
    , CH.SRC_CRT_USR_ID
    , CH.SAP_TRANS_CD
    , CH.PLN_CHG_ID
    , CH.ACTL_CHG_DOC_ID
    , CH.PLN_CHG_IND
    , CH.CHG_TYP_CD
    , CH.LANG_ID
    , CH.VER_ID

FROM GDYR_BI_vWS.CHG_DOC_ITM CDI

    INNER JOIN GDYR_BI_VWS.CHG_DOC CH
        ON CH.ORIG_SYS_ID = CDI.ORIG_SYS_ID
        AND CH.OBJ_CLS_CD = CDI.OBJ_CLS_CD
        AND CH.OBJ_VAL_ID = CDI.OBJ_VAL_ID
        AND CH.CHG_DOC_ID = CDI.CHG_DOC_ID
        AND CH.SRC_CRT_DT = CDI.SRC_CRT_DT

WHERE
    CDI.ORIG_SYS_ID = 2
    AND CDI.OBJ_CLS_CD = 'VERKBELEG'

    AND CDI.SRC_CRT_DT >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1) || '-01-01' AS DATE)

    AND CDI.SAP_TBL_NM = 'VBAP'
    AND CDI.SAP_COL_NM = 'YYORDD'
    
    AND (CDI.DOC_ID, CDI.DOC_ITM_ID) IN (
        SELECT
            ORDER_ID
            , ORDER_LINE_NBR
        FROM NA_BI_VWS.ORDER_DETAIL
        WHERE
            EXP_DT = CAST('5555-12-31' AS DATE)
            AND ORDER_CAT_ID = 'C'
            AND CUST_GRP2_CD = 'TLB'
            AND FRST_RDD >= CAST('2015-01-01' AS DATE)
            AND CUST_RDD IS NOT NULL
            AND FRST_RDD > CUST_RDD
        GROUP BY 1, 2
    )
