-- FACILITY HIERARCHY FILTERED ON THE NAT SALES ORGS

SELECT
    FACILITY_ID
    , FACILITY_DESC
    , XTND_NAME
    , VAL_AREA_ID
    , INT_CUST_ID
    , VENDOR_CUST_ID
    , PURCH_ORG_ID
    , SALES_ORG_CD
    , DISTR_CHAN_CD
    , DIV_CD
    , CNTRY_ID
    , TERR_ID
    , DISTRICT_ID
    , CITY_ID
    , FACILITY_TYPE_ID
    , FACILITY_CAT_ID
    , FACILITY_ACTIV_IND

FROM GDYR_BI_VWS.FACILITY_CURR

WHERE
    ORIG_SYS_ID = 2
    AND LANG_ID = 'EN'
    AND SALES_ORG_CD IN ('N306', 'N316', 'N326')
    AND DISTR_CHAN_CD = '81'
