
SELECT
    C.SHIP_TO_CUST_ID
    , C.CUST_NAME AS SHIP_TO_CUST_NAME

    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , C.CO_CD
    , C.CO_DESC

    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME

    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME

    , C.DIV_CD

    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME

    , C.PRIM_SHIP_FACILITY_ID
    , C.DELIV_PRTY_CD
    , C.SHIP_COND_ID
    , C.CUST_GRP2_CD

    , C.DISTRICT_NAME
    , C.TERR_NAME
    , C.CITY_NAME
    , C.POSTAL_CD
    , C.CNTRY_NAME_CD

    , CAST(CASE
        WHEN C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N307', 'N317', 'N336') OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN('30', '31'))
            THEN 'Replacement'
        ELSE 'OE'
        END AS VARCHAR(25)) AS OE_REPL_IND

FROM GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C

ORDER BY
    SHIP_TO_CUST_ID
