-- 2014-08-06 -> SQL Server import query definition for EDW.dbo.GoodyearCalendar

SELECT
    CAL.DAY_DATE
    , CAL.MONTH_DT
    , CAL.TTL_DAYS_IN_MNTH
    , CAL.DAY_OF_WEEK
    , CAL.DAY_OF_WEEK_NAME_ABBREV
    , CAL.DAY_OF_WEEK_NAME_DESC
    , CAL.WEEKDAY_IN_MONTH_OCCURENCE
    , CAL.DAY_OF_MONTH
    , CAL.DAY_OF_QTR
    , CAL.DAY_OF_YEAR
    , CAL.CAL_LAST_DAY_MO_IND
    , CAL.CAL_LAST_DAY_YR_IND
    , CAL.CAL_WK
    , CAL.CAL_MTH
    , CAL.CAL_YR
    , CAL.DOT_WK_YR
    , CAL.MNTH
    , CAL.MNTH_DESCR
    , CAL.MNTH_SEQ
    , CAL.MNTH_NAME_ABBREV
    , CAL.MNTH_NAME
    , CAL.MONTH_OF_QUARTER
    , CAL.LAST_SHIP_DAY_MO_IND
    , CAL.QTR_NO
    , CAL.QUARTER_OF_YEAR
    , CAL.QTR_DESCR
    , CAL.QTR_SEQ
    , CAL.SHIP_DAY_OF_MO
    , CAL.WEEK_OF_MONTH
    , CAL.WEEK_OF_YEAR
    , CAL.WEEKDAY_OF_MONTH
    , CAL.FIFTH_WRK_DY_IND
    , CAL.TWENTIETH_WRK_DY_IND
    , CAL.MTH_WRK_DYS
    , CAL.MTD_WRK_DYS
    , CAL.MTD_WRK_DYS_NON_ZERO
    , CAL.MTH_RTL_SLS_DYS
    , CAL.MTD_RTL_SLS_DYS
    , CAL.MTD_RTL_SLS_DYS_NON_ZERO
    , CAL.MTH_NON_HLDY_CT
    , CAL.MTD_NON_HLDY_CT
    , CAL.MTD_NON_HLDY_CT_NON_ZERO
    , CAL.SHP_DY_PAR
    , CAL.PERIOD_SK
    , CAL.CALENDAR_DATE
    , CAL.DAY_OF_WEEK_ISO
    , CAL.WEEK_OF_YEAR_ISO
    , CAL.WEEK_OF_CALENDAR_ISO
    , CAL.MONTH_OF_YEAR
    , CAL.TOT_CAL_MTHS

FROM GDYR_BI_VWS.GDYR_CAL CAL

WHERE
    CAL.DAY_DATE BETWEEN CAST(EXTRACT(YEAR FROM (CURRENT_DATE-1)) - 5 || '-01-01' AS DATE) AND CAST(EXTRACT(YEAR FROM (CURRENT_DATE-1)) + 6 || '-01-01' AS DATE)

ORDER BY
    CAL.DAY_DATE