SELECT 
    FAC.FACILITY_ID
	, FAC.NAME 
	, FAC.XTND_NAME 
	, FAC.VAL_AREA_ID 
	, FAC.INT_CUST_ID
	, FAC.VENDOR_CUST_ID
	, FAC.PURCH_ORG_ID 
	, FAC.SALES_ORG_CD
	, SO.NAME AS SALES_ORG_NAME
	, FAC.ACTIV_REQ_PLAN_IND
	, FAC.CNTRY_ID
	, FAC.TERR_ID
	, FAC.DISTRICT_ID
	, FAC.CITY_ID
	, FAC.DISTR_CHAN_CD
	, DC.NAME AS DISTR_CHAN_NAME
	, FAC.DIV_CD
	, FAC.LANG_ID
	, FAC.FACILITY_TYPE_ID
	, TYP.FACILITY_TYPE_DESC
	, FAC.FACILITY_CAT_ID
	, FAC.FACILITY_ACTIV_IND
	, FAC.SPLC_CD
	, FAC.SRC_LOC_CD
	, FAC.MFG_FACL_CD
	, FAC.PROD_FACILITY_ID
	, FAC.ADDR_ID
/*	, FAC.SBU_ID
	, FAC.ORIG_SYS_ID
	, FAC.SRC_SYS_ID
	, FAC.EFF_DT
	, FAC.EXP_DT*/
    
FROM GDYR_VWS.FACILITY FAC

    LEFT JOIN GDYR_VWS.FACILITY_TYPE TYP 
        ON TYP.FACILITY_TYPE_ID = FAC.FACILITY_TYPE_ID

    LEFT JOIN GDYR_VWS.SALES_ORG SO 
        ON SO.SALES_ORG_CD = FAC.SALES_ORG_CD
    	AND SO.EXP_DT = DATE '5555-12-31'
    	AND SO.LANG_ID = 'E'
    	AND SO.SBU_ID = FAC.SBU_ID
    	AND SO.ORIG_SYS_ID = FAC.ORIG_SYS_ID
        
    LEFT JOIN GDYR_VWS.DISTR_CHAN DC 
        ON DC.DISTR_CHAN_CD = FAC.DISTR_CHAN_CD
    	AND DC.EXP_DT = DATE '5555-12-31'
    	AND DC.SBU_ID = FAC.SBU_ID
    	AND DC.ORIG_SYS_ID = FAC.ORIG_SYS_ID
    
WHERE 
    FAC.SBU_ID = 2
	AND FAC.ORIG_SYS_ID = 2
	AND FAC.EXP_DT = DATE '5555-12-31'
	AND FAC.LANG_ID = 'EN'

ORDER BY
    FAC.FACILITY_ID