SELECT
    F.FACILITY_ID
    , F.NAME
    , F.XTND_NAME
    , F.VAL_AREA_ID
    , F.INT_CUST_ID
    , F.VENDOR_CUST_ID
    , F.PURCH_ORG_ID
    , F.SALES_ORG_CD
    , F.DISTR_CHAN_CD
    , F.DIV_CD
    , F.ACTIV_REQ_PLAN_IND
    , F.CNTRY_ID
    , F.TERR_ID
    , F.DISTRICT_ID
    , F.CITY_ID
    , F.LANG_ID
    , F.FACILITY_TYPE_ID
    , F.FACILITY_CAT_ID
    , F.FACILITY_ACTIV_IND
    , F.SPLC_CD
    , F.ADDR_ID

FROM GDYR_VWS.FACILITY F

WHERE
    F.ORIG_SYS_ID = 2
    AND F.EXP_DT = CAST('5555-12-31' AS DATE)
    AND F.LANG_ID = 'EN'
    AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
    AND F.DISTR_CHAN_CD = '81'
