SELECT
    DISTR_CHAN_CD
    , DC.NAME AS DISTR_CHAN_NAME
    , DC.SBU_ID
    , DC.ORIG_SYS_ID
    , DC.SRC_SYS_ID
    , DC.EFF_DT
    , DC.EXP_DT

FROM GDYR_VWS.DISTR_CHAN DC

WHERE
    DC.SBU_ID = 2
    AND DC.ORIG_SYS_ID = 2
    AND DC.EXP_DT = DATE '5555-12-31'

ORDER BY
    DISTR_CHAN_CD
