-- FACILITY HIERARCHY FILTERED ON THE NAT SALES ORGS

SELECT
    FACILITY_ID
    , FACILITY_ID || ' - ' || FACILITY_NAME AS FACILITY

    , VAL_AREA_ID
    , INT_CUST_ID
    , VENDOR_CUST_ID
    , PURCH_ORG_ID
    , SALES_ORG_CD
    , DISTR_CHAN_CD
    , DIV_CD

    , CNTRY_ID
    , TERR_ID
    , DISTRICT_ID
    , CITY_ID

FROM GDYR_BI_VWS.NAT_FACILITY_EN_CURR

WHERE
    SALES_ORG_CD IN ('N306', 'N316', 'N326')
    AND DISTR_CHAN_CD = '81'
