SELECT
    MAX(CASE WHEN TRIM(INDEXNAME) LIKE '%_NUPI' THEN 'NUPI' END) AS NUPI_IND
    , MAX(CASE WHEN TRIM(INDEXNAME) LIKE '%_UPI' AND TRIM(INDEXNAME) NOT LIKE '%_NUPI' THEN 'UPI' END) AS UPI_IND
    , MAX(CASE WHEN TRIM(INDEXNAME) LIKE '%_JI%' AND TRIM(INDEXNAME) NOT LIKE '%_JI' THEN 'JI' END) AS JI_IND
    , MAX(CASE WHEN TRIM(INDEXNAME) LIKE '%_PI' THEN 'PI' END) AS PI_IND
    , MAX(CASE WHEN TRIM(indexname) NOT LIKE ANY ('%_JI', '%_UPI', '%_NUPI') THEN SUBSTR(TRIM(indexname), LENGTH(TRIM(indexname)) - 5, LENGTH(TRIM(indexname))) end) AS other_ind
    , I.DATABASENAME
    , I.TABLENAME
    , I.COLUMNNAME
    
FROM DBC.INDICES I

WHERE
    DATABASENAME = 'NA_MART'

GROUP BY
    I.DATABASENAME
    , I.TABLENAME
    , I.COLUMNNAME

ORDER BY
    I.DATABASENAME
    , I.TABLENAME
    , I.COLUMNNAME

SAMPLE 1000