SELECT
    I.FACILITY_ID AS STOCKING_FACILITY_ID
    , FAC.FACILITY_NAME AS STOCKING_FACILITY_NAME

    , I.MATL_ID
    , MATL.MATL_STA_ID
    , MATL.MATL_PRTY_ID
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , MATL.TIC_CD
    , MATL.PBU_NBR || ' - ' || MATL.PBU_NAME AS PBU

    , MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY
    , MATL.MKT_CTGY_MKT_GRP_NBR || ' - ' || MATL.MKT_CTGY_MKT_GRP_NAME AS SEGMENT
    , MATL.MKT_CTGY_PROD_GRP_NBR || ' - ' || MATL.MKT_CTGY_PROD_GRP_NAME AS TIER
    , MATL.MKT_CTGY_PROD_LINE_NBR || ' - ' || MATL.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE

    , I.AVAIL_TO_PROM_QTY
    , I.BACK_ORDER_QTY
    , I.BLOCKED_STK_QTY
    , I.COMMIT_QTY AS COMMITTED_QTY
    , I.DEF_QTY AS DEFERRED_QTY
    , I.FACT_SHR AS FACTORY_SHARE_QTY
    , I.IN_PROS_TO_CUST_QTY AS GROSS_IN_PROCESS_QTY
    , I.TOT_QTY AS TOTAL_QTY
    , I.STO_OUTBOUND_QTY AS IN_PROCESS_FROM_QTY
    , I.STO_INBOUND_QTY AS IN_PROCESS_TO_QTY
    , I.NET_BACK_ORDER_QTY
    , I.COMMIT_QTY AS COMMIT_ON_HAND_QTY
    , I.QUAL_INSP_QTY AS QUALITY_INSP_QTY
    , I.RSVR_QTY AS RESERVED_QTY
    , I.RSTR_QTY AS RESTRICTED_QTY
    , I.STK_RET_QTY AS RETURN_STOCK_QTY
    , I.SAFE_STK_QTY AS SAFETY_STOCK_QTY
    , I.UN_COMMIT_QTY AS UNCOMMITTED_QTY
    , I.UNRSTR_QTY AS UNRESTRICTED_QTY
    , I.EST_DAYS_SUPPLY AS ESTIMATED_DAYS_OF_SUPPLY

FROM NA_BI_VWS.INVENTORY I

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FAC
        ON FAC.FACILITY_ID = I.FACILITY_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = I.MATL_ID
        AND MATL.PBU_NBR = '01'
        AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')

WHERE
    I.DAY_DT = CURRENT_DATE-1