SELECT
    M.MATL_ID
    , M.SAL_IND
    , PAL.PAL_IND
FROM GDYR_BI_VWS.NAT_MATL_CURR M
    LEFT OUTER JOIN GDYR_BI_VWS.NAT_MATL_PAL_CURR PAL
        ON PAL.MATL_ID = M.MATL_ID
WHERE
    M.PBU_NBR IN ('01', '03')
    AND M.MATL_TYPE_ID IN ('ACCT', 'PCTL')
    AND (M.SAL_IND = 'Y' OR PAL.PAL_IND = 'Y')


    