SELECT
    SDI.ORIG_SYS_ID
    , SDI.SRC_SYS_ID
    , SDI.EDW_JOB_ID
    , SDI.SBU_ID

    , SDI.EFF_DT
    , SDI.EXP_DT

    , SDI.FISCAL_YR
    , SDI.SLS_DOC_ID
    , SDI.SLS_DOC_ITM_ID

    , SDI.SRC_CRT_TS
    , SDI.SRC_CRT_USR_ID
    , SDI.SRC_UPD_DT

    , SDI.SLS_DOC_ITM_CTGY_CD
    , SDI.BILL_BLK_CD

    , SDI.FACILITY_ID
    , SDI.SHIP_RCVE_PT_CD
    , SDI.ROUTE_CD
    , SDI.ORIG_FACILITY_ID
    , SDI.APO_FACILITY_ID
    , SDI.APO_STOR_LOC_ID

    , SDI.MATL_ID
    , SDI.ORIG_MATL_ID
    , SDI.ORIG_REQ_MATL_ID
    , SDI.MATL_GRP_ID
    , SDI.MATL_HIER_ID

    , SDI.ITM_TYP_CD
    , SDI.ITM_RLVNT_DELIV_IND
    , SDI.ITM_RLVNT_BILL_ICD

    , SDI.REJ_REAS_ID
    , SDI.SLS_UNIT_TGT_QTY

    , SDI.DELIV_RND_QTY
    , SDI.ALLOW_DEVIATE_QTY

    , SDI.DELIV_GRP_ID
    , SDI.FIXED_QTY_IND
    , SDI.ALLOW_UNLMT_OVR_DELIV_IND
    , SDI.OVR_DELIV_LMT_PCT
    , SDI.UNDER_DELIV_LMT_PCT

    , SDI.REPL_PART_ICD
    , SDI.DIV_CD

    , SDI.MAX_PRTL_DELIV_QTY
    , SDI.PRTL_DELIV_ICD
    , SDI.SLS_UNIT_CUM_ORD_QTY
    , SDI.SLS_UNIT_CUM_REQ_DELIV_QTY
    , SDI.SLS_UNIT_CUM_CNFRM_QTY
    , SDI.BASE_UNIT_CUM_CNFRM_QTY
    , SDI.BASE_UOM_CD
    , SDI.SLS_UOM_CD

    , SDI.TOT_GROSS_WT_QTY
    , SDI.TOT_NET_WT_QTY
    , SDI.WT_UOM_CD

    , SDI.TOT_VOL_QTY
    , SDI.VOL_UOM_CD

    , SDI.ORIG_SLS_DOC_ID
    , SDI.ORIG_SLS_DOC_ITM_ID
    , SDI.REF_DOC_SLS_DOC_ID
    , SDI.REF_DOC_SLS_DOC_ITM_ID

    , SDI.DELIV_PRTY_CD

    , SDI.STOR_LOC_CD

    , SDI.ORD_PRBL_PCT

    , SDI.FIX_SHIP_DY_QTY
    , SDI.DELIV_DT_QTY_FIX_IND

    , SDI.RET_IND

    , SDI.AVAIL_CHK_GRP_CD
    , SDI.MATL_PRC_GRP_CD
    , SDI.ACCT_ASSGN_GRP_CD
    , SDI.VOL_REBATE_GRP_CD
    , SDI.PRC_AGR_IND

    , SDI.VAL_TYP_CD
    , SDI.SEPRT_VAL_IND

    , SDI.PROFT_CNTR_ID

    , SDI.MATL_GRP_CD_1
    , SDI.MATL_GRP_CD_2
    , SDI.MATL_GRP_CD_3
    , SDI.MATL_GRP_CD_4
    , SDI.MATL_GRP_CD_5

    , SDI.MATL_SUBST_REAS_CD
    , SDI.SPCL_STK_TYP_CD

    , SDI.ALLOC_ICD
    , SDI.PROFT_SEG_ID

    , SDI.ORD_ID
    , SDI.ACCT_ASSGN_CTGY_CD
    , SDI.CONS_POST_ICD
    , SDI.RQT_TYP_CD

    , SDI.CRED_MGMT_FUNCT_ACTV_IND
    , SDI.EXPCT_PRC_STA_CD
    , SDI.MNL_PRC_CHG_STA_CD
    , SDI.BUS_TRANS_TYP_CD
    , SDI.COST_SHEET_CD
    , SDI.PRC_CALC_REF_MATL_ID
    , SDI.PLN_DELIV_SCHD_INSTR_CD
    , SDI.KANBAN_SEQ_ID
    , SDI.VAL_CONTRACT_ID
    , SDI.VAL_CONTRACT_ITM_ID

    , SDI.SPCL_STK_VAL_ICD

    , SDI.CUST_DELIV_DT -- ACTUAL DELIVERY DATE?

    , SDI.ORIG_REQ_DELIV_DT -- ORDD?
    , SDI.REQ_DELIV_DT -- FRDD?
    , SDI.CUST_DELIV_PROM_DT -- FCDD?
    , SDI.CUST_DELIV_PROM_DT_TYP_CD
    , SDI.SHIP_REQ_ARRV_TS -- SEEMS POTENTIALLY IMPORTANT?

    , SDI.B2B_GRP_ID
    , SDI.B2B_CMPGN_ID
    , SDI.GLS_SLSMN_ID
    , SDI.TTS_SLSMN_ID
    , SDI.FTS_SLSMN_ID
    , SDI.ETS_SLSMN_ID
    , SDI.AVIAT_SLSMN_ID
    , SDI.CAR_DLR_SLSMN_ID
    , SDI.GLS_DIST_SLSMN_ID
    , SDI.TTS_DIST_SLSMN_ID
    , SDI.SLSMN_ID
    , SDI.SLSMN_HIER_LVL_1_ID
    , SDI.SLSMN_HIER_LVL_2_ID
    , SDI.SLSMN_HIER_LVL_3_ID

    , SDI.SAP_TRANS_CD
    , SDI.EXTRA_DMAN_ICD
    , SDI.BILL_PROFT_CNTR_CD

    , SDI.SPCL_APRVL_ID

    , SDI.CLAIM_STA_CD_1
    , SDI.CLAIM_STA_DT_1
    , SDI.CLAIM_STA_CD_2
    , SDI.CLAIM_STA_DT_2

    , SDI.CLEAN_CHRG_PCT_IND
    , SDI.FINISHED_TIRE_RIM_DIAM

    , SDI.PSEUDO_TERM_DT_1
    , SDI.PSEUDO_TERM_DT_2
    , SDI.TERM_PAY_ID_1
    , SDI.TERM_PAY_ID_2
    , SDI.TERM_PAY_ID_3

    , SDI.CROSS_DISTR_CHAIN_MATL_STA_CD
    , SDI.DFS_IND
    , SDI.PREC_SD_DOC_CTGY_CD

    , SDI.BOM_STRCTR_HI_LVL_ITM_ID
    , SDI.BATCH_NBR

    , SDI.NTFCTN_ID

    , SDI.FOS_SRV_CNTRY_NAME_CD
    , SDI.FOS_DFLT_SVC_IND

    , SDI.PN_IND
    , SDI.PN_TXT

    , SDI.GRNTE_PRC_DT_CD
    , SDI.EXTRA_DMAN_INQR_BLK_IND
    , SDI.EXTRA_DMAN_INQR_BLK_MNL_IND

    , SDI.EXTN_SLS_DOC_TYP_CD
    , SDI.EXTN_SLS_DOC_ITM_CTGY_CD

    , SDI.KEEP_PLANT_IND
    , SDI.SRV_LVL_TYP_CD -- ?

    , SDI.REL_PROC_CD
    , SDI.REL_SEQ_PROC_IND

    , SDI.CHG_BILL_BLK_STA_IND

    , SDI.BRAND_ID

    , SDI.TAX_SCEN_ID
    , SDI.DELIV_LOC_TYP_CD
    , SDI.MNL_CLOSE_IND

FROM NA_BI_VWS.NAT_SLS_DOC_ITM SDI

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC SD
        ON SD.EXP_DT = DATE '5555-12-31'
        AND SD.FISCAL_YR = SDI.FISCAL_YR
        AND SD.SLS_DOC_ID = SDI.SLS_DOC_ID
        AND SD.SD_DOC_CTGY_CD = 'C'
        AND SD.SLS_DOC_TYP_CD NOT IN ('ZLZ', 'ZDB', 'ZKB', 'ZKE')
        AND SD.CUST_PRCH_ORD_TYP_CD <> 'RO' -- RESERVE ORDERS
        AND SD.FISCAL_YR >= '2012'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = SDI.MATL_ID
        AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
        AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')

WHERE
    SDI.FISCAL_YR >= '2012'
    AND SDI.EXP_DT = DATE '5555-12-31'
    AND (SDI.FISCAL_YR, SDI.SLS_DOC_ID, SDI.SLS_DOC_ITM_ID) NOT IN (
        SELECT
            ORDER_FISCAL_YR
            , ORDER_ID
            , ORDER_LINE_NBR
        FROM NA_BI_VWS.ORDER_DETAIL_CURR
        WHERE
            ORDER_CAT_ID = 'C'
            AND ORDER_TYPE_ID <> 'ZLZ'
            AND PO_TYPE_ID <> 'RO'
            AND ORDER_FISCAL_YR >= '2012'
        GROUP BY
            ORDER_FISCAL_YR
            , ORDER_ID
            , ORDER_LINE_NBR
    )

