-- 2014-08-06 -> SQL Server import query definition for EDW.dbo.OrderDetailCurrent

SELECT
    ODC.ORDER_FISCAL_YR
	, ODC.ORDER_ID
	, ODC.ORDER_LINE_NBR
	, ODC.SCHED_LINE_NBR
    , ODC.CUST_PO_NBR
    
    , ODC.CO_CD
    , ODC.DIV_CD
    , ODC.SALES_ORG_CD
    , ODC.DISTR_CHAN_CD
    , ODC.CUST_GRP_ID
    , C.OWN_CUST_ID
	, ODC.SOLD_TO_CUST_ID
	, ODC.SHIP_TO_CUST_ID
	, ODC.BILL_TO_CUST_ID
	, ODC.PAYOR_CUST_ID
    
    , ODC.MATL_ID
    , M.PBU_NBR
    , M.MKT_AREA_NBR
    , M.EXT_MATL_GRP_ID
    , CAST(CASE M.PBU_NBR || M.MKT_AREA_NBR
        WHEN '0101' THEN 0.75
        WHEN '0108' THEN 0.80
        WHEN '0305' THEN 1.20
        WHEN '0314' THEN 1.20
        WHEN '0406' THEN 1.20
        WHEN '0507' THEN 0.75
        WHEN '0711' THEN 0.75
        WHEN '0712' THEN 0.75
        WHEN '0803' THEN 1.20
        WHEN '0923' THEN 0.75
        ELSE 1
        END AS DECIMAL(15, 3)) AS COMPRESSION_FACTOR
    
    , CAST(CASE
        WHEN ODC.FACILITY_ID IN ('N5US', 'N5CA')
            THEN 'N5US / N5CA'
        WHEN ODC.FACILITY_ID = C.PRIM_SHIP_FACILITY_ID
            THEN 'Primary LC'
        ELSE (CASE
            WHEN ODC.FACILITY_ID LIKE 'N5%'
                THEN 'Factory Direct'
            ELSE 'Out of Area'
            END)
        END AS VARCHAR(30)) AS PRIM_SHIP_FACILITY_TEST
    , C.PRIM_SHIP_FACILITY_ID
    , ODC.FACILITY_ID
	, ODC.SHIP_PT_ID
    
    , ODC.PRC_DT
	, ODC.PRICE
	, ODC.CRNCY_ID

	, ODC.QTY_UNIT_MEAS_ID AS QTY_UOM
	, ODC.ORDER_QTY
	, ODC.BUS_INQR_QTY
	, ODC.CNFRM_QTY
    
	, ODC.SLS_QTY_UNIT_MEAS_ID AS SLS_QTY_UOM
	, ODC.SLS_ORDER_QTY
    
    , ODC.RPT_QTY_UNIT_MEAS_ID AS RPT_QTY_UOM
	, ODC.RPT_ORDER_QTY
	, ODC.RPT_CNFRM_QTY
	
    , ODC.WT_UNITS_MEAS_ID AS WT_UOM
	, ODC.NET_WT
	, ODC.GROSS_WT
	
    , ODC.VOL_UNIT_MEAS_ID AS VOL_UOM
	, ODC.VOL
    , CAST(COMPRESSION_FACTOR * ODC.VOL AS DECIMAL(15,3)) AS COMPRESSED_VOL
    
	, ODC.SHIP_COND_ID
	, ODC.PRTL_DLVY_CD
	
	, ODC.ORDER_REAS_CD
	, ODC.BATCH_NBR
	, ODC.DELIV_PRTY_ID
	, ODC.HANDSHAKE_TYP_CD
    
    , ODC.ORDER_DT
	, ODC.CUST_RDD AS ORDD
    
	, ODC.FRST_MATL_AVL_DT AS FRDD_FMAD
    , ODC.FRST_PLN_GOODS_ISS_DT AS FRDD_FPGI
    , ODC.FRST_RDD AS FRDD
	
	, ODC.FC_MATL_AVL_DT AS FCDD_FMAD
	, ODC.FC_PLN_GOODS_ISS_DT AS FCDD_FPGI
	, ODC.FRST_PROM_DELIV_DT AS FCDD
    
	, ODC.PLN_TRANSP_PLN_DT
	, ODC.PLN_MATL_AVL_DT
	, ODC.PLN_LOAD_DT
	, ODC.PLN_GOODS_ISS_DT
	, ODC.PLN_DELIV_DT
	, ODC.PLN_ARRIVE_TM
	, ODC.FNL_ACCEPT_DT
    
	, ODC.DELIV_BLK_IND
    , ODC.CANCEL_IND
	, ODC.RETURN_IND
    , ODC.RO_PO_TYPE_IND
    
	, ODC.ROUTE_ID
	, ODC.DELIV_GRP_CD
	, ODC.SPCL_PROC_ID
	, ODC.PROD_ALLCT_DETERM_PROC_ID
	, ODC.RPT_FRT_PLCY_CD
	, ODC.CUST_GRP2_CD
	
    , ODC.CANCEL_DT
    , ODC.REJ_REAS_ID
	, ODC.REJ_REAS_DESC
    
	, ODC.ORDER_CAT_ID
	, ODC.ORDER_TYPE_ID
    , ODC.ITEM_CAT_ID
	, ODC.SCHD_LN_CTGY_CD
    , ODC.PO_TYPE_ID
	
	, ODC.DELIV_BLK_CD
	, ODC.BUS_INQR_IND
	, ODC.WAIT_LIST_CD
    , ODC.ORDER_CREATOR

FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_CURR C
        ON C.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = ODC.MATL_ID
        AND M.PBU_NBR IN ('01', '03')
        AND M.MATL_TYPE_ID IN ('ACCT', 'PCTL')

WHERE
    ODC.ORDER_FISCAL_YR >= CAST(EXTRACT(YEAR FROM (CURRENT_DATE-1)) - 1 AS CHAR(4))

    -- Orders w/ FRDD within a rolling 3 months
    AND ODC.FRST_RDD BETWEEN ADD_MONTHS((CURRENT_DATE-1), -3) - (EXTRACT(DAY FROM ADD_MONTHS((CURRENT_DATE-1), -3)) - 1)
        AND (CURRENT_DATE-1)

    -- Only Sales Orders, excluding returns
    AND ODC.ORDER_CAT_ID = 'C'

    -- Goodyear US, Canada & GDTNA main Sales Orgs
    AND ODC.SALES_ORG_CD IN (
            'N301', 'N302', 'N303', 
            'N311', 'N312', 'N313', 
            'N321', 'N322', 'N323'
        )

    -- Only certain DC's are active within these sales orgs -- trying to hit the db stats
    AND ODC.DISTR_CHAN_CD IN (
            '01', '03', '04', '05', '06', '07', '08', '09'
            , '10', '11', '12', '14', '15', '16'
            , '20', '21', '22'
            , '30', '31', '32'
        )

ORDER BY
    ODC.ORDER_FISCAL_YR
	, ODC.ORDER_ID
	, ODC.ORDER_LINE_NBR
	, ODC.SCHED_LINE_NBR    
