SELECT
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    , OOL.SCHED_LINE_NBR
    , OOL.OPEN_CNFRM_QTY
    , OOL.UNCNFRM_QTY
    , OOL.BACK_ORDER_QTY
    , OOL.DEFER_QTY
    , OOL.IN_PROC_QTY
    , OOL.WAIT_LIST_QTY
    , OOL.OTHR_ORDER_QTY
    , OOL.CREDIT_HOLD_FLG

FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL

ORDER BY
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    , OOL.SCHED_LINE_NBR
