SELECT
    CAL.MONTH_DT AS CMPL_MTH,
    POL.SHIP_FACILITY_ID,
    POL.PBU,
    POL.MATL_ID,
    POL.DESCR,
    
    SUM( POL.ORIG_ORD_QTY ) AS ORIG_ORD_QTY,
    SUM( POL.CURR_ORD_QTY ) AS CURR_ORD_QTY,
    SUM( POL.FPDD_ORD_QTY ) AS FPDD_ORD_QTY,
    SUM( POL.CANCEL_QTY ) AS CANCEL_QTY,
    SUM( POL.PRFCT_ORD_QTY ) AS PRFCT_ORD_QTY,
    
    SUM( OLC.ORDER_QTY ) AS ORDERED_QTY,
    SUM( OLC.CNFRM_QTY ) AS CONFIRMED_QTY,
    
    SUM( POL.IF_HIT_NS_QTY ) AS NO_STK_HIT_QTY,
    
    SUM( INV.BACK_ORDER_QTY ) AS FAC_BACK_ORDER_QTY,

    SUM( INV.UN_COMMIT_QTY ) AS FAC_UNCOMMIT_QTY,
    SUM( INV.TOT_QTY ) AS FAC_TOT_QTY,
    SUM( INV.AVAIL_TO_PROM_QTY ) AS FAC_ATP_QTY,
    
    SUM( INV.BLOCKED_STK_QTY ) AS FAC_BLK_STK_QTY,
    SUM( INV.RSTR_QTY ) AS FAC_RSTR_QTY,
    SUM( INV.UNRSTR_QTY ) AS FAC_UNRSTR_QTY

FROM A421356.PRFCT_ORD_LINE POL

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE = POL.CMPL_DT

    INNER JOIN A421356.ORDER_LINE_CURR OLC
        ON OLC.ORDER_ID = POL.ORDER_ID
        AND OLC.ORDER_LINE_NBR = POL.ORDER_LINE_NBR

    LEFT OUTER JOIN A421356.NAT_INV_MTH_END INV
        ON INV.INV_MTH = POL.FRDD_MTH
        AND INV.FACILITY_ID = POL.SHIP_FACILITY_ID
        AND INV.MATL_ID = POL.MATL_ID

WHERE
    CMPL_MTH / 100 = DATE '2014-02-01' / 100
    --POL.PRFCT_ORD_HIT_REAS = 'PO HIT - NS'
    --BETWEEN DATE '2013-01-01' AND CURRENT_DATE

GROUP BY
    --POL.FRDD_MTH,
    CMPL_MTH,
    POL.SHIP_FACILITY_ID,
    POL.PBU,
    POL.MATL_ID,
    POL.DESCR

ORDER BY
    POL.SHIP_FACILITY_ID,
    POL.MATL_ID,
    CMPL_MTH
    --POL.FRDD_MTH