SELECT 
    "ORDER_DETAIL_CURR"."ORDER_ID" "C0",
	"ORDER_DETAIL_CURR"."ORDER_LINE_NBR" "C1",
	"NAT_MATL_HIER_DESCR_EN_CURR"."MATL_ID_TRIM" "C2",
	SUM("OPEN_ORDER_SCHDLN_CURR"."OPEN_CNFRM_QTY") OVER (
		PARTITION BY "ORDER_DETAIL_CURR"."ORDER_ID",
		"ORDER_DETAIL_CURR"."ORDER_LINE_NBR",
		"NAT_MATL_HIER_DESCR_EN_CURR"."MATL_ID_TRIM",
		"ORDER_DETAIL_CURR"."FRST_RDD",
		"ORDER_DETAIL_CURR"."PLN_DELIV_DT",
		"ORDER_DETAIL_CURR"."DELIV_BLK_IND",
		"ORDER_DETAIL_CURR"."DELIV_BLK_CD",
		"NAT_CUST_HIER_DESCR_EN_CURR"."SHIP_TO_CUST_ID",
		"NAT_CUST_HIER_DESCR_EN_CURR"."CUST_NAME",
		"NAT_FACILITY_HIER_EN_CURR"."FACILITY_ID",
		"NAT_FACILITY_HIER_EN_CURR"."FAC_NAME",
		"ORDER_DETAIL_CURR"."FRST_MATL_AVL_DT",
		"NAT_MATL_HIER_DESCR_EN_CURR"."PBU_NBR" || ' - ' || "NAT_MATL_HIER_DESCR_EN_CURR"."PBU_NAME",
		"NAT_MATL_HIER_DESCR_EN_CURR"."MKT_CTGY_PROD_GRP_NBR" || ' - ' || "NAT_MATL_HIER_DESCR_EN_CURR"."MKT_CTGY_PROD_GRP_NAME",
		"NAT_MATL_HIER_DESCR_EN_CURR"."PROD_LINE_NAME",
		"NAT_MATL_HIER_DESCR_EN_CURR"."DESCR",
		"NAT_MATL_HIER_DESCR_EN_CURR"."PROD9_CD",
		"ORDER_DETAIL_CURR"."CUST_GRP2_CD",
		"ORDER_DETAIL_CURR"."SPCL_PROC_ID",
		"NAT_MATL_HIER_DESCR_EN_CURR"."PBU_NBR",
		"T6"."OWN_CUST_NAME",
		"T6"."OWN_CUST_ID",
		"ORDER_DETAIL_CURR"."PLN_GOODS_ISS_DT",
		"NAT_MATL_HIER_DESCR_EN_CURR"."MATL_ID",
		(
			CASE 
				WHEN "ORDER_DETAIL_CURR"."SPCL_PROC_ID" = 'OCUA'
					THEN 1
				ELSE 0
				END
			),
		(
			CASE 
				WHEN "ORDER_DETAIL_CURR"."SPCL_PROC_ID" IN (
						'OCUA',
						'OFPS'
						)
					THEN 1
				ELSE (
						CASE 
							WHEN "ORDER_DETAIL_CURR"."DELIV_BLK_IND" IN ('Y')
								THEN 1
							ELSE 0
							END
						)
				END
			),
		"NAT_MATL_HIER_DESCR_EN_CURR"."MKT_AREA_NBR",
		"NAT_MATL_HIER_DESCR_EN_CURR"."MKT_AREA_NAME"
		) "C3",
	"ORDER_DETAIL_CURR"."FRST_RDD" "C4",
	"ORDER_DETAIL_CURR"."PLN_DELIV_DT" "C5",
	"ORDER_DETAIL_CURR"."DELIV_BLK_IND" "C6",
	"ORDER_DETAIL_CURR"."DELIV_BLK_CD" "C7",
	"NAT_CUST_HIER_DESCR_EN_CURR"."SHIP_TO_CUST_ID" "C8",
	"NAT_CUST_HIER_DESCR_EN_CURR"."CUST_NAME" "C9",
	"NAT_FACILITY_HIER_EN_CURR"."FACILITY_ID" "C10",
	"NAT_FACILITY_HIER_EN_CURR"."FAC_NAME" "C11",
	"ORDER_DETAIL_CURR"."FRST_MATL_AVL_DT" "C12",
	"NAT_MATL_HIER_DESCR_EN_CURR"."PBU_NBR" || ' - ' || "NAT_MATL_HIER_DESCR_EN_CURR"."PBU_NAME" "C13",
	"NAT_MATL_HIER_DESCR_EN_CURR"."MKT_CTGY_PROD_GRP_NBR" || ' - ' || "NAT_MATL_HIER_DESCR_EN_CURR"."MKT_CTGY_PROD_GRP_NAME" "C14",
	"NAT_MATL_HIER_DESCR_EN_CURR"."PROD_LINE_NAME" "C15",
	"NAT_MATL_HIER_DESCR_EN_CURR"."DESCR" "C16",
	"NAT_MATL_HIER_DESCR_EN_CURR"."PROD9_CD" "C17",
	"ORDER_DETAIL_CURR"."CUST_GRP2_CD" "C18",
	"ORDER_DETAIL_CURR"."SPCL_PROC_ID" "C19",
	"NAT_MATL_HIER_DESCR_EN_CURR"."PBU_NBR" "C20",
	"T6"."OWN_CUST_NAME" "C21",
	"T6"."OWN_CUST_ID" "C22",
	"ORDER_DETAIL_CURR"."PLN_GOODS_ISS_DT" "C23",
	"NAT_MATL_HIER_DESCR_EN_CURR"."MATL_ID" "C24",
	(
		CASE 
			WHEN "ORDER_DETAIL_CURR"."SPCL_PROC_ID" = 'OCUA'
				THEN 1
			ELSE 0
			END
		) "C25",
	(
		CASE 
			WHEN "ORDER_DETAIL_CURR"."SPCL_PROC_ID" IN (
					'OCUA',
					'OFPS'
					)
				THEN 1
			ELSE (
					CASE 
						WHEN "ORDER_DETAIL_CURR"."DELIV_BLK_IND" IN ('Y')
							THEN 1
						ELSE 0
						END
					)
			END
		) "C26",
	"NAT_MATL_HIER_DESCR_EN_CURR"."MKT_AREA_NBR" "C27",
	"NAT_MATL_HIER_DESCR_EN_CURR"."MKT_AREA_NAME" "C28"
    
FROM  "NA_BI_VWS"."ORDER_DETAIL_CURR" "ORDER_DETAIL_CURR" 

    INNER JOIN "GDYR_BI_VWS"."NAT_CUST_HIER_DESCR_EN_CURR" "NAT_CUST_HIER_DESCR_EN_CURR" 
        ON "ORDER_DETAIL_CURR"."SHIP_TO_CUST_ID" = "NAT_CUST_HIER_DESCR_EN_CURR"."SHIP_TO_CUST_ID"

    INNER JOIN "GDYR_BI_VWS"."NAT_MATL_HIER_DESCR_EN_CURR" "NAT_MATL_HIER_DESCR_EN_CURR" 
        ON "ORDER_DETAIL_CURR"."MATL_ID" = "NAT_MATL_HIER_DESCR_EN_CURR"."MATL_ID"

    INNER JOIN "GDYR_BI_VWS"."NAT_FACILITY_HIER_EN_CURR" "NAT_FACILITY_HIER_EN_CURR" 
        ON "ORDER_DETAIL_CURR"."FACILITY_ID" = "NAT_FACILITY_HIER_EN_CURR"."FACILITY_ID"

    INNER JOIN "GDYR_BI_VWS"."NAT_CUST_HIER_DESCR_EN_CURR" "T6" 
        ON "ORDER_DETAIL_CURR"."SOLD_TO_CUST_ID" = "T6"."SHIP_TO_CUST_ID"

    LEFT JOIN "NA_BI_VWS"."OPEN_ORDER_SCHDLN_CURR" "OPEN_ORDER_SCHDLN_CURR" 
        ON "ORDER_DETAIL_CURR"."SCHED_LINE_NBR" = "OPEN_ORDER_SCHDLN_CURR"."SCHED_LINE_NBR"
    	AND "ORDER_DETAIL_CURR"."ORDER_LINE_NBR" = "OPEN_ORDER_SCHDLN_CURR"."ORDER_LINE_NBR"
    	AND "ORDER_DETAIL_CURR"."ORDER_ID" = "OPEN_ORDER_SCHDLN_CURR"."ORDER_ID"

WHERE 
    NOT "OPEN_ORDER_SCHDLN_CURR"."ORDER_ID" IS NULL
	AND "OPEN_ORDER_SCHDLN_CURR"."OPEN_CNFRM_QTY" <> 0
	AND "ORDER_DETAIL_CURR"."PO_TYPE_ID" <> 'RO'
	AND "NAT_MATL_HIER_DESCR_EN_CURR"."PBU_NBR" IN ('01', '03')
	AND "ORDER_DETAIL_CURR"."FRST_RDD" < CURRENT_DATE