SELECT
    POL.ORDER_ID
    , POL.ORDER_LINE_NBR

    , POL.MATL_ID
    , M.PBU_NBR
    , POL.SHIP_TO_CUST_ID
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , CASE
        WHEN C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N307', 'N317', 'N336') 
                OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN ('30', '31'))
            THEN 'R'
        ELSE 'O'
        END OE_REPL_IND
    , CASE OE_REPL_IND
        WHEN 'R' THEN 'Replacement'
        WHEN 'O' THEN 'OE'
        ELSE ''
        END AS OE_REPL_DESC
    , CAST(CASE
        WHEN C.SALES_ORG_CD IN ('N303', 'N313', 'N323') --AND C.DISTR_CHAN_CD = '30'
            THEN 'X'
        --WHEN C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD <> '30'
            --THEN 'N'
        ELSE 'D'
        END AS CHAR(1)) AS DOMESTIC_EXPORT_IND

    , CASE
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '01' AND C.OWN_CUST_ID = '00A0003149' THEN 1
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '01' AND C.OWN_CUST_ID = '00A0006582' THEN 2
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '01' AND C.OWN_CUST_ID = '00A0003088' THEN 3
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '01' AND C.OWN_CUST_ID = '00A0006929' THEN 4
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '01' AND C.OWN_CUST_ID = '00A0003047' THEN 5
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '01' AND C.OWN_CUST_ID = '00A0000632' THEN 6
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '01' AND C.OWN_CUST_ID = '00A0003117' THEN 7
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '01' AND C.OWN_CUST_ID = '00A0005262' THEN 8
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '01' AND C.OWN_CUST_ID = '00A0009337' THEN 9
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '01' AND C.OWN_CUST_ID = '00A0009994' THEN 10
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '01' AND C.OWN_CUST_ID = '00A0006932' THEN 11
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '01' AND C.OWN_CUST_ID = '00A0005041' THEN 12
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '01' AND C.OWN_CUST_ID = '00A0003158' THEN 13
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '01' AND C.OWN_CUST_ID = '00A0003085' THEN 14
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '01' AND C.OWN_CUST_ID = '00A0003084' THEN 15

        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '03' AND C.OWN_CUST_ID = '00A0006677' THEN 1
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '03' AND C.OWN_CUST_ID = '00A0006582' THEN 2
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '03' AND C.OWN_CUST_ID = '00A0009337' THEN 3
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '03' AND C.OWN_CUST_ID = '00A0006090' THEN 4
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '03' AND C.OWN_CUST_ID = '00A0003047' THEN 5
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '03' AND C.OWN_CUST_ID = '00A0005262' THEN 6
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '03' AND C.OWN_CUST_ID = '00A0005037' THEN 7
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '03' AND C.OWN_CUST_ID = '00A0006024' THEN 8
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '03' AND C.OWN_CUST_ID = '00A0005041' THEN 9
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '03' AND C.OWN_CUST_ID = '00A0008463' THEN 10
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '03' AND C.OWN_CUST_ID = '00A0006691' THEN 11
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '03' AND C.OWN_CUST_ID = '00A0003117' THEN 12
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '03' AND C.OWN_CUST_ID = '00A0008485' THEN 13
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '03' AND C.OWN_CUST_ID = '00A0006054' THEN 14
        WHEN OE_REPL_IND = 'R' AND DOMESTIC_EXPORT_IND = 'D' AND M.PBU_NBR = '03' AND C.OWN_CUST_ID = '00A0006199' THEN 15

        WHEN DOMESTIC_EXPORT_IND = 'X' THEN 50
    
        WHEN OE_REPL_IND = 'O' AND DOMESTIC_EXPORT_IND = 'D' THEN 90
        WHEN OE_REPL_IND = 'O' AND DOMESTIC_EXPORT_IND = 'X' THEN 95
        ELSE 75
        END AS RPT_OWN_CUST_SORT_KEY

    , CASE
        WHEN RPT_OWN_CUST_SORT_KEY < 16 THEN C.OWN_CUST_NAME
        WHEN RPT_OWN_CUST_SORT_KEY = 50 THEN 'Export'
        WHEN RPT_OWN_CUST_SORT_KEY = 75 THEN 'All Other Replacement'
        WHEN RPT_OWN_CUST_SORT_KEY = 90 THEN 'Total Domestic OE'
        WHEN RPT_OWN_CUST_SORT_KEY = 90 THEN 'Total Export OE'
        ELSE ''
        END AS RPT_OWN_CUST_DESC

    , CAST(CASE 
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 1 THEN 0.90
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 2 THEN 0.80
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 3 THEN 0.90
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 4 THEN 0.85
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 5 THEN 0.80
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 6 THEN 0.85
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 7 THEN 0.80
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 8 THEN 0.80
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 9 THEN 0.85
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 10 THEN 0.85
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 11 THEN 0.85
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 12 THEN 0.85
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 13 THEN 0.85
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 14 THEN 0.70
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 15 THEN 0.70
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY IN (16, 17) THEN 0.81

        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-01-01' AS DATE) THEN 0.68
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-02-01' AS DATE) THEN 0.71
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-03-01' AS DATE) THEN 0.78
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-04-01' AS DATE) THEN 0.82
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-05-01' AS DATE) THEN 0.85
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-06-01' AS DATE) THEN 0.85
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-07-01' AS DATE) THEN 0.84
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-08-01' AS DATE) THEN 0.80
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-09-01' AS DATE) THEN 0.80
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-10-01' AS DATE) THEN 0.78
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-11-01' AS DATE) THEN 0.75
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-12-01' AS DATE) THEN 0.70
        END AS DECIMAL(15,3)) AS FRDD_TGT

    , CAST(CASE 
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 1 THEN NULL
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 2 THEN 0.85
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 3 THEN NULL
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 4 THEN 0.90
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 5 THEN 0.85
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 6 THEN NULL
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 7 THEN 0.85
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 8 THEN 0.85
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 9 THEN 0.90
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 10 THEN 0.90
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 11 THEN 0.90
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 12 THEN 0.90
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 13 THEN 0.90
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 14 THEN 0.90
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY = 15 THEN 0.90
        WHEN M.PBU_NBR = '01' AND RPT_OWN_CUST_SORT_KEY IN (16, 17) THEN 0.91

        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-01-01' AS DATE) THEN 0.86
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-02-01' AS DATE) THEN 0.89
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-03-01' AS DATE) THEN 0.91
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-04-01' AS DATE) THEN 0.92
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-05-01' AS DATE) THEN 0.92
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-06-01' AS DATE) THEN 0.91
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-07-01' AS DATE) THEN 0.90
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-08-01' AS DATE) THEN 0.89
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-09-01' AS DATE) THEN 0.88
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-10-01' AS DATE) THEN 0.89
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-11-01' AS DATE) THEN 0.89
        WHEN M.PBU_NBR = '03' AND REPORTING_DT - EXTRACT(DAY FROM REPORTING_DT) + 1 = CAST('2015-12-01' AS DATE) THEN 0.88
        END AS DECIMAL(15,3)) AS FCDD_TGT

    , POL.SHIP_FACILITY_ID

    , POL.CMPL_DT AS FRDD_CMPL_DT
    , POL.CMPL_IND AS FRDD_CMPL_IND
    , POL.FPDD_CMPL_DT AS FCDD_CMPL_DT
    , POL.FPDD_CMPL_IND AS FCDD_CMPL_IND

    , ZEROIFNULL(POL.CURR_ORD_QTY) AS FRDD_ORDER_QTY
    , ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY) AS FRDD_HIT_QTY
    , ZEROIFNULL(POL.CURR_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY) AS FRDD_ONTIME_QTY

    , ZEROIFNULL(POL.FPDD_ORD_QTY) AS FCDD_ORDER_QTY
    , ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY) AS FCDD_HIT_QTY
    , ZEROIFNULL(POL.FPDD_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY) AS FCDD_ONTIME_QTY

    , CASE
        WHEN EXTRACT(DAY FROM CURRENT_DATE) < 8
            THEN CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE)
        ELSE CURRENT_DATE-1
        END AS REPORTING_DT

FROM NA_BI_VWS.PRFCT_ORD_LINE POL

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = POL.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID

WHERE
    M.PBU_NBR IN ('01', '03')
    AND M.MKT_AREA_NBR <> '04'
