SELECT
    DDC.FISCAL_YR
    , DDC.DELIV_ID
    , DDC.DELIV_LINE_NBR
    
    , DDC.BILL_LADING_ID
    , CDM.MSTR_BOL
    , CDM.SHIP_BOL
    
    , DDC.ORDER_FISCAL_YR
    , DDC.ORDER_ID
    , DDC.ORDER_LINE_NBR
    
    , DDC.SALES_ORG_CD
    , DDC.DISTR_CHAN_CD
    , DDC.CUST_GRP_ID
    , DDC.CUST_GRP2_CD
    
    , DDC.SHIP_TO_CUST_ID
    , CUST.SHIP_TO_CUST_ID || ' - ' || CUST.CUST_NAME AS SHIP_TO_CUST
    , CUST.OWN_CUST_ID || ' - ' || CUST.OWN_CUST_NAME AS OWN_CUST
    
    , CUST.PRIM_SHIP_FACILITY_ID
    , DDC.DELIV_LINE_FACILITY_ID
    , DDC.SHIP_PT_ID
    
    , DDC.MATL_ID
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , MATL.PBU_NBR || ' - ' || MATL.PBU_NAME AS PBU
    , MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME AS CTGY
    , MATL.MKT_CTGY_PROD_GRP_NAME AS SLS_TIER
    
    , DDC.QTY_UNIT_MEAS_ID
    , DDC.DELIV_QTY
    
    , DDC.WT_UNIT_MEAS_ID
    , DDC.GROSS_WT
    
    , DDC.VOL_UNIT_MEAS_ID
    , DDC.VOL
    
    , ODC.PLN_MATL_AVL_DT AS MAD_FIRST_DATE
    , DDC.DELIV_NOTE_CREA_DT
    , ODC.PLN_GOODS_ISS_DT AS PGI_FIRST_DATE
    , DDC.PLN_GOODS_MVT_DT
    , DDC.ACTL_GOODS_ISS_DT
    , ODC.PLN_DELIV_DT AS FIRST_DATE
    , DDC.DELIV_DT

    , POL.FCMAD AS FCDD_FMAD
    , POL.FCPGI_DT AS FCDD_FPGI
    , POL.FRST_PROM_DELIV_DT AS FCDD
    
    , ZEROIFNULL(POL.FPDD_ORD_QTY) AS FCDD_ORDER_QTY
    , ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY) AS FCDD_HIT_QTY
    , ZEROIFNULL(POL.FPDD_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY) AS FCDD_ONTIME_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_CARR_QTY) + ZEROIFNULL(POL.OT_FPDD_HIT_WI_QTY) AS PHYS_LOG_HIT_QTY
    
    , POL.A_IND
    , POL.R_IND
    , POL.CUST_APPT_DT
    , POL.MAX_SAP_DELIV_DT
    , POL.MAX_EDI_DELIV_DT
    , POL.ACTL_DELIV_DT
    
    , CDM.TM_CARR_ID
    , CDM.CARR_SCAC_ID
    , CDM.CARR_STOP_QTY
    , CDM.CARR_ACCEPT_TS
    , CDM.READYBYPLN_DT
    , CDM.ARRV_AT_PKUP_TS
    , CDM.DEPART_FROM_PKUP_TS
    , CDM.REQ_DELIV_DT
    , CDM.PLN_ARRV_TS
    , CDM.LPC_APPT_TS
    , CDM.ARRV_AT_DELIV_TS
    
    , DDC.GOODS_ISS_IND
    , DDC.SHIP_COND_ID
    , DDC.RTG_ID
    , DDC.TERMS_ID
    , DDC.UNLD_PT_CD
    , DDC.SPCL_PROC_ID
    , DDC.PRM_SHIP_CARR_CD
    , DDC.TRANSP_VEH_NO
    , DDC.SRC_CRT_USR_ID
    
    , DDC.DELIV_CAT_ID
    , DDC.DELIV_TYPE_ID
    
FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID
        AND CUST.OWN_CUST_ID = '00A0006929'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_dESCR_EN_CURR MATL
        ON MATL.MATL_ID = DDC.MATL_ID
        AND MATL.PBU_NBR IN ('01', '03')
        AND MATL.EXT_MATL_GRP_ID = 'TIRE'

    INNER JOIN NA_BI_VWS.ORDER_DETAIL_CURR ODC
        ON ODC.ORDER_FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND ODC.ORDER_ID = DDC.ORDER_ID
        AND ODC.ORDER_LINE_NBR = DDC.ORDER_LINE_NBR
        AND ODC.SCHED_LINE_NBR = 1
        AND ODC.ORDER_CAT_ID = 'C'
        AND ODC.RO_PO_TYPE_IND = 'N'
        AND ODC.ORDER_FISCAL_YR >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 AS CHAR(4))

    LEFT OUTER JOIN NA_BI_VWS.TM_CARR_DELIV_MSG_CURR CDM
        ON CDM.SAP_DELIV_FISCAL_YR = DDC.FISCAL_YR
        AND CDM.SAP_DELIV_ID = DDC.DELIV_ID
        AND CDM.TM_DEST_TYP_CD = 'CUST'
        AND CDM.REQ_DELIV_DT >= DATE '2014-01-01'

    INNER JOIN NA_BI_VWS.PRFCT_ORD_LINE POL
        ON POL.ORDER_ID = DDC.ORDER_ID
        AND POL.ORDER_LINE_NBR = DDC.ORDER_LINE_NBR
        AND POL.FPDD_CMPL_IND = 1
        AND POL.FPDD_CMPL_DT BETWEEN DATE '2014-09-01' AND DATE '2014-09-30'
        AND POL.FRST_PROM_DELIV_DT IS NOT NULL
        AND POL.PRFCT_ORD_FPDD_HIT_SORT_KEY <> 99
        AND (POL.OT_FPDD_HIT_CARR_QTY > 0 OR POL.OT_FPDD_HIT_WI_QTY > 0)

WHERE
    DDC.DELIV_CAT_ID = 'J'
    AND DDC.DELIV_QTY > 0
    AND DDC.GOODS_ISS_IND = 'Y'
    AND DDC.ACTL_GOODS_ISS_DT IS NOT NULL
    AND DDC.ACTL_GOODS_ISS_DT BETWEEN DATE '2014-08-01' AND CURRENT_DATE-1

ORDER BY
    1, 2, 3


