SELECT
    INV.DAY_DT AS BUS_DT,
    INV.FACILITY_ID || ' - ' || FAC.XTND_NAME AS FACILITY,
    
    INV.MATL_ID,
    MATL.DESCR,
    MATL.PBU_NBR || ' - ' || MATL.PBU_NAME AS PBU,
    MATL.MKT_AREA_NBR || ' - ' || MATL.MKT_AREA_NAME AS MKT_AREA,
    
    INV.TOT_QTY,
    INV.COMMIT_QTY,
    INV.UN_COMMIT_QTY,
    INV.AVAIL_TO_PROM_QTY,
    INV.IN_PROS_TO_CUST_QTY,
    INV.BACK_ORDER_QTY,
    INV.NET_BACK_ORDER_QTY,
    INV.BLOCKED_STK_QTY,
    INV.RSVR_QTY,
    
    INV.STO_INBOUND_QTY,
    INV.STO_OUTBOUND_QTY,
    INV.IN_TRANS_QTY,
    
    INV.QUAL_INSP_QTY,
    INV.BLOCKED_STK_QTY,
    INV.RSTR_QTY,
    INV.STK_RET_QTY,
    INV.UNRSTR_QTY,
    INV.EST_DAYS_SUPPLY

FROM NA_BI_VWS.INVENTORY INV

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = INV.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_HIER_EN_CURR FAC
        ON FAC.FACILITY_ID = INV.FACILITY_ID

WHERE
    INV.MATL_ID LIKE '%000?MaterialID'
    AND INV.FACILITY_ID = '?FacilityID'
    AND INV.DAY_DT BETWEEN (CURRENT_DATE - 60) AND CURRENT_DATE

ORDER BY
    INV.DAY_DT DESC

