SELECT
    CAST( CASE WHEN P.MAX_EDI_DELIV_DT IS NULL THEN 'MISSING' ELSE 'PRESENT' END AS VARCHAR(10) ) AS EDI_IND,
    CAST( SUBSTR( CAST( P.CMPL_DT AS CHAR(10) ), 1, 7 ) || '-01' AS DATE ) AS FRDD_COMPLETE_MONTH,
    -- CAST( SUBSTR( CAST( P.FPDD_CMPL_DT AS CHAR(10) ), 1, 7 ) || '-01' AS DATE ) AS FCDD_COMPLETE_MONTH,
    PRFCT_ORD_HIT_DESC,
    PRFCT_ORD_FPDD_HIT_DESC,
    
    SUM( ZEROIFNULL( CURR_ORD_QTY ) ) AS CURR_ORD_QTY,
    SUM( ZEROIFNULL( PRFCT_ORD_HIT_QTY ) ) AS FRDD_HIT_QTY,
    SUM( ZEROIFNULL( PRFCT_ORD_QTY ) ) AS FRDD_ONTIME_QTY,
    SUM( ZEROIFNULL( PRFCT_ORD_FPDD_HIT_QTY ) ) AS FCDD_HIT_QTY,
    SUM( ZEROIFNULL( PRFCT_ORD_FPDD_QTY ) ) AS FCDD_ONTIME_QTY
    
FROM NA_BI_VWS.PRFCT_ORD_LINE P

WHERE
    P.CMPL_IND = 1
    AND P.CMPL_DT BETWEEN DATE '2013-01-01' AND CURRENT_DATE - 1
    AND P.PBU_NBR = '01'

GROUP BY
    EDI_IND,
    FRDD_COMPLETE_MONTH,
    PRFCT_ORD_HIT_DESC,
    PRFCT_ORD_FPDD_HIT_DESC