SELECT
    OTD.METRIC_TYPE
    , OTD.COMPLETE_MTH
    
    , OTD.MATL_ID
    , OTD.MATL_DESCR
    
    , OTD.PBU_NBR
    , OTD.PBU
    
    , OTD.CATEGORY
    , OTD.TIER

    , OTD.OWN_CUST_ID || ' - ' || OTD.OWN_CUST_NAME AS OWN_CUST
    , OTD.TIRE_CUST_TYP_CD
    , OTD.SHIP_FACILITY_NAME AS SHIP_FACILITY

    , SUM(OTD.ORIG_ORDER_QTY) AS ORIG_ORDER_QTY
    , SUM(OTD.CANCEL_QTY) AS CANCEL_QTY
    , SUM(OTD.ORDER_QTY) AS ORDER_QTY
    , SUM(OTD.HIT_QTY) AS HIT_QTY
    , SUM(OTD.ONTIME_QTY) AS ONTIME_QTY
    , SUM(OTD.REL_LATE_QTY) AS REL_LATE_QTY
    , SUM(OTD.REL_ONTIME_QTY) AS REL_ONTIME_QTY
    , SUM(OTD.COMMIT_ONTIME_QTY) AS COMMIT_ONTIME_QTY
    , SUM(OTD.DELIV_LATE_QTY) AS DELIV_LATE_QTY
    , SUM(OTD.DELIV_ONTIME_QTY) AS DELIV_ONTIME_QTY
    , SUM(OTD.RETURN_HIT_QTY) AS RETURN_HIT_QTY
    , SUM(OTD.CLAIM_HIT_QTY) AS CLAIM_HIT_QTY
    , SUM(OTD.FREIGHT_POLICY_HIT_QTY) AS FREIGHT_POLICY_HIT_QTY
    , SUM(OTD.PHYS_LOG_HIT_QTY) AS PHYS_LOG_HIT_QTY
    , SUM(OTD.MAN_BLK_HIT_QTY) AS MAN_BLK_HIT_QTY
    , SUM(OTD.CREDIT_HOLD_HIT_QTY) AS CREDIT_HOLD_HIT_QTY
    , SUM(OTD.NO_STOCK_HIT_QTY) AS NO_STOCK_HIT_QTY
    , SUM(OTD.CANCEL_HIT_QTY) AS CANCEL_HIT_QTY
    , SUM(OTD.CUST_GEN_HIT_QTY) AS CUST_GEN_HIT_QTY
    , SUM(OTD.MAN_REL_CUST_GEN_HIT_QTY) AS MAN_REL_CUST_GEN_HIT_QTY
    , SUM(OTD.MAN_REL_HIT_QTY) AS MAN_REL_HIT_QTY
    , SUM(OTD.OTHER_HIT_QTY) AS OTHER_HIT_QTY

FROM (

    SELECT
        CAST('FRDD' AS CHAR(4)) AS METRIC_TYPE
        , POL.ORDER_ID AS ORDER_ID
        , POL.ORDER_LINE_NBR AS ORDER_LINE_NBR
        , POL.CMPL_IND AS COMPLETE_IND
        , POL.CMPL_DT AS COMPLETE_DT
        , COMPLETE_DT - (EXTRACT(DAY FROM COMPLETE_DT) - 1) AS COMPLETE_MTH
        , POL.NO_STK_DT AS NO_STOCK_DATE
        , NO_STOCK_DATE - (EXTRACT(DAY FROM NO_STOCK_DATE) - 1) AS NO_STOCK_MONTH
        , POL.MATL_ID AS MATL_ID
        , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
        , MATL.PBU_NBR
        , MATL.PBU_NBR || ' - ' || MATL.PBU_NAME AS PBU
        , MATL.MKT_AREA_NBR || ' - ' || MATL.MKT_AREA_NAME AS MKT_AREA
        , MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY
        , MATL.MKT_CTGY_PROD_GRP_NAME AS TIER
        , POL.SHIP_TO_CUST_ID
        , CUST.CUST_NAME AS SHIP_TO_CUST_NAME
        , CUST.OWN_CUST_ID
        , CUST.OWN_CUST_NAME
        , CUST.TIRE_CUST_TYP_CD
        , POL.SHIP_FACILITY_ID AS SHIP_FACILITY_ID
        , FAC.FACILITY_ID || ' - ' || FAC.FACILITY_NAME AS SHIP_FACILITY_NAME
        , POL.DELIV_PRTY_ID
        , POL.DELIV_BLK_IND
        , POL.CREDIT_HOLD_FLG
        , POL.NUM_DELIV_LINES
        , POL.CAN_REJ_REAS_ID
        , POL.PO_TYPE_ID
        , POL.CANCEL_IND
        , POL.CUST_GRP_ID
        , POL.CUST_GRP2_CD
        , POL.SHIP_COND_ID
        , POL.A_IND
        , POL.R_IND
        , POL.SPCL_PROC_ID
        , POL.MAX_CARR_SCAC_ID
        , POL.ORDER_DT
        , POL.OL_DT
        , POL.FMAD_DT AS METRIC_FMAD
        , POL.FPGI_DT AS METRIC_FPGI
        , POL.REQ_DELIV_DT AS METRIC_DT

        , POL.REQ_DELIV_DT AS FRDD
        , POL.FRST_PROM_DELIV_DT AS FCDD
        , POL.MAX_DELIV_NOTE_CREA_DT
        , POL.MAX_EDI_DELIV_DT
        , POL.MAX_SAP_DELIV_DT
        , POL.ACTL_DELIV_DT
        , POL.CUST_APPT_DT

        , ZEROIFNULL(POL.ORIG_ORD_QTY) AS ORIG_ORDER_QTY
        , ZEROIFNULL(POL.CANCEL_QTY) AS CANCEL_QTY
        , ZEROIFNULL(POL.CURR_ORD_QTY) AS ORDER_QTY
        , ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY) AS HIT_QTY
        , ZEROIFNULL(POL.CURR_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY) AS ONTIME_QTY
        , ZEROIFNULL(POL.REL_LATE_QTY) AS REL_LATE_QTY
        , ZEROIFNULL(POL.REL_ONTIME_QTY) AS REL_ONTIME_QTY
        , ZEROIFNULL(POL.COMMIT_ONTIME_QTY) AS COMMIT_ONTIME_QTY
        , ZEROIFNULL(POL.DELIV_LATE_QTY) AS DELIV_LATE_QTY
        , ZEROIFNULL(POL.DELIV_ONTIME_QTY) AS DELIV_ONTIME_QTY
        , ZEROIFNULL(POL.NE_HIT_RT_QTY) AS RETURN_HIT_QTY
        , ZEROIFNULL(POL.NE_HIT_CL_QTY) AS CLAIM_HIT_QTY
        , ZEROIFNULL(POL.OT_HIT_FP_QTY) AS FREIGHT_POLICY_HIT_QTY
        , ZEROIFNULL(POL.OT_HIT_CARR_PICKUP_QTY) + ZEROIFNULL(POL.OT_HIT_WI_QTY) AS PHYS_LOG_HIT_QTY
        , ZEROIFNULL(POL.OT_HIT_MB_QTY) AS MAN_BLK_HIT_QTY
        , ZEROIFNULL(POL.OT_HIT_CH_QTY) AS CREDIT_HOLD_HIT_QTY
        , ZEROIFNULL(POL.IF_HIT_NS_QTY) AS NO_STOCK_HIT_QTY
        , ZEROIFNULL(POL.IF_HIT_CO_QTY) AS CANCEL_HIT_QTY
        , ZEROIFNULL(POL.OT_HIT_CG_QTY) AS CUST_GEN_HIT_QTY
        , ZEROIFNULL(POL.OT_HIT_CG_99_QTY) AS MAN_REL_CUST_GEN_HIT_QTY
        , ZEROIFNULL(POL.OT_HIT_99_QTY) AS MAN_REL_HIT_QTY
        , ZEROIFNULL(POL.OT_HIT_LO_QTY) AS OTHER_HIT_QTY

    FROM NA_BI_VWS.PRFCT_ORD_LINE POL

        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID
            --AND CUST.CUST_GRP_ID <> '3R'

        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
            ON MATL.MATL_ID = POL.MATL_ID
            AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
            AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')

        INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FAC
            ON FAC.FACILITY_ID = POL.SHIP_FACILITY_ID

        INNER JOIN NA_BI_VWS.ORDER_DETAIL ODS
            ON ODS.ORDER_FISCAL_YR >= CAST(EXTRACT(YEAR FROM CURRENT_DATE - 1)-1 AS CHAR(4))
            AND ODS.ORDER_ID = POL.ORDER_ID
            AND ODS.ORDER_LINE_NBR = POL.ORDER_LINE_NBR
            AND ODS.SCHED_LINE_NBR = 1
            AND ODS.EXP_DT = DATE '5555-12-31'
            AND ODS.ORDER_CAT_ID = 'C'
            AND ODS.PO_TYPE_ID <> 'RO'

    WHERE
        POL.CMPL_IND = 1
        AND POL.CMPL_DT BETWEEN
            ADD_MONTHS((CURRENT_DATE-1), -3) - (EXTRACT(DAY FROM ADD_MONTHS((CURRENT_DATE-1), -3)) - 1)
            AND (CURRENT_DATE-1)
        AND POL.PRFCT_ORD_HIT_SORT_KEY <> 99

    UNION ALL

    SELECT
        CAST('FCDD' AS CHAR(4)) AS METRIC_TYPE
        , POL.ORDER_ID AS ORDER_ID
        , POL.ORDER_LINE_NBR AS ORDER_LINE_NBR
        , POL.FPDD_CMPL_IND AS COMPLETE_IND
        , POL.FPDD_CMPL_DT AS COMPLETE_DT
        , COMPLETE_DT - (EXTRACT(DAY FROM COMPLETE_DT) - 1) AS COMPLETE_MTH
        , POL.FPDD_NO_STK_DT AS NO_STOCK_DATE
        , NO_STOCK_DATE - (EXTRACT(DAY FROM NO_STOCK_DATE) - 1) AS NO_STOCK_MONTH
        , POL.MATL_ID AS MATL_ID
        , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
        , MATL.PBU_NBR
        , MATL.PBU_NBR || ' - ' || MATL.PBU_NAME AS PBU
        , MATL.MKT_AREA_NBR || ' - ' || MATL.MKT_AREA_NAME AS MKT_AREA
        , MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY
        , MATL.MKT_CTGY_PROD_GRP_NAME AS TIER
        , POL.SHIP_TO_CUST_ID
        , CUST.CUST_NAME AS SHIP_TO_CUST_NAME
        , CUST.OWN_CUST_ID
        , CUST.OWN_CUST_NAME
        , CUST.TIRE_CUST_TYP_CD
        , POL.SHIP_FACILITY_ID AS SHIP_FACILITY_ID
        , FAC.FACILITY_ID || ' - ' || FAC.FACILITY_NAME AS SHIP_FACILITY_NAME
        , POL.DELIV_PRTY_ID
        , POL.DELIV_BLK_IND
        , POL.CREDIT_HOLD_FLG
        , POL.NUM_DELIV_LINES
        , POL.CAN_REJ_REAS_ID
        , POL.PO_TYPE_ID
        , POL.CANCEL_IND
        , POL.CUST_GRP_ID
        , POL.CUST_GRP2_CD
        , POL.SHIP_COND_ID
        , POL.A_IND
        , POL.R_IND
        , POL.SPCL_PROC_ID
        , POL.MAX_CARR_SCAC_ID
        , POL.ORDER_DT

        , POL.OL_DT
        , ODS.FC_MATL_AVL_DT AS METRIC_FMAD
        , POL.FCPGI_DT AS METRIC_FPGI
        , POL.FRST_PROM_DELIV_DT AS METRIC_DT

        , POL.REQ_DELIV_DT AS FRDD
        , POL.FRST_PROM_DELIV_DT AS FCDD
        , POL.MAX_DELIV_NOTE_CREA_DT
        , POL.MAX_EDI_DELIV_DT
        , POL.MAX_SAP_DELIV_DT
        , POL.ACTL_DELIV_DT
        , POL.CUST_APPT_DT

        , ZEROIFNULL(POL.ORIG_ORD_QTY) AS ORIG_ORDER_QTY
        , ZEROIFNULL(POL.CANCEL_QTY) AS CANCEL_QTY
        , ZEROIFNULL(POL.FPDD_ORD_QTY) AS ORDER_QTY
        , ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY) AS HIT_QTY
        , ZEROIFNULL(POL.FPDD_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY) AS ONTIME_QTY
        , ZEROIFNULL(POL.DELIV_FPDD_LATE_QTY) AS DELIV_LATE_QTY
        , ZEROIFNULL(POL.DELIV_FPDD_ONTIME_QTY) AS DELIV_ONTIME_QTY
        , ZEROIFNULL(POL.FPDD_COMMIT_ONTIME_QTY) AS COMMIT_ONTIME_QTY
        , ZEROIFNULL(POL.REL_FPDD_LATE_QTY) AS REL_LATE_QTY
        , ZEROIFNULL(POL.REL_FPDD_ONTIME_QTY) AS REL_ONTIME_QTY
        , ZEROIFNULL(POL.NE_FPDD_HIT_RT_QTY) AS RETURN_HIT_QTY
        , ZEROIFNULL(POL.NE_FPDD_HIT_CL_QTY) AS CLAIM_HIT_QTY
        , ZEROIFNULL(POL.OT_FPDD_HIT_FP_QTY) AS FREIGHT_POLICY_HIT_QTY
        , ZEROIFNULL(POL.OT_FPDD_HIT_CARR_QTY) + ZEROIFNULL(POL.OT_FPDD_HIT_WI_QTY) AS PHYS_LOG_HIT_QTY
        , ZEROIFNULL(POL.OT_FPDD_HIT_MB_QTY) AS MAN_BLK_HIT_QTY
        , ZEROIFNULL(POL.OT_FPDD_HIT_CH_QTY) AS CREDIT_HOLD_HIT_QTY
        , ZEROIFNULL(POL.IF_FPDD_HIT_NS_QTY) AS NO_STOCK_HIT_QTY
        , ZEROIFNULL(POL.IF_FPDD_HIT_CO_QTY) AS CANCEL_HIT_QTY
        , ZEROIFNULL(POL.OT_FPDD_HIT_CG_QTY) AS CUST_GEN_HIT_QTY
        , ZEROIFNULL(POL.OT_FPDD_HIT_CG_99_QTY) AS MAN_REL_CUST_GEN_HIT_QTY
        , ZEROIFNULL(POL.OT_FPDD_HIT_99_QTY) AS MAN_REL_HIT_QTY
        , ZEROIFNULL(POL.OT_FPDD_HIT_LO_QTY) AS OTHER_HIT_QTY

    FROM NA_BI_VWS.PRFCT_ORD_LINE POL

        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID
            --AND CUST.CUST_GRP_ID <> '3R'

        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
            ON MATL.MATL_ID = POL.MATL_ID
            AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
            AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')

        INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FAC
            ON FAC.FACILITY_ID = POL.SHIP_FACILITY_ID

        INNER JOIN NA_BI_VWS.ORDER_DETAIL ODS
            ON ODS.ORDER_FISCAL_YR >= CAST(EXTRACT(YEAR FROM CURRENT_DATE - 1)-1 AS CHAR(4))
            AND ODS.ORDER_ID = POL.ORDER_ID
            AND ODS.ORDER_LINE_NBR = POL.ORDER_LINE_NBR
            AND ODS.SCHED_LINE_NBR = 1
            AND ODS.EXP_DT = DATE '5555-12-31'
            AND ODS.ORDER_CAT_ID = 'C'
            AND ODS.PO_TYPE_ID <> 'RO'

    WHERE
        POL.FPDD_CMPL_IND = 1
        AND POL.FRST_PROM_DELIV_DT IS NOT NULL
        AND POL.FPDD_CMPL_DT BETWEEN
            ADD_MONTHS((CURRENT_DATE-1), -3) - (EXTRACT(DAY FROM ADD_MONTHS((CURRENT_DATE-1), -3)) - 1)
            AND (CURRENT_DATE-1)
        AND POL.PRFCT_ORD_FPDD_HIT_SORT_KEY <> 99

    ) OTD

GROUP BY
    OTD.METRIC_TYPE
    , OTD.COMPLETE_MTH
    , OTD.MATL_ID
    , OTD.MATL_DESCR
    , OTD.PBU_NBR
    , OTD.PBU
    , OTD.CATEGORY
    , OTD.TIER
    , OWN_CUST
    , OTD.TIRE_CUST_TYP_CD
    , SHIP_FACILITY

ORDER BY
    OTD.METRIC_TYPE
    , OTD.COMPLETE_MTH
    , OWN_CUST
    , OTD.MATL_ID
    , SHIP_FACILITY


