SELECT
    OD.ORDER_ID,
    OD.ORDER_LINE_NBR,
    OD.SCHED_LINE_NBR,
    
    OD.ORDER_DT,
    OD.FRST_RDD AS FRDD,
    OD.FRST_MATL_AVL_DT AS FRDD_FMAD,
    OD.FRST_PLN_GOODS_ISS_DT AS FRDD_FPGI,
    
    CAST( FCDD - ( FRDD - FRDD_FMAD ) AS DATE ) AS FCDD_FMAD,
    CAST( FCDD - ( FRDD - FRDD_FPGI ) AS DATE ) AS FCDD_FPGI,
    CASE
        WHEN OD.FRST_PROM_DELIV_DT < OD.FRST_RDD
            THEN OD.FRST_RDD
        ELSE OD.FRST_PROM_DELIV_DT 
    END AS FCDD,
    
    OD.SHIP_TO_CUST_ID,
    OD.SALES_ORG_CD,
    OD.DISTR_CHAN_CD,
    OD.CUST_GRP_ID,
    OD.CO_CD,
    OD.DIV_CD,
    NULLIF( OD.RPT_FRT_PLCY_CD, '' ) AS CUST_GRP2_CD,
    
    OD.MATL_ID,
    NULLIF( OD.ITEM_CAT_ID, '' ) AS ITEM_CAT_ID,
    
    NULLIF( OD.FACILITY_ID, '' ) AS FACILITY_ID,
    NULLIF( OD.SHIP_PT_ID, '' ) AS SHIP_PT_ID,
    NULLIF( OD.ROUTE_ID, '' ) AS ROUTE_ID,
    
    NULLIF( OD.ORDER_CAT_ID, '' ) AS ORDER_CAT_ID,
    NULLIF( OD.ORDER_TYPE_ID, '' ) AS ORDER_TYPE_ID,
    NULLIF( OD.PO_TYPE_ID, '' ) AS PO_TYPE_ID,
    NULLIF( OD.REJ_REAS_ID, '' ) AS REJ_REAS_ID,
    NULLIF( OD.SHIP_COND_ID, '' ) AS SHIP_COND_ID,
    NULLIF( OD.DELIV_BLK_CD, '' ) AS DELIV_BLK_CD,
    NULLIF( OD.DELIV_PRTY_ID, '' ) AS DELIV_PRTY_ID,
    NULLIF( OD.DELIV_GRP_CD, '' ) AS DELIV_GRP_CD,
    NULLIF( OD.SPCL_PROC_ID, '' ) AS SPCL_PROC_ID,
    
    CASE WHEN OD.CANCEL_IND = 'Y' THEN 'Y' END AS CANCEL_IND,
    CASE WHEN OD.RETURN_IND = 'Y' THEN 'Y' END AS RETURN_IND,
    CASE WHEN OD.DELIV_BLK_IND = 'Y' THEN 'Y' END AS DELIV_BLK_IND,
    
    ZEROIFNULL( OD.ORDER_QTY ) AS ORDER_QTY,
    ZEROIFNULL( OD.CNFRM_QTY ) AS CNFRM_QTY,
    CASE
        WHEN OD.PLN_DELIV_DT <= FRDD
            THEN OD.CNFRM_QTY
        ELSE 0
    END AS CNFRM_FRDD_ONTIME_QTY,
    CASE
        WHEN NULLIF( OD.DELIV_BLK_CD, '' ) IS NOT NULL
            THEN OD.CNFRM_QTY
        ELSE 0
    END AS DLV_BLK_CNFRM_QTY,
    CASE
        WHEN NULLIF( OD.DELIV_BLK_CD, '' ) IS NOT NULL AND OD.PLN_DELIV_DT <= FRDD
            THEN OD.CNFRM_QTY
        ELSE 0
    END AS DLV_BLK_ONTIME_CNFRM_QTY,
    OO.OPEN_CNFRM_QTY,
    OO.UNCNFRM_QTY,
    OO.BACK_ORDER_QTY,
    OO.WAIT_LIST_QTY,
    OO.DEFER_QTY,
    OO.TOTAL_OPEN_QTY

FROM NA_BI_VWS.ORDER_DETAIL OD

    LEFT OUTER JOIN ( 
            SELECT
                OPN.ORDER_FISCAL_YR,
                OPN.ORDER_ID,
                OPN.ORDER_LINE_NBR,
                OPN.EFF_DT,
                OPN.EXP_DT,
                OPN.INTRA_CMPNY_FLG,
                OPN.CREDIT_HOLD_FLG,
                OPN.SLS_QTY_UNIT_MEAS_ID AS QTY_UOM,
                SUM( CASE WHEN OPN.OPEN_ORDER_STATUS_CD = 'C' THEN OPN.OPEN_ORDER_QTY ELSE 0 END ) AS OPEN_CNFRM_QTY,
                SUM( CASE WHEN OPN.OPEN_ORDER_STATUS_CD = 'U' THEN OPN.OPEN_ORDER_QTY ELSE 0 END ) AS UNCNFRM_QTY,
                SUM( CASE WHEN OPN.OPEN_ORDER_STATUS_CD = 'B' THEN OPN.OPEN_ORDER_QTY ELSE 0 END ) AS BACK_ORDER_QTY,
                SUM( CASE WHEN OPN.OPEN_ORDER_STATUS_CD = 'W' THEN OPN.OPEN_ORDER_QTY ELSE 0 END ) AS WAIT_LIST_QTY,
                SUM( CASE WHEN OPN.OPEN_ORDER_STATUS_CD = 'D' THEN OPN.OPEN_ORDER_QTY ELSE 0 END ) AS DEFER_QTY,
                --SUM( CASE WHEN OPN.OPEN_ORDER_STATUS_CD IN ( 'C', 'U', 'B' ) THEN OPN.OPEN_ORDEr_QTY ELSE 0 END ) AS OPEN_QTY,
                SUM(  OPN.OPEN_ORDER_QTY ) AS TOTAL_OPEN_QTY
                
            FROM GDYR_VWS.OPEN_ORDER OPN
            
            WHERE
                OPN.SBU_ID = 2
                AND OPN.ORIG_SYS_ID = 2
                AND OPN.SRC_SYS_ID = 2
            
            GROUP BY
                OPN.ORDER_FISCAL_YR,
                OPN.ORDER_ID,
                OPN.ORDER_LINE_NBR,
                OPN.EFF_DT,
                OPN.EXP_DT,
                OPN.INTRA_CMPNY_FLG,
                OPN.CREDIT_HOLD_FLG,
                OPN.SLS_QTY_UNIT_MEAS_ID
            ) OO
        ON OO.ORDER_ID = OD.ORDER_ID
        AND OO.ORDER_LINE_NBR = OD.ORDER_LINE_NBR
        AND OD.FRST_MATL_AVL_DT BETWEEN OO.EFF_DT AND OO.EXP_DT

WHERE
    OD.FRST_MATL_AVL_DT BETWEEN OD.EFF_DT AND OD.EXP_DT
    AND OD.ORDER_CAT_ID = 'C'
    AND OD.PO_TYPE_ID <> 'RO'
    AND OD.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
    AND OD.CUST_GRP_ID <> '3R'

QUALIFY
    ROW_NUMBER() OVER ( PARTITION BY OD.ORDER_ID, OD.ORDER_LINE_NBR, OD.SCHED_LINE_NBR ORDER BY OD.FRST_MATL_AVL_DT DESC ) = 1