SELECT
    --OL.OWN_CUST_NAME || ' - ' || OL.OWN_CUST_ID AS OWN_CUST,
    OL.PBU_NBR || ' - ' || OL.PBU_NAME AS PBU,
    
    OL.FRDD_CMPL_MTH,
    
    CAST( OL.FRDD_TO_FCDD_INTERVAL_DAYS / 7 AS INTEGER ) AS FRDD_TO_FCDD_INTERVAL_WKS,
    
    COUNT( OL.ORDER_ID || OL.ORDER_LINE_NBR ) AS ORDER_LINE_COUNT,
    
    SUM( OL.ORIGINAL_ORDER_QTY ) AS ORIGINAL_ORDER_QTY,
    SUM( OL.CURRENT_ORDER_QTY ) AS CURRENT_ORDER_QTY,
    SUM( OL.FCDD_ORDER_QTY ) AS FCDD_ORDER_QTY,
    
    SUM( OL.FRDD_REL_LATE_QTY ) AS FRDD_REL_LATE_QTY,
    SUM( OL.FRDD_REL_ONTIME_QTY ) AS FRDD_REL_ONTIME_QTY,
    SUM( OL.FCDD_REL_LATE_QTY ) AS FCDD_REL_LATE_QTY,
    SUM( OL.FCDD_REL_ONTIME_QTY ) AS FCDD_REL_ONTIME_QTY,
    
    SUM( OL.FRDD_DELIV_LATE_QTY ) AS FRDD_DELIV_LATE_QTY,
    SUM( OL.FRDD_DELIV_ONTIME_QTY ) AS FRDD_DELIV_ONTIME_QTY,
    SUM( OL.FCDD_DELIV_LATE_QTY ) AS FCDD_DELIV_LATE_QTY,
    SUM( OL.FCDD_DELIV_ONTIME_QTY ) AS FCDD_DELIV_ONTIME_QTY,
    
    SUM( OL.FRDD_HIT_QTY ) AS FRDD_HIT_QTY,
    SUM( OL.FRDD_ONTIME_QTY ) AS FRDD_ONTIME_QTY,
    SUM( OL.FCDD_HIT_QTY ) AS FCDD_HIT_QTY,
    SUM( OL.FCDD_ONTIME_QTY ) AS FCDD_ONTIME_QTY

FROM (

    SELECT
        POL.ORDER_ID,
        POL.ORDER_LINE_NBR,
        
        CUST.OWN_CUST_ID,
        CUST.OWN_CUST_NAME,
        
        MATL.PBU_NBR,
        MATL.PBU_NAME,
        
        POL.SHIP_FACILITY_ID AS FACILITY_ID,
        
        POL.ORDER_DT,
        --POL.CMPL_DT AS FRDD_CMPL_DT,
        CAL.MONTH_DT AS FRDD_CMPL_MTH,
        -- POL.FPDD_CMPL_DT AS FCDD_CMPL_DT,
        POL.REQ_DELIV_DT AS FRDD,
        CASE
            WHEN POL.FRST_PROM_DELIV_DT < POL.REQ_DELIV_DT
                THEN REQ_DELIV_DT
            ELSE POL.FRST_PROM_DELIV_DT
        END AS FCDD,        
        CAST( FCDD - FRDD AS INTEGER ) FRDD_TO_FCDD_INTERVAL_DAYS,
        
        SUM( POL.ORIG_ORD_QTY ) AS ORIGINAL_ORDER_QTY,
        SUM( POL.CURR_ORD_QTY ) AS CURRENT_ORDER_QTY,
        SUM( POL.FPDD_ORD_QTY ) AS FCDD_ORDER_QTY,

        SUM( POL.REL_LATE_QTY ) AS FRDD_REL_LATE_QTY,
        SUM( POL.REL_ONTIME_QTY ) AS FRDD_REL_ONTIME_QTY,
        SUM( POL.REL_FPDD_LATE_QTY ) AS FCDD_REL_LATE_QTY,
        SUM( POL.REL_FPDD_ONTIME_QTY ) AS FCDD_REL_ONTIME_QTY,
        
        SUM( POL.DELIV_LATE_QTY ) AS FRDD_DELIV_LATE_QTY,
        SUM( POL.DELIV_ONTIME_QTY ) AS FRDD_DELIV_ONTIME_QTY,
        SUM( POL.DELIV_FPDD_LATE_QTY ) AS FCDD_DELIV_LATE_QTY,
        SUM( POL.DELIV_FPDD_ONTIME_QTY ) AS FCDD_DELIV_ONTIME_QTY,
        
        SUM( POL.PRFCT_ORD_HIT_QTY ) AS FRDD_HIT_QTY,
        SUM( POL.PRFCT_ORD_QTY ) AS FRDD_ONTIME_QTY,
        SUM( POL.PRFCT_ORD_FPDD_HIT_QTY ) AS FCDD_HIT_QTY,
        SUM( POL.PRFCT_ORD_FPDD_QTY ) AS FCDD_ONTIME_QTY
    
    FROM NA_BI_VWS.PRFCT_ORD_LINE POL
    
        INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
            ON CAL.DAY_DATE = POL.CMPL_DT
            AND CAL.DAY_DATE BETWEEN CAST( '2013-01-01' AS DATE ) AND ( CURRENT_DATE - 1 )
    
        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID
            AND CUST.SALES_ORG_CD NOT IN ( 'N302', 'N312', 'N322' )
    
        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
            ON MATL.MATL_ID = POL.MATL_ID
            AND MATL.EXT_MATL_GRP_ID = 'TIRE'
            AND MATL.PBU_NBR = '01'    
    
    WHERE
        POL.FPDD_CMPL_IND = 1
        AND POL.FRST_PROM_DELIV_DT IS NOT NULL
    
    GROUP BY
        POL.ORDER_ID,
        POL.ORDER_LINE_NBR,
        
        CUST.OWN_CUST_ID,
        CUST.OWN_CUST_NAME,
        
        MATL.PBU_NBR,
        MATL.PBU_NAME,
        
        FACILITY_ID,
        
        POL.ORDER_DT,
        
        FRDD_CMPL_MTH,
        
        FRDD,
        FCDD,        
        FRDD_TO_FCDD_INTERVAL_DAYS
    
    HAVING
        ( FCDD_HIT_QTY + FCDD_ONTIME_QTY ) > 0

    ) OL

GROUP BY
    --OWN_CUST,
    PBU,
    
    OL.FRDD_CMPL_MTH,
    
    FRDD_TO_FCDD_INTERVAL_WKS

ORDER BY
    -- OWN_CUST,
    PBU,
    OL.FRDD_CMPL_MTH,
    FRDD_TO_FCDD_INTERVAL_WKS
    ;