
SELECT
    DD.SHIP_TO_CUST_ID,
    DD.SHIP_TO_CUST_NAME,
    DD.ACTL_GOODS_ISS_DT,
    DD.QTY_UNIT_MEAS_ID,
    SUM( DD.DELIV_QTY ) AS DELIV_QTY,
    DD.WT_UNIT_MEAS_ID,
    SUM( DD.NET_WT ) AS NET_WT,
    SUM( DD.GROSS_WT ) AS GROSS_WT,
    DD.VOL_UNIT_MEAS_ID,
    SUM( DD.VOL ) AS VOLUME

FROM (

SELECT
    DDC.DELIV_ID,
    DDC.DELIV_LINE_NBR,
    DDC.ORDER_ID,
    DDC.ORDER_LINE_NBR,
    
    DDC.SHIP_TO_CUST_ID,
    CUST.CUST_NAME AS SHIP_TO_CUST_NAME,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,
    CUST.PRIM_SHIP_FACILITY_ID,
    
    CASE
        WHEN CUST.PRIM_SHIP_FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID
            THEN 'Primary Facility'
        ELSE 'Not Primary Facility'
    END AS PRIM_SHIP_FACILITY_TEST,
    DDC.CUST_GRP_ID,
    DDC.CUST_GRP2_CD,
    DDC.DELIV_PRTY_ID,
    DDC.DELIV_TYPE_ID,
    DDC.DELIV_CAT_ID,
    DDC.FACILITY_ID,
    DDC.DELIV_LINE_FACILITY_ID,
    DDC.SHIP_PT_ID,
    DDC.SHIP_FACILITY_ID,
    DDC.PRTL_DLVY_CD,
    DDC.SHIP_COND_ID,
    DDC.RTG_ID,
    DDC.TERMS_ID,
    DDC.UNLD_PT_CD,
    DDC.SPCL_PROC_ID,
    DDC.BILL_LADING_ID,
    
    DDC.MATL_ID,
    MATL.MATL_NO_8,
    MATL.DESCR,
    MATL.PBU_NBR,
    MATL.PBU_NAME,
    MATL.EXT_MATL_GRP_ID,
    DDC.ITEM_CAT_ID,
    
    DDC.QTY_UNIT_MEAS_ID,
    DDC.DELIV_QTY,
    DDC.WT_UNIT_MEAS_ID,
    DDC.NET_WT,
    DDC.GROSS_WT,
    DDC.VOL_UNIT_MEAS_ID,
    DDC.VOL,
    
    DDC.DELIV_NOTE_CREA_DT,
    DDC.DELIV_LINE_CREA_DT,
    DDC.TRANSP_PLN_DT,
    DDC.LOAD_DT,
    DDC.ACTL_GOODS_ISS_DT,
    DDC.DELIV_DT
    
FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = DDC.MATL_ID

WHERE
    DDC.SHIP_TO_CUST_ID = '0000156815'
    AND DDC.ACTL_GOODS_ISS_DT >= CAST( ( EXTRACT( YEAR FROM CURRENT_DATE ) || '-02-01' )AS DATE ) 
    AND DDC.ACTL_GOODS_ISS_DT IS NOT NULL
    
    ) DD

GROUP BY
    DD.SHIP_TO_CUST_ID,
    DD.SHIP_TO_CUST_NAME,
    DD.QTY_UNIT_MEAS_ID,
    DD.ACTL_GOODS_ISS_DT,
    DD.WT_UNIT_MEAS_ID,
    DD.VOL_UNIT_MEAS_ID
 
ORDER BY
    DD.ACTL_GOODS_ISS_DT