SELECT
    SQ.MATL_ID,
    SQ.PBU_NBR,
    SQ.FACILITY_ID,
    SQ.NO_STK_MTH,
    SQ.CMPL_MTH,
    SUM( ZEROIFNULL( SQ.IF_HIT_NS_QTY ) ) AS TOT_NS_HIT_QTY,
    MAX( ZEROIFNULL( FAC.UNRSTR_QTY ) ) AS UNRSTR_QTY

FROM (

SELECT
    POL.ORDER_ID,
    POL.ORDER_LINE_NBR,
    POL.NO_STK_DT,
    SUBSTR( CAST( POL.NO_STK_DT AS CHAR(10) ), 1, 7 ) AS NO_STK_MTH,
    POL.CMPL_DT,
    POL.SHIP_FACILITY_ID AS FACILITY_ID,
    SUBSTR( CAST( POL.CMPL_DT AS CHAR(10) ), 1, 7 ) AS CMPL_MTH,
    CASE
        WHEN NO_STK_MTH = CMPL_MTH
            THEN 'EQ'
        WHEN NO_STK_MTH < CMPL_MTH
            THEN 'LT'
    END AS CMPL_VS_NS_MTH,
    POL.SHIP_TO_CUST_ID,
    POL.MATL_ID,
    MATL.DESCR,
    MATL.PBU_NBR,
    MATL.PBU_NAME,
    POL.IF_HIT_NS_QTY
    
FROM NA_BI_VWS.PRFCT_ORD_LINE POL    

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = POL.MATL_ID
        AND MATL.EXT_MATL_GRP_ID = 'TIRE'
        AND MATL.PBU_NBR IN ( '01', '03' ) 

WHERE
    POL.CMPL_DT >= DATE '2013-01-01'
    
    ) SQ
    
    LEFT OUTER JOIN GDYR_BI_VWS.NAT_INV_MTH_END FAC
        ON FAC.FACILITY_ID = SQ.FACILITY_ID
        AND FAC.MATL_ID = SQ.MATL_ID
        AND SUBSTR( CAST( FAC.DAY_DT AS CHAR(10) ), 1, 7 ) = SQ.NO_STK_MTH

GROUP BY
    SQ.MATL_ID,
    SQ.PBU_NBR,
    SQ.FACILITY_ID,
    SQ.NO_STK_MTH,
    SQ.CMPL_MTH

ORDER BY
    TOT_NS_HIT_QTY DESC