SELECT
    Q.FRDD_COMPLETE_DESC,
    Q.FCDD_COMPLETE_DESC,
    Q.FRDD_CMPL_MTH,
    Q.FCDD_CMPL_MTH,
    Q.PBU_NBR,
    Q.MAX_FRDD_HIT_DESC,
    Q.MAX_FCDD_HIT_DESC,
    SUM(Q.FRDD_ORDER_QTY) AS FRDD_ORDER_QTY,
    SUM(Q.FRDD_ONTIME_QTY) AS FRDD_ONTIME_QTY,
    SUM(Q.ADJ_FRDD_ONTIME_QTY) AS ADJ_FRDD_ONTIME_QTY,
    SUM(Q.FRDD_HIT_QTY) AS FRDD_HIT_QTY,
    SUM(Q.FCDD_ORDER_QTY) AS FCDD_ORDER_QTY,
    SUM(Q.FCDD_ONTIME_QTY) AS FCDD_ONTIME_QTY,
    SUM(Q.ADJ_FCDD_ONTIME_QTY) AS ADJ_FCDD_ONTIME_QTY,
    SUM(Q.FCDD_HIT_QTY) AS FCDD_HIT_QTY

FROM (

SELECT
    POL.ORDER_ID,
    POL.ORDER_LINE_NBR,

    CASE
        WHEN POL.CMPL_IND = 1 AND POL.CMPL_DT < CURRENT_DATE AND POL.PRFCT_ORD_HIT_DESC <> 'FRDD HIT - ERROR'
            THEN 'FRDD COMPLETE - INCLUDED'
        WHEN POL.CMPL_IND = 1 AND POL.CMPL_DT < CURRENT_DATE AND POL.PRFCT_ORD_HIT_DESC = 'FRDD HIT - ERROR'
            THEN 'FRDD COMPLETE - EXCLUDED'
        ELSE 'FRDD INCOMPLETE'
    END AS FRDD_COMPLETE_DESC,
    CASE
        WHEN POL.FPDD_CMPL_IND = 1 AND POL.FPDD_CMPL_DT < CURRENT_DATE
            THEN (CASE
                WHEN POL.PRFCT_ORD_FPDD_HIT_DESC <> 'FCDD HIT - ERROR' AND POL.FRST_PROM_DELIV_DT IS NOT NULL
                    THEN 'FCDD COMPLETE - INCLUDED'
                WHEN POL.PRFCT_ORD_FPDD_HIT_DESC <> 'FCDD HIT - ERROR' OR POL.FRST_PROM_DELIV_DT IS NULL
                    THEN 'FCDD COMPLETE - EXCLUDED'
            END)
        ELSE 'FCDD INCOMPLETE'
    END AS FCDD_COMPLETE_DESC,

    POL.CMPL_DT AS FRDD_CMPL_DT,
    POL.CMPL_DT - (EXTRACT(DAY FROM POL.CMPL_DT) - 1) AS FRDD_CMPL_MTH,
    POL.FPDD_CMPL_DT AS FCDD_CMPL_DT,
    POL.FPDD_CMPL_DT - (EXTRACT(DAY FROM POL.FPDD_CMPL_DT) - 1) AS FCDD_CMPL_MTH,
    POL.CMPL_IND AS FRDD_CMPL_IND,
    POL.FPDD_CMPL_IND AS FCDD_CMPL_IND,

    POL.SHIP_TO_CUST_ID,
    POL.MATL_ID,
    POL.PBU_NBR,
    POL.SHIP_FACILITY_ID,
    NULLIF(POL.MAX_CARR_SCAC_ID, '') AS MAX_CARR_SCAC_ID,

    NULLIF(POL.CAN_REJ_REAS_ID, '') AS CAN_REJ_REAS_ID,
    NULLIF(POL.PO_TYPE_ID, '') AS PO_TYPE_ID,
    CASE WHEN POL.CREDIT_HOLD_FLG = 'Y' THEN 'Y' ELSE 'N' END AS CREDIT_HOLD_FLG,
    CASE WHEN POL.DELIV_BLK_IND = 'Y' THEN 'Y' ELSE 'N' END AS DELIV_BLK_IND,
    CASE WHEN POL.CANCEL_IND = 'Y' THEN 'Y' ELSE 'N' END AS CANCEL_IND,
    POL.A_IND,
    POL.R_IND,
    NULLIF(POL.SPCL_PROC_ID, '') AS SPCL_PROC_ID,

    POL.ORDER_DT,
    POL.FMAD_DT AS FRDD_FMAD,
    POL.FPGI_DT AS FRDD_FPGI,
    POL.REQ_DELIV_DT AS FRDD,
    ORD.MAX_FRDD,

    FCDD - (FRDD - FRDD_FMAD) AS FCDD_FMAD,
    FCDD - (FRDD - FRDD_FPGI) AS FCDD_FPGI,
    POL.FRST_PROM_DELIV_DT AS FCDD,
    ORD.MAX_FCDD,

    POL.CUST_APPT_DT,
    POL.MAX_DELIV_NOTE_CREA_DT,
    POL.MAX_EDI_DELIV_DT,
    POL.MAX_SAP_DELIV_DT,
    POL.ACTL_DELIV_DT,
    CASE
        WHEN POL.ACTL_DELIV_DT <= ORD.MAX_FRDD
            THEN 'MAX FRDD - ON TIME'
        ELSE 'MAX FRDD - LATE'
    END AS MAX_FRDD_HIT_DESC,
    CASE
        WHEN POL.ACTL_DELIV_DT <= ORD.MAX_FCDD
            THEN 'MAX FCDD - ON TIME'
        ELSE 'MAX FCDD - LATE'
    END AS MAX_FCDD_HIT_DESC,
    POL.NO_STK_DT AS FRDD_NO_STOCK_DT,
    POL.FPDD_NO_STK_DT AS FCDD_NO_STOCK_DT,
    
    CASE
        WHEN POL.ACTL_DELIV_DT <= ORD.MAX_FRDD
            THEN FRDD_ONTIME_QTY + FRDD_HIT_QTY
        ELSE FRDD_ONTIME_QTY
    END AS ADJ_FRDD_ONTIME_QTY,
    CASE
        WHEN POL.ACTL_DELIV_DT <= ORD.MAX_FCDD
            THEN FCDD_ONTIME_QTY + FCDD_HIT_QTY
        ELSE FCDD_ONTIME_QTY
    END AS ADJ_FCDD_ONTIME_QTY,

    POL.PRFCT_ORD_HIT_DESC AS FRDD_HIT_DESC,
    POL.PRFCT_ORD_HIT_SORT_KEY AS FRDD_HIT_SORT_KEY,

    ZEROIFNULL(POL.ORIG_ORD_QTY) AS ORIG_ORDER_QTY,
    ZEROIFNULL(POL.CANCEL_QTY) AS CANCEL_QTY,

    ZEROIFNULL(POL.CURR_ORD_QTY) AS FRDD_ORDER_QTY,
    ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY) AS FRDD_HIT_QTY,
    ZEROIFNULL(POL.CURR_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY) AS FRDD_ONTIME_QTY,
    ZEROIFNULL(POL.REL_LATE_QTY) AS FRDD_REL_LATE_QTY,
    ZEROIFNULL(POL.REL_ONTIME_QTY) AS FRDD_REL_ONTIME_QTY,
    ZEROIFNULL(POL.COMMIT_ONTIME_QTY) AS FRDD_COMMIT_ONTIME_QTY,
    ZEROIFNULL(POL.DELIV_LATE_QTY) AS FRDD_DELIV_LATE_QTY,
    ZEROIFNULL(POL.DELIV_ONTIME_QTY) AS FRDD_DELIV_ONTIME_QTY,

    ZEROIFNULL(POL.NE_HIT_RT_QTY) AS FRDD_RETURN_HIT_QTY,
    ZEROIFNULL(POL.NE_HIT_CL_QTY) AS FRDD_CLAIM_HIT_QTY,
    ZEROIFNULL(POL.OT_HIT_FP_QTY) AS FRDD_FREIGHT_POLICY_HIT_QTY,
    ZEROIFNULL(POL.OT_HIT_CARR_PICKUP_QTY) + ZEROIFNULL(POL.OT_HIT_WI_QTY) AS FRDD_PHYS_LOG_HIT_QTY,
    ZEROIFNULL(POL.OT_HIT_MB_QTY) AS FRDD_MAN_BLK_HIT_QTY,
    ZEROIFNULL(POL.OT_HIT_CH_QTY) AS FRDD_CREDIT_HOLD_HIT_QTY,
    ZEROIFNULL(POL.IF_HIT_NS_QTY) AS FRDD_NO_STOCK_HIT_QTY,
    ZEROIFNULL(POL.IF_HIT_CO_QTY) AS FRDD_CANCEL_HIT_QTY,
    ZEROIFNULL(POL.OT_HIT_CG_QTY) AS FRDD_CUST_GEN_HIT_QTY,
    ZEROIFNULL(POL.OT_HIT_CG_99_QTY) AS FRDD_MAN_REL_CUST_GEN_HIT_QTY,
    ZEROIFNULL(POL.OT_HIT_99_QTY) AS FRDD_MAN_REL_HIT_QTY,
    ZEROIFNULL(POL.OT_HIT_LO_QTY) AS FRDD_OTHER_HIT_QTY,

    POL.PRFCT_ORD_FPDD_HIT_DESC AS FCDD_HIT_DESC,
    POL.PRFCT_ORD_FPDD_HIT_SORT_KEY AS FCDD_HIT_SORT_KEY,

    ZEROIFNULL(POL.FPDD_ORD_QTY) AS FCDD_ORDER_QTY,
    ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY) AS FCDD_HIT_QTY,
    ZEROIFNULL(POL.FPDD_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY) AS FCDD_ONTIME_QTY,
    ZEROIFNULL(POL.DELIV_FPDD_LATE_QTY) AS FCDD_DELIV_LATE_QTY,
    ZEROIFNULL(POL.DELIV_FPDD_ONTIME_QTY) AS FCDD_DELIV_ONTIME_QTY,
    ZEROIFNULL(POL.FPDD_COMMIT_ONTIME_QTY) AS FCDD_COMMIT_ONTIME_QTY,
    ZEROIFNULL(POL.REL_FPDD_LATE_QTY) AS FCDD_REL_LATE_QTY,
    ZEROIFNULL(POL.REL_FPDD_ONTIME_QTY) AS FCDD_REL_ONTIME_QTY,

    ZEROIFNULL(POL.NE_FPDD_HIT_RT_QTY) AS FCDD_RETURN_HIT_QTY,
    ZEROIFNULL(POL.NE_FPDD_HIT_CL_QTY) AS FCDD_CLAIM_HIT_QTY,
    ZEROIFNULL(POL.OT_FPDD_HIT_FP_QTY) AS FCDD_FREIGHT_POLICY_HIT_QTY,
    ZEROIFNULL(POL.OT_FPDD_HIT_CARR_QTY) + ZEROIFNULL(POL.OT_FPDD_HIT_WI_QTY) AS FCDD_PHYS_LOG_HIT_QTY,
    ZEROIFNULL(POL.OT_FPDD_HIT_MB_QTY) AS FCDD_MAN_BLK_HIT_QTY,
    ZEROIFNULL(POL.OT_FPDD_HIT_CH_QTY) AS FCDD_CREDIT_HOLD_HIT_QTY,
    ZEROIFNULL(POL.IF_FPDD_HIT_NS_QTY) AS FCDD_NO_STOCK_HIT_QTY,
    ZEROIFNULL(POL.IF_FPDD_HIT_CO_QTY) AS FCDD_CANCEL_HIT_QTY,
    ZEROIFNULL(POL.OT_FPDD_HIT_CG_QTY) AS FCDD_CUST_GEN_HIT_QTY,
    ZEROIFNULL(POL.OT_FPDD_HIT_CG_99_QTY) AS FCDD_MAN_REL_CUST_GEN_HIT_QTY,
    ZEROIFNULL(POL.OT_FPDD_HIT_99_QTY) AS FCDD_MAN_REL_HIT_QTY,
    ZEROIFNULL(POL.OT_FPDD_HIT_LO_QTY) AS FCDD_OTHER_HIT_QTY

FROM NA_BI_VWS.PRFCT_ORD_LINE POL

    INNER JOIN ( 
        SELECT
            OD.ORDER_ID,
            OD.ORDER_LINE_NBR,
            MAX(OD.FRST_RDD) AS MAX_FRDD,
            MAX(OD.FRST_PROM_DELIV_DT) AS MAX_FCDD
        FROM NA_BI_VWS.ORDER_DETAIL OD
        WHERE
            OD.ORDER_DT >= CAST('2013-01-01' AS DATE)
            AND OD.EXP_DT >= CAST('2014-01-01' AS DATE)
            AND OD.ORDER_CAT_ID = 'C'
            AND OD.ORDER_TYPE_ID NOT IN ('ZLS', 'ZLZ')
            AND OD.PO_TYPE_ID <> 'RO'
        GROUP BY
            OD.ORDER_ID,
            OD.ORDER_LINE_NBR
            ) ORD
        ON ORD.ORDER_ID = POL.ORDER_ID
        AND ORD.ORDER_LINE_NBR = POL.ORDER_LINE_NBR

WHERE
/*    (
    POL.CMPL_DT / 100 BETWEEN ((CURRENT_DATE-1) / 100) - 3 AND (CURRENT_DATE-1) /  100
    AND POL.CMPL_IND = 1
    AND POL.PRFCT_ORD_HIT_DESC <> 'FRDD HIT - ERROR'
    )
    OR */(
    POL.FPDD_CMPL_DT BETWEEN DATE '2014-02-01' AND (CURRENT_DATE-1)
    AND POL.FPDD_CMPL_IND = 1
    AND POL.PRFCT_ORD_FPDD_HIT_DESC <> 'FCDD HIT - ERROR' 
    AND POL.FRST_PROM_DELIV_DT IS NOT NULL
    )
    
    
    ) Q

GROUP BY
    Q.FRDD_COMPLETE_DESC,
    Q.FCDD_COMPLETE_DESC,
    Q.FRDD_CMPL_MTH,
    Q.FCDD_CMPL_MTH,
    Q.PBU_NBR,
    Q.MAX_FRDD_HIT_DESC,
    Q.MAX_FCDD_HIT_DESC
    