
-- NAMED QUERY ON_TIME_DELIVERY HELPS REDUCE THE NUMBER OF PLACES LOGIC NEEDS TO BE MAINTAINED FOR OUTPUT
WITH ON_TIME_DELIVERY (

    METRIC_TYPE
    , COMPLETE_MTH
    , QUARTER
    , MONTH_NAME
    , PBU_NBR
    , PBU
    , CATEGORY_CD
    , CATEGORY_NAME
    , TIER
    , CATEGORY_TIER
    , EXT_MATL_GRP_ID
    , MATL_PRTY_CTGY
    , MATL_PRTY
    , MATL_PRTY_DESCR
    , OWN_CUST_RNK
    , OWN_CUST_ID
    , OWN_CUST_NAME
    , OE_REPL_IND
    , EXPORT_IND
    , ORDER_QTY
    , HIT_QTY
    , ONTIME_QTY
    , RETURN_HIT_QTY
    , CLAIM_HIT_QTY
    , FREIGHT_POLICY_HIT_QTY
    , PHYS_LOG_HIT_QTY
    , MAN_BLK_HIT_QTY
    , CREDIT_HOLD_HIT_QTY
    , NO_STOCK_HIT_QTY
    , CANCEL_HIT_QTY
    , CUST_GEN_HIT_QTY
    , MAN_REL_CUST_GEN_HIT_QTY
    , MAN_REL_HIT_QTY
    , OTHER_HIT_QTY
    , SUPPLY_HIT_QTY
    , POLICY_HIT_QTY
    , TOT_OTHER_HIT_QTY
    , TARGET_NUMERATOR
    , TARGET_DENOMINATOR
    , AOP_NUMERATOR

    ) AS (

    SELECT
        CAST('FRDD' AS CHAR(4)) AS METRIC_TYPE
        , CAL.MONTH_DT AS COMPLETE_MTH
        , CAL.QUARTER
        , CAST(CAL.MONTH_DT AS FORMAT 'Mmm') (CHAR(3)) AS MONTH_NAME
        , MATL.PBU_NBR
        , MATL.PBU_NBR || ' - ' || MATL.PBU_NAME AS PBU
        , CASE
            WHEN MATL.PBU_NBR = '01'
                THEN MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME
            ELSE MATL.MKT_CTGY_MKT_GRP_NBR || ' - ' || MATL.MKT_CTGY_MKT_GRP_NAME
            END AS CATEGORY_CD
        , CASE
            WHEN MATL.PBU_NBR = '01'
                THEN MATL.MKT_CTGY_MKT_AREA_NAME
            ELSE MATL.MKT_CTGY_MKT_GRP_NAME
            END AS CATEGORY_NAME
        , CASE
            WHEN MATL.PBU_NBR = '01'
                THEN MATL.MKT_CTGY_PROD_GRP_NAME
            ELSE MATL.TIERS
            END AS TIER
        , CATEGORY_NAME || ' (' || TIER || ')' AS CATEGORY_TIER
        , MATL.EXT_MATL_GRP_ID
        , MATL.MATL_PRTY_CTGY
        , MATL.MATL_PRTY
        , MATL.MATL_PRTY_DESCR
        , CASE
            WHEN EXPORT_IND = 'D'
                THEN (CASE
                    -- CONSUMER
                    WHEN CUST.OWN_CUST_ID = '00A0003149' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 1
                    WHEN CUST.OWN_CUST_ID = '00A0006582' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 2
                    WHEN CUST.OWN_CUST_ID = '00A0003088' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 3
                    WHEN CUST.OWN_CUST_ID = '00A0006929' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 4
                    WHEN CUST.OWN_CUST_ID = '00A0003047' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 5
                    WHEN CUST.OWN_CUST_ID = '00A0000632' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 6
                    WHEN CUST.OWN_CUST_ID = '00A0003117' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 7
                    WHEN CUST.OWN_CUST_ID = '00A0005262' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 8
                    WHEN CUST.OWN_CUST_ID = '00A0009337' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 9
                    WHEN CUST.OWN_CUST_ID = '00A0009994' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 10
                    WHEN CUST.OWN_CUST_ID = '00A0006932' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 11
                    WHEN CUST.OWN_CUST_ID = '00A0005041' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 12
                    -- MAXX REQUESTED CHANGES FOR CONSUMER
                    WHEN CUST.OWN_CUST_ID = '00A0003158' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 13
                    WHEN CUST.OWN_CUST_ID = '00A0003085' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 14
                    WHEN CUST.OWN_CUST_ID = '00A0003084' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 15
                    -- COMMERCIAL
                    WHEN CUST.OWN_CUST_ID = '00A0006677' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 1
                    WHEN CUST.OWN_CUST_ID = '00A0006582' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 2
                    WHEN CUST.OWN_CUST_ID = '00A0009337' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 3
                    WHEN CUST.OWN_CUST_ID = '00A0006090' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 4
                    WHEN CUST.OWN_CUST_ID = '00A0003047' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 5
                    WHEN CUST.OWN_CUST_ID = '00A0005262' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 6
                    WHEN CUST.OWN_CUST_ID = '00A0005037' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 7
                    WHEN CUST.OWN_CUST_ID = '00A0006024' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 8
                    WHEN CUST.OWN_CUST_ID = '00A0005041' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 9
                    WHEN CUST.OWN_CUST_ID = '00A0008463' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 10
                    WHEN CUST.OWN_CUST_ID = '00A0006691' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 11
                    WHEN CUST.OWN_CUST_ID = '00A0003117' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 12
                    WHEN CUST.OWN_CUST_ID = '00A0008485' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 13
                    WHEN CUST.OWN_CUST_ID = '00A0006054' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 14
                    WHEN CUST.OWN_CUST_ID = '00A0006199' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 15
                    ELSE 17
                END)
            WHEN EXPORT_IND = 'X' AND OE_REPL_IND = 'Repl' THEN 16
            ELSE 17
            END AS OWN_CUST_RNK
        , CASE
            WHEN OWN_CUST_RNK < 16 THEN CUST.OWN_CUST_ID
            WHEN OWN_CUST_RNK = 16 THEN 'Export'
            ELSE 'Other'
            END AS OWN_CUST_ID
        , CASE
            WHEN OWN_CUST_RNK < 16 THEN CUST.OWN_CUST_NAME
            WHEN OWN_CUST_RNK = 16 THEN 'Export'
            ELSE 'Other'
            END AS OWN_CUST_NAME
        --, CUST.OWN_CUST_ID
        --, CUST.OWN_CUST_NAME
        , CASE
            WHEN CUST.SALES_ORG_GRP_DESC = 'NA' THEN 'REPL'
            ELSE CUST.SALES_ORG_GRP_DESC
            END AS OE_REPL_IND
        , CAST(CASE
            WHEN CUST.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND CUST.DISTR_CHAN_CD = '30'
                THEN 'X'
            WHEN CUST.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND CUST.DISTR_CHAN_CD <> '30'
                THEN 'N'
            ELSE 'D'
            END AS CHAR(1)) AS EXPORT_IND

        , SUM(ZEROIFNULL(POL.CURR_ORD_QTY)) AS ORDER_QTY
        , SUM(ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY)) AS HIT_QTY
        , SUM(ZEROIFNULL(POL.CURR_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY)) AS ONTIME_QTY
        , SUM(ZEROIFNULL(POL.NE_HIT_RT_QTY)) AS RETURN_HIT_QTY
        , SUM(ZEROIFNULL(POL.NE_HIT_CL_QTY)) AS CLAIM_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_FP_QTY)) AS FREIGHT_POLICY_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_CARR_PICKUP_QTY) + ZEROIFNULL(POL.OT_HIT_WI_QTY)) AS PHYS_LOG_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_MB_QTY)) AS MAN_BLK_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_CH_QTY)) AS CREDIT_HOLD_HIT_QTY
        , SUM(ZEROIFNULL(POL.IF_HIT_NS_QTY)) AS NO_STOCK_HIT_QTY
        , SUM(ZEROIFNULL(POL.IF_HIT_CO_QTY)) AS CANCEL_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_CG_QTY)) AS CUST_GEN_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_CG_99_QTY)) AS MAN_REL_CUST_GEN_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_99_QTY)) AS MAN_REL_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_LO_QTY)) AS OTHER_HIT_QTY

        , NO_STOCK_HIT_QTY + CANCEL_HIT_QTY AS SUPPLY_HIT_QTY
        , CREDIT_HOLD_HIT_QTY + FREIGHT_POLICY_HIT_QTY + MAN_BLK_HIT_QTY AS POLICY_HIT_QTY
        , RETURN_HIT_QTY + CLAIM_HIT_QTY + CUST_GEN_HIT_QTY + MAN_REL_CUST_GEN_HIT_QTY + MAN_REL_HIT_QTY + OTHER_HIT_QTY AS TOT_OTHER_HIT_QTY

        , CAST(CASE
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q1' THEN 7.3
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q2' THEN 7.4
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q3' THEN 7.6
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q4' THEN 7.7
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q1' THEN 7.1
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q2' THEN 7.5
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q3' THEN 7.3
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q4' THEN 7.3
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q1' THEN 8.6
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q2' THEN 8.8
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q3' THEN 9.0
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q4' THEN 9.0
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q1' THEN 8.6
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q2' THEN 8.8
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q3' THEN 9.0
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q4' THEN 9.0
                ELSE 0
            END AS DECIMAL(15,3)) AS TARGET_NUMERATOR
        , CAST(10 AS DECIMAL(15,3)) AS TARGET_DENOMINATOR
        , CAST(CASE
            WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01' THEN 7.7
            WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03' THEN 7.3
            WHEN METRIC_TYPE = 'FCDD' THEN 8.9
            END AS DECIMAL(15,3)) AS AOP_NUMERATOR

    FROM NA_BI_VWS.PRFCT_ORD_LINE POL

        INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
            ON CAL.DAY_DATE = POL.CMPL_DT
                --AND CAL.MONTH_DT = DATE '2014-11-01'

        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID
                AND CUST.CUST_GRP_ID <> '3R'

        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
            ON MATL.MATL_ID = POL.MATL_ID
                AND MATL.PBU_NBR IN ('01', '03')
                AND MATL.EXT_MATL_GRP_ID = 'TIRE'
                --AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')

    WHERE
        POL.CMPL_IND = 1
        AND POL.CMPL_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE - 1) || '-01-01' AS DATE) AND CURRENT_DATE - 1
                --BETWEEN DATE '2014-10-01' AND DATE '2014-10-31'
        AND POL.PRFCT_ORD_HIT_SORT_KEY <> 99

    GROUP BY
        METRIC_TYPE
        , COMPLETE_MTH
        , CAL.QUARTER
        , MONTH_NAME
        , MATL.PBU_NBR
        , PBU
        , CATEGORY_CD
        , CATEGORY_NAME
        , TIER
        , CATEGORY_TIER
        , MATL.MATL_PRTY_CTGY
        , MATL.MATL_PRTY
        , MATL.MATL_PRTY_DESCR
        , MATL.EXT_MATL_GRP_ID
        , OE_REPL_IND
        , OWN_CUST_RNK
        , CUST.OWN_CUST_ID
        , CUST.OWN_CUST_NAME
        , EXPORT_IND
        , TARGET_NUMERATOR
        , TARGET_DENOMINATOR
        , AOP_NUMERATOR

    UNION ALL

    SELECT
        CAST('FCDD' AS CHAR(4)) AS METRIC_TYPE
        , CAL.MONTH_DT AS COMPLETE_MTH
        , CAL.QUARTER
        , CAST(CAL.MONTH_DT AS FORMAT 'Mmm') (CHAR(3)) AS MONTH_NAME
        , MATL.PBU_NBR
        , MATL.PBU_NBR || ' - ' || MATL.PBU_NAME AS PBU
        , CASE
            WHEN MATL.PBU_NBR = '01'
                THEN MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME
            ELSE MATL.MKT_CTGY_MKT_GRP_NBR || ' - ' || MATL.MKT_CTGY_MKT_GRP_NAME
            END AS CATEGORY_CD
        , CASE
            WHEN MATL.PBU_NBR = '01'
                THEN MATL.MKT_CTGY_MKT_AREA_NAME
            ELSE MATL.MKT_CTGY_MKT_GRP_NAME
            END AS CATEGORY_NAME
        , CASE
            WHEN MATL.PBU_NBR = '01'
                THEN MATL.MKT_CTGY_PROD_GRP_NAME
            ELSE MATL.TIERS
            END AS TIER
        , CATEGORY_NAME || ' (' || TIER || ')' AS CATEGORY_TIER
        , MATL.EXT_MATL_GRP_ID
        , MATL.MATL_PRTY_CTGY
        , MATL.MATL_PRTY
        , MATL.MATL_PRTY_DESCR
        , CASE
            WHEN EXPORT_IND = 'D'
                THEN (CASE
                    -- CONSUMER
                    WHEN CUST.OWN_CUST_ID = '00A0003149' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 1
                    WHEN CUST.OWN_CUST_ID = '00A0006582' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 2
                    WHEN CUST.OWN_CUST_ID = '00A0003088' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 3
                    WHEN CUST.OWN_CUST_ID = '00A0006929' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 4
                    WHEN CUST.OWN_CUST_ID = '00A0003047' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 5
                    WHEN CUST.OWN_CUST_ID = '00A0000632' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 6
                    WHEN CUST.OWN_CUST_ID = '00A0003117' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 7
                    WHEN CUST.OWN_CUST_ID = '00A0005262' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 8
                    WHEN CUST.OWN_CUST_ID = '00A0009337' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 9
                    WHEN CUST.OWN_CUST_ID = '00A0009994' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 10
                    WHEN CUST.OWN_CUST_ID = '00A0006932' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 11
                    WHEN CUST.OWN_CUST_ID = '00A0005041' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 12
                    -- MAXX REQUESTED CHANGES FOR CONSUMER
                    WHEN CUST.OWN_CUST_ID = '00A0003158' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 13
                    WHEN CUST.OWN_CUST_ID = '00A0003085' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 14
                    WHEN CUST.OWN_CUST_ID = '00A0003084' AND MATL.PBU_NBR = '01' AND OE_REPL_IND = 'Repl' THEN 15
                    -- COMMERCIAL
                    WHEN CUST.OWN_CUST_ID = '00A0006677' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 1
                    WHEN CUST.OWN_CUST_ID = '00A0006582' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 2
                    WHEN CUST.OWN_CUST_ID = '00A0009337' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 3
                    WHEN CUST.OWN_CUST_ID = '00A0006090' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 4
                    WHEN CUST.OWN_CUST_ID = '00A0003047' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 5
                    WHEN CUST.OWN_CUST_ID = '00A0005262' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 6
                    WHEN CUST.OWN_CUST_ID = '00A0005037' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 7
                    WHEN CUST.OWN_CUST_ID = '00A0006024' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 8
                    WHEN CUST.OWN_CUST_ID = '00A0005041' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 9
                    WHEN CUST.OWN_CUST_ID = '00A0008463' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 10
                    WHEN CUST.OWN_CUST_ID = '00A0006691' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 11
                    WHEN CUST.OWN_CUST_ID = '00A0003117' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 12
                    WHEN CUST.OWN_CUST_ID = '00A0008485' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 13
                    WHEN CUST.OWN_CUST_ID = '00A0006054' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 14
                    WHEN CUST.OWN_CUST_ID = '00A0006199' AND MATL.PBU_NBR = '03' AND OE_REPL_IND = 'Repl' THEN 15
                    ELSE 17
                END)
            WHEN EXPORT_IND = 'X' AND OE_REPL_IND = 'Repl' THEN 16
            ELSE 17
            END AS OWN_CUST_RNK
        , CASE
            WHEN OWN_CUST_RNK < 16 THEN CUST.OWN_CUST_ID
            WHEN OWN_CUST_RNK = 16 THEN 'Export'
            ELSE 'Other'
            END AS OWN_CUST_ID
        , CASE
            WHEN OWN_CUST_RNK < 16 THEN CUST.OWN_CUST_NAME
            WHEN OWN_CUST_RNK = 16 THEN 'Export'
            ELSE 'Other'
            END AS OWN_CUST_NAME
        --, CUST.OWN_CUST_ID
        --, CUST.OWN_CUST_NAME
        , CASE
            WHEN CUST.SALES_ORG_GRP_DESC = 'NA' THEN 'REPL'
            ELSE CUST.SALES_ORG_GRP_DESC
            END AS OE_REPL_IND
        , CAST(CASE
            WHEN CUST.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND CUST.DISTR_CHAN_CD = '30'
                THEN 'X'
            WHEN CUST.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND CUST.DISTR_CHAN_CD <> '30'
                THEN 'N'
            ELSE 'D'
            END AS CHAR(1)) AS EXPORT_IND

        , SUM(ZEROIFNULL(POL.FPDD_ORD_QTY)) AS ORDER_QTY
        , SUM(ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY)) AS HIT_QTY
        , SUM(ZEROIFNULL(POL.FPDD_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY)) AS ONTIME_QTY
        , SUM(ZEROIFNULL(POL.NE_FPDD_HIT_RT_QTY)) AS RETURN_HIT_QTY
        , SUM(ZEROIFNULL(POL.NE_FPDD_HIT_CL_QTY)) AS CLAIM_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_FP_QTY)) AS FREIGHT_POLICY_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CARR_QTY) + ZEROIFNULL(POL.OT_FPDD_HIT_WI_QTY)) AS PHYS_LOG_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_MB_QTY)) AS MAN_BLK_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CH_QTY)) AS CREDIT_HOLD_HIT_QTY
        , SUM(ZEROIFNULL(POL.IF_FPDD_HIT_NS_QTY)) AS NO_STOCK_HIT_QTY
        , SUM(ZEROIFNULL(POL.IF_FPDD_HIT_CO_QTY)) AS CANCEL_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CG_QTY)) AS CUST_GEN_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CG_99_QTY)) AS MAN_REL_CUST_GEN_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_99_QTY)) AS MAN_REL_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_LO_QTY)) AS OTHER_HIT_QTY
        , NO_STOCK_HIT_QTY + CANCEL_HIT_QTY AS SUPPLY_HIT_QTY
        , CREDIT_HOLD_HIT_QTY + FREIGHT_POLICY_HIT_QTY + MAN_BLK_HIT_QTY AS POLICY_HIT_QTY
        , RETURN_HIT_QTY + CLAIM_HIT_QTY + CUST_GEN_HIT_QTY + MAN_REL_CUST_GEN_HIT_QTY + MAN_REL_HIT_QTY + OTHER_HIT_QTY AS TOT_OTHER_HIT_QTY
        , CAST(CASE
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q1' THEN 7.3
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q2' THEN 7.4
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q3' THEN 7.6
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q4' THEN 7.7
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q1' THEN 7.1
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q2' THEN 7.5
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q3' THEN 7.3
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q4' THEN 7.3
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q1' THEN 8.6
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q2' THEN 8.8
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q3' THEN 9.0
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q4' THEN 9.0
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q1' THEN 8.6
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q2' THEN 8.8
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q3' THEN 9.0
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q4' THEN 9.0
                ELSE 0
            END AS DECIMAL(15,3)) AS TARGET_NUMERATOR
        , CAST(10 AS DECIMAL(15,3)) AS TARGET_DENOMINATOR
        , CAST(CASE
            WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01' THEN 7.7
            WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03' THEN 7.3
            WHEN METRIC_TYPE = 'FCDD' THEN 8.9
            END AS DECIMAL(15,3)) AS AOP_NUMERATOR

    FROM NA_BI_VWS.PRFCT_ORD_LINE POL

        INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
            ON CAL.DAY_DATE = POL.FPDD_CMPL_DT
                --AND CAL.MONTH_DT = DATE '2014-11-01'

        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID
                AND CUST.CUST_GRP_ID <> '3R'

        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
            ON MATL.MATL_ID = POL.MATL_ID
                AND MATL.PBU_NBR IN ('01', '03')
                AND MATL.EXT_MATL_GRP_ID = 'TIRE'
                --AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')

    WHERE
        POL.FPDD_CMPL_IND = 1
        AND POL.FRST_PROM_DELIV_DT IS NOT NULL
        AND POL.FPDD_CMPL_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE - 1) || '-01-01' AS DATE) AND CURRENT_DATE - 1
                --BETWEEN DATE '2014-10-01' AND DATE '2014-10-31'
        AND POL.PRFCT_ORD_FPDD_HIT_SORT_KEY <> 99

    GROUP BY
        METRIC_TYPE
        , COMPLETE_MTH
        , CAL.QUARTER
        , MONTH_NAME
        , MATL.PBU_NBR
        , PBU
        , CATEGORY_CD
        , CATEGORY_NAME
        , TIER
        , CATEGORY_TIER
        , MATL.MATL_PRTY_CTGY
        , MATL.MATL_PRTY
        , MATL.MATL_PRTY_DESCR
        , MATL.EXT_MATL_GRP_ID
        , OWN_CUST_RNK
        , CUST.OWN_CUST_ID
        , CUST.OWN_CUST_NAME
        , OE_REPL_IND
        , EXPORT_IND
        , TARGET_NUMERATOR
        , TARGET_DENOMINATOR
        , AOP_NUMERATOR
    )
-- END OF NAMED QUERY -- ON_TIME_DELIVERY

-- BEGIN SQL SELECT STATEMENT
SELECT
    OTD.METRIC_TYPE
    , OTD.COMPLETE_MTH
    , OTD.QUARTER
    , OTD.MONTH_NAME
    , OTD.PBU_NBR
    , OTD.PBU
    , OTD.CATEGORY_CD AS CATEGORY
    , OTD.CATEGORY_NAME
    , OTD.TIER
    , OTD.CATEGORY_TIER
    , OTD.EXT_MATL_GRP_ID
    , OTD.OWN_CUST_ID
    , OTD.OWN_CUST_NAME
    , OTD.OE_REPL_IND AS TIRE_CUST_TYP_CD
    , OTD.TARGET_NUMERATOR
    , OTD.TARGET_DENOMINATOR
    , OTD.AOP_NUMERATOR
    , OTD.ORDER_QTY
    , OTD.HIT_QTY
    , OTD.ONTIME_QTY
    , OTD.SUPPLY_HIT_QTY
    , OTD.POLICY_HIT_QTY
    , OTD.TOT_OTHER_HIT_QTY
    , OTD.RETURN_HIT_QTY
    , OTD.CLAIM_HIT_QTY
    , OTD.FREIGHT_POLICY_HIT_QTY
    , OTD.PHYS_LOG_HIT_QTY
    , OTD.MAN_BLK_HIT_QTY
    , OTD.CREDIT_HOLD_HIT_QTY
    , OTD.NO_STOCK_HIT_QTY
    , OTD.CANCEL_HIT_QTY
    , OTD.CUST_GEN_HIT_QTY
    , OTD.MAN_REL_CUST_GEN_HIT_QTY
    , OTD.MAN_REL_HIT_QTY
    , OTD.OTHER_HIT_QTY
    , OTD.OWN_CUST_RNK
    , MTH.MTH_PBU_ORDER_QTY
    , NULL AS CO_DELIV_QTY
    , NULL AS MTH_DELIV_QTY
    , OTD.MATL_PRTY
    , OTD.MATL_PRTY_DESCR
    , CO.YTD_CO_ORDER_QTY
    , CO.YTD_CO_ON_TIME_QTY
    , MTH.YTD_PBU_ORDER_QTY

FROM ON_TIME_DELIVERY OTD

    INNER JOIN (
        SELECT
            Q.METRIC_TYPE
            , Q.COMPLETE_MTH
            , Q.PBU_NBR
            , Q.EXT_MATL_GRP_ID
            , Q.OE_REPL_IND
            , Q.MTH_PBU_ORDER_QTY
            , SUM(Q.MTH_PBU_ORDER_QTY) OVER (
                PARTITION BY Q.METRIC_TYPE
                , Q.PBU_NBR
                , Q.EXT_MATL_GRP_ID
                , Q.OE_REPL_IND ORDER BY Q.COMPLETE_MTH ROWS UNBOUNDED PRECEDING
                ) AS YTD_PBU_ORDER_QTY
        FROM (
            SELECT
                METRIC_TYPE
                , COMPLETE_MTH
                , PBU_NBR
                , EXT_MATL_GRP_ID
                , OE_REPL_IND
                , SUM(ORDER_QTY) AS MTH_PBU_ORDER_QTY
            FROM ON_TIME_DELIVERY
            GROUP BY
                METRIC_TYPE
                , COMPLETE_MTH
                , PBU_NBR
                , EXT_MATL_GRP_ID
                , OE_REPL_IND
            ) Q
        ) MTH
        ON MTH.METRIC_TYPE = OTD.METRIC_TYPE
            AND MTH.COMPLETE_MTH = OTD.COMPLETE_MTH
            AND MTH.PBU_NBR = OTD.PBU_NBR
            AND MTH.EXT_MATL_GRP_ID = OTD.EXT_MATL_GRP_ID
            AND MTH.OE_REPL_IND = OTD.OE_REPL_IND

    INNER JOIN (
        SELECT
            Q.METRIC_TYPE
            , Q.COMPLETE_MTH
            , Q.PBU_NBR
            , Q.EXT_MATL_GRP_ID
            , Q.OE_REPL_IND
            , Q.OWN_CUST_RNK
            , Q.OWN_CUST_ID
            , Q.CO_ORDER_QTY
            , Q.CO_ONTIME_QTY
            , SUM(Q.CO_ORDER_QTY) OVER (
                PARTITION BY Q.METRIC_TYPE
                , Q.OWN_CUST_RNK
                , Q.OWN_CUST_ID
                , Q.PBU_NBR
                , Q.EXT_MATL_GRP_ID
                , Q.OE_REPL_IND ORDER BY Q.COMPLETE_MTH ROWS UNBOUNDED PRECEDING
                ) AS YTD_CO_ORDER_QTY
            , SUM(Q.CO_ONTIME_QTY) OVER (
                PARTITION BY Q.METRIC_TYPE
                , Q.OWN_CUST_RNK
                , Q.OWN_CUST_ID
                , Q.PBU_NBR
                , Q.EXT_MATL_GRP_ID
                , Q.OE_REPL_IND ORDER BY Q.COMPLETE_MTH ROWS UNBOUNDED PRECEDING
                ) AS YTD_CO_ON_TIME_QTY
        FROM (
            SELECT
                METRIC_TYPE
                , COMPLETE_MTH
                , PBU_NBR
                , EXT_MATL_GRP_ID
                , OE_REPL_IND
                , OWN_CUST_RNK
                , OWN_CUST_ID
                , SUM(ORDER_QTY) AS CO_ORDER_QTY
                , SUM(ONTIME_QTY) AS CO_ONTIME_QTY
            FROM ON_TIME_DELIVERY
            GROUP BY
                METRIC_TYPE
                , COMPLETE_MTH
                , PBU_NBR
                , EXT_MATL_GRP_ID
                , OWN_CUST_RNK
                , OWN_CUST_ID
                , OE_REPL_IND
            ) Q
        ) CO
        ON CO.METRIC_TYPE = OTD.METRIC_TYPE
            AND CO.COMPLETE_MTH = OTD.COMPLETE_MTH
            AND CO.PBU_NBR = OTD.PBU_NBR
            AND CO.EXT_MATL_GRP_ID = OTD.EXT_MATL_GRP_ID
            AND CO.OE_REPL_IND = OTD.OE_REPL_IND
            AND CO.OWN_CUST_RNK = OTD.OWN_CUST_RNK
            AND CO.OWN_CUST_ID = OTD.OWN_CUST_ID

/*WHERE
    OTD.COMPLETE_MTH = DATE '2014-11-01'
    AND OTD.METRIC_TYPE = 'FRDD'
    AND OTD.PBU_NBR = '01'*/

ORDER BY
    OTD.METRIC_TYPE
    , OTD.COMPLETE_MTH
    , OTD.PBU_NBR
    , OTD.EXT_MATL_GRP_ID
    , OTD.OE_REPL_IND
    , OTD.OWN_CUST_RNK

