SELECT
/*    OL.SHIP_TO_CUST_ID,
    OL.SHIP_TO_CUST_NAME,
    OL.OWN_CUST_ID,
    OL.OWN_CUST_NAME,
    OL.MATL_ID,
    OL.MATL_DESCR,*/
    OL.PBU,
/*    OL.FACILITY,
    OL.CUST_GRP2,
    OL.ORIGINAL_ORDER_QTY,
    OL.CURRENT_ORDER_QTY,
    OL.QTY_UNIT_MEAS_ID,
    OL.FRDD_RELEASE_LATE_QTY,
    OL.FRDD_RELEASE_ONTIME_QTY,
    
    OL.ORDER_DT,
    OL.ORDD,
    OL.FRDD_FMAD,
    OL.FRDD_FPGI,
    OL.FRDD,
    OL.FCDD_FMAD,
    OL.FCDD_FPGI,
    OL.FCDD,*/
    
/*    OL.MAX_DELIV_NOTE_CREA_DT,
    OL.CUST_APPT_DT,
    OL.MAX_EDI_DELIV_DT,
    OL.MAX_SAP_DELIV_DT,
    
    OL.CMPL_IND,*/
    OL.CMPL_DT,
/*    OL.NO_STK_DT,
    OL.CAN_EFF_DT,*/
    
/*  SUM( OL.CANCEL_QTY ) AS CANCEL_QTY,
     SUM( OL.FRDD_DELIVER_LATE_QTY ) AS FRDD_DELIVER_LATE_QTY,
    SUM( OL.FRDD_DELIVER_ONTIME_QTY ) AS FRDD_DELIVER_ONTIME_QTY,
    	
	SUM( OL.FRDD_RETURN_HIT_QTY ) AS FRDD_RETURN_HIT_QTY,
	SUM( OL.FRDD_CLAIM_HIT_QTY ) AS FRDD_CLAIM_HIT_QTY,
	SUM( OL.FRDD_FREIGHT_PLCY_HIT_QTY ) AS FRDD_FREIGHT_PLCY_HIT_QTY,
	SUM( OL.FRDD_PHYS_LOG_HIT_QTY ) AS FRDD_PHYS_LOG_HIT_QTY,
	SUM( OL.FRDD_MAN_BLK_HIT_QTY ) AS FRDD_MAN_BLK_HIT_QTY,
	SUM( OL.FRDD_CREDIT_HIT_QTY ) AS FRDD_CREDIT_HIT_QTY,
	SUM( OL.FRDD_NO_STOCK_HIT_QTY ) AS FRDD_NO_STOCK_HIT_QTY,
	SUM( OL.FRDD_CANCEL_HIT_QTY ) AS FRDD_CANCEL_HIT_QTY,
	SUM( OL.FRDD_CUST_GEN_HIT_QTY ) AS FRDD_CUST_GEN_HIT_QTY,
	SUM( OL.FRDD_MAN_REL_CUST_GEN_HIT_QTY ) AS FRDD_MAN_REL_CUST_GEN_HIT_QTY,
	SUM( OL.FRDD_MAN_REL_HIT_QTY ) AS FRDD_MAN_REL_HIT_QTY,
	SUM( OL.FRDD_OTHER_HIT_QTY ) AS FRDD_OTHER_HIT_QTY,*/
	
	SUM( OL.CURRENT_ORDER_QTY ) AS CURR_ORDER_QTY,
	SUM( OL.PRFCT_ORD_QTY ) AS FRDD_ONTIME_QTY,
	SUM( OL.PRFCT_ORD_HIT_QTY ) AS FRDD_LATE_QTY,
	CAST( FRDD_ONTIME_QTY AS DOUBLE PRECISION ) / CAST( NULLIFZERO( CURR_ORDER_QTY ) AS DOUBLE PRECISION )AS ON_TIME_PCT

    -- OL.PRFCT_ORD_HIT_DESC
    
FROM (

SELECT
    POL.ORDER_ID,
    POL.ORDER_LINE_NBR,
    
    POL.SHIP_TO_CUST_ID,
    CUST.CUST_NAME AS SHIP_TO_CUST_NAME,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,
    
    CUST.SALES_ORG_CD || ' - ' || CUST.SALES_ORG_NAME AS SALES_ORG,
    CUST.DISTR_CHAN_CD || ' - ' || CUST.DISTR_CHAN_NAME AS DISTR_CHAN,
    CUST.CUST_GRP_ID || ' - ' || CUST.CUST_GRP_NAME AS CUST_GRP,
    CUST.DELIV_PRTY_CD,
    CUST.DIV_CD,
    CUST.ACTIV_IND,
    CUST.SHIP_OR_CNCL_CD,

    CUST.OE_GRP_CD,
    CUST.OE_SHIP_TO_DOCK_ID,
    CUST.TRUCKWISE_IND,
    CUST.CMRCL_NTWRK_INCNTV_IND,
    CUST.LOYALTY_BONUS_LVL_ID,

    ODS.ORDER_TYPE_ID,
    
    MATL.MATL_ID,
    MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR,
    MATL.PBU_NBR,
    MATL.PBU_NBR || ' - ' || MATL.PBU_NAME AS PBU,
    MATL.EXT_MATL_GRP_ID,
    MATL.TIC_CD,
    MATL.HVA_FLG,
    MATL.HVA_TXT,
    MATL.HMC_TXT,
    MATL.TIERS,
    MATL.MATL_PRTY,
    MATL.MATL_PRTY_DESCR,
    
    MATL.PROD_CORE_LVL_CD,
    MATL.TARGET_MKT_SEGMENT,
    
    MATL.BRAND_ID || ' - ' || MATL.BRAND_NAME AS BRAND,
    MATL.MATL_GRP_CD,
    MATL.MKT_AREA_NBR || ' - ' || MATL.MKT_AREA_NAME AS MKT_AREA,
    MATL.MKT_GRP_NBR || ' - ' || MATL.MKT_GRP_NAME AS MKT_GRP,
    MATL.PROD_GRP_NBR || ' - ' || MATL.PROD_GRP_NAME AS PROD_GRP,
    MATL.PROD_LINE_NBR || ' - ' || MATL.PROD_LINE_NAME AS PROD_LINE,
    MATL.MKT_CTGY_PROD_GRP_NBR || ' - ' || MATL.MKT_CTGY_PROD_GRP_NAME AS MKT_CTGY_PROD_GRP,
    MATL.MKT_CTGY_PROD_LINE_NBR || ' - ' || MATL.MKT_CTGY_PROD_LINE_NAME AS MKT_CTGY_PROD_LINE,

    MATL.PRTY_SRC_FACL_ID,
    MATL.PRTY_SRC_FACL_ID || ' - ' || MATL.PRTY_SRC_FACL_NM AS MATL_PRTY_SRC_FACL,
    TRIM( CAST( ( MATL.SOP_FAMILY_ID MOD 100 ) AS FORMAT '-9(2)' ) )  || ' - ' ||  MATL.SOP_FAMILY_NM AS SOP_FAMILY,
    MATL.PRTY_SRC_FACL_ID || ' - ' || MATL.PRTY_SRC_FACL_NM AS SOURCE_FACILITY,
    
    CUST.PRIM_SHIP_FACILITY_ID,
    ODS.FACILITY_ID,
    F.FACILITY_ID || ' - ' || F.XTND_NAME AS FACILITY,
    CAST( CASE
        WHEN CUST.PRIM_SHIP_FACILITY_ID <> ODS.FACILITY_ID
            THEN '<>'
        ELSE '=='
    END AS CHAR(2) ) AS PRIMARY_SHIP_FACILITY_IND,   
    POL.SHIP_FACILITY_ID,
    POL.DELIV_PRTY_ID AS CUST_GRP2_CD,
    ODS.CUST_GRP2_CD AS OL_CUST_GRP2_CD,
    ODS.CUST_GRP2_CD || ' - ' || CGD.CUST_GRP2_DESC AS CUST_GRP2,
    CUST.CUST_GRP2_CD AS CUST_CUST_GRP2_CD,
    ODS.RPT_FRT_PLCY_CD,
    POL.DELIV_BLK_IND,
    ODS.SHIP_COND_ID,
    NULLIF( ODS.PRTL_DLVY_CD, ' ' ) AS PRTL_DLVY_CD,
    
    NULLIF( ODS.RETURN_IND, ' ' ) AS RETURN_IND,
    NULLIF( POL.CAN_REJ_REAS_ID, ' ' ) AS CAN_REJ_REAS_ID,
    POL.CAN_REJ_REAS_ID || ' - ' || RRC.REJ_REAS_DESC AS REJ_REAS,
    POL.CREDIT_HOLD_FLG,
    POL.PO_TYPE_ID,
    POL.CANCEL_IND,
    POL.A_IND,
    POL.R_IND,
    POL.SPCL_PROC_ID,
    POL.MAX_CARR_SCAC_ID,
    
    ZEROIFNULL( POL.ORIG_ORD_QTY ) AS ORIGINAL_ORDER_QTY,
    ZEROIFNULL( POL.CURR_ORD_QTY ) AS CURRENT_ORDER_QTY,
    ODS.QTY_UNIT_MEAS_ID,
    ZEROIFNULL( POL.REL_LATE_QTY ) AS FRDD_RELEASE_LATE_QTY,
    ZEROIFNULL( POL.REL_ONTIME_QTY ) AS FRDD_RELEASE_ONTIME_QTY,
    ZEROIFNULL( POL.REL_FPDD_LATE_QTY ) AS FCDD_RELEASE_LATE_QTY,
    ZEROIFNULL( POL.REL_FPDD_ONTIME_QTY ) AS FCDD_RELEASE_ONTIME_QTY,
    ZEROIFNULL( POL.CANCEL_QTY ) AS CANCEL_QTY,
    ZEROIFNULL( POL.DELIV_LATE_QTY ) AS FRDD_DELIVER_LATE_QTY,
    ZEROIFNULL( POL.DELIV_ONTIME_QTY ) AS FRDD_DELIVER_ONTIME_QTY,
    ZEROIFNULL( POL.DELIV_FPDD_LATE_QTY ) AS FCDD_DELIVER_LATE_QTY,
    ZEROIFNULL( POL.DELIV_FPDD_ONTIME_QTY ) AS FCDD_DELIVER_ONTIME_QTY,
	
	ZEROIFNULL( POL.NE_HIT_RT_QTY ) AS FRDD_RETURN_HIT_QTY,
	ZEROIFNULL( POL.NE_HIT_CL_QTY ) AS FRDD_CLAIM_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_FP_QTY ) AS FRDD_FREIGHT_PLCY_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_CARR_PICKUP_QTY ) + ZEROIFNULL( POL.OT_HIT_WI_QTY ) AS FRDD_PHYS_LOG_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_MB_QTY ) AS FRDD_MAN_BLK_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_CH_QTY ) AS FRDD_CREDIT_HIT_QTY,
	ZEROIFNULL( POL.IF_HIT_NS_QTY ) AS FRDD_NO_STOCK_HIT_QTY,
	ZEROIFNULL( POL.IF_HIT_CO_QTY ) AS FRDD_CANCEL_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_CG_QTY ) AS FRDD_CUST_GEN_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_CG_99_QTY ) AS FRDD_MAN_REL_CUST_GEN_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_99_QTY ) AS FRDD_MAN_REL_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_LO_QTY ) AS FRDD_OTHER_HIT_QTY,

    ZEROIFNULL( POL.CURR_ORD_QTY ) - ZEROIFNULL( POL.PRFCT_ORD_HIT_QTY ) AS PRFCT_ORD_QTY,
    ZEROIFNULL( POL.PRFCT_ORD_HIT_QTY ) AS PRFCT_ORD_HIT_QTY,

    POL.PRFCT_ORD_HIT_DESC,
    POL.PRFCT_ORD_HIT_SORT_KEY, 

	ZEROIFNULL( POL.NE_FPDD_HIT_RT_QTY ) AS FCDD_RETURN_HIT_QTY,
	ZEROIFNULL( POL.NE_FPDD_HIT_CL_QTY ) AS FCDD_CLAIM_HIT_QTY,
	ZEROIFNULL( POL.OT_FPDD_HIT_FP_QTY ) AS FCDD_FREIGHT_PLCY_HIT_QTY,
	ZEROIFNULL( POL.OT_FPDD_HIT_CARR_QTY ) + ZEROIFNULL( POL.OT_FPDD_HIT_WI_QTY ) AS FCDD_PHYS_LOG_HIT_QTY,
	ZEROIFNULL( POL.OT_FPDD_HIT_MB_QTY ) AS FCDD_MAN_BLK_HIT_QTY,
	ZEROIFNULL( POL.OT_FPDD_HIT_CH_QTY ) AS FCDD_CREDIT_HOLD_HIT_QTY,
	ZEROIFNULL( POL.IF_FPDD_HIT_NS_QTY ) AS FCDD_NO_STOCK_HIT_QTY,
	ZEROIFNULL( POL.IF_FPDD_HIT_CO_QTY ) AS FCDD_CANCEL_HIT_QTY,
	ZEROIFNULL( POL.OT_FPDD_HIT_CG_QTY ) AS FCDD_CUST_GEN_HIT_QTY,
	ZEROIFNULL( POL.OT_FPDD_HIT_CG_99_QTY ) AS FCDD_MAN_REL_CUST_GEN_HIT_QTY,
	ZEROIFNULL( POL.OT_FPDD_HIT_99_QTY ) AS FCDD_MAN_REL_HIT_QTY,
	ZEROIFNULL( POL.OT_FPDD_HIT_LO_QTY ) AS FCDD_OTHER_HIT_QTY,
    
    ZEROIFNULL( POL.CURR_ORD_QTY ) - ZEROIFNULL( POL.PRFCT_ORD_HIT_QTY ) AS PRFCT_ORD_FPDD_QTY,
    ZEROIFNULL( POL.PRFCT_ORD_FPDD_HIT_QTY ) AS PRFCT_ORD_FPDD_HIT_QTY,
    POL.PRFCT_ORD_FPDD_HIT_DESC,
    POL.PRFCT_ORD_FPDD_HIT_SORT_KEY,
    
    POL.ORDER_DT,
    ODS.CUST_RDD AS ORDD,
    
    POL.FMAD_DT AS FRDD_FMAD,
    POL.FPGI_DT AS FRDD_FPGI,
    POL.REQ_DELIV_DT AS FRDD,
    
    POL.FRST_PROM_DELIV_DT - ( POL.REQ_DELIV_DT - POL.FMAD_DT ) AS FCDD_FMAD,
    POL.FCPGI_DT AS FCDD_FPGI,
    POL.FRST_PROM_DELIV_DT AS FCDD,
    
    POL.MAX_DELIV_NOTE_CREA_DT,
    POL.CUST_APPT_DT,
    POL.MAX_EDI_DELIV_DT,
    POL.MAX_SAP_DELIV_DT,
    POL.ACTL_DELIV_DT,
    
    POL.CMPL_IND,
    POL.CMPL_DT,
    POL.NO_STK_DT,
    POL.CAN_EFF_DT,
    
    POL.FPDD_CMPL_IND,
    POL.FPDD_CMPL_DT,
    POL.FPDD_NO_STK_DT
    
FROM NA_BI_VWS.PRFCT_ORD_LINE POL

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID
        AND CUST.CUST_GRP_ID <> 'RO'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = POL.MATL_ID
        -- AND MATL.PBU_NBR IN ( '01', '03' ) 
        AND MATL.PBU_NBR = '01'
        AND MATL.EXT_MATL_GRP_ID = 'TIRE'

    INNER JOIN NA_BI_VWS.ORD_DTL_SMRY ODS
        ON ODS.ORDER_ID = POL.ORDER_ID
        AND ODS.ORDER_LINE_NBR = POL.ORDER_LINE_NBR
        AND ODS.ORDER_CAT_ID = 'C'
        AND ODS.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
        AND ODS.CUST_GRP_ID <> '3R'
        AND ODS.PO_TYPE_ID <> 'RO'
        AND ODS.CUST_GRP2_CD = 'TLB'
        
    LEFT OUTER JOIN GDYR_BI_VWS.NAT_ORDER_REJ_REAS_CURR RRC
        ON RRC.REJ_REAS_ID = POL.CAN_REJ_REAS_ID

    LEFT OUTER JOIN NA_BI_VWS.CUST_GRP2_DESC_EN_CURR CGD
        ON CGD.CUST_GRP2_CD = POL.DELIV_PRTY_ID

    LEFT OUTER JOIN GDYR_VWS.FACILITY F
        ON F.FACILITY_ID = POL.SHIP_FACILITY_ID
        AND F.ORIG_SYS_ID = 2
        AND F.EXP_DT = CAST( '5555-12-31' AS DATE )
        AND F.LANG_ID = 'EN'

WHERE
    -- FOR FRDD
    POL.CMPL_IND = 1 
    AND POL.CMPL_DT < CURRENT_DATE
    AND POL.CMPL_DT >= DATE '2013-09-01'
    
    -- FOR FCDD
    /*POL.FPDD_CMPL_IND = 1 
    AND POL.FPDD_CMPL_DT < CURRENT_DATE
    AND POL.FRST_PROM_DELIV_DT IS NOT NULL*/
    ) OL

GROUP BY
/*    OL.SHIP_TO_CUST_ID,
    OL.SHIP_TO_CUST_NAME,
    OL.OWN_CUST_ID,
    OL.OWN_CUST_NAME,
    OL.MATL_ID,
    OL.MATL_DESCR,*/
    OL.PBU,
/*    OL.FACILITY,
    OL.CUST_GRP2,
    OL.ORIGINAL_ORDER_QTY,
    OL.CURRENT_ORDER_QTY,
    OL.QTY_UNIT_MEAS_ID,
    OL.FRDD_RELEASE_LATE_QTY,
    OL.FRDD_RELEASE_ONTIME_QTY,
    
    OL.ORDER_DT,
    OL.ORDD,
    OL.FRDD_FMAD,
    OL.FRDD_FPGI,
    OL.FRDD,
    OL.FCDD_FMAD,
    OL.FCDD_FPGI,
    OL.FCDD,
    
    OL.MAX_DELIV_NOTE_CREA_DT,
    OL.CUST_APPT_DT,
    OL.MAX_EDI_DELIV_DT,
    OL.MAX_SAP_DELIV_DT,
    
    OL.CMPL_IND,*/
    OL.CMPL_DT/*,
    OL.NO_STK_DT,
    OL.CAN_EFF_DT,
    OL.PRFCT_ORD_HIT_DESC*/

ORDER BY
    OL.CMPL_DT