SELECT
    Q.FCDD_COMPLETE_MONTH AS "FCDD Complete Month",
    Q.C_TO_O_DAYS AS "Order Dt to FCDD Interval",
    Q.ORDER_QTY AS "Order Qty",
    Q.FCDD_ONTIME_QTY AS "FCDD On Time Qty",
    Q.FCDD_LATE_QTY AS "FCDD Late Qty",
    Q.FCDD_ONTIME_QTY + Q.FCDD_LATE_QTY AS "FCDD Late + On Time Qty"

FROM (

SELECT
    CAL.MONTH_DT AS FCDD_COMPLETE_MONTH,
    CAST( CASE WHEN POL.FRST_PROM_DELIV_DT < POL.REQ_DELIV_DT THEN POL.REQ_DELIV_DT ELSE POL.FRST_PROM_DELIV_DT END - POL.ORDER_DT AS INTEGER ) AS C_TO_O_DAYS,

    SUM( POL.CURR_ORD_QTY ) AS ORDER_QTY,
    SUM( POL.PRFCT_ORD_QTY ) AS FRDD_ONTIME_QTY,
    SUM( POL.PRFCT_ORD_HIT_QTY ) AS FRDD_LATE_QTY,
    SUM( POL.PRFCT_ORD_FPDD_QTY ) AS FCDD_ONTIME_QTY,
    SUM( POL.PRFCT_ORD_FPDD_HIT_QTY ) AS FCDD_LATE_QTY
    
FROM NA_BI_VWS.PRFCT_ORD_LINE POL
    
    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID
        AND CUST.CUST_GRP_ID <> '3R'
        AND CUST.SALES_ORG_CD NOT IN ( 'N302', 'N312', 'N322' )
        AND CUST.CUST_GRP_ID NOT IN ( '38', '67', '17' )
        -- AND CUST.SHIP_OR_CNCL_CD IS NULL 

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = POL.MATL_ID
        AND MATL.EXT_MATL_GRP_ID = 'TIRE'
        AND MATL.PBU_NBR IN ( '01' )
    
    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE = POL.FPDD_CMPL_DT
        AND CAL.MONTH_DT = CAST( '2014-02-01' AS DATE )

WHERE
    POL.ORIG_SYS_ID = 2
    AND POL.SBU_ID = 2
    AND POL.FPDD_CMPL_IND = 1
    AND POL.FRST_PROM_DELIV_DT IS NOT NULL
    AND FPDD_CMPL_DT BETWEEN DATE '2013-01-01' AND ( CURRENT_DATE - 1 )
    AND POL.PBU_NBR IN ( '01' )
    
GROUP BY
    FCDD_COMPLETE_MONTH,
    C_TO_O_DAYS

HAVING
    ( ORDER_QTY + FCDD_ONTIME_QTY + FCDD_LATE_QTY ) > 0

    ) Q

ORDER BY
    Q.FCDD_COMPLETE_MONTH,
    Q.C_TO_O_DAYS