SELECT
    POL.ORDER_ID,
    POL.ORDER_LINE_NBR,

    POL.SHIP_TO_CUST_ID,

    POL.MATL_ID,
    POL.PBU_NBR,

    POL.SHIP_FACILITY_ID,
    POL.DELIV_PRTY_ID,

    POL.CREDIT_HOLD_FLG,
    POL.NUM_DELIV_LINES,
    POL.ORD_LN_CT,
    NULLIF( POL.CAN_REJ_REAS_ID, ' ' ) AS REJ_REAS_ID,
    NULLIF( POL.PO_TYPE_ID, ' ' ) AS PO_TYPE_ID,
    NULLIF( POL.SPCL_PROC_ID, ' ' ) AS SPCL_PROC_ID,

    POL.CANCEL_IND,
    POL.DELIV_BLK_IND,
    POL.A_IND,
    POL.R_IND,

    POL.CMPL_IND AS FRDD_CMPL_IND,

    POL.FPDD_CMPL_IND AS FCDD_CMPL_IND,

    POL.ORIG_ORD_QTY,
    POL.CURR_ORD_QTY,
    POL.CANCEL_QTY,

    POL.ORDER_DT,
    POL.REQ_SHIP_DT,
    POL.ORIG_REQ_SHIP_DT,
    POL.CUST_APPT_DT,
    POL.MAX_DELIV_NOTE_CREA_DT,
    POL.MAX_EDI_DELIV_DT,
    POL.MAX_SAP_DELIV_DT,
    POL.ACTL_DELIV_DT,

    POL.ORDER_DT,
    POL.OL_DT,
    POL.CAN_EFF_DT,
    POL.LATEST_SHIP_DT,

    POL.FMAD_DT AS FRDD_FMAD,
    POL.FPGI_DT AS FRDD_FPGI,
    POL.REQ_DELIV_DT AS FRDD,

    POL.CMPL_DT AS FRDD_CMPL_DT,
    POL.NO_STK_DT AS FRDD_NO_STK_DT,

    POL.REL_LATE_QTY AS FRDD_REL_LATE_QTY,
    POL.REL_ONTIME_QTY AS FRDD_REL_ON_TIME_QTY,
    POL.COMMIT_ONTIME_QTY AS FRDD_COMMIT_ON_TIME_QTY,
    POL.DELIV_LATE_QTY AS FRDD_DELIV_LATE_QTY,
    POL.DELIV_ONTIME_QTY AS FRDD_DELIV_ON_TIME_QTY,
    POL.NE_HIT_RT_QTY AS FRDD_RETURN_HIT_QTY,
    POL.NE_HIT_CL_QTY AS FRDD_CLAIM_HIT_QTY,
    POL.OT_HIT_FP_QTY AS FRDD_FRT_PLCY_HIT_QTY,
    POL.OT_HIT_CARR_PICKUP_QTY + POL.OT_HIT_WI_QTY AS FRDD_PHYS_LOG_HIT_QTY,
    POL.OT_HIT_MB_QTY AS FRDD_MAN_BLK_HIT_QTY,
    POL.OT_HIT_CH_QTY AS FRDD_CREDIT_HOLD_HIT_QTY,
    POL.IF_HIT_NS_QTY AS FRDD_NO_STK_HIT_QTY,
    POL.IF_HIT_CO_QTY AS FRDD_CANCEL_HIT_QTY,
    POL.OT_HIT_CG_QTY AS FRDD_CUST_GEN_HIT_QTY,
    POL.OT_HIT_CG_99_QTY AS FRDD_MAN_CUST_GEN_HIT_QTY,
    POL.OT_HIT_99_QTY AS FRDD_MAN_REL_HIT_QTY,
    POL.OT_HIT_LO_QTY AS FRDD_OTHER_HIT_QTY,
    POL.PRFCT_ORD_HIT_QTY AS  FRDD_TOTAL_HIT_QTY,
    POL.PRFCT_ORD_QTY AS FRDD_ON_TIME_QTY,
    POL.PRFCT_ORD_HIT_DESC AS FRDD_HIT_DESCRIPTION,
    POL.PRFCT_ORD_HIT_REAS AS FRDD_HIT_CD,

    POL.FRST_PROM_DELIV_DT - ( CAST( POL.REQ_DELIV_DT - POL.FMAD_DT AS INTEGER ) ) AS FCDD_FMAD,
    POL.FCPGI_DT AS FCDD_FPGI,
    POL.FRST_PROM_DELIV_DT AS FCDD,

    POL.FP_HIT_REJ_DT AS FCDD_HIT_REJ_DT,
    POL.FPDD_CMPL_DT AS FCDD_CMPL_DT,
    POL.FPDD_NO_STK_DT AS FCDD_NO_STK_DT,

    POL.FPDD_ORD_QTY AS FCDD_ORDER_QTY,
    POL.REL_FPDD_LATE_QTY AS FCDD_REL_LATE_QTY,
    POL.REL_FPDD_ONTIME_QTY AS FCDD_REL_ON_TIME_QTY,
    POL.FPDD_COMMIT_ONTIME_QTY AS FCDD_COMMIT_ON_TIME_QTY,
    POL.DELIV_FPDD_LATE_QTY AS FCDD_DELIV_LATE_QTY,
    POL.DELIV_FPDD_ONTIME_QTY AS FCDD_DELIV_ON_TIME_QTY,
    POL.NE_FPDD_HIT_RT_QTY AS FCDD_RETURN_HIT_QTY,
    POL.NE_FPDD_HIT_CL_QTY AS FCDD_CLAIM_HIT_QTY,
    POL.OT_FPDD_HIT_FP_QTY AS FCDD_FRT_PLCY_HIT_QTY,
    ( POL.OT_FPDD_HIT_CARR_QTY + POL.OT_FPDD_HIT_WI_QTY ) AS FCDD_PHYS_LOG_HIT_QTY,
    POL.OT_FPDD_HIT_MB_QTY AS FCDD_MAN_BLK_HIT_QTY,
    POL.OT_FPDD_HIT_CH_QTY AS FCDD_CREDIT_HOLD_HIT_QTY,
    POL.IF_FPDD_HIT_NS_QTY AS FCDD_NO_STK_HIT_QTY,
    POL.IF_FPDD_HIT_CO_QTY AS FCDD_CANCEL_HIT_QTY,
    POL.OT_FPDD_HIT_CG_QTY AS FCDD_CUST_GEN_HIT_QTY,
    POL.OT_FPDD_HIT_CG_99_QTY AS FCDD_MAN_CUST_GEN_HIT_QTY,
    POL.OT_FPDD_HIT_99_QTY AS FCDD_MAN_REL_HIT_QTY,
    POL.OT_FPDD_HIT_LO_QTY AS FCDD_OTHER_HIT_QTY,
    POL.PRFCT_ORD_FPDD_HIT_QTY AS FCDD_TOTAL_HIT_QTY,
    POL.PRFCT_ORD_FPDD_QTY AS FCDD_ON_TIME_QTY,
    POL.PRFCT_ORD_FPDD_HIT_DESC AS FCDD_HIT_DESCRIPTION,
    POL.PRFCT_ORD_FPDD_HIT_REAS AS FCDD_HIT_CD

FROM NA_BI_VWS.PRFCT_ORD_LINE POL

WHERE
    POL.ORIG_SYS_ID = 2
    AND POL.SBU_ID = 2
    AND POL.ACTL_DELIV_DT IS NOT NULL
    AND POL.ACTL_DELIV_DT BETWEEN DATE '2013-01-01' AND CURRENT_DATE
    AND POL.SHIP_TO_CUST_ID NOT IN (
        SELECT
            C.SHIP_TO_CUST_ID
        FROM GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        WHERE
            C.SALES_ORG_CD IN ( 'N302', 'N312', 'N322' )
            AND C.CUST_GRP_ID = '3R'
            AND C.SHIP_OR_CNCL_CD = 'X'
        )
    AND POL.PBU_NBR IN ( '01', '03' )

ORDER BY
    POL.ORDER_ID,
    POL.ORDER_LINE_NBR