SELECT
    Q.CMPL_MTH AS "FRDD Complete Month",
    Q.OWN_CUST_ID AS "Common Owner ID",
    Q.OWN_CUST_NAME AS "Common Owner Name",
    Q.EXT_MATL_GRP_ID AS "External Material Group ID",
    Q.PBU,
    Q.FACILITY AS "Facility",
    Q.ATD_RDD_ONTIME_DESC AS "ATD Reasessment",
    Q.PRFCT_ORD_HIT_DESC AS "FRDD Hit Description",
    SUM( Q.CURRENT_ORDER_QTY ) AS "Order Qty",
    SUM( Q.FRDD_ONTIME_QTY ) AS "FRDD On Time Qty",
    SUM( Q.FRDD_LATE_QTY ) AS "FRDD Late Qty",
    SUM( Q.ADJ_FRDD_ONTIME_QTY ) AS "Adj. FRDD On Time Qty",
    SUM( Q.ADJ_FRDD_LATE_QTY ) AS "Adj. FRDD Late Qty",
	SUM( Q.FRDD_RETURN_HIT_QTY ) AS "FRDD Return Hit Qty",
	SUM( Q.FRDD_CLAIM_HIT_QTY ) AS "FRDD Claim Hit Qty",
	SUM( Q.FRDD_FREIGHT_PLCY_HIT_QTY ) AS "FRDD Freight Policy Hit Qty",
	SUM( Q.FRDD_PHYS_LOG_HIT_QTY ) AS "FRDD Phys. Log. Hit Qty",
	SUM( Q.FRDD_MAN_BLK_HIT_QTY ) AS "FRDD Manual Block Hit Qty",
	SUM( Q.FRDD_CREDIT_HIT_QTY ) AS "FRDD Credit Hold Hit Qty",
	SUM( Q.FRDD_NO_STOCK_HIT_QTY ) AS "FRDD No Stock Hit Qty",
	SUM( Q.FRDD_CANCEL_HIT_QTY ) AS "FRDD Cancel Hit Qty",
	SUM( Q.FRDD_CUST_GEN_HIT_QTY ) AS "FRDD Cust. Gen. Hit Qty",
	SUM( Q.FRDD_MAN_REL_CUST_GEN_HIT_QTY ) AS "FRDD MR Cust. Gen. Hit Qty",
	SUM( Q.FRDD_MAN_REL_HIT_QTY ) AS "FRDD Manual Release Hit Qty",
	SUM( Q.FRDD_OTHER_HIT_QTY ) AS "FRDD Other Hit Qty"

FROM (

SELECT
    POL.ORDER_ID,
    POL.ORDER_LINE_NBR,
    
    POL.SHIP_TO_CUST_ID,
    CUST.CUST_NAME AS SHIP_TO_CUST_NAME,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,
    
/*    CUST.SALES_ORG_CD || ' - ' || CUST.SALES_ORG_NAME AS SALES_ORG,
    CUST.DISTR_CHAN_CD || ' - ' || CUST.DISTR_CHAN_NAME AS DISTR_CHAN,
    CUST.CUST_GRP_ID || ' - ' || CUST.CUST_GRP_NAME AS CUST_GRP,
    CUST.ACTIV_IND,
    CUST.SHIP_OR_CNCL_CD,*/

    ODS.ORDER_TYPE_ID,
    
    MATL.MATL_ID,
    MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR,
    MATL.PBU_NBR,
    MATL.PBU_NBR || ' - ' || MATL.PBU_NAME AS PBU,
    MATL.EXT_MATL_GRP_ID,
/*    MATL.TIC_CD,
    MATL.HVA_TXT,
    MATL.HMC_TXT,
    MATL.TIERS,
    MATL.MATL_PRTY_DESCR,*/
    
/*    MATL.PROD_CORE_LVL_CD,
    MATL.TARGET_MKT_SEGMENT,
    
    MATL.BRAND_ID || ' - ' || MATL.BRAND_NAME AS BRAND,
    MATL.MATL_GRP_CD,
    MATL.MKT_AREA_NBR || ' - ' || MATL.MKT_AREA_NAME AS MKT_AREA,
    MATL.MKT_GRP_NBR || ' - ' || MATL.MKT_GRP_NAME AS MKT_GRP,
    MATL.PROD_GRP_NBR || ' - ' || MATL.PROD_GRP_NAME AS PROD_GRP,
    MATL.PROD_LINE_NBR || ' - ' || MATL.PROD_LINE_NAME AS PROD_LINE,
    MATL.MKT_CTGY_PROD_GRP_NBR || ' - ' || MATL.MKT_CTGY_PROD_GRP_NAME AS MKT_CTGY_PROD_GRP,
    MATL.MKT_CTGY_PROD_LINE_NBR || ' - ' || MATL.MKT_CTGY_PROD_LINE_NAME AS MKT_CTGY_PROD_LINE,

    MATL.PRTY_SRC_FACL_ID,
    MATL.PRTY_SRC_FACL_ID || ' - ' || MATL.PRTY_SRC_FACL_NM AS MATL_PRTY_SRC_FACL,
    TRIM( CAST( ( MATL.SOP_FAMILY_ID MOD 100 ) AS FORMAT '-9(2)' ) )  || ' - ' ||  MATL.SOP_FAMILY_NM AS SOP_FAMILY,
    MATL.PRTY_SRC_FACL_ID || ' - ' || MATL.PRTY_SRC_FACL_NM AS SOURCE_FACILITY,*/
    
    /*CUST.PRIM_SHIP_FACILITY_ID,
    ODS.FACILITY_ID,*/
    F.FACILITY_ID || ' - ' || F.XTND_NAME AS FACILITY,
/*    CAST( CASE
        WHEN CUST.PRIM_SHIP_FACILITY_ID <> ODS.FACILITY_ID
            THEN '<>'
        ELSE '=='
    END AS CHAR(2) ) AS PRIMARY_SHIP_FACILITY_IND,   */
/*    POL.SHIP_FACILITY_ID,
    ODS.CUST_GRP2_CD AS OL_CUST_GRP2_CD,
    ODS.CUST_GRP2_CD || ' - ' || CGD.CUST_GRP2_DESC AS CUST_GRP2,
    POL.DELIV_BLK_IND,
    ODS.SHIP_COND_ID,
    NULLIF( ODS.PRTL_DLVY_CD, '') AS PRTL_DLVY_CD,*/
    
/*    NULLIF( ODS.RETURN_IND, '') AS RETURN_IND,
    NULLIF( POL.CAN_REJ_REAS_ID, '') AS CAN_REJ_REAS_ID,
    POL.CAN_REJ_REAS_ID || ' - ' || RRC.REJ_REAS_DESC AS REJ_REAS,
    POL.CREDIT_HOLD_FLG,
    POL.PO_TYPE_ID,
    POL.CANCEL_IND,
    POL.A_IND,
    POL.R_IND,
    POL.SPCL_PROC_ID,
    POL.MAX_CARR_SCAC_ID,*/
    
    ZEROIFNULL( POL.ORIG_ORD_QTY ) AS ORIGINAL_ORDER_QTY,
    ZEROIFNULL( POL.CURR_ORD_QTY ) AS CURRENT_ORDER_QTY,
    ODS.QTY_UNIT_MEAS_ID,
    ZEROIFNULL( POL.REL_LATE_QTY ) AS FRDD_RELEASE_LATE_QTY,
    ZEROIFNULL( POL.REL_ONTIME_QTY ) AS FRDD_RELEASE_ONTIME_QTY,
    ZEROIFNULL( POL.CANCEL_QTY ) AS CANCEL_QTY,
    ZEROIFNULL( POL.DELIV_LATE_QTY ) AS FRDD_DELIVER_LATE_QTY,
    ZEROIFNULL( POL.DELIV_ONTIME_QTY ) AS FRDD_DELIVER_ONTIME_QTY,
	
	ZEROIFNULL( POL.NE_HIT_RT_QTY ) AS FRDD_RETURN_HIT_QTY,
	ZEROIFNULL( POL.NE_HIT_CL_QTY ) AS FRDD_CLAIM_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_FP_QTY ) AS FRDD_FREIGHT_PLCY_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_CARR_PICKUP_QTY ) + ZEROIFNULL( POL.OT_HIT_WI_QTY ) AS FRDD_PHYS_LOG_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_MB_QTY ) AS FRDD_MAN_BLK_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_CH_QTY ) AS FRDD_CREDIT_HIT_QTY,
	ZEROIFNULL( POL.IF_HIT_NS_QTY ) AS FRDD_NO_STOCK_HIT_QTY,
	ZEROIFNULL( POL.IF_HIT_CO_QTY ) AS FRDD_CANCEL_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_CG_QTY ) AS FRDD_CUST_GEN_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_CG_99_QTY ) AS FRDD_MAN_REL_CUST_GEN_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_99_QTY ) AS FRDD_MAN_REL_HIT_QTY,
	ZEROIFNULL( POL.OT_HIT_LO_QTY ) AS FRDD_OTHER_HIT_QTY,

    ZEROIFNULL( POL.CURR_ORD_QTY ) - ZEROIFNULL( POL.PRFCT_ORD_HIT_QTY ) AS FRDD_ONTIME_QTY,
    ZEROIFNULL( POL.PRFCT_ORD_HIT_QTY ) AS FRDD_LATE_QTY,

    POL.PRFCT_ORD_HIT_DESC,
    POL.PRFCT_ORD_HIT_SORT_KEY, 

    POL.ORDER_DT,
    CAST( POL.ORDER_DT + 8 AS DATE ) AS ATD_RDD,
    POL.FMAD_DT AS FRDD_FMAD,
    POL.FPGI_DT AS FRDD_FPGI,
    POL.REQ_DELIV_DT AS FRDD,
/*    CASE
        WHEN  CUST.OWN_CUST_ID = '00A0006582'
            THEN ( CASE
            WHEN ATD_RDD > FRDD
                THEN 'More Time'
            WHEN ATD_RDD = FRDD
                THEN 'Same Time'
            WHEN ATD_RDD < FRDD
                THEN 'Less Time'
            END )
        ELSE NULL
    END AS FRDD_VS_ATD_RDD,*/
    
    POL.MAX_DELIV_NOTE_CREA_DT,
    POL.CUST_APPT_DT,
    POL.MAX_EDI_DELIV_DT,
    POL.MAX_SAP_DELIV_DT,
    POL.ACTL_DELIV_DT,
    
    CASE
        WHEN  CUST.OWN_CUST_ID = '00A0006582'
            THEN ( CASE
                WHEN ATD_RDD <= POL.ACTL_DELIV_DT
                    THEN 'On Time'
                WHEN ATD_RDD > POL.ACTL_DELIV_DT
                    THEN 'Late'
                WHEN POL.ACTL_DELIV_DT IS NULL
                    THEN 'No Delivery Date'
                ELSE 'Unknown - Presumed Late'
            END )
        ELSE NULL
    END AS ATD_RDD_ONTIME_DESC,
    CASE
        WHEN ATD_RDD_ONTIME_DESC = 'On Time'
            THEN FRDD_ONTIME_QTY + FRDD_LATE_QTY
        ELSE FRDD_ONTIME_QTY
    END AS ADJ_FRDD_ONTIME_QTY,
    CURRENT_ORDER_QTY - ADJ_FRDD_ONTIME_QTY AS ADJ_FRDD_LATE_QTY,
    
    POL.CMPL_IND,
    POL.CMPL_DT,
    CAST( POL.CMPL_DT - CAST( EXTRACT( DAY FROM POL.CMPL_DT ) - 1 AS INTEGER ) AS DATE ) AS CMPL_MTH,
    POL.NO_STK_DT,
    POL.CAN_EFF_DT
    
FROM NA_BI_VWS.PRFCT_ORD_LINE POL

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID
        AND CUST.CUST_GRP_ID <> '3R'
        -- AND CUST.OWN_CUST_ID  = '00A0006582'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = POL.MATL_ID
        AND MATL.PBU_NBR IN ( '01', '03', '04', '05', '07', '08', '09' ) 
        -- AND MATL.EXT_MATL_GRP_ID = 'TIRE'

    LEFT OUTER JOIN NA_BI_VWS.ORD_DTL_SMRY ODS
        ON ODS.ORDER_ID = POL.ORDER_ID
        AND ODS.ORDER_LINE_NBR = POL.ORDER_LINE_NBR
        AND ODS.ORDER_CAT_ID = 'C'
        AND ODS.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
        AND ODS.CUST_GRP_ID <> '3R'
        AND ODS.PO_TYPE_ID <> 'RO'
        
    LEFT OUTER JOIN GDYR_BI_VWS.NAT_ORDER_REJ_REAS_CURR RRC
        ON RRC.REJ_REAS_ID = POL.CAN_REJ_REAS_ID

    LEFT OUTER JOIN NA_BI_VWS.CUST_GRP2_DESC_EN_CURR CGD
        ON CGD.CUST_GRP2_CD = POL.DELIV_PRTY_ID

    LEFT OUTER JOIN GDYR_BI_VWS.NAT_FACILITY_HIER_EN_CURR F
        ON F.FACILITY_ID = POL.SHIP_FACILITY_ID

WHERE
    -- FOR FRDD
    POL.CMPL_IND = 1 
    AND POL.CMPL_DT BETWEEN CAST( ( EXTRACT( YEAR FROM ( CURRENT_DATE - 1 ) ) -1) || '-01-01' AS DATE) AND ( CURRENT_DATE - 1 )
    AND POL.PRFCT_ORD_HIT_DESC <> 'FRDD Hit - Error' --  'No FRDD Hit', 
    AND POL.CUST_GRP_ID <> '3R'

    ) Q

GROUP BY
    Q.CMPL_MTH,
    Q.OWN_CUST_ID,
    Q.OWN_CUST_NAME,
    Q.EXT_MATL_GRP_ID,
    Q.PBU,
    Q.FACILITY,
    Q.ATD_RDD_ONTIME_DESC,
    Q.PRFCT_ORD_HIT_DESC
    
ORDER BY
    Q.CMPL_MTH,
    Q.OWN_CUST_ID,
    Q.PBU,
    Q.FACILITY,
    Q.EXT_MATL_GRP_ID