SELECT
    OD.ORDER_ID,
    OD.ORDER_LINE_NBR,
    OD.SHIP_TO_CUST_ID,
    OD.MATL_ID,
    NULLIF( OD.DELIV_BLK_CD, '' ) AS DELIV_BLK_CD,
    OD.ORDER_DT,
    OD.FRST_MATL_AVL_DT AS FRDD_FMAD,
    OD.FRST_PLN_GOODS_ISS_DT AS FRDD_FPGI,
    OD.FRST_RDD AS FRDD,
    OD.QTY_UNIT_MEAS_ID,
    SUM( OD.ORDER_QTY ) AS SL_ORDERED_QTY,
    SUM( OD.CNFRM_QTY ) AS SL_CONFIRMED_QTY,
    SL_ORDERED_QTY - SL_CONFIRMED_QTY AS SL_UNCONFIRMED_QTY,
    
    SUM( CASE
        WHEN NULLIF( OD.DELIV_BLK_CD, '' ) IS NOT NULL
            THEN OD.CNFRM_QTY
        ELSE 0
    END ) AS ANY_DELIV_BLK_CNFRM_QTY,
    SUM( CASE
        WHEN NULLIF( OD.DELIV_BLK_CD, '' ) IS NULL
            THEN OD.CNFRM_QTY
        ELSE 0
    END ) AS NO_DELIV_BLK_CNFRM_QTY,
    SUM( CASE
        WHEN NULLIF( OD.DELIV_BLK_CD, '' ) = '02'
            THEN OD.CNFRM_QTY
        ELSE 0
    END ) AS DELIV_BLK_02_CNFRM_QTY,
    SUM( CASE
        WHEN NULLIF( OD.DELIV_BLK_CD, '' ) = '09'
            THEN OD.CNFRM_QTY
        ELSE 0
    END ) AS DELIV_BLK_09_CNFRM_QTY,
    SUM( CASE
        WHEN NULLIF( OD.DELIV_BLK_CD, '' ) = '11'
            THEN OD.CNFRM_QTY
        ELSE 0
    END ) AS DELIV_BLK_11_CNFRM_QTY,
    SUM( CASE
        WHEN NULLIF( OD.DELIV_BLK_CD, '' ) = '15'
            THEN OD.CNFRM_QTY
        ELSE 0
    END ) AS DELIV_BLK_15_CNFRM_QTY,
    SUM( CASE
        WHEN NULLIF( OD.DELIV_BLK_CD, '' ) = 'YF'
            THEN OD.CNFRM_QTY
        ELSE 0
    END ) AS DELIV_BLK_YF_CNFRM_QTY,
    SUM( CASE
        WHEN NULLIF( OD.DELIV_BLK_CD, '' ) ='YR'
            THEN OD.CNFRM_QTY
        ELSE 0
    END ) AS DELIV_BLK_YR_CNFRM_QTY,
    SUM( CASE
        WHEN NULLIF( OD.DELIV_BLK_CD, '' ) ='YT'
            THEN OD.CNFRM_QTY
        ELSE 0
    END ) AS DELIV_BLK_YT_CNFRM_QTY

FROM NA_BI_VWS.ORDER_DETAIL OD

WHERE
    OD.FRST_RDD BETWEEN OD.EFF_DT AND OD.EXP_DT
    AND OD.ORDER_CAT_ID = 'C'
    AND OD.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' ) 
    AND OD.PO_TYPE_ID <> 'RO'
    AND OD.CUST_GRP_ID <> '3R'
    AND ( OD.ORDER_ID, OD.ORDER_LINE_NBR ) IN ( 
        SELECT
            P.ORDER_ID,
            P.ORDER_LINE_NBR
        FROM NA_BI_VWS.PRFCT_ORD_LINE P
        WHERE
            P.CMPL_IND = 1
            AND P.CMPL_DT BETWEEN CAST( '2013-01-01' AS DATE ) AND ( CURRENT_DATE - 1 )
    )

GROUP BY
    OD.ORDER_ID,
    OD.ORDER_LINE_NBR,
    OD.SHIP_TO_CUST_ID,
    OD.MATL_ID,
    DELIV_BLK_CD,
    OD.ORDER_DT,
    FRDD_FMAD,
    FRDD_FPGI,
    FRDD,
    OD.QTY_UNIT_MEAS_ID