SELECT
    CURRENT_DATE AS SNAPSHOT_DATE,
    POL.ORDER_ID,
    POL.ORDER_LINE_NBR,
    POL.CMPL_IND,
    POL.CMPL_DT,
    POL.PRFCT_ORD_HIT_DESC
FROM NA_BI_VWS.PRFCT_ORD_LINE POL
WHERE
    CMPL_DT = ( CURRENT_DATE - 1 )
    AND CMPL_IND = 1
    AND PRFCT_ORD_HIT_DESC = 'FRDD Hit - No Stock'
ORDER BY
    POL.ORDER_ID,
    POL.ORDER_LINE_NBR