-- PROPORTIONS FOR ALL ORDERS
SELECT
    OOF.PBU_NBR || ' - ' || OOF.PBU_NAME AS PBU,
    OOF.EXT_MATL_GRP_ID AS "External Material Group ID",
    OOF.OWN_CUST_ID || ' - ' || OOF.OWN_CUST_NAME AS "Common Owner",
    OOF.MKT_AREA AS "Market Area",
    OOF.MKT_GRP AS "Market Group",
    OOF.PROD_GRP AS "Product Group",
    OOF.PROD_LINE AS "Product Line",
    OOF.DELIV_PRTY_ID AS "Delivery Priority ID",
    OOF.CUST_GRP2_CD AS "Customer Group 2 Code",
    OOF.MATL_NO_8 || ' - ' || OOF.DESCR AS "Material Description",
    CAST( CAST( OOF.FCDD - CURRENT_DATE AS INTEGER ) / 7 AS INTEGER ) AS "Lead Time (Weeks)",
    CAST( SUM( OOF.OPEN_CONFIRMED_QTY ) AS INTEGER) AS "Open Confirmed Qty",
    CAST( SUM( CASE
        WHEN OOF.PDD > OOF.FCDD
            THEN OOF.OPEN_CONFIRMED_QTY
        ELSE 0
    END ) AS INTEGER ) AS "Open Confirmed Qty PDD > FCDD",

    OOF.QTY_UNIT_MEAS_ID AS "Quantity UOM"

FROM (
SELECT
    OOSL.ORDER_FISCAL_YR,
    OOSL.ORDER_ID,
    OOSL.ORDER_LINE_NBR,
    OOSL.SCHED_LINE_NBR,

    OOSL.CREDIT_HOLD_FLG,

    ODC.SHIP_TO_CUST_ID ,
    CUST.CUST_NAME AS SHIP_TO_CUST_NAME,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,

    ODC.SALES_ORG_CD,
    ODC.DISTR_CHAN_CD,
    ODC.CUST_GRP_ID,
    NULLIF( ODC.PO_TYPE_ID, ' ' ) AS PO_TYPE_ID,
    ODC.ORDER_CAT_ID,
    ODC.ORDER_TYPE_ID,
    CASE WHEN ODC.CANCEL_IND = 'Y' THEN 'Y' END AS CANCEL_IND,
    CASE WHEN ODC.RETURN_IND = 'Y' THEN 'Y' END AS RETURN_IND,
    NULLIF( ODC.DELIV_BLK_CD, ' ' ) AS DELIV_BLK_CD,
    ODC.FACILITY_ID,
    ODC.SHIP_PT_ID,
    ODC.DELIV_PRTY_ID,
    ODC.CUST_GRP2_CD,
    ODC.SPCL_PROC_ID,

    ODC.MATL_ID,
    MATL.MATL_NO_8,
    MATL.DESCR,
    MATL.PBU_NBR,
    MATL.PBU_NAME,
    MATL.EXT_MATL_GRP_ID,
    MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME AS MKT_AREA,
    MATL.MKT_CTGY_MKT_GRP_NBR || ' - ' || MATL.MKT_CTGY_MKT_GRP_NAME AS MKT_GRP,
    MATL.MKT_CTGY_PROD_GRP_NBR || ' - ' || MATL.MKT_CTGY_PROD_GRP_NAME AS PROD_GRP,
    MATL.MKT_CTGY_PROD_LINE_NBR || ' - ' || MATL.MKT_CTGY_PROD_LINE_NAME AS PROD_LINE,
    ODC.ITEM_CAT_ID,

    ODC.ORDER_DT,
    ODC.FRST_RDD AS FRDD,
    ODC.FRST_PROM_DELIV_DT AS FCDD,
    ODC.PLN_DELIV_DT AS PDD,

    ODC.ORDER_QTY AS ORDER_QTY,
    ODC.CNFRM_QTY AS TOTAL_CNFRM_QTY,

    OOSL.OPEN_CNFRM_QTY AS OPEN_CONFIRMED_QTY,
    OOSL.UNCNFRM_QTY AS UNCONFIRMED_QTY,
    OOSL.BACK_ORDER_QTY AS BACK_ORDERED_QTY,
    OOSL.DEFER_QTY AS DEFER_QTY,
    OOSL.IN_PROC_QTY AS IN_PROC_QTY,
    OOSL.WAIT_LIST_QTY AS WAIT_LIST_QTY,
    OOSL.OTHR_ORDER_QTY AS OTHR_ORDER_QTY,
    ODC.QTY_UNIT_MEAS_ID

FROM NA_VWS.OPEN_ORDER_SCHDLN OOSL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL_CURR ODC
        ON ODC.ORDER_FISCAL_YR = OOSL.ORDER_FISCAL_YR
        AND ODC.ORDER_ID = OOSL.ORDER_ID
        AND ODC.ORDER_LINE_NBR = OOSL.ORDER_LINE_NBR
        AND ODC.SCHED_LINE_NBR = OOSL.SCHED_LINE_NBR
        AND ODC.CUST_GRP_ID <> '3R'
        AND ODC.ORDER_TYPE_ID <> 'ZLZ'
        AND ODC.RO_PO_TYPE_IND = 'N' -- AND ODC.PO_TYPE_ID <> 'RO'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID
        AND CUST.CUST_GRP_ID <> '3R'

WHERE
    OOSL.EXP_DT = DATE '5555-12-31'
    AND FCDD > CURRENT_DATE
    AND ( OPEN_CONFIRMED_QTY > 0
    OR UNCONFIRMED_QTY > 0
    OR BACK_ORDERED_QTY > 0 )
) OOF

GROUP BY
    PBU,
    OOF.MKT_AREA,
    OOF.MKT_GRP,
    OOF.PROD_GRP,
    OOF.PROD_LINE,
    OOF.DELIV_PRTY_ID,
    OOF.CUST_GRP2_CD,
    OOF.EXT_MATL_GRP_ID,
    "Material Description",
    "Common Owner",
    "Lead Time (Weeks)",
    OOF.QTY_UNIT_MEAS_ID

ORDER BY
    PBU,
    OOF.MKT_AREA,
    OOF.MKT_GRP,
    OOF.PROD_GRP,
    OOF.PROD_LINE,
    "Common Owner",
    OOF.DELIV_PRTY_ID,
    OOF.CUST_GRP2_CD
;


-- ORDERS WITH PDD > FCDD @ ORDER LINE LEVEL
SELECT
    OOF.ORDER_ID AS "Order ID",
    OOF.ORDER_LINE_NBR AS "Order Line Nbr",
    OOF.SCHED_LINE_NBR AS "Schedule Line Nbr",

    OOF.CREDIT_HOLD_FLG AS "Credit Hold Flag",

    OOF.SHIP_TO_CUST_ID || ' - ' || OOF.SHIP_TO_CUST_NAME AS "Ship To Customer",
    OOF.OWN_CUST_ID || ' - ' || OOF.OWN_CUST_NAME AS "Common Owner",

    OOF.SALES_ORG_CD AS "Sales Organization Code",
    OOF.DISTR_CHAN_CD AS "Distribution Channel Code",
    OOF.CUST_GRP_ID AS "Customer Group ID", 
    OOF.PO_TYPE_ID AS "PO Type ID",
    OOF.ORDER_CAT_ID AS "Order Category ID",
    OOF.ORDER_TYPE_ID AS "Order Type ID",
    OOF.DELIV_BLK_CD AS "Delivery Block Code",
    OOF.FACILITY_ID AS "Facility ID",
    OOF.SHIP_PT_ID AS "Ship Point ID",
    OOF.DELIV_PRTY_ID AS "Delivery Priority ID",
    OOF.CUST_GRP2_CD AS "Customer Group 2 Code",
    
    OOF.MATL_NO_8 || ' - ' || OOF.DESCR AS "Material Description",
    OOF.PBU_NBR || ' - ' || OOF.PBU_NAME AS PBU,
    OOF.EXT_MATL_GRP_ID AS "External Material Group ID",
    OOF.MKT_AREA AS "Market Area",
    OOF.MKT_GRP AS "Market Group",
    OOF.PROD_GRP AS "Product Group",
    OOF.PROD_LINE AS "Product Line",
    OOF.ITEM_CAT_ID AS "Item Category ID",

    OOF.ORDER_DT AS "Order Date",
    OOF.FRDD,
    OOF.FCDD,
    CAST( CAST( OOF.FCDD - CURRENT_DATE AS FORMAT '-9(3)' ) || ' Days between ' || CURRENT_DATE ||  ' and FCDD' AS VARCHAR(40) )AS "Days between Today and FCDD",
    OOF.PDD AS "Planned Delivery Date",
    CAST( CAST( OOF.PDD - OOF.FCDD AS FORMAT '-9(3)' ) || ' Days between FCDD and PDD' AS VARCHAR(40) ) AS "Days between FCDD and PDD", 

    OOF.OPEN_CONFIRMED_QTY AS "Open Confirmed Qty",
    OOF.UNCONFIRMED_QTY AS "Unconfirmed Qty",
    OOF.BACK_ORDERED_QTY AS "Back Ordered Qty",
    OOF.QTY_UNIT_MEAS_ID AS  "Quantity UOM"
    
FROM (

SELECT
    OOSL.ORDER_ID,
    OOSL.ORDER_LINE_NBR,
    OOSL.SCHED_LINE_NBR,

    OOSL.CREDIT_HOLD_FLG,

    ODC.SHIP_TO_CUST_ID ,
    CUST.CUST_NAME AS SHIP_TO_CUST_NAME,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,

    ODC.SALES_ORG_CD,
    ODC.DISTR_CHAN_CD,
    ODC.CUST_GRP_ID,
    NULLIF( ODC.PO_TYPE_ID, ' ' ) AS PO_TYPE_ID,
    ODC.ORDER_CAT_ID,
    ODC.ORDER_TYPE_ID,
    CASE WHEN ODC.CANCEL_IND = 'Y' THEN 'Y' END AS CANCEL_IND,
    CASE WHEN ODC.RETURN_IND = 'Y' THEN 'Y' END AS RETURN_IND,
    NULLIF( ODC.DELIV_BLK_CD, ' ' ) AS DELIV_BLK_CD,
    ODC.FACILITY_ID,
    ODC.SHIP_PT_ID,
    ODC.DELIV_PRTY_ID,
    ODC.CUST_GRP2_CD,

    ODC.MATL_ID,
    MATL.MATL_NO_8,
    MATL.DESCR,
    MATL.PBU_NBR,
    MATL.PBU_NAME,
    MATL.EXT_MATL_GRP_ID,
    MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME AS MKT_AREA,
    MATL.MKT_CTGY_MKT_GRP_NBR || ' - ' || MATL.MKT_CTGY_MKT_GRP_NAME AS MKT_GRP,
    MATL.MKT_CTGY_PROD_GRP_NBR || ' - ' || MATL.MKT_CTGY_PROD_GRP_NAME AS PROD_GRP,
    MATL.MKT_CTGY_PROD_LINE_NBR || ' - ' || MATL.MKT_CTGY_PROD_LINE_NAME AS PROD_LINE,
    ODC.ITEM_CAT_ID,

    ODC.ORDER_DT,
    ODC.FRST_RDD AS FRDD,
    ODC.FRST_PROM_DELIV_DT AS FCDD,
    ODC.PLN_DELIV_DT AS PDD,

    ODC.ORDER_QTY AS ORDER_QTY,
    ODC.CNFRM_QTY AS TOTAL_CNFRM_QTY,

    OOSL.OPEN_CNFRM_QTY AS OPEN_CONFIRMED_QTY,
    OOSL.UNCNFRM_QTY AS UNCONFIRMED_QTY,
    OOSL.BACK_ORDER_QTY AS BACK_ORDERED_QTY,
    OOSL.DEFER_QTY AS DEFER_QTY,
    OOSL.IN_PROC_QTY AS IN_PROC_QTY,
    OOSL.WAIT_LIST_QTY AS WAIT_LIST_QTY,
    OOSL.OTHR_ORDER_QTY AS OTHR_ORDER_QTY,
    ODC.QTY_UNIT_MEAS_ID

FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOSL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL_CURR ODC
        ON ODC.ORDER_ID = OOSL.ORDER_ID
        AND ODC.ORDER_LINE_NBR = OOSL.ORDER_LINE_NBR
        AND ODC.SCHED_LINE_NBR = OOSL.SCHED_LINE_NBR
        AND ODC.CUST_GRP_ID <> '3R'
        AND ODC.ORDER_TYPE_ID <> 'ZLZ'
        AND ODC.RO_PO_TYPE_IND = 'N' -- AND ODC.PO_TYPE_ID <> 'RO'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID
        AND CUST.CUST_GRP_ID <> '3R'

WHERE
    FCDD > CURRENT_DATE
    AND ( OPEN_CONFIRMED_QTY > 0
    OR UNCONFIRMED_QTY > 0
    OR BACK_ORDERED_QTY > 0 )
    
) OOF

WHERE
    OOF.PDD > OOF.FCDD
    
ORDER BY
    OOF.ORDER_ID,
    OOF.ORDER_LINE_NBR
;
