SELECT
    OL.ORDER_ID,
    OL.ORDER_LINE_NBR,
    
    OL.OWN_CUST_ID,
    OL.OWN_CUST_NAME,
    
    OL.MATL_ID,
    OL.DESCR,
    OL.PBU_NBR || ' - ' || OL.PBU_NAME AS PBU,
    
    OL.ORDER_DT,
    OL.ORDD,
    ROW_NUMBER( ) OVER ( PARTITION BY PBU ORDER BY OL.ORDD DESC ) AS ORDD_RANK,
    OL.FRDD,
    ROW_NUMBER( ) OVER ( PARTITION BY PBU ORDER BY OL.FRDD DESC ) AS FRDD_RANK,
    OL.FCDD,
    ROW_NUMBER( ) OVER ( PARTITION BY PBU ORDER BY OL.FCDD DESC ) AS FCDD_RANK
    
FROM (
    SELECT
        ODC.ORDER_ID,
        ODC.ORDER_LINE_NBR,
        
        ODC.SHIP_TO_CUST_ID,
        CUST.CUST_NAME AS SHIP_TO_CUST_NAME,
        CUST.OWN_CUST_ID,
        CUST.OWN_CUST_NAME,
        ODC.MATL_ID,
        MATL.DESCR,
        MATL.PBU_NBR,
        MATL.PBU_NAME,
        
        ODC.ORDER_DT,
        ODC.CUST_RDD AS ORDD,
        ODC.FRST_RDD AS FRDD,
        ODC.FRST_PROM_DELIV_DT AS FCDD
        
    FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC
    
        INNER JOIN NA_BI_vWS.OPEN_ORDER_ORDLN_CURR OOL
            ON OOL.ORDER_ID = ODC.ORDER_ID
            AND OOL.ORDER_LINE_NBR = ODC.ORDER_LINE_NBR
            AND ( OOL.OPEN_CNFRM_QTY > 0 OR OOL.UNCNFRM_QTY > 0 OR OOL.BACK_ORDER_QTY > 0 )
        
        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID
        
        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
            ON MATL.MATL_ID = ODC.MATL_ID
            
    WHERE
        ODC.FRST_PROM_DELIV_DT IS NOT NULL
    
    GROUP BY
        ODC.ORDER_ID,
        ODC.ORDER_LINE_NBR,
        ODC.SHIP_TO_CUST_ID,
        CUST.CUST_NAME,
        CUST.OWN_CUST_ID,
        CUST.OWN_CUST_NAME,
        ODC.MATL_ID,
        MATL.DESCR,
        MATL.PBU_NBR,
        MATL.PBU_NAME,
        ODC.ORDER_DT,
        ODC.CUST_RDD,
        ODC.FRST_RDD,
        ODC.FRST_PROM_DELIV_DT
    ) OL

QUALIFY
    ORDD_RANK < 10
    OR FRDD_RANK < 10
    OR FCDD_RANK < 10