SELECT
    OOSL.ORDER_ID,
    OOSL.ORDER_LINE_NBR,
    OOSL.SCHED_LINE_NBR,

    OOSL.CREDIT_HOLD_FLG,

    ODC.SHIP_TO_CUST_ID ,
    CUST.CUST_NAME AS SHIP_TO_CUST_NAME,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,

    ODC.SALES_ORG_CD,
    ODC.DISTR_CHAN_CD,
    ODC.CUST_GRP_ID,
    NULLIF( ODC.PO_TYPE_ID, ' ' ) AS PO_TYPE_ID,
    ODC.ORDER_CAT_ID,
    ODC.ORDER_TYPE_ID,
    CASE WHEN ODC.CANCEL_IND = 'Y' THEN 'Y' END AS CANCEL_IND,
    CASE WHEN ODC.RETURN_IND = 'Y' THEN 'Y' END AS RETURN_IND,
    NULLIF( ODC.DELIV_BLK_CD, ' ' ) AS DELIV_BLK_CD,
    ODC.FACILITY_ID,
    ODC.SHIP_PT_ID,
    ODC.DELIV_PRTY_ID,
    ODC.CUST_GRP2_CD,

    ODC.MATL_ID,
    MATL.MATL_NO_8,
    MATL.DESCR,
    MATL.PBU_NBR,
    MATL.PBU_NAME,
    MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME AS MKT_AREA,
    MATL.MKT_CTGY_MKT_GRP_NBR || ' - ' || MATL.MKT_CTGY_MKT_GRP_NAME AS MKT_GRP,
    MATL.MKT_CTGY_PROD_GRP_NBR || ' - ' || MATL.MKT_CTGY_PROD_GRP_NAME AS PROD_GRP,
    MATL.MKT_CTGY_PROD_LINE_NBR || ' - ' || MATL.MKT_CTGY_PROD_LINE_NAME AS PROD_LINE,
    ODC.ITEM_CAT_ID,

    ODC.ORDER_DT,
    ODC.FRST_RDD AS FRDD,
    ODC.FRST_PROM_DELIV_DT AS FCDD,
    ODC.PLN_DELIV_DT AS PDD,

    ODC.ORDER_QTY AS ORDER_QTY,
    ODC.CNFRM_QTY AS TOTAL_CNFRM_QTY,

    OOSL.OPEN_CNFRM_QTY AS OPEN_CONFIRMED_QTY,
    OOSL.UNCNFRM_QTY AS UNCONFIRMED_QTY,
    OOSL.BACK_ORDER_QTY AS BACK_ORDERED_QTY,
    OOSL.DEFER_QTY AS DEFER_QTY,
    OOSL.IN_PROC_QTY AS IN_PROC_QTY,
    OOSL.WAIT_LIST_QTY AS WAIT_LIST_QTY,
    OOSL.OTHR_ORDER_QTY AS OTHR_ORDER_QTY,
    ODC.QTY_UNIT_MEAS_ID

FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOSL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL_CURR ODC
        ON ODC.ORDER_ID = OOSL.ORDER_ID
        AND ODC.ORDER_LINE_NBR = OOSL.ORDER_LINE_NBR
        AND ODC.SCHED_LINE_NBR = OOSL.SCHED_LINE_NBR
        AND ODC.CUST_GRP_ID <> '3R'
        AND ODC.ORDER_TYPE_ID <> 'ZLZ'
        AND ODC.RO_PO_TYPE_IND = 'N' -- AND ODC.PO_TYPE_ID <> 'RO'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID
        AND MATL.PBU_NBR IN ( '01', '03' )
        AND MATL.EXT_MATL_GRP_ID = 'TIRE'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID
        AND CUST.CUST_GRP_ID <> '3R'

WHERE
    FCDD > CURRENT_DATE
    AND ( OPEN_CONFIRMED_QTY > 0
    OR UNCONFIRMED_QTY > 0
    OR BACK_ORDERED_QTY > 0 )
;