SELECT
    OD.ORDER_ID,
    OD.ORDER_LINE_NBR,
    OD.SCHED_LINE_NBR,

    OD.EFF_DT,
    OD.EXP_DT,

    OD.MATL_ID,
    M.DESCR,
    M.PBU_NBR,
    M.PBU_NAME,
    M.EXT_MATL_GRP_ID,
    OD.ITEM_CAT_ID,
    NULLIF( OD.BATCH_NBR, ' ' ) AS BATCH_NBR,

    OD.SHIP_TO_CUST_ID,
    C.CUST_NAME AS SHIP_TO_CUST_NAME,
    C.OWN_CUST_ID,
    C.OWN_CUST_NAME,
    OD.SALES_ORG_CD,
    OD.DISTR_CHAN_CD,
    OD.CUST_GRP_ID,
    OD.CO_CD,
    OD.DIV_CD,

    OD.ORDER_CAT_ID,
    OD.ORDER_TYPE_ID,
    NULLIF( OD.PO_TYPE_ID , ' ' ) AS PO_TYPE_ID,
    NULLIF( OD.ORDER_CREATOR, ' ' ) AS ORDER_CREATOR,
    NULLIF( OD.REJ_REAS_ID, ' ' ) AS REJ_REAS_ID,
    NULLIF( OD.ORDER_REAS_CD, ' ' ) AS ORDER_REAS_CD,
    NULLIF( OD.PROD_ALLCT_DETERM_PROC_ID, ' ' ) AS PROD_ALLCT_DETERM_PROC_ID,

    OD.FACILITY_ID,
    OD.SHIP_PT_ID,
    NULLIF( OD.DELIV_BLK_CD, ' ' ) AS DELIV_BLK_CD,
    OD.DELIV_PRTY_ID,
    NULLIF( OD.ROUTE_ID, ' ' ) AS ROUTE_ID,
    OD.DELIV_GRP_CD,
    NULLIF( OD.SPCL_PROC_ID, ' ' ) AS SPCL_PROC_ID,
    NULLIF( OD.RPT_FRT_PLCY_CD, ' ' ) AS CUST_GRP2_CD,
    NULLIF( OD.SHIP_COND_ID, ' ' ) AS SHIP_COND_ID,

    CASE WHEN OD.CANCEL_IND = 'Y' THEN 'Y' END AS CANCEL_IND,
    CASE WHEN OD.RETURN_IND = 'Y' THEN 'Y' END AS RETURN_IND,
    CASE WHEN OD.RO_PO_TYPE_IND = 'Y' THEN 'Y' END AS RO_PO_TYPE_IND,
    CASE WHEN OD.DELIV_BLK_IND = 'Y' THEN 'Y' END AS DELIV_BLK_IND,
    NULLIF( OD.PRTL_DLVY_CD, ' ' ) AS PRTL_DLVY_CD,
    NULLIF( OD.HANDSHAKE_TYP_CD, ' ' ) AS HANDSHAKE_TYP_CD,

    OD.ORDER_DT,
    CASE WHEN OD.CUST_RDD < OD.ORDER_DT THEN OD.ORDER_DT ELSE OD.CUST_RDD END AS CUST_RDD,
    OD.FRST_RDD,
    OD.FRST_MATL_AVL_DT AS FRDD_FMAD,
    OD.FRST_PLN_GOODS_ISS_DT AS FRDD_FPGI,

    CASE WHEN OD.FRST_PROM_DELIV_DT < OD.FRST_RDD THEN OD.FRST_RDD ELSE OD.FRST_PROM_DELIV_DT END AS FRST_CDD,
    FRST_CDD - ( CAST( OD.FRST_RDD - FRDD_FMAD AS INTEGER ) ) AS FCDD_FMAD,
    FRST_CDD - ( CAST( OD.FRST_RDD - FRDD_FPGI AS INTEGER ) ) AS FCDD_FPGI,

    OD.PLN_TRANSP_PLN_DT,
    OD.PLN_MATL_AVL_DT,
    OD.PLN_TRANSP_PLN_DT,
    OD.PLN_MATL_AVL_DT,
    OD.PLN_LOAD_DT,
    OD.PLN_DELIV_DT,
    OD.FNL_ACCEPT_DT,

    CAST( CASE
        WHEN OD.PLN_DELIV_DT > OD.FRST_RDD
            THEN 'PDD > FRDD'
        WHEN OD.PLN_DELIV_DT = OD.FRST_RDD
            THEN 'PDD = FRDD'
        WHEN OD.PLN_DELIV_DT < OD.FRST_RDD
            THEN 'PDD < FRDD'
    END AS CHAR(10) ) AS PDD_VS_FRDD_TEST,
    CAST( CASE
        WHEN OD.PLN_DELIV_DT > FRST_CDD
            THEN 'PDD > FCDD'
        WHEN OD.PLN_DELIV_DT = FRST_CDD
            THEN 'PDD = FCDD'
        WHEN OD.PLN_DELIV_DT < FRST_CDD
            THEN 'PDD < FCDD'
    END AS CHAR(10) ) AS PDD_VS_FCDD_TEST,


    OD.QTY_UNIT_MEAS_ID,
    OD.ORDER_QTY,
    OD.CNFRM_QTY,

    OD.WT_UNITS_MEAS_ID,
    OD.NET_WT,
    OD.GROSS_WT,
    OD.VOL_UNIT_MEAS_ID,
    OD.VOL

FROM NA_BI_VWS.ORDER_DETAIL OD

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID
        AND C.CUST_GRP_ID <> '3R'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID

WHERE
    --OD.EXP_DT = CAST( '5555-12-31' AS DATE )
    OD.CUST_GRP_ID <> '3R'
    AND OD.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
    AND OD.RO_PO_TYPE_IND = 'N'
    -- AND OD.ORDER_LINE_NBR = 20

ORDER BY
    OD.ORDER_ID,
    OD.ORDER_LINE_NBR,
    OD.SCHED_LINE_NBR,
    CAL.DAY_DATE
