SELECT 
    OD.ORDER_ID,
    OD.ORDER_LINE_NBR,
    OD.SCHED_LINE_NBR,
    OD.EFF_DT,
    OD.EXP_DT,
    OD.CO_CD,
    OD.DIV_CD,
    OD.SALES_ORG_CD,
    OD.DISTR_CHAN_CD,
    OD.CUST_GRP_ID,
    OD.SHIP_TO_CUST_ID,
    OD.ORDER_DT,
    OD.ORDER_CAT_ID,
    OD.ORDER_TYPE_ID,
    OD.SCHD_LN_CTGY_CD,
    OD.CANCEL_IND,
    OD.RETURN_IND,
    OD.PO_TYPE_ID,
    OD.RO_PO_TYPE_IND,
    OD.DELIV_BLK_IND,
    OD.DELIV_BLK_CD,
    OD.FACILITY_ID,
    OD.SHIP_PT_ID,
    OD.ITEM_CAT_ID,
    OD.MATL_ID,
    OD.QTY_UNIT_MEAS_ID,
    OD.ORDER_QTY,
    OD.CNFRM_QTY,
    OD.NET_WT,
    OD.GROSS_WT,
    OD.WT_UNITS_MEAS_ID,
    OD.VOL,
    OD.VOL_UNIT_MEAS_ID,
    OD.ORDER_CREATOR,
    OD.SHIP_COND_ID,
    OD.REJ_REAS_ID,
    OD.DELIV_PRTY_ID,
    OD.CUST_RDD,
    OD.FRST_RDD,
    OD.FRST_MATL_AVL_DT,
    OD.FRST_PLN_GOODS_ISS_DT,
    OD.FRST_PROM_DELIV_DT,
    OD.PLN_TRANSP_PLN_DT,
    OD.PLN_MATL_AVL_DT,
    OD.PLN_LOAD_DT,
    OD.PLN_GOODS_ISS_DT,
    OD.PLN_DELIV_DT,
    OD.ROUTE_ID,
    OD.DELIV_GRP_CD,
    OD.SPCL_PROC_ID,
    OD.RPT_FRT_PLCY_CD

FROM NA_BI_VWS.ORDER_DETAIL OD

WHERE
    (
        OD.EXP_DT >= CAST( ( EXTRACT(YEAR FROM CURRENT_DATE ) - 1 ) || '-01-01' AS DATE )
        OR ( CAST( ( EXTRACT(YEAR FROM CURRENT_DATE ) - 1 ) || '-01-01' AS DATE ) BETWEEN OD.EFF_DT AND OD.EXP_DT )
    )
    AND OD.ORDER_CAT_ID = 'C'
    AND OD.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
    AND OD.PO_TYPE_ID NOT IN ( 'RO' )
