SELECT
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    ODC.SCHED_LINE_NBR,
    ODC.CO_CD,
    ODC.DIV_CD,
    ODC.SALES_ORG_CD,
    ODC.DISTR_CHAN_CD,
    ODC.CUST_GRP_ID,
    ODC.SHIP_TO_CUST_ID,
    ODC.ORDER_DT,
    ODC.ORDER_CAT_ID,
    ODC.ORDER_TYPE_ID,
    ODC.RETURN_IND,
    ODC.PO_TYPE_ID,
    ODC.DELIV_BLK_CD,
    ODC.FACILITY_ID,
    ODC.SHIP_PT_ID,
    ODC.ITEM_CAT_ID,
    ODC.MATL_ID,
    ODC.QTY_UNIT_MEAS_ID,
    ODC.ORDER_QTY,
    ODC.CNFRM_QTY,
    ODC.NET_WT,
    ODC.GROSS_WT,
    ODC.WT_UNITS_MEAS_ID,
    ODC.VOL,
    ODC.VOL_UNIT_MEAS_ID,
    ODC.SHIP_COND_ID,
    ODC.REJ_REAS_ID,
    ODC.REJ_REAS_DESC,
    ODC.DELIV_PRTY_ID,
    ODC.CUST_RDD,
    ODC.FRST_RDD,
    ODC.FRST_MATL_AVL_DT,
    ODC.FRST_PLN_GOODS_ISS_DT,
    ODC.FRST_PROM_DELIV_DT,
    ODC.PLN_MATL_AVL_DT,
    ODC.PLN_GOODS_ISS_DT,
    ODC.PLN_DELIV_DT,
    ODC.ROUTE_ID,
    ODC.DELIV_GRP_CD,
    ODC.SPCL_PROC_ID,
    ODC.CUST_GRP2_CD,
    ODC.FC_MATL_AVL_DT,
    ODC.FC_PLN_GOODS_ISS_DT,
    ODC.CANCEL_DT

FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC

/*    INNER JOIN NA_BI_VWS.OPEN_ORDER_ORDLN_CURR OOL
        ON OOL.ORDER_ID = ODC.ORDER_ID
        AND OOL.ORDER_LINE_NBR = ODC.ORDER_LINE_NBR
        AND ( OOL.OPEN_CNFRM_QTY > 0 OR OOL.UNCNFRM_QTY > 0 OR OOL.BACK_ORDER_QTY > 0 ) -- ONLY ORDERS WHICH HAVE NOT SHIPPED */

WHERE
    ODC.ORDER_CAT_ID = 'C'
    AND ODC.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
    AND ODC.PO_TYPE_ID <> 'RO'
