SELECT
    --POL.ORDER_ID,
    --POL.ORDER_LINE_NBR,
    SUBSTR( CAST( POL.CMPL_DT AS CHAR(10) ), 1, 7 ) AS "FRDD Complete Month",
    POL.PBU_NBR AS "PBU Nbr",
    --POL.SHIP_FACILITY_ID,
    --CUST.OWN_CUST_ID,
    --CUST.OWN_CUST_NAME,
    POL.PRFCT_ORD_HIT_DESC AS "FRDD Hit Description",
    SUM( ODS.OL_CNT ) AS "Order Line Count",
    --SUM( POL.IF_HIT_NS_QTY ) AS "FRDD No Stock Hit Qty",
    --SUM( POL.IF_HIT_NS_QTY * ODS.OL_CNT ) AS "FRDD No Stock Hit Qty MAX",
    SUM( POL.PRFCT_ORD_HIT_QTY )  AS "FRDD Hit Total Qty",
    SUM( POL.PRFCT_ORD_HIT_QTY * ODS.OL_CNT ) AS "FRDD Hit Total Qty MAX",
    SUM( POL.PRFCT_ORD_QTY ) AS "FRDD On Time Qty",
    SUM( POL.PRFCT_ORD_QTY * ODS.OL_CNT ) AS "FRDD On Time Qty MAX",
    MATL.EXT_MATL_GRP_ID AS "External Material Group ID"
    
FROM  NA_BI_VWS.PRFCT_ORD_LINE POL

/*    INNER JOIN NA_BI_VWS.PRFCT_ORD_LINE POL
        ON ORD.ORDER_ID = POL.ORDER_ID
        AND ORD.ORDER_LINE_NBR = POL.ORDER_LINE_NBR
        AND ORD.ORDER_DT >= DATE '2013-01-01'*/

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = POL.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID

    INNER JOIN (
        SELECT
            O.ORDER_ID,
            O.ORDER_LINE_NBR,
            COUNT( * ) AS OL_CNT
        FROM NA_BI_VWS.ORD_DTL_SMRY O
        WHERE
            O.ORDER_DT >= DATE '2013-01-01'
        GROUP BY
            O.ORDER_ID,
            O.ORDER_LINE_NBR
        ) ODS
    ON ODS.ORDER_ID = POL.ORDER_ID
    AND ODS.ORDER_LINE_NBR = POL.ORDER_LINE_NBR

GROUP BY
    POL.PRFCT_ORD_HIT_DESC,
    MATL.EXT_MATL_GRP_ID,
    POL.PBU_NBR,
    --CUST.OWN_CUST_ID,
    --CUST.OWN_CUST_NAME,
    --POL.SHIP_FACILITY_ID,
    "FRDD Complete Month"

ORDER BY
    "FRDD Complete Month",
    POL.PRFCT_ORD_HIT_DESC