

SELECT
    OTD.METRIC_TYPE
    , OTD.COMPLETE_MTH
    , CASE
        WHEN DD.OWN_CUST_RNK > 15
            THEN 'Other'
        ELSE DD.OWN_CUST_ID
        END AS COMMON_OWNER_ID
    , CASE
        WHEN DD.OWN_CUST_RNK > 15 AND DD.EXPORT_IND = 'X'
            THEN 'Export'
        WHEN DD.OWN_CUST_RNK > 15 AND DD.EXPORT_IND <> 'X'
            THEN 'Other'
        ELSE DD.OWN_CUST_NAME
        END AS COMMON_OWNER_NAME
    , DD.TIRE_CUST_TYP_CD
    , CASE DD.EXPORT_IND
        WHEN 'D' THEN 'Domestic'
        WHEN 'X' THEN 'Export'
        END AS DOMESTIC_EXPORT_IND
    , DD.PBU_NBR
    , DD.PBU_NAME
    , SUM(DD.CO_DELIV_QTY) AS CO_DELIV_QTY
    , MAX(DD.MTH_DELIV_QTY) AS MTH_DELIV_QTY
    , CASE
        WHEN DD.OWN_CUST_RNK > 15 AND DD.EXPORT_IND = 'D'
            THEN 17
        WHEN DD.OWN_CUST_RNK > 15 AND DD.EXPORT_IND = 'X'
            THEN 16
        ELSE DD.OWN_CUST_RNK
        END AS SHIPMENT_RNK

    , SUM(ZEROIFNULL(OTD.ORDER_QTY)) AS ORDER_QTY
    , SUM(ZEROIFNULL(OTD.HIT_QTY)) AS HIT_QTY
    , SUM(ZEROIFNULL(OTD.ONTIME_QTY)) AS ONTIME_QTY

    , SUM(ZEROIFNULL(OTD.SUPPLY_HIT_QTY)) AS SUPPLY_HIT_QTY
    , SUM(ZEROIFNULL(OTD.POLICY_HIT_QTY)) AS POLICY_HIT_QTY
    , SUM(ZEROIFNULL(OTD.TOT_OTHER_HIT_QTY)) AS TOT_OTHER_HIT_QTY

    , SUM(ZEROIFNULL(OTD.RETURN_HIT_QTY)) AS RETURN_HIT_QTY
    , SUM(ZEROIFNULL(OTD.CLAIM_HIT_QTY)) AS CLAIM_HIT_QTY
    , SUM(ZEROIFNULL(OTD.FREIGHT_POLICY_HIT_QTY)) AS FREIGHT_POLICY_HIT_QTY
    , SUM(ZEROIFNULL(OTD.PHYS_LOG_HIT_QTY)) AS PHYS_LOG_HIT_QTY
    , SUM(ZEROIFNULL(OTD.MAN_BLK_HIT_QTY)) AS MAN_BLK_HIT_QTY
    , SUM(ZEROIFNULL(OTD.CREDIT_HOLD_HIT_QTY)) AS CREDIT_HOLD_HIT_QTY
    , SUM(ZEROIFNULL(OTD.NO_STOCK_HIT_QTY)) AS NO_STOCK_HIT_QTY
    , SUM(ZEROIFNULL(OTD.CANCEL_HIT_QTY)) AS CANCEL_HIT_QTY
    , SUM(ZEROIFNULL(OTD.CUST_GEN_HIT_QTY)) AS CUST_GEN_HIT_QTY
    , SUM(ZEROIFNULL(OTD.MAN_REL_CUST_GEN_HIT_QTY)) AS MAN_REL_CUST_GEN_HIT_QTY
    , SUM(ZEROIFNULL(OTD.MAN_REL_HIT_QTY)) AS MAN_REL_HIT_QTY
    , SUM(ZEROIFNULL(OTD.OTHER_HIT_QTY)) AS OTHER_HIT_QTY

FROM (

    SELECT
        D.OWN_CUST_ID
        , D.OWN_CUST_NAME
        , D.TIRE_CUST_TYP_CD
        , D.EXPORT_IND
        , D.PBU_NBR
        , D.PBU_NAME
        , D.MONTH_DT
        , D.NEXT_MONTH_DT
        , D.CO_DELIV_QTY
        , SUM(D.CO_DELIV_QTY) OVER (PARTITION BY D.TIRE_CUST_TYP_CD, D.PBU_NBR, D.MONTH_DT) AS MTH_DELIV_QTY
        , ROW_NUMBER() OVER (PARTITION BY D.MONTH_DT, D.PBU_NBR, D.TIRE_CUST_TYP_CD ORDER BY D.CO_DELIV_QTY DESC) AS OWN_CUST_RNK

    FROM (

        SELECT
            CUST.OWN_CUST_ID
            , CUST.OWN_CUST_NAME
            , CUST.TIRE_CUST_TYP_CD
            , CASE WHEN CUST.SALES_ORG_CD IN ('N303', 'N313', 'N323') THEN 'X' ELSE 'D' END AS EXPORT_IND
            , MATL.PBU_NBR
            , MATL.PBU_NAME
            , CAL.MONTH_DT
            , ADD_MONTHS(CAL.MONTH_DT, 1) AS NEXT_MONTH_DT
            , SUM(DDC.DELIV_QTY) AS CO_DELIV_QTY

        FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

            INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
                ON CAL.DAY_DATE = DDC.ACTL_GOODS_ISS_DT

            INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
                ON MATL.MATL_ID = DDC.MATL_ID
                AND MATL.PBU_NBR IN ('01', '03')
                AND MATL.EXT_MATL_GRP_ID = 'TIRE'

            INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FAC
                ON FAC.FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID
                AND FAC.SALES_ORG_CD IN ('N306', 'N316', 'N326')
                AND FAC.DISTR_CHAN_CD = '81'

            INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
                ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID
                AND CUST.CUST_GRP_ID <> '3R'

        WHERE
            DDC.GOODS_ISS_IND = 'Y'
            AND DDC.ACTL_GOODS_ISS_DT IS NOT NULL
            AND DDC.ACTL_GOODS_ISS_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-12-01' AS DATE) AND CURRENT_DATE-1
            AND DDC.DELIV_CAT_ID = 'J'
            AND DDC.DELIV_QTY > 0
            AND DDC.SALES_ORG_CD NOT IN ('N306', 'N316', 'N326')
            AND DDC.DISTR_CHAN_CD <> '81'

        GROUP BY
            CUST.OWN_CUST_ID
            , CUST.OWN_CUST_NAME
            , CUST.TIRE_CUST_TYP_CD
            , EXPORT_IND
            , MATL.PBU_NBR
            , MATL.PBU_NAME
            , CAL.MONTH_DT
            , NEXT_MONTH_DT

        ) D

    ) DD

    LEFT OUTER JOIN (
            SELECT
                CAST('FRDD' AS CHAR(4)) AS METRIC_TYPE
                , POL.CMPL_DT - (EXTRACT(DAY FROM POL.CMPL_DT) - 1) AS COMPLETE_MTH

                , CUST.OWN_CUST_ID
                , CUST.TIRE_CUST_TYP_CD
                , CAST(CASE WHEN CUST.SALES_ORG_CD IN ('N303', 'N313', 'N323') THEN 'X' ELSE 'D' END AS CHAR(1)) AS EXPORT_IND
                , MATL.PBU_NBR

                , SUM(ZEROIFNULL(POL.ORIG_ORD_QTY)) AS ORIG_ORDER_QTY
                , SUM(ZEROIFNULL(POL.CANCEL_QTY)) AS CANCEL_QTY
                , SUM(ZEROIFNULL(POL.CURR_ORD_QTY)) AS ORDER_QTY
                , SUM(ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY)) AS HIT_QTY
                , SUM(ZEROIFNULL(POL.CURR_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY)) AS ONTIME_QTY
                , SUM(ZEROIFNULL(POL.REL_LATE_QTY)) AS REL_LATE_QTY
                , SUM(ZEROIFNULL(POL.REL_ONTIME_QTY)) AS REL_ONTIME_QTY
                , SUM(ZEROIFNULL(POL.COMMIT_ONTIME_QTY)) AS COMMIT_ONTIME_QTY
                , SUM(ZEROIFNULL(POL.DELIV_LATE_QTY)) AS DELIV_LATE_QTY
                , SUM(ZEROIFNULL(POL.DELIV_ONTIME_QTY)) AS DELIV_ONTIME_QTY
                , SUM(ZEROIFNULL(POL.NE_HIT_RT_QTY)) AS RETURN_HIT_QTY
                , SUM(ZEROIFNULL(POL.NE_HIT_CL_QTY)) AS CLAIM_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_HIT_FP_QTY)) AS FREIGHT_POLICY_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_HIT_CARR_PICKUP_QTY) + ZEROIFNULL(POL.OT_HIT_WI_QTY)) AS PHYS_LOG_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_HIT_MB_QTY)) AS MAN_BLK_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_HIT_CH_QTY)) AS CREDIT_HOLD_HIT_QTY
                , SUM(ZEROIFNULL(POL.IF_HIT_NS_QTY)) AS NO_STOCK_HIT_QTY
                , SUM(ZEROIFNULL(POL.IF_HIT_CO_QTY)) AS CANCEL_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_HIT_CG_QTY)) AS CUST_GEN_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_HIT_CG_99_QTY)) AS MAN_REL_CUST_GEN_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_HIT_99_QTY)) AS MAN_REL_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_HIT_LO_QTY)) AS OTHER_HIT_QTY

                , NO_STOCK_HIT_QTY + CANCEL_HIT_QTY AS SUPPLY_HIT_QTY
                , CREDIT_HOLD_HIT_QTY + FREIGHT_POLICY_HIT_QTY + MAN_BLK_HIT_QTY AS POLICY_HIT_QTY
                , RETURN_HIT_QTY + CLAIM_HIT_QTY + CUST_GEN_HIT_QTY + MAN_REL_CUST_GEN_HIT_QTY + MAN_REL_HIT_QTY + OTHER_HIT_QTY AS TOT_OTHER_HIT_QTY

            FROM NA_BI_VWS.PRFCT_ORD_LINE POL

                INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
                    ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID

                INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
                    ON MATL.MATL_ID = POL.MATL_ID
                    AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
                    AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')

                INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FAC
                    ON FAC.FACILITY_ID = POL.SHIP_FACILITY_ID
                    AND FAC.SALES_ORG_CD IN ('N306', 'N316', 'N326')
                    AND FAC.DISTR_CHAN_CD = '81'

                INNER JOIN NA_BI_VWS.ORDER_DETAIL ODS
                    ON ODS.ORDER_FISCAL_YR >= CAST(EXTRACT(YEAR FROM (CURRENT_DATE - 1)) - 2 AS CHAR(4))
                    AND ODS.ORDER_ID = POL.ORDER_ID
                    AND ODS.ORDER_LINE_NBR = POL.ORDER_LINE_NBR
                    AND ODS.SCHED_LINE_NBR = 1
                    AND ODS.EXP_DT = DATE '5555-12-31'
                    AND ODS.ORDER_CAT_ID = 'C'
                    AND ODS.RO_PO_TYPE_IND = 'N'

            WHERE
                POL.CMPL_IND = 1
                AND POL.CMPL_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1) || '-01-01' AS DATE) AND CURRENT_DATE-1
                AND POL.PRFCT_ORD_HIT_SORT_KEY <> 99

            GROUP BY
                METRIC_TYPE
                , COMPLETE_MTH

                , CUST.OWN_CUST_ID
                , CUST.TIRE_CUST_TYP_CD
                , EXPORT_IND
                , MATL.PBU_NBR

            UNION ALL

            SELECT
                CAST('FCDD' AS CHAR(4)) AS METRIC_TYPE
                , POL.FPDD_CMPL_DT - (EXTRACT(DAY FROM POL.FPDD_CMPL_DT) - 1) AS COMPLETE_MTH

                , CUST.OWN_CUST_ID
                , CUST.TIRE_CUST_TYP_CD
                , CAST(CASE WHEN CUST.SALES_ORG_CD IN ('N303', 'N313', 'N323') THEN 'X' ELSE 'D' END AS CHAR(1)) AS EXPORT_IND
                , MATL.PBU_NBR

                , SUM(ZEROIFNULL(POL.ORIG_ORD_QTY)) AS ORIG_ORDER_QTY
                , SUM(ZEROIFNULL(POL.CANCEL_QTY)) AS CANCEL_QTY
                , SUM(ZEROIFNULL(POL.FPDD_ORD_QTY)) AS ORDER_QTY
                , SUM(ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY)) AS HIT_QTY
                , SUM(ZEROIFNULL(POL.FPDD_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY)) AS ONTIME_QTY
                , SUM(ZEROIFNULL(POL.DELIV_FPDD_LATE_QTY)) AS DELIV_LATE_QTY
                , SUM(ZEROIFNULL(POL.DELIV_FPDD_ONTIME_QTY)) AS DELIV_ONTIME_QTY
                , SUM(ZEROIFNULL(POL.FPDD_COMMIT_ONTIME_QTY)) AS COMMIT_ONTIME_QTY
                , SUM(ZEROIFNULL(POL.REL_FPDD_LATE_QTY)) AS REL_LATE_QTY
                , SUM(ZEROIFNULL(POL.REL_FPDD_ONTIME_QTY)) AS REL_ONTIME_QTY
                , SUM(ZEROIFNULL(POL.NE_FPDD_HIT_RT_QTY)) AS RETURN_HIT_QTY
                , SUM(ZEROIFNULL(POL.NE_FPDD_HIT_CL_QTY)) AS CLAIM_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_FP_QTY)) AS FREIGHT_POLICY_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CARR_QTY) + ZEROIFNULL(POL.OT_FPDD_HIT_WI_QTY)) AS PHYS_LOG_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_MB_QTY)) AS MAN_BLK_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CH_QTY)) AS CREDIT_HOLD_HIT_QTY
                , SUM(ZEROIFNULL(POL.IF_FPDD_HIT_NS_QTY)) AS NO_STOCK_HIT_QTY
                , SUM(ZEROIFNULL(POL.IF_FPDD_HIT_CO_QTY)) AS CANCEL_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CG_QTY)) AS CUST_GEN_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CG_99_QTY)) AS MAN_REL_CUST_GEN_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_99_QTY)) AS MAN_REL_HIT_QTY
                , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_LO_QTY)) AS OTHER_HIT_QTY

                , NO_STOCK_HIT_QTY + CANCEL_HIT_QTY AS SUPPLY_HIT_QTY
                , CREDIT_HOLD_HIT_QTY + FREIGHT_POLICY_HIT_QTY + MAN_BLK_HIT_QTY AS POLICY_HIT_QTY
                , RETURN_HIT_QTY + CLAIM_HIT_QTY + CUST_GEN_HIT_QTY + MAN_REL_CUST_GEN_HIT_QTY + MAN_REL_HIT_QTY + OTHER_HIT_QTY AS TOT_OTHER_HIT_QTY

            FROM NA_BI_VWS.PRFCT_ORD_LINE POL

                INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
                    ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID

                INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
                    ON MATL.MATL_ID = POL.MATL_ID
                    AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
                    AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')

                INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FAC
                    ON FAC.FACILITY_ID = POL.SHIP_FACILITY_ID
                    AND FAC.SALES_ORG_CD IN ('N306', 'N316', 'N326')
                    AND FAC.DISTR_CHAN_CD = '81'

                INNER JOIN NA_BI_VWS.ORDER_DETAIL ODS
                    ON ODS.ORDER_FISCAL_YR >= CAST(EXTRACT(YEAR FROM (CURRENT_DATE - 1)) - 2 AS CHAR(4))
                    AND ODS.ORDER_ID = POL.ORDER_ID
                    AND ODS.ORDER_LINE_NBR = POL.ORDER_LINE_NBR
                    AND ODS.SCHED_LINE_NBR = 1
                    AND ODS.EXP_DT = DATE '5555-12-31'
                    AND ODS.ORDER_CAT_ID = 'C'
                    AND ODS.RO_PO_TYPE_IND = 'N'

            WHERE
                POL.FPDD_CMPL_IND = 1
                AND POL.FRST_PROM_DELIV_DT IS NOT NULL
                AND POL.FPDD_CMPL_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1) || '-01-01' AS DATE) AND CURRENT_DATE-1
                AND POL.PRFCT_ORD_FPDD_HIT_SORT_KEY <> 99

            GROUP BY
                METRIC_TYPE
                , COMPLETE_MTH

                , CUST.OWN_CUST_ID
                , CUST.TIRE_CUST_TYP_CD
                , EXPORT_IND
                , MATL.PBU_NBR
            ) OTD
        ON OTD.COMPLETE_MTH = DD.NEXT_MONTH_DT
        AND OTD.OWN_CUST_ID = DD.OWN_CUST_ID
        AND OTD.TIRE_CUST_TYP_CD = DD.TIRE_CUST_TYP_CD
        AND OTD.EXPORT_IND = DD.EXPORT_IND
        AND OTD.PBU_NBR = DD.PBU_NBR

GROUP BY
    OTD.METRIC_TYPE
    , OTD.COMPLETE_MTH
    , COMMON_OWNER_ID
    , COMMON_OWNER_NAME
    , DD.TIRE_CUST_TYP_CD
    , DD.EXPORT_IND
    , DD.PBU_NBR
    , DD.PBU_NAME
    , SHIPMENT_RNK

ORDER BY
    OTD.COMPLETE_MTH DESC
    , OTD.METRIC_TYPE
    , DD.PBU_NBR
    , DD.TIRE_CUST_TYP_CD
    , SHIPMENT_RNK
    , DOMESTIC_EXPORT_IND
