SELECT
    OTD.METRIC_TYPE
    , OTD.COMPLETE_MTH
    , OTD.QUARTER
    , OTD.MONTH_NAME
    , OTD.PBU_NBR
    , OTD.PBU
    , OTD.CATEGORY
    , OTD.CATEGORY_NAME
    , OTD.TIER
    , OTD.CATEGORY_TIER
    , OTD.EXT_MATL_GRP_ID
    , NULL AS OWN_CUST_ID
    , NULL AS OWN_CUST_NAME
    , OTD.TIRE_CUST_TYP_CD
    , OTD.TARGET_NUMERATOR
    , OTD.AOP_NUMERATOR
    , OTD.TARGET_DENOMINATOR
    , OTD.ORDER_QTY
    , OTD.HIT_QTY
    , OTD.ONTIME_QTY
    , OTD.SUPPLY_HIT_QTY
    , OTD.POLICY_HIT_QTY
    , OTD.TOT_OTHER_HIT_QTY
    , OTD.RETURN_HIT_QTY
    , OTD.CLAIM_HIT_QTY
    , OTD.FREIGHT_POLICY_HIT_QTY
    , OTD.PHYS_LOG_HIT_QTY
    , OTD.MAN_BLK_HIT_QTY
    , OTD.CREDIT_HOLD_HIT_QTY
    , OTD.NO_STOCK_HIT_QTY
    , OTD.CANCEL_HIT_QTY
    , OTD.CUST_GEN_HIT_QTY
    , OTD.MAN_REL_CUST_GEN_HIT_QTY
    , OTD.MAN_REL_HIT_QTY
    , OTD.OTHER_HIT_QTY
    , NULL AS OWN_CUST_RNK
    , SUM(OTD.ORDER_QTY) OVER (PARTITION BY OTD.METRIC_TYPE, OTD.COMPLETE_MTH, OTD.PBU_NBR, OTD.EXT_MATL_GRP_ID, OTD.TIRE_CUST_TYP_CD, OTD.EXPORT_IND) AS MTH_PBU_ORDER_QTY
    , NULL AS CO_DELIV_QTY
    , NULL AS MTH_DELIV_QTY
    , OTD.MATL_PRTY
    , OTD.MATL_PRTY_DESCR
    , CASE
        WHEN OTD.EXPORT_IND = 'D' THEN 'Domestic'
        WHEN OTD.EXPORT_IND = 'X' THEN 'Export'
        END AS DOMESTIC_EXPORT_IND

FROM (

    SELECT
        CAST('FRDD' AS CHAR(4)) AS METRIC_TYPE
        , POL.CMPL_DT - (EXTRACT(DAY FROM POL.CMPL_DT) - 1) AS COMPLETE_MTH
        , CAL.QUARTER
        , CAST(CAL.MONTH_DT AS FORMAT 'Mmm') (CHAR(3)) AS MONTH_NAME
        , MATL.PBU_NBR
        , MATL.PBU_NBR || ' - ' || MATL.PBU_NAME AS PBU
        , CASE
            WHEN MATL.PBU_NBR = '01'
                THEN MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME
            ELSE MATL.MKT_CTGY_MKT_GRP_NBR || ' - ' || MATL.MKT_CTGY_MKT_GRP_NAME
          END  AS CATEGORY
        , CASE
            WHEN MATL.PBU_NBR = '01'
                THEN MATL.MKT_CTGY_MKT_AREA_NAME
            ELSE MATL.MKT_CTGY_MKT_GRP_NAME
            END AS CATEGORY_NAME
        , CASE
            WHEN MATL.PBU_NBR = '01'
                THEN MATL.MKT_CTGY_PROD_GRP_NAME
            ELSE MATL.TIERS
            END AS TIER
        , CATEGORY_NAME || ' (' || TIER || ')' AS CATEGORY_TIER
        , MATL.EXT_MATL_GRP_ID
        , MATL.MATL_PRTY_CTGY
        , MATL.MATL_PRTY
        , MATL.MATL_PRTY_DESCR
        , CUST.TIRE_CUST_TYP_CD
        , CAST(CASE
            WHEN CUST.SALES_ORG_CD IN ('N303', 'N313', 'N323') THEN 'X'
            ELSE 'D'
            END AS CHAR(1)) AS EXPORT_IND

        , SUM(ZEROIFNULL(POL.CURR_ORD_QTY)) AS ORDER_QTY
        , SUM(ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY)) AS HIT_QTY
        , SUM(ZEROIFNULL(POL.CURR_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY)) AS ONTIME_QTY

        , SUM(ZEROIFNULL(POL.NE_HIT_RT_QTY)) AS RETURN_HIT_QTY
        , SUM(ZEROIFNULL(POL.NE_HIT_CL_QTY)) AS CLAIM_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_FP_QTY)) AS FREIGHT_POLICY_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_CARR_PICKUP_QTY) + ZEROIFNULL(POL.OT_HIT_WI_QTY)) AS PHYS_LOG_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_MB_QTY)) AS MAN_BLK_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_CH_QTY)) AS CREDIT_HOLD_HIT_QTY
        , SUM(ZEROIFNULL(POL.IF_HIT_NS_QTY)) AS NO_STOCK_HIT_QTY
        , SUM(ZEROIFNULL(POL.IF_HIT_CO_QTY)) AS CANCEL_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_CG_QTY)) AS CUST_GEN_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_CG_99_QTY)) AS MAN_REL_CUST_GEN_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_99_QTY)) AS MAN_REL_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_LO_QTY)) AS OTHER_HIT_QTY

        , NO_STOCK_HIT_QTY + CANCEL_HIT_QTY AS SUPPLY_HIT_QTY
        , CREDIT_HOLD_HIT_QTY + FREIGHT_POLICY_HIT_QTY + MAN_BLK_HIT_QTY AS POLICY_HIT_QTY
        , RETURN_HIT_QTY + CLAIM_HIT_QTY + CUST_GEN_HIT_QTY + MAN_REL_CUST_GEN_HIT_QTY + MAN_REL_HIT_QTY + OTHER_HIT_QTY AS TOT_OTHER_HIT_QTY

        , CAST(CASE
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q1' THEN 7.3
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q2' THEN 7.4
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q3' THEN 7.6
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q4' THEN 7.7
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q1' THEN 7.1
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q2' THEN 7.5
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q3' THEN 7.3
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q4' THEN 7.3
                
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q1' THEN 8.6
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q2' THEN 8.8
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q3' THEN 9.0
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q4' THEN 9.0
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q1' THEN 8.6
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q2' THEN 8.8
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q3' THEN 9.0
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q4' THEN 9.0
                ELSE 0
            END AS DECIMAL(15,3)) AS TARGET_NUMERATOR
        , CAST(10 AS DECIMAL(15,3)) AS TARGET_DENOMINATOR
        , CAST(CASE
            WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01' THEN 7.7
            WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03' THEN 7.3
            WHEN METRIC_TYPE = 'FCDD' THEN 8.9
            END AS DECIMAL(15,3)) AS AOP_NUMERATOR

    FROM NA_BI_VWS.PRFCT_ORD_LINE POL

        INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
            ON CAL.DAY_DATE = POL.CMPL_DT

        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID
            AND CUST.CUST_GRP_ID <> '3R'

        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
            ON MATL.MATL_ID = POL.MATL_ID
            AND MATL.PBU_NBR IN ('01', '03')
            AND MATL.EXT_MATL_GRP_ID = 'TIRE'
            --AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')

    WHERE
        POL.CMPL_IND = 1
        AND POL.CMPL_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1) || '-01-01' AS DATE) AND CURRENT_DATE-1
        AND POL.PRFCT_ORD_HIT_SORT_KEY <> 99

    GROUP BY
        METRIC_TYPE
        , COMPLETE_MTH
        , CAL.QUARTER
        , MONTH_NAME
        , MATL.PBU_NBR
        , PBU
        , CATEGORY
        , CATEGORY_NAME
        , TIER
        , CATEGORY_TIER
        , MATL.MATL_PRTY_CTGY
        , MATL.MATL_PRTY
        , MATL.MATL_PRTY_DESCR
        , MATL.EXT_MATL_GRP_ID
        , CUST.TIRE_CUST_TYP_CD
        , EXPORT_IND
        , TARGET_NUMERATOR
        , TARGET_DENOMINATOR
        , AOP_NUMERATOR

    UNION ALL

    SELECT
        CAST('FCDD' AS CHAR(4)) AS METRIC_TYPE
        , POL.FPDD_CMPL_DT - (EXTRACT(DAY FROM POL.FPDD_CMPL_DT) - 1) AS COMPLETE_MTH
        , CAL.QUARTER
        , CAST(CAL.MONTH_DT AS FORMAT 'Mmm') (CHAR(3)) AS MONTH_NAME
        , MATL.PBU_NBR
        , MATL.PBU_NBR || ' - ' || MATL.PBU_NAME AS PBU
        , CASE
            WHEN MATL.PBU_NBR = '01'
                THEN MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME
            ELSE MATL.MKT_CTGY_MKT_GRP_NBR || ' - ' || MATL.MKT_CTGY_MKT_GRP_NAME
          END  AS CATEGORY
        , CASE
            WHEN MATL.PBU_NBR = '01'
                THEN MATL.MKT_CTGY_MKT_AREA_NAME
            ELSE MATL.MKT_CTGY_MKT_GRP_NAME
            END AS CATEGORY_NAME
        , CASE
            WHEN MATL.PBU_NBR = '01'
                THEN MATL.MKT_CTGY_PROD_GRP_NAME
            ELSE MATL.TIERS
            END AS TIER
        , CATEGORY_NAME || ' (' || TIER || ')' AS CATEGORY_TIER
        , MATL.EXT_MATL_GRP_ID
        , MATL.MATL_PRTY_CTGY
        , MATL.MATL_PRTY
        , MATL.MATL_PRTY_DESCR
        , CUST.TIRE_CUST_TYP_CD
        , CAST(CASE
            WHEN CUST.SALES_ORG_CD IN ('N303', 'N313', 'N323') THEN 'X'
            ELSE 'D'
            END AS CHAR(1)) AS EXPORT_IND

        , SUM(ZEROIFNULL(POL.FPDD_ORD_QTY)) AS ORDER_QTY
        , SUM(ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY)) AS HIT_QTY
        , SUM(ZEROIFNULL(POL.FPDD_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY)) AS ONTIME_QTY

        , SUM(ZEROIFNULL(POL.NE_FPDD_HIT_RT_QTY)) AS RETURN_HIT_QTY
        , SUM(ZEROIFNULL(POL.NE_FPDD_HIT_CL_QTY)) AS CLAIM_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_FP_QTY)) AS FREIGHT_POLICY_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CARR_QTY) + ZEROIFNULL(POL.OT_FPDD_HIT_WI_QTY)) AS PHYS_LOG_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_MB_QTY)) AS MAN_BLK_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CH_QTY)) AS CREDIT_HOLD_HIT_QTY
        , SUM(ZEROIFNULL(POL.IF_FPDD_HIT_NS_QTY)) AS NO_STOCK_HIT_QTY
        , SUM(ZEROIFNULL(POL.IF_FPDD_HIT_CO_QTY)) AS CANCEL_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CG_QTY)) AS CUST_GEN_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CG_99_QTY)) AS MAN_REL_CUST_GEN_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_99_QTY)) AS MAN_REL_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_LO_QTY)) AS OTHER_HIT_QTY
        
        , NO_STOCK_HIT_QTY + CANCEL_HIT_QTY AS SUPPLY_HIT_QTY
        , CREDIT_HOLD_HIT_QTY + FREIGHT_POLICY_HIT_QTY + MAN_BLK_HIT_QTY AS POLICY_HIT_QTY
        , RETURN_HIT_QTY + CLAIM_HIT_QTY + CUST_GEN_HIT_QTY + MAN_REL_CUST_GEN_HIT_QTY + MAN_REL_HIT_QTY + OTHER_HIT_QTY AS TOT_OTHER_HIT_QTY
        
        , CAST(CASE
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q1' THEN 7.3
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q2' THEN 7.4
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q3' THEN 7.6
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q4' THEN 7.7
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q1' THEN 7.1
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q2' THEN 7.5
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q3' THEN 7.3
                WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q4' THEN 7.3
                
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q1' THEN 8.6
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q2' THEN 8.8
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q3' THEN 9.0
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '01'  AND CAL.QUARTER = 'Q4' THEN 9.0
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q1' THEN 8.6
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q2' THEN 8.8
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q3' THEN 9.0
                WHEN METRIC_TYPE = 'FCDD' AND MATL.PBU_NBR = '03'  AND CAL.QUARTER = 'Q4' THEN 9.0
                ELSE 0
            END AS DECIMAL(15,3)) AS TARGET_NUMERATOR
        , CAST(10 AS DECIMAL(15,3)) AS TARGET_DENOMINATOR
        , CAST(CASE
            WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '01' THEN 7.7
            WHEN METRIC_TYPE = 'FRDD' AND MATL.PBU_NBR = '03' THEN 7.3
            WHEN METRIC_TYPE = 'FCDD' THEN 8.9
            END AS DECIMAL(15,3)) AS AOP_NUMERATOR

    FROM NA_BI_VWS.PRFCT_ORD_LINE POL

        INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
            ON CAL.DAY_DATE = POL.FPDD_CMPL_DT

        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID
            AND CUST.CUST_GRP_ID <> '3R'

        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
            ON MATL.MATL_ID = POL.MATL_ID
            AND MATL.PBU_NBR IN ('01', '03')
            AND MATL.EXT_MATL_GRP_ID = 'TIRE'
            --AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')

    WHERE
        POL.FPDD_CMPL_IND = 1
        AND POL.FRST_PROM_DELIV_DT IS NOT NULL
        AND POL.FPDD_CMPL_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1) || '-01-01' AS DATE) AND CURRENT_DATE-1
        AND POL.PRFCT_ORD_FPDD_HIT_SORT_KEY <> 99

    GROUP BY
        METRIC_TYPE
        , COMPLETE_MTH
        , CAL.QUARTER
        , MONTH_NAME
        , MATL.PBU_NBR
        , PBU
        , CATEGORY
        , CATEGORY_NAME
        , TIER
        , CATEGORY_TIER
        , MATL.MATL_PRTY_CTGY
        , MATL.MATL_PRTY
        , MATL.MATL_PRTY_DESCR
        , MATL.EXT_MATL_GRP_ID
        , CUST.TIRE_CUST_TYP_CD
        , EXPORT_IND
        , TARGET_NUMERATOR
        , TARGET_DENOMINATOR
        , AOP_NUMERATOR

    ) OTD