WITH 
CUST_HIER (
    SHIP_TO_CUST_ID
    , SHIP_TO_CUST_NAME
    , OWN_CUST_ID
    , OWN_CUST_NAME
    
    , PRIM_SHIP_FACILITY_ID
    , OE_REPL_IND
    , SALES_ORG_CD
    , SALES_ORG_NAME
    , DISTR_CHAN_CD
    , DISTR_CHAN_NAME
    , CUST_GRP_ID
    , CUST_GRP_NAME
    
) AS (

SELECT
    SHIP_TO_CUST_ID
    , CUST_NAME AS SHIP_TO_CUST_NAME
    , OWN_CUST_ID
    , OWN_CUST_NAME
    
    , PRIM_SHIP_FACILITY_ID
    , CASE
        WHEN TIRE_CUST_TYP_CD = 'NA'
            THEN 'REPL'
        ELSE TIRE_CUST_TYP_CD
        END AS OE_REPL_IND
    , SALES_ORG_CD
    , SALES_ORG_NAME
    , DISTR_CHAN_CD
    , DISTR_CHAN_NAME
    , CUST_GRP_ID
    , CUST_GRP_NAME

FROM GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR
WHERE
    SALES_ORG_CD IN (
        'N301', 'N302', 'N303', 'N304', 'N305'
        , 'N311', 'N312', 'N313'
        , 'N321', 'N322', 'N323', 'N325'
        )

),
-- NAMED QUERY
MATL_HIER (

    MATL_ID
    , PBU_NBR
    , PBU_NAME
    , EXT_MATL_GRP_ID
    
) AS (

SELECT
    MATL_ID
    , PBU_NBR
    , PBU_NAME
    , EXT_MATL_GRP_ID

FROM GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR

WHERE
    PBU_NBR = '01'
    AND EXT_MATL_GRP_ID = 'TIRE'

), 
-- NAMED QUERY
DELIV_DOC (

    FISCAL_YR
    , DELIV_DOC_ID

    , BILL_LADING_ID

    , SHIP_TO_CUST_ID

    , SRC_CRT_USR_ID
    , SRC_CRT_TS
    , PLN_GOODS_MVT_DT
    , ACTL_GOODS_MVT_DT
    , DELIV_DT

    , SD_DOC_CTGY_CD
    , DELIV_TYP_CD

    , UNLD_PT_TXT
    , INCOTERM_CD_1
    , INCOTERM_CD_2
    , ROUTE_CD
    , DELIV_PRTY_CD
    , SHIP_COND_CD
    
) AS (

SELECT
    FISCAL_YR
    , DELIV_DOC_ID

    , BILL_LADING_ID

    , SHIP_TO_CUST_ID

    , SRC_CRT_USR_ID
    , SRC_CRT_TS
    , PLN_GOODS_MVT_DT
    , ACTL_GOODS_MVT_DT
    , DELIV_DT

    , SD_DOC_CTGY_CD
    , DELIV_TYP_CD

    , UNLD_PT_TXT
    , INCOTERM_CD_1
    , INCOTERM_CD_2
    , ROUTE_CD
    , DELIV_PRTY_CD
    , SHIP_COND_CD
    
FROM NA_BI_VWS.NAT_DELIV_DOC_CURR_ALL

WHERE
    SD_DOC_CTGY_CD = 'J'
    AND ACTL_GOODS_MVT_DT IS NOT NULL
    AND ACTL_GOODS_MVT_DT BETWEEN DATE '2008-11-01' AND CURRENT_DATE-1

), 
-- NAMED QUERY
DELIV_DOC_ITM (
    FISCAL_YR
    , DELIV_DOC_ID
    , DELIV_DOC_ITM_ID

    , ITM_CTGY_CD
    , SRC_CRT_USR_ID
    , SRC_CRT_TS

    , MATL_ID
    , BATCH_NBR
    , MATL_GRP_CD
    , MATL_HIER_ID

    , FACILITY_ID

    , BASE_UOM_CD
    , ACTL_DELIV_QTY

    , MATL_AVAIL_DT

    , SD_DOC_CTGY_CD
    , SLS_DOC_ID
    , SLS_DOC_ITM_ID

    , AVAIL_CHK_GRP_CD

    , DISTR_CHAN_CD
    , DELIV_GRP_CD
) AS (

SELECT
    FISCAL_YR
    , DELIV_DOC_ID
    , DELIV_DOC_ITM_ID

    , ITM_CTGY_CD
    , SRC_CRT_USR_ID
    , SRC_CRT_TS

    , MATL_ID
    , BATCH_NBR
    , MATL_GRP_CD
    , MATL_HIER_ID

    , FACILITY_ID

    , BASE_UOM_CD
    , ACTL_DELIV_QTY

    , MATL_AVAIL_DT

    , SD_DOC_CTGY_CD
    , SLS_DOC_ID
    , SLS_DOC_ITM_ID

    , AVAIL_CHK_GRP_CD
    , DISTR_CHAN_CD
    , DELIV_GRP_CD

FROM NA_BI_VWS.NAT_DELIV_DOC_ITM_CURR

WHERE
    ACTL_DELIV_QTY <> 0
    AND SRC_CRT_TS BETWEEN TIMESTAMP '2008-11-01 00:00:00' AND CURRENT_TIMESTAMP

),
-- NAMED QUERY
SLS_DOC (
    FISCAL_YR
    , SLS_DOC_ID

    , SRC_CRT_DT
    , SRC_CRT_TM
    , SRC_CRT_USR_ID
    , DOC_DT

    , SD_DOC_CTGY_CD
    , TRANS_GRP_CD
    , SLS_DOC_TYP_CD
    , DELIV_BLK_CD
    , BILL_BLK_CD

    , CO_CD
    , SALES_ORG_CD
    , DISTR_CHAN_CD
    , DIV_CD

    , COMPL_DELIV_IND
    , SHIP_COND_CD

    , CUST_PRCH_ORD_ID
    , CUST_PRCH_ORD_TYP_CD
    , CUST_PRCH_ORD_DT

    , SOLD_TO_CUST_ID
    , SHIP_TO_CUST_ID

    , MATL_AVAIL_DT
    , REQ_DELIV_DT
    
) AS (

SELECT
    FISCAL_YR
    , SLS_DOC_ID

    , SRC_CRT_DT
    , SRC_CRT_TM
    , SRC_CRT_USR_ID
    , DOC_DT

    , SD_DOC_CTGY_CD
    , TRANS_GRP_CD
    , SLS_DOC_TYP_CD
    , DELIV_BLK_CD
    , BILL_BLK_CD

    , CO_CD
    , SALES_ORG_CD
    , DISTR_CHAN_CD
    , DIV_CD

    , COMPL_DELIV_IND
    , SHIP_COND_CD

    , CUST_PRCH_ORD_ID
    , CUST_PRCH_ORD_TYP_CD
    , CUST_PRCH_ORD_DT

    , SOLD_TO_CUST_ID
    , SHIP_TO_CUST_ID

    , MATL_AVAIL_DT
    , REQ_DELIV_DT
    
FROM GDYR_BI_VWS.NAT_SLS_DOC_CURR

WHERE
    SD_DOC_CTGY_CD = 'C'
    --AND CO_CD IN ('N101', 'N102', 'N266')
    AND SRC_CRT_DT BETWEEN DATE '2008-01-01' AND CURRENT_DATE-1
),
-- NAMED QUERY
SLS_DOC_ITM (
    FISCAL_YR
    , SLS_DOC_ID
    , SLS_DOC_ITM_ID

    , SRC_CRT_TS
    , SRC_CRT_USR_ID
    , SRC_UPD_DT

    , MATL_ID
    , MATL_GRP_ID
    , MATL_HIER_ID

    , FACILITY_ID
    , SHIP_RCVE_PT_CD

    , SLS_UOM_CD
    , SLS_UNIT_CUM_ORD_QTY
    , SLS_UNIT_CUM_REQ_DELIV_QTY

    , SLS_DOC_ITM_CTGY_CD
    , ITM_TYP_CD

    , REJ_REAS_ID
    , DELIV_GRP_ID
    , DELIV_PRTY_CD
    
    , ORIG_REQ_DELIV_DT
    , FRST_MATL_AVAIL_DT
    , FRST_PLN_GOODS_ISS_DT
    , FRST_REQ_DELIV_DT
    , FNL_ACCEPT_DT
) AS (

SELECT
    FISCAL_YR
    , SLS_DOC_ID
    , SLS_DOC_ITM_ID

    , SRC_CRT_TS
    , SRC_CRT_USR_ID
    , SRC_UPD_DT

    , MATL_ID
    , MATL_GRP_ID
    , MATL_HIER_ID

    , FACILITY_ID
    , SHIP_RCVE_PT_CD

    , SLS_UOM_CD
    , SLS_UNIT_CUM_ORD_QTY
    , SLS_UNIT_CUM_REQ_DELIV_QTY

    , SLS_DOC_ITM_CTGY_CD
    , ITM_TYP_CD

    , REJ_REAS_ID
    , DELIV_GRP_ID
    , DELIV_PRTY_CD
    
    , ORIG_REQ_DELIV_DT
    , FRST_MATL_AVAIL_DT
    , FRST_PLN_GOODS_ISS_DT
    , FRST_REQ_DELIV_DT
    , FNL_ACCEPT_DT

FROM GDYR_BI_VWS.NAT_SLS_DOC_ITM_CURR

WHERE
    SRC_CRT_TS BETWEEN TIMESTAMP '2008-01-01 00:00:00' AND CURRENT_TIMESTAMP

),
-- NAMED QUERY
SCHED_LINE (

    FISCAL_YR
    , SLS_DOC_ID
    , SLS_DOC_ITM_ID
    , SCHD_LN_ID

    , MATL_AVAIL_DT
    , GOODS_ISS_DT
    , SCHD_LN_DELIV_DT

    , SLS_UOM_CD
    , SLS_UNIT_ORD_QTY
    , SLS_UNIT_CNFRM_QTY
    
) AS (

SELECT
    FISCAL_YR
    , SLS_DOC_ID
    , SLS_DOC_ITM_ID
    , SCHD_LN_ID

    , MATL_AVAIL_DT
    , GOODS_ISS_DT
    , SCHD_LN_DELIV_DT

    , SLS_UOM_CD
    , SLS_UNIT_ORD_QTY
    , SLS_UNIT_CNFRM_QTY

FROM GDYR_BI_VWS.NAT_SLS_DOC_SCHD_LN_CURR

WHERE
    SCHD_LN_ID = 1

)

-- OUTPUT QUERY
SELECT
    --Q.ON_TIME_IND_GOODS_ISS AS ON_TIME_IND
    --, Q.ADJ_REQ_DELIV_DT - (EXTRACT(DAY FROM Q.ADJ_REQ_DELIV_DT)-1) AS REQ_DELIV_MTH_DT
    --, 
    Q.ACTL_GOODS_MVT_DT - (EXTRACT(DAY FROM Q.ACTL_GOODS_MVT_DT)-1) AS AGID_MTH_DT
    
/*    , Q.SALES_ORG_CD
    , Q.DISTR_CHAN_CD
    , Q.CUST_GRP_ID*/
    
    , Q.OE_REPL_IND
    
    , Q.PBU_NBR || ' - ' || Q.PBU_NAME AS PBU

    , Q.BASE_UOM_CD
    , SUM(Q.ACTL_DELIV_QTY) AS TOT_DELIV_QTY
    , SUM(CASE
        WHEN Q.ON_TIME_IND_GOODS_ISS = 'Y'
            THEN Q.ACTL_DELIV_QTY
        ELSE 0
        END) AS ON_TIME_DELIV_QTY
    , SUM(CASE
        WHEN Q.ON_TIME_IND_GOODS_ISS = 'N'
            THEN Q.ACTL_DELIV_QTY
        ELSE 0
        END) AS LATE_DELIV_QTY
    
FROM (

SELECT
    DDI.FISCAL_YR AS DELIV_DOC_FISCAL_YR
    , DDI.DELIV_DOC_ID
    , DDI.DELIV_DOC_ITM_ID
    
    , SDI.FISCAL_YR AS SLS_DOC_FISCAL_YR
    , SDI.SLS_DOC_ID
    , SDI.SLS_DOC_ITM_ID
    
    , SD.SRC_CRT_DT AS SD_HDR_CRT_DT
    , SD.SRC_CRT_TM AS SD_HDR_CRT_TM
    , SD.SRC_CRT_USR_ID AS SD_HDR_CRT_USR_ID
    , SDI.SRC_CRT_TS AS SD_ITM_CRT_TS
    , SDI.SRC_CRT_USR_ID AS SD_ITM_CRT_USR_ID
    , DD.SRC_CRT_TS AS DLV_HDR_CRT_TS
    , DD.SRC_CRT_USR_ID AS DLV_HDR_CRT_USR_ID
    , DDI.SRC_CRT_TS AS DLV_ITM_CRT_TS
    , DDI.SRC_CRT_USR_ID AS DLV_ITM_CRT_USR_ID
    
    , SD.SHIP_TO_CUST_ID
    , CUST.OE_REPL_IND
    
    , CUST.SALES_ORG_CD
    , CUST.DISTR_CHAN_CD
    , CUST.CUST_GRP_ID

    , SDI.MATL_ID
    , SDI.MATL_GRP_ID
    , SDI.MATL_HIER_ID
    , MATL.PBU_NBR
    , MATL.PBU_NAME
    
    , SDI.FACILITY_ID

    , SD.SHIP_COND_CD
    , SDI.REJ_REAS_ID
    , SDI.DELIV_GRP_ID
    , SDI.DELIV_PRTY_CD

    , SD.CUST_PRCH_ORD_ID
    , SD.CUST_PRCH_ORD_TYP_CD
    , SD.CUST_PRCH_ORD_DT

    , SD.MATL_AVAIL_DT
    , SD.REQ_DELIV_DT
    , CASE
        WHEN SDI.FRST_PLN_GOODS_ISS_DT IS NOT NULL
            THEN SDI.FRST_PLN_GOODS_ISS_DT
        WHEN SD.REQ_DELIV_DT < SL.SCHD_LN_DELIV_DT
            THEN SL.SCHD_LN_DELIV_DT
        ELSE SD.REQ_DELIV_DT
        END AS ADJ_REQ_DELIV_DT
    
    , SDI.SLS_UOM_CD
    , SDI.SLS_UNIT_CUM_ORD_QTY
    , SDI.SLS_UNIT_CUM_REQ_DELIV_QTY
    
    , DDI.BASE_UOM_CD
    , DDI.ACTL_DELIV_QTY
    
    , SDI.ORIG_REQ_DELIV_DT
    , SDI.FRST_MATL_AVAIL_DT
    , SDI.FRST_PLN_GOODS_ISS_DT
    , SDI.FRST_REQ_DELIV_DT
    
    , SL.MATL_AVAIL_DT AS MAD_FIRST_DATE
    , SL.GOODS_ISS_DT AS PGI_FIRST_DATE
    , SL.SCHD_LN_DELIV_DT AS FIRST_DATE
    
    , DD.SRC_CRT_USR_ID
    , DD.SRC_CRT_TS
    , DD.PLN_GOODS_MVT_DT
    , DD.ACTL_GOODS_MVT_DT
    , DD.DELIV_DT
    
    , CASE
        WHEN ADJ_REQ_DELIV_DT >= DD.DELIV_DT
            THEN 'Y'
        ELSE 'N'
        END AS ON_TIME_IND_DELIV
    , CASE
        WHEN ADJ_REQ_DELIV_DT >= DD.ACTL_GOODS_MVT_DT
            THEN 'Y'
        ELSE 'N'
        END AS ON_TIME_IND_GOODS_ISS

    , SD.SD_DOC_CTGY_CD AS ORDER_CAT_ID
    , SD.SLS_DOC_TYP_CD AS ORDER_TYPE_ID
    , DD.SD_DOC_CTGY_CD AS DELIV_CAT_ID
    , DD.DELIV_TYP_CD
    
    , DD.UNLD_PT_TXT
    
FROM DELIV_DOC_ITM DDI

    INNER JOIN MATL_HIER MATL
        ON MATL.MATL_ID = DDI.MATL_ID

    INNER JOIN DELIV_DOC DD
        ON DD.FISCAL_YR = DDI.FISCAL_YR
        AND DD.DELIV_DOC_ID = DDI.DELIV_DOC_ID

    INNER JOIN CUST_HIER CUST
        ON CUST.SHIP_TO_CUST_ID = DD.SHIP_TO_CUST_ID

    INNER JOIN SLS_DOC_ITM SDI
        ON SDI.SLS_DOC_ID = DDI.SLS_DOC_ID
        AND SDI.SLS_DOC_ITM_ID = DDI.SLS_DOC_ITM_ID
        AND SDI.MATL_ID = DDI.MATL_ID
        AND SDI.FACILITY_ID = DDI.FACILITY_ID

    INNER JOIN SCHED_LINE SL
        ON SL.FISCAL_YR = SDI.FISCAL_YR
        AND SL.SLS_DOC_ID = SDI.SLS_DOC_ID
        AND SL.SLS_DOC_ITM_ID = SDI.SLS_DOC_ITM_ID

    INNER JOIN SLS_DOC SD
        ON SD.FISCAL_YR = SDI.FISCAL_YR
        AND SD.SLS_DOC_ID = SDI.SLS_DOC_ID

WHERE
    DD.ACTL_GOODS_MVT_DT BETWEEN DATE '2009-01-01' AND CURRENT_DATE-1
    AND CUST.CUST_GRP_ID <> '3R'

    ) Q

GROUP BY
    --ON_TIME_IND
    --, REQ_DELIV_MTH_DT
    --, 
    AGID_MTH_DT
    
/*    , Q.SALES_ORG_CD
    , Q.DISTR_CHAN_CD
    , Q.CUST_GRP_ID*/
    
    , Q.OE_REPL_IND
    , PBU
    --, DAYS_BW_REQ_AND_DELIV
    --, Q.SHIP_TO_CUST_ID
    --, Q.MATL_ID
    --, Q.FACILITY_ID
    , Q.BASE_UOM_CD


