SELECT
    OTD.METRIC_TYPE
    , OTD.COMPLETE_MTH

    , OTD.PBU_NBR
    , OTD.PBU_NAME
    , OTD.CATEGORY_CD
    , OTD.CATEGORY_NAME
    , OTD.TIER
    , OTD.EXT_MATL_GRP_ID

    , OTD.TIRE_CUST_TYP_CD

    , OTD.PRIM_SHIP_FACILITY_TEST
    , OTD.SHIP_FACILITY_ID
    , OTD.SHIP_FACILITY_NAME
    , OTD.SHIP_FACILITY_ID || ' - ' || OTD.SHIP_FACILITY_NAME AS SHIP_FACILITY_AND_NAME

    , OTD.CUST_GRP2_CD
    , OTD.CUST_GRP2_DESC

    , OTD.ORDER_QTY
    , OTD.HIT_QTY
    , OTD.ONTIME_QTY

    , OTD.MAN_BLK_HIT_QTY
    , OTD.FREIGHT_POLICY_HIT_QTY
    , OTD.CREDIT_HOLD_HIT_QTY

    , OTD.PHYS_LOG_HIT_QTY
    , SUM(OTD.PHYS_LOG_HIT_QTY) OVER (PARTITION BY OTD.METRIC_TYPE, EXTRACT(YEAR FROM OTD.COMPLETE_MTH), OTD.PBU_NBR, OTD.EXT_MATL_GRP_ID, OTD.SHIP_FACILITY_ID) AS YTD_PHYS_LOG_HIT_QTY

    , OTD.NO_STOCK_HIT_QTY
    , OTD.CANCEL_HIT_QTY

    , OTD.RETURN_HIT_QTY
    , OTD.CLAIM_HIT_QTY
    , OTD.CUST_GEN_HIT_QTY
    , OTD.MAN_REL_CUST_GEN_HIT_QTY
    , OTD.MAN_REL_HIT_QTY
    , OTD.OTHER_HIT_QTY

    , ZEROIFNULL(DD.DELIV_QTY) AS LC_MTH_SHIP_QTY
    , ZEROIFNULL(SF.FORC_QTY) AS LC_MTH_FORC_QTY
    , SUM(OTD.ORDER_QTY) OVER (PARTITION BY OTD.METRIC_TYPE, EXTRACT(YEAR FROM OTD.COMPLETE_MTH), OTD.PBU_NBR, OTD.EXT_MATL_GRP_ID, OTD.SHIP_FACILITY_ID) AS YTD_ORDER_QTY

FROM (

    SELECT
        CAST('FRDD' AS CHAR(4)) AS METRIC_TYPE
        , POL.CMPL_DT - (EXTRACT(DAY FROM POL.CMPL_DT) - 1) AS COMPLETE_MTH

        , MATL.PBU_NBR
        , MATL.PBU_NAME
        , MATL.MKT_CTGY_MKT_AREA_NBR AS CATEGORY_CD
        , MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY_NAME
        , MATL.MKT_CTGY_PROD_GRP_NAME AS TIER
        , MATL.EXT_MATL_GRP_ID

        , CUST.TIRE_CUST_TYP_CD
        , CASE
            WHEN POL.SHIP_FACILITY_ID IN ('N5US', 'N5CA')
                THEN 'N5US/N5CA'
            WHEN POL.SHIP_FACILITY_ID = CUST.PRIM_SHIP_FACILITY_ID
                THEN 'Primary LC'
            ELSE (CASE
                WHEN POL.SHIP_FACILITY_ID LIKE 'N5%'
                    THEN 'Factory Direct'
                ELSE 'Out of Area'
            END)
            END AS PRIM_SHIP_FACILITY_TEST
        , CUST.PRIM_SHIP_FACILITY_ID
        , POL.SHIP_FACILITY_ID
        , FAC.FACILITY_NAME AS SHIP_FACILITY_NAME
        , POL.CUST_GRP2_CD
        , CG2.CUST_GRP2_DESC

        , SUM(ZEROIFNULL(POL.CURR_ORD_QTY)) AS ORDER_QTY
        , SUM(ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY)) AS HIT_QTY
        , SUM(ZEROIFNULL(POL.CURR_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY)) AS ONTIME_QTY

        , SUM(ZEROIFNULL(POL.NE_HIT_RT_QTY)) AS RETURN_HIT_QTY
        , SUM(ZEROIFNULL(POL.NE_HIT_CL_QTY)) AS CLAIM_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_FP_QTY)) AS FREIGHT_POLICY_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_CARR_PICKUP_QTY) + ZEROIFNULL(POL.OT_HIT_WI_QTY)) AS PHYS_LOG_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_MB_QTY)) AS MAN_BLK_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_CH_QTY)) AS CREDIT_HOLD_HIT_QTY
        , SUM(ZEROIFNULL(POL.IF_HIT_NS_QTY)) AS NO_STOCK_HIT_QTY
        , SUM(ZEROIFNULL(POL.IF_HIT_CO_QTY)) AS CANCEL_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_CG_QTY)) AS CUST_GEN_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_CG_99_QTY)) AS MAN_REL_CUST_GEN_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_99_QTY)) AS MAN_REL_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_HIT_LO_QTY)) AS OTHER_HIT_QTY

    FROM NA_BI_VWS.PRFCT_ORD_LINE POL

        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID

        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
            ON MATL.MATL_ID = POL.MATL_ID
            AND MATL.PBU_NBR IN ('01', '03')
            AND MATL.EXT_MATL_GRP_ID = 'TIRE'

        INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FAC
            ON FAC.FACILITY_ID = POL.SHIP_FACILITY_ID

        INNER JOIN NA_BI_VWS.CUST_GRP2_DESC_EN_CURR CG2
            ON CG2.CUST_GRP2_CD = POL.CUST_GRP2_CD

    WHERE
        POL.CMPL_IND = 1
        AND POL.CMPL_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1) || '-01-01' AS DATE) AND CURRENT_DATE-1
            --CAST(EXTRACT(YEAR FROM CURRENT_DATE-1) || '-01-01' AS DATE) AND CURRENT_DATE-1
        AND POL.PRFCT_ORD_HIT_SORT_KEY <> 99

    GROUP BY
        METRIC_TYPE
        , COMPLETE_MTH

        , MATL.PBU_NBR
        , MATL.PBU_NAME
        , CATEGORY_CD
        , CATEGORY_NAME
        , TIER
        , MATL.EXT_MATL_GRP_ID

        , CUST.TIRE_CUST_TYP_CD
        , PRIM_SHIP_FACILITY_TEST
        , CUST.PRIM_SHIP_FACILITY_ID
        , POL.SHIP_FACILITY_ID
        , SHIP_FACILITY_NAME
        , POL.CUST_GRP2_CD
        , CG2.CUST_GRP2_DESC

    UNION ALL

    SELECT
        CAST('FCDD' AS CHAR(4)) AS METRIC_TYPE
        , POL.FPDD_CMPL_DT - (EXTRACT(DAY FROM POL.FPDD_CMPL_DT) - 1) AS COMPLETE_MTH

        , MATL.PBU_NBR
        , MATL.PBU_NAME
        , MATL.MKT_CTGY_MKT_AREA_NBR AS CATEGORY_CD
        , MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY_NAME
        , MATL.MKT_CTGY_PROD_GRP_NAME AS TIER
        , MATL.EXT_MATL_GRP_ID

        , CUST.TIRE_CUST_TYP_CD
        , CASE
            WHEN POL.SHIP_FACILITY_ID IN ('N5US', 'N5CA')
                THEN 'N5US/N5CA'
            WHEN POL.SHIP_FACILITY_ID = CUST.PRIM_SHIP_FACILITY_ID
                THEN 'Primary LC'
            ELSE (CASE
                WHEN POL.SHIP_FACILITY_ID LIKE 'N5%'
                    THEN 'Factory Direct'
                ELSE 'Out of Area'
            END)
            END AS PRIM_SHIP_FACILITY_TEST
        , CUST.PRIM_SHIP_FACILITY_ID
        , POL.SHIP_FACILITY_ID
        , FAC.FACILITY_NAME AS SHIP_FACILITY_NAME
        , POL.CUST_GRP2_CD
        , CG2.CUST_GRP2_DESC

        , SUM(ZEROIFNULL(POL.FPDD_ORD_QTY)) AS ORDER_QTY
        , SUM(ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY)) AS HIT_QTY
        , SUM(ZEROIFNULL(POL.FPDD_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY)) AS ONTIME_QTY

        , SUM(ZEROIFNULL(POL.NE_FPDD_HIT_RT_QTY)) AS RETURN_HIT_QTY
        , SUM(ZEROIFNULL(POL.NE_FPDD_HIT_CL_QTY)) AS CLAIM_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_FP_QTY)) AS FREIGHT_POLICY_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CARR_QTY) + ZEROIFNULL(POL.OT_FPDD_HIT_WI_QTY)) AS PHYS_LOG_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_MB_QTY)) AS MAN_BLK_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CH_QTY)) AS CREDIT_HOLD_HIT_QTY
        , SUM(ZEROIFNULL(POL.IF_FPDD_HIT_NS_QTY)) AS NO_STOCK_HIT_QTY
        , SUM(ZEROIFNULL(POL.IF_FPDD_HIT_CO_QTY)) AS CANCEL_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CG_QTY)) AS CUST_GEN_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_CG_99_QTY)) AS MAN_REL_CUST_GEN_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_99_QTY)) AS MAN_REL_HIT_QTY
        , SUM(ZEROIFNULL(POL.OT_FPDD_HIT_LO_QTY)) AS OTHER_HIT_QTY

    FROM NA_BI_VWS.PRFCT_ORD_LINE POL

        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID

        INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
            ON MATL.MATL_ID = POL.MATL_ID
            AND MATL.PBU_NBR IN ('01', '03')
            AND MATL.EXT_MATL_GRP_ID = 'TIRE'

        INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FAC
            ON FAC.FACILITY_ID = POL.SHIP_FACILITY_ID

        INNER JOIN NA_BI_VWS.CUST_GRP2_DESC_EN_CURR CG2
            ON CG2.CUST_GRP2_CD = POL.CUST_GRP2_CD

    WHERE
        POL.FPDD_CMPL_IND = 1
        AND POL.FRST_PROM_DELIV_DT IS NOT NULL
        AND POL.FPDD_CMPL_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1) || '-01-01' AS DATE) AND CURRENT_DATE-1
            --CAST(EXTRACT(YEAR FROM CURRENT_DATE-1) || '-01-01' AS DATE) AND CURRENT_DATE-1
        AND POL.PRFCT_ORD_FPDD_HIT_SORT_KEY <> 99

    GROUP BY
        METRIC_TYPE
        , COMPLETE_MTH

        , MATL.PBU_NBR
        , MATL.PBU_NAME
        , CATEGORY_CD
        , CATEGORY_NAME
        , TIER
        , MATL.EXT_MATL_GRP_ID

        , CUST.TIRE_CUST_TYP_CD
        , PRIM_SHIP_FACILITY_TEST
        , CUST.PRIM_SHIP_FACILITY_ID
        , POL.SHIP_FACILITY_ID
        , SHIP_FACILITY_NAME
        , POL.CUST_GRP2_CD
        , CG2.CUST_GRP2_DESC

    ) OTD

    LEFT OUTER JOIN (
            SELECT
                DDC.DELIV_LINE_FACILITY_ID
                , MATL.PBU_NBR
                , MATL.EXT_MATL_GRP_ID
                , CAL.MONTH_DT
                , SUM(DDC.DELIV_QTY) AS DELIV_QTY

            FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

                INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
                    ON CAL.DAY_DATE = DDC.ACTL_GOODS_ISS_DT

                INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR MATL
                    ON MATL.MATL_ID = DDC.MATL_ID
                    AND MATL.PBU_NBR IN ('01', '03')
                    AND MATL.EXT_MATL_GRP_ID = 'TIRE'

                INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
                    ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID

            WHERE
                DDC.DELIV_CAT_ID = 'J'
                AND DDC.DISTR_CHAN_CD <> '81'
                AND DDC.DELIV_QTY > 0
                AND DDC.GOODS_ISS_IND = 'Y'
                AND DDC.ACTL_GOODS_ISS_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1) || '-01-01' AS DATE) AND CURRENT_DATE-1

            GROUP BY
                DDC.DELIV_LINE_FACILITY_ID
                , MATL.PBU_NBR
                , MATL.EXT_MATL_GRP_ID
                , CAL.MONTH_DT
            ) DD
        ON DD.DELIV_LINE_FACILITY_ID = OTD.SHIP_FACILITY_ID
        AND DD.PBU_NBR = OTD.PBU_NBR
        AND DD.MONTH_DT = OTD.COMPLETE_MTH
        AND DD.EXT_MATL_GRP_ID = OTD.EXT_MATL_GRP_ID

    LEFT OUTER JOIN (
            SELECT
                SF.FORC_MTH_DT AS MONTH_DT
                , SF.FACILITY_ID
                , SF.PBU_NBR
                , SF.EXT_MATL_GRP_ID
                , SUM(ZEROIFNULL(SF.FORC_SKU_QTY)) AS FORC_QTY

            FROM (
                    SELECT
                        F.FACILITY_ID
                        , F.MATL_ID
                        , MATL.PBU_NBR
                        , MATL.EXT_MATL_GRP_ID
                        , F.FORC_MTH_DT
                        , F.FORC_MTH_DT + 10 AS FCST_DT
                        , F.FORC_SKU_QTY

                    FROM GDYR_VWS.SKU_FORC F

                        INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR MATL
                            ON MATL.MATL_ID = F.MATL_ID
                            AND MATL.PBU_NBR IN ('01', '03')
                            AND MATL.EXT_MATL_GRP_ID = 'TIRE'

                        INNER JOIN GDYR_BI_vWS.NAT_FACILITY_EN_CURR FAC
                            ON FAC.FACILITY_ID = F.FACILITY_ID
                            AND FAC.SALES_ORG_CD IN ('N306', 'N316', 'N326')
                            AND FAC.DISTR_CHAN_CD = '81'

                    WHERE
                        F.EXP_DT >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1) || '-01-01' AS DATE)
                        AND F.SBU_ID = 2
                        AND FCST_DT BETWEEN F.EFF_DT AND F.EXP_DT
                        AND F.FORC_MTH_DT >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1) || '-01-01' AS DATE)

                        ) SF

            GROUP BY
                SF.FORC_MTH_DT
                , SF.FACILITY_ID
                , SF.PBU_NBR
                , SF.EXT_MATL_GRP_ID
            ) SF
        ON SF.FACILITY_ID = OTD.SHIP_FACILITY_ID
        AND SF.PBU_NBR = OTD.PBU_NBR
        AND SF.MONTH_DT = OTD.COMPLETE_MTH
        AND SF.EXT_MATL_GRP_ID = OTD.EXT_MATL_GRP_ID



