SELECT
    Q.METRIC_TYPE
    , Q.COMPLETE_MTH
    , Q.MATL_ID
    , Q.MATL_DESCR
    , Q.PBU_NBR
    , Q.PBU_NAME
    , Q.CATEGORY_CD
    , Q.CATEGORY_NM
    , Q.TIER
    , Q.MATL_PRTY

    , Q.SALES_ORG_CD
    , Q.SALES_ORG_NAME
    , Q.DISTR_CHAN_CD
    , Q.DISTR_CHAN_NAME
    , Q.CUST_GRP_ID
    , Q.CUST_GRP_NAME
    , Q.OWN_CUST_ID
    , Q.OWN_CUST_NAME
    , Q.OE_REPL_IND
    , Q.OE_REPL_DESC

    , Q.PRIM_SHIP_FACILITY_ID
    , Q.FACILITY_ID
    , Q.FACILITY_NAME
    , Q.DELIV_PRTY_ID

    --, Q.METRIC_FMAD
    --, Q.METRIC_FPGI
    --, Q.METRIC_DT

    , SUM(Q.ORIG_ORDER_QTY) AS ORIG_ORDER_QTY
    , SUM(Q.CANCEL_QTY) AS CANCEL_QTY
    , SUM(Q.ORDER_QTY) AS ORDER_QTY
    , SUM(Q.HIT_QTY) AS HIT_QTY
    , SUM(Q.ONTIME_QTY) AS ONTIME_QTY
    , SUM(Q.REL_LATE_QTY) AS REL_LATE_QTY
    , SUM(Q.REL_ONTIME_QTY) AS REL_ONTIME_QTY
    , SUM(Q.COMMIT_ONTIME_QTY) AS COMMIT_ONTIME_QTY
    , SUM(Q.DELIV_LATE_QTY) AS DELIV_LATE_QTY
    , SUM(Q.DELIV_ONTIME_QTY) AS DELIV_ONTIME_QTY
    , SUM(Q.RETURN_HIT_QTY) AS RETURN_HIT_QTY
    , SUM(Q.CLAIM_HIT_QTY) AS CLAIM_HIT_QTY
    , SUM(Q.FREIGHT_POLICY_HIT_QTY) AS FREIGHT_POLICY_HIT_QTY
    , SUM(Q.PHYS_LOG_HIT_QTY) AS PHYS_LOG_HIT_QTY
    , SUM(Q.MAN_BLK_HIT_QTY) AS MAN_BLK_HIT_QTY
    , SUM(Q.CREDIT_HOLD_HIT_QTY) AS CREDIT_HOLD_HIT_QTY
    , SUM(Q.NO_STOCK_HIT_QTY) AS NO_STOCK_HIT_QTY
    , SUM(Q.CANCEL_HIT_QTY) AS CANCEL_HIT_QTY
    , SUM(Q.CUST_GEN_HIT_QTY) AS CUST_GEN_HIT_QTY
    , SUM(Q.MAN_REL_CUST_GEN_HIT_QTY) AS MAN_REL_CUST_GEN_HIT_QTY
    , SUM(Q.MAN_REL_HIT_QTY) AS MAN_REL_HIT_QTY
    , SUM(Q.OTHER_HIT_QTY) AS OTHER_HIT_QTY

FROM (

SELECT
    CAST('FRDD' AS CHAR(4)) AS METRIC_TYPE
    , OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR
    , POL.CMPL_IND
    , POL.CMPL_DT
    , CMPL_CAL.MONTH_DT AS COMPLETE_MTH
    , POL.NO_STK_DT AS NO_STOCK_DATE

    , POL.MATL_ID
    , M.MATL_NO_8 || ' - ' || M.DESCR AS MATL_DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , CASE
        WHEN M.PBU_NBR = '01'
            THEN M.MKT_CTGY_MKT_AREA_NBR
        ELSE M.MKT_CTGY_MKT_GRP_NBR
        END AS CATEGORY_CD
    , CASE
        WHEN M.PBU_NBR = '01'
            THEN M.MKT_CTGY_MKT_AREA_NAME
        ELSE M.MKT_CTGY_MKT_GRP_NAME
        END AS CATEGORY_NM
    , CASE
        WHEN M.PBU_NBR = '01'
            THEN M.MKT_CTGY_PROD_GRP_NAME
        ELSE M.TIERS
        END AS TIER
    , M.EXT_MATL_GRP_ID
    , M.MATL_PRTY

    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME
    , POL.SHIP_TO_CUST_ID
    , C.CUST_NAME AS SHIP_TO_CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , CAST(CASE 
        WHEN C.SALES_ORG_CD IN ('N302', 'N312', 'N322') OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD = '32')
            THEN 'OE'
        ELSE 'REPL'
        END AS VARCHAR(4)) OE_REPL_IND
    , CAST(CASE 
        WHEN OE_REPL_IND = 'OE'
            THEN 'OEM'
        WHEN OE_REPL_IND = 'REPL'
            THEN 'Replacement'
        ELSE OE_REPL_IND
        END AS VARCHAR(25)) OE_REPL_DESC
    , C.PRIM_SHIP_FACILITY_ID
    , F.FACILITY_ID
    , F.FACILITY_NAME
    , POL.DELIV_PRTY_ID
    , POL.DELIV_BLK_IND
    , POL.CREDIT_HOLD_FLG
    , POL.NUM_DELIV_LINES
    , POL.CAN_REJ_REAS_ID
    , OD.CANCEL_DT
    , POL.PO_TYPE_ID
    , POL.CANCEL_IND
    , POL.CUST_GRP2_CD
    , POL.SHIP_COND_ID
    , POL.TMS_CD
    , POL.SPCL_PROC_ID
    , POL.MAX_CARR_SCAC_ID
    , OD.ORDER_DT
    , OD.ORDER_CRT_TM
    , OD.ORDER_LN_CRT_DT
    , OD.ORDER_LN_CRT_TM
    , POL.FMAD_DT AS METRIC_FMAD
    , POL.FPGI_DT AS METRIC_FPGI
    , POL.REQ_DELIV_DT AS METRIC_DT

    , POL.REQ_DELIV_DT AS FRDD
    , POL.FRST_PROM_DELIV_DT AS FCDD
    , POL.MAX_DELIV_NOTE_CREA_DT
    , POL.MAX_EDI_DELIV_DT
    , POL.MAX_SAP_DELIV_DT
    , POL.ACTL_DELIV_DT
    , POL.CUST_APPT_DT

    , ZEROIFNULL(POL.ORIG_ORD_QTY) AS ORIG_ORDER_QTY
    , ZEROIFNULL(POL.CANCEL_QTY) AS CANCEL_QTY
    , ZEROIFNULL(POL.CURR_ORD_QTY) AS ORDER_QTY
    , ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY) AS HIT_QTY
    , ZEROIFNULL(POL.CURR_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY) AS ONTIME_QTY
    , ZEROIFNULL(POL.REL_LATE_QTY) AS REL_LATE_QTY
    , ZEROIFNULL(POL.REL_ONTIME_QTY) AS REL_ONTIME_QTY
    , ZEROIFNULL(POL.COMMIT_ONTIME_QTY) AS COMMIT_ONTIME_QTY
    , ZEROIFNULL(POL.DELIV_LATE_QTY) AS DELIV_LATE_QTY
    , ZEROIFNULL(POL.DELIV_ONTIME_QTY) AS DELIV_ONTIME_QTY
    , ZEROIFNULL(POL.NE_HIT_RT_QTY) AS RETURN_HIT_QTY
    , ZEROIFNULL(POL.NE_HIT_CL_QTY) AS CLAIM_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_FP_QTY) AS FREIGHT_POLICY_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_CARR_PICKUP_QTY) + ZEROIFNULL(POL.OT_HIT_WI_QTY) AS PHYS_LOG_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_MB_QTY) AS MAN_BLK_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_CH_QTY) AS CREDIT_HOLD_HIT_QTY
    , ZEROIFNULL(POL.IF_HIT_NS_QTY) AS NO_STOCK_HIT_QTY
    , ZEROIFNULL(POL.IF_HIT_CO_QTY) AS CANCEL_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_CG_QTY) AS CUST_GEN_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_CG_99_QTY) AS MAN_REL_CUST_GEN_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_99_QTY) AS MAN_REL_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_LO_QTY) AS OTHER_HIT_QTY

FROM NA_BI_VWS.PRFCT_ORD_LINE POL

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CMPL_CAL
        ON CMPL_CAL.DAY_DATE = POL.CMPL_DT
        AND CMPL_CAL.DAY_DATE < CURRENT_DATE

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = POL.MATL_ID
        AND M.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
        AND M.MATL_TYPE_ID = 'PCTL'

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = POL.SHIP_FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = POL.ORDER_FISCAL_YR
        AND OD.ORDER_ID = POL.ORDER_ID
        AND OD.ORDER_LINE_NBR = POL.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = 1
        AND OD.EXP_DT = CAST('5555-12-31' AS DATE)
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.RO_PO_TYPE_IND = 'N'

WHERE
    POL.CMPL_IND = 1
    AND POL.CMPL_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND CURRENT_DATE-1
    AND POL.PRFCT_ORD_HIT_SORT_KEY <> 99

    AND C.PRIM_SHIP_FACILITY_ID <> POL.SHIP_FACILITY_ID
    AND M.PBU_NBR IN ('01', '03')
    AND M.MKT_AREA_NBR <> '04'

UNION ALL

SELECT
    CAST('FCDD' AS CHAR(4)) AS METRIC_TYPE
    , OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , POL.FPDD_CMPL_IND AS COMPLETE_IND
    , POL.FPDD_CMPL_DT AS COMPLETE_DT
    , CMPL_CAL.MONTH_DT AS COMPLETE_MTH
    , POL.FPDD_NO_STK_DT AS NO_STOCK_DATE

    , POL.MATL_ID
    , M.MATL_NO_8 || ' - ' || M.DESCR AS MATL_DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , CASE
        WHEN M.PBU_NBR = '01'
            THEN M.MKT_CTGY_MKT_AREA_NBR
        ELSE M.MKT_CTGY_MKT_GRP_NBR
        END AS CATEGORY_CD
    , CASE
        WHEN M.PBU_NBR = '01'
            THEN M.MKT_CTGY_MKT_AREA_NAME
        ELSE M.MKT_CTGY_MKT_GRP_NAME
        END AS CATEGORY_NM
    , CASE
        WHEN M.PBU_NBR = '01'
            THEN M.MKT_CTGY_PROD_GRP_NAME
        ELSE M.TIERS
        END AS TIER
    , M.EXT_MATL_GRP_ID
    , M.MATL_PRTY

    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME
    , POL.SHIP_TO_CUST_ID
    , C.CUST_NAME AS SHIP_TO_CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , CAST(CASE 
        WHEN C.SALES_ORG_CD IN ('N302', 'N312', 'N322') OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD = '32')
            THEN 'OE'
        ELSE 'REPL'
        END AS VARCHAR(4)) OE_REPL_IND
    , CAST(CASE 
        WHEN OE_REPL_IND = 'OE'
            THEN 'OEM'
        WHEN OE_REPL_IND = 'REPL'
            THEN 'Replacement'
        ELSE OE_REPL_IND
        END AS VARCHAR(25)) OE_REPL_DESC
    , C.PRIM_SHIP_FACILITY_ID
    , F.FACILITY_ID
    , F.FACILITY_NAME
    , POL.DELIV_PRTY_ID
    , POL.DELIV_BLK_IND
    , POL.CREDIT_HOLD_FLG
    , POL.NUM_DELIV_LINES
    , POL.CAN_REJ_REAS_ID
    , OD.CANCEL_DT
    , POL.PO_TYPE_ID
    , POL.CANCEL_IND
    , POL.CUST_GRP2_CD
    , POL.SHIP_COND_ID
    , POL.TMS_CD
    , POL.SPCL_PROC_ID
    , POL.MAX_CARR_SCAC_ID
    , OD.ORDER_DT
    , OD.ORDER_CRT_TM
    , OD.ORDER_LN_CRT_DT
    , OD.ORDER_LN_CRT_TM
    , OD.FC_MATL_AVL_DT AS METRIC_FMAD
    , POL.FCPGI_DT AS METRIC_FPGI
    , POL.FRST_PROM_DELIV_DT AS METRIC_DT

    , POL.REQ_DELIV_DT AS FRDD
    , POL.FRST_PROM_DELIV_DT AS FCDD
    , POL.MAX_DELIV_NOTE_CREA_DT
    , POL.MAX_EDI_DELIV_DT
    , POL.MAX_SAP_DELIV_DT
    , POL.ACTL_DELIV_DT
    , POL.CUST_APPT_DT

    , ZEROIFNULL(POL.ORIG_ORD_QTY) AS ORIG_ORDER_QTY
    , ZEROIFNULL(POL.CANCEL_QTY) AS CANCEL_QTY
    , ZEROIFNULL(POL.FPDD_ORD_QTY) AS ORDER_QTY
    , ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY) AS HIT_QTY
    , ZEROIFNULL(POL.FPDD_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY) AS ONTIME_QTY
    , ZEROIFNULL(POL.DELIV_FPDD_LATE_QTY) AS DELIV_LATE_QTY
    , ZEROIFNULL(POL.DELIV_FPDD_ONTIME_QTY) AS DELIV_ONTIME_QTY
    , ZEROIFNULL(POL.FPDD_COMMIT_ONTIME_QTY) AS COMMIT_ONTIME_QTY
    , ZEROIFNULL(POL.REL_FPDD_LATE_QTY) AS REL_LATE_QTY
    , ZEROIFNULL(POL.REL_FPDD_ONTIME_QTY) AS REL_ONTIME_QTY
    , ZEROIFNULL(POL.NE_FPDD_HIT_RT_QTY) AS RETURN_HIT_QTY
    , ZEROIFNULL(POL.NE_FPDD_HIT_CL_QTY) AS CLAIM_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_FP_QTY) AS FREIGHT_POLICY_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_CARR_QTY) + ZEROIFNULL(POL.OT_FPDD_HIT_WI_QTY) AS PHYS_LOG_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_MB_QTY) AS MAN_BLK_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_CH_QTY) AS CREDIT_HOLD_HIT_QTY
    , ZEROIFNULL(POL.IF_FPDD_HIT_NS_QTY) AS NO_STOCK_HIT_QTY
    , ZEROIFNULL(POL.IF_FPDD_HIT_CO_QTY) AS CANCEL_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_CG_QTY) AS CUST_GEN_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_CG_99_QTY) AS MAN_REL_CUST_GEN_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_99_QTY) AS MAN_REL_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_LO_QTY) AS OTHER_HIT_QTY

FROM NA_BI_VWS.PRFCT_ORD_LINE POL

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CMPL_CAL
        ON CMPL_CAL.DAY_DATE = POL.FPDD_CMPL_DT
        AND CMPL_CAL.DAY_DATE < CURRENT_DATE

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = POL.MATL_ID
        AND M.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
        AND M.MATL_TYPE_ID = 'PCTL'

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = POL.SHIP_FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = POL.ORDER_FISCAL_YR
        AND OD.ORDER_ID = POL.ORDER_ID
        AND OD.ORDER_LINE_NBR = POL.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = 1
        AND OD.EXP_DT = CAST('5555-12-31' AS DATE)
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.RO_PO_TYPE_IND = 'N'

WHERE
    POL.FPDD_CMPL_IND = 1
    AND POL.FRST_PROM_DELIV_DT IS NOT NULL
    AND POL.FPDD_CMPL_DT BETWEEN CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE) AND CURRENT_DATE-1
    AND POL.PRFCT_ORD_FPDD_HIT_SORT_KEY <> 99
    
    AND C.PRIM_SHIP_FACILITY_ID <> POL.SHIP_FACILITY_ID
    AND M.PBU_NBR IN ('01', '03')
    AND M.MKT_AREA_NBR <> '04'

    ) Q

GROUP BY
    Q.METRIC_TYPE
    , Q.COMPLETE_MTH
    , Q.MATL_ID
    , Q.MATL_DESCR
    , Q.PBU_NBR
    , Q.PBU_NAME
    , Q.CATEGORY_CD
    , Q.CATEGORY_NM
    , Q.TIER
    , Q.MATL_PRTY

    , Q.SALES_ORG_CD
    , Q.SALES_ORG_NAME
    , Q.DISTR_CHAN_CD
    , Q.DISTR_CHAN_NAME
    , Q.CUST_GRP_ID
    , Q.CUST_GRP_NAME
    , Q.OWN_CUST_ID
    , Q.OWN_CUST_NAME
    , Q.OE_REPL_IND
    , Q.OE_REPL_DESC

    , Q.PRIM_SHIP_FACILITY_ID
    , Q.FACILITY_ID
    , Q.FACILITY_NAME
    , Q.DELIV_PRTY_ID

    --, Q.METRIC_FMAD
    --, Q.METRIC_FPGI
    --, Q.METRIC_DT

ORDER BY
    Q.METRIC_TYPE
    , Q.SALES_ORG_CD
    , Q.DISTR_CHAN_CD
    , Q.CUST_GRP_ID
    , Q.OWN_CUST_ID
    , Q.OE_REPL_IND

    , Q.COMPLETE_MTH
    , Q.PBU_NBR
    , Q.MATL_ID

    , Q.PRIM_SHIP_FACILITY_ID
    , Q.FACILITY_ID
    , Q.DELIV_PRTY_ID
