WITH WILL_CALL_PHYS_LOG (
    ORDER_FISCAL_YR
    , ORDER_ID
    , ORDER_LINE_NBR

    , SHIP_TO_CUST_ID
    , SHIP_TO_CUST_NAME
    , OWN_CUST_ID
    , OWN_CUST_NAME

    , MATL_ID
    , MATL_DESCR
    , PBU_NBR
    , PBU_NAME
    , CATEGORY_CD
    , CATEGORY_NM
    , TIER

    , SHIP_FACILITY_ID
    , SHIP_FACILITY_NAME
    
    , SHIP_COND_ID
    , ACTL_DELIV_DT

    , FRDD_FMAD
    , FRDD_FPGI
    , FRDD

    , FCDD_FMAD
    , FCDD_FPGI
    , FCDD

    , FRDD_PHYS_LOG_HIT_QTY

    , FCDD_PHYS_LOG_HIT_QTY
) AS (

SELECT
    OTD.ORDER_FISCAL_YR
    , OTD.ORDER_ID
    , OTD.ORDER_LINE_NBR

    , OTD.SHIP_TO_CUST_ID
    , OTD.SHIP_TO_CUST_NAME
    , OTD.OWN_CUST_ID
    , OTD.OWN_CUST_NAME

    , OTD.MATL_ID
    , OTD.MATL_DESCR
    , OTD.PBU_NBR
    , OTD.PBU_NAME
    , OTD.CATEGORY_CD
    , OTD.CATEGORY_NM
    , OTD.TIER

    , OTD.SHIP_FACILITY_ID
    , OTD.SHIP_FACILITY_NAME
    
    , OTD.SHIP_COND_ID
    , MAX(OTD.ACTL_DELIV_DT) AS ACTL_DELIV_DT

    , MAX(CASE WHEN OTD.METRIC_TYPE = 'FRDD' THEN OTD.METRIC_FMAD END) AS FRDD_FMAD
    , MAX(CASE WHEN OTD.METRIC_TYPE = 'FRDD' THEN OTD.METRIC_FPGI END) AS FRDD_FPGI
    , OTD.FRDD

    , MAX(CASE WHEN OTD.METRIC_TYPE = 'FCDD' THEN OTD.METRIC_FMAD END) AS FCDD_FMAD
    , MAX(CASE WHEN OTD.METRIC_TYPE = 'FCDD' THEN OTD.METRIC_FPGI END) AS FCDD_FPGI
    , OTD.FCDD

    , MAX(CASE WHEN OTD.METRIC_TYPE = 'FRDD' THEN OTD.PHYS_LOG_HIT_QTY END) AS FRDD_PHYS_LOG_HIT_QTY

    , MAX(CASE WHEN OTD.METRIC_TYPE = 'FCDD' THEN OTD.PHYS_LOG_HIT_QTY END) AS FCDD_PHYS_LOG_HIT_QTY
    
FROM (

SELECT
    CAST('FRDD' AS CHAR(4)) AS METRIC_TYPE
    , ODS.ORDER_FISCAL_YR
    , ODS.ORDER_ID
    , ODS.ORDER_LINE_NBR
    , POL.CMPL_IND AS COMPLETE_IND
    , POL.CMPL_DT AS COMPLETE_DT
    , COMPLETE_DT - (EXTRACT(DAY FROM COMPLETE_DT) - 1) AS COMPLETE_MTH
    , POL.NO_STK_DT AS NO_STOCK_DATE
    , NO_STOCK_DATE - (EXTRACT(DAY FROM NO_STOCK_DATE) - 1) AS NO_STOCK_MONTH

    , POL.MATL_ID
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , MATL.PBU_NBR
    , MATL.PBU_NAME
    , CASE
        WHEN MATL.PBU_NBR = '01'
            THEN MATL.MKT_CTGY_MKT_AREA_NBR
        ELSE MATL.MKT_CTGY_MKT_GRP_NBR
        END AS CATEGORY_CD
    , CASE
        WHEN MATL.PBU_NBR = '01'
            THEN MATL.MKT_CTGY_MKT_AREA_NAME
        ELSE MATL.MKT_CTGY_MKT_GRP_NAME
        END AS CATEGORY_NM
    , CASE
        WHEN MATL.PBU_NBR = '01'
            THEN MATL.MKT_CTGY_PROD_GRP_NAME
        ELSE MATL.TIERS
        END AS TIER
    , MATL.EXT_MATL_GRP_ID
    , MATL.MATL_PRTY

    , CUST.SALES_ORG_CD
    , CUST.SALES_ORG_NAME
    , CUST.DISTR_CHAN_CD
    , CUST.DISTR_CHAN_NAME
    , CUST.CUST_GRP_ID
    , CUST.CUST_GRP_NAME
    , POL.SHIP_TO_CUST_ID
    , CUST.CUST_NAME AS SHIP_TO_CUST_NAME
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    , CUST.TIRE_CUST_TYP_CD
    , POL.SHIP_FACILITY_ID AS SHIP_FACILITY_ID
    , FAC.FACILITY_NAME AS SHIP_FACILITY_NAME
    , POL.DELIV_PRTY_ID
    , POL.DELIV_BLK_IND
    , POL.CREDIT_HOLD_FLG
    , POL.NUM_DELIV_LINES
    , POL.CAN_REJ_REAS_ID
    , POL.PO_TYPE_ID
    , POL.CANCEL_IND
    , POL.CUST_GRP_ID
    , POL.CUST_GRP2_CD
    , POL.SHIP_COND_ID
    , POL.A_IND
    , POL.R_IND
    , POL.SPCL_PROC_ID
    , POL.MAX_CARR_SCAC_ID
    , POL.ORDER_DT
    , POL.OL_DT
    , POL.FMAD_DT AS METRIC_FMAD
    , POL.FPGI_DT AS METRIC_FPGI
    , POL.REQ_DELIV_DT AS METRIC_DT

    , POL.REQ_DELIV_DT AS FRDD
    , POL.FRST_PROM_DELIV_DT AS FCDD
    , POL.MAX_DELIV_NOTE_CREA_DT
    , POL.MAX_EDI_DELIV_DT
    , POL.MAX_SAP_DELIV_DT
    , POL.ACTL_DELIV_DT
    , POL.CUST_APPT_DT

    , ZEROIFNULL(POL.ORIG_ORD_QTY) AS ORIG_ORDER_QTY
    , ZEROIFNULL(POL.CANCEL_QTY) AS CANCEL_QTY
    , ZEROIFNULL(POL.CURR_ORD_QTY) AS ORDER_QTY
    , ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY) AS HIT_QTY
    , ZEROIFNULL(POL.CURR_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY) AS ONTIME_QTY
    , ZEROIFNULL(POL.REL_LATE_QTY) AS REL_LATE_QTY
    , ZEROIFNULL(POL.REL_ONTIME_QTY) AS REL_ONTIME_QTY
    , ZEROIFNULL(POL.COMMIT_ONTIME_QTY) AS COMMIT_ONTIME_QTY
    , ZEROIFNULL(POL.DELIV_LATE_QTY) AS DELIV_LATE_QTY
    , ZEROIFNULL(POL.DELIV_ONTIME_QTY) AS DELIV_ONTIME_QTY
    , ZEROIFNULL(POL.NE_HIT_RT_QTY) AS RETURN_HIT_QTY
    , ZEROIFNULL(POL.NE_HIT_CL_QTY) AS CLAIM_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_FP_QTY) AS FREIGHT_POLICY_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_CARR_PICKUP_QTY) + ZEROIFNULL(POL.OT_HIT_WI_QTY) AS PHYS_LOG_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_MB_QTY) AS MAN_BLK_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_CH_QTY) AS CREDIT_HOLD_HIT_QTY
    , ZEROIFNULL(POL.IF_HIT_NS_QTY) AS NO_STOCK_HIT_QTY
    , ZEROIFNULL(POL.IF_HIT_CO_QTY) AS CANCEL_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_CG_QTY) AS CUST_GEN_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_CG_99_QTY) AS MAN_REL_CUST_GEN_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_99_QTY) AS MAN_REL_HIT_QTY
    , ZEROIFNULL(POL.OT_HIT_LO_QTY) AS OTHER_HIT_QTY

FROM NA_BI_VWS.PRFCT_ORD_LINE POL

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID
        --AND CUST.OWN_CUST_ID = '00A0009994'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = POL.MATL_ID
        AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
        AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FAC
        ON FAC.FACILITY_ID = POL.SHIP_FACILITY_ID
        AND FAC.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND FAC.DISTR_CHAN_CD = '81'
        AND FAC.FACILITY_ID IN ('N6D3', 'N526')

    INNER JOIN NA_BI_VWS.ORDER_DETAIL ODS
        ON ODS.ORDER_FISCAL_YR >= CAST(EXTRACT(YEAR FROM (CURRENT_DATE - 1)) - 2 AS CHAR(4))
        AND ODS.ORDER_ID = POL.ORDER_ID
        AND ODS.ORDER_LINE_NBR = POL.ORDER_LINE_NBR
        AND ODS.SCHED_LINE_NBR = 1
        AND ODS.EXP_DT = DATE '5555-12-31'
        AND ODS.ORDER_CAT_ID = 'C'
        AND ODS.RO_PO_TYPE_IND = 'N'

WHERE
    POL.CMPL_IND = 1
    AND POL.CMPL_DT BETWEEN CURRENT_DATE-28 AND CURRENT_DATE-1
    AND POL.PRFCT_ORD_HIT_SORT_KEY <> 99
    AND PHYS_LOG_HIT_QTY > 0

UNION ALL

SELECT
    CAST('FCDD' AS CHAR(4)) AS METRIC_TYPE
    , ODS.ORDER_FISCAL_YR
    , ODS.ORDER_ID
    , ODS.ORDER_LINE_NBR

    , POL.FPDD_CMPL_IND AS COMPLETE_IND
    , POL.FPDD_CMPL_DT AS COMPLETE_DT
    , COMPLETE_DT - (EXTRACT(DAY FROM COMPLETE_DT) - 1) AS COMPLETE_MTH
    , POL.FPDD_NO_STK_DT AS NO_STOCK_DATE
    , NO_STOCK_DATE - (EXTRACT(DAY FROM NO_STOCK_DATE) - 1) AS NO_STOCK_MONTH

    , POL.MATL_ID
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , MATL.PBU_NBR
    , MATL.PBU_NAME
    , CASE
        WHEN MATL.PBU_NBR = '01'
            THEN MATL.MKT_CTGY_MKT_AREA_NBR
        ELSE MATL.MKT_CTGY_MKT_GRP_NBR
        END AS CATEGORY_CD
    , CASE
        WHEN MATL.PBU_NBR = '01'
            THEN MATL.MKT_CTGY_MKT_AREA_NAME
        ELSE MATL.MKT_CTGY_MKT_GRP_NAME
        END AS CATEGORY_NM
    , CASE
        WHEN MATL.PBU_NBR = '01'
            THEN MATL.MKT_CTGY_PROD_GRP_NAME
        ELSE MATL.TIERS
        END AS TIER
    , MATL.EXT_MATL_GRP_ID
    , MATL.MATL_PRTY

    , CUST.SALES_ORG_CD
    , CUST.SALES_ORG_NAME
    , CUST.DISTR_CHAN_CD
    , CUST.DISTR_CHAN_NAME
    , CUST.CUST_GRP_ID
    , CUST.CUST_GRP_NAME
    , POL.SHIP_TO_CUST_ID
    , CUST.CUST_NAME AS SHIP_TO_CUST_NAME
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    , CUST.TIRE_CUST_TYP_CD
    , POL.SHIP_FACILITY_ID AS SHIP_FACILITY_ID
    , FAC.FACILITY_NAME AS SHIP_FACILITY_NAME
    , POL.DELIV_PRTY_ID
    , POL.DELIV_BLK_IND
    , POL.CREDIT_HOLD_FLG
    , POL.NUM_DELIV_LINES
    , POL.CAN_REJ_REAS_ID
    , POL.PO_TYPE_ID
    , POL.CANCEL_IND
    , POL.CUST_GRP_ID
    , POL.CUST_GRP2_CD
    , POL.SHIP_COND_ID
    , POL.A_IND
    , POL.R_IND
    , POL.SPCL_PROC_ID
    , POL.MAX_CARR_SCAC_ID
    , POL.ORDER_DT

    , POL.OL_DT
    , ODS.FC_MATL_AVL_DT AS METRIC_FMAD
    , POL.FCPGI_DT AS METRIC_FPGI
    , POL.FRST_PROM_DELIV_DT AS METRIC_DT

    , POL.REQ_DELIV_DT AS FRDD
    , POL.FRST_PROM_DELIV_DT AS FCDD
    , POL.MAX_DELIV_NOTE_CREA_DT
    , POL.MAX_EDI_DELIV_DT
    , POL.MAX_SAP_DELIV_DT
    , POL.ACTL_DELIV_DT
    , POL.CUST_APPT_DT

    , ZEROIFNULL(POL.ORIG_ORD_QTY) AS ORIG_ORDER_QTY
    , ZEROIFNULL(POL.CANCEL_QTY) AS CANCEL_QTY
    , ZEROIFNULL(POL.FPDD_ORD_QTY) AS ORDER_QTY
    , ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY) AS HIT_QTY
    , ZEROIFNULL(POL.FPDD_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY) AS ONTIME_QTY
    , ZEROIFNULL(POL.DELIV_FPDD_LATE_QTY) AS DELIV_LATE_QTY
    , ZEROIFNULL(POL.DELIV_FPDD_ONTIME_QTY) AS DELIV_ONTIME_QTY
    , ZEROIFNULL(POL.FPDD_COMMIT_ONTIME_QTY) AS COMMIT_ONTIME_QTY
    , ZEROIFNULL(POL.REL_FPDD_LATE_QTY) AS REL_LATE_QTY
    , ZEROIFNULL(POL.REL_FPDD_ONTIME_QTY) AS REL_ONTIME_QTY
    , ZEROIFNULL(POL.NE_FPDD_HIT_RT_QTY) AS RETURN_HIT_QTY
    , ZEROIFNULL(POL.NE_FPDD_HIT_CL_QTY) AS CLAIM_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_FP_QTY) AS FREIGHT_POLICY_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_CARR_QTY) + ZEROIFNULL(POL.OT_FPDD_HIT_WI_QTY) AS PHYS_LOG_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_MB_QTY) AS MAN_BLK_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_CH_QTY) AS CREDIT_HOLD_HIT_QTY
    , ZEROIFNULL(POL.IF_FPDD_HIT_NS_QTY) AS NO_STOCK_HIT_QTY
    , ZEROIFNULL(POL.IF_FPDD_HIT_CO_QTY) AS CANCEL_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_CG_QTY) AS CUST_GEN_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_CG_99_QTY) AS MAN_REL_CUST_GEN_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_99_QTY) AS MAN_REL_HIT_QTY
    , ZEROIFNULL(POL.OT_FPDD_HIT_LO_QTY) AS OTHER_HIT_QTY

FROM NA_BI_VWS.PRFCT_ORD_LINE POL

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = POL.SHIP_TO_CUST_ID
        --AND CUST.OWN_CUST_ID = '00A0009994'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = POL.MATL_ID
        AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
        AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR FAC
        ON FAC.FACILITY_ID = POL.SHIP_FACILITY_ID
        AND FAC.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND FAC.DISTR_CHAN_CD = '81'
        AND FAC.FACILITY_ID IN ('N6D3', 'N526')

    INNER JOIN NA_BI_VWS.ORDER_DETAIL ODS
        ON ODS.ORDER_FISCAL_YR >= CAST(EXTRACT(YEAR FROM (CURRENT_DATE - 1)) - 2 AS CHAR(4))
        AND ODS.ORDER_ID = POL.ORDER_ID
        AND ODS.ORDER_LINE_NBR = POL.ORDER_LINE_NBR
        AND ODS.SCHED_LINE_NBR = 1
        AND ODS.EXP_DT = DATE '5555-12-31'
        AND ODS.ORDER_CAT_ID = 'C'
        AND ODS.RO_PO_TYPE_IND = 'N'

WHERE
    POL.FPDD_CMPL_IND = 1
    AND POL.FRST_PROM_DELIV_DT IS NOT NULL
    AND POL.FPDD_CMPL_DT BETWEEN CURRENT_DATE-28 AND CURRENT_DATE-1
    AND POL.PRFCT_ORD_FPDD_HIT_SORT_KEY <> 99
    AND PHYS_LOG_HIT_QTY > 0

    ) OTD
    
GROUP BY
    OTD.ORDER_FISCAL_YR
    , OTD.ORDER_ID
    , OTD.ORDER_LINE_NBR

    , OTD.SHIP_TO_CUST_ID
    , OTD.SHIP_TO_CUST_NAME
    , OTD.OWN_CUST_ID
    , OTD.OWN_CUST_NAME

    , OTD.MATL_ID
    , OTD.MATL_DESCR
    , OTD.PBU_NBR
    , OTD.PBU_NAME
    , OTD.CATEGORY_CD
    , OTD.CATEGORY_NM
    , OTD.TIER

    , OTD.SHIP_FACILITY_ID
    , OTD.SHIP_FACILITY_NAME
    
    , OTD.SHIP_COND_ID
    
    , OTD.FRDD
    , OTD.FCDD

)

SELECT
    Q.FISCAL_YR
    , Q.DELIV_ID
    , Q.TM_DELIV_ID
    , Q.FRT_MVMNT_ID
    
    , Q.SAP_BOL_ID
    , Q.MSTR_BOL_ID
    
    , Q.SHIP_TO_CUST_ID
    , Q.SHIP_TO_CUST_NAME
    , Q.OWN_CUST_ID
    , Q.OWN_CUST_NAME
    
    , Q.DELIV_LINE_FACILITY_ID
    , Q.SHIP_FACILITY_NAME
    , Q.SHIP_COND_ID
    
    , Q.QTY_UNIT_MEAS_ID
    , SUM(Q.DELIV_QTY) AS DELIV_QTY
    
/*    , SUM(ZEROIFNULL(Q.FRDD_PHYS_LOG_HIT_QTY)) AS FRDD_PHYS_LOG_HIT_QTY
    , SUM(ZEROIFNULL(Q.FCDD_PHYS_LOG_HIT_QTY)) AS FCDD_PHYS_LOG_HIT_QTY*/
    
    , Q.DELIV_NOTE_CREA_DT
    , Q.PLN_GOODS_MVT_DT
    , Q.ACTL_GOODS_ISS_DT
    --, Q.DELIV_DT
    , Q.ACTL_DELIV_DT
    
    , Q.FRDD
    , Q.FCDD
    
FROM (

SELECT
    DDC.FISCAL_YR
    , DDC.DELIV_ID
    , DDC.DELIV_LINE_NBR
    
    , DDC.ORDER_FISCAL_YR
    , DDC.ORDER_ID
    , DDC.ORDER_LINE_NBR
    
    , XR.FRT_MVMNT_ID
    , XR.FRT_MVMNT_SCHD_ID
    , XR.FRT_MVMNT_STOP_ID
    , XR.TM_DELIV_ID
    
    --, ROW_NUMBER() OVER (PARTITION BY DDC.ORDER_FISCAL_YR, DDC.ORDER_ID, DDC.ORDER_LINE_NBR ORDER BY DDC.DELIV_NOTE_CREA_DT ASC) AS DN_SEQ_ID
    
    , DDC.BILL_LADING_ID AS SAP_BOL_ID
    , FM.BILL_LADING_ID AS MSTR_BOL_ID
    , FMS.BILL_LADING_ID AS STOP_BOL_ID
    
    , DDC.SHIP_TO_CUST_ID
    , CTC.SHIP_TO_CUST_NAME
    , CTC.OWN_CUST_ID
    , CTC.OWN_CUST_NAME
    
    , DDC.SHIP_COND_ID
    
    , DDC.DELIV_LINE_FACILITY_ID
    , DDC.SHIP_PT_ID
    , CTC.SHIP_FACILITY_NAME
    
    , DDC.MATL_ID
    
    , DDC.QTY_UNIT_MEAS_ID
    , DDC.DELIV_QTY
    
    , CTC.FRDD_PHYS_LOG_HIT_QTY
    , CTC.FCDD_PHYS_LOG_HIT_QTY
    
    , DDC.DELIV_NOTE_CREA_DT
    , DDC.DELIV_LINE_CREA_DT
    , DDC.PLN_GOODS_MVT_DT
    , DDC.ACTL_GOODS_ISS_DT
    , DDC.DELIV_DT
    , CTC.ACTL_DELIV_DT

    , CTC.FRDD_FMAD
    , CTC.FRDD_FPGI
    , CTC.FRDD

    , CTC.FCDD_FMAD
    , CTC.FCDD_FPGI
    , CTC.FCDD
    
    , TDC.OWN_TXT
    , TDC.CUST_APPT_DT
    , TDC.CUST_APPT_TM

FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID

    INNER JOIN WILL_CALL_PHYS_LOG CTC
        ON CTC.ORDER_FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND CTC.ORDER_ID = DDC.ORDER_ID
        AND CTC.ORDER_LINE_NBR = DDC.ORDER_LINE_NBR

    INNER JOIN NA_BI_VWS.TM_FRTMV_DLV_XREF_CURR XR
        ON XR.SAP_DELIV_ID_FISCAL_YR = DDC.FISCAL_YR
        AND XR.SAP_DELIV_ID = DDC.DELIV_ID

    INNER JOIN NA_BI_VWS.TM_DELIV_CURR TDC
        ON TDC.TM_DELIV_ID = XR.TM_DELIV_ID
        AND TDC.TM_PLN_SCHD_ID = XR.TM_PLN_SCHD_ID
        AND TDC.TM_DELIV_SPLIT_ID = XR.TM_DELIV_SPLIT_ID
        AND TDC.SAP_DELIV_ID_FISCAL_YR = DDC.FISCAL_YR
        AND TDC.SAP_DELIV_ID = DDC.DELIV_ID

    INNER JOIN NA_BI_VWS.TM_FRT_MVMNT_STOP_CURR FMS
        ON FMS.FRT_MVMNT_ID = XR.FRT_MVMNT_ID
        AND FMS.FRT_MVMNT_SCHD_ID = XR.FRT_MVMNT_SCHD_ID
        AND FMS.FRT_MVMNT_STOP_ID = XR.FRT_MVMNT_STOP_ID
        AND FMS.STOP_TYP_CD = 'DL'
    
    INNER JOIN NA_BI_VWS.TM_FRT_MVMNT_CURR FM
        ON FM.FRT_MVMNT_ID = XR.FRT_MVMNT_ID
        AND FM.FRT_MVMNT_SCHD_ID = XR.FRT_MVMNT_SCHD_ID

WHERE
    DDC.DELIV_LINE_FACILITY_ID IN ('N6D3', 'N526')
    AND DDC.SHIP_COND_ID IN ('00', 'LW')
    AND DDC.DELIV_QTY > 0
    AND DDC.GOODS_ISS_IND = 'Y'

    ) Q

GROUP BY
    Q.FISCAL_YR
    , Q.DELIV_ID
    , Q.TM_DELIV_ID
    , Q.FRT_MVMNT_ID
    
    , Q.SAP_BOL_ID
    , Q.MSTR_BOL_ID

    , Q.SHIP_TO_CUST_ID
    , Q.SHIP_TO_CUST_NAME
    , Q.OWN_CUST_ID
    , Q.OWN_CUST_NAME
    
    , Q.DELIV_LINE_FACILITY_ID
    , Q.SHIP_FACILITY_NAME
    , Q.SHIP_COND_ID
    
    , Q.QTY_UNIT_MEAS_ID
    
    , Q.DELIV_NOTE_CREA_DT
    , Q.PLN_GOODS_MVT_DT
    , Q.ACTL_GOODS_ISS_DT
    --, Q.DELIV_DT
    , Q.ACTL_DELIV_DT
    
    , Q.FRDD
    , Q.FCDD

ORDER BY
    Q.FISCAL_YR
    , Q.DELIV_ID
    , Q.TM_DELIV_ID
    , Q.FRT_MVMNT_ID