SELECT
    ODC.ORDER_ID AS "Order ID",
    ODC.ORDER_LINE_NBR AS "Order Line Nbr",
    
    ODC.MATL_ID AS "Material ID",
    MATL.DESCR AS "Material Description",
    MATL.PBU_NBR || ' - ' || MATL.PBU_NAME AS PBU,
    CUST.TIRE_CUST_TYP_CD AS "Tire Type Customer Code",
    
    ODC.SHIP_TO_CUST_ID AS "Ship To Customer ID",
    CUST.CUST_NAME AS "Ship To Customer Name",
    CUST.OWN_CUST_ID AS "Common Owner ID",
    CUST.OWN_CUST_NAME AS "Common Owner Name",
    
    ODC.SALES_ORG_CD AS "Sales Organization Code",
    SO.SALES_ORG_NAME AS "Sales Organization Name",
    ODC.CUST_GRP_ID AS "Customer Group ID",
    CG.CUST_GRP_NAME AS "Customer Group Name",
    
    ODC.ORDER_DT AS "Order Create Date",
    ODC.FRST_RDD AS FRDD,
    ODC.CANCEL_DT AS "Cancellation Date",
    ODC.REJ_REAS_ID AS "Reason for Rejection ID",
    ODC.REJ_REAS_DESC AS "Reason for Rejection Desc"

FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID 

    LEFT OUTER JOIN GDYR_BI_VWS.NAT_CUST_GRP_EN_CURR CG
        ON CG.CUST_GRP_ID = ODC.CUST_GRP_ID
    
    LEFT OUTER JOIN GDYR_BI_VWS.NAT_SALES_ORG_EN_CURR SO
        ON SO.SALES_ORG_CD = ODC.SALES_ORG_CD

WHERE
    ODC.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
    AND ODC.ORDER_CAT_ID = 'C'
    AND ODC.PO_TYPE_ID <> 'RO'
    AND ODC.CANCEL_DT = ( CURRENT_DATE - 1 )
    AND ( CASE
        WHEN ODC.REJ_REAS_ID = 'Z3' AND ODC.SALES_ORG_CD IN ( 'N302', 'N312', 'N322' )
            THEN 0
        WHEN ODC.CUST_GRP_ID = '3R' AND ODC.REJ_REAS_ID LIKE 'C%'
            THEN 0
        WHEN ODC.REJ_REAS_ID = 'Z2' AND CUST.OWN_CUST_ID IN ( '00A0000632', '00A0003088', '00A0003149', '00A0008921', 
                '00A0009004', '00B1164474', '00B1164508', '00B1165232', '00B1165240', '00B1192657', '00B1225952', '00B3001635' )
            THEN 0
        ELSE 1
    END ) = 1

GROUP BY
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    
    ODC.MATL_ID,
    MATL.DESCR,
    PBU,
    CUST.TIRE_CUST_TYP_CD,
    
    ODC.SHIP_TO_CUST_ID,
    CUST.CUST_NAME,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,
    
    ODC.SALES_ORG_CD,
    SO.SALES_ORG_NAME,
    ODC.CUST_GRP_ID,
    CG.CUST_GRP_NAME,
    
    ODC.ORDER_DT,
    ODC.FRST_RDD,
    ODC.CANCEL_DT,
    ODC.REJ_REAS_ID,
    ODC.REJ_REAS_DESC

ORDER BY
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR
