SELECT
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    ODC.SCHED_LINE_NBR,
    CASE
        WHEN OOSL.ORDER_LINE_NBR IS NULL
            THEN 'Open'
        ELSE 'Closed'
    END AS OPEN_ORDER_IND,
    
    ODC.SHIP_TO_CUST_ID,
    CUST.CUST_NAME AS SHIP_TO_CUST_NAME,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,
    ODC.SALES_ORG_CD,
    SO.NAME AS SALES_ORG_NAME,
    ODC.DISTR_CHAN_CD,
    DC.NAME AS DISTR_CHAN_NAME,
    ODC.CO_CD,
    COMP.NAME AS CO_CD_NAME,
    ODC.DIV_CD,
    
    ODC.MATL_ID,
    ODC.ITEM_CAT_ID,
    
    ODC.FACILITY_ID,
    ODC.SHIP_PT_ID,
    
    NULLIF( ODC.ORDER_TYPE_ID, ' ' ) AS ORDER_TYPE_ID,
    NULLIF( ODC.ORDER_CAT_ID, ' ' ) AS ORDER_CAT_ID,
    NULLIF( ODC.PO_TYPE_ID, ' ' ) AS PO_TYPE_ID,
    NULLIF( ODC.DELIV_BLK_CD, ' ' ) AS DELIV_BLK_CD,
    NULLIF( ODC.REJ_REAS_ID, ' ' ) AS REJ_REAS_ID,
    NULLIF( ODC.DELIV_PRTY_ID, ' ' ) AS DELIV_PRTY_ID,
    NULLIF( ODC.ROUTE_ID, ' ' ) AS ROUTE_ID,
    NULLIF( ODC.DELIV_GRP_CD, ' ' ) AS DELIV_GRP_CD,
    NULLIF( ODC.SPCL_PROC_ID, ' ' ) AS SPCL_PROC_ID,
    NULLIF( ODC.CUST_GRP2_CD, ' ' ) AS CUST_GRP2_CD,
    
    CASE WHEN ODC.CANCEL_IND = 'Y' THEN 'Y' END AS CANCEL_IND,
    CASE WHEN ODC.RETURN_IND = 'Y' THEN 'Y' END AS RETURN_IND,
    CASE WHEN ODC.RO_PO_TYPE_IND = 'Y' THEN 'Y' END AS RO_PO_TYPE_IND,
    CASE WHEN ODC.DELIV_BLK_IND = 'Y' THEN 'Y' END AS DELIV_BLK_IND,
    
    ODC.QTY_UNIT_MEAS_ID,
    ODC.ORDER_QTY,
    ODC.CNFRM_QTY,
    OOSL.OPEN_CNFRM_QTY,
    OOSL.UNCNFRM_QTY,
    OOSL.BACK_ORDER_QTY,
    
    ODC.ORDER_DT,
    CASE
        WHEN COALESCE( ODC.CUST_RDD, ODC.FRST_RDD ) < ODC.ORDER_DT
            THEN ODC.ORDER_DT
        ELSE COALESCE( ODC.CUST_RDD, ODC.FRST_RDD )
    END AS ORDD,
    ODC.FRST_RDD AS FRDD,
    ODC.FRST_MATL_AVL_DT AS FRDD_FMAD,
    ODC.FRST_PLN_GOODS_ISS_DT AS FRDD_FPGI,
    CASE
        WHEN ODC.FRST_RDD < ODC.FRST_PROM_DELIV_DT
            THEN ODC.FRST_RDD
        ELSE ODC.FRST_PROM_DELIV_DT
    END AS FCDD,
    FCDD - ( FRDD - FRDD_FMAD ) AS FCDD_FMAD,
    FCDD - ( FRDD - FRDD_FPGI ) AS FCDD_FPGI,
    
    ODC.PLN_TRANSP_PLN_DT,
    ODC.PLN_MATL_AVL_DT,
    ODC.PLN_LOAD_DT,
    ODC.PLN_GOODS_ISS_DT,
    ODC.PLN_DELIV_DT
    
FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC
    
    LEFT OUTER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOSL
        ON OOSL.ORDER_ID = ODC.ORDER_ID
        AND OOSL.ORDER_LINE_NBR = ODC.ORDER_LINE_NBR
        AND OOSL.SCHED_LINE_NBR = ODC.SCHED_LINE_NBR
        AND ( OOSL.OPEN_CNFRM_QTY > 0 OR OOSL.UNCNFRM_QTY > 0 OR OOSL.BACK_ORDER_QTY > 0 )

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID
        AND MATL.PBU_NBR IN ( '01', '03' )

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID

    LEFT OUTER JOIN GDYR_VWS.SALES_ORG SO
        ON SO.SALES_ORG_CD = ODC.SALES_ORG_CD
        AND CURRENT_DATE BETWEEN SO.EFF_DT AND SO.EXP_DT
        AND SO.SBU_ID = 2
        AND SO.ORIG_SYS_ID = 2
        AND SO.SRC_SYS_ID = 2
        AND SO.LANG_ID = 'E'

    LEFT OUTER JOIN GDYR_VWS.DISTR_CHAN DC
        ON DC.DISTR_CHAN_CD = ODC.DISTR_CHAN_CD
        AND DC.ORIG_SYS_ID = 2
        AND DC.SRC_SYS_ID = 2
        AND DC.SBU_ID = 2
        AND CURRENT_DATE BETWEEN DC.EFF_DT AND DC.EXP_DT

    LEFT OUTER JOIN GDYR_VWS.CO COMP
        ON COMP.CO_CD = ODC.CO_CD
        AND COMP.ORIG_SYS_ID = 2
        AND COMP.SRC_SYS_ID = 2
        AND COMP.SBU_ID = 2
        AND CURRENT_DATE BETWEEN COMP.EFF_DT AND COMP.EXP_DT

WHERE
    ODC.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
    AND ODC.ORDER_CAT_ID = 'C'
    AND ODC.RO_PO_TYPE_IND = 'N'
    AND ODC.CUST_GRP2_CD = 'TLB'
    AND ODC.ORDER_DT >= CAST( '2013-03-05' AS DATE )
    