SELECT
    DDC.FISCAL_YR AS DELIV_FISCAL_YR
    , DDC.DELIV_ID
    , COUNT(DDC.DELIV_LINE_NBR) AS DELIV_LINE_CNT
    , COUNT(DISTINCT DDC.ORDER_FISCAL_YR || DDC.ORDER_ID || DDC.ORDER_LINE_NBR) AS ORDER_LINE_CNT
    , COUNT(DISTINCT DDC.MATL_ID) AS MATL_ID_CNT
    
    , NDDC.SRC_CRT_TS AS DN_SRC_CRT_TS
    
    , CUST.SHIP_TO_CUST_ID
    , CUST.SHIP_TO_CUST_NO
	, CUST.CUST_NAME AS SHIP_TO_CUST_NAME
    , CUST.SHIP_TO_CUST_ID || ' - ' || CUST.CUST_NAME AS SHIP_TO_CUST

    , CUST.OWN_CUST_ID
	, CUST.OWN_CUST_NAME
	, CUST.OWN_CUST_ID || ' - ' || CUST.OWN_CUST_NAME AS OWN_CUST
    
    , CUST.SALES_ORG_CD || ' - ' || CUST.SALES_ORG_NAME AS SALES_ORG
	, CUST.DISTR_CHAN_CD || ' - ' || CUST.DISTR_CHAN_NAME AS DISTR_CHAN
	, CUST.CUST_GRP_ID || ' - ' || CUST.CUST_GRP_NAME AS CUST_GRP
    , CUST.PRIM_SHIP_FACILITY_ID
    , CUST.TIRE_CUST_TYP_CD AS OE_REPL_IND
    
    , DDC.DELIV_LINE_FACILITY_ID AS FACILITY_ID
    , DF.FACILITY_NAME
    , DDC.SHIP_PT_ID
    , SP.FACILITY_NAME AS SHIP_PT_DESC
    
    , DDC.GOODS_ISS_IND
    , DDC.DELIV_PRTY_ID
    , DDC.BILL_LADING_ID
    , DDC.SHIP_COND_ID
    , DDC.RTG_ID AS ROUTE_ID
    , DDC.TERMS_ID
    , DDC.UNLD_PT_CD
    , DDC.SPCL_PROC_ID
    , DDC.PRM_SHIP_CARR_CD
    , DDC.TRANSP_VEH_NO
    , CASE
        WHEN DDC.SRC_CRT_USR_ID LIKE ANY ('LD%', 'COWD%')
            THEN 'SYSTEM'
        ELSE 'USER'
        END AS DELIVERY_CREATOR_TYPE
    , MAX(CASE
        WHEN ODS.ORDER_CREATOR LIKE ANY ('LD%', 'COWD%')
            THEN 'SYSTEM'
        END) AS ORDER_CREATOR_SYSTEM
    , MAX(CASE
        WHEN ODS.ORDER_CREATOR NOT LIKE ANY ('LD%', 'COWD%')
            THEN 'USER'
        END) AS ORDER_CREATOR_USER

    , DDC.DELIV_NOTE_CREA_DT
    , DDC.DELIV_LINE_CREA_DT
    , DDC.TRANSP_PLN_DT
    , DDC.PICK_DT
    , DDC.LOAD_DT
    , DDC.PLN_GOODS_MVT_DT
    , DDC.ACTL_GOODS_ISS_DT
    , DDC.DELIV_DT
    
    , DDC.QTY_UNIT_MEAS_ID AS QTY_UOM
    , SUM(DDC.DELIV_QTY) AS DELIV_QTY
    
    , DDC.WT_UNIT_MEAS_ID AS WT_UOM
    , SUM(DDC.GROSS_WT) AS GROSS_WT
    , SUM(DDC.NET_WT) AS NET_WT
    
    , DDC.VOL_UNIT_MEAS_ID AS VOL_UOM
    , SUM(DDC.VOL) AS VOL
    , SUM((CAST(CASE MATL.PBU_NBR || MATL.MKT_AREA_NBR
        WHEN '0101' THEN 0.75
        WHEN '0108' THEN 0.80
        WHEN '0305' THEN 1.20
        WHEN '0314' THEN 1.20
        WHEN '0406' THEN 1.20
        WHEN '0507' THEN 0.75
        WHEN '0711' THEN 0.75
        WHEN '0712' THEN 0.75
        WHEN '0803' THEN 1.20
        WHEN '0923' THEN 0.75
        ELSE 1
    END AS DECIMAL(15, 3)) * MATL.UNIT_VOL) * DDC.DELIV_QTY) AS COMPRESSED_VOL

FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR MATL
        ON MATL.MATL_ID = DDC.MATL_ID
        AND MATL.PBU_NBR IN ('01', '03')
        AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')
    
    INNER JOIN NA_BI_VWS.NAT_DELIV_DOC_CURR NDDC
        ON NDDC.FISCAL_YR = DDC.FISCAL_YR
        AND NDDC.DELIV_DOC_ID = DDC.DELIV_ID

    INNER JOIN NA_BI_VWS.ORD_DTL_SMRY ODS
        ON ODS.ORDER_FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND ODS.ORDER_ID = DDC.ORDER_ID
        AND ODS.ORDER_LINE_NBR = DDC.ORDER_LINE_NBR
        AND ODS.ORDER_CAT_ID = 'C'
        AND ODS.PO_TYPE_ID <> 'RO'
        AND ODS.CUST_GRP2_CD = 'TLB'
        AND ODS.ORDER_DT >= DATE '2013-01-01'

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM_CURR SDIC
        ON SDIC.FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND SDIC.SLS_DOC_ID = DDC.ORDER_ID
        AND SDIC.SLS_DOC_ITM_ID = DDC.ORDER_LINE_NBR
        -- AND SDIC.DELIV_PRTY_CD = '12'
        -- AND SDIC.DELIV_GRP_ID > 0

    LEFT OUTER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR DF
        ON DF.FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID
    
    LEFT OUTER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR SP
        ON SP.FACILITY_ID = DDC.SHIP_PT_ID

WHERE
    DDC.DELIV_NOTE_CREA_DT >= DATE '2014-01-01'
    AND DDC.DELIV_CAT_ID = 'J'
    AND DDC.SHIP_COND_ID IN ('ST', 'PT')
    AND DDC.DELIV_QTY > 0

GROUP BY
    DDC.FISCAL_YR
    , DDC.DELIV_ID
    
    , NDDC.SRC_CRT_TS
    
    , CUST.SHIP_TO_CUST_ID
    , CUST.SHIP_TO_CUST_NO
	, CUST.CUST_NAME
    , CUST.SHIP_TO_CUST_ID || ' - ' || CUST.CUST_NAME

    , CUST.OWN_CUST_ID
	, CUST.OWN_CUST_NAME
	, CUST.OWN_CUST_ID || ' - ' || CUST.OWN_CUST_NAME
    
    , CUST.SALES_ORG_CD || ' - ' || CUST.SALES_ORG_NAME
	, CUST.DISTR_CHAN_CD || ' - ' || CUST.DISTR_CHAN_NAME
	, CUST.CUST_GRP_ID || ' - ' || CUST.CUST_GRP_NAME
    , CUST.PRIM_SHIP_FACILITY_ID
    , CUST.TIRE_CUST_TYP_CD
    
    , DDC.DELIV_LINE_FACILITY_ID
    , DF.FACILITY_NAME
    , DDC.SHIP_PT_ID
    , SP.FACILITY_NAME
    
    , DDC.GOODS_ISS_IND
    , DDC.DELIV_PRTY_ID
    , DDC.BILL_LADING_ID
    , DDC.SHIP_COND_ID
    , DDC.RTG_ID
    , DDC.TERMS_ID
    , DDC.UNLD_PT_CD
    , DDC.SPCL_PROC_ID
    , DDC.PRM_SHIP_CARR_CD
    , DDC.TRANSP_VEH_NO
    , DELIVERY_CREATOR_TYPE
    , ORDER_CREATOR_TYPE
    
    , DDC.DELIV_NOTE_CREA_DT
    , DDC.DELIV_LINE_CREA_DT
    , DDC.TRANSP_PLN_DT
    , DDC.PICK_DT
    , DDC.LOAD_DT
    , DDC.PLN_GOODS_MVT_DT
    , DDC.ACTL_GOODS_ISS_DT
    , DDC.DELIV_DT
    
    , DDC.QTY_UNIT_MEAS_ID
    
    , DDC.WT_UNIT_MEAS_ID
    
    , DDC.VOL_UNIT_MEAS_ID


-- Query validation -- should return zero records to pass
QUALIFY
    COUNT(*) OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID) > 1

    