SELECT 
    CDI.OBJ_CLS_CD
    , CDI.OBJ_VAL_ID
    , CDI.CHG_DOC_ID
    , CDI.SAP_TBL_NM
    , CDI.SAP_COL_NM
    , CDI.CHG_TBL_REC_ID
    , CDI.CHG_TYP_CD
    , CDI.DOC_ID
    , CDI.DOC_ITM_ID
    , CDI.TXT_CHG_IND
    , CDI.OLD_UNIT_QTY
    , CDI.NEW_UNIT_QTY
    , CDI.OLD_CRNCY_ID
    , CDI.NEW_CRNCY_ID
    , CDI.OLD_VAL_TXT
    , CDI.NEW_VAL_TXT
    , CDI.SRC_CRT_DT
    , CDI.SRC_CRT_TM
    , CDI.SRC_CRT_TS
    , CH.SRC_CRT_USR_ID
    , CH.SAP_TRANS_CD

FROM GDYR_BI_VWS.CHG_DOC_ITM CDI

    INNER JOIN GDYR_BI_VWS.CHG_DOC CH
        ON CH.ORIG_SYS_ID = CDI.ORIG_SYS_ID
        AND CH.OBJ_CLS_CD = CDI.OBJ_CLS_CD
        AND CH.OBJ_VAL_ID = CDI.OBJ_VAL_ID
        AND CH.CHG_DOC_ID = CDI.CHG_DOC_ID

WHERE 
    CDI.ORIG_SYS_ID = 2
    AND CDI.OBJ_CLS_CD = 'VERKBELEG'
    AND CDI.SRC_CRT_DT BETWEEN DATE '2014-12-01' AND CURRENT_DATE-1
    AND CDI.SAP_TBL_NM = 'VBAP'
    AND CDI.SAP_COL_NM = 'LPRIO'

