SELECT
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    , OOL.SCHED_LINE_NBR
    
    , OOL.ORDER_ID || '-' || TRIM(OOL.ORDER_LINE_NBR (FORMAT '-9(6)')) AS ORDER_HDR_ITM
    
    , OD.SHIP_TO_CUST_ID
    , CUST.CUST_NAME AS SHIP_TO_CUST_NAME
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    
    , OD.MATL_ID
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , MATL.PBU_NBR
    , MATL.PBU_NAME
    , MATL.MKT_CTGY_MKT_aREA_NBR AS CATEGORY_CD
    , MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY_NM
    , CASE
        WHEN MATL.PBU_NBR = '01'
            THEN MATL.MKT_CTGY_PROD_GRP_NAME
        ELSE MATL.TIERS
        END AS TIER
    
    , CASE
        WHEN CUST.PRIM_SHIP_fACILITY_ID = OD.FACILITY_ID
            THEN 'Primary LC'
        WHEN OD.FACILITY_ID IN ('N5US', 'N5CA')
            THEN 'N5US / N5CA'
        WHEN OD.FACILITY_ID LIKE 'N5%'
            THEN 'Factory Direct'
        ELSE 'Out of Area'
        END AS TEST_PRIM_SHIP_FACILITY
    , CUST.PRIM_SHIP_FACILITY_ID
    , OD.FACILITY_ID
    
    , OD.CUST_GRP2_CD
    , OD.DELIV_PRTY_ID
    , OD.SHIP_COND_ID
    , OD.DELIV_GRP_CD
    
    , OD.ORDER_DELIV_BLK_CD
    , OD.DELIV_BLK_CD
    
    , OD.ORDER_DT
    , OD.ORDER_LN_CRT_DT
    
    , OD.PLN_MATL_AVL_DT
    , OD.PLN_GOODS_ISS_DT
    , OD.PLN_DELIV_DT
    
    , OD.CUST_RDD
    , OD.FRST_RDD
    , OD.FRST_PROM_DELIV_DT
    
    , OD.QTY_UNIT_MEAS_ID
    , OD.ORDER_QTY
    , OOL.OPEN_CNFRM_QTY
    
    , ZEROIFNULL(INV.AVAIL_TO_PROM_QTY) AS ATP_QTY
    , ZEROIFNULL(INV.EST_DAYS_SUPPLY) AS EST_DSI
    
FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OOL.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = OD.ORDER_ID
        AND OOL.ORDER_LINE_NBR = OD.ORDER_LINE_NBR
        AND OD.EXP_DT = DATE '5555-12-31'
        AND OD.SCHED_LINE_NBR = 1
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.RO_PO_TYPE_IND = 'N'
        AND OD.PLN_MATL_AVL_DT IS NOT NULL
        AND OD.PLN_MATL_AVL_DT BETWEEN CURRENT_DATE AND CURRENT_DATE+14
        AND OD.CUST_GRP2_CD = 'TLB'
    
    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID
    
    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = OD.MATL_ID
        AND MATL.PBU_NBR IN ('01', '03')
        AND MATL.EXT_MATL_GRP_ID = 'TIRE'

    LEFT OUTER JOIN NA_BI_VWS.FACILITY_MATL_INVENTORY INV
        ON INV.DAY_DT = CURRENT_DATE-1
        AND INV.FACILITY_ID = OD.FACILITY_ID
        AND INV.MATL_ID = OD.MATL_ID

WHERE
    OOL.OPEN_CNFRM_QTY > 0

ORDER BY
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    , OOL.SCHED_LINE_NBR
