SELECT
    CAL.BEGIN_DT AS BEGIN_OF_WEEK_DT
    , COUNT(DISTINCT DDC.FISCAL_YR || DDC.DELIV_ID || DDC.DELIV_LINE_NBR) AS DELIV_LINE_CNT
    , COUNT(DISTINCT NULLIF(DDC.BILL_LADING_ID, '')) AS BOL_CNT
    , COUNT(DISTINCT DDC.SHIP_TO_CUST_ID) AS SHIP_TO_CUST_CNT
    , CASE
        WHEN GROSS_WEIGHT > 20000
            THEN '2OK+'
        WHEN GROSS_WEIGHT BETWEEN 10000 AND 20000
            THEN '10-20K'
        WHEN GROSS_WEIGHT BETWEEN 5000 AND 10000
            THEN '5-10K'
        WHEN GROSS_wEIGHT BETWEEN 2000 AND 5000
            THEN '2-5K'
        WHEN GROSS_WEIGHT < 2000
            THEN '2K-'
        END AS WEEKLY_GROSS_WEIGHT_TEST
    
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    , CUST.OWN_CUST_ID || ' - ' || CUST.OWN_CUST_NAME AS OWN_CUST
	
	, CUST.SALES_ORG_CD
	, CUST.SALES_ORG_CD || ' - ' || CUST.SALES_ORG_NAME AS SALES_ORG
    
	, CUST.DISTR_CHAN_CD
	, CUST.DISTR_CHAN_CD || ' - ' || CUST.DISTR_CHAN_NAME AS DISTR_CHAN
    
	, CUST.CUST_GRP_ID
	, CUST.CUST_GRP_ID || ' - ' || CUST.CUST_GRP_NAME AS CUST_GRP
    
    , CUST.TIRE_CUST_TYP_CD
    
    , DDC.DELIV_LINE_FACILITY_ID AS FACILITY_ID
    , DDC.CUST_GRP2_CD
    
    , CAST('EA' AS CHAR(3)) AS QTY_UOM
    , SUM(CASE 
        WHEN DDC.QTY_UNIT_MEAS_ID = 'LB'
            THEN DDC.DELIV_QTY / 100
        ELSE DDC.DELIV_QTY
        END) AS DELIVERY_QTY
    
    , CAST('LB' AS CHAR(3)) AS WT_UOM
    , SUM(CASE
        WHEN DDC.WT_UNIT_MEAS_ID = 'KG'
            THEN DDC.GROSS_WT * 2.20
        ELSE DDC.GROSS_WT
        END) AS GROSS_WEIGHT
    
    , DDC.VOL_UNIT_MEAS_ID AS VOL_UOM
    , SUM(DDC.VOL) AS VOL
    , SUM(CAST(CASE MATL.PBU_NBR || MATL.MKT_AREA_NBR
        WHEN '0101' THEN 0.75
        WHEN '0108' THEN 0.80
        WHEN '0305' THEN 1.20
        WHEN '0314' THEN 1.20
        WHEN '0406' THEN 1.20
        WHEN '0507' THEN 0.75
        WHEN '0711' THEN 0.75
        WHEN '0712' THEN 0.75
        WHEN '0803' THEN 1.20
        WHEN '0923' THEN 0.75
        ELSE 1
        END * MATL.UNIT_VOL * CASE 
        WHEN DDC.QTY_UNIT_MEAS_ID = 'LB'
            THEN DDC.DELIV_QTY / 100
        ELSE DDC.DELIV_QTY
        END AS DECIMAL(15,3))) AS CMPR_VOL

FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE = DDC.ACTL_GOODS_ISS_DT
        AND CAL.DAY_DATE BETWEEN DATE '2014-01-01' AND (CURRENT_DATE-1)

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_dESCR_EN_CURR MATL
        ON MATL.MATL_ID = DDC.MATL_ID
        AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
        AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID
        AND CUST.SALES_ORG_CD IN ('N301', 'N311')

WHERE
    DDC.BILL_LADING_ID <> ''
    AND DDC.GOODS_ISS_IND = 'Y'
    AND DDC.DELIV_CAT_ID = 'J'
    AND DDC.DISTR_CHAN_CD <> '81'
    AND DDC.DELIV_QTY > 0
    AND DDC.DELIV_NOTE_CREA_DT >= DATE '2014-01-01'
    AND DDC.CUST_GRP2_CD <> 'TLB'
    AND CUST.PRIM_SHIP_FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID

GROUP BY
    CAL.BEGIN_DT
    
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    , OWN_CUST
	
	, CUST.SALES_ORG_CD
	, SALES_ORG
    
	, CUST.DISTR_CHAN_CD
	, DISTR_CHAN
    
	, CUST.CUST_GRP_ID
	, CUST_GRP
    
    , CUST.TIRE_CUST_TYP_CD
    
    , DDC.DELIV_LINE_FACILITY_ID
    , DDC.CUST_GRP2_CD
    
    , QTY_UOM
    
    , WT_UOM
    
    , DDC.VOL_UNIT_MEAS_ID