SELECT
    TLM.FISCAL_YR
    , TLM.SLS_DOC_ID
    , TLM.SLS_DOC_ITM_ID

    , TLM.CUST_ID
    , TLM.DELIV_GRP_CD
    , SDI.DELIV_GRP_ID
    , TLM.FACILITY_ID
    , TLM.SHIP_RCVE_PT_CD
    , TLM.MATL_ID
    , TLM.ITM_QTY

    , TLM.MATL_AVL_DT
    , TLM.DELIV_DT
    , TLM.GROSS_WT_QTY
    , TLM.VOL_QTY
    , TLM.TL_PLN_CD
    
    , TLS.DELIV_DT AS SLOT_DELIV_DT

    , TLM.ACCTNG_DOC_CREATE_DT AS TLB_DOC_CRT_DT
    , TLM.ACCTNG_DOC_CREATE_TM AS TLB_DOC_CRT_TM
    , TLM.SRC_CRT_USR_ID
    , TLM.SAP_TRANS_CD

    , SDI.SPLIT_SLS_DOC_ITM_ID
    , CASE
        WHEN SDI.SPLIT_SLS_DOC_ITM_ID = 0 OR SDI.SPLIT_SLS_DOC_ITM_ID = TLM.SLS_DOC_ITM_ID
            THEN 'N'
        ELSE 'Y'
        END AS SPLIT_ITM_IND

    , SDI.ORIG_REQ_DELIV_DT
    , CASE
        WHEN SDI.ORIG_REQ_DELIV_DT = TLS.DELIV_DT
            THEN 'ORDD=SLOT DT'
        ELSE 'ORDD<>SLOT DT'
        END AS ORDD_V_SLOT_DT_IND
    
    , SDI.FRST_REQ_DELIV_DT
    , CASE
        WHEN SDI.FRST_REQ_DELIV_DT = TLS.DELIV_DT
            THEN 'FRDD=SLOT DT'
        ELSE 'FRDD<>SLOT DT'
        END AS FRDD_V_SLOT_DT_IND
    
    , CASE
        WHEN SDI.ORIG_REQ_DELIV_DT = SDI.FRST_REQ_DELIV_DT
            THEN 'EQ'
        ELSE 'NEQ'
        END AS ORDD_EQ_FRDD_IND

    , CHG.ORDD_UPD_CNT
    , CHG.SYS_ORDD_UPD_CNT
    , CHG.USR_ORDD_UPD_CNT

FROM NA_BI_VWS.TL_MSTR_CURR TLM

    INNER JOIN NA_BI_VWS.TL_CAP_DELIV_SCHD TLS
        ON TLS.CUST_ID = TLM.CUST_ID
        AND TLS.DELIV_DT = TLM.DELIV_DT
        AND TLS.DELIV_GRP_CD = TLM.DELIV_GRP_CD
        AND TLM.ACCTNG_DOC_CREATE_DT BETWEEN TLS.EFF_DT AND TLS.EXP_DT

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM_CURR SDI
        ON SDI.FISCAL_YR = TLM.FISCAL_YR
        AND SDI.SLS_DOC_ID = TLM.SLS_DOC_ID
        AND SDI.SLS_DOC_ITM_ID = TLM.SLS_DOC_ITM_ID

    LEFT OUTER JOIN (
            SELECT
                DOC_ID
                , DOC_ITM_ID
                , COUNT(SRC_CRT_TS) AS ORDD_UPD_CNT
                , COUNT(CASE
                    WHEN SRC_CRT_USR_ID LIKE 'L%'
                        THEN SRC_CRT_TS
                    END) AS SYS_ORDD_UPD_CNT
                , ORDD_UPD_CNT - SYS_ORDD_UPD_CNT AS USR_ORDD_UPD_CNT

            FROM GDYR_BI_VWS.NAT_CHG_DOC_SD_DTL 
            WHERE
                ORIG_SYS_ID = 2
                AND OBJ_CLS_CD = 'VERKBELEG'
                AND SRC_CRT_DT BETWEEN DATE '2014-10-01' AND CURRENT_DATE
                AND SAP_TBL_NM = 'VBAP'
                AND SAP_COL_NM = 'YYORDD'
                --AND DOC_ID = '0084562920'
                --AND DOC_ITM_ID = 70

            GROUP BY
                DOC_ID
                , DOC_ITM_ID
            ) CHG
        ON CHG.DOC_ID = TLM.SLS_DOC_ID
        AND CHG.DOC_ITM_ID = TLM.SLS_DOC_ITM_ID

WHERE
    TLM.SAP_TRANS_CD IN ('YSDTLBUILD', 'YSDTLBATCH')
    AND TLM.DELIV_DT BETWEEN CAST('2015-01-01' AS DATE) AND CURRENT_DATE-1
    --AND TLM.FISCAL_YR = '2014'
    --AND TLM.SLS_DOC_ID = '0084562920'
    --AND TLM.SLS_DOC_ITM_ID = 70

ORDER BY
    TLM.DELIV_DT
    , TLM.CUST_ID
    , TLM.DELIV_GRP_CD
    , TLM.FISCAL_YR
    , TLM.SLS_DOC_ID
    , TLM.SLS_DOC_ITM_ID
