SELECT
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    , OD.ORIG_ORDER_LINE_NBR
    , CASE
        WHEN OOL.ORDER_LINE_NBR = OD.ORIG_ORDER_LINE_NBR
            THEN 'N'
        ELSE 'Y'
        END AS SPLIT_LINE_IND

    , OD.ORDER_LN_CRT_DT
    , SDI.ORDER_LN_CRT_DT AS ORIG_ORDER_LN_CRT_DT

    , CASE
        WHEN SPLIT_LINE_IND = 'Y' AND OD.ORDER_LN_CRT_DT = SDI.ORDER_LN_CRT_DT
            THEN 'Y'
        ELSE 'N'
        END AS SPLIT_SAME_DAY_IND

    , OD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , OD.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME

    , OD.FACILITY_ID

    , OD.QTY_UNIT_MEAS_ID
    , OD.ORDER_QTY

FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND OD.ORDER_ID = OOL.ORDER_ID
        AND OD.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = 1
        AND OD.EXP_DT = CAST('5555-12-31' AS DATE)
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.RO_PO_TYPE_IND = 'N'
        AND OD.CUST_GRP2_CD = 'TLB'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID

    INNER JOIN NA_BI_VWS.ORDER_DETAIL SDI
        ON SDI.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
        AND SDI.ORDER_ID = OD.ORDER_ID
        AND SDI.ORDER_LINE_NBR = OD.ORIG_ORDER_LINE_NBR
        AND SDI.SCHED_LINE_NBR = 1
        AND SDI.EXP_DT = CAST('5555-12-31' AS DATE)

WHERE
    OOL.SCHED_LINE_NBR = 1
    AND OOL.IN_PROC_QTY = 0

ORDER BY
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
