SELECT
    O.ORDER_FISCAL_YR
    , O.ORDER_ID
    , O.ORDER_LINE_NBR

    , O.ORDER_DT
    , O.ORDER_LN_CRT_DT

    , O.MATL_ID
    , O.DESCR
    , O.PBU_NBR
    , O.PBU_NAME
    , O.MATL_STA_ID

    , O.FACILITY_ID
    , O.FACILITY_NAME
    , O.PRIM_SHIP_FACILITY_ID
    , O.TEST_PRIM_SHIP_FACILITY

    , O.SHIP_TO_CUST_ID
    , O.CUST_NAME
    , O.OWN_CUST_ID
    , O.OWN_CUST_NAME

    , O.HDR_DELIV_BLK_CD
    , O.SL_DELIV_BLK_CD
    , O.DELIV_PRTY_ID
    , O.DELIV_GRP_CD

    , O.TEST_HDR_DELIV_BLK
    , O.TEST_SL_DELIV_BLK
    , O.TEST_HDR_SL_DELIV_BLK
    , O.TEST_BLK_PRTY
    
    , MAX(CASE
        WHEN O.SAP_TBL_NM = 'VBAP' AND O.SAP_COL_NM = 'LPRIO'
            THEN O.TEST_SYS_USR_CHANGE
        END) AS TEST_SYS_USR_CHANGE_PRTY
    , MAX(CASE
        WHEN O.SAP_TBL_NM = 'VBAP' AND O.SAP_COL_NM = 'LPRIO'
            THEN O.OLD_VAL_TXT
        END) AS OLD_VAL_TXT_PRTY
    , MAX(CASE
        WHEN O.SAP_TBL_NM = 'VBAP' AND O.SAP_COL_NM = 'LPRIO'
            THEN O.NEW_VAL_TXT
        END) AS NEW_VAL_TXT_PRTY
    , MAX(CASE
        WHEN O.SAP_TBL_NM = 'VBAP' AND O.SAP_COL_NM = 'LPRIO'
            THEN O.SRC_CRT_TS
        END) AS SRC_CRT_TS_PRTY
    , MAX(CASE
        WHEN O.SAP_TBL_NM = 'VBAP' AND O.SAP_COL_NM = 'LPRIO'
            THEN O.SRC_CRT_USR_ID
        END) AS SRC_CRT_USR_ID_PRTY
    , MAX(CASE
        WHEN O.SAP_TBL_NM = 'VBAP' AND O.SAP_COL_NM = 'LPRIO'
            THEN O.SAP_TRANS_CD
        END) AS SAP_TRANS_CD_PRTY
    , MAX(CASE
        WHEN O.SAP_TBL_NM = 'VBEP' AND O.SAP_COL_NM = 'LIFSP'
            THEN O.TEST_SYS_USR_CHANGE
        END) AS TEST_SYS_USR_CHANGE_SL_BLK
    , MAX(CASE
        WHEN O.SAP_TBL_NM = 'VBEP' AND O.SAP_COL_NM = 'LIFSP'
            THEN O.OLD_VAL_TXT
        END) AS OLD_VAL_TXT_SL_BLK
    , MAX(CASE
        WHEN O.SAP_TBL_NM = 'VBEP' AND O.SAP_COL_NM = 'LIFSP'
            THEN O.NEW_VAL_TXT
        END) AS NEW_VAL_TXT_SL_BLK
    , MAX(CASE
        WHEN O.SAP_TBL_NM = 'VBEP' AND O.SAP_COL_NM = 'LIFSP'
            THEN O.SRC_CRT_TS
        END) AS SRC_CRT_TS_SL_BLK
    , MAX(CASE
        WHEN O.SAP_TBL_NM = 'VBEP' AND O.SAP_COL_NM = 'LIFSP'
            THEN O.SRC_CRT_USR_ID
        END) AS SRC_CRT_USR_ID_SL_BLK
    , MAX(CASE
        WHEN O.SAP_TBL_NM = 'VBEP' AND O.SAP_COL_NM = 'LIFSP'
            THEN O.SAP_TRANS_CD
        END) AS SAP_TRANS_CD_SL_BLK
    
    
FROM (

SELECT
    OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , OD.ORDER_DT
    , OD.ORDER_LN_CRT_DT

    , OD.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MATL_STA_ID

    , OD.FACILITY_ID
    , F.FACILITY_NAME
    , C.PRIM_SHIP_FACILITY_ID
    , CASE
        WHEN OD.FACILITY_ID IN ('N5US', 'N5CA')
            THEN 'N5US / N5CA'
        WHEN C.PRIM_SHIP_FACILITY_ID = OD.FACILITY_ID
            THEN 'Primary LC'
        ELSE 'Out of Area'
        END AS TEST_PRIM_SHIP_FACILITY

    , OD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , NULLIF(OD.ORDER_DELIV_BLK_CD, '') AS HDR_DELIV_BLK_CD
    , NULLIF(OD.DELIV_BLK_CD, '') AS SL_DELIV_BLK_CD

    , OD.DELIV_PRTY_ID
    , OD.DELIV_GRP_CD

    , CDI.CHG_TYP_CD
    , CDI.TXT_CHG_IND
    , CDI.OLD_VAL_TXT
    , CDI.NEW_VAL_TXT
    , CDI.SRC_CRT_DT
    , CDI.SRC_CRT_TM
    , CDI.SRC_CRT_TS
    , CH.SRC_CRT_USR_ID
    , CH.SAP_TRANS_CD

    , CASE
        WHEN CH.SRC_CRT_USR_ID LIKE 'L%'
            THEN 'System'
        WHEN CH.SRC_CRT_USR_ID IS NOT NULL
            THEN 'User'
        ELSE 'None'
        END AS TEST_SYS_USR_CHANGE
    , CASE
        WHEN HDR_DELIV_BLK_CD IS NULL OR HDR_DELIV_BLK_CD = 'YO'
            THEN 'Pass'
        ELSE 'Fail'
        END AS TEST_HDR_DELIV_BLK
    , CASE
        WHEN (SL_DELIV_BLK_CD IS NULL OR SL_DELIV_BLK_CD IN ('YT', 'YR')) OR (SL_DELIV_BLK_CD = '11' AND M.MATL_STA_ID = 'PD')
            THEN 'Pass'
        ELSE 'Fail'
        END AS TEST_SL_DELIV_BLK
    , CASE
        WHEN HDR_DELIV_BLK_CD = 'YO' AND SL_DELIV_BLK_CD IN ('YT', 'YR')
            THEN 'Fail'
        WHEN SL_DELIV_BLK_CD = 'YT' AND HDR_DELIV_BLK_CD IS NOT NULL
            THEN 'Fail'
        ELSE 'Pass'
        END AS TEST_HDR_SL_DELIV_BLK
    , CASE
        WHEN HDR_DELIV_BLK_CD IS NULL AND SL_DELIV_BLK_CD IS NULL AND OD.DELIV_PRTY_ID = '12'
            THEN 'Pass'
        WHEN (HDR_DELIV_BLK_CD IS NOT NULL OR SL_DELIV_BLK_CD IS NOT NULL) AND OD.DELIV_PRTY_ID = '45'
            THEN 'Pass'
        ELSE 'Fail'
        END AS TEST_BLK_PRTY

    , CDI.SAP_TBL_NM
    , CDI.SAP_COL_NM
    , CDI.CHG_TBL_REC_ID

FROM NA_BI_VWS.ORDER_DETAIL OD

    INNER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL
        ON OOL.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = OD.ORDER_ID
        AND OOL.ORDER_LINE_NBR = OD.ORDER_LINE_NBR
        AND OOL.SCHED_LINE_NBR = OD.SCHED_LINE_NBR
        AND (
                OOL.OPEN_CNFRM_QTY > 0
                OR OOL.UNCNFRM_QTY > 0
                OR OOL.BACK_ORDER_QTY > 0
                OR OOL.DEFER_QTY > 0
                OR OOL.WAIT_LIST_QTY > 0
            )

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    LEFT OUTER JOIN (
            GDYR_BI_VWS.CHG_DOC_ITM CDI

            INNER JOIN GDYR_BI_VWS.CHG_DOC CH
                ON CH.ORIG_SYS_ID = CDI.ORIG_SYS_ID
                AND CH.OBJ_CLS_CD = CDI.OBJ_CLS_CD
                AND CH.OBJ_VAL_ID = CDI.OBJ_VAL_ID
                AND CH.CHG_DOC_ID = CDI.CHG_DOC_ID
            )
        ON CDI.DOC_ID = OD.ORDER_ID
        AND CDI.DOC_ITM_ID = OD.ORDER_LINE_NBR
        AND CDI.ORIG_SYS_ID = 2
        AND CDI.OBJ_CLS_CD = 'VERKBELEG'
        AND CDI.SRC_CRT_DT BETWEEN DATE '2013-12-01' AND CURRENT_DATE-1
        AND CDI.SAP_TBL_NM = 'VBAP' 
        AND CDI.SAP_COL_NM = 'LPRIO'

WHERE
    OD.SCHED_LINE_NBR = 1
    AND OD.EXP_DT = CAST('5555-12-31' AS DATE)
    AND OD.ORDER_CAT_ID = 'C'
    AND OD.RO_PO_TYPE_IND = 'N'
    AND OD.CUST_GRP2_CD = 'TLB'
    AND OD.REJ_REAS_ID = ''
    AND (
        TEST_HDR_DELIV_BLK = 'Fail'
        OR TEST_SL_DELIV_BLK = 'Fail'
        OR TEST_HDR_SL_DELIV_BLK = 'Fail'
        OR TEST_BLK_PRTY = 'Fail'
        )

QUALIFY
    ROW_NUMBER() OVER (PARTITION BY OD.ORDER_FISCAL_YR, OD.ORDER_ID, OD.ORDER_LINE_NBR ORDER BY CDI.SRC_CRT_TS DESC) = 1

UNION ALL

SELECT
    OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , OD.ORDER_DT
    , OD.ORDER_LN_CRT_DT

    , OD.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MATL_STA_ID

    , OD.FACILITY_ID
    , F.FACILITY_NAME
    , C.PRIM_SHIP_FACILITY_ID
    , CASE
        WHEN OD.FACILITY_ID IN ('N5US', 'N5CA')
            THEN 'N5US / N5CA'
        WHEN C.PRIM_SHIP_FACILITY_ID = OD.FACILITY_ID
            THEN 'Primary LC'
        ELSE 'Out of Area'
        END AS TEST_PRIM_SHIP_FACILITY

    , OD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , NULLIF(OD.ORDER_DELIV_BLK_CD, '') AS HDR_DELIV_BLK_CD
    , NULLIF(OD.DELIV_BLK_CD, '') AS SL_DELIV_BLK_CD

    , OD.DELIV_PRTY_ID
    , OD.DELIV_GRP_CD

    , CDI.CHG_TYP_CD
    , CDI.TXT_CHG_IND
    , CDI.OLD_VAL_TXT
    , CDI.NEW_VAL_TXT
    , CDI.SRC_CRT_DT
    , CDI.SRC_CRT_TM
    , CDI.SRC_CRT_TS
    , CH.SRC_CRT_USR_ID
    , CH.SAP_TRANS_CD

    , CASE
        WHEN CH.SRC_CRT_USR_ID LIKE 'L%'
            THEN 'System'
        WHEN CH.SRC_CRT_USR_ID IS NOT NULL
            THEN 'User'
        ELSE 'None'
        END AS TEST_SYS_USR_CHANGE
    , CASE
        WHEN HDR_DELIV_BLK_CD IS NULL OR HDR_DELIV_BLK_CD = 'YO'
            THEN 'Pass'
        ELSE 'Fail'
        END AS TEST_HDR_DELIV_BLK
    , CASE
        WHEN (SL_DELIV_BLK_CD IS NULL OR SL_DELIV_BLK_CD IN ('YT', 'YR')) OR (SL_DELIV_BLK_CD = '11' AND M.MATL_STA_ID = 'PD')
            THEN 'Pass'
        ELSE 'Fail'
        END AS TEST_SL_DELIV_BLK
    , CASE
        WHEN HDR_DELIV_BLK_CD = 'YO' AND SL_DELIV_BLK_CD IN ('YT', 'YR')
            THEN 'Fail'
        WHEN SL_DELIV_BLK_CD = 'YT' AND HDR_DELIV_BLK_CD IS NOT NULL
            THEN 'Fail'
        ELSE 'Pass'
        END AS TEST_HDR_SL_DELIV_BLK
    , CASE
        WHEN HDR_DELIV_BLK_CD IS NULL AND SL_DELIV_BLK_CD IS NULL AND OD.DELIV_PRTY_ID = '12'
            THEN 'Pass'
        WHEN (HDR_DELIV_BLK_CD IS NOT NULL OR SL_DELIV_BLK_CD IS NOT NULL) AND OD.DELIV_PRTY_ID = '45'
            THEN 'Pass'
        ELSE 'Fail'
        END AS TEST_BLK_PRTY

    , CDI.SAP_TBL_NM
    , CDI.SAP_COL_NM
    , CDI.CHG_TBL_REC_ID

FROM NA_BI_VWS.ORDER_DETAIL OD

    INNER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL
        ON OOL.ORDER_FISCAL_YR = OD.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = OD.ORDER_ID
        AND OOL.ORDER_LINE_NBR = OD.ORDER_LINE_NBR
        AND OOL.SCHED_LINE_NBR = OD.SCHED_LINE_NBR
        AND (
                OOL.OPEN_CNFRM_QTY > 0
                OR OOL.UNCNFRM_QTY > 0
                OR OOL.BACK_ORDER_QTY > 0
                OR OOL.DEFER_QTY > 0
                OR OOL.WAIT_LIST_QTY > 0
            )

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

    LEFT OUTER JOIN (
            GDYR_BI_VWS.CHG_DOC_ITM CDI

            INNER JOIN GDYR_BI_VWS.CHG_DOC CH
                ON CH.ORIG_SYS_ID = CDI.ORIG_SYS_ID
                AND CH.OBJ_CLS_CD = CDI.OBJ_CLS_CD
                AND CH.OBJ_VAL_ID = CDI.OBJ_VAL_ID
                AND CH.CHG_DOC_ID = CDI.CHG_DOC_ID
            )
        ON CDI.DOC_ID = OD.ORDER_ID
        AND CDI.DOC_ITM_ID = OD.ORDER_LINE_NBR
        AND CDI.ORIG_SYS_ID = 2
        AND CDI.OBJ_CLS_CD = 'VERKBELEG'
        AND CDI.SRC_CRT_DT BETWEEN DATE '2013-12-01' AND CURRENT_DATE-1
        AND CDI.SAP_TBL_NM = 'VBEP' 
        AND CDI.SAP_COL_NM = 'LIFSP'

WHERE
    OD.SCHED_LINE_NBR = 1
    AND OD.EXP_DT = CAST('5555-12-31' AS DATE)
    AND OD.ORDER_CAT_ID = 'C'
    AND OD.RO_PO_TYPE_IND = 'N'
    AND OD.CUST_GRP2_CD = 'TLB'
    AND OD.REJ_REAS_ID = ''
    AND (
        TEST_HDR_DELIV_BLK = 'Fail'
        OR TEST_SL_DELIV_BLK = 'Fail'
        OR TEST_HDR_SL_DELIV_BLK = 'Fail'
        OR TEST_BLK_PRTY = 'Fail'
        )

QUALIFY
    ROW_NUMBER() OVER (PARTITION BY OD.ORDER_FISCAL_YR, OD.ORDER_ID, OD.ORDER_LINE_NBR ORDER BY CDI.SRC_CRT_TS DESC) = 1

    ) O

GROUP BY
    O.ORDER_FISCAL_YR
    , O.ORDER_ID
    , O.ORDER_LINE_NBR

    , O.ORDER_DT
    , O.ORDER_LN_CRT_DT

    , O.MATL_ID
    , O.DESCR
    , O.PBU_NBR
    , O.PBU_NAME
    , O.MATL_STA_ID

    , O.FACILITY_ID
    , O.FACILITY_NAME
    , O.PRIM_SHIP_FACILITY_ID
    , O.TEST_PRIM_SHIP_FACILITY

    , O.SHIP_TO_CUST_ID
    , O.CUST_NAME
    , O.OWN_CUST_ID
    , O.OWN_CUST_NAME

    , O.HDR_DELIV_BLK_CD
    , O.SL_DELIV_BLK_CD
    , O.DELIV_PRTY_ID
    , O.DELIV_GRP_CD

    , O.TEST_HDR_DELIV_BLK
    , O.TEST_SL_DELIV_BLK
    , O.TEST_HDR_SL_DELIV_BLK
    , O.TEST_BLK_PRTY
