SELECT
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    ODC.SCHED_LINE_NBR,
    
    CHG.OBJ_CLS_CD,
    CHG.OBJ_VAL_ID,
    CHG.CHG_DOC_ID,
    CHG.SRC_CRT_USR_ID,
    CHG.SRC_CRT_DT,
    CHG.SRC_CRT_TS,
    CHG.CHG_TBL_REC_ID,
    CHG.SAP_TBL_NM,
    CHG.SAP_COL_NM,
    CHG.CHG_TYP_CD,
    CHG.SAP_TRANS_CD,
    CHG.TXT_CHG_IND,
    CHG.OLD_UNIT_QTY,
    CHG.NEW_UNIT_QTY,
    CHG.OLD_CRNCY_ID,
    CHG.NEW_CRNCY_ID,
    CHG.OLD_VAL_TXT,
    CHG.NEW_VAL_TXT,
    
    ODC.SHIP_TO_CUST_ID,
    ODC.SALES_ORG_CD,
    ODC.DISTR_CHAN_CD,
    ODC.CO_CD,
    ODC.DIV_CD,
    
    ODC.MATL_ID,
    
    ODC.FACILITY_ID,
    ODC.SHIP_PT_ID,
    
    ODC.CUST_GRP2_CD,
    ODC.ORDER_CAT_ID,
    ODC.ORDER_TYPE_ID,
    ODC.PO_TYPE_ID,
    ODC.DELIV_BLK_CD,
    ODC.ORDER_CREATOR,
    ODC.SHIP_COND_ID,
    ODC.CANCEL_DT,
    ODC.REJ_REAS_ID,
    ODC.REJ_REAS_DESC,
    ODC.DELIV_PRTY_ID,
    ODC.ROUTE_ID,
    ODC.DELIV_GRP_CD,
    ODC.SPCL_PROC_ID,
    
    ODC.QTY_UNIT_MEAS_ID AS QTY_UOM,
    ODC.ORDER_QTY,
    ODC.CNFRM_QTY,
    
    ODC.WT_UNITS_MEAS_ID AS WT_UOM,
    ODC.NET_WT,
    ODC.GROSS_WT,
    
    ODC.VOL_UNIT_MEAS_ID AS VOL_UOM,
    ODC.VOL,
    
    ODC.ORDER_DT,
    ODC.CUST_RDD AS ORDD,
    ODC.FRST_MATL_AVL_DT AS FRDD_FMAD,
    ODC.FRST_PLN_GOODS_ISS_DT AS FRDD_FPGI,
    ODC.FRST_RDD AS FRDD,
    ODC.FC_MATL_AVL_DT AS FCDD_FMAD,
    ODC.FC_PLN_GOODS_ISS_DT AS FCDD_FPGI,
    ODC.FRST_PROM_DELIV_DT AS FCDD,
    ODC.PLN_TRANSP_PLN_DT,
    ODC.PLN_MATL_AVL_DT,
    ODC.PLN_LOAD_DT,
    ODC.PLN_GOODS_ISS_DT
    
FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID
        AND CUST.OWN_CUST_ID = '00A0006929'

    INNER JOIN NA_BI_VWS.OPEN_ORDER_ORDLN_CURR OOL
        ON OOL.ORDER_ID = ODC.ORDER_ID
        AND OOL.ORDER_LINE_NBR = ODC.ORDER_LINE_NBR

    LEFT OUTER JOIN GDYR_BI_VWS.NAT_CHG_DOC_SD_DTL CHG
        ON CHG.SRC_CRT_DT BETWEEN DATE '2014-03-24' AND DATE '2014-03-28'
        AND CHG.SBU_ID = 2
        AND CHG.SAP_TBL_NM IN ( 'VBAK', 'VBAP' )
        AND CHG.DOC_ID = ODC.ORDER_ID
        AND CHG.DOC_ITM_ID = ODC.ORDER_LINE_NBR

WHERE
    ODC.CUST_GRP2_CD = 'TLB'
    AND ( ODC.ORDER_ID, ODC.ORDER_LINE_NBR ) IN (
        SELECT
            O.ORDER_ID,
            O.ORDER_LINE_NBR
        FROM GDYR_BI_VWS.GDYR_CAL C
            INNER JOIN GDYR_VWS.OPEN_ORDER O
                ON C.DAY_DATE BETWEEN O.EFF_DT AND O.EXP_DT
                AND O.SBU_ID = 2
                AND O.ORIG_SYS_ID = 2
                AND O.SRC_SYS_ID = 2
                AND O.OPEN_ORDER_STATUS_CD = 'C'
                AND O.OPEN_ORDER_QTY > 0
        WHERE
            C.DAY_DATE BETWEEN DATE '2014-03-24' AND DATE '2014-03-28'
    )