SELECT
    DDC.FISCAL_YR AS DELIV_FISCAL_YR
    , DDC.DELIV_ID
    , DDC.DELIV_LINE_NBR
    , DDC.ORDER_FISCAL_YR
    , DDC.ORDER_ID
    , DDC.ORDER_LINE_NBR
    
    , DDC.DELIV_CAT_ID
    , DDC.DELIV_TYPE_ID
    , DDC.ITEM_CAT_ID
    
    , DDC.BILL_LADING_ID
    
    , DDC.DELIV_PRTY_ID
    , DDC.SHIP_COND_ID
    , DDC.ORIG_DELIV_LINE_NBR
    , DDC.RTG_ID AS ROUTE_ID
    , DDC.TERMS_ID
    , DDC.UNLD_PT_CD
    , DDC.SPCL_PROC_ID
    , DDC.PRM_SHIP_CARR_CD
    , DDC.TRANSP_VEH_NO
    , DDC.SRC_CRT_USR_ID
    , DDC.GOODS_ISS_IND
    
    , DDC.SHIP_TO_CUST_ID
    , DDC.SALES_ORG_CD
    , DDC.DISTR_CHAN_CD
    , DDC.CUST_GRP_ID
    , DDC.CUST_GRP2_CD
    
    , DDC.MATL_ID
	, MATL.EXT_MATL_GRP_ID
	, MATL.STK_CLASS_ID
	, MATL.TIRE_SZ_TEXT
    , MATL.PBU_NBR
    , MATL.MKT_AREA_NBR
    
	, MATL.VOL_MEAS_ID
	, MATL.UNIT_VOL
    
	, CAST(CASE MATL.PBU_NBR || MATL.MKT_AREA_NBR
        WHEN '0101' THEN 0.75
        WHEN '0108' THEN 0.80
        WHEN '0305' THEN 1.20
        WHEN '0314' THEN 1.20
        WHEN '0406' THEN 1.20
        WHEN '0507' THEN 0.75
        WHEN '0711' THEN 0.75
        WHEN '0712' THEN 0.75
        WHEN '0803' THEN 1.20
        WHEN '0923' THEN 0.75
        ELSE 1
    END AS DECIMAL(15, 3)) AS COMPRESSION_FACTOR
	, MATL.UNIT_VOL * COMPRESSION_FACTOR AS UNIT_COMPRESSED_VOL
    
	, MATL.WT_MEAS_ID
	, MATL.UNIT_WT
    
    , DDC.FACILITY_ID
    , DDC.DELIV_LINE_FACILITY_ID
    , DDC.SHIP_PT_ID
    , DDC.SHIP_FACILITY_ID
    
    , DDC.DELIV_NOTE_CREA_DT
    , DDC.DELIV_LINE_CREA_DT
    , DDC.TRANSP_PLN_DT
    , DDC.PICK_DT
    , DDC.LOAD_DT
    , DDC.PLN_GOODS_MVT_DT
    , DDC.ACTL_GOODS_ISS_DT
    , DDC.DELIV_DT
    
    , DDC.QTY_UNIT_MEAS_ID
    , DDC.DELIV_QTY
    
    , DDC.RPT_QTY_UNIT_MEAS_ID
    , DDC.RPT_DELIV_QTY
    
    , DDC.SLS_QTY_UNIT_MEAS_ID
    , DDC.SLS_DELIV_QTY
    
    , DDC.VOL_UNIT_MEAS_ID
    , DDC.VOL
    
    , DDC.WT_UNIT_MEAS_ID
    , DDC.GROSS_WT
    , DDC.NET_WT
    
FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID
        AND CUST.PRIM_SHIP_FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR MATL
        ON MATL.MATL_ID = DDC.MATL_ID
        AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')
        AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC SD
        ON SD.EXP_DT = DATE '5555-12-31'
        AND SD.FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND SD.FISCAL_YR = CAST(EXTRACT(YEAR FROM (CURRENT_DATE-1)) AS CHAR(4))
        AND SD.SLS_DOC_ID = DDC.ORDER_ID
        AND SD.SD_DOC_CTGY_CD = 'C'
        AND SD.CUST_PRCH_ORD_TYP_CD <> 'RO'
    
    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM SDI
        ON SDI.EXP_DT = DATE '5555-12-31'
        AND SDI.FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND SDI.FISCAL_YR = CAST(EXTRACT(YEAR FROM (CURRENT_DATE-1)) AS CHAR(4))
        AND SDI.SLS_DOC_ID = DDC.ORDER_ID
        AND SDI.SLS_DOC_ITM_ID = DDC.ORDER_LINE_NBR

WHERE
    DDC.FISCAL_YR = CAST(EXTRACT(YEAR FROM (CURRENT_DATE-1)) AS CHAR(4))
    AND DDC.CUST_GRP2_CD = 'TLB'
    AND DDC.ACTL_GOODS_ISS_DT IS NOT NULL
    AND DDC.GOODS_ISS_IND = 'Y'

ORDER BY
    DDC.ORDER_FISCAL_YR
    , DDC.ORDER_ID
    , DDC.ORDER_LINE_NBR
    , DDC.FISCAL_YR
    , DDC.DELIV_ID
    , DDC.DELIV_LINE_NBR

