SELECT
    CAL.DAY_DATE AS BUS_DT
    , OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    , ODC.SHIP_TO_CUST_ID
    , ODC.MATL_ID
    , SL.SCHD_LN_DELIV_DT AS FIRST_DATE
    , CASE
        WHEN (CAST(SDI.SRC_CRT_TS AS DATE) = CAL.DAY_DATE) AND (SDI.SRC_CRT_TS - (CAST(SD.SRC_CRT_DT AS TIMESTAMP(0)) + (SD.SRC_CRT_TM - TIME '00:00:00' HOUR TO SECOND))) DAY(4) TO SECOND > INTERVAL '5' MINUTE
            THEN 1
        ELSE 0
    END AS SPLIT_TODAY_IND
    , SUM(OOL.OPEN_CNFRM_QTY) AS OPEN_CNFRM_QTY

FROM GDYR_BI_VWS.GDYR_CAL CAL

    INNER JOIN NA_VWS.OPEN_ORDER_SCHDLN OOL
        ON CAL.DAY_DATE BETWEEN OOL.EFF_DT AND OOL.EXP_DT
        AND OOL.OPEN_CNFRM_QTY > 0
        
    INNER JOIN NA_BI_VWS.ORDER_DETAIL_CURR ODC
        ON ODC.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND ODC.ORDER_ID = OOL.ORDER_ID
        AND ODC.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND ODC.SCHED_LINE_NBR = 1
        AND ODC.ORDER_CAT_ID = 'C'
        AND ODC.ORDER_TYPE_ID <> 'ZLZ'
        AND ODC.PO_TYPE_ID <> 'RO'
        AND ODC.CUST_GRP2_CD = 'TLB'
        AND ODC.SHIP_COND_ID IN ('ST', 'PT')
    
    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID
        --AND MATL.PBU_NBR IN ('01', '03')
        --AND MATL.SUPER_BRAND_ID IN ('01' ,'02', '03', '05')
    
    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID
        AND CUST.PRIM_SHIP_FACILITY_ID = ODC.FACILITY_ID

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC SD
        ON SD.FISCAL_YR = ODC.ORDER_FISCAL_YR
        AND SD.SLS_DOC_ID = ODC.ORDER_ID
        AND SD.EXP_DT = DATE '5555-12-31'
    
    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM SDI
        ON SDI.FISCAL_YR = ODC.ORDER_FISCAL_YR
        AND SDI.SLS_DOC_ID = ODC.ORDER_ID
        AND SDI.SLS_DOC_ITM_ID = ODC.ORDER_LINE_NBR
        AND SDI.EXP_DT = DATE '5555-12-31'
    
    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_SCHD_LN SL
        ON SL.FISCAL_YR = ODC.ORDER_FISCAL_YR
        AND SL.SLS_DOC_ID = ODC.ORDER_ID
        AND SL.SLS_DOC_ITM_ID = ODC.ORDER_LINE_NBR
        AND SL.SCHD_LN_ID = 1
        AND CAL.DAY_DATE BETWEEN SL.EFF_DT AND SL.EXP_DT
        AND SL.SCHD_LN_DELIV_DT <= (CAL.DAY_DATE + 14)

WHERE   
    CAL.DAY_DATE BETWEEN DATE '2014-06-17' AND (CURRENT_DATE-1)
    

GROUP BY
    CAL.DAY_DATE
    , OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    , ODC.SHIP_TO_CUST_ID
    , ODC.MATL_ID
    , SL.SCHD_LN_DELIV_DT
    , SPLIT_TODAY_IND

ORDER BY
    CAL.DAY_DATE
    , OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
