SELECT
    D.SAP_BILL_LADING_ID

    , D.SHIP_TO_CUST_ID
    , D.SHIP_TO_CUST_NAME
    , D.OWN_CUST_ID
    , D.OWN_CUST_NAME

    , D.DELIV_LINE_FACILITY_ID

    , D.TRLR_TYP_ID
    , D.TRLR_TYP_DESC

    , MIN(D.SLOT_MATL_AVL_DT) AS TLB_MATL_AVL_DT
    , MIN(D.SLOT_DELIV_DT) AS TLB_DELIV_DT
    , MIN(D.DELIV_GRP_CD) AS DELIV_GRP_ID

    , MIN(D.DELIV_NOTE_CREA_DT) AS DN_CRT_DT
    , D.PLN_GOODS_MVT_DT
    , D.ACTL_GOODS_ISS_DT
    , D.DELIV_DT
    
    , MIN(D.FIRST_DATE) AS FIRST_DATE

    , MIN(UPPER(D.OWN_TXT)) AS APPT_CD
        
    , MAX(D.CUST_APPT_DT) AS APPT_DT
    , MAX(D.CUST_APPT_TS) AS APPT_TS
    
    , CASE
        WHEN APPT_DT = TLB_DELIV_DT
            THEN 'Same Day'
        WHEN APPT_DT > TLB_DELIV_DT
            THEN 'Push'
        WHEN APPT_DT < TLB_DELIV_DT
            THEN 'Pull'
        WHEN APPT_DT IS NULL
            THEN 'No Appointment'
        END AS APPT_CLASSIFIER
    , ZEROIFNULL(CAST(APPT_DT - TLB_DELIV_DT AS INTEGER)) AS DAY_BW_SLOT_APPT
    
    , COUNT(DISTINCT D.MATL_ID) AS MATL_CNT

    , D.WT_UNIT_MEAS_ID
    , MIN(D.MIN_WT_QTY) AS SLOT_MIN_WT
    , SUM(D.GROSS_WT) AS ITEM_GROSS_WT
    , MAX(D.MAX_WT_QTY) AS SLOT_MAX_WT
    
    , CASE
        WHEN ITEM_GROSS_WT BETWEEN SLOT_MIN_WT AND SLOT_MAX_WT
            THEN 'Within Range'
        WHEN ITEM_GROSS_WT < SLOT_MIN_WT
            THEN 'Underweight'
        WHEN ITEM_GROSS_WT > SLOT_MAX_WT
            THEN 'Overweight'
        END AS TEST_GROSS_WT
    
    , D.VOL_UNIT_MEAS_ID
    , SUM(D.VOL) AS ITEM_VOL
    , MAX(D.MAX_VOL_QTY) AS SLOT_MAX_VOL

    , CASE
        WHEN ITEM_VOL <= SLOT_MAX_VOL
            THEN 'Within Range'
        WHEN ITEM_GROSS_WT > SLOT_MAX_VOL
            THEN 'Over Volume'
        END AS TEST_VOL

FROM (

SELECT
    DDC.FISCAL_YR
    , DDC.DELIV_ID
    , DDC.DELIV_LINE_NBR
    
    , DDC.ORDER_FISCAL_YR
    , DDC.ORDER_ID
    , DDC.ORDER_LINE_NBR
    
    , XREF.FRT_MVMNT_ID
    , XREF.FRT_MVMNT_SCHD_ID
    , XREF.FRT_MVMNT_STOP_ID
    , XREF.TM_DELIV_ID
    , XREF.TM_PLN_SCHD_ID
    , XREF.TM_DELIV_SPLIT_ID
    
    , DDC.SHIP_TO_CUST_ID
    , CUST.CUST_NAME AS SHIP_TO_CUST_NAME
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    
    , DDC.DELIV_LINE_FACILITY_ID
    
    , DDC.MATL_ID
    , DDC.BATCH_NBR
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , MATL.PBU_NBR
    , MATL.PBU_NAME
    
    , DDC.QTY_UNIT_MEAS_ID
    , DDC.DELIV_QTY
    
    , TLC.TL_SEQ_ID
    , TLC.RPT_TL_SEQ_ID
    , TLC.TL_PLN_CD
    
    , TLC.TRLR_TYP_ID
    , TRL.TRLR_TYP_DESC
    
    , DDC.WT_UNIT_MEAS_ID
    , DDC.GROSS_WT
    
    , TLC.MIN_WT_QTY
    , TRL.MAX_WT_QTY
    
    , DDC.VOL_UNIT_MEAS_ID
    , CAST(DDC.VOL * CASE MATL.PBU_NBR || MATL.MKT_AREA_NBR
        WHEN '0101' THEN 0.75
        WHEN '0108' THEN 0.80
        WHEN '0305' THEN 1.20
        WHEN '0314' THEN 1.20
        WHEN '0406' THEN 1.20
        WHEN '0507' THEN 0.75
        WHEN '0711' THEN 0.75
        WHEN '0712' THEN 0.75
        WHEN '0803' THEN 1.20
        WHEN '0923' THEN 0.75
        ELSE 1
        END AS DECIMAL(15,3)) AS VOL
    
    , TRL.VOL_QTY AS MAX_VOL_QTY
    
    , DDC.BILL_LADING_ID AS SAP_BILL_LADING_ID
    , FM.BILL_LADING_ID AS MSTR_BILL_LADING_ID
    , FMS.BILL_LADING_ID AS STOP_BILL_LADING_ID
    
    , DDC.DELIV_PRTY_ID
    , DDC.SHIP_COND_ID
    , DDC.UNLD_PT_CD
    , DDC.SPCL_PROC_ID
    , DDC.PRM_SHIP_CARR_CD
    , DDC.SRC_CRT_USR_ID
    , DDC.GOODS_ISS_IND
    
    , TLM.DELIV_GRP_CD
    
    , DDC.DELIV_NOTE_CREA_DT
    , DDC.DELIV_LINE_CREA_DT
    , DDC.PLN_GOODS_MVT_DT
    , DDC.ACTL_GOODS_ISS_DT
    , DDC.DELIV_DT
    , TLM.MATL_AVL_DT AS SLOT_MATL_AVL_DT
    , TLM.DELIV_DT AS SLOT_DELIV_DT
    
    , DDC.PLN_GOODS_MVT_DT - DDC.DELIV_NOTE_CREA_DT AS EST_LOGISTICS_DAYS
    , DDC.ACTL_GOODS_ISS_DT - DDC.DELIV_NOTE_CREA_DT AS ACTL_LOGISTICS_DAYS
    
    , DDC.DELIV_CAT_ID
    , DDC.DELIV_TYPE_ID
    , DDC.ITEM_CAT_ID
    
    , FM.TRANSP_MODE_CD
    , FM.TM_CARR_ID

    , FM.FEASBL_IND
    , FM.XDOCK_CD
    , FMS.STOP_TYP_CD
    
    , TDC.OWN_TXT
    , TDC.CUST_APPT_DT
    , CAST(TDC.CUST_APPT_DT AS TIMESTAMP(0)) + (TDC.CUST_APPT_TM - TIME '00:00:00' HOUR TO SECOND) AS CUST_APPT_TS
    
    , OD.PLN_MATL_AVL_DT AS MAD_FIRST_DATE
    , OD.PLN_GOODS_ISS_DT AS PGI_FIRST_DATE
    , OD.PLN_DELIV_DT AS FIRST_DATE

FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN NA_BI_VWS.TL_MSTR_CURR TLM
        ON TLM.FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND TLM.SLS_DOC_ID = DDC.ORDER_ID
        AND TLM.SLS_DOC_ITM_ID = DDC.ORDER_LINE_NBR
        AND TLM.SAP_TRANS_CD IN ('YSDTLBATCH', 'YSDTLBUILD')

    INNER JOIN NA_BI_VWS.TL_CAP_DELIV_SCHD_CURR TLC
        ON TLC.CUST_ID = TLM.CUST_ID
        AND TLC.DELIV_DT = TLM.DELIV_DT
        AND TLC.DELIV_GRP_CD = TLM.DELIV_GRP_CD
    
    INNER JOIN NA_BI_VWS.TL_TRLR_MSTR_CURR TRL
        ON TRL.TRLR_TYP_ID = TLC.TRLR_TYP_ID

    -- THIS JOIN HELPS SCRUB DUPLICATE RECORDS FROM TL_MSTR_CURR (DUPLICATES ARE CREATED BY TLB PROGRAM)
    -- VERIFIES THAT FIRST DATES MATCH BETWEEN CURRENT RECORD AND TL_MSTR_CURR
    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND OD.ORDER_ID = DDC.ORDER_ID
        AND OD.ORDER_LINE_NBR = DDC.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = 1
        AND OD.EXP_DT = DATE '5555-12-31'
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.RO_PO_TYPE_IND = 'N'
        AND OD.PLN_DELIV_DT = TLM.DELIV_DT

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = DDC.MATL_ID

    INNER JOIN NA_BI_VWS.TM_FRTMV_DLV_XREF_CURR XREF
        ON XREF.SAP_DELIV_ID_FISCAL_YR = DDC.FISCAL_YR
        AND XREF.SAP_DELIV_ID = DDC.DELIV_ID
        AND XREF.TM_PLN_SCHD_ID LIKE '%GDYR%'

    INNER JOIN NA_BI_VWS.TM_DELIV_CURR TDC
        ON TDC.SAP_DELIV_ID_FISCAL_YR = XREF.SAP_DELIV_ID_FISCAL_YR
        AND TDC.SAP_DELIV_ID = XREF.SAP_DELIV_ID
        AND XREF.TM_DELIV_ID = TDC.TM_DELIV_ID
        AND XREF.TM_PLN_SCHD_ID = TDC.TM_PLN_SCHD_ID
        AND XREF.TM_DELIV_SPLIT_ID = TDC.TM_DELIV_SPLIT_ID

    INNER JOIN NA_BI_VWS.TM_FRT_MVMNT_STOP_CURR FMS
        ON FMS.FRT_MVMNT_ID = XREF.FRT_MVMNT_ID
        AND FMS.FRT_MVMNT_SCHD_ID = XREF.FRT_MVMNT_SCHD_ID
        AND FMS.FRT_MVMNT_STOP_ID = XREF.FRT_MVMNT_STOP_ID
        AND FMS.STOP_TYP_CD = 'DL'

    INNER JOIN NA_BI_VWS.TM_FRT_MVMNT_CURR FM
        ON FM.FRT_MVMNT_ID = XREF.FRT_MVMNT_ID
        AND FM.FRT_MVMNT_SCHD_ID = XREF.FRT_MVMNT_SCHD_ID

WHERE
    DDC.GOODS_ISS_IND = 'Y'
    AND DDC.DELIV_CAT_ID = 'J'
    AND DDC.DELIV_QTY > 0
    AND DDC.ACTL_GOODS_ISS_DT IS NOT NULL
    AND DDC.ACTL_GOODS_ISS_DT BETWEEN CURRENT_DATE-28 AND CURRENT_DATE-1
    --AND DDC.BILL_LADING_ID = '3208035031'

    ) D

GROUP BY
    D.SAP_BILL_LADING_ID

    , D.SHIP_TO_CUST_ID
    , D.SHIP_TO_CUST_NAME
    , D.OWN_CUST_ID
    , D.OWN_CUST_NAME

    , D.DELIV_LINE_FACILITY_ID

    , D.TRLR_TYP_ID
    , D.TRLR_TYP_DESC

    , D.PLN_GOODS_MVT_DT
    , D.ACTL_GOODS_ISS_DT
    , D.DELIV_DT

    , D.WT_UNIT_MEAS_ID
    , D.VOL_UNIT_MEAS_ID
    
/*ORDER BY
    D.DELIV_DT
    , D.SHIP_TO_CUST_ID
    , D.SAP_BILL_LADING_ID*/

