SELECT 
    DDC.FISCAL_YR AS DELIV_FISCAL_YR
	, DDC.DELIV_ID
	, DDC.DELIV_LINE_NBR
	, DDC.ORDER_FISCAL_YR
	, DDC.ORDER_ID
	, DDC.ORDER_LINE_NBR
    , TDC.TM_DELIV_ID
    , TDC.TM_PLN_SCHD_ID
    , TDC.TM_DELIV_SPLIT_ID
    , FMSC.FRT_MVMNT_ID
    , FMSC.FRT_MVMNT_SCHD_ID
    , FMSC.FRT_MVMNT_STOP_ID
    , FMC.BILL_LADING_ID
    , FMC.REF_BOL_ID
    
    , CASE
        WHEN POL.CMPL_IND = 1 AND POL.CMPL_DT < CURRENT_DATE-1
            THEN (CASE
                WHEN POL.PRFCT_ORD_HIT_SORT_KEY = '99'
                    THEN 'FRDD EXCLUDED'
                ELSE 'FRDD COMPLETE'
                END)
        ELSE 'FRDD INCOMPLETE'
        END AS OTD_FRDD_COMPLETE_TEST
    , CASE
        WHEN POL.FRST_PROM_DELIV_DT IS NULL
            THEN 'FCDD EXCLUDED'
        ELSE (CASE
            WHEN POL.FPDD_CMPL_IND = 1 AND POL.FPDD_CMPL_DT < CURRENT_DATE-1
                THEN (CASE
                    WHEN POL.PRFCT_ORD_FPDD_HIT_SORT_KEY = '99'
                        THEN 'FCDD EXCLUDED'
                    ELSE 'FCDD COMPLETE'
                    END)
                ELSE 'FCDD INCOMPLETE'
            END)
        END AS OTD_FCDD_COMPLETE_TEST

	, CNTS.UNQ_ORDER_LN_CNT
	, CNTS.UNQ_MATL_ID_CNT
	, CASE 
		WHEN DWS.DELIV_ID IS NOT NULL
			THEN 'Y'
		ELSE 'N'
		END AS EWM_DATA_AVAILABLE_IND
    , CASE
        WHEN TDC.TM_dELIV_ID IS NOT NULL
            THEN 'Y'
        ELSE 'N'
        END AS TMS_DATA_AVAILABLE_IND
    , DDC.GOODS_ISS_IND
    
	, DDC.DELIV_PRTY_ID
	, SDI.DELIV_GRP_ID
    
	, DDC.BILL_LADING_ID
	, DDC.RTG_ID AS ROUTE_ID
	, DDC.TERMS_ID
	, DDC.UNLD_PT_CD
    
	, CAST(SD.SRC_CRT_DT AS TIMESTAMP (0)) + (SD.SRC_CRT_TM - TIME '00:00:00' HOUR TO SECOND) AS SD_HDR_CRT_TS
	, SDI.SRC_CRT_TS AS SD_ITM_CRT_TS
	, NDDC.SRC_CRT_TS AS DD_HDR_CRT_TS
	, CASE 
		WHEN (SD_ITM_CRT_TS - SD_HDR_CRT_TS) DAY(4) TO MINUTE > INTERVAL '5' MINUTE
			THEN 'Y'
		ELSE 'N'
		END AS SPLIT_LINE_IND
        
	, CASE 
		WHEN EXTRACT(HOUR FROM NDDC.SRC_CRT_TS) < 6
			THEN 'Before 6AM'
		WHEN EXTRACT(HOUR FROM NDDC.SRC_CRT_TS) BETWEEN 6
				AND 12
			THEN 'Between 6AM and Noon'
		WHEN EXTRACT(HOUR FROM NDDC.SRC_CRT_TS) BETWEEN 13
				AND 18
			THEN 'Between Noon and 6PM'
		WHEN EXTRACT(HOUR FROM NDDC.SRC_CRT_TS) BETWEEN 19
				AND 24
			THEN 'After 6PM'
		ELSE 'Indeterminate'
		END AS DELIV_NOTE_DROP_TIME_DESC
        
	, SD.SRC_CRT_USR_ID AS SD_HDR_CRT_USR_ID
	, CAST(CASE 
			WHEN SD.SRC_CRT_USR_ID LIKE ANY ('LD%', 'COWD%')
				THEN 'SYSTEM'
			ELSE 'USER'
			END AS VARCHAR(6)) AS SD_HDR_CRT_USR_TYP
	, SDI.SRC_CRT_USR_ID AS SD_ITM_CRT_USR_ID
	, CAST(CASE 
			WHEN SDI.SRC_CRT_USR_ID LIKE ANY ('LD%', 'COWD%')
				THEN 'SYSTEM'
			ELSE 'USER'
			END AS VARCHAR(6)) AS SD_ITM_CRT_USR_TYP
	, DDC.SRC_CRT_USR_ID AS DN_CRT_USR_ID
	, CAST(CASE 
            WHEN DDC.SRC_CRT_USR_ID LIKE ANY ('LD%', 'COWD%')
				THEN 'SYSTEM'
			ELSE 'USER'
			END AS VARCHAR(6)) AS DN_CRT_USR_TYP
            
	, CUST.SHIP_TO_CUST_ID
	, CUST.SHIP_TO_CUST_ID || ' - ' || CUST.CUST_NAME AS SHIP_TO_CUST
	, CUST.OWN_CUST_ID || ' - ' || CUST.OWN_CUST_NAME AS OWN_CUST
	, CUST.SALES_ORG_CD || ' - ' || CUST.SALES_ORG_NAME AS SALES_ORG
	, CUST.DISTR_CHAN_CD || ' - ' || CUST.DISTR_CHAN_NAME AS DISTR_CHAN
	, CUST.CUST_GRP_ID || ' - ' || CUST.CUST_GRP_NAME AS CUST_GRP
	, CUST.DELIV_PRTY_CD AS CH_DELIV_PRTY_ID
	, CUST.SHIP_COND_ID AS CH_SHIP_COND_ID
	, CUST.TIRE_CUST_TYP_CD
	, CUST.CUST_GRP2_CD AS CH_CUST_GRP2_CD
	, ODS.CUST_GRP2_CD AS ORD_CUST_GRP2_CD
    
	, DDC.MATL_ID
	, MATL.SOP_FAMILY_ID || ' - ' || MATL.SOP_FAMILY_NM AS SOP_FAMILY
	, MATL.TIRE_CUST_TYP_CD
	, MATL.HVA_TXT
	, MATL.HMC_TXT
	, MATL.SAL_IND
    
	/* UNIT WEIGHT AND VOLUME, COMPRESSION_FACTOR CURRNET AS OF 2014-07-01' -- SOURCED FROM AP0 -- YTL_COMPRESSION */
	, MATL.VOL_MEAS_ID
	, MATL.UNIT_VOL
	, CAST(CASE MATL.PBU_NBR || MATL.MKT_AREA_NBR
			WHEN '0101'
				THEN 0.75
			WHEN '0108'
				THEN 0.80
			WHEN '0305'
				THEN 1.20
			WHEN '0314'
				THEN 1.20
			WHEN '0406'
				THEN 1.20
			WHEN '0507'
				THEN 0.75
			WHEN '0711'
				THEN 0.75
			WHEN '0712'
				THEN 0.75
			WHEN '0803'
				THEN 1.20
			WHEN '0923'
				THEN 0.75
			ELSE 1
			END AS DECIMAL(15, 3)) AS COMPRESSION_FACTOR
	, MATL.UNIT_VOL * COMPRESSION_FACTOR AS UNIT_COMPRESSED_VOL
	, MATL.WT_MEAS_ID
	, MATL.UNIT_WT
	/* END OF UNIT-LEVEL DETAILS */
    
	, CUST.PRIM_SHIP_FACILITY_ID
	, DDC.DELIV_LINE_FACILITY_ID
	, DDC.SHIP_FACILITY_ID
	, DDC.FACILITY_ID
	, DDC.SHIP_PT_ID
	, DDC.SHIP_COND_ID
    
	, DDC.QTY_UNIT_MEAS_ID AS QTY_UOM
	, DDC.DELIV_QTY AS DN_DELIV_QTY
	, SDI.SLS_UNIT_CUM_ORD_QTY AS CURR_CUM_ORD_QTY
	, SDI.SLS_UNIT_CUM_REQ_DELIV_QTY AS CURR_CUM_REQ_DELIV_QTY
	, SDI.SLS_UNIT_CUM_CNFRM_QTY AS CURR_CUM_CNFRM_QTY
	, SDIH.SLS_UNIT_CUM_ORD_QTY AS ORIG_CUM_ORD_QTY
	, SDIH.SLS_UNIT_CUM_REQ_DELIV_QTY AS ORIG_CUM_REQ_DELIV_QTY
	, SDIH.SLS_UNIT_CUM_CNFRM_QTY AS ORIG_CUM_CNFRM_QTY
	, DDC.RPT_QTY_UNIT_MEAS_ID AS RPT_QTY_UOM
	, DDC.RPT_DELIV_QTY
	, DDC.WT_UNIT_MEAS_ID AS WT_UOM
	, DDC.GROSS_WT
	, DDC.NET_WT
	, DDC.VOL_UNIT_MEAS_ID AS VOL_UOM
	, DDC.VOL
    
	, DWS.APPT_DT AS LC_APPT_DT
	, DDC.DELIV_NOTE_CREA_DT AS DN_HDR_CRT_DT
	, DDC.DELIV_LINE_CREA_DT AS DN_ITM_CRT_DT
	, DDC.TRANSP_PLN_DT AS DN_TRANSP_PLN_DT
	, DWS.RTE_PLN_DT AS LC_ROUTE_PLAN_DT
	, DDC.PICK_DT AS DN_PICK_DT
	, DWS.LD_PICK_DT AS LC_END_PICK_DATE
	, DDC.LOAD_DT AS DN_LOAD_DT
	, DWS.LD_READY_DT AS LC_READY_BY_DT
	, DDC.PLN_GOODS_MVT_DT AS DN_PLN_GOODS_MVT_DT
	, DDC.ACTL_GOODS_ISS_DT AS DN_ACTL_GOODS_ISS_DT
	, DWS.LD_REL_DT AS LC_RELEASE_DT
	, DDC.DELIV_DT AS SAP_DELIV_DT
    
	, TDC.OWN_TXT AS TM_APPT_IND
	, TDC.CUST_APPT_DT AS TM_CUST_APPT_DT
	, TDC.CUST_APPT_TM AS TM_CUST_APPT_TM
	, TDC.TM_DELIV_TYP_CD
    
    , FMC.FRT_MVMNT_STA_CD
    , FMC.TRANSP_MODE_CD
    , FMC.FROM_TM_LOC_ID
    , FMC.TO_TM_LOC_ID
    , FMC.STOP_QTY AS FMC_STOP_QTY
    , FMC.LANE_ID
    , FMC.TRLR_FILL_IND
    , FMC.EXT_BOL_ID
    , FMC.CARR_REF_ID
    , FMC.MOV_TYP_ID
    , FMC.CMDTY_ID
    , FMC.CMDTY_DESC
    
    , FMSC.STOP_QTY AS FMSC_STOP_QTY
    , FMSC.TM_CARR_ID
    , FMSC.TRLR_TYP_ID
    
    , FMSC.TM_LOC_ID
    , FMSC.STOP_TYP_CD
    , FMSC.WT_QTY
    , FMSC.CU_VOL_QTY
    , FMSC.PC_QTY
    , FMSC.PLLT_QTY
    , FMSC.MI_QTY
    , FMSC.ACTL_GROSS_QTY
    , FMSC.ACTL_PC_QTY
    
    , CAST(FMSC.ACTL_ARRV_DT AS TIMESTAMP (0)) + (FMSC.ACTL_ARRV_TM - TIME '00:00:00' HOUR TO SECOND) AS FMSC_ACTL_ARRIVE_TS
    , CAST(FMSC.ACTL_UNLD_START_DT AS TIMESTAMP (0)) + (FMSC.ACTL_UNLD_START_TM - TIME '00:00:00' HOUR TO SECOND) AS FMSC_ACTL_UNLD_START_TS
    , CAST(FMSC.ACTL_UNLD_END_DT AS TIMESTAMP (0)) + (FMSC.ACTL_UNLD_END_TM - TIME '00:00:00' HOUR TO SECOND) AS FMSC_ACTL_UNLD_END_TS
    , CAST(FMSC.ACTL_DEPART_DT AS TIMESTAMP (0)) + (FMSC.ACTL_DEPART_TM - TIME '00:00:00' HOUR TO SECOND) AS FMSC_ACTL_DEPART_TS
    , CAST(FMSC.CARR_APPT_DT AS TIMESTAMP (0)) + (FMSC.CARR_APPT_TM - TIME '00:00:00' HOUR TO SECOND) AS FMSC_ACTL_CARR_APPT_TS
    , CAST(FMSC.EARLY_DEPART_DT AS TIMESTAMP (0)) + (FMSC.EARLY_DEPART_TM - TIME '00:00:00' HOUR TO SECOND) AS FMSC_EARLY_DEPART_TS
    , CAST(FMSC.LATE_DEPART_DT AS TIMESTAMP (0)) + (FMSC.LATE_DEPART_TM - TIME '00:00:00' HOUR TO SECOND) AS FMSC_LATE_DEPART_TS
    , CAST(FMSC.SRC_CRT_DT AS TIMESTAMP (0)) + (FMSC.SRC_CRT_TM - TIME '00:00:00' HOUR TO SECOND) AS FMSC_CRT_TS
    , CAST(TDC.SRC_UPD_DT AS TIMESTAMP (0)) + (TDC.SRC_UPD_TM - TIME '00:00:00' HOUR TO SECOND) AS TM_SRC_UPD_TS
    
    , FMSC.DEPART_TRANSIT_DELAY_ID
    , FMSC.ARRV_TRANSIT_DELAY_ID
    
    , POL.CMPL_DT AS FRDD_CMPL_DT
	, POL.CMPL_DT - (EXTRACT(DAY FROM POL.CMPL_DT) - 1) AS FRDD_CMPL_MTH
	, POL.FPDD_CMPL_DT AS FCDD_CMPL_DT
	, POL.FPDD_CMPL_DT - (EXTRACT(DAY FROM POL.FPDD_CMPL_DT) - 1) AS FCDD_CMPL_MTH
	, POL.CMPL_IND AS FRDD_CMPL_IND
	, POL.FPDD_CMPL_IND AS FCDD_CMPL_IND
    
	, NULLIF(POL.CAN_REJ_REAS_ID, '') AS CAN_REJ_REAS_ID
	, NULLIF(POL.PO_TYPE_ID, '') AS PO_TYPE_ID
	, CASE 
		WHEN POL.CREDIT_HOLD_FLG = 'Y'
			THEN 'Y'
		ELSE 'N'
		END AS CREDIT_HOLD_FLG
	, CASE 
		WHEN POL.DELIV_BLK_IND = 'Y'
			THEN 'Y'
		ELSE 'N'
		END AS DELIV_BLK_IND
	, CASE 
		WHEN POL.CANCEL_IND = 'Y'
			THEN 'Y'
		ELSE 'N'
		END AS CANCEL_IND
	, POL.A_IND
	, POL.R_IND
	, NULLIF(POL.SPCL_PROC_ID, '') AS SPCL_PROC_ID
	, POL.FMAD_DT AS FRDD_FMAD
	, POL.FPGI_DT AS FRDD_FPGI
	, POL.REQ_DELIV_DT AS FRDD
	, FCDD - (FRDD - FRDD_FMAD) AS FCDD_FMAD
	, FCDD - (FRDD - FRDD_FPGI) AS FCDD_FPGI
	, POL.FRST_PROM_DELIV_DT AS FCDD
    
	, POL.CUST_APPT_DT
	, POL.MAX_DELIV_NOTE_CREA_DT
	, POL.MAX_EDI_DELIV_DT
	, POL.MAX_SAP_DELIV_DT
	, POL.ACTL_DELIV_DT
	, POL.NO_STK_DT AS FRDD_NO_STOCK_DT
	, POL.FPDD_NO_STK_DT AS FCDD_NO_STOCK_DT
    
	, POL.PRFCT_ORD_HIT_DESC AS FRDD_HIT_DESC
	, POL.PRFCT_ORD_HIT_SORT_KEY AS FRDD_HIT_SORT_KEY
	, ZEROIFNULL(POL.ORIG_ORD_QTY) AS ORIG_ORDER_QTY
	, ZEROIFNULL(POL.CANCEL_QTY) AS CANCEL_QTY
	, ZEROIFNULL(POL.CURR_ORD_QTY) AS FRDD_ORDER_QTY
	, ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY) AS FRDD_HIT_QTY
	, ZEROIFNULL(POL.CURR_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_HIT_QTY) AS FRDD_ONTIME_QTY
	, ZEROIFNULL(POL.REL_LATE_QTY) AS FRDD_REL_LATE_QTY
	, ZEROIFNULL(POL.REL_ONTIME_QTY) AS FRDD_REL_ONTIME_QTY
	, ZEROIFNULL(POL.COMMIT_ONTIME_QTY) AS FRDD_COMMIT_ONTIME_QTY
	, ZEROIFNULL(POL.DELIV_LATE_QTY) AS FRDD_DELIV_LATE_QTY
	, ZEROIFNULL(POL.DELIV_ONTIME_QTY) AS FRDD_DELIV_ONTIME_QTY
	, ZEROIFNULL(POL.NE_HIT_RT_QTY) AS FRDD_RETURN_HIT_QTY
	, ZEROIFNULL(POL.NE_HIT_CL_QTY) AS FRDD_CLAIM_HIT_QTY
	, ZEROIFNULL(POL.OT_HIT_FP_QTY) AS FRDD_FREIGHT_POLICY_HIT_QTY
	, ZEROIFNULL(POL.OT_HIT_CARR_PICKUP_QTY) + ZEROIFNULL(POL.OT_HIT_WI_QTY) AS FRDD_PHYS_LOG_HIT_QTY
	, ZEROIFNULL(POL.OT_HIT_MB_QTY) AS FRDD_MAN_BLK_HIT_QTY
	, ZEROIFNULL(POL.OT_HIT_CH_QTY) AS FRDD_CREDIT_HOLD_HIT_QTY
	, ZEROIFNULL(POL.IF_HIT_NS_QTY) AS FRDD_NO_STOCK_HIT_QTY
	, ZEROIFNULL(POL.IF_HIT_CO_QTY) AS FRDD_CANCEL_HIT_QTY
	, ZEROIFNULL(POL.OT_HIT_CG_QTY) AS FRDD_CUST_GEN_HIT_QTY
	, ZEROIFNULL(POL.OT_HIT_CG_99_QTY) AS FRDD_MAN_REL_CUST_GEN_HIT_QTY
	, ZEROIFNULL(POL.OT_HIT_99_QTY) AS FRDD_MAN_REL_HIT_QTY
	, ZEROIFNULL(POL.OT_HIT_LO_QTY) AS FRDD_OTHER_HIT_QTY
    
	, POL.PRFCT_ORD_FPDD_HIT_DESC AS FCDD_HIT_DESC
	, POL.PRFCT_ORD_FPDD_HIT_SORT_KEY AS FCDD_HIT_SORT_KEY
	, ZEROIFNULL(POL.FPDD_ORD_QTY) AS FCDD_ORDER_QTY
	, ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY) AS FCDD_HIT_QTY
	, ZEROIFNULL(POL.FPDD_ORD_QTY) - ZEROIFNULL(POL.PRFCT_ORD_FPDD_HIT_QTY) AS FCDD_ONTIME_QTY
	, ZEROIFNULL(POL.DELIV_FPDD_LATE_QTY) AS FCDD_DELIV_LATE_QTY
	, ZEROIFNULL(POL.DELIV_FPDD_ONTIME_QTY) AS FCDD_DELIV_ONTIME_QTY
	, ZEROIFNULL(POL.FPDD_COMMIT_ONTIME_QTY) AS FCDD_COMMIT_ONTIME_QTY
	, ZEROIFNULL(POL.REL_FPDD_LATE_QTY) AS FCDD_REL_LATE_QTY
	, ZEROIFNULL(POL.REL_FPDD_ONTIME_QTY) AS FCDD_REL_ONTIME_QTY
	, ZEROIFNULL(POL.NE_FPDD_HIT_RT_QTY) AS FCDD_RETURN_HIT_QTY
	, ZEROIFNULL(POL.NE_FPDD_HIT_CL_QTY) AS FCDD_CLAIM_HIT_QTY
	, ZEROIFNULL(POL.OT_FPDD_HIT_FP_QTY) AS FCDD_FREIGHT_POLICY_HIT_QTY
	, ZEROIFNULL(POL.OT_FPDD_HIT_CARR_QTY) + ZEROIFNULL(POL.OT_FPDD_HIT_WI_QTY) AS FCDD_PHYS_LOG_HIT_QTY
	, ZEROIFNULL(POL.OT_FPDD_HIT_MB_QTY) AS FCDD_MAN_BLK_HIT_QTY
	, ZEROIFNULL(POL.OT_FPDD_HIT_CH_QTY) AS FCDD_CREDIT_HOLD_HIT_QTY
	, ZEROIFNULL(POL.IF_FPDD_HIT_NS_QTY) AS FCDD_NO_STOCK_HIT_QTY
	, ZEROIFNULL(POL.IF_FPDD_HIT_CO_QTY) AS FCDD_CANCEL_HIT_QTY
	, ZEROIFNULL(POL.OT_FPDD_HIT_CG_QTY) AS FCDD_CUST_GEN_HIT_QTY
	, ZEROIFNULL(POL.OT_FPDD_HIT_CG_99_QTY) AS FCDD_MAN_REL_CUST_GEN_HIT_QTY
	, ZEROIFNULL(POL.OT_FPDD_HIT_99_QTY) AS FCDD_MAN_REL_HIT_QTY
	, ZEROIFNULL(POL.OT_FPDD_HIT_LO_QTY) AS FCDD_OTHER_HIT_QTY
    
FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN NA_BI_VWS.TM_FRTMV_DLV_XREF_CURR XREF
        ON XREF.SAP_DELIV_ID_FISCAL_YR = DDC.FISCAL_YR
            AND XREF.SAP_DELIV_ID = DDC.DELIV_ID
            
    /* TMS DATA */
    INNER JOIN NA_BI_VWS.TM_DELIV_CURR TDC
    	ON TDC.TM_DELIV_ID = XREF.TM_DELIV_ID
    		AND TDC.TM_PLN_SCHD_ID = XREF.TM_PLN_SCHD_ID
            AND TDC.TM_DELIV_SPLIT_ID = XREF.TM_DELIV_SPLIT_ID
    
    INNER JOIN NA_BI_VWS.TM_FRT_MVMNT_CURR FMC
        ON FMC.FRT_MVMNT_ID = XREF.FRT_MVMNT_ID
            AND FMC.FRT_MVMNT_SCHD_ID = XREF.FRT_MVMNT_SCHD_ID
    
    INNER JOIN NA_BI_vWS.TM_FRT_MVMNT_STOP_CURR FMSC
        ON FMSC.FRT_MVMNT_ID = XREF.FRT_MVMNT_ID
            AND FMSC.FRT_MVMNT_SCHD_ID = XREF.FRT_MVMNT_SCHD_ID
            AND FMSC.FRT_MVMNT_STOP_ID = XREF.FRT_MVMNT_STOP_ID
    /* TMS DATA */
    
    -- AP0-LIKP / DELIVERY HEADER
    INNER JOIN NA_BI_VWS.NAT_DELIV_DOC_CURR NDDC
    	ON NDDC.FISCAL_YR = DDC.FISCAL_YR
    		AND NDDC.DELIV_DOC_ID = DDC.DELIV_ID
    
    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
    	ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID
    		AND CUST.PRIM_SHIP_FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID
            
    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
    	ON MATL.MATL_ID = DDC.MATL_ID
    		AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
    		AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')
    
    -- ORDER DETAIL CURR @ ORDER LINE SUMMARY
    INNER JOIN NA_BI_VWS.ORD_DTL_SMRY ODS
    	ON ODS.ORDER_FISCAL_YR = DDC.ORDER_FISCAL_YR
    		AND ODS.ORDER_ID = DDC.ORDER_ID
    		AND ODS.ORDER_LINE_NBR = DDC.ORDER_LINE_NBR
    		AND ODS.ORDER_CAT_ID = 'C'
    		AND ODS.PO_TYPE_ID <> 'RO'
    		AND ODS.CUST_GRP2_CD = 'TLB'
    		AND ODS.SHIP_COND_ID IN ('ST', 'PT')
    
    -- ON TIME DELIEVRY METRIC DETAILS
    INNER JOIN NA_BI_VWS.PRFCT_ORD_LINE POL
    	ON POL.ORDER_ID = ODS.ORDER_ID
    		AND POL.ORDER_LINE_NBR = ODS.ORDER_LINE_NBR
    
    -- EWM DATA
    LEFT JOIN NA_BI_VWS.DELIV_WHSE_SCHD DWS
    	ON DWS.DELIV_FISCAL_YR = DDC.FISCAL_YR
    		AND DWS.DELIV_ID = DDC.DELIV_ID
    
    -- VBAK / SALES DOC HEADER
    INNER JOIN NA_BI_VWS.NAT_SLS_DOC SD
    	ON SD.EXP_DT = DATE '5555-12-31'
    		AND SD.FISCAL_YR = DDC.ORDER_FISCAL_YR
    		AND SD.SLS_DOC_ID = DDC.ORDER_ID
    
    -- VBAP / SALES DOC ITEM
    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM_CURR SDI
    	ON SDI.FISCAL_YR = DDC.ORDER_FISCAL_YR
    		AND SDI.SLS_DOC_ID = DDC.ORDER_ID
    		AND SDI.SLS_DOC_ITM_ID = DDC.ORDER_LINE_NBR
    		AND SDI.DELIV_GRP_ID > 0
    
    -- SALES DOC ITEM'S SATUS ON THE HEADER CREATE DATE
    LEFT JOIN NA_BI_VWS.NAT_SLS_DOC_ITM SDIH
    	ON SD.SRC_CRT_DT BETWEEN SDIH.EFF_DT AND SDIH.EXP_DT
    		AND SDIH.FISCAL_YR = DDC.ORDER_FISCAL_YR
    		AND SDIH.SLS_DOC_ID = DDC.ORDER_ID
    		AND SDIH.SLS_DOC_ITM_ID = DDC.ORDER_LINE_NBR
    
    INNER JOIN (
    	SELECT 
            DDC.FISCAL_YR
    		, DDC.DELIV_ID
    		, COUNT(DISTINCT DDC.ORDER_FISCAL_YR || DDC.ORDER_ID || DDC.ORDER_LINE_NBR) AS UNQ_ORDER_LN_CNT
    		, COUNT(DISTINCT DDC.MATL_ID) AS UNQ_MATL_ID_CNT
    		, COUNT(CASE 
    				WHEN (SDI.SRC_CRT_TS - (CAST(SD.SRC_CRT_DT AS TIMESTAMP (0)) + (SD.SRC_CRT_TM - TIME '00:00:00' HOUR TO SECOND)) DAY(4) TO MINUTE) > INTERVAL '5' MINUTE
    					THEN 'Y'
    				END) AS SPLIT_LINE_CNT
    	FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC
    	INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_CURR CUST
    		ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID
    			AND CUST.PRIM_SHIP_FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID
    	INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR MATL
    		ON MATL.MATL_ID = DDC.MATL_ID
    			AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')
    			AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
    	INNER JOIN NA_BI_VWS.ORD_DTL_SMRY ODS
    		ON ODS.ORDER_FISCAL_YR = DDC.ORDER_FISCAL_YR
    			AND ODS.ORDER_ID = DDC.ORDER_ID
    			AND ODS.ORDER_LINE_NBR = DDC.ORDER_LINE_NBR
    			AND ODS.ORDER_CAT_ID = 'C'
    			AND ODS.PO_TYPE_ID <> 'RO'
    			AND ODS.CUST_GRP2_CD = 'TLB'
    			AND ODS.SHIP_COND_ID IN ('ST', 'PT')
    	INNER JOIN NA_BI_VWS.NAT_SLS_DOC SD
    		ON SD.EXP_DT = DATE '5555-12-31'
    			AND SD.FISCAL_YR = DDC.ORDER_FISCAL_YR
    			AND SD.SLS_DOC_ID = DDC.ORDER_ID
    	INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM_CURR SDI
    		ON SDI.FISCAL_YR = DDC.ORDER_FISCAL_YR
    			AND SDI.SLS_DOC_ID = DDC.ORDER_ID
    			AND SDI.SLS_DOC_ITM_ID = DDC.ORDER_LINE_NBR
    			AND SDI.DELIV_GRP_ID > 0
    	WHERE 
            DDC.FISCAL_YR = '2014'
    		AND DDC.DELIV_NOTE_CREA_DT BETWEEN DATE '2014-01-01' AND (CURRENT_DATE - 1)
    		AND DDC.DELIV_CAT_ID = 'J'
    		AND DDC.DELIV_QTY > 0
    	GROUP BY 
            DDC.FISCAL_YR
    		, DDC.DELIV_ID
    	) CNTS
    	ON CNTS.FISCAL_YR = DDC.FISCAL_YR
    		AND CNTS.DELIV_ID = DDC.DELIV_ID
            
WHERE 
    DDC.FISCAL_YR = '2014'
	AND DDC.DELIV_NOTE_CREA_DT = (CURRENT_DATE - 1) -- BETWEEN DATE '2014-07-01' AND (CURRENT_DATE-1)
	AND DDC.DELIV_CAT_ID = 'J'
	AND DDC.DELIV_QTY > 0

/*
QUALIFY
    COUNT(*) OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID, DDC.DELIV_LINE_NBR) > 1
*/

ORDER BY 
    DDC.ORDER_FISCAL_YR
	, DDC.ORDER_ID
	, DDC.ORDER_LINE_NBR
	, DDC.FISCAL_YR
	, DDC.DELIV_ID
	, DDC.DELIV_LINE_NBR