SELECT
    TLM.FISCAL_YR
    , TLM.SLS_DOC_ID
    , TLM.SLS_DOC_ITM_ID
    
    , TLM.CUST_ID
    , CUST.CUST_NAME
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    
    , TLM.DELIV_GRP_CD
    
    , CUST.PRIM_SHIP_FACILITY_ID
    , TLM.FACILITY_ID
    , TLM.SHIP_RCVE_PT_CD
    
    , TLM.MATL_ID
    , MATL.DESCR
    , MATL.PBU_NBR
    , MATL.PBU_NAME
    
    , TLM.DELIV_DT
    , TLM.MATL_AVL_DT
    
    , OD.QTY_UNIT_MEAS_ID
    , TLM.ITM_QTY
    
    , TLC.TRLR_TYP_ID
    , OD.WT_UNITS_MEAS_ID
    , TLM.GROSS_WT_QTY
    , TLC.MIN_WT_QTY
    , TLT.MAX_WT_QTY
    
    , OD.VOL_UNIT_MEAS_ID
    , TLM.VOL_QTY
    , TLT.VOL_QTY AS MAX_VOL_QTY
    
    , TLC.TL_PLN_CD
    , TLM.SRC_CRT_USR_ID
    , TLM.SAP_TRANS_CD
    
    , TLC.TL_SEQ_ID
    , TLC.RPT_TL_SEQ_ID
    
    , OD.ORDER_DT
    , OD.ORDER_LN_CRT_DT
    , OD.ORDER_LN_CRT_TM
    , OD.ORDER_CREATOR
    , OD.SHIP_COND_ID
    , OD.DELIV_PRTY_ID
    , OD.ROUTE_ID
    , OD.CUST_GRP2_CD
    
    , OD.CUST_RDD AS ORDD
    
    , OD.FRST_MATL_AVL_DT AS FRDD_FMAD
    , OD.FRST_PLN_GOODS_ISS_DT AS FRDD_FPGI
    , OD.FRST_RDD AS FRDD
    
    , OD.PLN_MATL_AVL_DT AS MAD_FIRST_DATE
    , OD.PLN_GOODS_ISS_DT AS PGI_FIRST_DATE
    , OD.PLN_DELIV_DT AS FIRST_DATE
    
    , OD.ORDER_DELIV_BLK_CD
    , OD.DELIV_BLK_CD
    
    , OD.CUST_PO_NBR
    , OD.PO_TYPE_ID
    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID

FROM NA_BI_VWS.TL_MSTR_CURR TLM

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = TLM.CUST_ID
    
    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = TLM.MATL_ID

    INNER JOIN NA_BI_VWS.TL_CAP_DELIV_SCHD_CURR TLC
        ON TLC.CUST_ID = TLM.CUST_ID
        AND TLC.DELIV_DT = TLM.DELIV_DT
        AND TLC.DELIV_GRP_CD = TLM.DELIV_GRP_CD
        AND TLC.TL_PLN_CD IN ('X', 'M')

    INNER JOIN NA_BI_VWS.TL_TRLR_MSTR_CURR TLT
        ON TLT.TRLR_TYP_ID = TLC.TRLR_TYP_ID

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.EXP_DT = DATE '5555-12-31'
        AND OD.ORDER_FISCAL_YR = TLM.FISCAL_YR
        AND OD.ORDER_ID = TLM.SLS_DOC_ID
        AND OD.ORDER_LINE_NBR = TLM.SLS_DOC_ITM_ID
        AND OD.SCHED_LINE_NBR = 1
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.RO_PO_TYPE_IND = 'N'

WHERE
    TLM.SAP_TRANS_CD IN ('YSDTLBATCH', 'YSDTLBUILD')
    AND TLM.MATL_AVL_DT BETWEEN CURRENT_DATE+1 AND CURRENT_DATE+14

ORDER BY
    TLM.FISCAL_YR
    , TLM.SLS_DOC_ID
    , TLM.SLS_DOC_ITM_ID
