SELECT
    SQ.SHIP_TO_CUST_ID,
    SQ.SHIP_TO_CUST_NAME,
    SQ.OWN_CUST_ID,
    SQ.OWN_CUST_NAME,
    SQ.FACILITY_ID,
    SQ.FRDD,
    SQ.FCDD,
    SUM( SQ.ORDER_QTY ) AS ORDER_QTY,
    SUM( SQ.CNFRM_QTY ) AS CNFRM_QTY,
    SUM( SQ.CNFRM_QTY * SQ.UNIT_WT ) AS WT,
    SUM( SQ.CNFRM_QTY * SQ.UNIT_COMPRESSED_VOL ) AS CMP_VOL,
    SQ.VOL_UOM,
    SQ.WT_UOM,
    SQ.QTY_UOM

FROM (

SELECT
    Q.SHIP_TO_CUST_ID,
    Q.SHIP_TO_CUST_NAME,
    Q.OWN_CUST_ID,
    Q.OWN_CUST_NAME,
    Q.FACILITY_ID,
    Q.FRDD,
    Q.FCDD,
    SUM( Q.ORDER_QTY ) AS ORDER_QTY,
    SUM( Q.CNFRM_QTY ) AS CNFRM_QTY,
    SUM( Q.OPEN_CNFRM_QTY ) AS OPEN_CNFRM_QTY,
    SUM( Q.UNCNFRM_QTY ) AS UNCNFRM_QTY,
    SUM( Q.BACK_ORDER_QTY ) AS BACK_ORDER_QTY,
    Q.UNIT_WT,
    Q.UNIT_VOL,
    Q.UNIT_COMPRESSED_VOL,
    Q.VOL_UOM,
    Q.WT_UOM,
    Q.QTY_UOM

FROM (

SELECT
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    ODC.SCHED_LINE_NBR,

    ODC.SHIP_TO_CUST_ID,
    CUST.CUST_NAME AS SHIP_TO_CUST_NAME,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,
    ODC.SALES_ORG_CD,
    ODC.DISTR_CHAN_CD,
    ODC.CO_CD,
    ODC.DIV_CD,

    ODC.MATL_ID,
    CAST( CASE MATL.PBU_NBR || MATL.MKT_AREA_NBR
        WHEN '0101'
            THEN 0.75
        WHEN '0108'
            THEN 0.80
        WHEN '0305'
            THEN 1.20
        WHEN '0314'
            THEN 1.20
        ELSE 1
    END AS DECIMAL(15,3) ) AS COMPRESSION_FACTOR,

    ODC.FACILITY_ID,
    ODC.SHIP_PT_ID,

    ODC.CUST_GRP2_CD,
    ODC.ORDER_CAT_ID,
    ODC.ORDER_TYPE_ID,
    ODC.PO_TYPE_ID,
    ODC.DELIV_BLK_CD,
    ODC.ORDER_CREATOR,
    ODC.SHIP_COND_ID,
    ODC.PRTL_DLVY_CD,
    ODC.REJ_REAS_ID,
    ODC.DELIV_PRTY_ID,
    ODC.ROUTE_ID,
    ODC.DELIV_GRP_CD,
    ODC.CANCEL_DT,

    ODC.QTY_UNIT_MEAS_ID AS QTY_UOM,
    ODC.ORDER_QTY,
    ODC.CNFRM_QTY,
    OOL.OPEN_CNFRM_QTY,
    OOL.UNCNFRM_QTY,
    OOL.BACK_ORDER_QTY,

    ODC.WT_UNITS_MEAS_ID AS WT_UOM,
    ODC.NET_WT,
    ODC.GROSS_WT,
    SUM( ODC.GROSS_WT ) OVER ( PARTITION BY ODC.MATL_ID ) / SUM( ODC.ORDER_QTY ) OVER ( PARTITION BY ODC.MATL_ID ) AS UNIT_WT,

    ODC.VOL_UNIT_MEAS_ID AS VOL_UOM,
    ZEROIFNULL( ODC.VOL ) * COMPRESSION_FACTOR AS COMPRESSED_VOL,
    ODC.VOL,
    SUM( ODC.VOL ) OVER ( PARTITION BY ODC.MATL_ID ) / SUM( ODC.ORDER_QTY ) OVER ( PARTITION BY ODC.MATL_ID ) AS UNIT_VOL,
    SUM( COMPRESSED_VOL ) OVER ( PARTITION BY ODC.MATL_ID ) / SUM( ODC.ORDER_QTY ) OVER ( PARTITION BY ODC.MATL_ID ) AS UNIT_COMPRESSED_VOL,

    ODC.ORDER_DT,
    ODC.FRST_RDD AS FRDD,
    ODC.FRST_PROM_DELIV_DT AS FCDD

FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID
        AND MATL.PBU_NBR IN ( '01', '03', '04', '05', '07', '08', '09' )

    LEFT OUTER JOIN NA_BI_VWS.OPEN_ORDER_ORDLN_CURR OOL
        ON OOL.ORDER_ID = ODC.ORDER_ID
        AND OOL.ORDER_LINE_NBR = ODC.ORDER_LINE_NBR
        AND ( OOL.OPEN_CNFRM_QTY > 0 OR OOL.UNCNFRM_QTY > 0 OR OOL.BACK_ORDER_QTY > 0 )

WHERE
    ODC.CUST_GRP2_CD = 'TLB'
    AND ODC.ORDER_CAT_ID = 'C'
    AND ODC.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
    AND ODC.PO_TYPE_ID <> 'RO'
    AND ODC.SHIP_COND_ID NOT IN ( '', 'EG' )
    AND FRDD >= DATE '2014-02-01'
    AND FRDD = FCDD

    ) Q

GROUP BY
    Q.SHIP_TO_CUST_ID,
    Q.SHIP_TO_CUST_NAME,
    Q.OWN_CUST_ID,
    Q.OWN_CUST_NAME,
    Q.FACILITY_ID,
    Q.FRDD,
    Q.FCDD,
    Q.UNIT_WT,
    Q.UNIT_VOL,
    Q.UNIT_COMPRESSED_VOL,
    Q.VOL_UOM,
    Q.WT_UOM,
    Q.QTY_UOM

    ) SQ

GROUP BY
    SQ.SHIP_TO_CUST_ID,
    SQ.SHIP_TO_CUST_NAME,
    SQ.OWN_CUST_ID,
    SQ.OWN_CUST_NAME,
    SQ.FACILITY_ID,
    SQ.FRDD,
    SQ.FCDD,
    SQ.VOL_UOM,
    SQ.WT_UOM,
    SQ.QTY_UOM

ORDER BY
    SQ.SHIP_TO_CUST_ID,
    SQ.SHIP_TO_CUST_NAME,
    SQ.OWN_CUST_ID,
    SQ.OWN_CUST_NAME,
    SQ.FACILITY_ID,
    SQ.FRDD