SELECT
    Q.MSTR_BOL,
    Q.DELIV_DATE,
    Q.SHIP_TO_CUST_ID,
    Q.MATL_ID,
    Q.QTY_UOM,
    SUM( Q.DELIV_QTY ) AS DELIV_QTY,
    Q.VOL_UOM,
    SUM( Q.VOL ) AS VOL,
    Q.WT_UOM,
    SUM( Q.NET_WT ) AS NET_WT,
    SUM( Q.GROSS_WT ) AS GROSS_WT

FROM (

SELECT
    DDC.FISCAL_YR,
    DDC.DELIV_ID,
    DDC.DELIV_LINE_NBR,
    DDC.ORDER_ID,
    DDC.ORDER_LINE_NBR,
    
    DDC.SHIP_TO_CUST_ID,
    DDC.CUST_GRP_ID,
    DDC.CUST_GRP2_CD,
    DDC.SALES_ORG_CD,
    DDC.DISTR_CHAN_CD,
    
    DDC.MATL_ID,
    
    NULLIF( DDC.FACILITY_ID, '' ) AS FACILITY_ID,
    NULLIF( DDC.DELIV_LINE_FACILITY_ID, '' ) AS DELIV_LINE_FACILITY_ID,
    NULLIF( DDC.SHIP_PT_ID, '' ) AS SHIP_PT_ID,
    NULLIF( DDC.SHIP_FACILITY_ID, '' ) AS SHIP_FACILITY_ID,
    
    CAST( CASE WHEN DDC.RETURN_IND = 'Y' THEN 'Y' ELSE 'N' END AS CHAR(1) ) AS RETURN_IND,
    
    NULLIF( DDC.DELIV_TYPE_ID, '' ) AS DELIV_TYPE_ID,
    NULLIF( DDC.DELIV_CAT_ID, '' ) AS DELIV_CAT_ID,
    NULLIF( DDC.DELIV_PRTY_ID, '' ) AS DELIV_PRTY_ID,
    NULLIF( DDC.TERMS_ID, '' ) AS TERMS_ID,
    NULLIF( DDC.UNLD_PT_CD, '' ) AS UNLD_PT_CD,
    NULLIF( DDC.SPCL_PROC_ID, '' ) AS SPCL_PROC_ID,
    NULLIF( DDC.PRM_SHIP_CARR_CD, '' ) AS PRM_SHIP_CARR_CD,
    NULLIF( DDC.TRANSP_VEH_NO, '' ) AS TRANSP_VEH_NO,
    NULLIF( DDC.SRC_CRT_USR_ID, '' ) AS SRC_CRT_USR_ID,
    NULLIF( DDC.BILL_LADING_ID, '' ) AS BILL_LADING_ID,
    NULLIF( DDC.SHIP_COND_ID, '' ) AS SHIP_COND_ID,
    
    DDC.DELIV_NOTE_CREA_DT,
    DDC.DELIV_LINE_CREA_DT,
    DDC.LOAD_DT,
    DDC.PICK_DT,
    DDC.ACTL_GOODS_ISS_DT,
    DDC.DELIV_DT,
    DDC.PLN_GOODS_MVT_DT,
    DDC.NXT_PLN_DELIV_DT,
    
    ZEROIFNULL( DDC.DELIV_QTY ) AS DELIV_QTY,
    DDC.QTY_UNIT_MEAS_ID AS QTY_UOM,
    CASE MATL.PBU_NBR || MATL.MKT_AREA_NBR
        WHEN 
        
    
    ZEROIFNULL( DDC.VOL ) AS VOL,
    DDC.VOL_UNIT_MEAS_ID AS VOL_UOM,
    ZEROIFNULL( DDC.NET_WT ) AS NET_WT,
    ZEROIFNULL( DDC.GROSS_WT ) AS GROSS_WT,
    DDC.WT_UNIT_MEAS_ID AS WT_UOM,
    
    FPS.MSTR_BOL,
    --FPC.SHIP_TS,
    CAST( FPC.SHIP_TS AS DATE ) AS SHIP_DT,
    --FPC.DELIV_TS,
    CAST( FPC.DELIV_TS AS DATE ) AS DELIV_DATE

FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_vWS.NAT_MATL_HIER_dESCR_EN_CURR MATL
        ON MATL.MATL_ID = DDC.MATL_ID

    INNER JOIN GDYR_BI_VWS.FP_SHP_ORD_LN_CST_CURR FPS
        ON FPS.ORD_ID = DDC.DELIV_ID
        AND FPS.MATL_ID = DDC.MATL_ID
        
    INNER JOIN GDYR_BI_VWS.FP_SHP_CURR FPC
        ON FPC.MSTR_BOL = FPS.MSTR_BOL
        AND CAST( FPC.DELIV_TS AS DATE ) < CURRENT_DATE

WHERE
    DDC.DELIV_QTY > 0
    AND DDC.DELIV_DT < CURRENT_DATE
    AND NULLIF( DDC.SHIP_COND_ID, '' ) IS NOT NULL
    AND NULLIF( DDC.SHIP_COND_ID, '' ) <> 'EG'
    AND DDC.MATL_ID IN ( SELECT M.MATL_ID FROM GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR  M WHERE M.PBU_NBR IN ( '01', '03', '04', '05', '07', '08', '09' ) )
    -- SUBQUERY TO SELECT MATCHING DELIVERIES WITH RESPECT TO ORDER_DETAIL_CURR QUERY
    AND ( DDC.ORDER_ID, DDC.ORDER_LINE_NBR ) IN (
        SELECT
            ODC.ORDER_ID,
            ODC.ORDER_LINE_NBR
        FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC
        WHERE
            ODC.ORDER_CAT_ID = 'C'
            AND ODC.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
            AND ODC.PO_TYPE_ID <> 'RO'
            AND ODC.ORDER_DT >= CAST( SUBSTR( CAST( ADD_MONTHS( CURRENT_DATE, -6 ) AS CHAR(10) ), 1, 7 ) || '-01' AS DATE ) 
            AND ODC.SHIP_COND_ID NOT IN ( 'EG', '' )
            AND NULLIF( ODC.SHIP_COND_ID, '' ) IS NOT NULL
            AND ODC.CUST_GRP2_CD = 'TLB'
        GROUP BY
            ODC.ORDER_ID,
            ODC.ORDER_LINE_NBR
    )

GROUP BY
    DDC.FISCAL_YR,
    DDC.DELIV_ID,
    DDC.DELIV_LINE_NBR,
    DDC.ORDER_ID,
    DDC.ORDER_LINE_NBR,
    
    DDC.SHIP_TO_CUST_ID,
    DDC.CUST_GRP_ID,
    DDC.CUST_GRP2_CD,
    DDC.SALES_ORG_CD,
    DDC.DISTR_CHAN_CD,
    
    DDC.MATL_ID,
    
    FACILITY_ID,
    DELIV_LINE_FACILITY_ID,
    SHIP_PT_ID,
    SHIP_FACILITY_ID,
    
    RETURN_IND,
    
    DELIV_TYPE_ID,
    DELIV_CAT_ID,
    DELIV_PRTY_ID,
    TERMS_ID,
    UNLD_PT_CD,
    SPCL_PROC_ID,
    PRM_SHIP_CARR_CD,
    TRANSP_VEH_NO,
    SRC_CRT_USR_ID,
    BILL_LADING_ID,
    SHIP_COND_ID,
    
    DDC.DELIV_NOTE_CREA_DT,
    DDC.DELIV_LINE_CREA_DT,
    DDC.LOAD_DT,
    DDC.PICK_DT,
    DDC.ACTL_GOODS_ISS_DT,
    DDC.DELIV_DT,
    DDC.PLN_GOODS_MVT_DT,
    DDC.NXT_PLN_DELIV_DT,
    
    DELIV_QTY,
    QTY_UOM,
    VOL,
    VOL_UOM,
    NET_WT,
    GROSS_WT,
    WT_UOM,
    
    FPS.MSTR_BOL,
    --FPC.SHIP_TS,
    SHIP_DT,
    --FPC.DELIV_TS,
    DELIV_DATE

    ) Q
    
GROUP BY
    Q.MSTR_BOL,
    Q.DELIV_DATE,
    Q.SHIP_TO_CUST_ID,
    Q.MATL_ID,
    Q.QTY_UOM,
    Q.VOL_UOM,
    Q.WT_UOM
    