/*
Truckload Build - Historical Build

Created: 2014-04-24

This query pulls current Order ID & Order Lines which currently show zero open conifirmed, back ordered,
unconfirmed, deferred or wait list quantity (sourced from NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR).
*/


SELECT
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,

    ODC.SHIP_TO_CUST_ID,
    CUST.CUST_NAME AS SHIP_TO_CUST_NAME,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,

    ODC.FACILITY_ID,
    FAC.XTND_NAME AS FACILITY_NAME,
    ODC.SHIP_PT_ID,

    ODC.MATL_ID,
    MATL.DESCR,
    MATL.PBU_NBR,
    MATL.PBU_NAME,
    MATL.MKT_AREA_NBR,
    MATL.MKT_AREA_NAME,
    CAST( CASE MATL.PBU_NBR || MATL.MKT_AREA_NBR
        WHEN '0101'
            THEN 0.75
        WHEN '0108'
            THEN 0.80
        WHEN '0305'
            THEN 1.20
        WHEN '0314'
            THEN 1.20
        ELSE 1.00
    END AS DECIMAL(15,3) ) AS COMPRESSION_FACTOR,
    MATL.UNIT_WT,
    MATL.UNIT_VOL,
    MATL.UNIT_VOL * COMPRESSION_FACTOR AS UNIT_COMPRESS_VOL,

    CASE
        WHEN ODC.ORDER_CREATOR IS NULL
            THEN 'MISSING'
        WHEN ODC.ORDER_CREATOR LIKE 'LD%'
            THEN 'SYSTEM'
        ELSE 'USER'
    END AS ORDER_CREATOR_TYP,

    SUM( ODC.ORDER_QTY ) AS ORDER_QTY,
    SUM( ODC.CNFRM_QTY ) AS CNFRM_QTY,
    ODC.QTY_UNIT_MEAS_ID AS QTY_UOM

FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = ODC.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = ODC.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_HIER_EN_CURR FAC
        ON FAC.FACILITY_ID = ODC.FACILITY_ID

WHERE
    ODC.ORDER_CAT_ID = 'C'
    AND ODC.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
    AND ODC.PO_TYPE_ID <> 'RO'
    AND ODC.SHIP_COND_ID NOT IN ( '', 'EG' )
    AND ODC.FRST_RDD >= DATE '2014-02-01'
    AND ODC.CUST_GRP2_CD = 'TLB'
    AND ODC.DELIV_GRP_CD <> '0'
    AND ODC.DELIV_PRTY_ID = 12
    AND ODC.DELIV_BLK_CD = ''
    AND ( ODC.ORDER_ID, ODC.ORDER_LINE_NBR, ODC.SCHED_LINE_NBR ) NOT IN (
        SELECT
            ORDER_ID,
            ORDER_LINE_NBR,
            SCHED_LINE_NBR
        FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR
    )

GROUP BY
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,

    ODC.SHIP_TO_CUST_ID,
    CUST.CUST_NAME,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,

    ODC.FACILITY_ID,
    FAC.XTND_NAME,
    ODC.SHIP_PT_ID,

    ODC.MATL_ID,
    MATL.DESCR,
    MATL.PBU_NBR,
    MATL.PBU_NAME,
    MATL.MKT_AREA_NBR,
    MATL.MKT_AREA_NAME,
    COMPRESSION_FACTOR,
    MATL.UNIT_WT,
    MATL.UNIT_VOL,
    UNIT_COMPRESS_VOL,
    ORDER_CREATOR_TYP,
    ODC.QTY_UNIT_MEAS_ID