SELECT
    Q.FRST_RDD,
    CAL.DAY_OF_WEEK_NAME_DESC,
    SUM( Q.ORDER_QTY ) AS ORDER_QTY,
    SUM( Q.CNFRM_QTY ) AS CNFRM_QTY

FROM (

SELECT
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    ODC.SHIP_TO_CUST_ID,
    ODC.MATL_ID,
    ODC.CUST_GRP2_CD,
    ODC.FRST_RDD,
    MAX( ODC.ORDER_QTY ) AS ORDER_QTY,
    SUM( ODC.CNFRM_QTY ) AS CNFRM_QTY,
    ODC.QTY_UNIT_MEAS_ID

FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC

WHERE
    ODC.ORDER_CAT_ID = 'C'
    AND ODC.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
    AND ODC.PO_TYPE_ID <> 'RO'
    AND ODC.CUST_GRP2_CD = 'TLB'
    AND ODC.ORDER_DT >= CAST( '2013-08-01' AS DATE )

GROUP BY
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    ODC.SHIP_TO_CUST_ID,
    ODC.MATL_ID,
    ODC.CUST_GRP2_CD,
    ODC.FRST_RDD,
    ODC.QTY_UNIT_MEAS_ID
    
    ) Q

    INNER JOIN GDYR_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE = Q.FRST_RDD
        AND CAL.DAY_DATE < CURRENT_DATE
        -- AND CAL.CAL_YR = EXTRACT( YEAR FROM CURRENT_DATE )

GROUP BY
    Q.FRST_RDD,
    CAL.DAY_OF_WEEK_NAME_DESC

ORDER BY
    Q.FRST_RDD