SELECT
    OOSL.ORDER_ID AS "Order ID",
    OOSL.ORDER_LINE_NBR AS "Order Line Number",
    
    SD.SHIP_TO_CUST_ID AS "Ship To Customer ID",
    CUST.OWN_CUST_ID AS "Common Owner ID",
    CUST.OWN_CUST_NAME AS "Common Owner Name",
    CUST.CUST_GRP_ID AS "Customer Group ID",
    CUST.CUST_GRP2_CD AS "Customer Hier Group 2 Code",
    SD.CUST_GRP_ID_2 AS "Sales Doc Cust Group 2 Code",

    MAX( SDI.FACILITY_ID ) AS "Facility ID",
    MAX( SDSL.SCHD_LN_DELIV_BLK_CD ) AS "Schedule Line Deliv Block Code",

    SUM( OOSL.OPEN_CNFRM_QTY ) AS "Open Confirmed Qty",
    SUM( OOSL.UNCNFRM_QTY ) AS "Unconfirmed Qty",
    SUM( OOSL.BACK_ORDER_QTY ) AS "Back Ordered Qty"
    
FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOSL

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_SCHD_LN SDSL
        ON SDSL.SLS_DOC_ID = OOSL.ORDER_ID
        AND SDSL.SLS_DOC_ITM_ID = OOSL.ORDER_LINE_NBR
        AND SDSL.SCHD_LN_ID = OOSL.SCHED_LINE_NBR
        AND SDSL.EXP_DT = CAST( '5555-12-31' AS DATE )
        AND SDSL.ORIG_SYS_ID = 2
        AND SDSL.SCHD_LN_DELIV_BLK_CD NOT IN ( 'YT', 'YR', '11' )

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM SDI
        ON SDI.SLS_DOC_ID = OOSL.ORDER_ID
        AND SDI.SLS_DOC_ITM_ID = OOSL.ORDER_LINE_NBR
        AND SDI.ORIG_SYS_ID = 2
        AND SDI.EXP_DT = CAST( '5555-12-31' AS DATE )

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC SD
        ON SD.SLS_DOC_ID = OOSL.ORDER_ID
        AND SD.EXP_DT = CAST( '5555-12-31' AS DATE )
        AND SD.CUST_PRCH_ORD_TYP_CD <> 'RO'
        AND SD.SLS_DOC_TYP_CD NOT IN ( 'ZLS', 'ZLZ' )
        AND SD.ORIG_SYS_ID = 2

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = SD.SHIP_TO_CUST_ID
        AND CUST.CUST_GRP2_CD = 'TLB'

WHERE
    ( OOSL.OPEN_CNFRM_QTY > 0
    OR OOSL.UNCNFRM_QTY > 0
    OR OOSL.BACK_ORDER_QTY > 0 )
    AND OOSL.ORIG_SYS_ID = 2

GROUP BY
    OOSL.ORDER_ID ,
    OOSL.ORDER_LINE_NBR ,
    
    SD.SHIP_TO_CUST_ID,
    CUST.OWN_CUST_ID,
    CUST.OWN_CUST_NAME,
    CUST.CUST_GRP_ID,
    CUST.CUST_GRP2_CD,
    SD.CUST_GRP_ID_2