SELECT
    Q.SHIP_TO_CUST_ID,
    Q.CUST_GRP2_CD,
    Q.FRST_RDD,
    SUM( Q.CONFIRMED_QTY ) AS CONFIRMED_QTY,
    SUM( Q.CONFIRMED_WT ) AS CONFIRMED_WT,
    SUM( Q.CONFIRMED_VOL ) AS CONFIRMED_VOL
    
FROM ( 

SELECT
    O.SHIP_TO_CUST_ID,
    O.CUST_GRP2_CD,
    O.FRST_RDD,
    SUM( O.CNFRM_QTY) AS CONFIRMED_QTY,
    CONFIRMED_QTY * O.UNIT_WT AS CONFIRMED_WT,
    CONFIRMED_QTY * O.UNIT_VOL AS CONFIRMED_VOL,
    O.QTY_UNIT_MEAS_ID,
    O.WT_UNITS_MEAS_ID,
    O.VOL_UNIT_MEAS_ID

FROM (

SELECT
    ODC.ORDER_ID,
    ODC.ORDER_LINE_NBR,
    ODC.SCHED_LINE_NBR,
    ODC.CUST_GRP2_CD,
    NULLIF( ODC.DELIV_BLK_CD, '' ) AS DELIV_BLK_CD,
    ODC.SHIP_TO_CUST_ID,
    ODC.MATL_ID,
    ODC.ORDER_DT,
    ODC.FRST_MATL_AVL_DT,
    ODC.FRST_PLN_GOODS_ISS_DT,
    ODC.FRST_RDD,
    ODC.FRST_PROM_DELIV_DT,
    ODC.PLN_DELIV_DT,
    ODC.QTY_UNIT_MEAS_ID,
    ODC.ORDER_QTY,
    ODC.CNFRM_QTY,
    MAX( ODC.GROSS_WT ) OVER ( PARTITION BY ODC.ORDER_ID, ODC.ORDER_LINE_NBR ) / NULLIFZERO( MAX( ODC.ORDER_QTY ) OVER ( PARTITION BY ODC.ORDER_ID, ODC.ORDER_LINE_NBR ) ) AS UNIT_WT,
    MAX( ODC.VOL ) OVER ( PARTITION BY ODC.ORDER_ID, ODC.ORDER_LINE_NBR ) / NULLIFZERO( MAX( ODC.ORDER_QTY ) OVER ( PARTITION BY ODC.ORDER_ID, ODC.ORDER_LINE_NBR ) ) AS UNIT_VOL,
    ODC.WT_UNITS_MEAS_ID,
    ODC.VOL_UNIT_MEAS_ID

FROM NA_BI_VWS.ORDER_DETAIL_CURR ODC

WHERE
    ODC.CUST_GRP2_CD = 'TLB'
    AND ODC.ORDER_CAT_ID = 'C'
    AND ODC.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
    AND ODC.PO_TYPE_ID <> 'RO'
    AND ODC.ORDER_DT >= CAST( '2013-09-01' AS DATE )
    AND ODC.FRST_PROM_DELIV_DT IS NOT NULL
    AND ( ODC.CNFRM_QTY > 0 OR ODC.ORDER_QTY > 0 )

    ) O

WHERE
    O.FRST_RDD = O.FRST_PROM_DELIV_DT

GROUP BY
    O.SHIP_TO_CUST_ID,
    O.CUST_GRP2_CD,
    O.FRST_RDD,
    O.UNIT_WT,
    O.UNIT_VOL,
    O.QTY_UNIT_MEAS_ID,
    O.WT_UNITS_MEAS_ID,
    O.VOL_UNIT_MEAS_ID

    ) Q

GROUP BY
    Q.SHIP_TO_CUST_ID,
    Q.CUST_GRP2_CD,
    Q.FRST_RDD

;

