SELECT
    OD.ORDER_ID,
    OD.ORDER_LINE_NBR,
    OD.SCHED_LINE_NBR,

    ( OD.SHIP_TO_CUST_ID ) AS SHIP_TO_CUST_ID,
    OD.SALES_ORG_CD,
    OD.DISTR_CHAN_CD,
    OD.CO_CD,
    OD.DIV_CD,
    OD.CUST_GRP_ID,
    CGD.CUST_GRP2_CD || ' - ' || CGD.CUST_GRP2_DESC AS CUST_GRP2,
    
    OD.MATL_ID,
    OD.ITEM_CAT_ID,
    
    ( NULLIF( OD.ORDER_CAT_ID, ' ' ) ) AS ORDER_CAT_ID,
    ( NULLIF( OD.ORDER_TYPE_ID, ' ' ) ) AS ORDER_TYPE_ID,
    ( NULLIF( OD.PO_TYPE_ID, ' ' ) ) AS PO_TYPE_ID,
    ( NULLIF( OD.DELIV_BLK_CD, ' ' ) ) AS DELIV_BLK_CD,
    ( NULLIF( OD.FACILITY_ID, ' ' ) ) AS FACILITY_ID,
    ( NULLIF( OD.SHIP_PT_ID, ' ' ) ) AS SHIP_PT_ID,
    ( NULLIF( OD.SHIP_COND_ID, ' ' ) ) AS SHIP_COND_ID,
    ( NULLIF( OD.REJ_REAS_ID, ' ' ) ) AS REJ_REAS_ID,
    ( RRC.REJ_REAS_DESC ) AS REJ_REAS,
    ( NULLIF( OD.DELIV_PRTY_ID, ' ' ) ) AS DELIV_PRTY_ID,
    ( NULLIF( OD.ROUTE_ID, ' ' ) ) AS ROUTE_ID,
    ( NULLIF( OD.DELIV_GRP_CD, ' ' ) ) AS DELIV_GRP_CD,
    ( NULLIF( OD.SPCL_PROC_ID, ' ' ) ) AS SPCL_PROC_ID,
    
    OD.ORDER_DT,
    ( OD.CUST_RDD ) AS ORDD,
    ( OD.FRST_RDD ) AS FRDD,
    ( CASE WHEN OD.FRST_PROM_DELIV_DT < OD.FRST_RDD THEN OD.FRST_RDD ELSE OD.FRST_PROM_DELIV_DT END ) AS FCDD,
    
    ( OD.FRST_MATL_AVL_DT ) AS FRDD_FMAD,
    ( OD.FRST_PLN_GOODS_ISS_DT ) AS FRDD_FPGI,
    
    ( CAST( OD.FRST_PROM_DELIV_DT - CAST( OD.FRST_RDD - OD.FRST_MATL_AVL_DT AS INTEGER ) AS DATE ) ) AS FCDD_FMAD,
    ( CAST( OD.FRST_PROM_DELIV_DT - CAST( OD.FRST_RDD - OD.FRST_PLN_GOODS_ISS_DT AS INTEGER ) AS DATE ) ) AS FCDD_FPGI,
    
    OD.QTY_UNIT_MEAS_ID,
    ( OD.ORDER_QTY ) AS ORDER_QTY,
    ( OD.CNFRM_QTY ) AS CNFRM_QTY,
    CASE
        WHEN OOSL.SCHED_LINE_NBR IS NOT NULL
            THEN 'Open Order'
        ELSE 'Closed'
    END AS OPEN_ORDER_IND,    
    ( OOSL.OPEN_CNFRM_QTY ) AS OPEN_CNFRM_QTY,
    ( OOSL.UNCNFRM_QTY ) AS UNCNFRM_QTY,
    ( OOSL.BACK_ORDER_QTY ) AS BACK_ORDER_QTY
    
FROM NA_BI_VWS.ORDER_DETAIL_CURR OD

    LEFT OUTER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOSL
        ON OOSL.ORDER_ID = OD.ORDER_ID
        AND OOSL.ORDER_LINE_NBR = OD.ORDER_LINE_NBR
        AND OOSL.SCHED_LINE_NBR = OD.SCHED_LINE_NBR

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = OD.MATL_ID
        AND MATL.PBU_NBR IN ( '01', '03', '04', '05', '07', '08', '09' )
        
    LEFT OUTER JOIN GDYR_BI_VWS.NAT_ORDER_REJ_REAS_CURR RRC
        ON RRC.REJ_REAS_ID = OD.REJ_REAS_ID

    LEFT OUTER JOIN NA_BI_VWS.CUST_GRP2_DESC_EN_CURR CGD
        ON CGD.CUST_GRP2_CD = OD.CUST_GRP2_CD

    LEFT OUTER JOIN GDYR_VWS.FACILITY F
        ON F.FACILITY_ID = OD.FACILITY_ID
        AND F.ORIG_SYS_ID = 2
        AND F.EXP_DT = CAST( '5555-12-31' AS DATE )
        AND F.LANG_ID = 'EN'

WHERE
    OD.RPT_FRT_PLCY_CD = 'TLB'
    AND OD.ORDER_TYPE_ID NOT IN ( 'ZLS', 'ZLZ' )
    AND OD.ORDER_CAT_ID = 'C'
    AND OD.PO_TYPE_ID <> 'RO'
    AND OD.ORDER_DT >= CAST( '2014-03-05' AS DATE )

ORDER BY
    OD.ORDER_ID,
    OD.ORDER_LINE_NBR,
    OD.SCHED_LINE_NBR
