DROP TABLE YCAPACITY;

CREATE VOLATILE TABLE YCAPACITY  (

    SHIP_TO_CUST_ID CHAR(10),
    TRUCKLOAD_NBR INTEGER,
    GRP INTEGER,
    TRAILER_TYPE VARCHAR(3),
    TRUCKLOAD_PLANNED CHAR(1),
    DELIV_DT DATE FORMAT 'YYYY-MM-DD' ,
    MIN_WT INTEGER 
    
) PRIMARY INDEX (
    SHIP_TO_CUST_ID,
    DELIV_DT
) ON COMMIT PRESERVE ROWS;

-- INSERT INTO YCAPACITY (SHIP_TO_CUST_ID, TRUCKLOAD_NBR, GRP, TRAILER_TYPE, TRUCKLOAD_PLANNED, DELIV_DT, MIN_WT ) VALUES ( ?,?,?,?,?,?,? );

SELECT COUNT(*) FROM YCAPACITY;

SELECT
    SHIP_TO_CUST_ID,
    DELIV_DT,
    TRAILER_TYPE,
    COUNT(*) AS TRAILER_PER_DLV_CNT,
    SUM( CAST( CASE
        WHEN TRAILER_TYPE = 'S53'
            THEN 32000
        WHEN TRAILER_TYPE = 'D53'
            THEN 15500
        ELSE 0
    END AS INTEGER ) ) AS MAX_WT,
    SUM( CAST( CASE
        WHEN TRAILER_TYPE = 'S53'
            THEN 3667
        WHEN TRAILER_TYPE = 'D53'
            THEN 3667
        ELSE 0
    END AS FLOAT ) ) AS MAX_VOL,
    SUM( MIN_WT ) AS MIN_WT
FROM YCAPACITY
GROUP BY
    SHIP_TO_CUST_ID,
    DELIV_DT,
    TRAILER_TYPE