SELECT
    CAP.CUST_ID
    , CAP.DELIV_DT
    , CAP.TL_SEQ_ID
    , CAP.FIRST_SNAP_DT
    , CAP.LAST_SNAP_DT
    , CAP.SNAP_DELIV_GRP_CD
    , CAP.CURR_DELIV_GRP_CD
    , COUNT(*)

FROM (

SELECT
    CE.CUST_ID
    , CE.DELIV_DT
    , CE.DELIV_GRP_CD AS SNAP_DELIV_GRP_CD
    , CDC.DELIV_GRP_CD AS CURR_DELIV_GRP_CD
    , CE.TL_SEQ_ID
    , MIN(CE.EFF_DT) AS FIRST_SNAP_DT
    , MAX(CE.EFF_DT) AS LAST_SNAP_DT

FROM NA_BI_vWS.TL_CAP_DELIV_SCHD CE

    INNER JOIN NA_BI_VWS.TL_CAP_DELIV_SCHD_CURR CDC
        ON CDC.CUST_ID = CE.CUST_ID
        AND CDC.DELIV_DT = CE.DELIV_DT
        AND CDC.TL_SEQ_ID = CE.TL_SEQ_ID
        AND CDC.DELIV_GRP_CD = '000'

WHERE
    CE.DELIV_GRP_CD > '000'

GROUP BY
    CE.CUST_ID
    , CE.DELIV_DT
    , CE.DELIV_GRP_CD
    , CDC.DELIV_GRP_CD
    , CE.TL_SEQ_ID

    ) CAP
    
    INNER JOIN NA_BI_VWS.TL_MSTR_CURR TLM
        ON TLM.CUST_ID = CAP.CUST_ID
        AND TLM.DELIV_GRP_CD = CAP.SNAP_DELIV_GRP_CD
        AND TLM.DELIV_DT = CAP.DELIV_DT

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = TLM.FISCAL_YR
        AND OD.ORDER_ID = TLM.SLS_DOC_ID
        AND OD.ORDER_LINE_NBR = TLM.SLS_DOC_ITM_ID
        AND OD.SCHED_LINE_NBR = 1
        AND OD.EXP_DT = CAST('5555-12-31' AS DATE)
        AND OD.DELIV_GRP_CD = CAP.SNAP_DELIV_GRP_CD

GROUP BY
    CAP.CUST_ID
    , CAP.DELIV_DT
    , CAP.TL_SEQ_ID
    , CAP.FIRST_SNAP_DT
    , CAP.LAST_SNAP_DT
    , CAP.SNAP_DELIV_GRP_CD
    , CAP.CURR_DELIV_GRP_CD
