DROP TABLE YTL_CAPACITY;

CREATE VOLATILE TABLE YTL_CAPACITY (
    SHIP_TO_CUST_ID CHAR(10) NOT NULL
    , SLOT_DELIV_DT DATE FORMAT 'YYYY-MM-DD' NOT NULL
    , TRUCK_NBR SMALLINT NOT NULL
    , DELIV_GRP_CD SMALLINT
    , TRAILER_TYPE_CD CHAR(3)
    , TRAILER_TYPE_DESC VARCHAR(25)
    , TRAILER_PLANNED_CD CHAR(1)
    , MIN_WT DECIMAL(15,3)
    , MAX_WT DECIMAL(15,3)
    , MAX_VOL DECIMAL(15,3)
) 
    UNIQUE PRIMARY INDEX (SHIP_TO_CUST_ID, SLOT_DELIV_DT, TRUCK_NBR) 
    ON COMMIT PRESERVE ROWS
;

--INSERT INTO YTL_CAPACITY(?, ?, ?, ?, ?, ?, ?, ?, ?, ? );

SELECT
    SHIP_TO_CUST_ID
    , SLOT_DELIV_DT
    , TRUCK_NBR
    , DELIV_GRP_CD
    , TRAILER_TYPE_CD
    , TRAILER_TYPE_DESC
    , TRAILER_PLANNED_CD
    , MIN_WT
    , MAX_WT
    , MAX_VOL
    , ROW_NUMBER() OVER (PARTITION BY SHIP_TO_CUST_ID, SLOT_DELIV_DT ORDER BY MIN_WT ASC, TRUCK_NBR ASC) AS FILL_ORDER

FROM A421356.YTL_CAPACITY

ORDER BY
    SHIP_TO_CUST_ID
    , SLOT_DELIV_DT
    , FILL_ORDER
;