SELECT
    XR.FRT_MVMNT_ID
    , XR.FRT_MVMNT_SCHD_ID
    , XR.FRT_MVMNT_STOP_ID
    , XR.TM_DELIV_ID
    , XR.TM_PLN_SCHD_ID
    , XR.TM_DELIV_SPLIT_ID
    , XR.SAP_DELIV_ID_FISCAL_YR
    , XR.SAP_DELIV_ID
    
    , CUST.SHIP_TO_CUST_ID
    , CUST.CUST_NAME AS SHIP_TO_CUST_NAME
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    
    , FM.BILL_LADING_ID AS MSTR_BOL
    , FMS.BILL_LADING_ID AS STOP_BOL
    
    , FMS.STOP_TYP_CD
    , TDC.TM_DELIV_TYP_CD
    , TDC.TM_DELIV_STA_CD
    , TDC.TM_DELIV_STA_DT
    , TDC.SHIP_MODE_CD
    , TDC.OWN_TXT
    , TDC.CUST_APPT_DT
    , TDC.CUST_APPT_TM
    
    , FM.FEASBL_IND
    , FM.XDOCK_CD
    , FM.LOAD_MODIFY_IND
    , FM.TRLR_FILL_IND
    
    , FM.TRANSP_MODE_CD
    , FM.TM_CARR_ID
    , FM.TRLR_TYP_ID
    , FM.TRLR_ID
    , FM.TRLR_BLD_ID
    , FM.FRT_PAY_PROC_IND
    , FM.FRT_MVMNT_UPD_SRC_ID
    
    , FM.DOCK_DT
    , FM.DOCK_TM
    , FM.TRIP_CMPLT_DT
    , FM.TRIP_CMPLT_TM
    , FM.APPT_REQ_IND
    
    , FMS.CARR_APPT_DT
    , FMS.CARR_APPT_TM
    , FMS.CARR_CNFM_PK_DELIV_IND
    , FMS.DEPART_TRANSIT_DELAY_ID
    , FMS.ARRV_TRANSIT_DELAY_ID

FROM NA_BI_VWS.TM_FRTMV_DLV_XREF_CURR XR

    INNER JOIN NA_BI_VWS.TM_FRT_MVMNT_CURR FM
        ON FM.FRT_MVMNT_ID = XR.FRT_MVMNT_ID
        AND FM.FRT_MVMNT_SCHD_ID = XR.FRT_MVMNT_SCHD_ID

    INNER JOIN NA_BI_VWS.TM_FRT_MVMNT_STOP_CURR FMS
        ON FMS.FRT_MVMNT_ID = XR.FRT_MVMNT_ID
        AND FMS.FRT_MVMNT_SCHD_ID = XR.FRT_MVMNT_SCHD_ID
        AND FMS.FRT_MVMNT_STOP_ID = XR.FRT_MVMNT_STOP_ID
        AND FMS.STOP_TYP_CD = 'DL'
        
    INNER JOIN NA_BI_VWS.TM_DELIV_CURR TDC
        ON TDC.TM_DELIV_ID = XR.TM_DELIV_ID
        AND TDC.TM_PLN_SCHD_ID = XR.TM_PLN_SCHD_ID
        AND TDC.TM_DELIV_SPLIT_ID = XR.TM_DELIV_SPLIT_ID
        AND TDC.SAP_DELIV_ID_FISCAL_YR = XR.SAP_DELIV_ID_FISCAL_YR
        AND TDC.SAP_DELIV_ID = XR.SAP_DELIV_ID

    INNER JOIN NA_BI_VWS.NAT_DELIV_DOC_CURR_ALL DD
        ON DD.FISCAL_YR = XR.SAP_DELIV_ID_fISCAL_YR
        AND DD.DELIV_DOC_ID = XR.SAP_DELIV_ID
        AND DD.ACTL_GOODS_MVT_DT >= DATE '2014-08-01'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DD.SHIP_TO_CUST_ID
        AND CUST.OWN_CUST_ID = '00A0009337'

WHERE
    XR.SAP_DELIV_ID_FISCAL_YR = CAST(EXTRACT(YEAR FROM CURRENT_DATE-1) AS CHAR(4))
    AND XR.FRT_MVMNT_SCHD_ID LIKE '%GDYR%'
    AND XR.TM_PLN_SCHD_ID LIKE '%GDYR%'

ORDER BY
    XR.FRT_MVMNT_ID
    , XR.FRT_MVMNT_SCHD_ID
    , XR.FRT_MVMNT_STOP_ID
    , XR.TM_DELIV_ID
    , XR.TM_PLN_SCHD_ID
    , XR.TM_DELIV_SPLIT_ID
    , XR.SAP_DELIV_ID_FISCAL_YR
    , XR.SAP_DELIV_ID