SELECT
    DDI.FISCAL_YR
    , DDI.DELIV_DOC_ID
    , DDI.DELIV_DOC_ITM_ID

    , DD.BILL_LADING_ID

    , DDI.SLS_DOC_ID
    , DDI.SLS_DOC_ITM_ID

    , DD.SD_DOC_CTGY_CD AS DELIV_HDR_CTGY_CD
    , DD.DELIV_TYP_CD
    , DDI.SD_DOC_CTGY_CD AS DELIV_ITM_CTGY_CD
 
    , DD.SRC_CRT_TS AS DELIV_HDR_CRT_TS
    , DDI.SRC_CRT_TS AS DELIV_ITM_CRT_TS
    , DD.ORIG_DOC_DT
    , DD.PLN_GOODS_MVT_DT
    , DD.ACTL_GOODS_MVT_DT
    , DD.DELIV_DT
    , PDH.POST_DT AS GOODS_RCPT_POST_DT

    , DDI.MATL_ID
    , M.DESCR
    , DDI.MATL_HIER_ID
    , M.PBU_NBR
    , M.PBU_NAME

    , DDI.BASE_UOM_CD
    , DDI.ACTL_DELIV_QTY

    , DDI.FACILITY_ID AS SRC_FACILITY_ID
    , SF.FACILITY_NAME AS SRC_FACILITY_NAME

    , DD.FACILITY_ID AS DEST_FACILITY_ID
    , DF.FACILITY_NAME AS DEST_FACILITY_NAME

    , DD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME

FROM GDYR_VWS.DELIV_DOC_ITM DDI

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = DDI.MATL_ID
        AND M.PBU_NBR = '01'

    INNER JOIN GDYR_VWS.DELIV_DOC DD
        ON DD.FISCAL_YR = DDI.FISCAL_YR
        AND DD.DELIV_DOC_ID = DDI.DELIV_DOC_ID
        AND DD.ORIG_SYS_ID = DDI.ORIG_SYS_ID
        AND DD.EXP_DT = DDI.EXP_DT
        AND DD.SD_DOC_CTGY_CD IN ('7', 'J')

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR SF
        ON SF.FACILITY_ID = DDI.FACILITY_ID
        AND SF.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND SF.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR DF
        ON DF.FACILITY_ID = DD.FACILITY_ID
        AND DF.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND DF.DISTR_CHAN_CD = '81'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = DD.SHIP_TO_CUST_ID
        AND C.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND C.DISTR_CHAN_CD = '81'

    INNER JOIN (
        GDYR_VWS.PRCH_DOC_HIST PDH
        
        INNER JOIN GDYR_BI_VWS.NAT_MATL_DOC_CURR MD
            ON MD.MATL_DOC_YR = PDH.MATL_DOC_YR
            AND MD.MATL_DOC_ID = PDH.MATL_DOC_ID
            AND MD.ORIG_SYS_ID = PDH.ORIG_SYS_ID
            --AND MD.POST_DT = PDH.POST_DT
        )
        ON PDH.PRCH_DOC_ID = DDI.SLS_DOC_ID
        AND PDH.PRCH_DOC_ITM_ID = DDI.SLS_DOC_ITM_ID
        AND PDH.PRCH_HIST_CTGY_CD = 'E'
        AND PDH.MVMNT_TYP_CD = '101'
        AND PDH.ORIG_SYS_ID = DDI.ORIG_SYS_ID
        AND PDH.EXP_DT = DDI.EXP_DT
        AND MD.GOODS_RCPT_BOL_ID = DD.BILL_LADING_ID

WHERE
    DDI.EXP_DT = CAST('5555-12-31' AS DATE)
    AND DDI.ORIG_SYS_ID = 2
    AND DDI.SD_DOC_CTGY_CD = 'V'
    
    AND DD.FACILITY_ID IN ('N602', /*'N607',*/ 'N623', 'N636', 'N637', 'N639', 'N699', 'N6D3')
    AND DDI.FACILITY_ID IN ('N602', /*'N607',*/ 'N623', 'N636', 'N637', 'N639', 'N699', 'N6D3')
    AND DDI.ACTL_DELIV_QTY <> 0

    --AND DD.ORIG_DOC_DT BETWEEN DATE '2013-06-01' AND CURRENT_DATE-1
    AND DD.ACTL_GOODS_MVT_DT BETWEEN DATE '2014-01-01' AND DATE '2014-12-31'

ORDER BY 1,2,3
