-- RWS-2014-08-05 -- Explain shows no long steps or product joins - prod ready

SELECT
    DDC.FISCAL_YR AS DELIV_FISCAL_YR
    , DDC.BILL_LADING_ID
    , DDC.DELIV_ID
    
    , COUNT(DISTINCT DDC.ORDER_FISCAL_YR || DDC.ORDER_ID || DDC.ORDER_LINE_NBR) AS ORDER_LN_CNT
    , COUNT(DISTINCT DDC.MATL_ID) AS MATL_ID_CNT
    
    , DDC.DIV_CD
    , DDC.SALES_ORG_CD
    , DDC.DISTR_CHAN_CD
    , DDC.CUST_GRP_ID
    , DDC.CUST_GRP2_CD
    , DDC.SHIP_TO_CUST_ID
    
    , DDC.DELIV_LINE_FACILITY_ID
    , DDC.SHIP_FACILITY_ID
    , COUNT(DISTINCT DDC.SHIP_PT_ID) AS SHIP_PT_CNT
    , COUNT(DISTINCT DDC.SHIP_COND_ID) AS SHIP_COND_CNT
    
    , CAST('EA' AS CHAR(3)) AS QTY_UOM
    , MIN(CASE WHEN DDC.QTY_UNIT_MEAS_ID = 'EA' THEN DDC.DELIV_QTY END) AS MIN_DELIV_LINE_QTY
    , MEDIAN(CASE WHEN DDC.QTY_UNIT_MEAS_ID = 'EA' THEN DDC.DELIV_QTY END) AS MEDIAN_DELIV_LINE_QTY
    , CAST(AVERAGE(CASE WHEN DDC.QTY_UNIT_MEAS_ID = 'EA' THEN DDC.DELIV_QTY ELSE 0 END) AS DECIMAL(15,3)) AS AVERAGE_DELIV_LINE_QTY
    , MAX(CASE WHEN DDC.QTY_UNIT_MEAS_ID = 'EA' THEN DDC.DELIV_QTY END) AS MAX_DELIV_LINE_QTY
    
    , SUM(CASE WHEN DDC.QTY_UNIT_MEAS_ID = 'EA' THEN DDC.DELIV_QTY END) AS TOTAL_DELIV_QTY
    
    , COUNT(DISTINCT CASE WHEN DDC.QTY_UNIT_MEAS_ID = 'LB' THEN DDC.MATL_ID END) AS RETREAD_UNQ_MATL_CNT
    , SUM(CASE WHEN DDC.QTY_UNIT_MEAS_ID = 'LB' THEN DDC.DELIV_QTY END) AS RETREAD_DELIV_LB_QTY
    
    , DDC.WT_UNIT_MEAS_ID AS WT_UOM
    , SUM(DDC.GROSS_WT) AS GROSS_WT
    , SUM(DDC.NET_WT) AS NET_WT
    
    , COALESCE(NULLIF(DDC.VOL_UNIT_MEAS_ID, ''), 'FT3') AS VOL_UOM
    , SUM(DDC.VOL) AS VOL
    
    , DDC.DELIV_NOTE_CREA_DT
    , MAX(DDC.DELIV_LINE_CREA_DT) AS MAX_DELIV_LINE_CREA_DT
    
    , DDC.PLN_GOODS_MVT_DT
    , DDC.ACTL_GOODS_ISS_DT
    , DDC.DELIV_DT
    
    , DDC.DELIV_CAT_ID
    , DDC.DELIV_TYPE_ID
    
    , MIN(DDC.DELIV_PRTY_ID) AS DELIV_PRTY_ID
    , MAX(DDC.RTG_ID) AS ROUTE_ID
    , DDC.TERMS_ID AS INCOTERMS_CD
    , DDC.UNLD_PT_CD
    , DDC.SPCL_PROC_ID
    , MAX(DDC.SRC_CRT_USR_ID) AS SRC_CRT_USR_ID
    , DDC.GOODS_ISS_IND
    
FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

WHERE
    DDC.FISCAL_YR >= CAST(EXTRACT(YEAR FROM (CURRENT_DATE-1)) - 1 AS CHAR(4))
    
    -- Stats collected columns, want to 
    AND DDC.ACTL_GOODS_ISS_DT IS NOT NULL
    AND DDC.GOODS_ISS_IND = 'Y'
    
    -- Rolling ~ 3 months by Planned Goods Movement Date
    AND DDC.ACTL_GOODS_ISS_DT >= ADD_MONTHS((CURRENT_DATE-1), -3) - (EXTRACT(DAY FROM ADD_MONTHS((CURRENT_DATE-1), -3)) - 1)
    
    -- Core LC's only -- exclude from factory
    AND DDC.DELIV_LINE_FACILITY_ID IN  ('N602', 'N607', 'N623', 'N636', 'N637', 'N639', 'N699', 'N6D3')
    
    -- Standard deliveries, excluding returns
    AND DDC.DELIV_CAT_ID = 'J'
    
    -- Exclude unneccessary lines
    AND DDC.DELIV_QTY > 0
    
    -- Exclude Missing BOL 
    AND DDC.BILL_LADING_ID > ''
    
    -- Goodyear US, Canada & GDTNA main Sales Orgs
    AND DDC.SALES_ORG_CD IN (
            'N301', 'N302', 'N303', 
            'N311', 'N312', 'N313', 
            'N321', 'N322', 'N323'
        )
    
    -- Only certain DC's are active within these sales orgs -- trying to hit the db stats
    AND DDC.DISTR_CHAN_CD IN (
            '01', '03', '04', '05', '06', '07', '08', '09'
            , '10', '11', '12', '14', '15', '16'
            , '20', '21', '22'
            , '30', '31', '32'
        )

GROUP BY
    DDC.FISCAL_YR
    , DDC.BILL_LADING_ID
    , DDC.DELIV_ID
    , DDC.DIV_CD
    , DDC.SALES_ORG_CD
    , DDC.DISTR_CHAN_CD
    , DDC.CUST_GRP_ID
    , DDC.CUST_GRP2_CD
    , DDC.SHIP_TO_CUST_ID
    , DDC.DELIV_LINE_FACILITY_ID
    , DDC.SHIP_FACILITY_ID
    , QTY_UOM
    , DDC.WT_UNIT_MEAS_ID
    , VOL_UOM
    , DDC.DELIV_NOTE_CREA_DT
    , DDC.PLN_GOODS_MVT_DT
    , DDC.ACTL_GOODS_ISS_DT
    , DDC.DELIV_DT
    , DDC.DELIV_CAT_ID
    , DDC.DELIV_TYPE_ID
    , DDC.PRTL_DLVY_CD
    , DDC.TERMS_ID
    , DDC.UNLD_PT_CD
    , DDC.SPCL_PROC_ID
    , DDC.GOODS_ISS_IND

ORDER BY
    DDC.FISCAL_YR
    , DDC.BILL_LADING_ID
    , DDC.DELIV_ID

/*
-- DUPLICATE TEST - PASSED 2014-08-05
QUALIFY
    COUNT(*) OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID) > 1


*/

SAMPLE 1000


