SELECT
    DDC.FISCAL_YR
    , DDC.DELIV_ID
    , DDC.BILL_LADING_ID
    
    , DDC.SHIP_TO_CUST_ID
    , MAX(DDC.CUST_GRP2_CD) AS CUST_GRP2_CD
    
    , DDC.DELIV_LINE_FACILITY_ID
    , DDC.SHIP_FACILITY_ID
    , DDC.SHIP_PT_ID
    
    , DDC.DELIV_CAT_ID
    , DDC.DELIV_TYPE_ID

    , DDC.DELIV_PRTY_ID
    , DDC.SHIP_COND_ID
    
    , DDC.DELIV_NOTE_CREA_DT
    , DD.SRC_CRT_TS AS DELIV_HEADER_CRT_TS
    , MIN(DDI.SRC_CRT_TS) AS MIN_DELIV_LINE_CRT_TS
    , MAX(DDI.SRC_CRT_TS) AS MAX_DELIV_LINE_CRT_TS

    , DDC.TRANSP_PLN_DT
    , DDC.LOAD_DT
    , DDC.PICK_DT
    , DDC.PLN_GOODS_MVT_DT
    , DDC.ACTL_GOODS_ISS_DT
    , DDC.DELIV_DT
    
    , COUNT(DISTINCT DDC.MATL_ID) AS MATL_ID_CNT
    , COUNT(DISTINCT MATL.PBU_NBR || MATL.MKT_AREA_NBR) AS MKT_AREA_CNT
    , COUNT(DDC.DELIV_LINE_NBR) AS DELIV_LINE_CNT
    
    , 'EA' AS QTY_UOM
    , SUM(DDC.SLS_DELIV_QTY) AS TOTAL_DELIV_QTY
    
    , MIN(DDC.SLS_DELIV_QTY) AS MIN_DELIV_LINE_QTY
    , AVERAGE(DDC.SLS_DELIV_QTY) AS AVERAGE_DELIV_LINE_QTY
    , MEDIAN(DDC.SLS_DELIV_QTY) AS MEDIAN_DELIV_LINE_QTY
    , MAX(DDC.SLS_DELIV_QTY) AS MAX_DELIV_LINE_QTY
    
    , 'LB' AS WT_UOM
    , SUM(DDC.GROSS_WT) AS GROSS_WT
    
    , 'FT3' AS VOL_UOM
    , SUM(DDC.VOL) AS VOL
    , SUM(CAST(DDC.VOL * CASE MATL.PBU_NBR || MATL.MKT_AREA_NBR
            WHEN '0101' THEN 0.75
            WHEN '0108' THEN 0.80
            WHEN '0305' THEN 1.20
            WHEN '0314' THEN 1.20
            WHEN '0406' THEN 1.20
            WHEN '0507' THEN 0.75
            WHEN '0711' THEN 0.75
            WHEN '0712' THEN 0.75
            WHEN '0803' THEN 1.20
            WHEN '0923' THEN 0.75
            ELSE 1
        END AS DECIMAL(15,3))) AS COMPRESSED_VOL
    
FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR MATL
        ON MATL.MATL_ID = DDC.MATL_ID
        AND MATL.PBU_NBR IN ('01', '03')
        AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')

    INNER JOIN NA_BI_VWS.ORDER_DETAIL_CURR ODC
        ON ODC.ORDER_FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND ODC.ORDER_ID = DDC.ORDER_ID
        AND ODC.ORDER_LINE_NBR = DDC.ORDER_LINE_NBR
        AND ODC.SCHED_LINE_NBR = 1
        AND ODC.ORDER_DT >= DATE '2013-01-01'
        AND ODC.ORDER_CAT_ID = 'C'
        AND ODC.PO_TYPE_ID <> 'RO'

    INNER JOIN NA_BI_VWS.NAT_DELIV_DOC_CURR DD
        ON DD.FISCAL_YR = DDC.FISCAL_YR
        AND DD.DELIV_DOC_ID = DDC.DELIV_ID

    INNER JOIN NA_BI_VWS.NAT_DELIV_DOC_ITM_CURR DDI
        ON DDI.FISCAL_YR = DDC.FISCAL_YR
        AND DDI.DELIV_DOC_ID = DDC.DELIV_ID
        AND DDI.DELIV_DOC_ITM_ID = DDC.DELIV_LINE_NBR

    INNER JOIN NA_BI_VWS.TM_DELIV_CURR TDC
        ON TDC.SAP_DELIV_ID_FISCAL_YR = DDC.FISCAL_YR
        AND TDC.SAP_DELIV_ID = DDC.DELIV_ID

WHERE
    DDC.DELIV_NOTE_CREA_DT >= DATE '2013-06-01'
    AND DDC.ACTL_GOODS_ISS_DT BETWEEN (CURRENT_DATE-2) AND (CURRENT_DATE-1)
    AND DDC.DELIV_CAT_ID = 'J'
    AND DDC.DELIV_QTY > 0
    AND DDC.GOODS_ISS_IND = 'Y'

GROUP BY
    DDC.FISCAL_YR
    , DDC.DELIV_ID
    , DDC.BILL_LADING_ID
    
    , DDC.SHIP_TO_CUST_ID
    
    , DDC.DELIV_LINE_FACILITY_ID
    , DDC.SHIP_FACILITY_ID
    , DDC.SHIP_PT_ID
    
    , DDC.DELIV_CAT_ID
    , DDC.DELIV_TYPE_ID

    , DDC.DELIV_PRTY_ID
    , DDC.SHIP_COND_ID
    
    , DDC.DELIV_NOTE_CREA_DT
    , DD.SRC_CRT_TS

    , DDC.TRANSP_PLN_DT
    , DDC.LOAD_DT
    , DDC.PICK_DT
    , DDC.PLN_GOODS_MVT_DT
    , DDC.ACTL_GOODS_ISS_DT
    , DDC.DELIV_DT
    
    , QTY_UOM
    , WT_UOM
    , VOL_UOM
   