SELECT
    FRT_MVMNT_ID
    , TM_DELIV_FISCAL_YR
    , TM_DELIV_ID
    , TM_PLN_SCHD_ID
    , SAP_DELIV_FISCAL_YR
    , SAP_DELIV_ID
    , TM_DEST_TYP_CD
    , TM_SHIP_FROM_LOC_ID
    , TM_SHIP_TO_LOC_ID
    , CUST_ID
    , TM_CARR_ID
    , CARR_SCAC_ID
    , MSTR_BOL
    , SHIP_BOL
    , CARR_STOP_QTY
    , CARR_ACCEPT_TS
    , READYBYPLN_DT
    , ARRV_AT_PKUP_TS
    , DEPART_FROM_PKUP_TS
    , REQ_DELIV_DT
    , PLN_ARRV_TS
    , LPC_APPT_TS
    , ARRV_AT_DELIV_TS
    , SRC_CRT_TS
    , SRC_UPD_TS

FROM NA_BI_VWS.TM_CARR_DELIV_MSG_CURR

WHERE
    TM_DEST_TYP_CD = 'CUST'
    AND SRC_CRT_TS >= CAST('2014-06-01 00:00:00' AS TIMESTAMP(0))

ORDER BY
    FRT_MVMNT_ID
    , TM_DELIV_FISCAL_YR
    , TM_DELIV_ID
    , TM_PLN_SCHD_ID
    , SAP_DELIV_FISCAL_YR
    , SAP_DELIV_ID
