SELECT
    Q.OWN_CUST_ID
    , Q.OWN_CUST_NAME
    , Q.ACTL_GOODS_MVT_MTH_DT
    , Q.TM_CARR_ID
    , Q.CARR_SCAC_ID
    , Q.CARR_MODE_CD
    , Q.EDI_AB_CNT
    , COUNT(*) AS DN_CNT

FROM (

    SELECT
        XR.FRT_MVMNT_ID
        , FM.BILL_LADING_ID AS MSTR_BILL_LADING_ID
        , XR.FRT_MVMNT_SCHD_ID
        , XR.FRT_MVMNT_STOP_ID
        , FMS.BILL_LADING_ID AS STOP_BILL_LADING_ID
        
        , XR.TM_DELIV_ID
        , XR.TM_PLN_SCHD_ID
        , XR.TM_DELIV_SPLIT_ID
        
        , XR.SAP_DELIV_ID_FISCAL_YR
        , XR.SAP_DELIV_ID
        
        , DDC.PLN_GOODS_MVT_DT
        , DDC.ACTL_GOODS_MVT_DT
        , DDC.ACTL_GOODS_MVT_DT - (EXTRACT(DAY FROM DDC.ACTL_GOODS_MVT_DT)-1) AS ACTL_GOODS_MVT_MTH_DT
        , DDC.DELIV_DT
        
        , DDC.SHIP_RCVE_PT_CD
        , DDC.DELIV_TYP_CD
        , DDC.UNLD_PT_TXT
        , DDC.INCOTERM_CD_1
        , DDC.INCOTERM_CD_2
        , DDC.ROUTE_CD
        , DDC.DELIV_PRTY_CD
        , DDC.SHIP_COND_CD
        , DDC.SHIP_TO_CUST_ID
        , CUST.CUST_NAME AS SHIP_TO_CUST_NAME
        , CUST.OWN_CUST_ID
        , CUST.OWN_CUST_NAME
        
        , CASE
            WHEN AB.EDI_AB_CNT = 1
                THEN 'Y'
            WHEN AB.LAST_AB_APPT_TS + INTERVAL '15' MINUTE < AB.FIRST_AB_APPT_TS
                THEN 'N'
            ELSE 'Y'
            END AS TEST_AB_NO_CHANGES
        , AB.EDI_AB_CNT
        , AB.FIRST_AB_APPT_TS
        , AB.FIRST_AB_CRT_TS
        , AB.LAST_AB_APPT_TS
        , AB.LAST_AB_CRT_TS
        
        , DC.FRST_LST_CD
        , DC.TM_DELIV_STA_CD
        , DC.TM_DELIV_STA_DT
        , DC.TM_DELIV_STA_TM

        , DC.OWN_TXT
        , DC.CUST_APPT_DT
        , DC.CUST_APPT_TM

        , DC.DELIV_MOD_IND
        , DC.INBOUND_IND
        
        , FMS.STOP_TYP_CD
        
        , FM.FRT_MVMNT_STA_CD
        , FM.TRANSP_MODE_CD
        
        , FM.TM_CARR_ID
        , CARR.CARR_SCAC_ID
        , CARR.CARR_MODE_CD

        , FM.TRLR_TYP_ID
        , FM.TRLR_ID
        , FM.XDOCK_CD
        , FM.TRLR_FILL_IND
        , FM.FRT_PAY_PROC_IND
        , FM.FEASBL_IND
        
        , FMS.WT_QTY
        , FMS.CU_VOL_QTY
        , FMS.PC_QTY
        , FMS.MI_QTY
        
        , CDM.TM_DEST_TYP_CD
        , CDM.CARR_STOP_QTY
        , CDM.CARR_ACCEPT_TS
        , CDM.READYBYPLN_DT
        , CDM.ARRV_AT_PKUP_TS
        , CDM.DEPART_FROM_PKUP_TS
        , CDM.REQ_DELIV_DT
        , CDM.PLN_ARRV_TS
        , CDM.LPC_APPT_TS
        , CDM.ARRV_AT_DELIV_TS
        , CDM.SRC_CRT_TS
        , CDM.SRC_UPD_TS

    FROM NA_BI_VWS.TM_FRTMV_DLV_XREF_CURR XR

        INNER JOIN NA_BI_VWS.NAT_DELIV_DOC_CURR DDC
            ON DDC.FISCAL_YR = XR.SAP_DELIV_ID_FISCAL_YR
            AND DDC.DELIV_DOC_ID = XR.SAP_DELIV_ID
            AND DDC.SRC_CRT_TS >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01 00:00:00' AS TIMESTAMP(0))
            AND DDC.SD_DOC_CTGY_CD = 'J'
            AND DDC.ACTL_GOODS_MVT_DT >= DATE '2014-05-01'

        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID

        INNER JOIN NA_BI_VWS.TM_FRT_MVMNT_CURR FM
            ON FM.FRT_MVMNT_ID = XR.FRT_MVMNT_ID
            AND FM.FRT_MVMNT_SCHD_ID = XR.FRT_MVMNT_SCHD_ID
            AND FM.LATE_DEPART_DT >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE)
            --AND FM.FEASBL_IND = 'Y'

        INNER JOIN NA_BI_VWS.TM_CARR_CURR CARR
            ON CARR.TM_CARR_ID = FM.TM_CARR_ID

        INNER JOIN NA_BI_VWS.TM_FRT_MVMNT_STOP_CURR FMS
            ON FMS.FRT_MVMNT_ID = XR.FRT_MVMNT_ID
            AND FMS.FRT_MVMNT_SCHD_ID = XR.FRT_MVMNT_SCHD_ID
            AND FMS.FRT_MVMNT_STOP_ID = XR.FRT_MVMNT_STOP_ID
            AND FMS.LATE_ARRV_DT >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE)
            AND FMS.STOP_TYP_CD = 'DL'

        INNER JOIN NA_BI_VWS.TM_DELIV_CURR DC
            ON DC.TM_DELIV_ID = XR.TM_DELIV_ID
            AND DC.TM_PLN_SCHD_ID = XR.TM_PLN_SCHD_ID
            AND DC.TM_DELIV_SPLIT_ID = XR.TM_DELIV_SPLIT_ID
            AND DC.SAP_DELIV_ID_FISCAL_YR = XR.SAP_DELIV_ID_FISCAL_YR
            AND DC.SAP_DELIV_ID = XR.SAP_DELIV_ID
            AND DC.SRC_UPD_DT >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01' AS DATE)

        --LEFT OUTER JOIN (
        INNER JOIN (
                SELECT
                    Q.BILL_LADING_ID
                    , Q.FRT_MVMNT_STOP_ID
                    , Q.CARR_SCAC_ID
                    , Q.EDI_AB_CNT
                    , MAX(CASE WHEN Q.EDI_AB_SEQ_ID = 1 THEN Q.OCCASION_TS END) AS FIRST_AB_APPT_TS
                    , MAX(CASE WHEN Q.EDI_AB_SEQ_ID = 1 THEN Q.SRC_CRT_TS END) AS FIRST_AB_CRT_TS
                    , MAX(CASE WHEN Q.EDI_AB_SEQ_ID = Q.EDI_AB_CNT THEN Q.OCCASION_TS END) AS LAST_AB_APPT_TS
                    , MAX(CASE WHEN Q.EDI_AB_SEQ_ID = Q.EDI_AB_CNT THEN Q.SRC_CRT_TS END) AS LAST_AB_CRT_TS
                FROM (
                    SELECT
                        BILL_LADING_ID
                        , FRT_MVMNT_STOP_ID
                        , OCCASION_TS
                        , SRC_CRT_TS
                        , ROW_NUMBER() OVER (PARTITION BY BILL_LADING_ID, FRT_MVMNT_STOP_ID, CARR_SCAC_ID ORDER BY SRC_CRT_TS, SEQ_ID) AS EDI_AB_SEQ_ID
                        , COUNT(*) OVER (PARTITION BY BILL_LADING_ID, FRT_MVMNT_STOP_ID, CARR_SCAC_ID ORDER BY SRC_CRT_TS, SEQ_ID) AS EDI_AB_CNT
                        , CARR_SCAC_ID
                    FROM NA_BI_VWS.TM_SHIP_STA_CURR
                    WHERE
                        SRC_CRT_TS >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01 00:00:00' AS TIMESTAMP(0))
                        AND SHIP_STA_CD = 'AB'
                    ) Q
                GROUP BY
                    Q.BILL_LADING_ID
                    , Q.FRT_MVMNT_STOP_ID
                    , Q.CARR_SCAC_ID
                    , Q.EDI_AB_CNT
                ) AB
            ON AB.BILL_LADING_ID = FM.BILL_LADING_ID
            AND AB.FRT_MVMNT_STOP_ID = FMS.FRT_MVMNT_STOP_ID
            AND AB.CARR_SCAC_ID = CARR.CARR_SCAC_ID

        LEFT OUTER JOIN NA_BI_VWS.TM_CARR_DELIV_MSG_CURR CDM
            ON CDM.TM_DELIV_ID = XR.TM_DELIV_ID
            AND CDM.SAP_DELIV_ID = XR.SAP_DELIV_ID
            AND CDM.SAP_DELIV_FISCAL_YR = XR.SAP_DELIV_ID_FISCAL_YR
            AND CDM.FRT_MVMNT_ID = XR.FRT_MVMNT_ID
            AND CDM.SHIP_BOL = FMS.BILL_LADING_ID
            AND CDM.TM_PLN_SCHD_ID = XR.TM_PLN_SCHD_ID
            AND CDM.SRC_CRT_TS >= CAST(EXTRACT(YEAR FROM CURRENT_DATE-1)-1 || '-01-01 00:00:00' AS TIMESTAMP(0))

    WHERE
        XR.FRT_MVMNT_SCHD_ID LIKE '%GDYR'
        AND XR.TM_PLN_SCHD_ID LIKE '%GDYR'
        --AND AB.EDI_AB_CNT > 1
        --AND FM.BILL_LADING_ID = '63912348547M'

    --QUALIFY
        --COUNT(*) OVER (PARTITION BY XR.FRT_MVMNT_ID, XR.FRT_MVMNT_STOP_ID, XR.TM_DELIV_ID) > 1

    ) Q
    
GROUP BY
    Q.OWN_CUST_ID
    , Q.OWN_CUST_NAME
    , Q.ACTL_GOODS_MVT_MTH_DT
    , Q.TM_CARR_ID
    , Q.CARR_SCAC_ID
    , Q.CARR_MODE_CD
    , Q.EDI_AB_CNT
