SELECT
    --YTRANSIT DATA ROLLED UP  TO SAP BOL
    YTRANSIT.BILL_LADING_ID,
    FRT_MVMNT.TMS_BOL_ID,
    YTRANSIT.SHIP_FROM_FACILITY_ID,
    YTRANSIT.SHIP_FROM_CITY_NM,
    YTRANSIT.SHIP_TO_FACILITY_ID,
    YTRANSIT.SHIP_TO_CITY_NM,
    YTRANSIT.LANE,
    YTRANSIT.TM_CARR_ID AS CARRIER,
    YTRANSIT.TRANSP_ID AS TRAILER,
    YTRANSIT.GOODS_ISS_TS,
    YTRANSIT.GOODS_ISS_DT,
    GI_CAL.DAY_OF_WEEK_NAME_ABBREV AS GOODS_ISS_DAY,
    GI_CAL.WEEK_OF_YEAR_ISO AS GOODS_ISS_WEEK,
    GI_CAL.CAL_MTH AS GOODS_ISS_MONTH,
    GI_CAL.CAL_YR AS GOODS_ISS_YEAR,
    YTRANSIT.GOODS_RCPT_TS,
    YTRANSIT.GOODS_RCPT_DT,
    GR_CAL.DAY_OF_WEEK_NAME_ABBREV AS GOODS_RCPT_DAY,
    GR_CAL.WEEK_OF_YEAR_ISO AS GOODS_RCPT_WEEK,
    GR_CAL.CAL_MTH AS GOODS_RCPT_MONTH,
    GR_CAL.CAL_YR AS GOODS_RCPT_YEAR,
    YTRANSIT.DAYS_IN_TRANSIT,
    CAST(YTRANSIT.DAYS_IN_TRANSIT AS DECIMAL(4, 0)) AS RND_DAYS_IN_TRANSIT,
    --SHPPING LANE ATRRIBUTE
    YTRANSIT.TRANSIT_TM_QTY,
    --FRIEGHT MOVEMENT (LOAD) ATTRIBUTES
    FRT_MVMNT.GATE_OUT_TS,
    FRT_MVMNT.GATE_IN_TS,
    FRT_MVMNT.MI_QTY,
    FRT_MVMNT.PLN_NOTE_1_TXT,
    FRT_MVMNT.PLN_NOTE_2_TXT,
    --ESTIMATED FRIEGHT MOVEMENT STOP TIMES
    FRT_MVMNT.PK_EST_TS,
    FRT_MVMNT.LEAVE_PK_TS,
    FRT_MVMNT.DL_EST_TS,
    FRT_MVMNT.UNLOAD_DL_TS,
    --ORDER (DELIVERY) CONTRACT TYPE
    FRT_MVMNT.CONTRACT_TYPE,
    --EWM PLANNING DATES
    EWM_PLAN.PLN_START_DT,
    EWM_PLAN.PLN_START_DAY,
    EWM_PLAN.PLN_START_TM,
    EWM_PLAN.PLN_START_TS,
    --TRANSPORT PERFORMANCE METRICS IN DAYS
    YTRANSIT.DAYS_IN_TRANSIT - YTRANSIT.TRANSIT_TM_QTY AS TRANSIT_GOAL_VS_ACTUAL,
    CAST(((FRT_MVMNT.GATE_OUT_TS - YTRANSIT.GOODS_ISS_TS) HOUR(4)) AS DECIMAL(6, 2)) / CAST(24 AS DECIMAL(6, 2)) AS GI_TO_GATE_OUT_DAYS,
    CAST(((FRT_MVMNT.GATE_OUT_TS - FRT_MVMNT.GATE_IN_TS) HOUR(4)) AS DECIMAL(6, 2)) / CAST(24 AS DECIMAL(6, 2)) AS GATE_OUT_TO_IN_DAYS,
    CAST(((FRT_MVMNT.GATE_IN_TS - YTRANSIT.GOODS_RCPT_TS) HOUR(4)) AS DECIMAL(6, 2)) / CAST(24 AS DECIMAL(6, 2)) AS GATE_IN_TO_GR_DAYS,
    CAST(((FRT_MVMNT.GATE_OUT_TS - EWM_PLAN.PLN_START_TS) HOUR(4)) AS DECIMAL(6, 2)) / CAST(24 AS DECIMAL(6, 2)) AS GATE_IN_TO_APPT_DAYS,
    --GOS VARIANCE METRICS
    CAST(((YTRANSIT.GOODS_ISS_TS - FRT_MVMNT.PK_EST_TS) HOUR(4)) AS DECIMAL(6, 2)) * CAST(24 AS DECIMAL(6, 2)) AS GI_EST_TO_ACTUAL,
    CASE
            WHEN YTRANSIT.GOODS_ISS_DT - FRT_MVMNT.PK_EST_DT < 416.6
                THEN CAST(((YTRANSIT.GOODS_ISS_TS - FRT_MVMNT.PK_EST_TS) HOUR(4)) AS DECIMAL(6, 2))
        ELSE  YTRANSIT.GOODS_ISS_DT - FRT_MVMNT.PK_EST_DT
    END AS GI_EST_TO_ACTL_HR_VAR,
    CASE
            WHEN YTRANSIT.GOODS_RCPT_DT - FRT_MVMNT.DL_EST_DT < 416.6
                THEN CAST(((YTRANSIT.GOODS_RCPT_TS - FRT_MVMNT.DL_EST_TS) HOUR(4)) AS DECIMAL(6, 2))
        ELSE (YTRANSIT.GOODS_RCPT_DT - FRT_MVMNT.DL_EST_DT) * 24
    END AS GR_EST_TO_ACTL_HR_VAR,
    CASE
        WHEN YTRANSIT.GOODS_RCPT_DT - EWM_PLAN.PLN_START_DT < 416.6
            THEN CAST(((YTRANSIT.GOODS_RCPT_TS - EWM_PLAN.PLN_START_TS) HOUR(4)) AS DECIMAL(6, 2)) / CAST(24 AS DECIMAL(6, 2))
        ELSE (YTRANSIT.GOODS_RCPT_DT - EWM_PLAN.PLN_START_DT) *24
    END AS APPT_TO_GR_DAYS,
    --WEIGHT ROLLED UP TO BOL FROM AND TO FACILITY
    YTRANSIT.WEIGHT_QTY,
    --OUTBOUND DELIVERY NOTE UNIT QTY AND COUNT OF MATL CODES
    YTRANSIT.RPT_DELIV_QTY,
    YTRANSIT.RPT_QTY_UNIT_MEAS_ID,
    YTRANSIT.SKU_COUNT,
    --TOTAL LANE TRANSIT GOAL
    YTRANSIT.TRANSIT_DY_GOAL,
    CAST(YTRANSIT.TRANSIT_DY_GOAL AS DECIMAL(4, 0)) AS RND_TRANSIT_DY_GOAL,
    --PREVIOUS SUNDAY FOR FILTERING LAST WEEK
    FILTER.LAST_SUNDAY,
    FILTER.LAST_SUNDAY - 6 AS LAST_WEEK_MON,
    CASE
        WHEN RND_DAYS_IN_TRANSIT IS NULL
            THEN 'Not Applicable'
        WHEN RND_DAYS_IN_TRANSIT <= RND_TRANSIT_DY_GOAL
            THEN 'In Time'
        ELSE 'Late'
    END AS GOAL_STATUS,
    ADD_MONTHS(((CURRENT_DATE - 1) - DAYOFMONTH(CURRENT_DATE-1)) +1, -1) AS PRI_MONTH_START,
    ((CURRENT_DATE - 1) - DAYOFMONTH(CURRENT_DATE -1)) AS PRI_MONTH_END,
    ((CURRENT_DATE - 1) - DAYOFMONTH(CURRENT_DATE-1))+1 AS CURR_MONTH_START,
    ADD_MONTHS(((CURRENT_DATE - 1) - DAYOFMONTH(CURRENT_DATE-1)) +1, 1) -1 AS CURR_MONTH_END,
    ((CURRENT_DATE-1)-DAYOFYEAR(CURRENT_DATE-1))+1 AS CURR_YR_START
FROM
    NA_BI_VWS.TM_TRANSIT_SMRY YTRANSIT
    INNER JOIN GDYR_BI_VWS.GDYR_CAL GI_CAL
    ON
        YTRANSIT.GOODS_ISS_DT = GI_CAL.DAY_DATE
    LEFT OUTER JOIN GDYR_BI_VWS.GDYR_CAL GR_CAL
    ON
        YTRANSIT.GOODS_RCPT_DT = GR_CAL.DAY_DATE
    LEFT OUTER JOIN NA_BI_VWS.TM_INBNDTRNS_SMRY_CURR EWM_PLAN
    ON
        YTRANSIT.BILL_LADING_ID = EWM_PLAN.BILL_LADING_ID
        AND YTRANSIT.SHIP_FROM_FACILITY_ID = EWM_PLAN.SHIP_FROM_FACILITY_ID
        AND YTRANSIT.SHIP_TO_FACILITY_ID = EWM_PLAN.SHIP_TO_FACILITY_ID
    LEFT OUTER JOIN NA_BI_VWS.TM_FRT_MVMNT_SMRY_CURR FRT_MVMNT
    ON
        FRT_MVMNT.BOL_ID = YTRANSIT.BILL_LADING_ID
        AND FRT_MVMNT.SHIP_FROM_FACILITY_ID = YTRANSIT.SHIP_FROM_FACILITY_ID
        AND FRT_MVMNT.SHIP_TO_FACILITY_ID = YTRANSIT.SHIP_TO_FACILITY_ID
    INNER JOIN
        (
            SELECT
                DAY_DATE AS LAST_SUNDAY
            FROM
                GDYR_BI_VWS.GDYR_CAL
            WHERE
                DAY_OF_WEEK = 1
                AND DAY_DATE BETWEEN CURRENT_DATE - 7 AND CURRENT_DATE
        )
        FILTER
    ON
        1 = 1