SELECT
    DDI.FISCAL_YR
    , DDI.DELIV_DOC_ID
    , DDI.DELIV_DOC_ITM_ID
    
    , STA.GOODS_MVT_STA_CD
    
    , TRIM(DD.BILL_LADING_ID) AS BILL_LADING_ID
    , TRIM(REGEXP_SUBSTR(DD.BILL_LADING_ID, '([0-9A-ZA-Z]+)', 1, 1, 'I')) AS BOL_SUBSTR_1
    , TRIM(REGEXP_SUBSTR(DD.BILL_LADING_ID, '([0-9A-ZA-Z]+)', 1, 2, 'I')) AS BOL_SUBSTR_2
    
    , DD.MOT_SHIP_ID

    , DDI.FACILITY_ID
    , DD.SHIP_RCVE_PT_CD
    
    , ZEROIFNULL(INV.AVAIL_TO_PROM_QTY) AS AVAIL_TO_PROM_QTY
    , ZEROIFNULL(INV.EST_DAYS_SUPPLY) AS EST_DAYS_SUPPLY
    
    , DD.SRC_CRT_TS
    , DD.PLN_GOODS_MVT_DT
    , DD.ACTL_GOODS_MVT_DT
    , DD.DELIV_DT
    
    , DD.VEND_ID
    , VEND.CUST_NAME AS VEND_NAME
    
    , DDI.MATL_ID
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    , DDI.BATCH_NBR
    , DDI.MATL_HIER_ID
    , MATL.PBU_NBR
    , MATL.PBU_NBR || ' - ' || MATL.PBU_NAME AS PBU
    , MATL.MKT_CTGY_MKT_AREA_NBR || ' - ' || MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY
    , MATL.MKT_CTGY_PROD_LINE_NBR || ' - ' || MATL.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE
    
    , DDI.BASE_UOM_CD
    , DDI.ACTL_DELIV_QTY
    
    , DDI.WT_UOM_CD
    , DDI.TOT_GROSS_WT_QTY
    , DD.TOT_WT_QTY
    
    , DDI.SD_DOC_CTGY_CD AS ORDER_CAT_ID
    , DDI.SLS_DOC_ID
    , DDI.SLS_DOC_ITM_ID
    
    , DD.SD_DOC_CTGY_CD AS DELIV_CAT_ID
    , DD.DELIV_TYP_CD AS DELIV_TYPE_ID
    , DD.INCOTERM_CD_1
    , DD.INCOTERM_CD_2

FROM NA_BI_VWS.SD_DOC_STA STA

    INNER JOIN GDYR_BI_VWS.DELIV_DOC_CURR DD
        ON DD.FISCAL_YR = STA.FISCAL_YR
        AND DD.DELIV_DOC_ID = STA.SD_DOC_ID
        AND DD.ORIG_SYS_ID = STA.ORIG_SYS_ID
        AND DD.SD_DOC_CTGY_CD = '7'

    INNER JOIN NA_BI_VWS.NAT_DELIV_DOC_ITM_CURR DDI
        ON DDI.FISCAL_YR = DD.FISCAL_YR
        AND DDI.DELIV_DOC_ID = DD.DELIV_DOC_ID
        AND DDI.ACTL_DELIV_QTY > 0

    INNER JOIN GDYR_BI_VWS.NAT_CUST_CURR VEND
        ON VEND.CUST_ID = DD.VEND_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = DDI.MATL_ID

    LEFT OUTER JOIN NA_BI_VWS.INVENTORY INV
        ON INV.FACILITY_ID = DDI.FACILITY_ID
        AND INV.MATL_ID = DDI.MATL_ID
        AND INV.DAY_DT = CURRENT_DATE-1

WHERE
    STA.FISCAL_YR = '2014'
    AND STA.DOC_CTGY_ID = '7'
    AND STA.EXP_DT = DATE '5555-12-31'
    AND STA.GOODS_MVT_STA_CD IN ('A', 'B')

ORDER BY
    DDI.FISCAL_YR DESC
    , DDI.DELIV_DOC_ID DESC
    , DDI.DELIV_DOC_ITM_ID ASC

