SELECT
    DD.DELIV_FISCAL_YR
    , DD.DELIV_ID
    , DD.BILL_LADING_ID
    
    , DD.DELIVERY_GROUP
    , DD.DELIVERY_PRIORITY
    , DD.DN_SHIPPING_CONDITION
    , DD.CUST_GRP2_CD
    , DD.TRUCKLOAD_BUILD_TEST
    , DD.YTL_BUILD_TEST
    , DD.QTY_UOM
    
    , MIN(CASE
            WHEN DD.DELIV_LINE_CNT = 1
                THEN DD.NONPARAMETRIC_DELIV_QTY
        WHEN DD.QUANTILE_ROW = 'MIN'
            THEN DD.NONPARAMETRIC_DELIV_QTY
        END) AS MIN_DELIV_LINE_QTY
    , MAX(CASE
            WHEN DD.QUANTILE_ROW = 'Q25'
                THEN DD.NONPARAMETRIC_DELIV_QTY
        END) AS Q25_DELIV_LINE_QTY
    , MAX(CASE
            WHEN DD.DELIV_LINE_CNT = 1
                THEN DD.NONPARAMETRIC_DELIV_QTY
            WHEN DD.DELIV_LINE_CNT = 2
                THEN AVG_DELIV_LINE_QTY
            WHEN DD.QUANTILE_ROW = 'Q50'
                THEN DD.NONPARAMETRIC_DELIV_QTY
        END) AS MEDIAN_DELIV_LINE_QTY
    , CAST(DD.DELIV_QTY / NULLIFZERO(DD.DELIV_LINE_CNT) AS DECIMAL(15,3)) AS AVG_DELIV_LINE_QTY
    , MAX(CASE
            WHEN DD.QUANTILE_ROW = 'Q75'
                THEN DD.NONPARAMETRIC_DELIV_QTY
        END) AS Q75_DELIV_LINE_QTY
    , MAX(CASE
            WHEN DD.DELIV_LINE_CNT = 1
                THEN DD.NONPARAMETRIC_DELIV_QTY
        WHEN DD.QUANTILE_ROW = 'MAX'
            THEN DD.NONPARAMETRIC_DELIV_QTY
        END) AS MAX_DELIV_LINE_QTY
    , DD.DELIV_QTY
    , DD.DELIV_LINE_CNT
    
    , DD.DN_SRC_CRT_TS
    --, DD.MIN_SD_CRT_TS
    --, DD.MAX_SD_CRT_TS
    --, DD.MAX_SD_ITM_CRT_TS
    
    , DD.SHIP_TO_CUST_ID
    , DD.SHIP_TO_CUST_NO
	, DD.SHIP_TO_CUST_NAME
    , DD.SHIP_TO_CUST

    , DD.OWN_CUST_ID
	, DD.OWN_CUST_NAME
	, DD.OWN_CUST
    
    , DD.SALES_ORG
	, DD.DISTR_CHAN
	, DD.CUST_GRP
    , DD.PRIM_SHIP_FACILITY_ID
    , DD.OE_REPL_IND
    
    , DD.FACILITY_ID
    , DD.FACILITY
    , DD.SHIP_PT_ID
    , DD.SHIP_PT_DESC

    , DD.GOODS_ISSUED_IND
    , DD.ROUTE_ID
    , DD.INCOTERMS
    , DD.UNLOADING_POINT
    , DD.SPECIAL_PROCESSING_IND
    , DD.PRM_SHIP_CARR_CD
    , DD.TRANSP_VEH_NO
    , DD.DELIVERY_CREATOR_TYPE
    , MAX(DD.ORDER_CREATOR_SYSTEM) AS ORDER_CREATOR_SYSTEM_IND
    , MAX(DD.ORDER_CREATOR_USER) AS ORDER_CREATOR_USER_IND

    , DD.DELIV_NOTE_CREA_DT
    , DD.DELIV_LINE_CREA_DT
    , DD.TRANSP_PLN_DT
    , DD.PICK_DT
    , DD.LOAD_DT
    , DD.PLN_GOODS_MVT_DT
    , DD.ACTL_GOODS_ISS_DT
    , DD.DELIV_DT
    
    , DD.WT_UOM
    , DD.GROSS_WT
    , DD.NET_WT
    
    , DD.VOL_UOM
    , DD.VOL
    , DD.COMPRESSED_VOL
    
FROM (

    SELECT
        DDC.FISCAL_YR AS DELIV_FISCAL_YR
        , DDC.DELIV_ID
        , DDC.BILL_LADING_ID
        
        , MAX(SDIC.DELIV_GRP_ID) OVER (PARTITION BY DDC.DELIV_ID, DDC.DELIV_LINE_NBR) AS DELIVERY_GROUP
        , MIN(SDIC.DELIV_PRTY_CD) OVER (PARTITION BY DDC.DELIV_ID, DDC.DELIV_LINE_NBR) AS DELIVERY_PRIORITY
        , DDC.SHIP_COND_ID AS DN_SHIPPING_CONDITION
        , DDC.CUST_GRP2_CD
        
        , CAST(MAX(CASE
            WHEN SDIC.DELIV_GRP_ID > 0 
                    AND SDIC.DELIV_PRTY_CD < '45' 
                    AND DDC.SHIP_COND_ID IN ('ST', 'PT') 
                    AND CUST.PRIM_SHIP_FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID
                THEN 'TLB'
            END) OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID) AS CHAR(3)) AS TRUCKLOAD_BUILD_TEST
        , CAST(MAX(CASE
            WHEN SDIC.DELIV_GRP_ID > 0 
                    AND SDIC.DELIV_PRTY_CD < '45' 
                    AND DDC.SHIP_COND_ID IN ('ST', 'PT') 
                    AND CUST.PRIM_SHIP_FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID
                THEN (CASE
                    WHEN DELIVERY_CREATOR_TYPE = 'SYSTEM'
                        THEN 'YSDTLBATCH'
                    WHEN DELIVERY_CREATOR_TYPE = 'USER'
                        THEN 'YTL_BUILD'
                    END)
            END) OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID) AS VARCHAR(10)) AS YTL_BUILD_TEST
        
        , DDC.QTY_UNIT_MEAS_ID AS QTY_UOM
        , DDC.DELIV_QTY AS NONPARAMETRIC_DELIV_QTY
        , SUM(DDC.DELIV_QTY) OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID) AS DELIV_QTY
        , COUNT(DDC.DELIV_LINE_NBR) OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID) AS DELIV_LINE_CNT
            
        , NDDC.SRC_CRT_TS AS DN_SRC_CRT_TS
/*        , MIN((CAST(SD.SRC_CRT_DT AS TIMESTAMP(0)) + (SD.SRC_CRT_TM - TIME '00:00:00' MINUTE TO SECOND))) 
            OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID) AS MIN_SD_CRT_TS
        , MAX((CAST(SD.SRC_CRT_DT AS TIMESTAMP(0)) + (SD.SRC_CRT_TM - TIME '00:00:00' MINUTE TO SECOND))) 
            OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID) AS MAX_SD_CRT_TS
        , MAX(SDIC.SRC_CRT_TS) OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID) AS MAX_SD_ITM_CRT_TS*/
        
        , CUST.SHIP_TO_CUST_ID
        , CUST.SHIP_TO_CUST_NO
    	, CUST.CUST_NAME AS SHIP_TO_CUST_NAME
        , CUST.SHIP_TO_CUST_ID || ' - ' || CUST.CUST_NAME AS SHIP_TO_CUST

        , CUST.OWN_CUST_ID
    	, CUST.OWN_CUST_NAME
    	, CUST.OWN_CUST_ID || ' - ' || CUST.OWN_CUST_NAME AS OWN_CUST
        
        , CUST.SALES_ORG_CD || ' - ' || CUST.SALES_ORG_NAME AS SALES_ORG
    	, CUST.DISTR_CHAN_CD || ' - ' || CUST.DISTR_CHAN_NAME AS DISTR_CHAN
    	, CUST.CUST_GRP_ID || ' - ' || CUST.CUST_GRP_NAME AS CUST_GRP
        , CUST.TIRE_CUST_TYP_CD AS OE_REPL_IND
        
        , CAST(CASE
            WHEN CUST.PRIM_SHIP_FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID
                THEN 'Primary LC'
            ELSE 'Out of Area'
            END AS VARCHAR(25)) AS PRIMARY_SHIP_FACILITY_TEST
        , CUST.PRIM_SHIP_FACILITY_ID
        , DDC.DELIV_LINE_FACILITY_ID AS FACILITY_ID
        , DF.FACILITY_ID || ' - ' || DF.FACILITY_NAME AS FACILITY
        , DDC.SHIP_PT_ID
        , SP.FACILITY_ID || ' - ' || SP.FACILITY_NAME AS SHIP_PT_DESC

        , DDC.GOODS_ISS_IND AS GOODS_ISSUED_IND
        , DDC.RTG_ID AS ROUTE_ID
        , DDC.TERMS_ID AS INCOTERMS
        , DDC.UNLD_PT_CD AS UNLOADING_POINT
        , DDC.SPCL_PROC_ID AS SPECIAL_PROCESSING_IND
        , DDC.PRM_SHIP_CARR_CD
        , DDC.TRANSP_VEH_NO
        , CAST(CASE
            WHEN DDC.SRC_CRT_USR_ID LIKE ANY ('LD%', 'COWD%')
                THEN 'SYSTEM'
            ELSE 'USER'
            END AS VARCHAR(10)) AS DELIVERY_CREATOR_TYPE
        , CAST(CASE
            WHEN ODC.ORDER_CREATOR LIKE ANY ('LD%', 'COWD%')
                THEN 'SYSTEM'
            END AS VARCHAR(10)) AS ORDER_CREATOR_SYSTEM
        , CAST(CASE
            WHEN ODC.ORDER_CREATOR NOT LIKE ANY ('LD%', 'COWD%')
                THEN 'USER'
            END AS VARCHAR(10)) AS ORDER_CREATOR_USER

        , DDC.DELIV_NOTE_CREA_DT
        , DDC.DELIV_LINE_CREA_DT
        , DDC.TRANSP_PLN_DT
        , DDC.PICK_DT
        , DDC.LOAD_DT
        , DDC.PLN_GOODS_MVT_DT
        , DDC.ACTL_GOODS_ISS_DT
        , DDC.DELIV_DT
        
        , DDC.WT_UNIT_MEAS_ID AS WT_UOM
        , SUM(DDC.GROSS_WT) OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID) AS GROSS_WT
        , SUM(DDC.NET_WT) OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID) AS NET_WT
        
        , DDC.VOL_UNIT_MEAS_ID AS VOL_UOM
        , SUM(DDC.VOL) OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID) AS VOL
        , SUM((CAST(CASE MATL.PBU_NBR || MATL.MKT_AREA_NBR
            WHEN '0101' THEN 0.75
            WHEN '0108' THEN 0.80
            WHEN '0305' THEN 1.20
            WHEN '0314' THEN 1.20
            WHEN '0406' THEN 1.20
            WHEN '0507' THEN 0.75
            WHEN '0711' THEN 0.75
            WHEN '0712' THEN 0.75
            WHEN '0803' THEN 1.20
            WHEN '0923' THEN 0.75
            ELSE 1
            END AS DECIMAL(15, 3)) * MATL.UNIT_VOL) * DDC.DELIV_QTY) OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID) AS COMPRESSED_VOL

        , CAST(ROW_NUMBER() OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID ORDER BY DDC.DELIV_QTY ASC) AS DECIMAL(15,3)) AS ROW_NBR
        , CAST(PERCENT_RANK() OVER (PARTITION BY DDC.FISCAL_YR, DDC.DELIV_ID ORDER BY DDC.DELIV_QTY ASC) AS DECIMAL(15,3)) AS PCT_RNK
        , CAST(CASE
            WHEN ROW_NBR = 1
                THEN 'MIN'
            WHEN ROW_NBR = CAST(ROUND(0.250 * DELIV_LINE_CNT) AS DECIMAL(15,3))
                THEN 'Q25'
            WHEN ROW_NBR = CAST(ROUND(0.500 * DELIV_LINE_CNT) AS DECIMAL(15,3))
                THEN 'Q50'
            WHEN ROW_NBR = CAST(ROUND(0.750 * DELIV_LINE_CNT) AS DECIMAL(15,3))
                THEN 'Q75'
            WHEN ROW_NBR = DELIV_LINE_CNT
                THEN 'MAX'
            END AS CHAR(3)) AS QUANTILE_ROW

    FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

        INNER JOIN NA_BI_VWS.ORDER_DETAIL_CURR ODC
            ON ODC.ORDER_FISCAL_YR = DDC.ORDER_FISCAL_YR
            AND ODC.ORDER_ID = DDC.ORDER_ID
            AND ODC.ORDER_LINE_NBR = DDC.ORDER_LINE_NBR
            AND ODC.SCHED_LINE_NBR = 1
            AND ODC.ORDER_CAT_ID = 'C'
            AND ODC.PO_TYPE_ID <> 'RO'
            --AND ODC.CUST_GRP2_CD = 'TLB'
            AND ODC.ORDER_DT >= DATE '2013-01-01'

        INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
            ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID

        INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR MATL
            ON MATL.MATL_ID = DDC.MATL_ID
            AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08', '09')
            AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')
        
        INNER JOIN NA_BI_VWS.NAT_DELIV_DOC_CURR NDDC
            ON NDDC.FISCAL_YR = DDC.FISCAL_YR
            AND NDDC.DELIV_DOC_ID = DDC.DELIV_ID

        INNER JOIN NA_BI_VWS.NAT_SLS_DOC SD
            ON SD.FISCAL_YR = DDC.ORDER_FISCAL_YR
            AND SD.SLS_DOC_ID = DDC.ORDER_ID
            AND SD.EXP_DT = DATE '5555-12-31'

        INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM_CURR SDIC
            ON SDIC.FISCAL_YR = DDC.ORDER_FISCAL_YR
            AND SDIC.SLS_DOC_ID = DDC.ORDER_ID
            AND SDIC.SLS_DOC_ITM_ID = DDC.ORDER_LINE_NBR

        LEFT OUTER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR DF
            ON DF.FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID
        
        LEFT OUTER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR SP
            ON SP.FACILITY_ID = DDC.SHIP_PT_ID

    WHERE
        --DDC.DELIV_NOTE_CREA_DT >= DATE '2014-07-01'
        DDC.ACTL_GOODS_ISS_DT IS NOT NULL
        AND DDC.DELIV_CAT_ID = 'J'
        AND DDC.SHIP_COND_ID IN ('ST', 'PT')
        AND DDC.DELIV_QTY > 0
        AND DDC.ACTL_GOODS_ISS_DT BETWEEN DATE '2014-06-01' AND DATE '2014-06-30'

    QUALIFY
        QUANTILE_ROW IS NOT NULL
    
    ) DD

GROUP BY
    DD.DELIV_FISCAL_YR
    , DD.DELIV_ID
    , DD.BILL_LADING_ID
    
    , DD.DELIVERY_GROUP
    , DD.DELIVERY_PRIORITY
    , DD.DN_SHIPPING_CONDITION
    , DD.CUST_GRP2_CD
    , DD.TRUCKLOAD_BUILD_TEST
    , DD.YTL_BUILD_TEST
    , DD.QTY_UOM
    
    , CAST(DD.DELIV_QTY / NULLIFZERO(DD.DELIV_LINE_CNT) AS DECIMAL(15,3))
    , DD.DELIV_QTY
    , DD.DELIV_LINE_CNT
        
    , DD.DN_SRC_CRT_TS
    --, DD.MIN_SD_CRT_TS
    --, DD.MAX_SD_CRT_TS
    --, DD.MAX_SD_ITM_CRT_TS
    
    , DD.SHIP_TO_CUST_ID
    , DD.SHIP_TO_CUST_NO
	, DD.SHIP_TO_CUST_NAME
    , DD.SHIP_TO_CUST

    , DD.OWN_CUST_ID
	, DD.OWN_CUST_NAME
	, DD.OWN_CUST
    
    , DD.SALES_ORG
	, DD.DISTR_CHAN
	, DD.CUST_GRP
    , DD.PRIM_SHIP_FACILITY_ID
    , DD.OE_REPL_IND
    
    , DD.FACILITY_ID
    , DD.FACILITY
    , DD.SHIP_PT_ID
    , DD.SHIP_PT_DESC

    , DD.GOODS_ISSUED_IND
    , DD.ROUTE_ID
    , DD.INCOTERMS
    , DD.UNLOADING_POINT
    , DD.SPECIAL_PROCESSING_IND
    , DD.PRM_SHIP_CARR_CD
    , DD.TRANSP_VEH_NO
    , DD.DELIVERY_CREATOR_TYPE

    , DD.DELIV_NOTE_CREA_DT
    , DD.DELIV_LINE_CREA_DT
    , DD.TRANSP_PLN_DT
    , DD.PICK_DT
    , DD.LOAD_DT
    , DD.PLN_GOODS_MVT_DT
    , DD.ACTL_GOODS_ISS_DT
    , DD.DELIV_DT
    
    , DD.WT_UOM
    , DD.GROSS_WT
    , DD.NET_WT
    
    , DD.VOL_UOM
    , DD.VOL
    , DD.COMPRESSED_VOL


/*
-- QUERY VALIDATION -- SHOULD RETURN ZERO RECORDS TO PASS
QUALIFY
    COUNT(*) OVER (PARTITION BY DD.DELIV_FISCAL_YR, DD.DELIV_ID) > 1
*/