SELECT --COUNT(*)
    TD.TM_DELIV_ID
    , TD.TM_PLN_SCHD_ID
    , TD.TM_DELIV_SPLIT_ID
    
    , DDC.FISCAL_YR AS SAP_DELIV_FISCAL_YR
    , DDC.DELIV_ID AS SAP_DELIV_ID
    , DDC.BILL_LADING_ID AS SAP_BILL_LADING_ID
    
    , TD.FRST_LST_CD
    , TD.TM_DELIV_STA_CD
    , CAST(TD.TM_DELIV_STA_DT AS TIMESTAMP(0)) + (TD.TM_DELIV_STA_TM - TIME '00:00:00' HOUR TO SECOND) AS TM_DELIV_STA_TS
    , TD.OWN_TXT AS TM_DN_APPT_IND
    
    , DDC.SHIP_TO_CUST_ID
    , CUST.SHIP_TO_CUST_ID || ' - ' || CUST.CUST_NAME AS SHIP_TO_CUST
    , CUST.OWN_CUST_ID || ' - ' || CUST.OWN_CUST_NAME AS OWN_CUST
    , DDC.CUST_GRP2_CD
    
    , CUST.PRIM_SHIP_FACILITY_ID
    , TD.TM_DELIV_FACILITY_ID

    , DDC.DELIV_LINE_FACILITY_ID
    , DDC.SHIP_FACILITY_ID
    , DDC.SHIP_PT_ID

    , DDC.DELIV_CAT_ID
    , DDC.DELIV_TYPE_ID

    , DDC.DELIV_PRTY_ID
    , DDC.SHIP_COND_ID

    , DDC.DELIV_HEADER_CRT_TS
    , DDC.MIN_DELIV_LINE_CRT_TS
    , DDC.MAX_DELIV_LINE_CRT_TS

    , DDC.TRANSP_PLN_DT
    , DDC.LOAD_DT
    , DDC.PICK_DT
    , DDC.PLN_GOODS_MVT_DT
    , DDC.ACTL_GOODS_ISS_DT
    , DDC.DELIV_DT

    , DDC.MATL_ID_CNT
    , DDC.MKT_AREA_CNT
    , DDC.DELIV_LINE_CNT

    , DDC.QTY_UOM
    , DDC.TOTAL_DELIV_QTY

    , DDC.MIN_DELIV_LINE_QTY
    , DDC.AVERAGE_DELIV_LINE_QTY
    , DDC.MEDIAN_DELIV_LINE_QTY
    , DDC.MAX_DELIV_LINE_QTY

    , DDC.WT_UOM
    , DDC.GROSS_WT

    , DDC.VOL_UOM
    , DDC.VOL
    , DDC.COMPRESSED_VOL

    , CAST(TD.EARLY_DELIV_DT AS TIMESTAMP(0)) + (TD.EARLY_DELIV_TM - TIME '00:00:00' HOUR TO SECOND) AS TM_DN_EARLY_DELIV_TS
    , CAST(TD.LATE_DELIV_DT AS TIMESTAMP(0)) + (TD.LATE_DELIV_TM - TIME '00:00:00' HOUR TO SECOND) AS TM_DN_LATE_DELIV_TS
    , CAST(TD.EARLY_ARRV_DT AS TIMESTAMP(0)) + (TD.EARLY_ARRV_TM - TIME '00:00:00' HOUR TO SECOND) AS TM_DN_EARLY_ARRV_TS
    , CAST(TD.LATE_ARRV_DT AS TIMESTAMP(0)) + (TD.LATE_ARRV_TM - TIME '00:00:00' HOUR TO SECOND) AS TM_DN_LATE_ARRV_TS
    , CAST(TD.CUST_APPT_DT AS TIMESTAMP(0)) + (TD.CUST_APPT_TM - TIME '00:00:00' HOUR TO SECOND) AS TM_DN_CUST_APPT_DT
    

    
    
FROM NA_BI_VWS.TM_DELIV_CURR TD

    INNER JOIN (
-- deliv in dev
               
                ) DDC
        ON DDC.FISCAL_YR = TD.SAP_DELIV_ID_FISCAL_YR
        AND DDC.DELIV_ID = TD.SAP_DELIV_ID

    INNER JOIN NA_BI_VWS.NAT_DELIV_DOC_CURR DD
        ON DD.FISCAL_YR = DDC.FISCAL_YR
        AND DD.DELIV_DOC_ID = DDC.DELIV_ID
        
    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID

ORDER BY
    TD.TM_DELIV_ID
    , TD.TM_PLN_SCHD_ID
    , TD.TM_DELIV_SPLIT_ID

SAMPLE 1000


