SELECT
    DDC.FISCAL_YR AS DELIV_FISCAL_YR
    , DDC.DELIV_ID
    , DDC.DELIV_LINE_NBR
    , DDC.ORDER_FISCAL_YR
    , DDC.ORDER_ID
    , DDC.ORDER_LINE_NBR
    
    , DDC.DELIV_CAT_ID
    , DDC.DELIV_TYPE_ID
    
    , DDC.SHIP_TO_CUST_ID
    , DDC.SALES_ORG_CD
    , DDC.DISTR_CHAN_CD
    , DDC.CUST_GRP_ID
    , DDC.CUST_GRP2_CD
    
    , DDC.MATL_ID
    
    , DDC.FACILITY_ID
    , DDC.DELIV_LINE_FACILITY_ID
    , DDC.SHIP_FACILITY_ID
    , DDC.SHIP_PT_ID
    
    , SDI.SRC_UPD_DT
    , SDI.DELIV_PRTY_CD
    , SDI.DELIV_GRP_ID
    , SDI.ROUTE_CD
    , SDI.SRC_CRT_TS
    , SDI.SRC_CRT_USR_ID
    , SDI.AVAIL_CHK_GRP_CD

FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR MATL
        ON MATL.MATL_ID = DDC.MATL_ID
        AND MATL.MATL_TYPE_ID IN ('ACCT', 'PCTL')
        AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07' ,'08', '09')
    
    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID

    INNER JOIN NA_BI_VWS.NAT_SLS_DOC SD
        ON SD.FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND SD.SLS_DOC_ID = DDC.ORDER_ID
        AND SD.EXP_DT = DATE '5555-12-31'
        AND SD.SD_DOC_CTGY_CD = 'C'
        AND SD.SLS_DOC_TYP_CD IN ('ZCC', 'ZEX', 'ZML', 'ZOE', 'ZOP', 'ZOR', 'ZRS', 'ZTA')
        AND SD.SALES_ORG_CD IN ('N301', 'N302', 'N303', 'N305', 'N309', 'N311', 'N312', 'N313', 'N321', 'N322', 'N323', 'N325', 'N329')
        AND SD.DISTR_CHAN_CD IN ('01', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '14', '15', '16', '20', '21', '22', '30', '31', '32', '55', '56', '62', '84')
        AND SD.DIV_CD = '01'
    
    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM_CURR SDI
        ON SDI.FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND SDI.SLS_DOC_ID = DDC.ORDER_ID
        AND SDI.SLS_DOC_ITM_ID = DDC.ORDER_LINE_NBR
        AND SDI.SLS_DOC_ITM_CTGY_CD IN ('TAMA', 'TAN', 'ZOP', 'ZRST', 'ZZML')

WHERE
    DDC.DELIV_CAT_ID = 'J'
    AND DDC.ACTL_GOODS_ISS_DT BETWEEN DATE '2014-06-01' AND DATE '2014-06-30'
