SELECT
    DDC.FISCAL_YR
    , DDC.BILL_LADING_ID
    , DDC.DELIV_ID
    , DDC.DELIV_LINE_NBR
    
    , DDC.ORDER_FISCAL_YR
    , DDC.ORDER_ID
    , DDC.ORDER_LINE_NBR
    
    , DDC.DIV_CD
    , DDC.SALES_ORG_CD
    , DDC.DISTR_CHAN_CD
    , DDC.CUST_GRP_ID
    , DDC.CUST_GRP2_CD
    , DDC.SHIP_TO_CUST_ID
    
    , CASE
        WHEN CUST.PRIM_SHIP_FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID
            THEN 'PRIMARY LC'
        ELSE 'OUT OF AREA'
        END AS PRIM_SHIP_FACILITY_TEST
    , CUST.PRIM_SHIP_FACILITY_ID
    , DDC.DELIV_LINE_FACILITY_ID
    , DDC.SHIP_PT_ID
    
    , DDC.MATL_ID
    , MATL.PBU_NBR
    , MATL.MKT_AREA_NBR
    , CAST(CASE MATL.PBU_NBR || MATL.MKT_AREA_NBR
        WHEN '0101' THEN 0.75
        WHEN '0108' THEN 0.80
        WHEN '0305' THEN 1.20
        WHEN '0314' THEN 1.20
        WHEN '0406' THEN 1.20
        WHEN '0507' THEN 0.75
        WHEN '0711' THEN 0.75
        WHEN '0712' THEN 0.75
        WHEN '0803' THEN 1.20
        WHEN '0923' THEN 0.75
        ELSE 1.00
        END AS DECIMAL(15, 3)) AS COMPRESSION_FACTOR
    
    , DDC.QTY_UNIT_MEAS_ID
    , DDC.DELIV_QTY
    
    , DDC.WT_UNIT_MEAS_ID
    , DDC.GROSS_WT
    , CASE WHEN SDI.DELIV_GRP_ID = 0 THEN DDC.GROSS_WT ELSE 0 END AS ADD_ON_GROSS_WT
    
    , DDC.VOL_UNIT_MEAS_ID
    , DDC.VOL
    , COMPRESSION_FACTOR * DDC.VOL AS COMPRESSED_VOL
    
    , DDC.DELIV_NOTE_CREA_DT
    , DD.SRC_CRT_TS AS DELIV_HEADER_CRT_TS
    , DDC.DELIV_LINE_CREA_DT
    , DDI.SRC_CRT_TS AS DELIV_ITEM_CRT_TS
    , DDC.TRANSP_PLN_DT
    , DDC.LOAD_DT
    , DDC.PICK_DT
    , DDC.PLN_GOODS_MVT_DT
    , DDC.ACTL_GOODS_ISS_DT
    , DDC.DELIV_DT

    , SDI.DELIV_GRP_ID
    , CASE WHEN SDI.DELIV_GRP_ID = 0 THEN 1 ELSE 0 END AS ADD_ON_DELIV_LINE_CNT
    , DDC.DELIV_PRTY_ID
    , DDC.SHIP_COND_ID
    , DDC.RTG_ID AS ROUTE_ID
    , DDC.TERMS_ID
    , DDC.UNLD_PT_CD
    , DDC.SPCL_PROC_ID
    , DDC.GOODS_ISS_IND
    
    , DDC.DELIV_CAT_ID
    , DDC.DELIV_TYPE_ID
    , DDC.ITEM_CAT_ID

FROM NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    -- NEED TO FILTER ON MATERIAL HIERARCHY
    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR MATL
        ON MATL.MATL_ID = DDC.MATL_ID
        AND MATL.PBU_NBR IN ('01', '03', '04', '05', '07', '08')

    -- NEED TO EXCLUDE OUT-OF-AREA (LINES NOT AT THEIR PRIMARY LC)
    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID
        AND CUST.PRIM_SHIP_FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID

    -- DELIVERY HEADER CREATE TIMESTAMP
    INNER JOIN NA_BI_VWS.NAT_DELIV_DOC_CURR DD
        ON DD.FISCAL_YR = DDC.FISCAL_YR
        AND DD.DELIV_DOC_ID = DDC.DELIV_ID
        -- LIMIT JOIN RECORDS
        AND DD.ACTL_GOODS_MVT_DT >= DATE '2014-01-01'
        AND DD.SRC_CRT_TS >= CAST('2013-11-01 00:00:00' AS TIMESTAMP(0))
        -- STANDARD DELIVERY
        AND DD.SD_DOC_CTGY_CD = 'J'
    
    -- DELIVERY ITEM CREATE TIMESTAMP
    INNER JOIN NA_BI_VWS.NAT_DELIV_DOC_ITM_CURR DDI
        ON DDI.FISCAL_YR = DDC.FISCAL_YR
        AND DDI.DELIV_DOC_ID = DDC.DELIV_ID
        AND DDI.DELIV_DOC_ITM_ID = DDC.DELIV_LINE_NBR
        -- LIMIT JOIN RECORDS
        AND DDI.SRC_CRT_TS >= CAST('2013-11-01 00:00:00' AS TIMESTAMP(0))
        -- EXCLUDE INTERNAL SALES
        AND DDI.DISTR_CHAN_CD <> '81'
        -- SALES DOCS
        AND DDI.SD_DOC_CTGY_CD = 'C'
        AND DDI.ACTL_DELIV_QTY > 0
        
    -- DELIVERY GROUP CODE (DELIVERY DOC ITEM SEEMS TO ONLY HAVE ZEROS...)
    INNER JOIN NA_BI_VWS.NAT_SLS_DOC_ITM_CURR SDI
        ON SDI.FISCAL_YR = DDC.ORDER_FISCAL_YR
        AND SDI.SLS_DOC_ID = DDC.ORDER_ID
        AND SDI.SLS_DOC_ITM_ID = DDC.ORDER_LINE_NBR
        -- LIMIT JOIN RECORDS
        AND SDI.SRC_CRT_TS >= CAST('2013-01-01 00:00:00' AS TIMESTAMP(0))
 
WHERE
    DDC.DELIV_NOTE_CREA_DT >= CAST(EXTRACT(YEAR FROM (CURRENT_DATE-1)) || '-01-01' AS DATE)
    AND DDC.DELIV_CAT_ID = 'J'
    AND DDC.DELIV_QTY > 0
    AND DDC.CUST_GRP2_CD = 'TLB'
/*
    AND DDC.SALES_ORG_CD IN (
            'N301', 'N302', 'N303', 'N304', 'N305'
            , 'N311', 'N312', 'N313'
            , 'N321', 'N322', 'N323', 'N325'
        )
    AND DDC.DELIV_LINE_FACILITY_ID IN (
            'N501', 'N502', 'N503', 'N505', 'N508', 'N509', 'N510', 'N513', 'N518', 'N526', 'N5CA', 'N5US'
            , 'N602', 'N607', 'N613', 'N61L', 'N61Q', 'N623', 'N636', 'N637', 'N639', 'N63X', 'N64C', 'N64E'
            , 'N64M', 'N64T', 'N653', 'N659', 'N661', 'N662', 'N667', 'N670', 'N692', 'N699', 'N6A6', 'N6AE'
            , 'N6AG', 'N6CK', 'N6D3', 'N6DA', 'N6DB', 'N6DE', 'N6DF', 'N6J8'
        )
*/

ORDER BY
    DDC.FISCAL_YR
    , DDC.DELIV_ID
    , DDC.DELIV_LINE_NBR
