SELECT
    TD.TM_DELIV_ID
    , TD.TM_PLN_SCHD_ID
    , TD.TM_DELIV_SPLIT_ID
    
    , TD.SAP_DELIV_ID_FISCAL_YR AS SAP_DELIV_FISCAL_YR
    , TD.SAP_DELIV_ID
    
    , TD.TM_DELIV_TYP_CD
    , TD.TM_SHIP_FROM_LOC_ID
    , TD.TM_SHIP_TO_LOC_ID
    , TD.TM_DELIV_FACILITY_ID
    , TD.FRT_TERMS_CD
    , TD.CNSLDT_CD
    , TD.CNFRM_ID
    , TD.SHIP_MODE_CD
    , TD.SHIP_PRTY_ID
    , TD.DELIV_MOD_IND
    
    , TD.TM_DELIV_STA_CD
    , CAST(TD.TM_DELIV_STA_DT AS TIMESTAMP(0)) + (TD.TM_DELIV_STA_TM - TIME '00:00:00' HOUR TO SECOND) AS TM_DELIV_STA_TS
    
    , CAST(TD.EARLY_DELIV_DT AS TIMESTAMP(0)) + (TD.EARLY_DELIV_TM - TIME '00:00:00' HOUR TO SECOND) AS EARLY_DELIV_TS
    , CAST(TD.LATE_DELIV_DT AS TIMESTAMP(0)) + (TD.LATE_DELIV_TM - TIME '00:00:00' HOUR TO SECOND) AS LATE_DELIV_TS
    , CAST(TD.EARLY_ARRV_DT AS TIMESTAMP(0)) + (TD.EARLY_ARRV_TM - TIME '00:00:00' HOUR TO SECOND) AS EARLY_ARRV_TS
    , CAST(TD.LATE_ARRV_DT AS TIMESTAMP(0)) + (TD.LATE_ARRV_TM - TIME '00:00:00' HOUR TO SECOND) AS LATE_ARRV_TS
    , CAST(TD.CUST_APPT_DT AS TIMESTAMP(0)) + (TD.CUST_APPT_TM - TIME '00:00:00' HOUR TO SECOND) AS CUST_APPT_TS
    
    , TD.OWN_TXT AS TM_APPT_IND
    , CAST(TD.SHIP_DT AS TIMESTAMP(0)) + (TD.SHIP_TM - TIME '00:00:00' HOUR TO SECOND) AS SHIP_TS
    
FROM NA_BI_VWS.TM_DELIV_CURR TD

WHERE
    TD.EARLY_DELIV_DT >= DATE '2014-01-01'
    AND TD.INBOUND_IND = 'N'
    AND TD.SAP_DELIV_ID_FISCAL_YR = CAST(EXTRACT(YEAR FROM CURRENT_DATE) AS CHAR(4))
    AND TD.TM_DELIV_FACILITY_ID IN ('ALASKA', 'AMERICAN', 'BRAND', 'CROSS', 'DISCOUNT', 'FRIDAY', 'MONDAY', 'N602', 'N603', 'N623', 'N636', 'N637', 'N639', 'N699', 'N6D3', 'SAMS', 'SEARS', 'THURSDAY', 'VMI', 'WAL_FRI', 'WAL_MON', 'WAL_THURS', 'WAL_TUES', 'WAL_WEDS')

ORDER BY
    TD.TM_DELIV_ID
    , TD.TM_PLN_SCHD_ID
    , TD.TM_DELIV_SPLIT_ID
    
    , TD.SAP_DELIV_ID_FISCAL_YR
    , TD.SAP_DELIV_ID
