SELECT
    XREF.FRT_MVMNT_ID
    , XREF.FRT_MVMNT_SCHD_ID
    , XREF.FRT_MVMNT_STOP_ID
    
    , COALESCE(FM.BILL_LADING_ID, CDM.MSTR_BOL) AS TMS_MSTR_BOL
    , COALESCE(FMS.BILL_LADING_ID, CDM.SHIP_BOL) AS TMS_STOP_BOL

    , XREF.TM_DELIV_ID
    , XREF.TM_PLN_SCHD_ID
    , XREF.TM_DELIV_SPLIT_ID
    
    , XREF.SAP_DELIV_ID_FISCAL_YR AS SAP_FISCAL_YR
    , XREF.SAP_DELIV_ID
    
    , CDM.TM_DEST_TYP_CD
    , FM.FRT_MVMNT_STA_CD
    , FMS.STOP_TYP_CD
    , DC.TM_DELIV_TYP_CD
    , DC.TM_DELIV_STA_CD AS TMD_DELIV_STA_CD
    , CAST(DC.TM_DELIV_STA_DT AS TIMESTAMP(0)) + (DC.TM_DELIV_STA_TM - TIME '00:00:00' HOUR TO SECOND) AS TMD_DELIV_STA_TS
    
    , FM.TM_CARR_ID
    , FM.TRLR_TYP_ID
    , FM.TRANSP_MODE_CD
    
    , DC.TM_DELIV_FACILITY_ID
    , DC.TM_SHIP_FROM_LOC_ID AS TMD_SHIP_FROM_LOC_ID
    , DC.TM_SHIP_TO_LOC_ID AS TMD_SHIP_TO_LOC_ID
    , CAST(DC.SRC_UPD_DT AS TIMESTAMP(0)) + (DC.SRC_UPD_TM - TIME '00:00:00' HOUR TO SECOND) AS TMD_SRC_UPD_TS
    
    , FM.STOP_QTY
    
    , FMS.WT_QTY AS FMS_WT_QTY
    , FMS.CU_VOL_QTY AS FMS_CU_VOL_QTY
    , FMS.PC_QTY AS FMS_PC_QTY   
    , FMS.MI_QTY AS FMS_MI_QTY
    , FMS.MI_ID
    
    , CDM.CARR_ACCEPT_TS AS CDM_CARR_ACCEPT_TS
    , CDM.READYBYPLN_DT AS CDM_READY_BY_TS
    , CDM.REQ_DELIV_DT AS CDM_REQ_DELIV_DT
    , CDM.LPC_APPT_TS AS CDM_LPC_APPT_TS
    , CDM.PLN_ARRV_TS AS CDM_PLN_ARRV_TS
    , CDM.ARRV_AT_PKUP_TS AS CDM_ARRV_AT_PKUP_TS
    , CDM.DEPART_FROM_PKUP_TS AS CDM_DEPART_FROM_PKUP_TS
    , CDM.ARRV_AT_DELIV_TS AS CDM_ARRV_AT_DELIV_TS

    , DC.OWN_TXT AS APPT_IND
    , CAST(DC.CUST_APPT_DT AS TIMESTAMP(0)) + (DC.CUST_APPT_TM - TIME '00:00:00' HOUR TO SECOND) AS TMD_CUST_APPT_TS
    , CAST(DC.EARLY_ARRV_DT AS TIMESTAMP(0)) + (DC.EARLY_ARRV_TM - TIME '00:00:00' HOUR TO SECOND) AS TMD_EARLY_ARRV_TS
    , CAST(DC.LATE_ARRV_DT AS TIMESTAMP(0)) + (DC.LATE_ARRV_TM - TIME '00:00:00' HOUR TO SECOND) AS TMD_LATE_ARRV_TS
    , CAST(DC.EARLY_DELIV_DT AS TIMESTAMP(0)) + (DC.EARLY_DELIV_TM - TIME '00:00:00' HOUR TO SECOND) AS TMD_EARLY_DELIV_TS
    , CAST(DC.LATE_DELIV_DT AS TIMESTAMP(0)) + (DC.LATE_DELIV_TM - TIME '00:00:00' HOUR TO SECOND) AS TMD_LATE_DELIV_TS
    
    , CAST(FMS.OPEN_DT AS TIMESTAMP(0)) + (FMS.OPEN_TM - TIME '00:00:00' HOUR TO SECOND) AS FMS_OPEN_TS
    , CAST(FMS.CLOS_DT AS TIMESTAMP(0)) + (FMS.CLOS_TM - TIME '00:00:00' HOUR TO SECOND) AS FMS_CLOS_TS
    , CAST(FMS.EARLY_ARRV_DT AS TIMESTAMP(0)) + (FMS.EARLY_ARRV_TM - TIME '00:00:00' HOUR TO SECOND) AS FMS_EARLY_ARRV_TS
    , CAST(FMS.LATE_ARRV_DT AS TIMESTAMP(0)) + (FMS.LATE_ARRV_TM - TIME '00:00:00' HOUR TO SECOND) AS FMS_LATE_ARRV_TS
    , CAST(FMS.ARRV_DT AS TIMESTAMP(0)) + (FMS.ARRV_TM - TIME '00:00:00' HOUR TO SECOND) AS FMS_ARRV_TS
    , CAST(FMS.UNLD_START_DT AS TIMESTAMP(0)) + (FMS.UNLD_START_TM - TIME '00:00:00' HOUR TO SECOND) AS FMS_UNLD_START_TS
    , CAST(FMS.UNLD_END_DT AS TIMESTAMP(0)) + (FMS.UNLD_END_TM - TIME '00:00:00' HOUR TO SECOND) AS FMS_UNLD_END_TS
    , CAST(FMS.DEPART_DT AS TIMESTAMP(0)) + (FMS.DEPART_TM - TIME '00:00:00' HOUR TO SECOND) AS FMS_DEPART_TS
    , CAST(FMS.CARR_APPT_DT AS TIMESTAMP(0)) + (FMS.CARR_APPT_TM - TIME '00:00:00' HOUR TO SECOND) AS FMS_CARR_APPT_TS
    , CAST(FMS.EARLY_DEPART_DT AS TIMESTAMP(0)) + (FMS.EARLY_DEPART_TM - TIME '00:00:00' HOUR TO SECOND) AS FMS_EARLY_DEPART_TS
    , CAST(FMS.LATE_DEPART_DT AS TIMESTAMP(0)) + (FMS.LATE_DEPART_TM - TIME '00:00:00' HOUR TO SECOND) AS FMS_LATE_DEPART_TS
    
    , CAST(FM.EARLY_DEPART_DT AS TIMESTAMP(0)) + (FM.EARLY_DEPART_TM - TIME '00:00:00' HOUR TO SECOND) AS FM_EARLY_DEPART_TS
    , CAST(FM.LATE_DEPART_DT AS TIMESTAMP(0)) + (FM.LATE_DEPART_TM - TIME '00:00:00' HOUR TO SECOND) AS FM_LATE_DEPART_TS
    , CAST(FM.BEST_DEPART_DT AS TIMESTAMP(0)) + (FM.BEST_DEPART_TM - TIME '00:00:00' HOUR TO SECOND) AS FM_BEST_DEPART_TS
    , CAST(FM.DOCK_DT AS TIMESTAMP(0)) + (FM.DOCK_TM - TIME '00:00:00' HOUR TO SECOND) AS FM_DOCK_TS
    , CAST(FM.TRIP_CMPLT_DT AS TIMESTAMP(0)) + (FM.TRIP_CMPLT_TM - TIME '00:00:00' HOUR TO SECOND) AS FM_TRIP_CMPLT_TS
    
FROM NA_BI_VWS.TM_FRTMV_DLV_XREF_CURR XREF

    INNER JOIN NA_BI_VWS.TM_DELIV_CURR DC
        ON DC.TM_DELIV_ID = XREF.TM_DELIV_ID
        AND DC.TM_PLN_SCHD_ID = XREF.TM_PLN_SCHD_ID
        AND DC.TM_DELIV_SPLIT_ID = XREF.TM_DELIV_SPLIT_ID
        AND DC.SRC_UPD_DT >= DATE '2014-01-01'
        AND DC.TM_SHIP_FROM_LOC_ID = '00903354'

    INNER JOIN NA_BI_VWS.TM_FRT_MVMNT_STOP_CURR FMS
        ON FMS.FRT_MVMNT_ID = XREF.FRT_MVMNT_ID
        AND FMS.FRT_MVMNT_SCHD_ID = XREF.FRT_MVMNT_SCHD_ID
        AND FMS.FRT_MVMNT_STOP_ID = XREF.FRT_MVMNT_STOP_ID
        AND FMS.OPEN_DT >= DATE '2014-01-01'
    
    INNER JOIN NA_BI_VWS.TM_FRT_MVMNT_CURR FM
        ON FM.FRT_MVMNT_ID = XREF.FRT_MVMNT_ID
        AND FM.FRT_MVMNT_SCHD_ID = XREF.FRT_MVMNT_SCHD_ID
        AND FM.EARLY_DEPART_DT >= DATE '2014-01-01'
        AND FM.FROM_TM_LOC_ID = '00903354'

    LEFT OUTER JOIN NA_BI_VWS.TM_CARR_DELIV_MSG_CURR CDM
        ON CDM.TM_DELIV_ID = XREF.TM_DELIV_ID
        AND CDM.TM_PLN_SCHD_ID = XREF.TM_PLN_SCHD_ID
        AND CDM.FRT_MVMNT_ID = XREF.FRT_MVMNT_ID
        AND CDM.SRC_CRT_TS >= TIMESTAMP '2014-01-01 00:00:00'
        AND CDM.TM_SHIP_FROM_LOC_ID = '00903354'

WHERE
    XREF.SAP_DELIV_ID_FISCAL_YR >= CAST(EXTRACT(YEAR FROM CURRENT_DATE)-1 AS CHAR(4))
    
/*
-- MINIMALLY SUFFICIENT UNIQUE IDENTIFIER
QUALIFY
    COUNT(*) OVER (PARTITION BY XREF.FRT_MVMNT_ID, XREF.FRT_MVMNT_STOP_ID, XREF.TM_DELIV_ID) > 1
*/

ORDER BY
    XREF.FRT_MVMNT_ID
    , XREF.FRT_MVMNT_SCHD_ID
    , XREF.FRT_MVMNT_STOP_ID
    
    , XREF.TM_DELIV_ID
    , XREF.TM_PLN_SCHD_ID
    , XREF.TM_DELIV_SPLIT_ID
    
    , XREF.SAP_DELIV_ID_FISCAL_YR
    , XREF.SAP_DELIV_ID



/*    , DC.FRST_LST_CD
    
    , DC.EMRGNCY_CD
    , DC.PLN_DELIV_IND
    , DC.FRT_TERMS_CD
    , DC.CNSLDT_CD
    
    , DC.SHIP_MODE_CD
    , DC.LIVE_LOAD_DELIV_CD
    , DC.LIVE_UNLD_DELIV_CD
    , DC.DELIV_MOD_IND
    , DC.SUBSTNTL_CHG_IND
    , DC.EXT_STA_CD

    , DC.INBOUND_IND
    , DC.EXCL_FROM_ROUTE_INTFC_IND
    
    , FMS.FIX_ETA_IND
    , FMS.CARR_CNFM_PK_DELIV_IND
    
    , FM.APPT_REQ_IND
    , FM.ALLCT_IND
    , FM.XDOCK_CD
    , FM.LOAD_MODIFY_IND
    , FM.LOAD_LOCK_IND
    , FM.LANE_ID

    , FM.TRLR_FILL_IND
    , FM.FRT_PAY_PROC_IND
    , FM.NEED_REVIEW_IND
    
    , FM.FEASBL_IND
    , FM.FEASBL_ERR_1_CD
    , FM.FEASBL_ERR_2_CD
    , FM.FEASBL_ERR_3_CD
    , FM.FEASBL_ERR_4_CD
    , FM.FEASBL_ERR_5_CD*/
