SELECT
    XREF.FRT_MVMNT_ID
    , XREF.FRT_MVMNT_SCHD_ID
    , XREF.FRT_MVMNT_STOP_ID
    
    , XREF.TM_DELIV_ID
    , XREF.TM_PLN_SCHD_ID
    , XREF.TM_DELIV_SPLIT_ID
    
    , XREF.SAP_DELIV_ID_FISCAL_YR
    , XREF.SAP_DELIV_ID

FROM NA_BI_VWS.TM_FRTMV_DLV_XREF_CURR XREF

WHERE
    XREF.SAP_DELIV_ID_FISCAL_YR = CAST(EXTRACT(YEAR FROM CURRENT_DATE) AS CHAR(4))
    
ORDER BY
    XREF.FRT_MVMNT_ID
    , XREF.FRT_MVMNT_SCHD_ID
    , XREF.FRT_MVMNT_STOP_ID
    
    , XREF.TM_DELIV_ID
    , XREF.TM_PLN_SCHD_ID
    , XREF.TM_DELIV_SPLIT_ID
    
    , XREF.SAP_DELIV_ID_FISCAL_YR
    , XREF.SAP_DELIV_ID
