SELECT
    --COUNT(*) AS CNT
    XREF.SAP_DELIV_ID_FISCAL_YR AS SAP_DELIV_FISCAL_YR
    , XREF.SAP_DELIV_ID
    
    , TDC.TM_DELIV_ID
    , TDC.TM_PLN_SCHD_ID
    , TDC.TM_DELIV_SPLIT_ID
    
    , FMC.FRT_MVMNT_ID
    , FMC.FRT_MVMNT_SCHD_ID
    , FMSC.FRT_MVMNT_STOP_ID
        
    , FMC.BILL_LADING_ID AS TM_MASTER_BOL
    , FMSC.BILL_LADING_ID AS TM_SHIP_BOL
    , DDC.BILL_LADING_ID AS SAP_BOL
    
    , DDC.SHIP_TO_CUST_ID
    , CUST.CUST_NAME AS SHIP_TO_CUST_NAME
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    
    , DDC.WT_UOM_CD AS WEIGHT_UOM
    , DDC.TOT_WT_QTY
    , DDC.TOT_NET_WT_QTY
    
    , DDC.VOL_UOM_CD AS VOLUME_UOM
    , DDC.TOT_VOL_QTY
    
    , FMC.FRT_MVMNT_STA_CD
    , TDC.TM_DELIV_STA_CD
    
    , TDC.TM_DELIV_TYP_CD
    
    , TDC.TM_DELIV_FACILITY_ID
    , CUST.PRIM_SHIP_FACILITY_ID
    , CASE
        WHEN CUST.PRIM_SHIP_FACILITY_ID = TDC.TM_DELIV_FACILITY_ID
            THEN 'Primary LC'
        ELSE 'Out of Area'
        END AS PRIMARY_SHIP_FACILITY_TEST
    
    , DDC.SHIP_RCVE_PT_CD
    
    , DDC.ROUTE_CD
    , DDC.DELIV_PRTY_CD
    , DDC.SHIP_COND_CD
    , FMC.TRANSP_MODE_CD
    , FMC.FROM_TM_LOC_ID
    , FMSC.TM_LOC_ID
    
    , FMSC.WT_QTY AS STOP_WT_QTY
    , FMSC.CU_VOL_QTY AS STOP_CU_VOL_QTY
    
    , FMC.TM_CARR_ID
    , FMC.TRLR_TYP_ID
    , FMC.TRLR_ID
    
    , FMC.WT_QTY
    , FMC.CU_VOL_QTY
    , FMC.PC_QTY
    
    , TDC.OWN_TXT AS APPT_CODE_IND
    , CAST(TDC.CUST_APPT_DT AS TIMESTAMP(0)) + (TDC.CUST_APPT_TM - TIME '00:00:00' HOUR TO SECOND) AS CUSTOMER_APPT_TS
    
    , DDC.SRC_CRT_TS AS SAP_DN_CRT_TS
    , DDC.SRC_CRT_USR_ID AS SAP_DN_CRT_USER_ID
    
    , CAST(FMC.DOCK_DT AS TIMESTAMP(0)) + (FMC.DOCK_TM - TIME '00:00:00' HOUR TO SECOND) AS DOCK_TS    
    , DDC.ACTL_GOODS_MVT_DT

FROM NA_BI_VWS.TM_FRTMV_DLV_XREF_CURR XREF

    INNER JOIN NA_BI_VWS.TM_FRT_MVMNT_STOP_CURR FMSC
        ON FMSC.FRT_MVMNT_ID = XREF.FRT_MVMNT_ID
        AND FMSC.FRT_MVMNT_SCHD_ID = XREF.FRT_MVMNT_SCHD_ID
        AND FMSC.FRT_MVMNT_STOP_ID = XREF.FRT_MVMNT_STOP_ID

    INNER JOIN NA_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_NO = FMSC.TM_LOC_ID
        AND CUST.CUST_GRP2_CD IN ('20M', 'MAN', 'NWC', 'TLB', 'YDN')
        AND CUST.DISTR_CHAN_CD NOT IN ('12', '14', '56', '81', '95')
        AND CUST.OWN_CUST_ID <> '00A0003088'

    INNER JOIN NA_BI_VWS.TM_FRT_MVMNT_CURR FMC
        ON FMC.FRT_MVMNT_ID = FMSC.FRT_MVMNT_ID
        AND FMC.FRT_MVMNT_SCHD_ID = FMSC.FRT_MVMNT_SCHD_ID

    INNER JOIN NA_BI_VWS.TM_DELIV_CURR TDC
        ON TDC.TM_DELIV_ID = XREF.TM_DELIV_ID
        AND TDC.TM_PLN_SCHD_ID = XREF.TM_PLN_SCHD_ID
        AND TDC.TM_DELIV_SPLIT_ID = XREF.TM_DELIV_SPLIT_ID
    
    INNER JOIN NA_BI_VWS.NAT_DELIV_DOC_CURR DDC
        ON DDC.FISCAL_YR = XREF.SAP_DELIV_ID_FISCAL_YR
        AND DDC.DELIV_DOC_ID = XREF.SAP_DELIV_ID
        AND DDC.SD_DOC_CTGY_CD = 'J'
        AND DDC.ACTL_GOODS_MVT_DT BETWEEN DATE '2014-05-01' AND (CURRENT_DATE-1)

ORDER BY
    XREF.SAP_DELIV_ID_FISCAL_YR
    , XREF.SAP_DELIV_ID
    , TDC.TM_DELIV_ID
    , TDC.TM_PLN_SCHD_ID
    , TDC.TM_DELIV_SPLIT_ID
    , FMC.FRT_MVMNT_ID
    , FMC.FRT_MVMNT_SCHD_ID
    , FMSC.FRT_MVMNT_STOP_ID

/*
-- CONFIRMS DUPLICATES ARE NOT BEING CREATED IF ZERO RECORDS ARE RETURNED WHEN QUALIFY IS UNCOMMENTED
QUALIFY
    COUNT(*) OVER (PARTITION BY XREF.FRT_MVMNT_ID, XREF.FRT_MVMNT_SCHD_ID, XREF.FRT_MVMNT_STOP_ID, XREF.TM_DELIV_ID) > 1
*/