SELECT
    CDM.SAP_DELIV_FISCAL_YR
    , CDM.SAP_DELIV_ID
    , CDM.FRT_MVMNT_ID
    , CDM.TM_DELIV_FISCAL_YR
    , CDM.TM_DELIV_ID
    , CDM.TM_PLN_SCHD_ID
    , CDM.TM_SHIP_FROM_LOC_ID
    , CDM.TM_SHIP_TO_LOC_ID
    , CDM.CUST_ID
    , CDM.TM_CARR_ID
    , CDM.CARR_SCAC_ID
    , CDM.MSTR_BOL
    , CDM.SHIP_BOL
    , CDM.CARR_STOP_QTY
    , CDM.CARR_ACCEPT_TS
    , CDM.READYBYPLN_DT
    , CDM.ARRV_AT_PKUP_TS
    , CDM.DEPART_FROM_PKUP_TS
    , CDM.REQ_DELIV_DT
    , CDM.PLN_ARRV_TS
    , CDM.LPC_APPT_TS

FROM NA_BI_VWS.TM_CARR_DELIV_MSG_CURR CDM

WHERE
    CDM.SAP_DELIV_FISCAL_YR = CAST(EXTRACT(YEAR FROM CURRENT_DATE) AS CHAR(4))
    AND CDM.TM_DELIV_FISCAL_YR = CAST(EXTRACT(YEAR FROM CURRENT_DATE) AS CHAR(4))
    AND CDM.TM_SHIP_FROM_LOC_ID IN ('00903208', '00907821', '00901308', '00903905', '00903354', '00909405', '00904004')
