SELECT
    FM.FRT_MVMNT_ID
    , FM.FRT_MVMNT_SCHD_ID
    , FM.FRT_MVMNT_SCHD_ID
    
    , FM.FRT_MVMNT_STA_CD
    , FM.BILL_LADING_ID
    , FM.TRANSP_MODE_CD
    , FM.TM_CARR_ID
    , FM.TRLR_TYP_ID
    , FM.APPT_REQ_IND
    , FM.ALLCT_IND
    , FM.TRLR_ID
    , FM.TRLR_BLD_ID
    , FM.REF_BOL_ID
    , FM.RATE_TM_CARR_ID
    , FM.FRT_TERM_CD
    , FM.TEAM_IND
    , FM.XDOCK_CD
    
    , FM.FROM_TM_LOC_ID
    , FM.TO_TM_LOC_ID
    , FM.STOP_QTY
    , FM.WT_QTY
    , FM.CU_VOL_QTY
    , FM.PC_QTY
    , FM.PLLT_QTY
    , FM.NTFY_QTY
    , FM.MI_QTY
    
    , FM.DRIVE_TM
    , FM.ELAPSE_TM
    , FM.SERVE_TM
    , FM.LAYOVER_TM
    , FM.SHIP_BUFFER_TM
    , FM.SHIP_SLACK_TM
    , FM.WRK_TM
    
    , CAST(FM.EARLY_DEPART_DT AS TIMESTAMP(0)) + (FM.EARLY_DEPART_TM - TIME '00:00:00' HOUR TO SECOND(0)) AS EARLY_DEPART_TS
    , CAST(FM.LATE_DEPART_DT AS TIMESTAMP(0)) + (FM.LATE_DEPART_TM - TIME '00:00:00' HOUR TO SECOND(0)) AS LATE_DEPART_TS
    , CAST(FM.BEST_DEPART_DT AS TIMESTAMP(0)) + (FM.BEST_DEPART_TM - TIME '00:00:00' HOUR TO SECOND(0)) AS BEST_DEPART_TS
    , CAST(FM.DOCK_DT AS TIMESTAMP(0)) + (FM.DOCK_TM - TIME '00:00:00' HOUR TO SECOND(0)) AS DOCK_TS
    , CAST(FM.TRIP_CMPLT_DT AS TIMESTAMP(0)) + (FM.TRIP_CMPLT_TM - TIME '00:00:00' HOUR TO SECOND(0)) AS TRIP_CMPLT_TS

FROM NA_BI_VWS.TM_FRT_MVMNT_CURR FM

WHERE
    FM.EARLY_DEPART_DT >= DATE '2014-01-01'
    AND FM.FROM_TM_LOC_ID IN ('00903208', '00907821', '00901308', '00903905', '00903354', '00909405', '00904004')
    