SELECT
    *

--FROM NA_BI_VWS.TM_FRT_MVMNT_STA
FROM NA_BI_VWS.TM_SHIP_STA_CURR

WHERE
    BILL_LADING_ID = '6D312941424M'

/*ORDER BY
    FRT_MVMNT_STA_DT
    , FRT_MVMNT_STA_TM*/

SELECT
    BILL_LADING_ID
    , FRT_MVMNT_STOP_ID
    , CARR_SCAC_ID
    , OCCASION_TS
    , SRC_CRT_TS
    , SEQ_ID
    , SHIP_STA_CD
    , EVT_TXT
    , INT_STA_CD
    , INT_STA_DESC

FROM NA_BI_VWS.TM_SHIP_STA_CURR

WHERE
    BILL_LADING_ID = '6D312941424M'

ORDER BY
    SRC_CRT_TS
    , OCCASION_TS


SELECT
    *

FROM na_bi_vws.tm_carr_deliv_sta_curr
WHERE
    ship_bol = '6D312941424M'