SELECT
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    , OOL.SCHED_LINE_NBR
    
    , OD.PROD_ALLCT_DETERM_PROC_ID
    
    , CUST.OWN_CUST_ID
    , CUST.OWN_CUST_NAME
    , OD.SHIP_TO_CUST_ID
    , CUST.CUST_NAME AS SHIP_TO_CUST_NAME

    , CUST.DISTRICT_NAME
    , CUST.TERR_NAME
    , CUST.CITY_NAME
	, CUST.POSTAL_CD
    , CUST.CNTRY_NAME_CD
    
    , OD.FACILITY_ID
    , OD.SHIP_PT_ID
    
    , OD.MATL_ID
    , OD.BATCH_NBR
    , MATL.MATL_NO_8 || ' - ' || MATL.DESCR AS MATL_DESCR
    
    , OD.QTY_UNIT_MEAS_ID AS QTY_UOM
    , FD.ORDER_QTY
    , CASE
        WHEN OOL.OPEN_CNFRM_QTY > 0
            THEN 'OPEN CONFIRMED'
        WHEN OOL.UNCNFRM_QTY > 0
            THEN 'UNCONFIRMED'
        WHEN OOL.BACK_ORDER_QTY > 0
            THEN 'BACK ORDER'
        WHEN OOL.DEFER_QTY > 0
            THEN 'DEFER'
        WHEN OOL.WAIT_LIST_QTY > 0
            THEN 'WAIT LIST'
        END AS OPEN_STATUS
    , ZEROIFNULL(OOL.OPEN_CNFRM_QTY) + ZEROIFNULL(OOL.UNCNFRM_QTY) + ZEROIFNULL(OOL.BACK_ORDER_QTY) + ZEROIFNULL(OOL.DEFER_QTY) + ZEROIFNULL(OOL.WAIT_LIST_QTY) AS OPEN_QTY
    
    , CUST.SALES_ORG_CD
    , CUST.SALES_ORG_NAME

    , CUST.DISTR_CHAN_CD
    , CUST.DISTR_CHAN_NAME

    , CUST.CUST_GRP_ID
    , CUST.CUST_GRP_NAME
    
    , MATL.TIC_CD
    , MATL.MATL_PRTY
    , MATL.EXT_MATL_GRP_ID

    , MATL.PBU_NBR
    , MATL.PBU_NAME
    , MATL.MKT_CTGY_MKT_AREA_NBR AS CATEGORY_CD
    , MATL.MKT_CTGY_MKT_AREA_NAME AS CATEGORY_NM

    , MATL.MKT_CTGY_MKT_GRP_NBR AS SEGMENT_CD
    , MATL.MKT_CTGY_MKT_GRP_NAME AS SEGMENT_NM

    , MATL.MKT_CTGY_PROD_GRP_NBR AS SALES_PROD_GRP_CD
    , MATL.MKT_CTGY_PROD_GRP_NAME AS SALES_PROD_GRP_NM

    , MATL.MKT_CTGY_PROD_LINE_NBR AS SALES_PROD_LINE_CD
    , MATL.MKT_CTGY_PROD_LINE_NAME AS SALES_PROD_LINE_NM

    , OD.ORDER_DT
    , OD.ORDER_LN_CRT_DT

    , FD.PLN_MATL_AVL_DT AS MAD_FIRST_DATE
    , FD.PLN_GOODS_ISS_DT AS PGI_FIRST_DATE
    , FD.PLN_DELIV_DT AS PDD_FIRST_DATE

    , OD.PLN_MATL_AVL_DT
    , OD.PLN_GOODS_ISS_DT
    , OD.PLN_DELIV_DT

    , OD.CUST_RDD AS ORDD
    , OD.FRST_MATL_AVL_DT AS FRDD_FMAD
    , OD.FRST_PLN_GOODS_ISS_DT AS FRDD_FPGI
    , OD.FRST_RDD AS FRDD
    
    , OD.FC_MATL_AVL_DT AS FCDD_FMAD
    , OD.FC_PLN_GOODS_ISS_DT AS FCDD_FPGI
    , OD.FRST_PROM_DELIV_DT AS FCDD
    
    , OD.FNL_ACCEPT_DT AS FAD

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID
    , OD.ITEM_CAT_ID
    
    , OD.ORDER_CREATOR
    , OD.SHIP_COND_ID
    , OD.DELIV_PRTY_ID
    , OD.ROUTE_ID
    , OD.DELIV_GRP_CD
    , OD.SPCL_PROC_ID
    , OD.CUST_GRP2_CD

FROM NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND OD.ORDER_ID = OOL.ORDER_ID
        AND OD.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = OOL.SCHED_LINE_NBR
        AND OD.EXP_DT = DATE '5555-12-31'
        AND OD.PROD_ALLCT_DETERM_PROC_ID > ''
        AND OD.REJ_REAS_ID = ''

    INNER JOIN NA_BI_VWS.ORDER_DETAIL FD
        ON FD.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND FD.ORDER_ID = OOL.ORDER_ID
        AND FD.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND FD.SCHED_LINE_NBR = 1
        AND FD.EXP_DT = DATE '5555-12-31'
        AND FD.PROD_ALLCT_DETERM_PROC_ID > ''
        AND FD.REJ_REAS_ID = ''

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR MATL
        ON MATL.MATL_ID = OD.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR CUST
        ON CUST.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

WHERE
    OOL.IN_PROC_QTY = 0
    AND OPEN_QTY > 0

ORDER BY
    OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    , OOL.SCHED_LINE_NBR
    