SELECT
    R.ORDER_FISCAL_YR
    , R.ORDER_ID
    , R.ORDER_LINE_NBR
    , R.SCHED_LINE_NBR

    , R.PRIOR_DY_RESCHD_DT
    , R.RESCHD_DT
    , R.RESCHD_TM

    , R.ORDER_TYPE_ID
    , R.AVAIL_CHK_GRP_CD
    , R.DOC_TYP_CD
    , R.TRANS_UPD_CD
    , R.SRC_UPD_USR_ID

    , R.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    
    , R.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.MKT_GRP_NBR
    , M.MKT_GRP_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME

    , R.RESCHD_IND
    , R.DELIV_DT_CHG_CD
    , R.PLN_DELIV_DT
    , R.RESCHD_DELIV_DT
    , R.DELIV_DT_VAR_QTY
    , R.CNFRM_QTY_CHG_CD
    , R.CNFRM_QTY
    , R.RESCHD_CNFRM_QTY
    , R.CNFRM_VAR_QTY

    , R.PLN_MATL_AVAIL_DT
    , R.RESCHD_MATL_AVAIL_DT
    , R.MATL_AVAIL_DT_VAR_QTY

FROM NA_BI_vWS.ORD_RESCHD R

    INNER JOIN NA_BI_vWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = R.ORDER_FISCAL_YR
        AND OD.ORDER_ID = R.ORDER_ID
        AND OD.ORDER_LINE_NBR = R.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = 1
        AND OD.EXP_DT = CAST('5555-12-31' AS DATE)

    INNER JOIN GDYR_BI_vWS.NAT_CUST_HIER_DESCR_EN_cURR C
        ON C.SHIP_TO_CUST_ID = R.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = R.MATL_ID

WHERE
    R.PRIOR_DY_RESCHD_DT BETWEEN DATE '2015-07-01' AND CURRENT_DATE-1
    AND R.MATL_ID IN ('000000000000204189', '000000000000218254', '000000000000061902')

ORDER BY
    R.ORDER_FISCAL_YR
    , R.ORDER_ID
    , R.ORDER_LINE_NBR
    , R.SCHED_LINE_NBR
    , R.PRIOR_DY_RESCHD_DT