SELECT
    Q.VARIANT_NM
    , Q.SCHD_DT
    , Q.SCHD_HR
    , Q.MIN_JOB_START_TS
    , Q.MAX_JOB_END_TS
    , Q.JOB_DUR_INTERVAL_SEC
    , COUNT(DISTINCT Q.EXEC_ACTL_SRVR_NM) AS UNIQUE_ACTL_SRVR_CNT
    , COUNT(Q.EXEC_ACTL_SRVR_NM) AS TOT_ACTL_SRVR_CNT

FROM (

SELECT
    BSO.PGM_NM
    , BSO.VAR_NM
    
    , CASE COALESCE(VD.VAR_NM, SUBSTR(BO.BACKGRND_JOB_NM, 16))
        WHEN 'N6DEF' THEN 'N6DE_F'
        ELSE COALESCE(VD.VAR_NM, SUBSTR(BO.BACKGRND_JOB_NM, 16))
        END AS VARIANT_NM

    , CASE
        WHEN BSO.PGM_NM = '/BTR/MDR_INTERVAL_PROCESSING'
            THEN 'C'
        ELSE 'P'
        END AS PROCESS_TYP

    , BO.BACKGRND_JOB_NM
    , BO.BACKGRND_JOB_ID
    , BO.BACKGRND_JOB_STEP_ID

    , BO.EXEC_TGT_SRVR_NM
    , BO.EXEC_ACTL_SRVR_NM

    , BO.SCHD_DT
    , BO.SCHD_TM
    , EXTRACT(HOUR FROM BO.SCHD_TM) AS SCHD_HR
    , CAST(BO.SCHD_DT AS TIMESTAMP(0)) + (BO.SCHD_TM - TIME '00:00:00' HOUR TO SECOND) AS SCHD_TS

    , BO.JOB_START_DT
    , BO.JOB_START_TM
    , BO.JOB_START_TS
    , MIN(BO.JOB_START_TS) OVER (PARTITION BY VARIANT_NM, BO.SCHD_DT, SCHD_HR) AS MIN_JOB_START_TS

    , BO.JOB_END_DT
    , BO.JOB_END_TM
    , BO.JOB_END_TS
    , MAX(BO.JOB_END_TS) OVER (PARTITION BY VARIANT_NM, BO.SCHD_DT, SCHD_HR) AS MAX_JOB_END_TS

    , BO.JOB_DUR_TM_IN_SS_QTY
    , (MAX_JOB_END_TS - MIN_JOB_START_TS DAY(4) TO SECOND) AS JOB_DUR_INTERVAL
    , CAST((60 * ((60 * ((EXTRACT(DAY FROM JOB_DUR_INTERVAL) * 24) + EXTRACT(HOUR FROM JOB_DUR_INTERVAL))) + EXTRACT(MINUTE FROM JOB_DUR_INTERVAL))) + EXTRACT(SECOND FROM JOB_DUR_INTERVAL) AS INTEGER) AS JOB_DUR_INTERVAL_SEC

    , BO.BACKGRND_JOB_STA_CD
    , BSO.BACKGRND_JOB_STEP_STA_CD
    , BO.NEW_JOB_ID_CRT_CD
    , BO.AUTH_BACKGRND_USR_ID

    , BO.JOB_SCHDLR_USR_ID
    , BO.LST_JOB_CHG_DT
    , BO.LST_JOB_CHG_TM
    , BO.LST_JOB_CHG_USR_ID

    , VD.SRC_CRT_USR_ID AS VAR_CRT_USR_ID
    , CAST(VD.SRC_CRT_DT AS TIMESTAMP(0)) + (VD.SRC_CRT_TM - TIME '00:00:00' HOUR TO SECOND) AS VAR_CRT_TS
    , VD.SRC_UPD_USR_ID AS VAR_UPD_USR_ID
    , CAST(VD.SRC_UPD_DT AS TIMESTAMP(0)) + (VD.SRC_UPD_TM - TIME '00:00:00' HOUR TO SECOND) AS VAR_UPD_TS

FROM NA_BI_VWS.BACKGRND_JOB_OVRVW_CURR BO

    INNER JOIN NA_BI_VWS.BACKGRND_JOB_STEP_OVRVW_CURR BSO
        ON BSO.BACKGRND_JOB_ID = BO.BACKGRND_JOB_ID
        AND BSO.BACKGRND_JOB_NM = BO.BACKGRND_JOB_NM
        AND BSO.BACKGRND_JOB_STEP_ID = BO.BACKGRND_JOB_STEP_ID

    LEFT OUTER JOIN NA_BI_vWS.VAR_DIR VD
        ON VD.PGM_NM = BSO.PGM_NM
        AND VD.VAR_NM = BSO.VAR_NM
        AND BO.SCHD_DT BETWEEN VD.EFF_DT AND VD.EXP_DT

WHERE
    BO.JOB_START_DT IS NOT NULL
    AND BO.BACKGRND_JOB_NM LIKE '%YSDV03V02%'
    AND BO.SCHD_DT >= CAST('2015-01-01' AS DATE)

/*ORDER BY
    SCHD_TS
    , BO.BACKGRND_JOB_NM
    , BO.BACKGRND_JOB_ID
    , BO.BACKGRND_JOB_STEP_ID*/

    ) Q

GROUP BY
    Q.VARIANT_NM
    , Q.SCHD_DT
    , Q.SCHD_HR
    , Q.MIN_JOB_START_TS
    , Q.MAX_JOB_END_TS
    , Q.JOB_DUR_INTERVAL_SEC
