SELECT
    'Operations' AS QRY_SOURCE
    , RS.FACILITY_ID
    , COUNT(*) AS RSCHD_CNT

FROM (

SELECT
    R.ORDER_FISCAL_YR
    , R.ORDER_ID
    , R.ORDER_LINE_NBR
    , R.SCHED_LINE_NBR

    , R.RESCHD_IND
    , R.AVAIL_CHK_GRP_CD
    , R.ORDER_TYPE_ID
    , R.DOC_TYP_CD
    , R.TRANS_UPD_CD
    , R.SRC_UPD_USR_ID

    , R.PRIOR_DY_RESCHD_DT
    , R.RESCHD_DT
    , R.RESCHD_TM

    , R.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , R.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    
    , SDI.FACILITY_ID

    , R.DELIV_DT_CHG_CD
    , R.PLN_MATL_AVAIL_DT
    , R.RESCHD_MATL_AVAIL_DT
    , R.MATL_AVAIL_DT_VAR_QTY
    , R.PLN_DELIV_DT
    , R.RESCHD_DELIV_DT
    , R.DELIV_DT_VAR_QTY

    , R.CNFRM_QTY_CHG_CD
    , R.CNFRM_QTY
    , R.RESCHD_CNFRM_QTY
    , R.CNFRM_VAR_QTY

FROM NA_BI_VWS.ORD_RESCHD R

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = R.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = R.SHIP_TO_CUST_ID
        AND C.CUST_GRP_ID <> '3R'
        AND C.OWN_CUST_ID <> '00A0005538' --COWD

    INNER JOIN GDYR_VWS.SLS_DOC SD
        ON SD.FISCAL_YR = R.ORDER_FISCAL_YR
        AND SD.SLS_DOC_ID = R.ORDER_ID
        AND SD.ORIG_SYS_ID = R.ORIG_SYS_ID
        AND SD.EXP_DT = CAST('5555-12-31' AS DATE)
        AND SD.CO_CD IN ('N101', 'N102', 'N266')
        AND SD.SD_DOC_CTGY_CD = 'C'
        AND SD.CUST_PRCH_ORD_TYP_CD <> 'RO'

    INNER JOIN GDYR_VWS.SLS_DOC_ITM SDI
        ON SDI.FISCAL_YR = R.ORDER_FISCAL_YR
        AND SDI.SLS_DOC_ID = R.ORDER_ID
        AND SDI.SLS_DOC_ITM_ID = R.ORDER_LINE_NBR
        AND SDI.ORIG_SYS_ID = R.ORIG_SYS_ID
        AND SDI.EXP_DT = CAST('5555-12-31' AS DATE)

WHERE
    R.PBU_NBR IN ('01', '03')
    AND R.RESCHD_DT = CAST('2015-03-17' AS DATE)
    AND R.DOC_TYP_CD = 'O'
    AND R.TRANS_UPD_CD = 'R'
    AND (CASE WHEN C.OWN_CUST_ID = '00A0000632' AND SUBSTR(SD.CUST_PRCH_ORD_ID,5,2)<>'62' THEN 0 ELSE 1 END) = 1 --SAMS KIOSK

    ) RS

WHERE
    RS.FACILITY_ID IN ('N636', 'N637')

GROUP BY
    RS.FACILITY_ID

UNION ALL

SELECT
    'Simulation' AS QRY_SOURCE
    , RS.FACILITY_ID
    , COUNT(*) AS RSCHD_CNT

FROM (

SELECT
    R.ORDER_FISCAL_YR
    , R.ORDER_ID
    , R.ORDER_LINE_NBR
    , R.SCHED_LINE_NBR

    , R.RESCHD_IND
    , R.AVAIL_CHK_GRP_CD
    , R.ORDER_TYPE_ID
    , R.DOC_TYP_CD
    , R.TRANS_UPD_CD
    , R.SRC_UPD_USR_ID

    , R.PRIOR_DY_RESCHD_DT
    , R.RESCHD_DT
    , R.RESCHD_TM

    , R.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , R.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME

    , SDI.FACILITY_ID

    , R.DELIV_DT_CHG_CD
    , R.PLN_MATL_AVAIL_DT
    , R.RESCHD_MATL_AVAIL_DT
    , R.MATL_AVAIL_DT_VAR_QTY
    , R.PLN_DELIV_DT
    , R.RESCHD_DELIV_DT
    , R.DELIV_DT_VAR_QTY

    , R.CNFRM_QTY_CHG_CD
    , R.CNFRM_QTY
    , R.RESCHD_CNFRM_QTY
    , R.CNFRM_VAR_QTY

FROM SUPP_EDW.ORD_RESCHD R

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = R.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = R.SHIP_TO_CUST_ID
        AND C.CUST_GRP_ID <> '3R'
        AND C.OWN_CUST_ID <> '00A0005538' --COWD

    INNER JOIN GDYR_VWS.SLS_DOC SD
        ON SD.FISCAL_YR = R.ORDER_FISCAL_YR
        AND SD.SLS_DOC_ID = R.ORDER_ID
        AND SD.ORIG_SYS_ID = R.ORIG_SYS_ID
        AND SD.EXP_DT = CAST('5555-12-31' AS DATE)
        AND SD.CO_CD IN ('N101', 'N102', 'N266')
        AND SD.SD_DOC_CTGY_CD = 'C'
        AND SD.CUST_PRCH_ORD_TYP_CD <> 'RO'

    INNER JOIN GDYR_VWS.SLS_DOC_ITM SDI
        ON SDI.FISCAL_YR = R.ORDER_FISCAL_YR
        AND SDI.SLS_DOC_ID = R.ORDER_ID
        AND SDI.SLS_DOC_ITM_ID = R.ORDER_LINE_NBR
        AND SDI.ORIG_SYS_ID = R.ORIG_SYS_ID
        AND SDI.EXP_DT = CAST('5555-12-31' AS DATE)

WHERE
    R.PBU_NBR IN ('01', '03')
    AND R.RESCHD_DT = CAST('2015-03-17' AS DATE)
    AND R.DOC_TYP_CD = 'O'
    AND R.TRANS_UPD_CD = 'R'
    AND (CASE WHEN C.OWN_CUST_ID = '00A0000632' AND SUBSTR(SD.CUST_PRCH_ORD_ID,5,2)<>'62' THEN 0 ELSE 1 END) = 1 --SAMS KIOSK
    AND SUBSTR(R.EDW_JOB_ID,10,2) = '00'

    ) RS

WHERE
    RS.FACILITY_ID IN ('N636', 'N637')

GROUP BY
    RS.FACILITY_ID

