SELECT
    OO.DAY_DATE
    , OO.MONTH_DT
    , OO.END_OF_MONTH_DT
    , OO.AT_RISK_IND
    , CAST(OO.AT_RISK_IND AS FORMAT '-9(2)') || ' - ' || OO.AT_RISK_DESC AS AT_RISK_DESC

    , OO.OWN_CUST_ID
    , OO.OWN_CUST_NAME
    , OO.SALES_ORG_CD
    , OO.SALES_ORG_NAME
    , OO.DISTR_CHAN_CD
    , OO.DISTR_CHAN_NAME
    , OO.CUST_GRP_ID
    , OO.CUST_GRP_NAME
    , OO.OE_REPL_IND

    --, OO.MATL_ID
    --, OO.MATL_DESCR
    , OO.PBU_NBR
    , OO.PBU_NAME
    , OO.MKT_AREA_NBR
    , OO.MKT_AREA_NAME
    , OO.MKT_CTGY_MKT_AREA_NBR
    , OO.MKT_CTGY_MKT_AREA_NAME
    , NULL AS PROD_LINE_NBR
    , NULL AS PROD_LINE_NAME

    , OO.TEST_PRIM_SHIP_FACILITY_ID
    --, OO.PRIM_SHIP_FACILITY_ID
    , OO.FACILITY_ID
    , OO.FACILITY_NAME

    , OO.SLS_QTY_UNIT_MEAS_ID
    , SUM(OO.OPEN_CNFRM_QTY) AS OPEN_CNFRM_QTY

FROM (

SELECT
    CAL.DAY_DATE
    , CAL.MONTH_DT
    , ADD_MONTHS(CAL.MONTH_DT, 1) - INTERVAL '1' DAY AS END_OF_MONTH_DT

    , OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    , OOL.SCHED_LINE_NBR

    , CAST(CASE
        WHEN OD.ORDER_DELIV_BLK_CD > '' OR SCHD_LN_DELIV_BLK_CD > ''
            THEN 99
        WHEN OD.SHIP_COND_ID IN ('00', 'LW') AND OE_REPL_IND = 'Replacement'
            THEN 10
        WHEN OD.CUST_GRP2_CD IN ('MAN') AND OE_REPL_IND = 'Replacement'
            THEN 5
        ELSE 0
        END AS SMALLINT) AS AT_RISK_IND

    , CASE
        WHEN AT_RISK_IND = 99
            THEN 'High Risk - Delivery / Credit Block Present'
        WHEN AT_RISK_IND = 10
            THEN 'Medium Risk - Will-Call'
        WHEN AT_RISK_IND = 5
            THEN 'Medium Risk - Manual Release'
        WHEN AT_RISK_IND = 0
            THEN 'Low Risk'
        ELSE 'Undefined Description'
        END AS AT_RISK_DESC

    , OD.CUST_PO_NBR
    , OD.PO_TYPE_ID

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID

    , OD.ORDER_DELIV_BLK_CD
    , OD.DELIV_BLK_CD AS SCHD_LN_DELIV_BLK_CD

    , OD.SHIP_COND_ID
    , OD.SPCL_PROC_ID
    , OD.PROD_ALLCT_DETERM_PROC_ID
    , OD.CUST_GRP2_CD
    , OD.SHIP_TO_CUST_ID

    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME
    , CASE 
        WHEN C.SALES_ORG_CD IN ('N302', 'N312', 'N322') OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD = '32')
            THEN 'OE'
        ELSE 'Replacement'
        END OE_REPL_IND

    , OD.MATL_ID
    , M.MATL_NO_8 || ' - ' || M.DESCR AS MATL_DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME

    , CASE
        WHEN OD.FACILITY_ID IN ('N5US', 'N5CA')
            THEN 'N5US / N5CA'
        WHEN OD.FACILITY_ID = C.PRIM_SHIP_FACILITY_ID
            THEN 'Primary LC'
        WHEN OD.FACILITY_ID LIKE 'N5%'
            THEN 'Factory Direct'
        ELSE 'Out of Area'
        END AS TEST_PRIM_SHIP_FACILITY_ID
    , C.PRIM_SHIP_FACILITY_ID
    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , OOL.SLS_QTY_UNIT_MEAS_ID
    , OOL.OPEN_CNFRM_QTY

    , OD.FRST_MATL_AVL_DT
    , OD.FRST_PLN_GOODS_ISS_DT
    , OD.FRST_RDD
    , OD.FC_MATL_AVL_DT
    , OD.FC_PLN_GOODS_ISS_DT
    , OD.FRST_PROM_DELIV_DT

FROM GDYR_BI_VWS.GDYR_CAL CAL

    INNER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN OOL
        ON CAL.DAY_DATE BETWEEN OOL.EFF_DT AND OOL.EXP_DT
        AND OOL.OPEN_CNFRM_QTY > 0

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND OD.ORDER_ID = OOL.ORDER_ID
        AND OD.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = OOL.SCHED_LINE_NBR
        AND CAL.DAY_DATE BETWEEN OD.EFF_DT AND OD.EXP_DT
        AND OD.PO_TYPE_ID <> 'RO'
        AND OD.PLN_GOODS_ISS_DT BETWEEN CAL.MONTH_DT AND END_OF_MONTH_DT

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        --AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        --AND F.DISTR_CHAN_CD = '81'

WHERE
    CAL.DAY_DATE BETWEEN ADD_MONTHS(CURRENT_DATE-1, -1) - (EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE-1, -1))-1) AND CURRENT_DATE-1
    AND M.PBU_NBR = '01'
    AND OE_REPL_IND = 'Replacement'

    ) OO

GROUP BY
    OO.DAY_DATE
    , OO.MONTH_DT
    , OO.END_OF_MONTH_DT
    , OO.AT_RISK_IND
    , OO.AT_RISK_DESC

    , OO.OWN_CUST_ID
    , OO.OWN_CUST_NAME
    , OO.SALES_ORG_CD
    , OO.SALES_ORG_NAME
    , OO.DISTR_CHAN_CD
    , OO.DISTR_CHAN_NAME
    , OO.CUST_GRP_ID
    , OO.CUST_GRP_NAME
    , OO.OE_REPL_IND

    --, OO.MATL_ID
    --, OO.MATL_DESCR
    , OO.PBU_NBR
    , OO.PBU_NAME
    , OO.MKT_AREA_NBR
    , OO.MKT_AREA_NAME
    , OO.MKT_CTGY_MKT_AREA_NBR
    , OO.MKT_CTGY_MKT_AREA_NAME
    --, OO.PROD_LINE_NBR
    --, OO.PROD_LINE_NAME

    , OO.TEST_PRIM_SHIP_FACILITY_ID
    --, OO.PRIM_SHIP_FACILITY_ID
    , OO.FACILITY_ID
    , OO.FACILITY_NAME

    , OO.SLS_QTY_UNIT_MEAS_ID

ORDER BY
    OO.DAY_DATE
    , OO.AT_RISK_IND
    , OO.PBU_NBR
    , OO.FACILITY_ID
    , OO.OE_REPL_IND
    , OO.OWN_CUST_ID
