SELECT
    Q.DAY_DATE
    , Q.WEEK_OF_MONTH

    , Q.ORDER_TYPE_ID
    , Q.PO_TYPE_ID

    , Q.AT_RISK_IND
    , Q.AT_RISK_DESC

    , Q.ORDER_DELIV_BLK_CD
    , Q.SCHD_LN_DELIV_BLK_CD

    , Q.SHIP_COND_ID
    , Q.SNAP_SPCL_PROC_ID
    , Q.PROD_ALLCT_DETERM_PROC_ID
    , Q.CUST_GRP2_CD

    --, Q.SHIP_TO_CUST_ID
    --, Q.CUST_NAME
    , Q.OWN_CUST_ID
    , Q.OWN_CUST_NAME

    --, Q.REJ_REAS_ID
    --, Q.REJ_REAS_DESC
    --, Q.CANCEL_DT

    --, Q.MATL_ID
    --, Q.MATL_DESCR
    , Q.PBU_NBR
    , Q.PBU_NAME
    , Q.MKT_AREA_NBR
    , Q.MKT_AREA_NAME
    , Q.MKT_CTGY_MKT_AREA_NBR
    , Q.MKT_CTGY_MKT_AREA_NAME
    --, Q.PROD_LINE_NBR
    --, Q.PROD_LINE_NAME

    , Q.TEST_PRIM_SHIP_FACILITY_ID
    --, OOD.PRIM_SHIP_FACILITY_ID
    , Q.FACILITY_ID
    , Q.FACILITY_NAME

    , Q.SLS_QTY_UNIT_MEAS_ID
    , SUM(Q.SL_OPEN_CNFRM_QTY) AS SNAP_OPEN_CNFRM_QTY

    , SUM(Q.CURR_OPEN_CNFRM_QTY) AS CURR_OPEN_CNFRM_QTY
    , SUM(Q.CURR_UNCNFRM_QTY) AS CURR_UNCNFRM_QTY
    , SUM(Q.CURR_BACK_ORDER_QTY) AS CURR_BACK_ORDER_QTY
    , SUM(Q.CURR_WAIT_LIST_QTY) AS CURR_WAIT_LIST_QTY
    , SUM(Q.CURR_OPEN_CNFRM_QTY) AS CURR_OPEN_CNFRM_QTY

    , SUM(Q.AGID_BEFORE_SNAP_DT_QTY) AS AGID_BEFORE_SNAP_DT_QTY
    , SUM(Q.AGID_BW_SNAP_AND_EOM_QTY) AS AGID_BW_SNAP_AND_EOM_QTY
    , SUM(Q.AGID_AFTER_MONTH_QTY) AS AGID_AFTER_MONTH_QTY

    , SUM(Q.PGMV_BEFORE_SNAP_DT_QTY) AS PGMV_BEFORE_SNAP_DT_QTY
    , SUM(Q.PGMV_BW_SNAP_AND_EOM_QTY) AS PGMV_BW_SNAP_AND_EOM_QTY
    , SUM(Q.PGMV_AFTER_MONTH_QTY) AS PGMV_AFTER_MONTH_QTY

    , SUM(CASE
        WHEN Q.REJ_REAS_ID > '' AND Q.SL_OPEN_CNFRM_QTY - Q.TOT_DELIV_QTY > 0
            THEN Q.SL_OPEN_CNFRM_QTY - Q.TOT_DELIV_QTY
        ELSE 0
        END) AS NET_CANCEL_QTY

    , Q.AGID_TYP_CD
    , Q.AGID_TYP_DESCR

FROM (

SELECT
    OOD.DAY_DATE
    , OOD.WEEK_OF_MONTH
    , OOD.MONTH_DT
    , OOD.END_OF_MONTH_DT

    , OOD.ORDER_FISCAL_YR
    , OOD.ORDER_ID
    , OOD.ORDER_LINE_NBR

    , OOD.AT_RISK_IND
    , OOD.AT_RISK_DESC

    --, OOD.CUST_PO_NBR
    , OOD.PO_TYPE_ID

    , OOD.ORDER_CAT_ID
    , OOD.ORDER_TYPE_ID

    , OOD.ORDER_DELIV_BLK_CD
    , OOD.SCHD_LN_DELIV_BLK_CD

    , OOD.SHIP_COND_ID
    , OOD.SPCL_PROC_ID AS SNAP_SPCL_PROC_ID
    --, ODS.SPCL_PROC_ID AS CURR_SPCL_PROC_ID
    , OOD.PROD_ALLCT_DETERM_PROC_ID
    , OOD.CUST_GRP2_CD

    , OOD.SHIP_TO_CUST_ID
    , OOD.CUST_NAME
    , OOD.OWN_CUST_ID
    , OOD.OWN_CUST_NAME

    , OOD.SALES_ORG_CD
    , OOD.SALES_ORG_NAME
    , OOD.DISTR_CHAN_CD
    , OOD.DISTR_CHAN_NAME
    , OOD.CUST_GRP_ID
    , OOD.CUST_GRP_NAME
    , OOD.OE_REPL_IND

    , ODS.REJ_REAS_ID
    , ODS.REJ_REAS_DESC
    , ODS.CANCEL_DT

    , OOD.MATL_ID
    , OOD.MATL_DESCR
    , OOD.PBU_NBR
    , OOD.PBU_NAME
    , OOD.MKT_AREA_NBR
    , OOD.MKT_AREA_NAME
    , OOD.MKT_CTGY_MKT_AREA_NBR
    , OOD.MKT_CTGY_MKT_AREA_NAME
    , OOD.PROD_LINE_NBR
    , OOD.PROD_LINE_NAME

    , OOD.TEST_PRIM_SHIP_FACILITY_ID
    --, OOD.PRIM_SHIP_FACILITY_ID
    , OOD.FACILITY_ID
    , OOD.FACILITY_NAME

    , OOD.SLS_QTY_UNIT_MEAS_ID
    , SUM(OOD.SL_OPEN_CNFRM_QTY) AS SL_OPEN_CNFRM_QTY

    , ZEROIFNULL(OOL.OPEN_CNFRM_QTY) AS CURR_OPEN_CNFRM_QTY
    , ZEROIFNULL(OOL.UNCNFRM_QTY) AS CURR_UNCNFRM_QTY
    , ZEROIFNULL(OOL.BACK_ORDER_QTY) AS CURR_BACK_ORDER_QTY
    , ZEROIFNULL(OOL.WAIT_LIST_QTY) AS CURR_WAIT_LIST_QTY

    , ZEROIFNULL(SUM(D.DELIV_QTY)) AS TOT_DELIV_QTY

    , ZEROIFNULL(SUM(CASE
        WHEN D.ACTL_GOODS_ISS_DT <= OOD.DAY_DATE
            THEN D.DELIV_QTY
        ELSE 0
        END)) AS AGID_BEFORE_SNAP_DT_QTY
    , ZEROIFNULL(SUM(CASE
        WHEN D.ACTL_GOODS_ISS_DT BETWEEN OOD.DAY_DATE AND OOD.END_OF_MONTH_DT
            THEN D.DELIV_QTY
        ELSE 0
        END)) AS AGID_BW_SNAP_AND_EOM_QTY
    , ZEROIFNULL(SUM(CASE
        WHEN D.ACTL_GOODS_ISS_DT > OOD.END_OF_MONTH_DT
            THEN D.DELIV_QTY
        ELSE 0
        END)) AS AGID_AFTER_MONTH_QTY

    , ZEROIFNULL(SUM(CASE
        WHEN D.ACTL_GOODS_ISS_DT IS NULL AND D.PLN_GOODS_MVT_DT <= OOD.DAY_DATE
            THEN D.DELIV_QTY
        ELSE 0
        END)) AS PGMV_BEFORE_SNAP_DT_QTY
    , ZEROIFNULL(SUM(CASE
        WHEN D.ACTL_GOODS_ISS_DT IS NULL AND D.PLN_GOODS_MVT_DT BETWEEN OOD.DAY_DATE + CAST(1 AS INTERVAL DAY) AND OOD.END_OF_MONTH_DT
            THEN D.DELIV_QTY
        ELSE 0
        END)) AS PGMV_BW_SNAP_AND_EOM_QTY
    , ZEROIFNULL(SUM(CASE
        WHEN D.ACTL_GOODS_ISS_DT IS NULL AND D.PLN_GOODS_MVT_DT > OOD.END_OF_MONTH_DT
            THEN D.DELIV_QTY
        ELSE 0
        END)) AS PGMV_AFTER_MONTH_QTY

    , CASE
        WHEN (AGID_BW_SNAP_AND_EOM_QTY + PGMV_BW_SNAP_AND_EOM_QTY) >= SUM(OOD.SL_OPEN_CNFRM_QTY)
            THEN 0
        WHEN SUM(OOD.SL_OPEN_CNFRM_QTY) <= ZEROIFNULL(OOL.OPEN_CNFRM_QTY)
            THEN 5
        WHEN (AGID_BW_SNAP_AND_EOM_QTY + PGMV_BW_SNAP_AND_EOM_QTY) BETWEEN 1 AND SUM(OOD.SL_OPEN_CNFRM_QTY)
            THEN 10
        WHEN (AGID_AFTER_MONTH_QTY + PGMV_AFTER_MONTH_QTY) BETWEEN 1 AND SUM(OOD.SL_OPEN_CNFRM_QTY)
            THEN 20
        WHEN ZEROIFNULL(SUM(D.DELIV_QTY)) < SUM(OOD.SL_OPEN_CNFRM_QTY)
            THEN 90
        WHEN ODS.REJ_REAS_ID > ''
            THEN 95
        ELSE 99
        END AS AGID_TYP_CD

    , CAST(AGID_TYP_CD AS FORMAT '-9(2)') || ' - ' || CASE AGID_TYP_CD
        WHEN 0 THEN 'All Open Cnfrm Qty Plan/Actual GI In Month'
        WHEN 5 THEN 'Current Open Qty >= Snapshot Open Qty'
        WHEN 10 THEN 'Some Open Cnfrm Qty Plan/Actual GI in Month'
        WHEN 20 THEN 'Plan/Actual GI After Snapshot PGI Month'
        WHEN 90 THEN 'Current DN Qty < Snapshot Open Cnfrm Qty'
        WHEN 95 THEN 'Cancelled'
        WHEN 99 THEN 'Undefined'
        ELSE 'No Description'
        END AS AGID_TYP_DESCR

FROM (

SELECT
    CAL.DAY_DATE
    , CAL.WEEK_OF_MONTH
    , CAL.MONTH_DT
    , ADD_MONTHS(CAL.MONTH_DT, 1) - INTERVAL '1' DAY AS END_OF_MONTH_DT

    , OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    --, OOL.SCHED_LINE_NBR

    , CAST(CASE
        WHEN OD.ORDER_DELIV_BLK_CD > '' OR SCHD_LN_DELIV_BLK_CD > ''
            THEN 99
        WHEN OD.SHIP_COND_ID IN ('00', 'LW') AND OE_REPL_IND = 'Replacement'
            THEN 95
        WHEN OD.CUST_GRP2_CD IN ('MAN') AND OE_REPL_IND = 'Replacement'
            THEN 10
        ELSE 0
        END AS INTEGER) AS AT_RISK_IND

    , CAST(AT_RISK_IND AS FORMAT '-9(2)') || ' - ' || CASE AT_RISK_IND
        WHEN 99 THEN 'Risk - Delivery / Credit Block Present'
        WHEN 95 THEN 'Risk - Will-Call'
        WHEN 10 THEN 'Risk - Manual Release'
        WHEN 0 THEN 'Expected to GI In Month'
        ELSE 'Undefined Description'
        END AS AT_RISK_DESC

    , OD.CUST_PO_NBR
    , OD.PO_TYPE_ID

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID

    , OD.ORDER_DELIV_BLK_CD
    , MAX(OD.DELIV_BLK_CD) AS SCHD_LN_DELIV_BLK_CD

    , OD.SHIP_COND_ID
    , OD.SPCL_PROC_ID
    , OD.PROD_ALLCT_DETERM_PROC_ID
    , OD.CUST_GRP2_CD

    , OD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME
    , CASE 
        WHEN C.SALES_ORG_CD IN ('N302', 'N312', 'N322') OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD = '32')
            THEN 'OE'
        ELSE 'Replacement'
        END OE_REPL_IND

    , OD.MATL_ID
    , M.MATL_NO_8 || ' - ' || M.DESCR AS MATL_DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME

    , CASE
        WHEN OD.FACILITY_ID IN ('N5US', 'N5CA')
            THEN 'N5US / N5CA'
        WHEN OD.FACILITY_ID = C.PRIM_SHIP_FACILITY_ID
            THEN 'Primary LC'
        WHEN OD.FACILITY_ID LIKE 'N5%'
            THEN 'Factory Direct'
        ELSE 'Out of Area'
        END AS TEST_PRIM_SHIP_FACILITY_ID
    , C.PRIM_SHIP_FACILITY_ID
    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , OOL.SLS_QTY_UNIT_MEAS_ID
    , SUM(OOL.OPEN_CNFRM_QTY) AS SL_OPEN_CNFRM_QTY

FROM GDYR_BI_VWS.GDYR_CAL CAL

    INNER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN OOL
        ON CAL.DAY_DATE BETWEEN OOL.EFF_DT AND OOL.EXP_DT
        AND OOL.OPEN_CNFRM_QTY > 0

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND OD.ORDER_ID = OOL.ORDER_ID
        AND OD.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = OOL.SCHED_LINE_NBR
        AND CAL.DAY_DATE BETWEEN OD.EFF_DT AND OD.EXP_DT
        AND OD.PO_TYPE_ID <> 'RO'
        AND OD.PLN_GOODS_ISS_DT <= END_OF_MONTH_DT

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        --AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        --AND F.DISTR_CHAN_CD = '81'

WHERE
    CAL.DAY_DATE BETWEEN DATE '2015-02-01' AND CURRENT_DATE-1
    AND M.PBU_NBR = '01'
    AND OE_REPL_IND = 'Replacement'

GROUP BY
    CAL.DAY_DATE
    , CAL.WEEK_OF_MONTH
    , CAL.MONTH_DT
    , END_OF_MONTH_DT

    , OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    --, OOL.SCHED_LINE_NBR

    --, AT_RISK_IND
    --, AT_RISK_DESC

    , OD.CUST_PO_NBR
    , OD.PO_TYPE_ID

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID

    , OD.ORDER_DELIV_BLK_CD
    --, MAX(OD.DELIV_BLK_CD) AS SCHD_LN_DELIV_BLK_CD

    , OD.SHIP_COND_ID
    , OD.SPCL_PROC_ID
    , OD.PROD_ALLCT_DETERM_PROC_ID
    , OD.CUST_GRP2_CD
    , OD.SHIP_TO_CUST_ID

    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME
    , OE_REPL_IND

    , OD.MATL_ID
    , MATL_DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME

    , TEST_PRIM_SHIP_FACILITY_ID
    , C.PRIM_SHIP_FACILITY_ID
    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , OOL.SLS_QTY_UNIT_MEAS_ID
    --, SUM(OOL.OPEN_CNFRM_QTY) AS SL_OPEN_CNFRM_QTY

    ) OOD

    INNER JOIN NA_BI_VWS.ORD_DTL_SMRY ODS
        ON ODS.ORDER_FISCAL_YR = OOD.ORDER_FISCAL_YR
        AND ODS.ORDER_ID = OOD.ORDER_ID
        AND ODS.ORDER_LINE_NBR = OOD.ORDER_LINE_NBR
        AND ODS.ORDER_CAT_ID = 'C'
        AND ODS.RO_PO_TYPE_IND = 'N'

    LEFT OUTER JOIN NA_BI_VWS.OPEN_ORDER_ORDLN_CURR OOL
        ON OOL.ORDER_FISCAL_YR = OOD.ORDER_FISCAL_YR
        AND OOL.ORDER_ID = OOD.ORDER_ID
        AND OOL.ORDER_LINE_NBR = OOD.ORDER_LINE_NBR

GROUP BY
    OOD.DAY_DATE
    , OOD.WEEK_OF_MONTH
    , OOD.MONTH_DT
    , OOD.END_OF_MONTH_DT

    , OOD.ORDER_FISCAL_YR
    , OOD.ORDER_ID
    , OOD.ORDER_LINE_NBR

    , OOD.AT_RISK_IND
    , OOD.AT_RISK_DESC

    --, OOD.CUST_PO_NBR
    , OOD.PO_TYPE_ID

    , OOD.ORDER_CAT_ID
    , OOD.ORDER_TYPE_ID

    , OOD.ORDER_DELIV_BLK_CD
    , OOD.SCHD_LN_DELIV_BLK_CD

    , OOD.SHIP_COND_ID
    , OOD.SPCL_PROC_ID
    --, ODS.SPCL_PROC_ID
    , OOD.PROD_ALLCT_DETERM_PROC_ID
    , OOD.CUST_GRP2_CD

    , OOD.SHIP_TO_CUST_ID
    , OOD.CUST_NAME
    , OOD.OWN_CUST_ID
    , OOD.OWN_CUST_NAME

    , OOD.SALES_ORG_CD
    , OOD.SALES_ORG_NAME
    , OOD.DISTR_CHAN_CD
    , OOD.DISTR_CHAN_NAME
    , OOD.CUST_GRP_ID
    , OOD.CUST_GRP_NAME
    , OOD.OE_REPL_IND

    , ODS.REJ_REAS_ID
    , ODS.REJ_REAS_DESC
    , ODS.CANCEL_DT
    , OOD.MATL_ID
    , OOD.MATL_DESCR
    , OOD.PBU_NBR
    , OOD.PBU_NAME
    , OOD.MKT_AREA_NBR
    , OOD.MKT_AREA_NAME
    , OOD.MKT_CTGY_MKT_AREA_NBR
    , OOD.MKT_CTGY_MKT_AREA_NAME
    , OOD.PROD_LINE_NBR
    , OOD.PROD_LINE_NAME

    , OOD.TEST_PRIM_SHIP_FACILITY_ID
    --, OOD.PRIM_SHIP_FACILITY_ID
    , OOD.FACILITY_ID
    , OOD.FACILITY_NAME

    , OOD.SLS_QTY_UNIT_MEAS_ID
    , ZEROIFNULL(OOL.OPEN_CNFRM_QTY)
    , ZEROIFNULL(OOL.UNCNFRM_QTY) 
    , ZEROIFNULL(OOL.BACK_ORDER_QTY) 
    , ZEROIFNULL(OOL.WAIT_LIST_QTY) 

    ) Q

GROUP BY
    Q.DAY_DATE
    , Q.WEEK_OF_MONTH

    , Q.ORDER_TYPE_ID
    , Q.PO_TYPE_ID

    , Q.AT_RISK_IND
    , Q.AT_RISK_DESC

    , Q.ORDER_DELIV_BLK_CD
    , Q.SCHD_LN_DELIV_BLK_CD

    , Q.SHIP_COND_ID
    , Q.SNAP_SPCL_PROC_ID
    , Q.PROD_ALLCT_DETERM_PROC_ID
    , Q.CUST_GRP2_CD

    --, Q.SHIP_TO_CUST_ID
    --, Q.CUST_NAME
    , Q.OWN_CUST_ID
    , Q.OWN_CUST_NAME

    --, Q.REJ_REAS_ID
    --, Q.REJ_REAS_DESC
    --, Q.CANCEL_DT

    --, Q.MATL_ID
    --, Q.MATL_DESCR
    , Q.PBU_NBR
    , Q.PBU_NAME
    , Q.MKT_AREA_NBR
    , Q.MKT_AREA_NAME
    , Q.MKT_CTGY_MKT_AREA_NBR
    , Q.MKT_CTGY_MKT_AREA_NAME
    --, Q.PROD_LINE_NBR
    --, Q.PROD_LINE_NAME

    , Q.TEST_PRIM_SHIP_FACILITY_ID
    --, OOD.PRIM_SHIP_FACILITY_ID
    , Q.FACILITY_ID
    , Q.FACILITY_NAME

    , Q.SLS_QTY_UNIT_MEAS_ID
    --, SUM(Q.SL_OPEN_CNFRM_QTY) AS SNAP_OPEN_CNFRM_QTY

    --, SUM(Q.CURR_OPEN_CNFRM_QTY) AS CURR_OPEN_CNFRM_QTY

    --, SUM(Q.AGID_BEFORE_SNAP_DT_QTY) AS AGID_BEFORE_SNAP_DT_QTY
    --, SUM(Q.AGID_BW_SNAP_AND_EOM_QTY) AS AGID_BW_SNAP_AND_EOM_QTY
    --, SUM(Q.AGID_AFTER_MONTH_QTY) AS AGID_AFTER_MONTH_QTY

    --, SUM(Q.PGMV_BEFORE_SNAP_DT_QTY) AS PGMV_BEFORE_SNAP_DT_QTY
    --, SUM(Q.PGMV_BW_SNAP_AND_EOM_QTY) AS PGMV_BW_SNAP_AND_EOM_QTY
    --, SUM(Q.PGMV_AFTER_MONTH_QTY) AS PGMV_AFTER_MONTH_QTY

    , Q.AGID_TYP_CD

    , Q.AGID_TYP_DESCR
