SELECT
    CAL.DAY_DATE
    , CAL.MONTH_DT
    , ADD_MONTHS(CAL.MONTH_DT, 1) - CAST(1 AS INTERVAL DAY) AS END_OF_MONTH_DT

    , CAL.CAL_YR
    , CAL.CAL_MTH AS MONTH_OF_YEAR
    , CAL.CAL_WK AS WEEK_OF_YEAR
    
    , CAL.DAY_OF_YEAR
    , CAL.DAY_OF_QTR
    , CAL.DAY_OF_MONTH
    , CAL.DAY_OF_WEEK

    , OOL.ORDER_FISCAL_YR
    , OOL.ORDER_ID
    , OOL.ORDER_LINE_NBR
    , OOL.SCHED_LINE_NBR
    
    , OD.SHIP_TO_CUST_ID
    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME
    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME
    
    , OD.FACILITY_ID
    , F.FACILITY_NAME
    
    , OD.MATL_ID
    , M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME

    , OD.ORDER_DT
    , OD.ORDER_CRT_TM
    , OD.ORDER_LN_CRT_DT
    , OD.ORDER_LN_CRT_TM
    , OD.CUST_RDD
    , OD.PLN_MATL_AVL_DT
    , OD.PLN_GOODS_ISS_DT
    , OD.PLN_DELIV_DT
    , CASE
        WHEN OD.PLN_GOODS_ISS_DT BETWEEN CAL.MONTH_DT AND END_OF_MONTH_DT
            THEN 'CM'
        WHEN OD.PLN_GOODS_ISS_DT < CAL.MONTH_DT
            THEN 'PM'
        WHEN OD.PLN_GOODS_ISS_DT > END_OF_MONTH_DT
            THEN 'FM'
        ELSE 'UK'
        END AS PGI_MONTH_CD
    , OD.FRST_MATL_AVL_DT
    , OD.FRST_PLN_GOODS_ISS_DT
    , CASE
        WHEN OD.FRST_PLN_GOODS_ISS_DT BETWEEN CAL.MONTH_DT AND END_OF_MONTH_DT
            THEN 'CM'
        WHEN OD.FRST_PLN_GOODS_ISS_DT < CAL.MONTH_DT
            THEN 'PM'
        WHEN OD.FRST_PLN_GOODS_ISS_DT > END_OF_MONTH_DT
            THEN 'FM'
        ELSE 'UK'
        END AS FRDD_PGI_MONTH_CD
    , OD.FRST_RDD
    , OD.FC_MATL_AVL_DT
    , OD.FC_PLN_GOODS_ISS_DT
    , CASE
        WHEN OD.FC_PLN_GOODS_ISS_DT BETWEEN CAL.MONTH_DT AND END_OF_MONTH_DT
            THEN 'CM'
        WHEN OD.FC_PLN_GOODS_ISS_DT < CAL.MONTH_DT
            THEN 'PM'
        WHEN OD.FC_PLN_GOODS_ISS_DT > END_OF_MONTH_DT
            THEN 'FM'
        ELSE 'UK'
        END AS FCDD_PGI_MONTH_CD
    , OD.FRST_PROM_DELIV_DT

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID
    , OD.PO_TYPE_ID

    , OD.REJ_REAS_ID
    , OD.CANCEL_DT
    , OOL.CREDIT_HOLD_FLG
    , OD.ORDER_DELIV_BLK_cD
    , OD.DELIV_BLK_CD
    , OD.CUST_GRP2_CD
    , OD.SHIP_COND_ID
    , OD.ROUTE_ID
    , OD.DELIV_GRP_CD
    , OD.SPCL_PROC_ID
    , OD.PROD_ALLCT_DETERM_PROC_ID
    , OD.AVAIL_CHK_GRP_CD
    , OD.PRTL_DLVY_CD
    , OD.ORDER_REAS_CD
    , OD.DELIV_PRTY_ID

    , OD.QTY_UNIT_MEAS_ID
    , OD.ORDER_QTY
    , OD.CNFRM_QTY

    , OOL.SLS_QTY_UNIT_MEAS_ID
    , CASE
        WHEN OOL.OPEN_CNFRM_QTY > 0 THEN 'OC'
        WHEN OOL.UNCNFRM_QTY > 0 THEN 'UC'
        WHEN OOL.BACK_ORDER_QTY > 0 THEN 'BO'
        WHEN OOL.DEFER_QTY > 0 THEN 'DF'
        WHEN OOL.IN_PROC_QTY > 0 THEN 'IP'
        WHEN OOL.WAIT_LIST_QTY > 0 THEN 'WL'
        WHEN OOL.OTHR_ORDER_QTY > 0 THEN 'OT'
        ELSE 'UK'
        END AS OPEN_STATUS_CD
    , ZEROIFNULL(OOL.OPEN_CNFRM_QTY) + ZEROIFNULL(OOL.UNCNFRM_QTY) + ZEROIFNULL(OOL.BACK_ORDER_QTY) + ZEROIFNULL(OOL.DEFER_QTY) + ZEROIFNULL(OOL.IN_PROC_QTY) + ZEROIFNULL(OOL.WAIT_LIST_QTY) + ZEROIFNULL(OOL.OTHR_ORDER_QTY) AS OPEN_QTY

FROM NA_VWS.OPEN_ORDER_SCHDLN OOL

    INNER JOIN GDYR_BI_VWS.GDYR_CAL CAL
        ON CAL.DAY_DATE BETWEEN OOL.EFF_DT AND OOL.EXP_DT

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND OD.ORDER_ID = OOL.ORDER_ID
        AND OD.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = OOL.SCHED_LINE_NBR
        AND CAL.DAY_DATE BETWEEN OOL.EFF_DT AND OOL.EXP_DT
        AND OD.ORDER_CAT_ID = 'C'
        AND OD.RO_PO_TYPE_IND = 'N'

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'

WHERE
    CAL.DAY_DATE BETWEEN DATE '2015-01-01' AND DATE '2015-03-31'
    AND M.PBU_NBR = '01'
    AND C.CUST_GRP_ID = '3A'
