SELECT
    DIP.DELIV_FISCAL_YR
    , DIP.DELIV_ID
    , DIP.DELIV_LINE_NBR

    , DIP.ORDER_FISCAL_YR
    , DIP.ORDER_ID
    , DIP.ORDER_LINE_NBR

    , D.BILL_LADING_ID

    , CASE
        WHEN D.PLN_GOODS_MVT_DT < CURRENT_DATE AND TD.CUST_APPT_DT IS NULL
            THEN 'Risk - PGMV in the Past and No Appointment'
        WHEN TD.CUST_APPT_DT IS NOT NULL AND (TD.CUST_APPT_DT - (EXTRACT(DAY FROM TD.CUST_APPT_DT)-1)) > (D.DELIV_DT - (EXTRACT(DAY FROM D.DELIV_DT)-1))
            THEN 'Risk - Customer Set Appointment'
        WHEN D.PLN_GOODS_MVT_DT < CURRENT_DATE
            THEN 'Risk - PGMV in the Past'
        WHEN (D.TERMS_ID = 'W' OR D.SHIP_COND_ID IN ('00', 'LW')) AND OE_REPL_IND = 'Replacement'
            THEN 'Risk - Will-Call'
        WHEN D.DELIV_LINE_FACILITY_ID <> C.PRIM_SHIP_FACILITY_ID AND OE_REPL_IND = 'Replacement'
            THEN 'Risk - Out of Area'
        ELSE 'Expected to GI In Month'
        END AS AT_RISK_IND

    , D.DELIV_CAT_ID
    , D.DELIV_TYPE_ID
    , D.SD_DOC_CTGY_CD

    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME
    , CASE 
        WHEN C.SALES_ORG_CD IN ('N302', 'N312', 'N322') OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD = '32')
            THEN 'OE'
        ELSE 'Replacement'
        END OE_REPL_IND

    , D.MATL_ID
    , M.MATL_NO_8 || ' - ' || M.DESCR AS MATL_DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME

    , CASE
        WHEN D.DELIV_LINE_FACILITY_ID = C.PRIM_SHIP_FACILITY_ID
            THEN 'Primary LC'
        WHEN D.DELIV_LINE_FACILITY_ID LIKE 'N5%'
            THEN 'Factory Direct'
        ELSE 'Out of Area'
        END AS TEST_PRIM_SHIP_FACILITY_ID
    , C.PRIM_SHIP_FACILITY_ID
    , D.DELIV_LINE_FACILITY_ID
    , F.FACILITY_NAME

    , D.QTY_UNIT_MEAS_ID
    , DIP.QTY_TO_SHIP AS IN_PROC_QTY

    , D.DELIV_NOTE_CREA_DT
    , D.DELIV_LINE_CREA_DT
    , D.PLN_GOODS_MVT_DT
    , D.ACTL_GOODS_ISS_DT
    , D.DELIV_DT
    
    , FM.BILL_LADING_ID AS MSTR_BOL
    , FMS.BILL_LADING_ID AS STOP_BOL
    , FMS.FRT_MVMNT_ID
    , FMS.FRT_MVMNT_SCHD_ID
    , FMS.FRT_MVMNT_STOP_ID
    , FMS.STOP_TYP_CD
    , FMS.DEPART_DT
    , FMS.ACTL_ARRV_DT
    , FMS.CARR_APPT_DT
    , FMS.DEPART_TRANSIT_DELAY_ID
    , FMS.ARRV_TRANSIT_DELAY_ID

    , FM.TRANSP_MODE_CD
    , FM.STOP_QTY
    , FM.TM_CARR_ID
    , FM.TRLR_TYP_ID
    , FM.EARLY_DEPART_DT
    , FM.LATE_DEPART_DT
    , FM.BEST_DEPART_DT
    , FM.DOCK_DT
    , FM.TRIP_CMPLT_DT
    , FM.APPT_REQ_IND
    , FM.XDOCK_CD
    , FM.MOV_TYP_ID

    , TD.CUST_APPT_DT
    , TD.CUST_APPT_TM
    , TD.OWN_TXT
    , TD.SRC_UPD_DT
    , TD.SRC_UPD_TM
    , TD.PLN_DELIV_IND
    , TD.SHIP_MODE_CD
    , TD.SHIP_DT
    , TD.SHIP_TM
    , TD.FT_IND
    , TD.CAR_ID
    , TD.SHIP_PRTY_ID
    , TD.EARLY_DELIV_DT
    , TD.LATE_DELIV_DT
    , TD.EARLY_ARRV_DT
    , TD.LATE_ARRV_DT
    , TD.TM_DELIV_STA_CD
    , TD.TM_DELIV_STA_DT
    , TD.TM_DELIV_STA_TM
    , TD.EMRGNCY_CD
    , TD.CNFRM_ID

FROM GDYR_VWS.DELIV_IN_PROC DIP

    INNER JOIN NA_VWS.DELIV_DTL D
        ON D.FISCAL_YR = DIP.DELIV_FISCAL_YR
        AND D.DELIV_ID = DIP.DELIV_ID
        AND D.DELIV_LINE_NBR = DIP.DELIV_LINE_NBR
        AND D.ORIG_SYS_ID = DIP.ORIG_SYS_ID
        AND D.EXP_DT = DIP.EXP_DT
        AND D.ACTL_GOODS_ISS_DT IS NULL
        AND D.PLN_GOODS_MVT_DT <= ADD_MONTHS(CURRENT_DATE-1, 1) - EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE-1, 1))
        --AND D.DELIV_CAT_ID = 'J'
        --AND D.SD_DOC_CTGY_CD = 'C'

    --INNER JOIN NA_BI_VWS.ORD_DTL_SMRY ODS
        --ON ODS.ORDER_FISCAL_YR = DIP.ORDER_FISCAL_YR
        --AND ODS.ORDER_ID = DIP.ORDER_ID
        --AND ODS.ORDER_LINE_NBR = DIP.ORDER_LINE_NBR
        --AND ODS.RO_PO_TYPE_IND = 'N'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = D.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = D.MATL_ID

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = D.DELIV_LINE_FACILITY_ID
        --AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        --AND F.DISTR_CHAN_CD = '81'

    LEFT OUTER JOIN (
        NA_BI_VWS.TM_FRTMV_DLV_XREF_CURR XREF
        
        INNER JOIN NA_BI_VWS.TM_DELIV_CURR TD
            ON TD.TM_DELIV_ID = XREF.TM_DELIV_ID
        
        INNER JOIN NA_BI_VWS.TM_FRT_MVMNT_STOP_CURR FMS
            ON FMS.FRT_MVMNT_ID = XREF.FRT_MVMNT_ID
            AND FMS.FRT_MVMNT_SCHD_ID = XREF.FRT_MVMNT_SCHD_ID
            AND FMS.FRT_MVMNT_STOP_ID = XREF.FRT_MVMNT_STOP_ID
            AND FMS.STOP_TYP_CD = 'DL'
        
        INNER JOIN NA_BI_VWS.TM_FRT_MVMNT_CURR FM
            ON FM.FRT_MVMNT_ID = XREF.FRT_MVMNT_ID
            AND FM.FRT_MVMNT_SCHD_ID = XREF.FRT_MVMNT_SCHD_ID
        ) 
        ON XREF.SAP_DELIV_ID_FISCAL_YR = DIP.DELIV_FISCAL_YR
        AND XREF.SAP_DELIV_ID = DIP.DELIV_ID

WHERE
    DIP.ORIG_SYS_ID = 2
    AND DIP.EXP_DT = CAST('5555-12-31' AS DATE)

    AND (
        C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N302', 'N312', 'N322', 'N307', 'N317', 'N336')
        OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN ('30', '31', '32'))
    )
    AND M.PBU_NBR = '01'
    AND M.MKT_AREA_NBR <> '04'
    AND M.SUPER_BRAND_ID IN ('01', '02', '03', '05')

    AND AT_RISK_IND = 'Risk - PGMV in the Past and No Appointment'

ORDER BY
    DIP.DELIV_FISCAL_YR
    , DIP.DELIV_ID
    , DIP.DELIV_LINE_NBR

    , DIP.ORDER_FISCAL_YR
    , DIP.ORDER_ID
    , DIP.ORDER_LINE_NBR
    
