SELECT
    OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , CASE
        WHEN OD.ORDER_DELIV_BLK_CD > '' OR SCHD_LN_DELIV_BLK_CD > ''
            THEN 'Risk - Delivery / Credit Block Present'
        WHEN ZEROIFNULL(I.TOT_QTY) < SUM(OOL.OPEN_CNFRM_QTY) AND OE_REPL_IND = 'Replacement'
            THEN 'Risk - Current Total Inventory < Confirmed Qty'
        WHEN OD.SHIP_COND_ID IN ('00', 'LW') AND OE_REPL_IND = 'Replacement'
            THEN 'Risk - Will-Call'
        WHEN OD.CUST_GRP2_CD IN ('MAN') AND OE_REPL_IND = 'Replacement'
            THEN 'Risk - Manual Release'
        --WHEN OD.FACILITY_ID <> C.PRIM_SHIP_FACILITY_ID AND OE_REPL_IND = 'Replacement'
            --THEN 'Risk - Out of Area'
        ELSE 'Expected to GI In Month'
        END AS AT_RISK_IND

    , OD.CUST_PO_NBR
    , OD.PO_TYPE_ID

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID

    , OD.ORDER_DELIV_BLK_CD
    , MAX(OD.DELIV_BLK_CD) AS SCHD_LN_DELIV_BLK_CD

    , OD.SHIP_COND_ID
    , OD.SPCL_PROC_ID
    , OD.PROD_ALLCT_DETERM_PROC_ID
    , OD.CUST_GRP2_CD
    , OD.SHIP_TO_CUST_ID

    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME
    , CASE 
        WHEN C.SALES_ORG_CD IN ('N302', 'N312', 'N322') OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD = '32')
            THEN 'OE'
        ELSE 'Replacement'
        END OE_REPL_IND

    , OD.MATL_ID
    , M.MATL_NO_8 || ' - ' || M.DESCR AS MATL_DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME

    , CASE
        WHEN OD.FACILITY_ID IN ('N5US', 'N5CA')
            THEN 'N5US / N5CA'
        WHEN OD.FACILITY_ID = C.PRIM_SHIP_FACILITY_ID
            THEN 'Primary LC'
        WHEN OD.FACILITY_ID LIKE 'N5%'
            THEN 'Factory Direct'
        ELSE 'Out of Area'
        END AS TEST_PRIM_SHIP_FACILITY_ID
    , C.PRIM_SHIP_FACILITY_ID
    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , OD.QTY_UNIT_MEAS_ID
    , SUM(OOL.OPEN_CNFRM_QTY) AS OPEN_CNFRM_QTY
    , ZEROIFNULL(I.AVAIL_TO_PROM_QTY) AS ATP_INV_QTY
    , ZEROIFNULL(I.TOT_QTY) AS TOT_INV_QTY
    , ZEROIFNULL(I.IN_TRANS_QTY) AS IN_TRANS_INV_QTY

    , OD.FRST_MATL_AVL_DT
    , OD.FRST_PLN_GOODS_ISS_DT
    , OD.FRST_RDD
    , OD.FC_MATL_AVL_DT
    , OD.FC_PLN_GOODS_ISS_DT
    , OD.FRST_PROM_DELIV_DT

FROM GDYR_BI_VWS.NGDY

    INNER JOIN NA_BI_VWS.OPEN_ORDER_SCHDLN_CURR OOL

    INNER JOIN NA_BI_VWS.ORDER_DETAIL OD
        ON OD.ORDER_FISCAL_YR = OOL.ORDER_FISCAL_YR
        AND OD.ORDER_ID = OOL.ORDER_ID
        AND OD.ORDER_LINE_NBR = OOL.ORDER_LINE_NBR
        AND OD.SCHED_LINE_NBR = OOL.SCHED_LINE_NBR
        AND OD.EXP_DT = CAST('5555-12-31' AS DATE)
        --AND OD.ORDER_CAT_ID = 'C'
        AND OD.RO_PO_TYPE_IND = 'N'
        AND OD.PLN_GOODS_ISS_DT <= ADD_MONTHS(CURRENT_DATE-1, 1) - EXTRACT(DAY FROM ADD_MONTHS(CURRENT_DATE-1, 1))

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_DESCR_EN_CURR C
        ON C.SHIP_TO_CUST_ID = OD.SHIP_TO_CUST_ID

    INNER JOIN GDYR_BI_VWS.NAT_MATL_HIER_DESCR_EN_CURR M
        ON M.MATL_ID = OD.MATL_ID
        AND M.PBU_NBR = '01'

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = OD.FACILITY_ID
        --AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        --AND F.DISTR_CHAN_CD = '81'

    LEFT OUTER JOIN NA_BI_VWS.FACL_MATL_INV I
        ON I.MATL_ID = OD.MATL_ID
        AND I.FACILITY_ID = OD.FACILITY_ID
        AND I.DAY_DT = CURRENT_DATE-1

WHERE
    (
        C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N302', 'N312', 'N322', 'N307', 'N317', 'N336')
        OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN ('30', '31', '32'))
    )
    AND M.PBU_NBR = '01'
    AND M.MKT_AREA_NBR <> '04'
    AND M.SUPER_BRAND_ID IN ('01', '02', '03', '05')
    AND OE_REPL_IND = 'Replacement'

    AND OOL.OPEN_CNFRM_QTY <> 0

GROUP BY
    OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR

    , OD.CUST_PO_NBR
    , OD.PO_TYPE_ID

    , OD.ORDER_CAT_ID
    , OD.ORDER_TYPE_ID

    , OD.ORDER_DELIV_BLK_CD
    --, MAX(OD.DELIV_BLK_CD) AS SCHD_LN_DELIV_BLK_CD

    , OD.SHIP_COND_ID
    , OD.SPCL_PROC_ID
    , OD.PROD_ALLCT_DETERM_PROC_ID
    , OD.CUST_GRP2_CD
    , OD.SHIP_TO_CUST_ID

    , C.CUST_NAME
    , C.OWN_CUST_ID
    , C.OWN_CUST_NAME

    , C.SALES_ORG_CD
    , C.SALES_ORG_NAME
    , C.DISTR_CHAN_CD
    , C.DISTR_CHAN_NAME
    , C.CUST_GRP_ID
    , C.CUST_GRP_NAME
    , CASE 
        WHEN C.SALES_ORG_CD IN ('N301', 'N311', 'N321', 'N307', 'N317', 'N336') OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD IN ('30', '31'))
            THEN 'Replacement'
        ELSE 'OE'
        END

    , OD.MATL_ID
    , M.MATL_NO_8 || ' - ' || M.DESCR
    , M.PBU_NBR
    , M.PBU_NAME
    , M.MKT_AREA_NBR
    , M.MKT_AREA_NAME
    , M.MKT_CTGY_MKT_AREA_NBR
    , M.MKT_CTGY_MKT_AREA_NAME
    , M.PROD_LINE_NBR
    , M.PROD_LINE_NAME

    , CASE
        WHEN OD.FACILITY_ID IN ('N5US', 'N5CA')
            THEN 'N5US / N5CA'
        WHEN OD.FACILITY_ID = C.PRIM_SHIP_FACILITY_ID
            THEN 'Primary LC'
        ELSE 'Out of Area'
        END
    , C.PRIM_SHIP_FACILITY_ID
    , OD.FACILITY_ID
    , F.FACILITY_NAME

    , OD.QTY_UNIT_MEAS_ID
    --, SUM(OOL.OPEN_CNFRM_QTY) AS OPEN_CNFRM_QTY

    , ZEROIFNULL(I.AVAIL_TO_PROM_QTY) 
    , ZEROIFNULL(I.TOT_QTY)
    , ZEROIFNULL(I.IN_TRANS_QTY) 

    , OD.FRST_MATL_AVL_DT
    , OD.FRST_PLN_GOODS_ISS_DT
    , OD.FRST_RDD
    , OD.FC_MATL_AVL_DT
    , OD.FC_PLN_GOODS_ISS_DT
    , OD.FRST_PROM_DELIV_DT

ORDER BY
    OD.ORDER_FISCAL_YR
    , OD.ORDER_ID
    , OD.ORDER_LINE_NBR
