
SELECT
    CAL.DAY_DATE AS MEAS_DT
    , CASE
        WHEN C.SALES_ORG_CD IN ('N302', 'N312', 'N322') OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD = '32')
            THEN 'OE'
        ELSE 'REPL'
        END AS OE_REPL_IND
    , M.PBU_NBR
    , ZEROIFNULL(SUM(DDC.DELIV_QTY)) AS DELIV_QTY

FROM GDYR_BI_VWS.GDYR_CAL CAL

    LEFT OUTER JOIN (
    NA_BI_VWS.DELIVERY_DETAIL_CURR DDC

    INNER JOIN GDYR_BI_VWS.NAT_MATL_CURR M
        ON M.MATL_ID = DDC.MATL_ID
        AND M.PBU_NBR = '01'

    INNER JOIN GDYR_BI_VWS.NAT_CUST_HIER_CURR C
        ON C.SHIP_TO_CUST_ID = DDC.SHIP_TO_CUST_ID
        AND CASE
        WHEN C.SALES_ORG_CD IN ('N302', 'N312', 'N322') OR (C.SALES_ORG_CD IN ('N303', 'N313', 'N323') AND C.DISTR_CHAN_CD = '32')
            THEN 'OE'
        ELSE 'REPL'
        END = 'REPL'

    INNER JOIN GDYR_BI_VWS.NAT_FACILITY_EN_CURR F
        ON F.FACILITY_ID = DDC.DELIV_LINE_FACILITY_ID
        AND F.SALES_ORG_CD IN ('N306', 'N316', 'N326')
        AND F.DISTR_CHAN_CD = '81'
        )
    ON DDC.ACTL_GOODS_ISS_DT = CAL.DAY_DATE
    AND DDC.DELIV_CAT_ID = 'J'
    AND DDC.SD_DOC_CTGY_CD = 'C'

WHERE
    CAL.DAY_DATE BETWEEN DATE '2014-01-01' AND CURRENT_DATE-1

GROUP BY
    MEAS_DT
    , OE_REPL_IND
    , M.PBU_NBR

ORDER BY
    MEAS_DT
